### ISSUE TITLE
[prometheus] Make a mount which is defined in extraConfigmapMounts optional

### ISSUE THREAD

**Issue by tom932** [prometheus-community/helm-charts#100]
**Is your feature request related to a problem? Please describe.**

We want to mount multiple configmaps as alerting rules via `extraConfigmapMounts`, as described in this comment: https://github.com/helm/charts/issues/9254#issuecomment-443554083
However, one configmap `prometheus-default-alerts` is available by default (managed by the team that sets up prometheus, and is deployed before the helm chart), but another one, `prometheus-alerts`, should only be mounted if it is available (managed by another team). 

Currently, when I deploy prometheus, it cannot start, since the second configmap is not available. (`MountVolume.SetUp failed for volume "server-prometheus-alerts" : configmap "prometheus-alerts" not found`)

Since kubernetes seems to be able to mount configmaps only if they are available, at least stated in https://stackoverflow.com/a/48228418/2286108 , it would be nice if the helm chart would provide this functionality for mounts too.

**Describe the solution you'd like**
It would be great if there would be a flag like show in the code piece below, that would allow to mount configmaps only if they are available:

```
extraConfigmapMounts:
    - name: prometheus-default-alerts
      mountPath: /etc/config/alerts
      configMap: prometheus-default-alerts
      readOnly: true
    - name: prometheus-alerts
      mountPath: /etc/config/alerts
      configMap: prometheus-alerts
      readOnly: true
      optional: true                # <-- this one is new
```

If a similar functionality is already available, please let me know, but I didn't find a hint in values.yaml or in the documentation.

Additionally, this would or example also be a good idea for `alertmanager.configFromSecret` and other places where configmaps/secrets are mounted.

If additional information is required (e.g. current values.yaml), please let me know!
