### ISSUE TITLE
[prometheus-kube-stack] Changes in PrometheusRules are not picked up by helm upgrade

### ISSUE THREAD

**Issue by TheKangaroo** [prometheus-community/helm-charts#1007]
**Describe the bug**
I'm not 100% sure if this is a problem with this chart, the PrometheusRule CRD oder helm itself.
I stumbled upon this while I was testing some alerts and manually changed the `for:` value of an alert to 1min. After I was done testing I run `helm upgrade` to make sure the PrometheusRule are back in the defined state, but the change appears to be not rolled back by the helm upgrade.
My understanding is, that helm would always enforce the defined state in it's templates but aparently this do not seems to be the case for everything.
Is there something I'm missing?

**Version of Helm and Kubernetes**:
```
helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-18T01:10:20Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kube-prometheus-stack

**Which version of the chart**:
16.1.0

**What happened**:
helm does not revert manually changed resources

**What you expected to happen**:
helm enforces the state defined in the templates

**How to reproduce it** (as minimally and precisely as possible):
start kind (or another k8s distro)
install kube-prometheus-stack without any value changes:
```
helm install prometheus prometheus-community/kube-prometheus-stack
```
change a PrometheusRule, e.g. I set the KubeNodeNotReady to 1min:
```
kubectl get prometheusrules.monitoring.coreos.com prometheus-kube-prometheus-kubernetes-system-kubelet -oyaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
[...]
spec:
  groups:
  - name: kubernetes-system-kubelet
    rules:
    - alert: KubeNodeNotReady
      annotations:
        description: '{{ $labels.node }} has been unready for more than 15 minutes.'
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubenodenotready
        summary: Node is not ready.
      expr: kube_node_status_condition{job="kube-state-metrics",condition="Ready",status="true"}
        == 0
      for: 1m # <- here
      labels:
        severity: warning
```
Run 
```
helm upgrade prometheus prometheus-community/kube-prometheus-stack
```
The PrometheusRule is not reset to the chart template value (https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml#L33)
