### ISSUE TITLE
[kube-prometheus-stack] password and other secret values are plaintext in values.yaml

### ISSUE THREAD

**Issue by hammadzz** [prometheus-community/helm-charts#1020]
**Is your feature request related to a problem? Please describe.**
I am not happy with having to add secret values as plaintext for grafana password, slack webhooks, etc. It can accidentally end up in git and is hard to version control.

**Describe the solution you'd like**
It would be wonderful if I could specify a kubernetes secret name to be used in place instead. 

So instead of specifying `grafana.password` as plaintext, you would specify `grafana.passwordSecret` with a reference to a kubernetes secret.

**Describe alternatives you've considered**
Another alternative is support for [kubernetes external secrets](https://github.com/external-secrets/kubernetes-external-secrets) and be able to specify an external source to populate the secret. I love this tool but feel it maybe too hopeful that it would get integrated.

**Comment by monotek** [comment]
Use the exisitinSecret feature of the charts.

You could use [sops](https://github.com/mozilla/sops), to store encrypted passwords in git.

Other options would be:
* https://github.com/bitnami-labs/sealed-secrets
* https://github.com/kubevault/operator

**Comment by yacinelazaar** [comment]
@monotek 
So If the alertmanager config has something like this:
```
global:
  smtp_smarthost: 'smtp.sendgrid.net:587'
  smtp_from: 'Swarm Alerts <ALERTING_EMAIL>'
  smtp_auth_username: 'apikey'
  smtp_auth_password: '<API KEY HERE>' 
```
If i want to protect the API key, should I mount the whole config as a secret?

**Comment by monotek** [comment]
Depends on the chart. 
Some charts support usage of already exisitng secrets in the cluster.
Example: https://github.com/prometheus-community/helm-charts/blob/5f760a0645623e3e3e401418d26dfcb06f024949/charts/prometheus-mysql-exporter/values.yaml#L120

If the chart does not support it yet, you might want to create a pull request to add it.

**Comment by yacinelazaar** [comment]
Lets take the kube-prometheus-stack chart as an example.
If i set the API key as a secret and mount is using the chart"s `exisitinSecret` and `secrets` values when applying the chart, I wont be able to reference it the alertmanager config since it takes an actual value and cannot load from a mounted file.

**Comment by Poweranimal** [comment]
What about passing the value by calling helm?
Do:
```
config:
  global:
    smtp_smarthost: 'smtp.sendgrid.net:587'
    smtp_from: 'Swarm Alerts <ALERTING_EMAIL>'
    smtp_auth_username: 'apikey'
    smtp_auth_password: '{{ required "A valid smtp auth password is required" .Values.smtp_auth_password }}'
tplConfig: true
```
And then call: `helm install debug some-helm-file --set smtp_auth_password=1234567890`

**Comment by hammadzz** [comment]
The suggestion above by @Poweranimal seems to be the best stop gap measure for my use case.

But I still hope to make a PR to support K8s secrets out of the box in this template's values file.

**Comment by AhmedGrati** [comment]
For alertmanager, to pass password and critical information as secrets it's possible by specifying that you're using an existing secret that you create manually on your cluster. the `values.yaml` would look like this:
```yaml
kube-prometheus-stack:
  ## Provide a name to substitute for the full names of resources
  ##
  fullnameOverride: "prometheus-stack"
  alertmanager:
    enabled: true
    alertmanagerSpec:
      useExistingSecret: true
      secrets:
        - alertmanager-prometheus-stack-alertmanager
```
## Note:
The secret name should follow this patter:
`alertmanager-{{fullname}}-alertmanager`
In my case I've overrode the fullname so my referenced secret is `alertmanager-prometheus-stack-alertmanager`.
<br>
Then you should create an `alertmanager.yaml` configuration file which looks like this:
```yaml
global:
  resolve_timeout: 1m
route:
  group_by: [ 'service' ]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
# Essential to create alertmanager pod
  receiver: 'null'
  routes:
    - match:
        alertname: Watchdog
# Essential to create alertmanager pod
      receiver: 'null'
    - match:
        service: static-assets-sync
      receiver: 'dev-team'
receivers:
  - name: 'null'
  - name: 'dev-team'
    email_configs:
      - to: xxxxxxxx
        from: xxxxxxx
        smarthost: smtp.gmail.com:587
        auth_username: xxxxxxx
        auth_identity: xxxxxxxxxxxxxx
        auth_password: xxxxxxx
        require_tls: true
        send_resolved: true
```
After that, you should create the secret which should have the same name as the one mentioned in the `values.yaml` file.
the command is:
`kubectl create secret generic -n monitoring alertmanager-prometheus-stack-alertmanager --from-file=alertmanager.yaml`

**Comment by didil** [comment]
For the smtp password I used the approach from this SO answer https://stackoverflow.com/questions/74254241/how-to-insert-a-secret-in-alertmanager-configuration-file ie setting the password in a secret, mounting the secret as a file then using `global.smtp_auth_password_file`

**Comment by davidB** [comment]
Some secret could be read from file like `credentials_file` for `http_config` of receivers. So the secret can be mounted as a volume.

```yaml
    alertmanagerSpec:
      volumes:
        - name: secret-kube-prometheus-stack
          secret:
            secretName: kube-prometheus-stack
            defaultMode: 420
      volumeMounts:
        - name: secret-kube-prometheus-stack
          mountPath: /etc/alertmanager/secrets/kube-prometheus-stack/
          readOnly: true
    config:
      receivers:
        - name: "null" # used by route for "InfoInhibitor|Watchdog"
        - name: my-alerts
          slack_configs:
            - api_url: "https://slack.com/api/chat.postMessage"
              #...
              http_config:
                authorization:
                  credentials_file: /etc/alertmanager/secrets/kube-prometheus-stack/MY_SLACK_TOKEN
```
