### ISSUE TITLE
[prometheus-blackbox-exporter] Explicit securityContext.runAsUser breaks deployment on Red Hat OpenShift 

### ISSUE THREAD

**Issue by CoaxVex** [prometheus-community/helm-charts#1036]
The prometheus-blackbox-exporter deployment template explicitly sets the **runAsUser** option, which does not work on OpenShift. OpenShift dynamically generates a uid to run the container.

```
Events:
  Type     Reason        Age                From                   Message
  ----     ------        ----               ----                   -------
  Warning  FailedCreate  9s (x13 over 30s)  replicaset-controller  Error creating: pods "blackbox-exporter-c9d95fb98-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000640000, 1000649999]]
```

These ranges are generated dynamically for each namespace, so just specifying a runAsUser in the above range is not what you'd want to do because then your configuration will only work on one namespace/cluster.

What usually happens in other charts, is that the entire securityContext can be overriden through values.yaml. On OpenShift, you then just set it to **null** to let OpenShift fill it in itself.

For example, when you run "helm create", the following is written to the example deployment.yaml:

```
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

```

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

```

Kubernetes Version:

```console
$ oc version
Client Version: 4.6.21
Server Version: 4.7.12
Kubernetes Version: v1.20.0+df9c838
```

**Which chart**:  prometheus-blackbox-exporter 

**Which version of the chart**: 4.13.0

**What happened**: ReplicaSet is unable to create pod

**What you expected to happen**: A configuration option which allows me to set the securityContext to null

**How to reproduce it** (as minimally and precisely as possible):

```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm install my-release prometheus-community/prometheus-blackbox-exporter
oc describe rs my-release-prometheus-blackbox-exporter-68d57d568f
```

**Comment by CoaxVex** [comment]
Just figured out I could make it work by setting **runAsUser** to null. I guess that's sufficient as a workaround.

**Comment by Thorndike** [comment]
This workaround only works if you deploy the chart directly. If the chart is included as a dependency then helm seems to still ignore null values.
In that case a switch would be helpful.

**Comment by CoaxVex** [comment]
> This workaround only works if you deploy the chart directly. If the chart is included as a dependency then helm seems to still ignore null values. In that case a switch would be helpful.

If you load the chart as a dependency, you can set the _null_ value like this in your values file:

```
prometheus-blackbox-exporter:
  runAsUser: null
```

**Comment by Thorndike** [comment]
I tried 


prometheus-blackbox-exporter:
&nbsp;&nbsp;securityContext:
&nbsp;&nbsp;&nbsp;&nbsp;runAsUser: null


Which is not working although 

prometheus-blackbox-exporter:
&nbsp;&nbsp;securityContext:
&nbsp;&nbsp;&nbsp;&nbsp;runAsUser: 1001

is just working fine so I assume my syntax is basically correct.

**Comment by Thorndike** [comment]
It has been recognized as a bug by helm contributors
[12741](https://github.com/helm/helm/issues/12741)

**Comment by dwrolvink** [comment]
According to that bug and the listed PR's the issue has been fixed. However, it seemingly resurfaced between version 3.17.0 and 3.17.1, then there are legion bug reports (various projects, all the same helm issue) from 2025 onwards, all without reply/autoclosed. In short, for me on version 4.2.0 it doesn't work currently.

Working with ArgoCD, the only way I've managed to fix this is by using helm parameters directly in the Application CR:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-monitoring-{{ .Values.cluster.name }}
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: openshift-monitoring
spec:
  project: default
  sources:
    - repoURL: {{ $openshiftMonitoringService.repoURL }}
      targetRevision: {{ $openshiftMonitoringService.revision | quote }}
      path: ./chart
      helm:
        releaseName: openshift-monitoring
        valueFiles:
          - values.yaml
        parameters:                                                                                # <========
          - name: prometheus-blackbox-exporter.securityContext                                     # <========
            value: "null"                                                                          # <========
```

It would be nice to if an option was provided to null the securitycontext out of the box, or even make the default `{}`.
