### ISSUE TITLE
kube-state-metrics  servicemonitor No Relabelings

### ISSUE THREAD

**Issue by QAQ-rookie** [prometheus-community/helm-charts#1039]
**Is your feature request related to a problem? Please describe.**

I use helm to install kube-state-metrics, but servicemonitor does not provide relabelings;

**Describe the solution you'd like**

I hope add relabelings in kube-state-metrics servicemonitor, so we can custom relabels in helm values.yaml

**Describe alternatives you've considered**

**Additional context**

Servicemonitor templeate:
```
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "kube-state-metrics.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints: 
   - port: http
     {{- if .Values.prometheus.monitor.honorLabels }}
     honorLabels: true      
     {{- end }}
   {{ if .Values.selfMonitor.enabled }}
  - port: metrics 
     {{- if .Values.prometheus.monitor.honorLabels }}
     honorLabels: true
     {{- end }}
  {{ end }}
```
   
How we use servicemonitor:
```
spec:
  endpoints:
  - honorLabels: true
    port: http
    relabelings:
    - action: labeldrop
      regex: (pod|service|endpoint|namespace)
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-state-metrics
      app.kubernetes.io/name: kube-state-metrics
```
