### ISSUE TITLE
[prometheus-kube-stack] field mute_time_intervals not found in type config.plain

### ISSUE THREAD

**Issue by eugenberend** [prometheus-community/helm-charts#1047]
**Describe the bug**
The field `mute_time_intervals` (which is new to alertmanager 0.22) is not recognized by prometheus-operator.

**Version of Helm and Kubernetes**:

Helm Version:

```console
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

Kubernetes Version:

```console
$ kubectl version
please put the output of it here
```

**Which chart**: prometheus-kube-stack

**Which version of the chart**: 15.0.0

**What happened**:

* put `mute_time_intervals` to alertmanager config values
* the error was logged in prometheus-operator pod:

```console
level=error ts=2021-06-07T11:17:37.786715076Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"prometheus-operator-alertmanager" failed: provision alertmanager configuration: base config from Secret could not be parsed: yaml: unmarshal errors:\n line 80: field mute_time_intervals not found in type config.plain\n 
```

**What you expected to happen**:

* working `mute_time_intervals` in alertmanager config

Here is part of our alertmanager config:

```
  config:
    mute_time_intervals:
      - name: out_of_business_hours
        time_intervals:
          - weekdays: ['monday':'friday']
            times:
            - start_time: '18:00'
              end_time: '22:00'
    route: ...
```

**Anything else we need to know**:

Alertmanager v0.22.2
Prometheus v2.27.1

I suggest it is because the schema in the `alertmanagerconfig` CRD simply does not contain such field.
