### ISSUE TITLE
add all\custom namespaces to monitoring kube-prometheus-stack

### ISSUE THREAD

**Issue by symanovich-a** [prometheus-community/helm-charts#106]
Hi team, 
I wasn't able to find how to add all metrics from different namespaces to monitoring. It looks like only metrics in deployment 
 namespace with kube-system and default were added
All services in custom namespaces were added successfully with **additionalServiceMonitors** section, but how may i add non services metrics - volumes, ingress etc. I tried  this part in values.yaml  _## Namespaces to scope the interaction of the Prometheus Operator and the apiserver (allow list)_ but without success.
I found only this workaround https://github.com/prometheus-operator/kube-prometheus#adding-additional-namespaces-to-monitor and found this solution https://github.com/prometheus-operator/prometheus-operator/issues/2890#issuecomment-583006452
but it doesn't help. Should i create role and rolebinding  in every necessary namespace or something else?

eks 1.17
prometheus-operator-9.3.0
app version 0.38.1 
Thank you in advance.

**Comment by jwenz723** [comment]
I think you would want to add something like the following into your helm values. This will allow kube-prometheus-stack to automatically discover PodMonitor, Rule, and ServiceMonitor objects in any namespace.

```yaml
prometheus:
      prometheusSpec:
        podMonitorNamespaceSelector:
          any: true
        podMonitorSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        ruleNamespaceSelector:
          any: true
        ruleSelector: {}
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelector:
          any: true
        serviceMonitorSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
```
