### ISSUE TITLE
[kube-prometheus-stack] Service monitor for kube-state-metrics seems to be breaking dashboards

### ISSUE THREAD

**Issue by amnk** [prometheus-community/helm-charts#1068]
**Describe the bug**
[Default port](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/exporters/kube-state-metrics/serviceMonitor.yaml#L13) for kube-state-metrics ServiceMonitor object is pointing to self-metrics. [`http`](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/templates/service.yaml#L24) seems to be the endpoint that exposes `kube_pod_info` and other metrics that dashboards use. 

**Which chart**: `kube-prometheus-stack`

**Which version of the chart**: `16.7.0`

**What happened**: with default values in use, `kube-prometheus-stack` should deploy working ServiceMonitors.

**What you expected to happen**: `kube-state-metrics` ServiceMonitor points to a non-existing port, thus this ServiceMonitor object is nor regognized by prometheus-operator.

**Anything else we need to know**: I have fixed this setup by deploying custom ServiceMonitor:
```
  additionalServiceMonitors:
    - name: "kube-state-metrics-custom"
      endpoints:
      - honorLabels: true
        targetPort: 8080
      jobLabel: app.kubernetes.io/name
      selector:
        matchLabels:
          app.kubernetes.io/instance: kube-prometheus-stack
          app.kubernetes.io/name: kube-state-metrics
```
without changing anything else. A PR should either update ServiceMonitor object to use `targetPort: 8080`, or to use `http`. `metrics` port in kube-state-metrics is used to emit own metrics. If it is used, some of the dashboards are not working properly, since they rely on `kube_pod_info` metrics which are not exposed with that endpoint. Either there should be a separate ServiceMonitor, or dashboards should be updated.
