### ISSUE TITLE
[prometheus-kube-stack] prometheus server service wrong selector (live upgraded to 16.8.0)

### ISSUE THREAD

**Issue by dennybaa** [prometheus-community/helm-charts#1082]
My selector is
```
Selector:          app=prometheus,prometheus=prometheus-kube-prometheus-prometheus
```

which doesn't match to those values set by chart.

**Comment by jcobb48** [comment]
Simillar issue over here, installed the chart from scratch in a brand new cluster and prometheus service had these selectors:

Service > prometheus-kube-prometheus-prometheus 
Selectors > app.kubernetes.io/name=prometheus,prometheus=prometheus-kube-prometheus-prometheus

Helm install: 
`helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --values values.yaml
`

Grafana could not connect to prometheus DS, checked the statefulset and it did not have the label "app.kubernetes.io/name=prometheus"

STS labels:
```
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/managed-by: Helm
    chart: kube-prometheus-stack-14.0.1
    heritage: Helm
    operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
    operator.prometheus.io/shard: "0"
    release: prometheus

```
Just removed label " app.kubernetes.io/name=prometheus" from service selector, that solved the issue.

Seems that the chart is adding the helm release name to the service labels, but not to the statefulset.
