### ISSUE TITLE
[prometheus-kube-stack] alertmanager pod not created while configuring alertmanager from custom values.yaml file

### ISSUE THREAD

**Issue by saiprakash-v** [prometheus-community/helm-charts#1096]
I'm using the latest version of helm chart, minikube `v1.16.0`,  kubectl `v1.20.0`

I'm trying to install prometheus-kube-stack chart with a custom values.yaml file 

I ran this:
`helm install prometheus prometheus-community/kube-prometheus-stack -f custom_values.yaml`

Contents of custom_values.yaml
```
additionalPrometheusRulesMap:
  - groups:
    - name: custom_rules
      rules:
        - record: node_memory_MemFree_percent
          expr: 100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes)
    - name: alert_rules
      rules:
        - alert: InstanceDown
          expr: up == 0
          for: 15s
          labels:
            severity: critical
          annotations:
            summary: "Instance [{{ $labels.instance }}] down"
            description: "[{{ $labels.instance }}] of job [{{ $labels.job }}] has been down for more than 1 minute."

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      receiver: 'post-webhook'
      group_interval: 30s
      repeat_interval: 30s
    receivers:
    - name: 'post-webhook'
      webhook_configs:
      - url: <my-post-url>
```

After running this, I ran `kubectl get pod` and the list doesn't have any alertmanager pod

But if I just install helm chart without passing any custom config file, pod gets created.

Am I doing something wrong? or is it a bug?

**Comment by nelaaro** [comment]
I can confirm that I have seen the same behavior.

Additionally, the statefulset for the alertmanger is not created if the custom configuration is loaded.

The secrets volume takes on a different name

In the statefulset for alertmanger created with no alertmanger configuration.

```
kind: StatefulSet
  name: alertmanager-kube-prometheus-stack-alertmanager
...
      volumes:
      - name: config-volume
        secret:
          defaultMode: 420
          secretName: alertmanager-kube-prometheus-stack-alertmanager-generated
...
```

This is different than the secret generated by the custom configuration

Which has the following name

```
kubectl get secret -n kube-prom-stack
NAME                                                         TYPE                                  DATA   AGE
alertmanager-kube-prometheus-stack-alertmanager              Opaque                                1      38h
alertmanager-kube-prometheus-stack-alertmanager-generated    Opaque                                1      15m
```

So a workaround would be to apply your custom config secret with the -generated suffix.
This is currently how I am making changes. It is defiantly not how the values and helm chart deployment should work.

This one was really confusing for me. 
Nothing in the helm chart. No statefulset, no secret-generated templates.
So this is being automagically created somewhere else in the alertmanger / operator / CDR this makes things a lot more difficult to debug and change. 

I have not see where the statefulset deployment and secret-genreated are created. I will update if I find this to assist in building a patch to fix. To ensure that values loaded into helm produce the expected resultlts
