### ISSUE TITLE
[prometheus-kube-stack] PodMonitor created outside of helm is ignored

### ISSUE THREAD

**Issue by tringuyen-yw** [prometheus-community/helm-charts#1097]
**Describe the bug**
PodMonitor created outside of the helm chart is not picked up by Prometheus. However when added as helm value `prometheus.additionalPodMonitors` it is visible in the Prometheus server UI http://my-prom-server:9190/targets

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version

version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

Kubernetes Version:
**Server: Azure AKS, Kubernetes v1.19.11**

```console
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", GitTreeState:"clean", BuildDate:"2021-05-13T17:14:18Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: kube-prometheus-stack 

**Which version of the chart**: 16.10.0

**What happened**:

This PodMonitor is NOT recognized by the Prometheus service (not visitble in http://my-prom-server:port/targets)

```yaml
# PodMonitor CRD outside of prometheus-kube-stack helm values
kubectl apply -f - << EOF
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cluster-operator-metrics
  labels:
    app: strimzi
spec:
  selector:
    matchLabels:
      strimzi.io/kind: cluster-operator
  namespaceSelector:
    matchNames:
      - strimzi
  podMetricsEndpoints:
  - path: /metrics
    port: http
EOF
```
**What you expected to happen**:

[charts/kube-prometheus-stack/values.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2068) states:

```
    ## PodMonitors to be selected for target discovery.
    ## If {}, select all PodMonitors
    ##
    podMonitorSelector: {}
```

As such the PodMonitor created in the "What happened" section should be picked up by the Prometheus instance. However when the custom `podmonitor` is defined as helm values, it works correctly (show up as target in Prometheus UI)

my-Extra-PodMonitor-values.yaml

```console
prometheus:
  additionalPodMonitors:
  - name: strimzi-cluster-operator-metrics
    additionalLabels:
      app: strimzi
    selector:
      matchLabels:
        strimzi.io/kind: cluster-operator
    namespaceSelector:
      matchNames:
        - strimzi
    podMetricsEndpoints:
      - path: /metrics
        port: http

  - name: kafka-entity-operator-metrics
    additionalLabels:
      app: strimzi
    selector:
      matchLabels:
        app.kubernetes.io/name: entity-operator
    namespaceSelector:
      matchNames:
        - kafka
    podMetricsEndpoints:
      - path: /metrics
        port: healthcheck
```
Then apply by

```console
helm upgrade my-kubpromstack prometheus-community/kube-prometheus-stack -n monitoring \
  --version version 16.10.0 \
  --reuse-values \
  -f my-Extra-PodMonitor-values.yaml
```

**QUESTION**: Maybe this is not a bug, but is simply a misconfiguration somewhere in my standalone PodMonitor CRD (missing label or annotation?). If this is the case, can you please give the answer here and possibly update the documentation [Include PodMonitors](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#include-podmonitors) ?

**NOTE**: the issue described here also apply to `PrometheusRules` ie. a `PrometheusRule` created independently is not picked up by Prometheus. Must be created via helm values `additionalPrometheusRulesMap.kafka-alert-rules`. Not sure if I should file a separate issue. Please suggest. Thanks
