### ISSUE TITLE
[prometheus-blackbox-exporter] Bug with module http_2xx on 0.17.0

### ISSUE THREAD

**Issue by gillg** [prometheus-community/helm-charts#110]
With default values at https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/values.yaml#L55 :

```yaml
http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2"]
        no_follow_redirects: false
        preferred_ip_protocol: "ip4"
```

There is a bug on probe if protocol is HTTP 2 on target.

The new good syntax is "HTTP/2.0"

Solution source : https://github.com/prometheus/blackbox_exporter/issues/651
