### ISSUE TITLE
[kube-prometheus-stack] Can't deploy properly when using tolerations on nodes

### ISSUE THREAD

**Issue by douchet-pa** [prometheus-community/helm-charts#1127]
**Describe the bug**
No deployment when the nodes have a taint

**Version of Helm and Kubernetes**:

Helm Version:
```console
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```

Kubernetes Version:
```console
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"9a45ba1752db920873e084791faff8d470278b09", GitTreeState:"clean", BuildDate:"2021-05-19T22:28:02Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kube-prometheus-stack
**Which version of the chart**:
13.9.1
**What happened**:
a pod is stuck in Pending because of the taint

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
alertmanager:
    config:
      global:
        smtp_smarthost: "xxxxxxxxxx"
        smtp_auth_username: "xxxxxxxxxx"
        smtp_auth_password: "xxxxxxxxxx"
        smtp_from: "xxxxxxxxxx"
    alertmanagerSpec:
      alertmanagerConfigSelector:
        matchLabels:
          alertmanagerconfig: ips
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    priorityClassName: "high-priority"
    retention: 120h
    storage: 
      volumeClaimTemplate:
        spec:
          storageClassName: azurefile
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    resources: 
      requests:
        memory: 400Mi

grafana:
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  adminPassword: "xxxxxxxxxx"
  plugins:
    - grafana-piechart-panel
    - camptocamp-prometheus-alertmanager-datasource
  persistence:
    storageClassName: managed-standard
    enabled: true
    accessModes: ["ReadWriteOnce"]
    size: 50Gi
  grafana.ini: 
    server:
      domain: xxxxxxxxxx
      enable_gzip: true
    smtp:
      enabled: true
      host: "xxxxxxxxxx"
      from_address: "xxxxxxxxxx"
      from_name: "xxxxxxxxxx"
      user: "xxxxxxxxxx"
      password: "xxxxxxxxxx"
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard  
      folder: /tmp/dashboards
      provider: 
        foldersFromFilesStructure: true
      annotations: 
        k8s-sidecar-target-directory: "/tmp/dashboards/Kubernetes"
    datasources:
      enabled: true    
      label: grafana_datasource
    notifiers:
      enabled: true
      label: grafana_notifier
prometheusOperator:
  admissionWebhooks:
    patch:
      priorityClassName: "high-priority"
  priorityClassName: "high-priority"
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

prometheus:
  prometheusSpec:
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    priorityClassName: "high-priority"
    retention: 60d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: azurefile
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 200Gi
    resources: 
      requests:
        memory: 400Mi
        
kube-state-metrics:
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
```

**The helm command that you execute and failing/misfunctioning**:

```console
helm install kps -n monitoring prometheus-community/kube-prometheus-stack --version 13.9.1 -f values.yaml
```

**Anything else we need to know**:
We're using AKS (Azure Kubernetes Service) and we're put taint on our nodepools. When we deploy kube-prometheus-stack, the first pod created is stuck in Pending because we can add the tolerations (the pod name is _kps-kube-prometheus-stack-admission-create-pqp8d_ in our case, _kps_ is the name of our helm release). We have to add manually our taint in the pod tolerations by editing it manually to let the pod deploy the stack. And after that, the pods are deployed but there's still one pod in Pending (the pod name is _kps-kube-prometheus-stack-admission-patch-5xgp2_) with the same issue (our taint isn't in the pod tolerations). And as previously, when we add the taint manually, the pod goes normally.

**Comment by douchet-pa** [comment]
Hi,

We still got no solution for this issue.
Is someone have a solution ?

Thanks,

**Comment by douchet-pa** [comment]
Hi,

We still got no solution for this issue on our side.
Nobody encounter this kind of configuration ?

Thanks,

**Comment by bshea5** [comment]
I'd like this issue re-opened. I'm experiencing the same issue as above, also on AKS.

**Comment by zeritti** [comment]
I understand that the problem is about the admissionWebhooks' create and patch jobs. Tolerations for these can still be set in values:
```
prometheusOperator:
  admissionWebhooks:
    patch:
      tolerations: []
```
This configuration applies to both jobs. Would this help?

**Comment by bshea5** [comment]
Doesn't seem to work. This is what I tried:
``` yaml
prometheusOperator:
  enabled: true
  admissionWebhooks:
    patch:
      tolerations:
        - key: "<key>"
          operator: "Equal"
          value: "monitoring"
          effect: "NoSchedule"
```

I only see the following tolerations defined on the pod when I deploy:
```
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s                                                                                                                                                     
                                    node.kubernetes.io/unreachable:NoExecute op=Exists for 300s   
```

**Comment by zeritti** [comment]
I cannot unfortunately confirm the same result. If I add the following to my values (chart v43.2.1, k8s 1.25.5, not AKS, though):
```
prometheusOperator:
  enabled: true
  tls:
    enabled: true
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
```
then e.g. the `create` pod (job-name=kube-prometheus-stack-admission-create) shows at runtime the following tolerations:
```
    tolerations:
    - effect: NoSchedule
      key: CriticalAddonsOnly
      operator: Equal
      value: "true"
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
```
Unfortunately, I do not have an AKS cluster to check at the moment.
