### ISSUE TITLE
prometheus-kube-stack - no metrics scraped when installing on different namespace

### ISSUE THREAD

**Issue by winaterion** [prometheus-community/helm-charts#1133]
**Describe the bug**
I run 
`helm install stable prometheus-community/kube-prometheus-stack -n monitoring -f .\values.yaml`
not getting all k8s basic metrics like kube_pod_info and much more. Also, I have my own app service which is deployed with the following yaml:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: my-exp
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8090'
```
When i run curl locally on this service, I get the pods, but when I check if the metrics exists in prometheus, I can't find any of them. seems like promethues doesn't check other namespaces. 
NOTE: promethues was deployed on "monitoring" namespace...

**Version of Helm and Kubernetes**:

Helm Version:
```console
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Kubernetes Version:

```console
1.19.11
```

**Which chart**:
kube-prometheus-stack

**Which version of the chart**:
16.7.0
