### ISSUE TITLE
[prometheus_statsd] Mapping config changes do not take effect without explicit pod restart

### ISSUE THREAD

**Issue by yuvipanda** [prometheus-community/helm-charts#1153]
**Describe the bug**

Any changes to `statsd.mappingConfig` do not take effect unless the prometheus_statsd part is explicitly deleted and recreated. This makes sense, since prometheus_statsd only reloads config on `SIGHUP`.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

Kubernetes Version:

```console
$ kubectl version
please put the output of it here
```

**Which chart**: prometheus-statsd-exporter

**Which version of the chart**: 0.3.1

**What happened**:  Doing a deploy with changes to `statsd.mappingConfig` was a no-op until prometheus-statsd was restarted

**What you expected to happen**: Changes to `statsd.mappingConfig` are applied after helm upgrade.

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
  statsd:
    mappingConfig: |-
      mappings:
      - match: "something.*"
        name: "something_metric"
        labels:
          variable: "$1"
```

**The helm command that you execute and failing/misfunctioning**:

```console
helm upgrade --install --wait   --namespace=support support support/
```

`support` depends on the prometheus-statsd chart

```yaml
dependencies:
 - name: prometheus-statsd-exporter
   version: 0.3.1
   repository: https://prometheus-community.github.io/helm-charts
 - name: prometheus
   version: 11.16.9
   repository: https://prometheus-community.github.io/helm-charts
 - name: grafana
   version: 6.2.1
   repository: https://grafana.github.io/helm-charts
 - name: cert-manager
   version: v1.1.0
   repository: https://charts.jetstack.io
 - name: ingress-nginx
   version: 3.23.0
   repository: https://kubernetes.github.io/ingress-nginx
```
