### ISSUE TITLE
[prometheus-node-exporter] Need more flexibility around sidecars and sidecar volume mounts

### ISSUE THREAD

**Issue by tillig** [prometheus-community/helm-charts#1163]
**Is your feature request related to a problem? Please describe.**

In the current version of the `prometheus-node-exporter` chart, there's a lot of very segmented controls around how you define sidecar volumes and volume mounts. Unfortunately, this means you can't define a volume that comes from the downward API, nor can you define a projected service account token volume.

A specific example is when trying to mount an Istio sidecar into the node exporter. This is useful if you want to take advantage of the Istio certificate authority and rotation for mTLS communications and not have to manage it yourself.

The Istio Envoy sidecar needs a service account token volume mounted and also takes advantage of the downward API to get additional information. The `volumes` YAML looks like this:

```yaml
    - name: istio-token
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
    - name: istio-pod
      downwardAPI:
        defaultMode: 420
        items:
          - path: labels
            fieldRef:
              fieldPath: metadata.labels
          - path: annotations
            fieldRef:
              fieldPath: metadata.annotations
```

Unfortunately these aren't configmaps, secrets, or in-memory volumes, but that's really all the current chart supports.

Further, the version of the `prometheus-node-exporter` chart that's _in the main `prometheus` chart_ doesn't include the sidecar support like this at all.

**Describe the solution you'd like**

It would be helpful if the sidecar support was less "specific." For example, in the main Prometheus server chart, you can define your sidecar YAML and it's expected to just include the sidecar volume mounts - you can set that up as part of the overall sidecar. You can also define `extraVolumeMounts` and whatnot as needed, so you're not limited in what gets defined or how.

It'd be nice to see sidecar support for node exporter be more open like this, though I recognize that could be a pretty major breaking change for current chart users.

**Describe alternatives you've considered**

There isn't really any alternative. I could fork the chart and own it myself, but that's about it.

**Additional context**

This somewhat goes along with #1161 where the Pushgateway chart doesn't have sidecar support at all. It might be worth unifying the manner in which sidecars are handled across all charts so it's consistent.
