### ISSUE TITLE
[HELP] PVC is not created for manually created PV

### ISSUE THREAD

**Issue by theadzik** [prometheus-community/helm-charts#1164]
I have a similar problem as described in this issue: [Issue](https://github.com/prometheus-community/helm-charts/issues/186) but the solution doesn't seem so trivial...

I'm using chart kube-prometheus-stack, version: 16.13.0 (I also tried 16.12.1 before). I have a managed azure-disk that I want to use for storage. I created a managed disk in azure and PV for it:

My PV:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-prometheus
  selfLink: /api/v1/persistentvolumes/monitoring-prometheus
  labels:
    app: monitoring-prometheus
spec:
  accessModes:
  - ReadWriteOnce
  azureDisk:
    cachingMode: None
    diskName: monitoring-prometheus-staging
    diskURI: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/monitoring-rg/providers/Microsoft.Compute/disks/monitoring-prometheus-staging
    fsType: ""
    kind: Managed
    readOnly: false
  capacity:
    storage: 15Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-standard
  volumeMode: Filesystem
status:
  phase: Available
```

After reading [this](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/storage.md) I created a custom storage class but it did not affect PVC creation. I tried creating labels and selectors as described in the above link as well. No luck.

StorageClass:

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-standard
  selfLink: /apis/storage.k8s.io/v1/storageclasses/managed-standard
parameters:
  kind: managed
  storageaccounttype: Standard_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

values.yaml:
```
prometheusOperator:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          selector:
            matchLabels:
              app.kubernetes.io/name: monitoring-prometheus
          storageClassName: "managed-standard"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 15Gi
```

kubectl get pv,pvc:
```
k get pv,pvc
NAME                                             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS       REASON   AGE
persistentvolume/monitoring-prometheus-staging   15Gi       RWO            Retain           Available           managed-standard            104m
```

I deploy everything through terraform using helm and Kubernetes providers. Am I missing some steps?

**Comment by jr0dd** [comment]
They really need to add the ability to use an existing claim in the chart. After scouring the internet for days I figured out how to add a static pv/pvc. Hopefully this will get you up and running.

```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-db
  labels:
    app: prometheus
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-standard
  azureDisk:
    cachingMode: None
    diskName: monitoring-prometheus-staging
    diskURI: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/monitoring-rg/providers/Microsoft.Compute/disks/monitoring-prometheus-staging
    fsType: ""
    kind: Managed
    readOnly: false

---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    prometheus: kube-prometheus-stack
spec:
  storage:
    volumeClaimTemplate:
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: prometheus
        storageClassName: managed-standard
        volumeName: prometheus-db
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
```

**Comment by theadzik** [comment]
>but the solution doesn't seem so trivial...

It was trivial.  I put my config under `prometheusOperator` instead of `prometheus` block... I spend way too much time looking at it.

```
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          selector:
            matchLabels:
              app.kubernetes.io/name: monitoring-prometheus
          storageClassName: "managed-standard"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 15Gi
```
