### ISSUE TITLE
How to remove the prefix of the prometheus pod name on kube-prometheus-stack of helm chart?

### ISSUE THREAD

**Issue by duanrex** [prometheus-community/helm-charts#1175]
When deploying prometheus, the pod name after the deployment is always automatically prefixed with "prometheus".

How can I remove this prefix?

such as :
fullnameOverride: "test-prometheus"

pod name: prometheus-test-prometheus.

Thanks

**Comment by rmgpinto** [comment]
Have you solved this? I've been trying to remove the `prometheus-` prefix as well...

**Comment by rmgpinto** [comment]
I want to do the same, I've successfully removed the prefix of grafana, prometheus-node-exporter, and kube-state-metrics with the following:

```yaml
grafana:
  fullnameOverride: "grafana"
kube-state-metrics:
  fullnameOverride: "kube-state-metrics"
prometheus-node-exporter:
  fullnameOverride: "prometheus-node-exporter"
```

But I'm still missing the prometheus, prometheus-operator and alertmanager pods, which are still named:

```
alertmanager-prometheus-kube-prometheus-alertmanager-0
prometheus-prometheus-kube-prometheus-prometheus-0
prometheus-kube-prometheus-operator-656fb5f5f4-p48zx
```

**Comment by torstenwalter** [comment]
The easiest way to figure out how to do things like this is to look at the code. Let's start exploring it base on alertmanager.

You've been asking about kube-prometheus-stack. So we first need to check if it renders the template directly or if it uses a dependent chart.

https://github.com/prometheus-community/helm-charts/blob/2ed3afd270e9b7013e7ddf810e81fcfd5f57e123/charts/kube-prometheus-stack/Chart.yaml#L37-L49

Looks like it only has three dependencies and alertmanager is not one of them. So if alertmanager is not a transitive dependency of one of those three charts then the template must be somewhere else.

Here it is:
https://github.com/prometheus-community/helm-charts/blob/2ed3afd270e9b7013e7ddf810e81fcfd5f57e123/charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml#L1-L6

As you can see from the template the name is `{{ template "kube-prometheus-stack.fullname" . }}-alertmanager`. The only thing you could influence is the prefix but not the `-alertmanager` suffix.

**Comment by rmgpinto** [comment]
I did try `values.fullnameOverride: pks` but prometheus pods don't come up, and alertmanager pods are named `alertmanager-pks-alertmanager-0`

**Comment by duanrex** [comment]
I tried values.fullnameOverride, the pod name still add the prefix "prometheus" on the pod name.

Are there other ways to deal with it?

**Comment by lusson-luo** [comment]
i has the same question，i set fullnameOverride or nameOverride in kube-prometheus-stack, but prometheus and alertmanager pod name after the deployment is always automatically prefixed with "prometheus".

i template kube-prometheus-stack to yaml file, alertmanager and prometheus yaml not has prefixed with "alertmanager|prometheus", i doubt it add but some crd.

how  can I remove this prefix?

my alertmanager and prometheus template yaml 
```
---
# Source: observable/charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: observable1-prometheus-alertmanager
  namespace: observable1
  labels:
    app: prometheus-alertmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: observable1
    app.kubernetes.io/version: "39.9.0"
    app.kubernetes.io/part-of: prometheus
    chart: kube-prometheus-stack-39.9.0
    release: "observable1"
    heritage: "Helm"
spec:
  image: "alertmanager:v0.24.0"
  version: v0.24.0
  replicas: 1
  listenLocal: false
  serviceAccountName: observable1-prometheus-alertmanager
  externalUrl: "http://alertmanager.monitor.dev-009.devops-cloud.club/"
  paused: false
  logFormat: "logfmt"
  logLevel:  "info"
  retention: "120h"
  alertmanagerConfigSelector: {}
  alertmanagerConfigNamespaceSelector: {}
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 50Mi
  routePrefix: "/"
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: local-path
  tolerations:
    - effect: NoSchedule
      key: type
      operator: Equal
      value: infrastructure
  imagePullSecrets:
    - name: monitor-registry-secret
  portName: http-web
```

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: observable1-prometheus-prometheus
  namespace: observable1
  labels:
    app: prometheus-prometheus
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: observable1
    app.kubernetes.io/version: "39.9.0"
    app.kubernetes.io/part-of: prometheus
    chart: kube-prometheus-stack-39.9.0
    release: "observable1"
    heritage: "Helm"
...
```

my pod name
![image](https://user-images.githubusercontent.com/19859400/196362530-9efa44e5-ad17-4be1-b532-8cba58999854.png)
![image](https://user-images.githubusercontent.com/19859400/196362566-941d3b0a-8dab-4e06-a7b5-d1adc5da37a8.png)
