### ISSUE TITLE
[kube-prometheus-stack] Need help customizing alerts

### ISSUE THREAD

**Issue by mnecochear** [prometheus-community/helm-charts#1180]
Hi,

(I'm new to this monitoring stack, so please excuse the lack of knowledge. Hopefully I'm asking in the right place.)

I'm trying to customize some alerts within Prometheus & Alertmanager, so that I can define the conditions and severity. For instance, I'd like to be alerted when a pod's CPU usage goes above 70%, with severity = medium, or something like that. Is is possible to do this? If so, how can I achieve it? I read the docs on this repo, but couldn't figure it out. Can someone point me in the right direction, please?

Thanks in advance.

**Comment by tchelovilar** [comment]
Hi @mnecochear ,

You have to create a `PrometheusRule` resource with the desired rules expression like this:
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: custom-pod-cpu-usage
  namespace: monitoring
spec:
  groups:
  - name: custom-pod-cpu-usage
    rules:
    - alert: HighPodCpuUsage
      annotations:
        message: *{{ $labels.pod }}* high cpu usage
      expr: sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (pod) > 0.7
      for: 5m
      labels:
        severity: medium
```

But this is not exactly what you want because it's based on the number of cores instead CPU usage percentual. But I think will help you to figure out a solution.

;)
