### ISSUE TITLE
[prometheus] Invalid volume permissions  with CSI driver

### ISSUE THREAD

**Issue by sam-cogan** [prometheus-community/helm-charts#1189]
**Describe the bug**
When deploying the prometheus helm chart to an AKS cluster running Kubernetes 1.21 the Prometheus Server pod fails to start due to an issue with permissions, with an error like:
```
"Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
```

This appears to be due a change in AKS 1.21 to switch to using the CSI driver for storage, but it is not clear why this is causing an issue for this chart configuration, or how to fix it. Any suggestions are appreciated.

**Version of Helm and Kubernetes**:

Kubernetes Version :1.21
Helm Version: 3.3.0

**Which chart**:
Prometheus
**Which version of the chart**:
13.8.0

**What happened**:

Prometheus server is unable to start due to permission denied on storage volume

**What you expected to happen**:

Prometheus server starts

**How to reproduce it** (as minimally and precisely as possible):

Deploy the Prometheus Helm chart with persistent storage enabled to an Azure AKS 1.21 cluster

**Comment by gbavoz1** [comment]
I found this bug too and the only way to get prometheus running was to force running as root (less than ideal):

```
          prometheusSpec:
            securityContext:
              runAsGroup: 0
              runAsNonRoot: false
              runAsUser: 0
              fsGroup: 0
```
I'll create an issue in https://github.com/kubernetes-sigs/azuredisk-csi-driver and link this one to bring more attention to this problem

**Comment by ams0** [comment]
I found this bug too and the only way to get prometheus running was to force running as root (less than ideal):

```
          prometheusSpec:
            securityContext:
              runAsGroup: 0
              runAsNonRoot: false
              runAsUser: 0
              fsGroup: 0
```
I'll create an issue in https://github.com/kubernetes-sigs/azuredisk-csi-driver and link this one to bring more attention to this problem
