### ISSUE TITLE
[prometheus-blackbox-exporter] ServiceMonitor creation issue

### ISSUE THREAD

**Issue by jr0dd** [prometheus-community/helm-charts#1191]
v5.0.2 of the chart is only generating 1 ServiceMonitor. It only creates the final entry. Running `helm template` looks like it's missing `---` in between instances.

values.yaml section
```
serviceMonitor:
  enabled: true
  defaults:
    labels:
      release: prometheus
    interval: 30s
    scrapeTimeout: 30s
  targets:
  - name: router
    url: 10.10.0.1
    module: icmp
  - name: switch
    url: 10.10.0.2
    module: icmp
```

helm output
```
---
# Source: prometheus-blackbox-exporter/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-exporter-router
  labels:
    helm.sh/chart: prometheus-blackbox-exporter-5.0.2
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/instance: prometheus-blackbox-exporter
    app.kubernetes.io/version: "0.19.0"
    app.kubernetes.io/managed-by: Helm
    release: prometheus
spec:
  endpoints:
  - port: http
    scheme: http
    path: "/probe"
    interval: 30s
    scrapeTimeout: 30s
    params:
      module:
      - icmp
      target:
      - 10.10.0.1
    metricRelabelings:
      - targetLabel: instance
        replacement: 10.10.0.1
      - targetLabel: target
        replacement: router
  jobLabel: "prometheus-blackbox-exporter"
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
      app.kubernetes.io/instance: prometheus-blackbox-exporter
  namespaceSelector:
    matchNames:
      - monitoring
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-exporter-switch
  labels:
    helm.sh/chart: prometheus-blackbox-exporter-5.0.2
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/instance: prometheus-blackbox-exporter
    app.kubernetes.io/version: "0.19.0"
    app.kubernetes.io/managed-by: Helm
    release: prometheus
spec:
  endpoints:
  - port: http
    scheme: http
    path: "/probe"
    interval: 30s
    scrapeTimeout: 30s
    params:
      module:
      - icmp
      target:
      - 10.10.0.2
    metricRelabelings:
      - targetLabel: instance
        replacement: 10.10.0.2
      - targetLabel: target
        replacement: switch
  jobLabel: "prometheus-blackbox-exporter"
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
      app.kubernetes.io/instance: prometheus-blackbox-exporter
  namespaceSelector:
    matchNames:
      - monitoring
```
