### ISSUE TITLE
Prometheus Pod not creating when using additionalAlertManagerConfigsSecret helm value

### ISSUE THREAD

**Issue by cloudpea** [prometheus-community/helm-charts#1207]
I am currently using the `additionalAlertManagerConfigsSecret` value in the helm chart to reference an existing secret for the AlertManager config in Prometheus. See Helm template below:

```yaml
  additionalAlertManagerConfigs:
{{- if .Values.prometheus.prometheusSpec.additionalAlertManagerConfigs }}
    name: {{ template "kube-prometheus-stack.fullname" . }}-prometheus-am-confg
    key: additional-alertmanager-configs.yaml
{{- end }}
{{- if .Values.prometheus.prometheusSpec.additionalAlertManagerConfigsSecret }}
    name: {{ .Values.prometheus.prometheusSpec.additionalAlertManagerConfigsSecret.name }}
    key: {{ .Values.prometheus.prometheusSpec.additionalAlertManagerConfigsSecret.key }}
{{- end }}
``` 

To create the secret i am using secrets-store-csi-driver-provider-aws which requires mounting a volume and referencing the SecretProviderClass resource to create the Kubernetes Secret object. I have mounted this volume within the PrometheusSpec volumes.

```yaml
prometheus:
  prometheusSpec:
    volumes:
    - name: secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: alertmanager-config
    volumeMounts:
      - name: secrets-store
        mountPath: "/mnt/secrets-store"
        readOnly: true
``` 

Unfortunately Prometheus Operator will not create the Prometheus instance because the secret does not exist, the secret will only get created once the pod is created...

Some workarounds that will resolve this are either:
 - Allow the ability to add additional volumes and volume mounts to the Prometheus Operator pod via the Helm Chart values so the secret is present when the Prometheus Instance is created.
 - Add the additional `optional` field within the `additionalAlertManagerConfigsSecret` value along with `name` and `key` so the Prometheus instance will be created regardless if the secret exists yet or not.
