### ISSUE TITLE
[prometheus-kube-stack] Trailing spaces in metadata.labels while doing helm template command

### ISSUE THREAD

**Issue by maheshrayas** [prometheus-community/helm-charts#1208]
**Describe the bug**
When I run helm template, the generated templates have trailing space in metadata.labels and thus yamllint fails while validating the generated templates.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
```

**Which chart**:
 prometheus-community/kube-prometheus-stack

**Which version of the chart**:
17.0.2

**What happened**:
When I run helm template, the generated templates have trailing space in metadata.labels and thus yamllint fails while validating the generated templates.

Below are the commands 

```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm template "prometheus" prometheus-community/kube-prometheus-stack --output-dir="output"

Most of the YAML files generated has a trailing space in metadata.labels : 
Example: output/kube-prometheus-stack/templates/prometheus/servicemonitor.yaml

`apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-kube-prometheus-prometheus
  namespace: platform-monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "17.0.2"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-17.0.2
    release: "prometheus"
    heritage: "Helm"
`

```
but a couple of files do not have the above issue:  
Example: prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml

Is there something I need to be setting in values.yaml to set the labels correctly?
