### ISSUE TITLE
 [prometheus-community] existingClaim

### ISSUE THREAD

**Issue by tretos53** [prometheus-community/helm-charts#1209]
**the bug**
Not sure if the bug or I'm doing something wrong.

I created a volume in AWS: 
- id: vol-REDACTED
- size: 100gb
- type: gp2
- zone: eu-west-2a

I created pvc and pv using below yaml:
```
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: prometheus-pvc
  awsElasticBlockStore:
    volumeID: vol-REDACTED # zone eu-west-2a  prometheus-pv
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  # we use the same name as in PV
  # so the PVC uses that PV
  name: prometheus-pvc
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
```

```
❯ kubectl apply -f volume-prometheus-community.yaml
persistentvolume/prometheus-pv created
persistentvolumeclaim/prometheus-pvc created
```

PVC and PV exist:

```
❯ k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                      STORAGECLASS   REASON   AGE
prometheus-pv                              100Gi      RWO            Retain           Bound    default/prometheus-pvc                             43s

❯ k get pvc
NAME               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
prometheus-pvc     Bound    prometheus-pv                              100Gi      RWO            gp2            51s
```

In the values.yaml I changed line 869: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L869 to include created PVC.

`    existingClaim: "prometheus-pvc"`

By default   persistentVolume: enabled: true

    ## Prometheus server data Persistent Volume existing claim name
    ## Requires server.persistentVolume.enabled: true
    ## If defined, PVC must be created manually before volume will be bound

I deployed prometheus-community with helm3

`helm3 install prometheus-community prometheus-community/prometheus -f values-prometheus-community.yaml --debug`

```
helm3 ls
prometheus-community	default  	5       	2021-07-26 16:36:51.508921 +0100 BST	deployed	prometheus-14.4.1   	2.26.0
```

The pod has PVC:
```
❯ k get pod prometheus-community-server-5446f7754c-hbfj8 -o yaml | grep -i persistentVolumeClaim: -A 1
    persistentVolumeClaim:
      claimName: prometheus-pvc
```

When I list the pvc and pv I can see that the new PV has been created and attached to the PVC. An old pvc has been released.

```
❯ k get pvc
NAME               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
prometheus-pvc     Bound    pvc-dcb684a8-4fb0-4982-ad83-15e22e49a488   100Gi      RWO            gp2            18h

❯ k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                      STORAGECLASS   REASON   AGE
prometheus-pv                              100Gi      RWO            Retain           Released   default/prometheus-pvc                             18h
pvc-dcb684a8-4fb0-4982-ad83-15e22e49a488   100Gi      RWO            Delete           Bound      default/prometheus-pvc     gp2                     18h
```
How can I attach the volume I created in AWS to the prometheus pod?

The pod is deployed to a node in Availability zone eu-west-2a. The same as the volume I created. Both PVs are in the same zone.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm3 version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: prometheus-community

**Which version of the chart**: 14.4.1

**What happened**: prometheus-server creates a new PV instead of using the created manually volume.

**What you expected to happen**: prometheus-server should use the manually created volume.

**How to reproduce it** (as minimally and precisely as possible): Follow above.

**Changed values of values.yaml** (only put values which differ from the defaults):

```
ALERTMANAGER
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - <REDACTED>
  resources:
    limits:
      cpu: 10m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 32Mi
NODEEXPORTER
  resources:
    limits:
      cpu: 200m
      memory: 50Mi
    requests:
      cpu: 100m
      memory: 30Mi
SERVER:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - <REDACTED>
    existingClaim: "prometheus-pvc"
    size: 100Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
    global:
      resolve_timeout: 1m
      slack_api_url: '<REDACTED>'
    receivers:
    - name: slack_notifications
      slack_configs:
      - channel: <REDACTED>
        send_resolved: true
    route:
      group_by:
      - job
      - namespace
      - deployment
      receiver: slack_notifications
      routes:
      - match:
          severity: warning
        receiver: slack_notifications
      - match:
          severity: critical
        receiver: slack_notifications

```

**The helm command that you execute and failing/misfunctioning**: See above. The helm install command is working.
