### ISSUE TITLE
[kube-prometheus-stack] additionalServiceMonitors need add metricRelabelings

### ISSUE THREAD

**Issue by gouki777** [prometheus-community/helm-charts#1211]
**I want add metricRelabelings to additionalServiceMonitors**

A configuration problem is found. 
What should I do,thanks

My bad config
```
  additionalServiceMonitors:
  - name: "xxx"
     ...................................
    endpoints:
      - port: "metrics"
    metricRelabelings:     ############## I add this config . but config don't working
      - separator: ;
        regex: (image_id|container_id|image)
        replacement: $1
        action: labeldrop
```
