### ISSUE TITLE
[prometheus-kube-stack] new prometheus operator chart needs to be reflected?

### ISSUE THREAD

**Issue by perezjasonr** [prometheus-community/helm-charts#123]
**Describe the bug**

getting the error:

`Failed to list *v1.Probe: probes.monitoring.coreos.com is forbidden: User "system:serviceaccount:monitoring:prometheus-stack-kube-prom-operator" cannot list resource "probes" in API group "monitoring.coreos.com" at the cluster scope`

update:
if using newer image version v0.42.0 prometheus operator

**Version of Helm and Kubernetes**:

Helm Version:

version.BuildInfo{Version:"v3.3.0-rc.2", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}

Kubernetes Version:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"archive", BuildDate:"2020-07-31T19:03:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**: prometheus-kube-stack
**Which version of the chart**:  9.4.3 it says in the index.yaml or
```
kube-prometheus-stack:
  - annotations:
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
        - name: Upstream Project
          url: https://github.com/prometheus-operator/kube-prometheus
      artifacthub.io/operator: "true"
    apiVersion: v1
    appVersion: 0.38.1

```

**What happened**:

i got the error mentioned above in prometheus operator logs repeating, and no prometheus pod is created

**What you expected to happen**:

the error doesn't appear, and Prometheus pod is created

**How to reproduce it** (as minimally and precisely as possible):

install the chart, i did not deviate from defaults much, however i found the default prometheus operator image seems fine, its the newer image that breaks:

`helm install prometheus-stack -n monitoring prometheus-community/kube-prometheus-stack --set prometheusOperator.image.tag=v0.42.0`

**Anything else we need to know**:

I believe it has to do with this:

https://github.com/bitnami/charts/issues/3297

and

https://github.com/bitnami/charts/pull/3333

it seems prometheus operator was updated to handle this, i dont think this update is reflected in the kube-prometheus-stack
