### ISSUE TITLE
[thanos-query] - Metrics isn't displayed

### ISSUE THREAD

**Issue by weyderfs** [prometheus-community/helm-charts#1232]
Hello guys,
I had deployed the Prometheus Operator + Prometheus Server with Thanos Sidecar and looking at the application logs everything it's okay and running.
I had configured too Promethes data source in Grafana however when I use the `thanos-store....` endpoint the _metrics_ isn't displayed, but when I switch to `prometheus-operated...` _metrics_ works.

### thanos-query deployment

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thanos-query
  name: thanos-query
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      containers:
      - args:
        - query
        - --log.level=debug 
        - --http-address=0.0.0.0:10902
        - --grpc-address=0.0.0.0:10901
        - --store=dnssrv+_grpc._tcp.thanos-store.observability.svc.cluster.local
        image: quay.io/thanos/thanos:v0.17.2
        name: thanos-query
        ports:
        - containerPort: 10902
          name: http
        - containerPort: 10901
          name: grpc
```
### thanos-query service

```
apiVersion: v1
kind: Service
metadata:
  labels:
  name: thanos-query
  namespace: observability
spec:
  ports:
  - name: http
    port: 10902
    targetPort: http
  selector:
    app: thanos-query
```

Has anyone ever experienced this?
