### ISSUE TITLE
[prometheus-kube-stack] generated custom resource field `Prometheus.spec.storage.volumeClaimTemplate.metadata.name` does not remain set

### ISSUE THREAD

**Issue by wmgroot** [prometheus-community/helm-charts#124]
**Describe the bug**
When I apply a Prometheus resource with `spec.storage.volumeClaimTemplate.metadata.name` set, the metadata field is empty when I get the Prometheus resource through the Kubernetes API after.

The prometheus-kube-stack helm chart sets this field by default.

This causes resync loop issues with gitops-based deployment models that rely on diffs between Git and the K8s API, such as Flux and ArgoCD.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
**Which version of the chart**:
9.3.4

**What happened**:
I applied the following YAML to my cluster.
```
---
# Source: kube-prometheus-stack/templates/prometheus/prometheus.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: test-kube-prometheus-stack-prometheus
  namespace: prometheus-test
  labels:
    app: kube-prometheus-stack-prometheus
    
    chart: kube-prometheus-stack-9.4.3
    release: "test"
    heritage: "Helm"
spec:
  alerting:
    alertmanagers:
      - namespace: prometheus-test
        name: test-kube-prometheus-stack-alertmanager
        port: web
        pathPrefix: "/"
        apiVersion: v2
  baseImage: quay.io/prometheus/prometheus
  version: v2.18.2
  externalLabels:
    cluster: test
    federation: pure
  externalUrl: "https://prometheus-test.test.k8s.test.com"
  paused: false
  replicas: 1
  logLevel:  info
  logFormat:  logfmt
  listenLocal: false
  enableAdminAPI: false
  retention: "3d"
  routePrefix: "/"
  serviceAccountName: test-kube-prometheus-stack-prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus/operator: test

  serviceMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: "test"

  podMonitorNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      prometheus/operator: test
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus-main     # <-------- this field right here 
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  query:
    maxSamples: 10000000
  priorityClassName: tier-0
  portName: web
```

**What you expected to happen**:
I expected the `Prometheus.spec.storage.volumeClaimTemplate.metadata.name` field to remain set.
```
$ kubectl get prometheus -n prometheus-test test-kube-prometheus-stack-prometheus -o yaml

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: kube-prometheus-stack-prometheus
    argocd.argoproj.io/instance: prometheus-test-helm-test
    chart: kube-prometheus-stack-9.4.3
    heritage: Tiller
    release: test
  name: test-kube-prometheus-stack-prometheus
  namespace: prometheus-test
  uid: 2ac5c98f-8da4-47d3-a5ee-5879f9ad6867
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: test-kube-prometheus-stack-alertmanager
      namespace: prometheus-test
      pathPrefix: /
      port: web
  baseImage: quay.io/prometheus/prometheus
  enableAdminAPI: false
  externalLabels:
    cluster: test
    federation: pure
  externalUrl: https://prometheus-test.test.k8s.test.com
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: test
  portName: web
  priorityClassName: tier-0
  query:
    maxSamples: 10000000
  replicas: 1
  retention: 3d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      prometheus/operator: test
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: test-kube-prometheus-stack-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      prometheus/operator: pure
  storage:
    volumeClaimTemplate:
      metadata: {}  # <--------- this has become unset 
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  version: v2.18.2
```

**How to reproduce it** (as minimally and precisely as possible):

Please see the "What Happened" section above for repro steps.

**Anything else we need to know**:
I am currently able to work around the issue in ArgoCD by including an ignoreDifferences block.
```
          ignoreDifferences:
            # not sure why the volumeClaimTemplate metadata.name doesn't stick
            - kind: Prometheus
              group: monitoring.coreos.com
              jsonPointers:
                - /spec/storage/volumeClaimTemplate/metadata
```
