### ISSUE TITLE
[kube-prometheus-stack] Does not support SigV4 , remoteWrite

### ISSUE THREAD

**Issue by hetpats** [prometheus-community/helm-charts#1242]
### Is your feature request related to a problem ?

kube-prometheus-stack Does not Suport Remote Write for Amazon managed prometheus that requires sigv4.
Standalon Prometheus chart supports this feature.
While implementing RemoteWrite with SigV4 to use Amazon managed Prometheus we get the following error.

Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Prometheus.spec.remoteWrite[0]): unknown field "sigv4" in com.coreos.monitoring.v1.Prometheus.spec.remoteWrite

### Describe the solution you'd like.

We would like to use kube-prometheus-stack and its rich features to work with remoteWrite SigV4 support.

### Describe alternatives you've considered.

WE have implemented prometheus chart (standalone ) and are manually adding components as needed, but make the stack work would make deployment easy and simple

### Additional context.

Amazon has confirmed that this is an issue with kube-prometheus-stack .

**Comment by kimmornetum** [comment]
As a workaroud for the time being, I am using a sidecar to achieve this: https://github.com/awslabs/aws-sigv4-proxy

The usage of the sidecar translates to the kube-prometheus-stack chart like this:
```
prometheus:
  prometheusSpec:
    containers:
    - args:
      - --name
      - aps
      - --region
      - <amp-region-here>
      - --host
      - aps-workspaces.<amp-region-here>.amazonaws.com
      - --port
      - :8005
      image: public.ecr.aws/aws-observability/aws-sigv4-proxy:1.0
      imagePullPolicy: Always
      name: aws-sigv4-proxy-sidecar
      ports:
      - containerPort: 8005
        name: aws-sigv4-proxy
    remoteWrite:
    - url: http://localhost:8005/workspaces/<your-workspace-id>/api/v1/remote_write
```
You might want to bump up the aws-sigv4-proxy version on the image line.

Here I am using service accounts annotation and linking them to IAM role but you could pass the credentials eg. in the args.

Hope this helps.

**Comment by sachin064** [comment]
> As a workaroud for the time being, I am using a sidecar to achieve this: https://github.com/awslabs/aws-sigv4-proxy
> 
> The usage of the sidecar translates to the kube-prometheus-stack chart like this:
> 
> ```
> prometheus:
>   prometheusSpec:
>     containers:
>     - args:
>       - --name
>       - aps
>       - --region
>       - <amp-region-here>
>       - --host
>       - aps-workspaces.<amp-region-here>.amazonaws.com
>       - --port
>       - :8005
>       image: public.ecr.aws/aws-observability/aws-sigv4-proxy:1.0
>       imagePullPolicy: Always
>       name: aws-sigv4-proxy-sidecar
>       ports:
>       - containerPort: 8005
>         name: aws-sigv4-proxy
>     remoteWrite:
>     - url: http://localhost:8005/workspaces/<your-workspace-id>/api/v1/remote_write
> ```
> 
> You might want to bump up the aws-sigv4-proxy version on the image line.
> 
> Here I am using service accounts annotation and linking them to IAM role but you could pass the credentials eg. in the args.
> 
> Hope this helps.

HI Kimmo Rantala am trying the same thing in Kube-prometheus-stack operator , but am not able to view the metrices in amazon managed grafana, can you please elaborate how you achieved this am trying in private EKS cluster.

**Comment by kimmornetum** [comment]
> > As a workaroud for the time being, I am using a sidecar to achieve this: https://github.com/awslabs/aws-sigv4-proxy
> > The usage of the sidecar translates to the kube-prometheus-stack chart like this:
> > ```
> > prometheus:
> >   prometheusSpec:
> >     containers:
> >     - args:
> >       - --name
> >       - aps
> >       - --region
> >       - <amp-region-here>
> >       - --host
> >       - aps-workspaces.<amp-region-here>.amazonaws.com
> >       - --port
> >       - :8005
> >       image: public.ecr.aws/aws-observability/aws-sigv4-proxy:1.0
> >       imagePullPolicy: Always
> >       name: aws-sigv4-proxy-sidecar
> >       ports:
> >       - containerPort: 8005
> >         name: aws-sigv4-proxy
> >     remoteWrite:
> >     - url: http://localhost:8005/workspaces/<your-workspace-id>/api/v1/remote_write
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You might want to bump up the aws-sigv4-proxy version on the image line.
> > Here I am using service accounts annotation and linking them to IAM role but you could pass the credentials eg. in the args.
> > Hope this helps.
> 
> HI Kimmo Rantala am trying the same thing in Kube-prometheus-stack operator , but am not able to view the metrices in amazon managed grafana, can you please elaborate how you achieved this am trying in private EKS cluster.

We actually use our own Grafana installation to view the metrics but documentation to get the AMP datasource into AWS managed Grafana can be found here: https://docs.aws.amazon.com/grafana/latest/userguide/AMP-adding-AWS-config.html

**Comment by philschmid** [comment]
@sachin064 did you manage to get it to work? 
I would love to use Amazon Managed Prometheus and Amazon Managed Grafana, but it looks like it is not working with `prometheus-community/kube-prometheus-stack`.

**Comment by rrijkse** [comment]
Just in case it helps anyone, this PR fixed the sigv4 issue: https://github.com/prometheus-community/helm-charts/pull/1485

Example values.yaml
```
prometheus:
   prometheusSpec:
      remoteWrite:
        - url: "https://aps-workspaces.us-east-2.amazonaws.com/workspaces/<WORKSPACE ID>/api/v1/remote_write"
          sigv4:
            region: us-east-2
            roleArn: <ROLE TO ASSUME>
```

All available values are here: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#sigv4

**Comment by dbaltor** [comment]
Hi @rrijkse, this is very useful. Thanks for sharing this. I'm having trouble when combining this config with the service account annotation using the same role as per below:
```

**Comment by dbaltor** [comment]
Hi @rrijkse, this is very useful. Thanks for sharing. I'm having trouble when combining this config with the service account annotation using the same role as per below:
```
prometheus:
  agentMode: true
  serviceAccount:
    create: true
    name: "prometheus"
    annotations: {eks.amazonaws.com/role-arn: "${role_arn}"}
  prometheusSpec:
    remoteWrite:
    - url: "${workspace_url}"
      sigv4:
        region: "${region}"
        roleArn: "${role_arn}"
```
May I ask how you managed to configure kube-promethues-stack to connect to AMP?

**Comment by dbaltor** [comment]
For future reference, when deploying **kube-prometheus-stack** with Amazon Managed Prometheus, we do need to specify `sigv4` but NOT the `roleArn` attribute in the `remoteWrite` section on **values.yaml**. The iam role must be specified only as a service account annotation.
Here is the **values.yaml** file that did the tricky:
```
prometheus:
  agentMode: true

  serviceAccount:
    create: true
    name: "prometheus"
    annotations: {eks.amazonaws.com/role-arn: "${role_arn}"}

  prometheusSpec:
    remoteWrite:
    - url: "${workspace_url}"
      sigv4:
        region: "${region}"   
```

**Comment by shutupflanders** [comment]
> For future reference, when deploying **kube-prometheus-stack** with Amazon Managed Prometheus, we do need to specify `sigv4` but NOT the `roleArn` attribute in the `remoteWrite` section on **values.yaml**. The iam role must be specified only as a service account annotation. Here is the **values.yaml** file that did the tricky:
> 
> ```
> prometheus:
>   agentMode: true
> 
>   serviceAccount:
>     create: true
>     name: "prometheus"
>     annotations: {eks.amazonaws.com/role-arn: "${role_arn}"}
> 
>   prometheusSpec:
>     remoteWrite:
>     - url: "${workspace_url}"
>       sigv4:
>         region: "${region}"   
> ```

Note that this solution requires that the AMP workspace is in the **same AWS account**, this will **not work on cross-account setups**.

**Comment by dbaltor** [comment]
Thanks @shutupflanders. It would be great if you could share here the required configuration for cross-account setups.

**Comment by shutupflanders** [comment]
> Thanks @shutupflanders. It would be great if you could share here the required configuration for cross-account setups.

Sorry, only just seen this - I've not managed any cross account setups as of yet but I'll drop the config in here when I eventually do set one up!

**Comment by arohter** [comment]
For posterity:

```
prometheus:
  extraSecret:
    name: remote-write
    data:
      access_key: ${access_key}
      secret_key: ${secret_key}
  prometheusSpec:
    remoteWriteDashboards: true
    remoteWrite:
    - queueConfig:
        maxSamplesPerSend: ${samples}
        maxShards: ${shards}
        capacity: ${capacity}
      sigv4:
        region: ${region}
        accessKey:
          name: remote-write
          key: access_key
        secretKey:
          name: remote-write
          key: secret_key
      url: https://aps-workspaces.${region}.amazonaws.com/workspaces/${workspace}/api/v1/remote_write
```

**Comment by dbaltor** [comment]
That's awesome! Thanks @arohter

**Comment by kstevensonnv** [comment]
Below is a bare-bones example of using IAM roles instead of an access key to write from account A (development) to account B (tooling).

```
prometheus:
  enabled: true
  serviceAccount:
    create: true
    name: prometheus
    annotations:
      eks.amazonaws.com/role-arn: $account_a_development_iam_role_arn

  prometheusSpec:
    remoteWrite:
    - url: $prometheus_remote_write_endpoint
      sigv4:
        region: $aws_region
        roleArn: $account_b_tooling_iam_role_arn
      queueConfig:
        maxSamplesPerSend: 1000
        maxShards: 200
        capacity: 2500
```
