### ISSUE TITLE
[prometheus-kube-stack] metrics issue 

### ISSUE THREAD

**Issue by rkydybets** [prometheus-community/helm-charts#1244]
### Describe the bug a clear and concise description of what the bug is.

have issue with getting metric `container_spec_memory_limit_bytes`
is is appears from time to time, but no error in logs 

### What's your helm version?

version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

17.2.0

### Enter the changed values of values.yaml?

```
## Create default rules for monitoring the cluster
##
defaultRules:
  create: true
  rules:
    alertmanager: false
    etcd: false
    general: true
    k8s: true
    kubeApiserver: false
    kubeApiserverAvailability: false
    kubeApiserverError: false
    kubeApiserverSlos: false
    kubelet: true
    kubePrometheusGeneral: true
    kubePrometheusNodeAlerting: true
    kubePrometheusNodeRecording: true
    kubernetesAbsent: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeScheduler: false
    kubeStateMetrics: true
    network: true
    node: true
    prometheus: true
    prometheusOperator: true
    time: true


alertmanager:

  ## Deploy alertmanager
  ##
  enabled: false


## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  enabled: false
  
## Component scraping the kube api server
##
kubeApiServer:
  enabled: false

## Component scraping the kubelet and kubelet-hosted cAdvisor
##
kubelet:
  enabled: true

## Component scraping the kube controller manager
##
kubeControllerManager:
  enabled: false
## Component scraping coreDns. Use either this or kubeDns
##
coreDns:
  enabled: false

## Component scraping kubeDns. Use either this or coreDns
##
kubeDns:
  enabled: false
## Component scraping etcd
##
kubeEtcd:
  enabled: false

## Component scraping kube scheduler
##
kubeScheduler:
  enabled: false

## Component scraping kube proxy
##
kubeProxy:
  enabled: false

## Component scraping kube state metrics
##
kubeStateMetrics:
  enabled: true

kube-state-metrics:
  extraArgs:
    - --metric-labels-allowlist=nodes=[*],namespaces=[*],cronjobs=[*],jobs=[*],pods=[*],persistentvolumeclaims=[*],deployments=[*],statefulsets=[*],configmaps=[*],secrets=[*],services=[*],replicasets=[*]

## Deploy node exporter as a daemonset to all nodes
##
nodeExporter:
  enabled: true

## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  enabled: true
  logLevel: info
  configReloaderCpu: 200m
  configReloaderMemory: 128Mi

## Deploy a Prometheus instance
##
prometheus:
  enabled: true

  ## Settings affecting prometheusSpec
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
  ##
  prometheusSpec:

    serviceMonitorSelectorNilUsesHelmValues: false

    ## How long to retain metrics
    ##
    retention: 7d

    ## Interval between consecutive scrapes.
    ## Defaults to 30s.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/release-0.44/pkg/prometheus/promcfg.go#L180-L183
    ##
    scrapeInterval: "60s"

    ## Enable compression of the write-ahead log using Snappy.
    ##
    walCompression: true

    ## If true, the Operator won't process any Prometheus configuration changes
    ##
    paused: false

    ## Log level for Prometheus be configured in
    ##
    logLevel: info

    # https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md
    query:
      maxSamples: 20000000
      timeout: 15s
```

### Enter the command that you execute and failing/misfunctioning.

install chart with terraform
