### ISSUE TITLE
[prometheus] Securing Prometheus API and UI endpoints using basic auth in Container

### ISSUE THREAD

**Issue by prab2014** [prometheus-community/helm-charts#1255]
Team,

I am running Prometheus on containers using helm chart prometheus-community/prometheus .

Chart - **https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus** 

Need to add basic authentication in prometheus to secure the UI and API endpoints . I am following the docs "https://prometheus.io/docs/guides/basic-auth/"  and "https://prometheus.io/docs/prometheus/latest/configuration/https/" for the same .

Have created the web.yml file with basic auth settings .

I am not able to do helm upgrade as not sure how to set the flag  "web.config.file" in prometheus . On local environment i can easily do this by restarting the prometheus and running the below command 

Tried below upgrade commands but it doe not work as expected

1)  helm upgrade --set-file web.config.file="C:\\prometheus\\prometheus\\web.yaml" --reuse-values [release] prometheus-community/prometheus -n "namespace"

2)  helm upgrade --set-file extraFlags.web.config.file="C:\\prometheus\\prometheus\\web.yaml" --reuse-values [release]prometheus-community/prometheus -n "namespace"

 **.\prometheus. exe  --web.config-file == "my web.yml file path"**

Prometheus version  - 2.26 
valu.yml = https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml

Any help/suggestion would be great here.

**Comment by prab2014** [comment]
Any updates here?

**Comment by prab2014** [comment]
Thanks.
I have tried this earlier but as mentioned ,the pods were not working post helm upgrade with these changes.(401 error)
Also, added the basic auth settings at ingress level but got the ingress error( i am still working on this).
Do let me know the best way to secure prometheus api endpoints and web ui.  Also, mechanism to integrate the  promethues auth settings in Grafana too.

**Comment by prab2014** [comment]
> Basic auth is fairly easy to enable
> 
> ```yaml
> server:
>   extraArgs:
>     web.config.file: /etc/config/web_config.yml
> serverFiles:
>   web.config.yml:
>     basic_auth_users:
>       user: 'bcrypt password'
> ```
> 
> The issue is that is also enable basic authentication on endpoints used for liveness and readiness probes, resulting in the pod being killed. Would be great to describe an idiomatic way to secure prometheus.

Thanks.  

I have tried this earlier but as mentioned ,the pods were not working post helm upgrade with these changes.(401 error)
Also, added the basic auth settings at ingress level but got the ingress error( i am still working on this).
Do let me know the best way to secure prometheus api endpoints and web ui.  Also, mechanism to integrate the  promethues auth settings in Grafana too.

**Comment by prab2014** [comment]
> > Basic auth is fairly easy to enable
> > ```yaml
> > server:
> >   extraArgs:
> >     web.config.file: /etc/config/web_config.yml
> > serverFiles:
> >   web.config.yml:
> >     basic_auth_users:
> >       user: 'bcrypt password'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The issue is that is also enable basic authentication on endpoints used for liveness and readiness probes, resulting in the pod being killed. Would be great to describe an idiomatic way to secure prometheus.
> 
> Thanks.
> 
> I have tried this earlier but as mentioned ,the pods were not working post helm upgrade with these changes.(401 error)
> Also, added the basic auth settings at ingress level but got the ingress error( i am still working on this).
> Do let me know the best way to secure prometheus api endpoints and web ui. Also, mechanism to integrate the promethues auth settings in Grafana too.

**Comment by prab2014** [comment]
> Basic auth is fairly easy to enable
> 
> ```yaml
> server:
>   extraArgs:
>     web.config.file: /etc/config/web_config.yml
> serverFiles:
>   web.config.yml:
>     basic_auth_users:
>       user: 'bcrypt password'
> ```
> 
> The issue is that is also enable basic authentication on endpoints used for liveness and readiness probes, resulting in the pod being killed. Would be great to describe an idiomatic way to secure prometheus.

Hi,any updates here?

**Comment by prab2014** [comment]
> Basic auth is fairly easy to enable
> 
> ```yaml
> server:
>   extraArgs:
>     web.config.file: /etc/config/web_config.yml
> serverFiles:
>   web.config.yml:
>     basic_auth_users:
>       user: 'bcrypt password'
> ```
> 
> The issue is that is also enable basic authentication on endpoints used for liveness and readiness probes, resulting in the pod being killed. Would be great to describe an idiomatic way to secure prometheus.

Hi, What would be the best way to add basic auths?

**Comment by isac-seven** [comment]
I have the same problem, while it doesn't get fixed I'm using basic auth at the ingress level.

```yaml
prometheus:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
```

As described [here](https://kubernetes.github.io/ingress-nginx/examples/auth/basic/).

**Comment by prab2014** [comment]
> I have the same problem, while it doesn't get fixed I'm using basic auth at the ingress level.
> 
> ```yaml
> prometheus:
>   ingress:
>     enabled: true
>     annotations:
>       nginx.ingress.kubernetes.io/auth-type: basic
>       nginx.ingress.kubernetes.io/auth-secret: basic-auth
>       nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
> ```
> 
> As described [here](https://kubernetes.github.io/ingress-nginx/examples/auth/basic/).

i have done the same stuff. Strange, why Prometheus inbuilt feature is not working here.

**Comment by prab2014** [comment]
> FYI - for whomever might still be looking for a solution for this it seems a workaround is now supported in Prometheusm Helm chart >= 14.10. Via support for custom headers (which can be used to autheticate the healthchecks), it was imeplemented here - [0d69e90](https://github.com/prometheus-community/helm-charts/commit/0d69e90769e87f6f972bd7c1ad9663a7f54c6677) and merged here - #1422
> 
> ```
> probeHeaders:
>   - name: Authorization
>     value: Basic YWRtaW46c29tZXBhc3M=
> ```
> 
> Where the user and pass are base64 encoded in format user:pass and sent with an Authorization header.

ok, this is great news.I will check the implementaions

**Comment by looorent** [comment]
Thanks @burizz , I confirm combining `extraArgs` with `server.probeHeaders` works fine.
Here is a template:
```
server:
  extraArgs:
    web.config.file: /etc/config/web_config.yml
  probeHeaders:
    - name: Authorization
      value: Basic <'username:password' in base64> 

serverFiles:
  web.config.yml:
    basic_auth_users:
      <username>: '<bcrypt password>'
```

**Comment by AntonioVelichkov** [comment]
`probeHeaders` works for Prometheus Server, but not for Alertmanger. So if I use `basic-auth` for Alertmanager the pod will still fail with `Readiness probe failed: HTTP probe failed with statuscode: 401`.

Has anyone found a workaround for this or we need to wait for `probeHeaders` for Alertmanger?

**Comment by mindrunner** [comment]
How does this work with kube-prometheus-stack?

**Comment by brsolomon-deloitte** [comment]
Seconding @mindrunner 's question since `kube-prometheus-stack` values.yaml seems to offer neither `probeHeaders` nor `serverFiles`.

**Comment by Kushagratandon12** [comment]
Hey @cykl @prab2014 @burizz I was facing this same issue and found out one typo mistake that we are making 

> ```
> server:
>   extraArgs:
>     web.config.file: /etc/config/web_config.yml
> serverFiles:
>   web.config.yml:
>     basic_auth_users:
>       user: 'bcrypt password'
> 
> ```

If you  noticed the web.config.file we are creating or putting the data is web_config.yml + while in serverFiles we are specifying web.config.yml. This is what the small mistake we were making pasting correct code_snip


```
server:
  extraArgs:
    web.config.file: /etc/config/web.config.yml
serverFiles:
  web.config.yml:
    basic_auth_users:
      user: 'bcrypt password'
```

**Comment by taskovskig** [comment]
This is the full working solution (version 15.5.0):

'''
server:
  tcpSocketProbeEnabled: true
  extraArgs:
    web.config.file: /etc/config/web.config.yml
  probeHeaders:
    - name: Authorization
      value: Basic 'base64 ${prometheus_admin_user_password}'
serverFiles:
  web.config.yml:
    basic_auth_users:
      admin: 'bcrypt ${prometheus_admin_password}'
'''

If you deep dive into deployment template, you'll see that `tcpSocketProbeEnabled: true` disables the probes.

**Comment by MDanialSaleem** [comment]
It might be useful to get the base64 user:pass value from a secret instead. 
Usecase:
-> store all secret values in external secret store (AWS secrets manager, Hashicorp vault etc)
-> use value from that secret, thereby removing the need to store a sensitive value in values file.

**Comment by diegocarrillo-kr** [comment]
> config

have anyone find a way to implement this on kube-prometheus-stack?

**Comment by ravindraprasad85** [comment]
@taskovskig - Above does not worked for me, Can you please share your values.yaml files where you got this worked.
Do we need nginx as well to add password based authentication in kube-prometheus-stack?

Below is my content from values.yaml
-----------
  server:
    tcpSocketProbeEnabled: true
    extraArgs:
      web.config.file: /etc/config/web.config.yml
    probeHeaders:
      - name: Authorization
        value: Basic 'base64 V3IwbmdTY3IxcHRAMzIx'
  serverFiles:
    web.config.yml:
      basic_auth_users:
        admin: 'bcrypt $apr1$ywJcehu3$XFqudMF9.PEoM3QNrCi6E.'

**Comment by rshiva777** [comment]
I am unable to find any parameters with **serverFiles** in the kube-prometheus-stack values.yaml

Where can we enable authentication for prometheus using the kube-prometheus-stack helm chart and what parameters need to be updated on values.yaml. Could anyone please help on this

**Comment by yeatun** [comment]
hey is it possible to implement this basic auth in prometheus.yaml that are provide istio,if it is please tell me the process

**Comment by YuriiSmolii** [comment]
Hi folks, recently I have tried to implement basic auth using configurations provided above:

Chart version: 19.3.3

values.yml
```
server:
  tcpSocketProbeEnabled: true
  extraArgs:
    web.config.file: /etc/config/web.config.yml
  probeHeaders:
    - name: Authorization
      value: Basic 'bW9udXNlcjpzdHJvbmdwYXNzMjAy'

serverFiles:
  web.config.yml:
    basic_auth_users:
      monuser: '$2a$12$A4DJ9RThnu3EZjMtyLbfReOeQW8uCmJ2RX5lXbDqSdDT8u4jIxM.K'
```
P.S I've tried with and without '' around credentials. Config don't work for me (
Does anyone have updates ? @taskovskig @looorent

**Comment by swetharao12** [comment]
Hi All, Anyone has any update on above? I am trying to put the authentication on the prometheus server and would like to make it work for cluster.
works on the prometheus server using below document: https://prometheus.io/docs/guides/basic-auth/

**Comment by rajibmitra** [comment]
Hey everyone,
I came across an issue with the solution mentioned in this thread= It seems that the solution is not working as expected when using basic authentication in Helm charts.
If anyone has successfully enabled basic authentication and has a working values.yml file, could you please share. 
Thank you!

**Comment by huiweiguozi** [comment]
It took me so much time to investigate this issue. but I finally just figured it out. A simple example could explain everything. 

```
server:
  tcpSocketProbeEnabled: true
  extraArgs:
    web.config.file: /etc/config/web.config.yml
  probeHeaders:
    - name: Authorization
      value: Basic 'base64 ${prometheus_admin_user_password}'
serverFiles:
  web.config.yml:
    basic_auth_users:
      admin: 'bcrypt ${prometheus_admin_password}'
```
---

If the username=test, and password=test, 
then use the python code to generate the prometheus_admin_password, result is $2b$12$/u2Vwu7QRcycE9JwJ6SzWOkdZMxIGiajWL3rakyGaXRMUX9hPncJS
```import getpass
import bcrypt

password = 'test'
hashed_password = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt())
print(hashed_password.decode())
```
and 'base64 ${prometheus_admin_user_password}' should be generated like this:
```
echo -n 'test:test' | base64
```
result: dGVzdDp0ZXN0

Thus, the configuration block that fully works for me is:
```
server:
  extraArgs:
    web.config.file: /etc/config/web.config.yml
  probeHeaders:
    - name: Authorization
      value: Basic 'dGVzdDp0ZXN0'
serverFiles:
  web.config.yml:
    basic_auth_users:
      test: '$2b$12$/u2Vwu7QRcycE9JwJ6SzWOkdZMxIGiajWL3rakyGaXRMUX9hPncJS'

**Comment by mrbahrianyi** [comment]
There are 2 more variants to do it. Previous solution was not appropriate in my case.
Chart: **prometheus-27.49.0**
- 1 variant with configMap.
1. Create configMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: webconf-configmap
  namespace: monitoring
data:
  web-config.yml: |
    basic_auth_users:
      prom: '$2b$12$pK1trB/ddm4WbBdAwKUHSepJAYMPrb7wozpudPJ5mUf/BDNdFoFTu'
```
2. Generate token for probes as [huiweiguozi](https://github.com/huiweiguozi) mentioned above.
3. Add configuration
```
server:
  probeHeaders:
    - name: "Authorization"
      value: "Basic cHJvbTpwcm9t"
  extraArgs:
    web.config.file: /etc/config/webconf/web.config.yml
  extraConfigmapMounts:
    - name: webconf-configmap
      mountPath: /etc/config/webconf
      configMap: webconf-configmap
      readOnly: true
```
- 2 variant with secret.
1. Create web-config.yml:
```
basic_auth_users:
  prom: '$2b$12$pK1trB/ddm4WbBdAwKUHSepJAYMPrb7wozpudPJ5mUf/BDNdFoFTu'
```
2. Create generic secret from file
`kubectl create secret generic webconf-secret --from-file web-config.yml`
3. Generate token for probes as [huiweiguozi](https://github.com/huiweiguozi) mentioned above.
4. Add configuration
```
server:
  probeHeaders:
    - name: "Authorization"
      value: "Basic cHJvbTpwcm9t"
  extraArgs:
    web.config.file: /etc/config/webconfsecret/web.config.yml
  extraSecretMounts:
    - name: webconf-secret
      mountPath: /etc/config/webconfsecret
      secretName: webconf-secret
      readOnly: true
```
