### ISSUE TITLE
[prometheus-kube-stack] Missing new config parameters from alertmanager

### ISSUE THREAD

**Issue by anderius** [prometheus-community/helm-charts#1268]
### Describe the bug a clear and concise description of what the bug is.

New alertmanager config parameters not accepted by the operator.

### What's your helm version?

version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"7ea22988e84a8e0701cb7e4b21b44d2634f8205d", GitTreeState:"clean", BuildDate:"2021-07-15T22:09:43Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

18.0.0

### What happened?

The parameter `api_url_file` was introduced in alertmanager 0.22, and I am running that version. It seems, however, that the operator is using configuration from version 0.21, and the field is not valid for that version.

`level=error ts=2021-08-19T13:11:03.227726252Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"kube-prometheus/kube-prometheus-kube-prome-alertmanager\" failed: provision alertmanager configuration: base config from Secret could not be parsed: yaml: unmarshal errors:\n  line 7: field api_url_file not found in type alertmanager.slackConfig"`

I am not sure how the operator validates or fetches the alertmanager configuration schema.

### What you expected to happen?

The config is valid, and shouwl be accepted.

### How to reproduce it?

Use the following config for alertmanager:
```
 config:
      route:
        receiver: "slack"
      receivers:
        - name: "null"
        - name: "slack"
          slack_configs:
            - send_resolved: true
              channel: blabla
              api_url_file: "/etc/alertmanager/secrets/alertmanager-custom-secret/slack-hook-url"
```

### Enter the command that you execute and failing/misfunctioning.

I use ArgoCD, so I don't have the exact commands at hand.

**Comment by anderius** [comment]
It seems prometheus-operator does not support AlertManager 0.22 yet.

See https://github.com/prometheus-operator/prometheus-operator/issues/4078 and https://github.com/prometheus-operator/prometheus-operator/issues/4087

**Comment by anderius** [comment]
This PR should fix it: https://github.com/prometheus-operator/prometheus-operator/pull/4092

**Comment by sneko** [comment]
@anderius I'm not sure but in the documentation https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md?plain=1#L1550 I can see we are able to use `*v1.SecretKeySelector` to get the URL from a secret.

Is there any example of the object value to set (secret key/field)? Does it mean we cannot set the URL directly as I did before with the `slack_api_url`?

Thanks,

**Comment by sneko** [comment]
@anderius after multiple attempts like:
```
      - name: slack
        slack_configs:
          - channel: "#alertmanager"
            api_url:
              name: alertmanager-slack
              key: generalChannelUrl
```

It does not work at all, even worst, when uninstalling/reinstalling the chart, the AlertManager won't be deployed since the operator detects a wrong configuration.

If I set back `api_url: https...` the AlertManager is deployed and works properly...

I guess the work done on `prometheus-operator` about this SecreetSelector is not yet adapted into the Helm chart, right (didn't find it in charts templates)?

Thank you,
