### ISSUE TITLE
[kube-prometheus-stack] The various service monitors deployed should allow templating of the values passed into it

### ISSUE THREAD

**Issue by TomHellier** [prometheus-community/helm-charts#1269]
### Is your feature request related to a problem ?

I am deploying kube-prometheus-stack to a cluster with the SHARD option enabled, and I think I need to apply the following relabellings to the service monitors. Example for the nodeExporter below...
```
kube-prometheus-stack:
  nodeExporter:
    # configure the service monitor to add the kubernetes node to the name
    serviceMonitor:
      relabelings:
        - target_label: __tmp_hash
          source_labels:
            - __address__
          modulus: 3  # must equal the number of shards
          action: hashmod
        - source_labels:
            - __tmp_hash
          regex: $(SHARD)
          action: keep
```

And this will ensure that the metrics are only stored by the shard which is responsible for it (based on the modulus function).

### Describe the solution you'd like.

I would like to be able to pass in `kube-prometheus-stack.prometheus.prometheusSpec.shards` into the modulus, which would allow me to not have to redefine this for every cluster I deploy, as some have different shard values.

For some reason, the [metricsRelabelling](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/exporters/node-exporter/servicemonitor.yaml#L34) is passed through `tpl`, but not the [relabelling](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/exporters/node-exporter/servicemonitor.yaml#L38)

### Describe alternatives you've considered.

I could configure the relabel configs for each cluster in values files provided on a per-cluster basis, but the amount of times I would need to repeat the `modulus` would become unwieldy.
