### ISSUE TITLE
[prometheus-node-exporter] Port of daemonset is incorrect

### ISSUE THREAD

**Issue by fredgate** [prometheus-community/helm-charts#1279]
### Describe the bug a clear and concise description of what the bug is.

The values of the chart allow to configure the service and especially its ports:
```yaml
service:
  type: ClusterIP
  port: 9100
  targetPort: 9100
  nodePort:
  listenOnAllInterfaces: true
  annotations:
    prometheus.io/scrape: "true"
```

In the daemonset, its port is configured with the variable `.Values.service.port`
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/templates/daemonset.yaml#L66
```yaml
ports:
  - name: metrics
    containerPort: {{ .Values.service.port }}
    protocol: TCP
```
when it should be `.Values.service.targetPort`.

This inversion is present three more times in the daemonset file at the lines 47, 71 and 75.

It works if the values `service.port` and `service.targetPort` are identical, what is their defaults, but it fails if we override one of these values when installing the chart.

### What's your helm version?

3.5.2

### What's your kubectl version?

1.20.4

### Which chart?

prometheus-node-exporter

### What's the chart version?

2.0.4

### What happened?

The pod of the daemonset does not listen to the expected port, and the service can not redirect to the pod.

### What you expected to happen?

The daemonset should listen to the correct port.

### How to reproduce it?

Install the chart by overriding either `service.port` or `service.targetPort`. 

### Enter the changed values of values.yaml?

```yaml
service:
  targetPort: 9101
```

### Enter the command that you execute and failing/misfunctioning.

helm install node-exporter prometheus-community/prometheus-node-exporter --values values.yaml
