### ISSUE TITLE
[kube-prometheus-stack] adjust thanos service and add sidecar servicemonitor

### ISSUE THREAD

**Issue by jr0dd** [prometheus-community/helm-charts#1291]
### Is your feature request related to a problem ?

The official thanos sidecar also uses http port 10902 which is also the port that the servicemonitor connects to since it can't use grpc. I was hoping that you can add the additional port to the chart as well as adding the servicemonitor.

### Describe the solution you'd like.

service:
```
spec:
  ports:
    - name: grpc
       port: 10901
       targetPort: 10901
    - name: http
       port: 10902
       targetPort: 10902
```

servicemonitor:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: sidecar
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: thanos
  name: thanos-sidecar
  namespace: monitoring
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app: prometheus-thanos-discovery
      app.kubernetes.io/instance: kube-prometheus-stack
```

### Describe alternatives you've considered.

manually deploying service and servicemonitor, but defeats the purpose of the chart
