### ISSUE TITLE
[prometheus-statsd-exporter] ConfigMap name set incorrectly in _helpers.tpl

### ISSUE THREAD

**Issue by MaroonedMind** [prometheus-community/helm-charts#1295]
### Describe the bug a clear and concise description of what the bug is.

If you set a `mappingConfigMapName` value `helm template` command will give the following error:  

> helm.go:81: [debug] error converting YAML to JSON: yaml: line 78: could not find expected ':'

This is due to the following line:
https://github.com/prometheus-community/helm-charts/blob/bd7f3ca7efb7b5806b720b098144d1240c930a70/charts/prometheus-statsd-exporter/templates/_helpers.tpl#L69

It should be: 

 `{{- default .Values.statsd.mappingConfigMapName }}`

### What's your helm version?

version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-statsd-exporter

### What's the chart version?

0.3.1

### What happened?

Helm generates invalid deployment.yaml: 

```
      volumes:
        - name: statsd-mapping-config
          configMap:
            name: 
 statsd
            items:
              - key: statsd.mappingConf
                path: statsd-mapping.conf
```

### What you expected to happen?

A valid deployment.yaml: 

```
      volumes:
        - name: statsd-mapping-config
          configMap:
            name: statsd
            items:
              - key: statsd.mappingConf
                path: statsd-mapping.conf
```

### How to reproduce it?

Specify value for `mappingConfigMapName` in _values.yaml_ file and run `helm template`

### Enter the changed values of values.yaml?

mappingConfigMapName: "statsd"

### Enter the command that you execute and failing/misfunctioning.

helm template -f mychart/values.yaml mychart/
