### ISSUE TITLE
[ kube-prometheus-stack ] support explicit `kubernetesResource` alert configuration

### ISSUE THREAD

**Issue by mars64** [prometheus-community/helm-charts#1296]
### Is your feature request related to a problem ?

No

### Describe the solution you'd like.

Currently, the [`kubernetes-resources.yaml` config](https://github.com/prometheus-community/helm-charts/blob/5477284197a4075229e80decbb89ebb963d9eb15/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-resources.yaml) is an all-or-nothing enable via:

```
{{- if and (semverCompare ">=1.14.0-0" $kubeTargetVersion) (semverCompare "<9.9.9-9" $kubeTargetVersion) .Values.defaultRules.create .Values.defaultRules.rules.kubernetesResources }}
```

In my case with `clusterAutoscaling`, I care when `CPUThrottlingHigh` fires, but not when `Kube*Overcommit` fires -- my cluster will autoscale when needed, so I'm intentionally overcommitting, especially in non-prod environments.

I'd like to be able to, e.g. default all probes to `enabled: true`, then:

```
defaultRules:
  rules:
    kubernetesResources:
      kubeCPUOvercommit: 
        enabled: false
```

### Describe alternatives you've considered.

NONE

**Comment by sean-rossignol** [comment]
For anyone else who stumbled upon this issue and found no resolution.  This feature was added in the following commit in 2021: https://github.com/prometheus-community/helm-charts/commit/51351ed2db55a180105598ac83255afde0a12765

Which was done in this PR: https://github.com/prometheus-community/helm-charts/pull/1173

This change added a `disabled` block to the `defaultRules` which accepts a mapping of rule names to boolean values.  Here's an example disabling the `KubeCPUOverCommit` and `KubeMemoryOvercommit` rules:
```
defaultRules:
  disabled:
    KubeCPUOvercommit: true
    KubeMemoryOvercommit: true
```
