### ISSUE TITLE
[kube-prometheus-stack] Make default kube-controller-manager and kube-scheduler ports depend on Kubernetes versions v1.22 and v1.23

### ISSUE THREAD

**Issue by invidian** [prometheus-community/helm-charts#1310]
### Is your feature request related to a problem ?

Right now, all deployments to Kubernetes v1.22+ must change the kube-controller-manager port to 10257 explicitly to be able to scrape metrics from it, as default port has been changed in upstream Kubernetes:
> liveness/readiness probes to controller-manager MUST use HTTPS now, and the default port has been changed to 10257.

From https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#deprecation

### Describe the solution you'd like.

Change default port to 10257 or make it dynamic based on detected Kubernetes version.

### Describe alternatives you've considered.

NONE

### Additional context.

Note that this might be a breaking change for clusters <v1.22.

As a workaround, when deploying on 1.22, one can add the following snippet to their values.yaml:
```yaml
kubeControllerManager:
  service:
    port: 10257
    targetPort: 10257
  serviceMonitor:
    https: true
    insecureSkipVerify: true
```
