### ISSUE TITLE
[kube-prometheus-stack] `node-exporter-nodes` Dashboard doesn't suppport cluster selector

### ISSUE THREAD

**Issue by sherifkayad** [prometheus-community/helm-charts#1311]
### Describe the bug a clear and concise description of what the bug is.

Currently with the flag `grafana.sidecar.dashboards.multicluster.global.enabled` set to `true`, most (if not all) of the dashboards should support multi-cluster setup providing the ability to have a `cluster` label in the dashboards.

This is not the behavior in the `node-exporter-nodes` Dashboard.

### What's your helm version?

version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

18.0.0

### What happened?

Currently with the flag `grafana.sidecar.dashboards.multicluster.global.enabled` set to `true`, most (if not all) of the dashboards should support multi-cluster setup providing the ability to have a `cluster` label in the dashboards.

This is not the behavior in the `node-exporter-nodes` Dashboard.

### What you expected to happen?

The `node-exporter-nodes` Dashboard should have a `cluster` drop-down selector.

### How to reproduce it?

Just install the chart!

### Enter the changed values of values.yaml?

```yaml
## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  enabled: false

  ## ForceDeployDatasources Create datasource configmap even if grafana deployment has been disabled
  ##
  forceDeployDatasources: false
  ## ForceDeployDashboard Create dashboard configmap even if grafana deployment has been disabled
  ##
  forceDeployDashboards: true

  ## Deploy default dashboards.
  ##
  defaultDashboardsEnabled: true

  sidecar:
    dashboards:
      label: grafana_dashboard
      multicluster:
        global:
          enabled: true
        etcd:
          enabled: false
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install kube-prometheus --namespace=monitoring -f monitoring/kube-prometheus-stack/values.yml prometheus-community/kube-prometheus-stack --version="18.0.0"
