### ISSUE TITLE
[kube-prometheus-stack] Unable to pass grafana.ini

### ISSUE THREAD

**Issue by MatteoGioioso** [prometheus-community/helm-charts#1337]
### Describe the bug a clear and concise description of what the bug is.

Trying to pass my `auth.anonymous` configuration to the `grafana.ini` value, however it does nothing, when I check the `grafana.ini` inside the pod is still the default one. According to the default values.yaml that should work.

### What's your helm version?

version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

18.0.6

### What happened?

`grafana.ini` does not change

### What you expected to happen?

To update the `grafana.ini`

### How to reproduce it?

1. create a new helm chart and import it as dependencies:

`Chart.yaml`

```
...
dependencies:
  - name: kube-prometheus-stack
    version: 18.0.6
    repository: https://prometheus-community.github.io/helm-charts
```

Then input the following values:

### Enter the changed values of values.yaml?

```
kube-prometheus-stack:
  prometheusOperator:
    podAnnotations:
      linkerd.io/inject: enabled
  grafana:
    enabled: true
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_name: my_org
        org_role: Editor
```

### Enter the command that you execute and failing/misfunctioning.

`helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n prometheus -f values.yaml`

**Comment by baczus** [comment]
Hi,
could you explain how to enable anonymous access in Grafana?

**Comment by MatteoGioioso** [comment]
Hey,

I am supplying those values to: `elm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n prometheus -f values.yaml`

```
grafana:
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Editor
    auth:
      disable_login_form: true
```

Note: `Main Org.` is not a made-up name, it is the name of the default organization, if the name of the org is not present in grafana you won't be able to login.
