### ISSUE TITLE
[prometheus-kube-stack] Unable to use with Traefik

### ISSUE THREAD

**Issue by mokhos** [prometheus-community/helm-charts#1338]
Hi. As my title states, I'm not able to configure Traefik as ingress for this chart. I spent so much time for this to be fixed, but looks like a bug to me (unless I'm not able to configure it!). Anyways, I have configured traefik as ingress for my apps. The same config works fine for all except this chart! When I apply the ingress config, it is recognised by the Traefik and I can see that in my Traefik-dashboard. However, when I call the address through browser, I get "Gateway Timeout".

I already talked to a Traefik expert in their own community and I'm pretty sure that's not a Traefik issue!

So my Traefik configuration for all ingress and all other apps that are working without any problem, is like below:

```
ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: true
    ingressClassName: traefik # This field is required in order for traefik to pickup ingress!
    ## Annotations for Grafana Ingress
    ##
    annotations: 
        traefik.ingress.kubernetes.io/router.entrypoints: web
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

    ## Labels to be added to the Ingress
    ##
    labels: {}

    ## Hostnames.
    ## Must be provided if Ingress is enable.
    ##
    # hosts:
    #   - grafana.domain.com
    hosts: 
        - grafana.example.com

    ## Path for grafana ingress
    path: /

    pathType: Prefix
```

P.S: I did the same for prometheus-ingress and alert-manager-ingress in the same chart, but no luck!

Please help, if you have any idea.

Thanks
