### ISSUE TITLE
Guidance for how to perform a cluster-wide install

### ISSUE THREAD

**Issue by trondhindenes** [prometheus-community/helm-charts#1358]
### Is your feature request related to a problem ?

(Please note that I'm a prometheus-noob, although having years of experience with kubernetes)

My goal is to install prometheus so that we can use it to monitor both the cluster itself, and workloads running on the cluster in various namespaces. It's surprising to me that this seems to not be the "default" use-case. For example, the default Prometheus install seems to be tied to a single namespace (or a very limited set of them at least). I'm very surprised that I have to dig thro github issues and the api spec to figure out how I can make prometheus discover stuff to monitor across all namespaces (it even looks as tho namespaces have to be explicitly labelled, there's no `namespaces: *` as far as I can see.

While I do understand that some larger clusters are multi-tenant installations and thus require a more isolated approach I'm finding it quite strange that this seems to be the default.

I find myself going in circles trying to get this thing up and running...

### Describe the solution you'd like.

I totally understand that this is not an "actionable" issue, but what would help me at least is some documentation around "scenarios": 
- "click here if you just want to monitor the cluster and workloads in any namespace"
- "click here if you want a setup where you can have multiple prometheus instances on a single cluster"

### Describe alternatives you've considered.

NONE

**Comment by christopheblin** [comment]
I did a brand new install of the helm-charts some days ago, and all the namespaces are monitored by default (CPU/RAM and PV usage)

so indeed, monitoring the workload in all namespaces seems to be the default

do you have the node-exporter pods up and running ?

I do agree with you however that the doc for newbies to prometheus/grafana/alertmanager is not a breeze ...

**Comment by parberge** [comment]
@christopheblin If you create an app in a new namespace (e.g not the same namespace as prometheus or default or kube-system) with a service and then you add a `serviceMonitor` resource  it won't be discovered. At least that's my problem and I believe this is what @trondhindenes want to have documented.

I have had the exact same experience as @trondhindenes . Very hard to find out how I can enable discovering targets (with `serviceMonitor`) in all namespaces.

**Comment by trondhindenes** [comment]
Sorry, I should have been more precise in my description. I'm not talking about generic metrics that prometheus can pull from kube-metrics, I'm talking about scraping metrics endpoints in custom namespaces.

For example, I have a pod running `my-super-api` in namespace `hello-i-am-namespace`. My super-api has a `/scrape` endpoint that I want prometheus to scrape for metrics.

Most documentation I've found is very "infrastructure-focused" and seems to kindof skip the part where Prometheus is used to scrape custom app metrics endpoints (which is IMHO one of the unique strenghts of prometheus). 

After hours of googling and trying to stich together information, this seems to be the values I need to pass to the helm chart in order for Prometheus to be willing to scrape pods in other namespaces:

```yaml
prometheus:
  prometheusSpec:
    podMonitorNamespaceSelector:
      matchExpressions:
      - key: non-existent-label
        operator: DoesNotExist
    podMonitorSelector:
      matchExpressions:
      - key: non-existent-label
        operator: DoesNotExist
    podMonitorSelectorNilUsesHelmValues: false
    ruleNamespaceSelector:
      matchExpressions:
      - key: non-existent-label
        operator: DoesNotExist
    serviceMonitorNamespaceSelector:
      matchExpressions:
      - key: non-existent-label
        operator: DoesNotExist
    serviceMonitorSelector:
      matchExpressions:
      - key: non-existent-label
        operator: DoesNotExist
    serviceMonitorSelectorNilUsesHelmValues: false
```

**Comment by christopheblin** [comment]
@trondhindenes 

ok, I get your point (and given that I did not try to scrape my own metrics yet, I've not been hitted by this problem yet and that will surely save my time :+1:)

and I totally agree with you when you say : 

> It's difficult to stich together enough information on how to configure this chart and not charts in general.

You find lots of doc around prometheus or grafana or prometheus-operator, but it is hard to find out how to use them when you are using this chart and you have to dig insides the templates/values to get a clue of what you need to do

I have the exact same kind of troubles to 
* create a custom dashboard in grafana (that survives when grafana restarts). 
* configure the alertmanager notifications 
* choose k8s components to monitor

So, like you, I am more or less in need for a "hey, if you are just starting, here's what you should do after installation"

However, I am grateful that this chart exists because there are so many components involved that I am not sure I could manage to use separate charts for each one ...

**Comment by austonpramodh** [comment]
> Sorry, I should have been more precise in my description. I'm not talking about generic metrics that prometheus can pull from kube-metrics, I'm talking about scraping metrics endpoints in custom namespaces.
> 
> For example, I have a pod running `my-super-api` in namespace `hello-i-am-namespace`. My super-api has a `/scrape` endpoint that I want prometheus to scrape for metrics.
> 
> Most documentation I've found is very "infrastructure-focused" and seems to kindof skip the part where Prometheus is used to scrape custom app metrics endpoints (which is IMHO one of the unique strenghts of prometheus).
> 
> After hours of googling and trying to stich together information, this seems to be the values I need to pass to the helm chart in order for Prometheus to be willing to scrape pods in other namespaces:
> 
> ```yaml
> prometheus:
>   prometheusSpec:
>     podMonitorNamespaceSelector:
>       matchExpressions:
>       - key: non-existent-label
>         operator: DoesNotExist
>     podMonitorSelector:
>       matchExpressions:
>       - key: non-existent-label
>         operator: DoesNotExist
>     podMonitorSelectorNilUsesHelmValues: false
>     ruleNamespaceSelector:
>       matchExpressions:
>       - key: non-existent-label
>         operator: DoesNotExist
>     serviceMonitorNamespaceSelector:
>       matchExpressions:
>       - key: non-existent-label
>         operator: DoesNotExist
>     serviceMonitorSelector:
>       matchExpressions:
>       - key: non-existent-label
>         operator: DoesNotExist
>     serviceMonitorSelectorNilUsesHelmValues: false
> ```
> 
> The documentation is a bit confusing and much of it sends me to the prometheus-operator repo. The "Configuration" link just sends me to Helm's documentation covering generic helm chart documentation. It's difficult to stich together enough information on how to configure _this_ chart and not charts in general. IMHO there should be a "hey if you just want prometheus to be able to scrape all your namespaces based on PodMonitor and ServiceMonitor objects, here's what you should do" part very visible in the readme for this repo.

I tried using the values provided by you. Unfortunately, it still doesn't seem to detect the services deployed in other namespaces. I might be doing something wrong as well, I am new to Prometheus.

![image](https://user-images.githubusercontent.com/5049050/135671923-cb7af27a-1dbe-4ad0-bfb9-2212f520241d.png)

**Comment by jwalton** [comment]
```yaml
    serviceMonitorNamespaceSelector:
      matchExpressions:
      - key: non-existent-label
        operator: DoesNotExist
    [snip]
```

All this "non-existent-label" hackery *ought* to be unnecessary.  According to [the docs](https://github.com/prometheus-operator/prometheus-operator/blob/e23ff77fceba6a5d9f190f5d1a123c87701dc964/pkg/apis/monitoring/v1/types.go#L96-L97), "Namespace's labels to match for ServiceMonitor discovery. If nil, only check own namespace."  But in the `serviceMonitorNamespaceSelector: {}` case, serviceMonitorNamespaceSelector is not nil, it is empty, and [an empty label selector should match all objects](https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#labelselector-v1-meta).

**Comment by giovannicandido** [comment]
> 
> 
> > @trondhindenes
> > ok, I get your point (and given that I did not try to scrape my own metrics yet, I've not been hitted by this problem yet and that will surely save my time 👍)
> > and I totally agree with you when you say :
> > > It's difficult to stich together enough information on how to configure this chart and not charts in general.
> > 
> > 
> > You find lots of doc around prometheus or grafana or prometheus-operator, but it is hard to find out how to use them when you are using this chart and you have to dig insides the templates/values to get a clue of what you need to do
> > I have the exact same kind of troubles to
> > ```
> > * create a custom dashboard in grafana (that survives when grafana restarts).
> > 
> > * configure the alertmanager notifications
> > 
> > * choose k8s components to monitor
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So, like you, I am more or less in need for a "hey, if you are just starting, here's what you should do after installation"
> > However, I am grateful that this chart exists because there are so many components involved that I am not sure I could manage to use separate charts for each one ...
> 
> Hey @trondhindenes How to configure grafana to survive restart with this chart and how to configure alertmanager email stmp configuration?

I figure out how to do it:

```yaml
alertmanager:
  config:
    global:
      smtp_from: from
      smtp_smarthost: host:port
      smtp_require_tls: true
      smtp_auth_username: username
      smtp_auth_password: password
    receivers:
    - name: 'null'
    - name: email
      email_configs:
      - send_resolved: true
        to: infra@kugelbit.com
grafana:
  persistence:
    enabled: true
    storageClassName: fast
```
