### ISSUE TITLE
[prometheus-kube-stack] fails to install when defining additionalPodMonitors

### ISSUE THREAD

**Issue by digiserg** [prometheus-community/helm-charts#1369]
### Describe the bug a clear and concise description of what the bug is.

Hi,

This happens to me on a **fresh** install of this helm chart when defining `additionalPodMonitors`

```
unable to recognize no matches for kind "PodMonitor" in version "monitoring.coreos.com/v1"
```

My current workaround is to comment them out, install the helm chart, adding them again and do a helm upgrade. 

### What's your helm version?

version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}

### What's your kubectl version?

v1.20.2

### Which chart?

prometheus-kube-stack

### What's the chart version?

18.0.12

### How to reproduce it?

Just do a helm install on a fresh build with no CRD installed using a values file like the example below

### Enter the changed values of values.yaml?

```yaml
prometheus:
  additionalPodMonitors:
    - name: "something"
      selector:
        matchLabels:
          app: mine
      namespaceSelector:
        matchNames:
          - app
      podMetricsEndpoints:
        - path: /metrics
          port: http
```

### Enter the command that you execute and failing/misfunctioning.

```sh
helm upgrade --install prom -f values.yaml prometheus-community/kube-prometheus-stack --version 18.0.12 --dry-run --debug -n monitoring
```
