### ISSUE TITLE
[prometheus-snmp-exporter] use custom snmp.yml

### ISSUE THREAD

**Issue by c0da** [prometheus-community/helm-charts#137]
I needed to generate a new snmp.yml (using the snmp exporter config generator) file in order to add my ReadyNAS 2120's MIBs, but I have no idea on how to apply this file to prometheus-snmp-exporter's chart. I've been struggling for a while, I've seen that probably I could use a configmap, but I wasn't able to to achieve it, and I couldn't find any examples anywhere..

Could anybody please point me on the right direction? It's driving me nuts :(

**Comment by jhedden** [comment]
I ran into something similar with the snmp-exporter helm chart. Using a newer image tag worked for me.

```
image:
  tag: v0.19.0

config: |
  custom_module:
    walk:
    - 1.3.6.1.2.1.2
    - 1.3.6.1.2.1.31.1.1
    ...
    ...
```
