### ISSUE TITLE
[prometheus-kube-stack] Strange behavior when ingress is specified with annotations.kubernetes.io/ingress.class

### ISSUE THREAD

**Issue by christopheblin** [prometheus-community/helm-charts#1380]
### Describe the bug a clear and concise description of what the bug is.

Specifying annotations.kubernetes.io/ingress.class has an inconsistent behavior

### What's your helm version?

version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"4966fd0dded6419fd23233a38c8905c67a3ea78e", GitTreeState:"clean", BuildDate:"2021-08-17T02:06:07Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

latest

### What happened?

in the values.yaml, do something like :

```
alertmanager:
  #configure the ingress
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: tools
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: monitoring-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - monitoring'
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      role: production
    hosts:
      - monitoring-alertmanager.tools.xxx.io
    paths:
      - "/"
```

> same probelm with grafana and prometheus BTW

when you run the install or upgrade command AND YOU DO NOT HAVE THE INGRESS yet : 

```
% helm upgrade prometheus-operator prometheus-community/kube-prometheus-stack -f values.yaml --namespace monitoring 
Error: UPGRADE FAILED: failed to create resource: Ingress.extensions "prometheus-operator-kube-p-alertmanager" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "tools": can not be set when the class field is also set
```

so I remove the annotations, OK !

```
helm upgrade prometheus-operator prometheus-community/kube-prometheus-stack -f values.yaml --namespace monitoring
Release "prometheus-operator" has been upgraded. Happy Helming!
NAME: prometheus-operator
LAST DEPLOYED: Tue Sep 28 13:44:11 2021
NAMESPACE: monitoring
STATUS: deployed
REVISION: 43
NOTES:
kube-prometheus-stack has been installed. Check its status by running:
  kubectl --namespace monitoring get pods -l "release=prometheus-operator"

Visit https://github.com/prometheus-operator/kube-prometheus for instructions on how to create & configure Alertmanager and Prometheus instances using the Operator.
```

Now, just put back the annotation in the values.yaml and run the helm upgrade : the helm upgrade succeeds AND the annotation is correctly set in the ingress

NOTE : we need this annotations because, in our setup, this is how the correct nginx controller is triggered (i.e the ingress will correctly be picked up by the ingress inside the tools if the host is tools.xxx.io (xxx is not our real domain, obviusly :))

### What you expected to happen?

Either the chart rejects the annotation all the time for a good reason or the chart always accept the annotation

### How to reproduce it?

see what happenend

### Enter the changed values of values.yaml?

see what happenend

### Enter the command that you execute and failing/misfunctioning.

see what happenend
