### ISSUE TITLE
prometheus-kube-stack-How to change Prometheus image to my local_ECR in Values file

### ISSUE THREAD

**Issue by srreddy2020** [prometheus-community/helm-charts#1389]
### Describe the bug a clear and concise description of what the bug is.

Hi Team,
When we are deploying Prometheus stack with Helm ,its taking the images from default like  quay.io/prometheus/prometheus:v2.28.1.
But i want use my ECR Images

### What's your helm version?

Helm 3

### What's your kubectl version?

Client Version: v1.16.8-eks-e16311 Server Version: v1.19.13-eks-8df270

### Which chart?

https://prometheus-community.github.io/helm-charts

### What's the chart version?

19.0.1

### What happened?

I added my local ECR_Repo_Image path  to values file but still its using the default image from stack
```
prometheus:
  prometheusSpec:
    scrapeInterval: "10s"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: aws-efs
          accessModes: 
          - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
   image:
    repository: ecr repo
    tag: prometheus.v2.28.1
    sha: ""
    version: v2.28.1
```

-------------------------------
```
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: aws-efs
          accessModes: 
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
    image:          
      repository: ECR repo
      tag: alertmanager.v0.22.2
      sha: ""
      version: v0.22.2
```

### What you expected to happen?

I want to use my ECR repo images 

### Enter the changed values of values.yaml?

```
prometheus:
  prometheusSpec:
    scrapeInterval: "10s"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: aws-efs
          accessModes: 
          - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
   image:
    repository: ecr repo
    tag: prometheus.v2.28.1
    sha: ""
    version: v2.28.1
```
-------------------------------
```
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: aws-efs
          accessModes: 
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
    image:          
      repository: ECR repo
      tag: alertmanager.v0.22.2
      sha: ""
      version: v0.22.2
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade monitoring prometheus-community/kube-prometheus-stack -n monitoring -f values.yaml

**Comment by Mark-Smithh** [comment]
I am experiencing the same issue myself.  I saw the issue in chart version 15.4.6.  I then bumped to chart version 19.0.1 and am still seeing the same behavior.  I am trying to use an image from an internal container registry, and passing it on the values.yaml does not work.  I have noticed that if prometheusSpec:image:repository and tag are passed the statefulset is not updated at all.  If I manually edit the image in the prometheus-prometheus-kube-prometheus-prometheus statefulset then it loads my image.  

values.yaml snippet below
```YAML
kube-prometheus-stack:
  prometheusOperator:
    prometheusDefaultBaseImage:  "{{ K8S_REPOSITORY }}"

  prometheus:
    prometheusSpec:
      image:
        repository: "{{ K8S_REPOSITORY }}" # IF THIS IS SET THE STATEFULSET DOES NOT UPDATE
        tag: "{{ K8S_TAG }}" # IF THIS IS SET THE STATEFULSET DOES NOT UPDATE
```
