### ISSUE TITLE
[kube-prometheus-stack] Better ingress / alerting / serviceMonitor customizability to allow for seamless oauth proxying

### ISSUE THREAD

**Issue by cwrau** [prometheus-community/helm-charts#1391]
### Is your feature request related to a problem ?

Yes, I'm trying to proxy Prometheus and Alertmanager through an OAuth-proxy.

I achieved the goal by using a sidecar container but ran into the problem that the Prometheus->Alertmanager communication failed because of authentication problems.

Also, the Service-Monitor will for the Alertmanager and Prometheus also fail with authentication problems which I couldn't work around, currently, we're just not gathering metrics for them 🤷

It looks like we're gonna have to set up the OAuth-proxy externally and point it to the (hopefully) stable service name if we want to monitor the Prometheus and the Alertmanager.

### Describe the solution you'd like.

I want to set the port used by the ingress of the Alertmanager to a different one than the one used by the Prometheus alerting configuration and the Service-Monitors for Alertmanager and Prometheus

Specifically, the values `.Values.alertmanager.service.port` and `.Values.alertmanager.alertmanagerSpec.portName` need to be decoupled. Currently they are used for the service in the same service-port.

Maybe a new value `.Values.alertmanager.alertingPort` or `.Values.promtheus.alerting.portName`. Then used with a default to the current value, `.Values.alertmanager.alertmanagerSpec.portName`. And of course an `monitoringPort` so that the serviceMonitor is going to work again

Even better would be an integrated OAuth-proxy solution, like https://github.com/jaegertracing/helm-charts/tree/main/charts/jaeger#oauth2-sidecar, which we can just enable and configure.

### Describe alternatives you've considered.

We're currently setting the following values to achieve this;

```yaml
alertmanager:
  alertmanagerSpec:
    containers:
      - args:
          - --config=/etc/oauth2-proxy/oauth2-proxy.cfg
          - --http-address=0.0.0.0:4180
          - --upstream=http://localhost:9093
          - --skip-provider-button=true
          - --provider=oidc
        env:
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: client-id
                name: prometheus-operator-oauth-secrets
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: client-secret
                name: prometheus-operator-oauth-secrets
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                key: cookie-secret
                name: prometheus-operator-oauth-secrets
        image: bitnami/oauth2-proxy:7.1.3
        name: oauth-proxy
        ports:
          - containerPort: 4180
            name: oauth-proxy
        volumeMounts:
          - mountPath: /etc/oauth2-proxy
            name: oauth-configuration
    replicas: 3
    volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-operator-oauth-configuration
        name: oauth-configuration
  config:
    global:
      pagerduty_url: https://events.eu.pagerduty.com/v2/enqueue
    receivers:
      - name: pagerduty
        pagerduty_configs:
          - routing_key: REDACTED
      - name: 'null'
    route:
      receiver: pagerduty
  enabled: true
  ingress:
    enabled: true
    hosts:
      - alertmanager.domain
    tls:
      - hosts:
          - alertmanager.domain
        secretName: cluster-wildcard-certificate
  service:
    port: 4180
    targetPort: oauth-proxy
prometheus:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - prometheus.domain
    tls:
      - hosts:
          - prometheus.domain
        secretName: cluster-wildcard-certificate
  prometheusSpec:
    alertingEndpoints:
      - apiVersion: v2
        name: prometheus-operator-kube-p-alertmanager
        namespace: monitoring
        pathPrefix: /
        port: web-unauthenticated
    containers:
      - args:
          - --config=/etc/oauth2-proxy/oauth2-proxy.cfg
          - --http-address=0.0.0.0:4180
          - --upstream=http://localhost:9090
          - --skip-provider-button=true
          - --provider=oidc
        env:
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: client-id
                name: prometheus-operator-oauth-secrets
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: client-secret
                name: prometheus-operator-oauth-secrets
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                key: cookie-secret
                name: prometheus-operator-oauth-secrets
        image: bitnami/oauth2-proxy:7.1.3
        name: oauth-proxy
        ports:
          - containerPort: 4180
            name: oauth-proxy
        volumeMounts:
          - mountPath: /etc/oauth2-proxy
            name: oauth-configuration
    volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-operator-oauth-configuration
        name: oauth-configuration
  service:
    additionalPorts:
      - name: web-unauthenticated
        port: 9090
        targetPort: web
    port: 4180
    targetPort: oauth-proxy
```

Note that we override the alerting config by ourselves just to set the `port`;

```yaml
    alertingEndpoints:
      - apiVersion: v2
        name: prometheus-operator-kube-p-alertmanager
        namespace: monitoring
        pathPrefix: /
        port: web-unauthenticated
```

hoping that those values won't ever change 😕
