### ISSUE TITLE
[prometheus-adapter] hpa can find custom metric but metric doesn't show up in prometheus?

### ISSUE THREAD

**Issue by perezjasonr** [prometheus-community/helm-charts#1399]
### Describe the bug a clear and concise description of what the bug is.

For some reason, I can tell pods to use a custom metric, provided through prometheus adapter, hpa objects claim to be able to find it. However, I cannot find it in prometheus itself, from querying.

The series query I base the metricsQuery off of seems to work fine. Also putting an example metricsQuery seems to also work:

ex:
 if the seriesQuery is a metric: "some_exposed_metric"
 i tried:
 sum(some_exposed_metric)
 
 and that works in prometheus, but the name I provide in "name.as" doesn't show up, again, yet hpa says it can find it and is using it.
 
 any ideas on what this could be? is it a bug?

### What's your helm version?

argocd's helm (its v3)

### What's your kubectl version?

1.22

### Which chart?

prometheus-adapter

### What's the chart version?

2.17.0

### What happened?

hpa claims to be able to find a metric provided in my custom section. Yet I cannot get it to show up in prometheus.

### What you expected to happen?

i should be able to view the metric in promethus.

### How to reproduce it?

set up a custom metric, I did the following:

```
custom:
  - seriesQuery: 'some_metric'
    resources:
      overrides:
        namespace: {resource: "namespace"}
        pod: {resource: "pod"}
    name:
      as: the_name_im_looking_for
    metricsQuery: 'sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>) * 100'
```

for me, "some metric" shows up.
sum(some_metric) *100 also shows up
but not "the_name_im_looking_for"

### Enter the changed values of values.yaml?

```
prometheus:
  url: http://kube-prometheus-stack-prometheus.monitoring.svc
  port: 9090
rules:
  default: true
  custom:
  - seriesQuery: 'gitlab_runner_concurrent_saturation'
    resources:
      overrides:
        namespace: {resource: "namespace"}
        pod: {resource: "pod"}
    name:
      as: gitlab_runner_concurrent_saturation_percent
    metricsQuery: 'sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>) * 100'
  resource:
    cpu:
      containerQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, container!=""}[3m])) by (<<.GroupBy>>)
      nodeQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, id='/'}[3m])) by (<<.GroupBy>>)
      resources:
        overrides:
          node:
            resource: node
          namespace:
            resource: namespace
          pod:
            resource: pod
      containerLabel: container
    memory:
      containerQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>, container!=""}) by (<<.GroupBy>>)
      nodeQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>,id='/'}) by (<<.GroupBy>>)
      resources:
        overrides:
          node:
            resource: node
          namespace:
            resource: namespace
          pod:
            resource: pod
      containerLabel: container
    window: 3m
```

### Enter the command that you execute and failing/misfunctioning.

in prometheus i tried to query for the name.as item under custom section

### Anything else we need to know?

not at this time but let me know if i can provide any further info.
or if I'm missing something obvious sorry.
