### ISSUE TITLE
Grafana - SMTP Configuration - Help

### ISSUE THREAD

**Issue by johnhydemtm365** [prometheus-community/helm-charts#1427]
Hi, I have installed this chart...
https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

But I cannot see anywhere where I can change the SMTP configuration using the values.yml 

Am I missing something?

Thanks
John

**Comment by johnhydemtm365** [comment]
Hey up anyone?

**Comment by MTRNord** [comment]
Any update?

**Comment by johnhydemtm365** [comment]
Hey up, not sure why this is closed, it would be good to get a response..?

**Comment by locomoco28** [comment]
Taking a look at the [Chart.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/Chart.yaml) reveals that this chart depends on the official `https://grafana.github.io/helm-charts` Grafana repo and uses the `grafana` chart. You can take the [`grafana` chart's `values.yaml`](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L613) as reference to configure it. Just put everything in the `values.yaml` under the `grafana` key. (And don't forget to update the `grafana.ini` as stated in the linked `values.yaml`)

```yaml
grafana:
  grafana.ini:
    smtp:
      enabled: true
      host: smtp.gmail.com:587 # Gmail example
  smtp:
    existingSecret: grafana-smtp-credentials
    # You can optionally change the keys in your secret
    #userKey: "user"
    #passwordKey: "password"
```

You basically just need to set the `existingSecret` value to whatever you want to call your secret, and then you can just use `user` and `password` as the corresponding keys as those are the default values from the Grafana chart (or you can configure them as above)

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-smtp-credentials
  namespace: my-grafana-namespace
data:
  password: "base64encoded password"
  user: "base64encoded username"
type: Opaque
```
