### ISSUE TITLE
[prometheus-kube-stack] kube_*_labels are "empty"

### ISSUE THREAD

**Issue by h4wkmoon** [prometheus-community/helm-charts#1444]
### Describe the bug a clear and concise description of what the bug is.

Hi, 
All the metrics that are supposed to have labels based on kubernetes object labels don't.
ex : kube_namespace_labels, kube_node_labels

### What's your helm version?

version.BuildInfo{Version:"v3.5.0+6.el8", GitCommit:"77fb4bd2415712e8bfebe943389c404893ad53ce", GitTreeState:"clean", GoVersion:"go1.14.12"}

### What's your kubectl version?

client : v1.21 // Server  v1.20

### Which chart?

prometheus-kube-stack

### What's the chart version?

19.1.0  

### What happened?

No kubernetes labels on kube_*_labels metrics.

### What you expected to happen?

Actual kubernetes labels on kube_*_labels metrics.

### Enter the changed values of values.yaml?

(From fluxcd helmrelease)
```yaml
  values:
    kube-state-metrics:  
      image:
        tag: v2.2.1  # Because I need configmap labels metric.
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    grafana:
      plugins:
      - michaeldmoore-multistat-panel
      - marcusolsson-hexmap-panel
      datasources: 
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: Loki
            type: loki
            url: http://loki:3100
      ingress: 
        enabled: true
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: "vault-issuer"
          cert-manager.io/common-name: "[redacted]"
        ingressClassName: kong-internal
        hosts:
        - "[redacted]"
        tls: 
        - secretName: "[redacted]"
          hosts:
          - "[redacted]"
      persistence:
        type: pvc
        enabled: true
    prometheus:
      enabled: true
      prometheusSpec:
        ruleSelectorNilUsesHelmValues: false
        ruleSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorSelector: {}
        probeSelectorNilUsesHelmValues: false
        probeSelector: {}
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 1Gi
    alertmanager:
      enabled: true
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 1Gi
```

### Enter the command that you execute and failing/misfunctioning.

FluxCD takes care of it.

### Anything else we need to know?

I guess the relabeling configs aren't correct, but I can't figure out what to do.
There should be an option in the cahrt to activate the correct labeling config. I'd be willing to push an PR to implement such an option, but I need the prometheus config for that.
