### ISSUE TITLE
[kube-prometheus-stack] Failure of kube-prometheus-s-admission-create on eks

### ISSUE THREAD

**Issue by skluthe** [prometheus-community/helm-charts#1456]
### Describe the bug a clear and concise description of what the bug is.

The helm chart is having issues (specifically when deployed on eks as it worked on a local cluster) with finding the admission secret causing the helm install to fail.

### What's your helm version?

version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691",  GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"windows/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

19.2.2

### What happened?

The deployment of the helm chart seems to get stuck here:
![image](https://user-images.githubusercontent.com/23664304/138473125-c37aa67b-2acf-4105-bc85-698fc499b75d.png)

When looking at the logs I'm getting the following.
```
{"err":"secrets \"dops-mon-kube-prometheus-s-admission\" is forbidden: User \"system:serviceaccount:monitoring:dops-mon-kube-prometheus-s-admission\" cannot get resource \"secrets\" in API group \"\" in the namespace \"default\"","level":"fatal","msg":"error getting secret","source":"k8s/k8s.go:110","time":"2021-10-22T14:31:29Z"}
```

It looks like the service account is created with access to the secret. It also looks like it's looking for the default namespace. It's being deployed into the `monitoring` namespace though.

![image](https://user-images.githubusercontent.com/23664304/138473626-b76f771d-48d1-4fd6-bc91-2ad0986547c9.png)

### What you expected to happen?

Deployment to succeed.

### How to reproduce it?

spin up an eks cluster and run the following:
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm dependency build
helm template --include-crds --release-name dops-mon . > all.yaml
kustomize build | kubectl apply -n monitoring -f -
```
with the following kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./all.yaml

namespace: monitoring
```

### Enter the changed values of values.yaml?

Tried this after encountering the first failure but it didn't change the output. Other than this it's blank:
```
prometheusOperator:
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false
```

### Enter the command that you execute and failing/misfunctioning.

I am using argo-cd and kustomized-helm in order to deploy with the following custom plugin:
```yaml
    - name: mon-kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && helm repo update && helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template --include-crds --release-name dops-mon . > all.yaml && kustomize build"]
```

This essentially runs the following (just trying to be thorough):
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm dependency build
helm template --include-crds --release-name dops-mon . > all.yaml
kustomize build | kubectl apply -n monitoring -f -
```

### Anything else we need to know?

Definitely understand that this may not be a supported use case/deployment strategy. If not, just let me know and I'll try finding another way to deploy.

**Comment by skluthe** [comment]
Is there anything I can add that would give this more detail?

**Comment by skluthe** [comment]
## Solution
Instead of using the kustomized-helm plugin above, use the helm utility that's built into kustomize: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md

This is what my kustomization.yaml looks like now:
```yaml
helmCharts:
- name: kube-prometheus-stack
  releaseName: kustom-prom
  version: 19.2.1
  repo: https://prometheus-community.github.io/helm-charts
  valuesFile: values.yaml
```
then change the configmap for argo to the following for the configManagementPlugins section:
```yaml
  configManagementPlugins: |
    - name: kustomized-helm
      generate:
        command: [sh, -c]
        args: ["kustomize build --enable-helm"]
```

Once this is done, you'll want to make sure you override the namespace in your values.yaml file:
```yaml
namespaceOverride: "monitoring"
```

Then it should deploy correctly.
