### ISSUE TITLE
[prometheus-kube-stack] Problem with storage and second replica

### ISSUE THREAD

**Issue by ws-prive** [prometheus-community/helm-charts#1471]
### Describe the bug a clear and concise description of what the bug is.

When using more than 1 replica, the second replica says that the database is locked. When I start a shell and look at the mount there is indeed a lock. It looks like the 1st and 2nd replica are using the same storage.

### What's your helm version?

3.6.3

### What's your kubectl version?

1.22.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

19.2.2

### What happened?

The error show at the second replica is:

```
level=error ts=2021-10-31T17:26:25.884Z caller=main.go:917 err="opening storage failed: lock DB directory: resource temporarily unavailable"
```
Complete log of the pod:
```
level=info ts=2021-10-31T17:26:25.871Z caller=main.go:443 msg="Starting Prometheus" version="(version=2.28.1, branch=HEAD, revision=b0944590a1c9a6b35dc5a696869f75f422b107a1)"
level=info ts=2021-10-31T17:26:25.871Z caller=main.go:448 build_context="(go=go1.16.5, user=root@2915dd495090, date=20210701-15:20:10)"
level=info ts=2021-10-31T17:26:25.871Z caller=main.go:449 host_details="(Linux 5.4.0-86-generic #97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 x86_64 prometheus-kube-prometheus-stack-prometheus-1 (none))"
level=info ts=2021-10-31T17:26:25.871Z caller=main.go:450 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2021-10-31T17:26:25.871Z caller=main.go:451 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2021-10-31T17:26:25.878Z caller=web.go:541 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2021-10-31T17:26:25.878Z caller=main.go:824 msg="Starting TSDB ..."
level=info ts=2021-10-31T17:26:25.882Z caller=tls_config.go:227 component=web msg="TLS is disabled." http2=false
level=warn ts=2021-10-31T17:26:25.883Z caller=db.go:676 component=tsdb msg="A TSDB lockfile from a previous execution already existed. It was replaced" file=/prometheus/lock
level=info ts=2021-10-31T17:26:25.884Z caller=main.go:697 msg="Stopping scrape discovery manager..."
level=info ts=2021-10-31T17:26:25.884Z caller=main.go:711 msg="Stopping notify discovery manager..."
level=info ts=2021-10-31T17:26:25.884Z caller=main.go:733 msg="Stopping scrape manager..."
level=info ts=2021-10-31T17:26:25.884Z caller=manager.go:934 component="rule manager" msg="Stopping rule manager..."
level=info ts=2021-10-31T17:26:25.884Z caller=manager.go:944 component="rule manager" msg="Rule manager stopped"
level=info ts=2021-10-31T17:26:25.884Z caller=notifier.go:601 component=notifier msg="Stopping notification manager..."
level=info ts=2021-10-31T17:26:25.884Z caller=main.go:908 msg="Notifier manager stopped"
level=info ts=2021-10-31T17:26:25.884Z caller=main.go:693 msg="Scrape discovery manager stopped"
level=info ts=2021-10-31T17:26:25.884Z caller=main.go:707 msg="Notify discovery manager stopped"
level=info ts=2021-10-31T17:26:25.884Z caller=main.go:727 msg="Scrape manager stopped"
level=error ts=2021-10-31T17:26:25.884Z caller=main.go:917 err="opening storage failed: lock DB directory: resource temporarily unavailable"
```

### What you expected to happen?

No errors in the second replica

### How to reproduce it?

Execute yaml with enclosed values file and have a default storage-class

### Enter the changed values of values.yaml?

```
prometheus:
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
  thanosServiceExternal:
    enabled: true
  prometheusSpec: 
    replicas: 2                             # work in High-Availability mode
    retention: 12h                          # we only need a few hours of retenion, since the rest is uploaded to blob
    serviceMonitorNamespaceSelector:
      any: true
    externalLabels:                         # a cool way to add default labels to all metrics 
      geo: nl          
      region: nb
      name: test-cluster
    podAntiAffinity: "hard"
    initContainers: #https://stackoverflow.com/questions/64621872/prometheus-operator-error-opening-query-log-file-permission-denied
      - name: prometheus-data-permission-fix
        image: busybox
        securityContext:
          runAsUser: 65534
          runAsGroup: 65534
          runAsNonRoot: true
          fsGroup: 65534
        command: ["/bin/sh", "-c"]
        args:
          - echo starting chown/chmod;
            chown -R "65534:65534" /prometheus;
            chmod -R 777 /prometheus;
            echo done chown/chmod;
        volumeMounts:
        - name: prometheus-kube-prometheus-stack-prometheus-db
          mountPath: /prometheus
          subPath: ""      
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi    
    disableCompaction: true
    thanos:
      objectStorageConfig:
        name: thanos-objstore-config
        key: s3_config.yaml
grafana:
  enabled: false
  initChownData:
    enabled: false

```

### Enter the command that you execute and failing/misfunctioning.

```
helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack -f override-prometheus-values.yaml \
  --install \
  --version 19.2.2 \
  --namespace monitoring \
  --create-namespace
```

### Anything else we need to know?

I do have 1 master and 2 workers.
