### ISSUE TITLE
[prometheus-kube-stack] Resouces limits not set for kubeStateMetrics and nodeExporter

### ISSUE THREAD

**Issue by tomme87** [prometheus-community/helm-charts#1478]
### Describe the bug a clear and concise description of what the bug is.

When setting resource limits on nodeExporter and kubeStateMetrics it does not apply after helm upgrade.

### What's your helm version?

version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17.1"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-alpha.2", GitCommit:"ee297b6f4d78daaf2f71c78a05203698581ca40a", GitTreeState:"clean", BuildDate:"2020-10-13T18:56:04Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"881d4a5a3c0f4036c714cfb601b377c4c72de543", GitTreeState:"clean", BuildDate:"2021-10-21T05:13:01Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

19.2.2

### What happened?

nothing

### What you expected to happen?

resource limits set on the containers

### How to reproduce it?

set resoruce limits for nodeExporter and kubeStateMetrics

### Enter the changed values of values.yaml?
```yaml
kubeStateMetrics:
  resources:
    requests:
      memory: 30Mi
      cpu: 10m
    limits:
      memory: 60Mi
      cpu: 200m

nodeExporter:
  resources:
    requests:
      memory: 30Mi
      cpu: 30m
    limits:
      memory: 60Mi
      cpu: 200m
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade prometheus-stack prometheus-community/kube-prometheus-stack -f my-values.yaml --namespace monitoring
