### ISSUE TITLE
[prometheus-elasticsearch-exporter] Automatically insert prometheus scrape annotations

### ISSUE THREAD

**Issue by ook** [prometheus-community/helm-charts#1481]
### Is your feature request related to a problem ?

Exporter `prometheus-elasticsearch-exporter` provide a way to expose a `/metric` endpoint compatible with prometheus system.
This helm chart should publish (or at least have a switch to let publish) the autodiscovery annotations for prometheus.

### Describe the solution you'd like.

The exporter pod should embed the following snippet:

```yaml
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9108'
```

### Describe alternatives you've considered.

NONE
