### ISSUE TITLE
[blackbox-exporter] Service labels are not matching

### ISSUE THREAD

**Issue by mbaykara** [prometheus-community/helm-charts#1489]
### Describe the bug a clear and concise description of what the bug is.

declaring labels for ServiceMonitor does not match Service labels and Prometheus does not fetch metrics from blackbox exporter. This issue is occurring with chart version 5.3.0. In the previous version like 5.0.3, it works like charm. As I see from the commits the in Service yaml the corresponding place has been changed.

### What's your helm version?

version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.6"}

### What's your kubectl version?

"v1.22.2"

### Which chart?

blackbox-exporter

### What's the chart version?

5.3.0

### What happened?

Prometheus does not get metrics from blackbox exporter

### What you expected to happen?

Seeing BlackBox metrics on Prometheus UI

### How to reproduce it?

I assume the Prometheus is already installed

`helm install blackbox-exporter -f custom-values.yaml prometheus-community/prometheus-blackbox-exporter`

### Enter the changed values of values.yaml?

custom-values.yaml
```
serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a prometheus operator
  ## https://github.com/coreos/prometheus-operator
  ##
  enabled: true

  # Default values that will be used for all ServiceMonitors created by `targets`
  defaults:
    additionalMetricsRelabels:
      release: prometheus
    labels: {}
    interval: 30s
    scrapeTimeout: 30s
    module: http_2xx
  ## scheme: HTTP scheme to use for scraping. Can be used with `tlsConfig` for example if using istio mTLS.
  scheme: http
  ## tlsConfig: TLS configuration to use when scraping the endpoint. For example if using istio mTLS.
  ## Of type: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#tlsconfig
  tlsConfig: {}
  bearerTokenFile:

  targets:
    - name: u2be                    # Human readable URL that will appear in Prometheus / AlertManager
      url: https://youtube.com/  # The URL that blackbox will scrape
      labels:
        release: prometheus
        app: blackbox-exporter-prometheus-blackbox-exporter                        # Map of labels for ServiceMonitor. Overrides value set in `defaults`
      interval: 60s                    # Scraping interval. Overrides value set in `defaults`
      scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
      module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`
      additionalMetricsRelabels: {}   
```

### Enter the command that you execute and failing/misfunctioning.

NOPE

### Anything else we need to know?

NOPE

**Comment by mbaykara** [comment]
Here is how service yaml looks with custom value

chart version 5.3.0
```
# Source: prometheus-blackbox-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: blackbox-export-prometheus-blackbox-exporter
  labels:
    {}
spec:
  type: ClusterIP
  ports:
    - port: 9115
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: blackbox-export
```
And here with chart version 5.0.3 with same custom values 

```
# Source: prometheus-blackbox-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: blackbox-export-prometheus-blackbox-exporter
  labels:
    helm.sh/chart: prometheus-blackbox-exporter-5.0.3
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: blackbox-export
    app.kubernetes.io/version: "0.19.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9115
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: blackbox-export
```
