### ISSUE TITLE
kube-prometheus-stack 1.20.7 fails to install with argocd

### ISSUE THREAD

**Issue by KlavsKlavsen** [prometheus-community/helm-charts#1507]
### Describe the bug a clear and concise description of what the bug is.

First it fails with : #4355 
And when I select argocd replace (to use create instead) - it works, but it then fails with this error:
Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://latest-kube-prometheus-sta-operator.default.svc:443/admission-prometheusrules/mutate?timeout=10s": service "latest-kube-prometheus-sta-operator" not found

and no such service is defined anywhere?

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:
Install with argocd 2.1.6

**Environment**
kubernetes 1.20.7.

anything else of interest I can provide? 

### What's your helm version?

helm 3.6.3

### What's your kubectl version?

1.20.7

### Which chart?

kube-prometheus-stack

### What's the chart version?

1.20.7

### What happened?

Many of the resources simply fail with this error:
Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://latest-kube-prometheus-sta-operator.default.svc:443/admission-prometheusrules/mutate?timeout=10s": service "latest-kube-prometheus-sta-operator" not found

### Enter the changed values of values.yaml?

```
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: rook-ceph-block
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
  grafana:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: traefik-cert-manager
      hosts:
      - grafana.kam.example.com
      tls:
      - secretName: kube-prometheus-grafana-tls
        hosts:
        - grafana.kam.example.com
    analytics:
      check_for_updates: false
    env:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: true
    envValueFrom:
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
        secretKeyRef:
            name: kube-prometheus-stack-grafana
            key: grafana-keycloak-secret
    grafana.ini:
      auth:
        disable_login_form: true
        oauth_auto_login: true
        disable_signout_menu: false
        signout_redirect_url: https://keycloak.kam.example.com/auth/realms/devops/protocol/openid-connect/logout?redirect_uri=https://grafana.kam.example.com
      server:
        root_url: https://grafana.kam.example.com
      auth.generic_oauth:
        enabled: true
        allow_sign_up: true
        scopes: openid profile email
        name: Keycloak
        auth_url: https://keycloak.kam.example.com/auth/realms/devops/protocol/openid-connect/auth
        token_url: https://keycloak.kam.example.com/auth/realms/devops/protocol/openid-connect/token
        api_url: https://keycloak.kam.example.com/auth/realms/devops/protocol/openid-connect/userinfo
        client_id: grafana
        role_attribute_path: contains(not_null(roles[*],''), 'Admin') && 'Admin' || contains(not_null(roles[*],''), 'Editor') && 'Editor' || contains(not_null(roles[*],''), 'Viewer') && 'Viewer'|| ''
  alertmanager:
    alertmanagerSpec:
      # Secret, containing alertmanager.yaml config MUST be named alertmanager-kube-prometheus-stack-alertmanager
      useExistingSecret: true
      secrets:
       - "example-clientcert"

  namespaceOverride: monitoring
  alertmanager:
    alertmanagerSpec:
      resources: 
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 20Mi
  prometheusOperator:
    resources: 
      limits:
        cpu: 100m
        memory: 80Mi
      requests:
        cpu: 10m
        memory: 30Mi
  grafana:
    ingress:
      enabled: true
      annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
      labels: {}

    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    # ingressClassName: nginx
  prometheus:
    # defaults - should be adjusted per-cluster, as it depends on amount of metrics.
    prometheusSpec:
      resources: 
        limits:
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 200Mi
      storageSpec: 
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
```

### Enter the command that you execute and failing/misfunctioning.

Using argocd currently. Trying to reproduce with Helm.

### Anything else we need to know?

We're trying to reproduce now with plain helm install
