### ISSUE TITLE
[kube-prometheus-stack] How to add thanos sidecar args

### ISSUE THREAD

**Issue by fannw** [prometheus-community/helm-charts#1517]
### Is your feature request related to a problem ?

Maybe, the story is I only use prometheus before, I want to integrate thanos and put the old prometheus metrics to S3, so I need this parameter "--shipper.upload-compacted=true", but I can't find where I can add it.  I also try to add the parameter to prometheus statefulset, but it may reset by prometheus operator. So when I check prometheus stateful again, the parameter gone.

https://thanos.io/tip/components/sidecar.md/#upload-compacted-blocks

### Describe the solution you'd like.

Can add --shipper.upload-compacted to thanos sidecar args

### Describe alternatives you've considered.

Any workaround?

**Comment by aviralharsh** [comment]
Hey hi @fannw , i am trying to deploy thanos with this helm chart but it seems its a little complex. Can you please share how you are doing this ?

**Comment by fannw** [comment]
@aviralharsh 
kube-prometheus-stack, install thanos sidecar, after install, check if thanos-sidecar container in prometheus pod.
I use bitnami-thanos to install thanos other components.
https://github.com/bitnami/charts/tree/master/bitnami/thanos/

thanos-storage-config.yaml
```
type: s3
config:
  bucket: xxx
  endpoint: s3.ap-northeast-1.amazonaws.com
```

Create secret
```
kubectl -n prometheus create secret generic thanos-objstore-config --from-file=thanos-storage-config.yaml=thanos-storage-config.yaml
```

values.yaml
```
    ## Thanos configuration allows configuring various aspects of a Prometheus server in a Thanos environment.
    ## This section is experimental, it may change significantly without deprecation notice in any release.
    ## This is experimental and may change significantly without backward compatibility in any release.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#thanosspec
    ##
    thanos:
      objectStorageConfig:
        key: "thanos-storage-config.yaml"
        name: "thanos-objstore-config"


  # Service for thanos service discovery on sidecar
  # Enable this can make Thanos Query can use
  # `--store=dnssrv+_grpc._tcp.${kube-prometheus-stack.fullname}-thanos-discovery.${namespace}.svc.cluster.local` to discovery
  # Thanos sidecar on prometheus nodes
  # (Please remember to change ${kube-prometheus-stack.fullname} and ${namespace}. Not just copy and paste!)
  thanosService:
    enabled: enable
    annotations: {}
    labels: {}

  ## Thanos side-car image when configured
  ##
  thanosImage:
    repository: quay.io/thanos/thanos
    tag: v0.17.2
    sha: ""
```

bitnami-thanos
values.yaml
```
objstoreConfig: |-
  type: S3
  config:
    bucket: xxxxx
    endpoint: s3.ap-northeast-1.amazonaws.com
    #    service_account: |-
    #      {
    #        "type": "prometheus-prometheus-oper-prometheus",
    #      }

## Bitnami Thanos image
## ref: https://hub.docker.com/r/bitnami/thanos/tags/
## @param image.registry Thanos image registry
## @param image.repository Thanos image repository
## @param image.tag Thanos image tag (immutable tags are recommended)
## @param image.pullPolicy Thanos image pull policy
## @param image.pullSecrets Specify docker-registry secret names as an array
##
image:
  registry: docker.io
  repository: bitnami/thanos
  tag: 0.22.0-scratch-r4
  ## Specify a imagePullPolicy. Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: []

existingObjstoreSecretItems: []
## @param existingServiceAccount Provide a common service account to be shared with all components
##
existingServiceAccount: "prometheus-prometheus-oper-prometheus"

query:
  enabled: true
  ## @param query.replicaCount Number of Thanos Query replicas to deploy
  ##
  replicaCount: 1

  ## Dynamically configure store APIs using DNS discovery
  ## @param query.dnsDiscovery.enabled Enable store APIs discovery via DNS
  ## @param query.dnsDiscovery.sidecarsService Sidecars service name to discover them using DNS discovery
  ## @param query.dnsDiscovery.sidecarsNamespace Sidecars namespace to discover them using DNS discovery
  ##
  ##  dnsDiscovery:
  ##    enabled: true
  ##    sidecarsService: prometheus-stack-sre-prome-thanos-discovery
  ##    sidecarsNamespace: prometheus
  ##    stores:
  ##      - thanos-storegateway.prometheus.svc.cluster.local:10901
  ##        #      - prometheus-operated.prometheus.svc.cluster.local:9090
  stores:
    - thanos-storegateway.prometheus.svc.cluster.local:10901

queryFrontend:
  enabled: true

bucketweb:
  enabled: true
  refresh: "10m"

compactor:
  enabled: true
  ## Resolution and Retention flags
  ## @param compactor.retentionResolutionRaw Resolution and Retention flag
  ## @param compactor.retentionResolution5m Resolution and Retention flag
  ## @param compactor.retentionResolution1h Resolution and Retention flag
  ##
  retentionResolutionRaw: 180d
  retentionResolution5m: 2y
  retentionResolution1h: 5y

  ## Persistence parameters
  ##
  persistence:
    ## @param compactor.persistence.enabled Enable data persistence using PVC(s) on Thanos Compactor pods
    ##
    enabled: true
    ## @param compactor.persistence.storageClass Specify the `storageClass` used to provision the volume
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ## set, choosing the default provisioner.
    ##
    storageClass: "ebs-sc"
    ## @param compactor.persistence.accessModes PVC Access Modes for data volume
    ##
    accessModes:
      - ReadWriteOnce
    ## @param compactor.persistence.size PVC Storage Request for data volume
    ##
    size: 30Gi
    ## @param compactor.persistence.annotations Annotations for the PVC
    ##
    annotations: {}
    ## @param compactor.persistence.existingClaim Name of an existing PVC to use
    ## If defined, PVC must be created manually before volume will be bound
    ##
    existingClaim: ""


storegateway:
  enabled: true
  persistence:
    size: "10Gi"
    existingClaim: ""

ruler:
  enabled: false

receive:
  enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

**Comment by aviralharsh** [comment]
Hi @fannw, thanks for sharing the config. However I am getting "dropping store, external labels are not unique" error. 
Can you please tell how can i add dynamic/unique labels to each prometheus-replica ?
I am sung this chart https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus

**Comment by fannw** [comment]
@aviralharsh Maybe you have multi prometheus and don't have different external label.

https://github.com/thanos-io/thanos/issues/764

```
jojohappy commented on 28 Jan 2019
For your case, settings suggestion:

prometheus instance1:
external_labels:
    replica: 'prometheus instance1'
    shard: '0'
prometheus instance2:
external_labels:
    replica: 'prometheus instanc2'
    shard: '1'
prometheus instance3:
external_labels:
    replica: 'prometheus instance3'
    shard: '0'
prometheus instance4:
external_labels:
    replica: 'prometheus instanc4'
    shard: '1'
the replica-label flag for query is --query.replica-label=replica
```

**Comment by aslamkhan-dremio** [comment]
@fannw - I also wanted to enable this flag `--shipper.upload-compacted=true` via helm chart. any way to do this?

**Comment by fannw** [comment]
@aslamkhan-dremio No, this's my origin question and seems Prometheus operator doesn't support it( the follow link ), so I give the old metrics to thanos(aws S3) and new metrics will compact.
https://github.com/prometheus-operator/prometheus-operator/issues/2900

**Comment by 5cat** [comment]
For future readers, you can add the `--shipper.upload-compacted` option. https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#thanosspec
```yaml
prometheus:
  prometheusSpec:
    thanos:
      additionalArgs:
        - name: shipper.upload-compacted
```
