### ISSUE TITLE
[prometheus] Allow templating for ingresses

### ISSUE THREAD

**Issue by jarrettprosser** [prometheus-community/helm-charts#1525]
### Is your feature request related to a problem ?

I'm building a helm chart which collects our commonly deployed monitoring applications into one. I would like to add prometheus as a subchart, and use a `global` value to build the ingress URLs. For example:

```
global:
  baseUrl: some-url.com
  
prometheus:
  enabled: true
  server: 
    ingress:
      enabled: true
      hosts:
        - "prometheus.{{ .Values.global.baseUrl }}"
 ```
should produce an ingress with the host `prometheus.some-url.com`.

### Describe the solution you'd like.

Add the `tpl` function in the ingress definition. See a similar implementation in the [Grafana chart's ingress](https://github.com/grafana/helm-charts/blob/7acffc7fbb02eda79296e61ef9784640bf1a7726/charts/grafana/templates/ingress.yaml#L37).

### Describe alternatives you've considered.

I've tried other ways of templating the value (such as using a helper with `include`) but because the value is not templated in the ingress definition the include causes other rendering errors.
