### ISSUE TITLE
Support for Google Managed Prometheus PodMonitoring resource.

### ISSUE THREAD

**Issue by mugioka** [prometheus-community/helm-charts#1540]
### Is your feature request related to a problem ?

[Google Managed Prometheus](https://cloud.google.com/stackdriver/docs/managed-prometheus) uses the [PodMonitoring resource](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#gmp-pod-monitoring) instead of the ServiceMonitor resource.
Therefore, it is good to be able to enable or disable the PodMonitoring resource from the valus file and reflect it.

### Describe the solution you'd like.

It would be nice if the values file could be configured as follows:
```
podMonitoring:
  enabled: true
  labels:
    extra-label: hoge
  annotations:
    extra-annotation: fuga
  selector:
    matchLabels:
      pp.kubernetes.io/instance: fuga
  endpoints:
  - port: metrics
    interval: 30s
 targetLabels:
    fromPod:
      - from: pod-name
        to: pod_name
```

### Describe alternatives you've considered.

NONE
