### ISSUE TITLE
prometheus-kube-stack: oauth with gitlab

### ISSUE THREAD

**Issue by domcar** [prometheus-community/helm-charts#1551]
### Describe the bug a clear and concise description of what the bug is.

I'm not able to use gitlab as IdP, please see below the description of the problem

### What's your helm version?

version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-gke.1300", GitCommit:"9352724e36d9c7c35609d30b2696b0de61d23aa0", GitTreeState:"clean", BuildDate:"2021-10-06T09:26:56Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

19.1.0

### What happened?

**Environment**:
- Grafana version: 8.2.1
Deployed on GKE using the kube-promethues-stack

**What happened**:
I have one gke cluster where gitlab is running and exposed with two ingress: 1 with internal IP and 1 with external IP.

In a second cluster I have a grafana deployment that I would like to "connect" to gitlab in order to use gitlab as authentication provider.
Since the internal url of gitlab is not reachable from grafana, I use the external one, but something doesn't seem to work:
in the logs I see that a requests goes from grafana to the internal IP, and I can't understand why.
This is the grafana config:
```
    auth.gitlab:
      enabled: true 
      allow_sign_up: true
      scopes: read_api
      auth_url: https://external-url/oauth/authorize
      token_url: https://external-url/oauth/token
      api_url: https://external-url/api/v4
```

and these are the logs from grafana:

```
t=2021-12-01T12:36:30+0000 lvl=dbug msg="OAuthLogin Got token" logger=oauth token="&{AccessToken:redacted TokenType:Bearer RefreshToken:redacted Expiry:0001-01-01 00:00:00 +0000 UTC raw:map[access_token:redacted created_at:1.637755993e+09 refresh_token:redacted scope:read_api token_type:Bearer]}"
t=2021-12-01T12:36:30+0000 lvl=dbug msg="HTTP GET https://external-url/api/v4/user: 200 OK {redacted information}
t=2021-12-01T12:36:30+0000 lvl=dbug msg="HTTP GET https://external-ip/api/v4/groups: 200 OK {redacted information}
t=2021-12-01T12:38:42+0000 lvl=eror msg="Error getting groups from GitLab API" logger=oauth.gitlab err="Get \"https://INTERNAL-URL/api/v4/groups?order_by=name&owned=false&page=2&per_page=20&sort=asc&statistics=false&with_custom_attributes=false\": dial tcp internal-ip:443: connect: connection timed out"
t=2021-12-01T12:38:42+0000 lvl=dbug msg="OAuthLogin got user info" logger=oauth userInfo="&{redacted information}
```

Can anyone help me with this?
Thanks in advance

### Enter the command that you execute and failing/misfunctioning.

deplyoed with helmfilem

### Anything else we need to know?

I'm not sure if this is the right place for this Issue, I also placed one at grafana

**Comment by ebr** [comment]
Just resolved this yesterday for myself. You need to let Grafana know its public URL, otherwise the callback from Gitlab will fail.

```
    grafana.ini:
      server:
        root_url: https://<your-public-grafana-url>
     auth.gitlab:
        ....
```
