### ISSUE TITLE
[prometheus-adapter] sigv4 support needed

### ISSUE THREAD

**Issue by andrewgkew** [prometheus-community/helm-charts#1568]
### Is your feature request related to a problem ?

With the imminent release of prometheus agent mode, this will mean no local prometheus metrics, and so prometheus adapter would need to connect to the global instance where the metrics are being remote written to. If a service like AWS Managed Prometheus (AMP) is being used then the adapter needs support for authentication with AWS using sigv4

### Describe the solution you'd like.

sigv4 support added allowing authentication for either

1. IAM Access and secret keys (using k8s secrets)
2. AWS Role using service account (service account is already in the values file)

Adjusting the values file to take these different values

```
prometheus:
  # Value is templated
  url: http://prometheus.default.svc
  port: 9090
  path: ""
  sigv4:
    region: eu-west-1
    #below are optional if you are using role and service account to auth
    accessKey:
      name: secret-name
      key: secret-key
    secretKey:
      name: secret-name
      key: secret-key
```

### Describe alternatives you've considered.

There are only 2 alternatives here:

1. Dont use prometheus agent mode and keep the metrics locally
2. Use a sidecar proxy to do the sigv4 signing - this is how AWS suggest doing it but think having the functionality natively would be better (as prometheus does for remote writing/reading)
