### ISSUE TITLE
not recognizing matchNames in *NamespaceSelector

### ISSUE THREAD

**Issue by yudar1024** [prometheus-community/helm-charts#157]
**Describe the bug**
serviceMonitorNamespaceSelector can not recognize matchnames and any

**Version of Helm and Kubernetes**:

Helm Version:
3.3.4

Kubernetes Version:
1.19.2

**Which chart**:
**Which version of the chart**:
kube-prometheus-stack-9.4.4

**What happened**:

```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Prometheus.spec.ruleNamespaceSelector): unknown field "any" in com.coreos.monitoring.v1.Prometheus.spec.ruleNamespaceSelector, ValidationError(Prometheus.spec.serviceMonitorNamespaceSelector): unknown field "any" in com.coreos.monitoring.v1.Prometheus.spec.serviceMonitorNamespaceSelector]
```

**What you expected to happen**:
work correctly

**How to reproduce it** (as minimally and precisely as possible):
```shell
helm install monitor prometheus-community/kube-prometheus-stack -f pro-values.yaml
```
<~--
This could be something like:

values.yaml (only put values which differ from the defaults)

```yaml
prometheus:
  prometheusSpec: 
    serviceMonitorNamespaceSelector:
        any: true # or
        matchNames:
           - default
           - monitor
```

```
helm install my-release prometheus-community/name-of-chart --version version --values values.yaml
```

-->

**Anything else we need to know**:

**Comment by fktkrt** [comment]
As the snippet says above:

- you should use either `any: true` to enable all namespaces, or
-  explicitly enable some by listing them under `matchNames`

**Comment by yudar1024** [comment]
> As the snippet says above:
> 
> * you should use either `any: true` to enable all namespaces, or
> * explicitly enable some by listing them under `matchNames`

@fktkrt I use this config above but helm report error. it can not know these parameters. any and matchNames are invalid when use helm install .

**Comment by pie-r** [comment]
Same issue encountered yesterday, for RuleMatchNamespace (not remember the right sintax)

**Comment by volgorean** [comment]
[Looks like the CRD doesn't actually define the `matchNames` or `any` properties for the *NamespaceSelector(s).](https://github.com/prometheus-community/helm-charts/blame/b643f58714a063e5a0ddf6832cd00ed29c0f4fab/charts/kube-prometheus-stack/crds/crd-prometheus.yaml#L3920)

**Comment by skiley22** [comment]
can you try `serviceMonitorNamespaceSelector: {}` ? That sure ensure that service monitors from all namespaces will be selected

**Comment by gw0** [comment]
Same issue with `any` for most *NamespaceSelectors:

```
prometheus:
  prometheusSpec:
    ruleNamespaceSelector:
      any: true
    serviceMonitorNamespaceSelector:
      any: true
    podMonitorNamespaceSelector:
      any: true
```

```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Prometheus.spec.podMonitorNamespaceSelector): unknown field "any" in com.coreos.monitoring.v1.Prometheus.spec.podMonitorNamespaceSelector, ValidationError(Prometheus.spec.ruleNamespaceSelector): unknown field "any" in com.coreos.monitoring.v1.Prometheus.spec.ruleNamespaceSelector, ValidationError(Prometheus.spec.serviceMonitorNamespaceSelector): unknown field "any" in com.coreos.monitoring.v1.Prometheus.spec.serviceMonitorNamespaceSelector]
```

While on the other hand, using `matchLabels` works perfectly for all namespaces labeled with `prometheus=monitoring`:

```
prometheus:
    ruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector:
      matchLabels:
        prometheus: monitoring
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector:
      matchLabels:
        prometheus: monitoring
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector:
      matchLabels:
        prometheus: monitoring
    probeSelectorNilUsesHelmValues: false
    probeNamespaceSelector:
      matchLabels:
        prometheus: monitoring
```

Using kube-prometheus-stack 11.0.4, Helm 3.1.3. Same issue in old repository: https://github.com/helm/charts/issues/20581

**Comment by gw0** [comment]
> can you try `serviceMonitorNamespaceSelector: {}` ? That sure ensure that service monitors from all namespaces will be selected

According to the [comment in CRD](https://github.com/prometheus-community/helm-charts/blob/3ab7f9b04e1ab5abd6c0b35268368422436ae3a6/charts/kube-prometheus-stack/crds/crd-prometheuses.yaml#L4396-L4398) by default only the current namespace is selected.

**Comment by irLinja** [comment]
I have same issue ☹️ 
Would anybody help in this regard?

**Comment by irLinja** [comment]
Any update on this?

**Comment by irLinja** [comment]
Is anybody eager to fix or even shoot a comment?

**Comment by BenWolstencroft** [comment]
Same issue, is this a documentation issue, or a CRD issue?  as mentioned above, the documentation says you can set any: true against the *NamespaceSelector configs, but the CRD doesn't define this option - if the CRD was fixed, would the functionality work?

**Comment by johnjbateman** [comment]
Experiencing this issue as well.

**Comment by luismiguelsaez** [comment]
As far as I know, if we review the specs, the `matchNames` is not supported, so we can use the `matchExpressions` instead:

`prometheus:
  prometheusSpec:
    ruleNamespaceSelector:
      matchExpressions:
        - key: name
          operator: in
          values:
            - monitoring
            - mongodb`
  
Although it's a more complex structure, it should work.

**Comment by dududko** [comment]
Looks like specifying `ruleNamespaceSelector.any: true` option is indeed unavailable.
Instead the following should be used to discover prometheus rules in all namespaces
```
prometheus: 
    prometheusSpec: 
        ruleNamespaceSelector: 
            matchLabels: {}
```
