### ISSUE TITLE
[prometheus-kube-stack] PR #1417 ended up breaking the generation for Alertmanager (charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml)

### ISSUE THREAD

**Issue by br05s** [prometheus-community/helm-charts#1572]
### Describe the bug a clear and concise description of what the bug is.

PR #1417 ended up breaking the generation for Alertmanager (charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml).

If alertmanager.alertmanagerSpec.podAntiAffinity or alertmanager.alertmanagerSpec.affinity is not set, then nothing below will get generated, even though those settings have nothing to do with affinity.

I no longer get tolerations on the resulting manifest.

### What's your helm version?

version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

23.1.1

### What happened?

The Alertmanager object is no longer taking values below the affinity section if no affinity settings are configured.

### What you expected to happen?

The sections get generated when affinity is not configured.

### How to reproduce it?

Add a toleration to alertmanagerSpec but don't put any affinity.

### Enter the changed values of values.yaml?
```
alertmanager:
  alertmanagerSpec:
    securityContext:
      fsGroup: 10010
      runAsGroup: 10010
      runAsNonRoot: true
      runAsUser: 10006
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi
          selector:
            matchLabels:
              app.kubernetes.io/name: prometheus-alertmanager
          storageClassName: local-storage
    tolerations:
    - effect: NoSchedule
      key: storage
      operator: Equal
      value: local
  ingress:
    enabled: true
    hosts:
    - alertmanager.apps.mydomain.tld
    tls:
    - hosts:
      - '*.apps.mydomain.tld'
grafana:
  adminPassword: prom-operator
  defaultDashboardsTimezone: America/Chicago
  ingress:
    enabled: true
    hosts:
    - grafana.apps.mydomain.tld
    tls:
    - hosts:
      - '*.apps.mydomain.tld'
prometheus:
  ingress:
    enabled: true
    hosts:
    - prometheus.apps.mydomain.tld
    tls:
    - hosts:
      - '*.apps.mydomain.tld'
  prometheusSpec:
    securityContext:
      fsGroup: 10010
      runAsGroup: 10010
      runAsNonRoot: true
      runAsUser: 10006
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi
          selector:
            matchLabels:
              app.kubernetes.io/name: prometheus
          storageClassName: local-storage
    tolerations:
    - effect: NoSchedule
      key: storage
      operator: Equal
      value: local
prometheusOperator:
  admissionWebhooks:
    patch:
      securityContext:
        runAsGroup: 10010
        runAsNonRoot: true
        runAsUser: 10006
  securityContext:
    fsGroup: 10010
    runAsGroup: 10010
    runAsNonRoot: true
    runAsUser: 10006
```
### Enter the command that you execute and failing/misfunctioning.

helm upgrade -i --reset-values -f=/tmp/tmp_8ex2en4.yml prometheus prometheus-community/kube-prometheus-stack

### Anything else we need to know?

Using Ansible, which is why the command is upgrade instead of install. But changing that to install gets the same results.
