### ISSUE TITLE
[kube-prometheus-stack] Misleading comments in psp.yaml

### ISSUE THREAD

**Issue by ww3pl** [prometheus-community/helm-charts#1580]
### Is your feature request related to a problem ?

When you look at the `psp.yaml` in most of the Charts (ex. [Prometheus's psp.yaml](https://github.com/prometheus-community/helm-charts/blob/ada271ce703bfc72d1a8a4f6ba8ce8396da3510f/charts/kube-prometheus-stack/templates/prometheus/psp.yaml) ), the file seems to be a slightly modified copy of the Pod Security Policy example from the [Kubernetes docs](https://kubernetes.io/docs/concepts/policy/pod-security-policy/)

Because of that, not only the file contains commented code that can now be removed, but also confusing comments. One of the examples is the 

```yaml
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 0
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 0
        max: 65535
```

In the original version, where the `min` value was equal `1`, this was true. Now it's just misleading and confusing, where I had to consult surrounding comments and code in general to know if the possibility to run as root is actually supposed to be here (i.e. to be sure if it's the comment that's wrong or the yaml values). I was sure what's going on only after I've found the original example in k8s docs. 

Other examples include things like
```yaml
spec:
  privileged: false
  # Required to prevent escalations to root.
  # allowPrivilegeEscalation: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  #requiredDropCapabilities:
  #  - ALL
```

Where, once again, we got the original yaml parts commented without any specific reason. 

### Describe the solution you'd like.

I'd love to see those comments either corrected (to not be misleading) or removed altogether, bringing those files further away from a mere copy of the K8S docs and closer to the nice yaml file.

### Describe alternatives you've considered.

NONE
