### ISSUE TITLE
[kube-prometheus-stack] High CPU throttling for config-reloader after v22/v23 upgrade

### ISSUE THREAD

**Issue by mac-chaffee** [prometheus-community/helm-charts#1587]
### Describe the bug a clear and concise description of what the bug is.

After upgrading from v21 to v23, the config-reloader container inside the Prometheus pod began experiencing high CPU throttling:
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/7581860/145626164-9ba932a7-2233-4b67-9723-cb16f22f29d0.png">

We don't specify a custom value for the config-reloader container, so it still had its default 100m CPU limit before and after the upgrade.

### What's your helm version?

v3.7.1

### What's your kubectl version?

v1.22.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

23.1.5

### What happened?

Upgrading to v23 caused higher-than-normal CPU throttling.

### What you expected to happen?

No spike in CPU usage.

### How to reproduce it?

1. On a large-ish cluster (13 nodes, 230 pods), install kube-prometheus-stack v21
2. Observe little-to-no CPU throttling on the config-reloader container
3. Upgrade to v23
4. Observe CPU throttling on the config-reloader container

### Enter the changed values of values.yaml?

Relevant section:
```
kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      ruleSelector: {}
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      serviceMonitorSelectorNilUsesHelmValues: false
      retention: 90d
      resources:
        requests:
          cpu: 2500m
          memory: 4000Mi
        limits:
          cpu: 2500m
          memory: 4000Mi
```

### Enter the command that you execute and failing/misfunctioning.

`helm upgrade --install -n monitoring monitoring . -f values.yaml`

### Anything else we need to know?

I know that the values for config-reloader did change slightly, but I don't think that changed the default CPU limit of 100m, that's always been there IIRC.

And I don't think config-reloader itself changed substantially recently: https://github.com/prometheus-operator/prometheus-operator/commits/main/cmd/prometheus-config-reloader

Maybe some other part of the ecosystem changed that could make config-reloader's job more CPU-intensive?
