### ISSUE TITLE
[prometheus] server prefixURL and baseURL properties result in args in incorrect order

### ISSUE THREAD

**Issue by js8080** [prometheus-community/helm-charts#1594]
### Describe the bug a clear and concise description of what the bug is.

I was deploying the Prometheus server via the chart here: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus

I want to access my Prometheus server metrics page from outside of my cluster via the following URL:
`https://my-cluster-external-hostname/prometheus`

My override values.yaml looks like this:
```yaml
  server:
    prefixURL: /
    baseURL: https://my-cluster-external-hostname/prometheus
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      path: "/prometheus(/|$)(.*)"
      hosts:
        - my-cluster-external-hostname
      tls:
        - secretName: cluster-tls-secret
          hosts:
            - my-cluster-external-hostname
    service:
      servicePort: 9090
```

Now the resulting deployment spec for `prometheus-server` ends up with these args (note the order and specifically that `--web.route-prefix` is at the top):

```yaml
      --web.route-prefix=/
      --storage.tsdb.retention.time=15d
      --config.file=/etc/config/prometheus.yml
      --storage.tsdb.path=/data
      --web.console.libraries=/etc/prometheus/console_libraries
      --web.console.templates=/etc/prometheus/consoles
      --web.enable-lifecycle
      --web.external-url=https://my-cluster-external-hostname/prometheus
```

This does NOT work as the /-/healthy endpoint results in a 404 (from `kubectl describe pod prometheus-server`) and therefore, the prometheus-server pod never becomes "ready":
```
  Warning  Unhealthy  9s (x9 over 49s)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 404
  Warning  Unhealthy  9s (x3 over 39s)  kubelet            Liveness probe failed: HTTP probe failed with statuscode: 404
```

After much trial and error, I realized the order of those arguments seemed to matter so I changed my Helm chart values.yaml as follows:

```yaml
  server:
    # prefixURL: /   # <-- commented out
    # baseURL: https://my-cluster-external-hostname/prometheus  # <-- commented out
    extraFlags:  # <-- added this section to specify my args manually
      - web.enable-lifecycle
      - web.route-prefix=/
      - web.external-url=https://my-cluster-external-hostname/prometheus
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      path: "/prometheus(/|$)(.*)"
      hosts:
        - my-cluster-external-hostname
      tls:
        - secretName: cluster-tls-secret
          hosts:
            - my-cluster-external-hostname
    service:
      servicePort: 9090
```

The resulting deployment from this values.yaml puts the arguments in the apparently proper order which makes the health check endpoint available (internally) and allows accessing Prometheus from outside the cluster. Notice where `--web.route-prefix` is located now.

```yaml
      --storage.tsdb.retention.time=15d
      --config.file=/etc/config/prometheus.yml
      --storage.tsdb.path=/data
      --web.console.libraries=/etc/prometheus/console_libraries
      --web.console.templates=/etc/prometheus/consoles
      --web.enable-lifecycle
      --web.route-prefix=/
      --web.external-url=https://my-cluster-external-hostname/prometheus
```

After this change, the http://:9090/-/healthy endpoint is available and no longer returns a 404 so the pods are considered healthy and my Prometheus server is available via the external URL.

I am not sure if this is a bug for the Prometheus chart here or Prometheus itself as it seems a little strange that the argument order matters.

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7+k3s1", GitCommit:"ac70570999c566ac3507d2cc17369bb0629c1cc0", GitTreeState:"clean", BuildDate:"2021-11-29T16:40:13Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7+k3s1", GitCommit:"ac70570999c566ac3507d2cc17369bb0629c1cc0", GitTreeState:"clean", BuildDate:"2021-11-29T16:40:13Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-community/prometheus

### What's the chart version?

15.0.1

### Enter the command that you execute and failing/misfunctioning.

helm install myrelease ./myrelease

**Comment by js8080** [comment]
After further investigation, my original premise for this issue was wrong. The problem I was facing was NOT due to the order of the `args` parameters and I think is instead due to how the `prefixURL` setting is used in the `deploy.yaml` template.

For example, I believe the following references to `.Values.server.prefixURL` will cause problems when `prefixURL` is set to `/` like I had it (i.e. `prefixURL: /`):

```yaml
          args:
            - --volume-dir=/etc/config
            - --webhook-url=http://127.0.0.1:9090{{ .Values.server.prefixURL }}/-/reload
```

```yaml
          readinessProbe:
            {{- if not .Values.server.tcpSocketProbeEnabled }}
            httpGet:
              path: {{ .Values.server.prefixURL }}/-/ready
```

```yaml
          livenessProbe:
            {{- if not .Values.server.tcpSocketProbeEnabled }}
            httpGet:
              path: {{ .Values.server.prefixURL }}/-/healthy
```

```yaml
          startupProbe:
            {{- if not .Values.server.tcpSocketProbeEnabled }}
            httpGet:
              path: {{ .Values.server.prefixURL }}/-/healthy
```

This results in the various URLs being set to:
- `//-/reload`
- `//-/ready`
- `//-/healthy`

That extra slash presumably screws things up...
