### ISSUE TITLE
[prometheus-kube-stack] grafana.ini database type postgres still creating with terraform

### ISSUE THREAD

**Issue by yoelmacia** [prometheus-community/helm-charts#1603]
### Describe the bug a clear and concise description of what the bug is.

Unable to create database type postgres into grafana ini configuration:

```
grafana.ini:
    server:
      root_url: https://grafana.mydomain.com
    database:
      type: postgres
      user: grafana
      password: grafana
      name: grafana
```

Error: timed out waiting for the condition

### What's your helm version?

v3.7.1

### What's your kubectl version?

1.22.4

### Which chart?

kube-prometheus-stack

### What's the chart version?

kube-prometheus-stack-23.3.2

### What happened?

Error: timed out waiting for the condition

### What you expected to happen?

Deploy the grafana config with database postgres

### Enter the command that you execute and failing/misfunctioning.

terraform plan 
terraform apply
