### ISSUE TITLE
Prometheus without persistent volume on k8s (no EBS on aws eks)

### ISSUE THREAD

**Issue by antoineNRB** [prometheus-community/helm-charts#1606]
Hello,
I've been trying to run a Prometheus on Kubernetes without it needing of a persistent volume. Why ? Cause I'm remotly writing the data gathered by this prometheus to an AWS Managed Prometheus and would prefer not having an EBS created with the cluster. I've tried playing with the values on chart helm like for instance doing this :
```  
server:
  persistentVolume:
    ## If true, alertmanager will create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: false
```
and same with `alertmanager` and `pushgateway` but it still create a PVC and PV.

Could someone indicates where I could find some docs or info on my use case as I can't find it?
Or maybe explain me what I'm missing or not understanding, as I'm fairly new with k8s, helm and such.
Thanks !
