### ISSUE TITLE
[kube-prometheus-stack] KubeProxyDown rule can't be disabled

### ISSUE THREAD

**Issue by ckotzbauer** [prometheus-community/helm-charts#1618]
### Describe the bug a clear and concise description of what the bug is.

Since #1614 there is an alert "KubeProxyDown" which checks if the "kube-proxy" target is available. This rule cannot be disabled, which is a problem for all clusters which run a CNI with a kube-proxy-replacement.

### What's your helm version?

3.6.3

### What's your kubectl version?

1.23.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

25.0.0

### What you expected to happen?

The mentioned rule can be disabled with a new parameter e.g. `Values.defaultRules.rules.kubeProxy`

### Enter the command that you execute and failing/misfunctioning.

helm upgrade -i prometheus -n monitoring prometheus-community/kube-prometheus-stack -f custom-values.yaml

**Comment by kimmornetum** [comment]
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kube-proxy.yaml#L7 is missing .Values.kubeProxy.enabled

**Comment by sota0113** [comment]
I'm facing same problem.

**Comment by tarioch** [comment]
My guess is that, the script here

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/hack/sync_prometheus_rules.py

would need to be extended to add the correct condition.

**Comment by mrueg** [comment]
> My guess is that, the script here
> 
> https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/hack/sync_prometheus_rules.py
> 
> would need to be extended to add the correct condition.

Yes, that is correct. Do you want to create a PR for that?

**Comment by ckotzbauer** [comment]
fixed by #1629
thanks @jjmengze!

**Comment by mindrunner** [comment]
I just updated to v30 of the chart. Still I am getting kubeProxyDown alerts. I do have kubeProxy pods in my cluster (Azure) and I have `kubeProxy.serviceMonitor.enabled` set to `true`. What am I missing here?

**Comment by snuggie12** [comment]
@mindrunner if it is anything like my GKE setup the `ServiceMonitor` presumes certain labels being present on the kube proxy pods and they aren't there.

In previous versions this was fine because no pods found isn't inherently bad. However, what was added was a specific `PrometheusRule` that isn't as dynamic and is specifically for kube proxy.

I didn't bother to look because I'm good with just dropping the alert, but there could be a way in the chart to customize the labels or you could use something like `kustomize` to alter the selector if you still want to keep it.

**Comment by hgm-kklingspor** [comment]
@mindrunner 
> I just updated to v30 of the chart. Still I am getting kubeProxyDown alerts. I do have kubeProxy pods in my cluster (Azure) and I have `kubeProxy.serviceMonitor.enabled` set to `true`. What am I missing here?

Check your proxy-labels (kube-system/kube-proxy). For my AKS-Cluster it is `component=kube-proxy`. Per default the service tries to get its endpoint via selector k8s-app=kube-proxy.
I needed to change the Values for kube-proxy. Since I don't get access to Azure-Kube-Scheduler and Controller-Manager, I had to disable the according services/servicemonitors/rules.
My changes in the values.yaml as follows (I am not sure, if my defaultRules-section is correctly working, but the configuration is working for me)
```
defaultRules:
  rules:
    kubeScheduler: false
  disabled: 
    KubeControllerManagerDown: true
    KubeSchedulerDown: true

kubeProxy:
  enabled: true
  service:
    enabled: true
    selector:
      component: kube-proxy

kubeControllerManager:
  enabled: false
  service:
    enabled: false
  serviceMonitor:
    enabled: false

kubeScheduler:
  enabled: false
  service:
    enabled: false
  serviceMonitor:
    enabled: false
```

**Comment by mindrunner** [comment]
Cool, thats super helpful! I will have a look and adapt our config :)

**Comment by mindrunner** [comment]
Can we maybe have a documentation section for Azure/GCP/AWS specific configurations? This could also be helpful for others I suppose.

**Comment by alfador1** [comment]
Hello,
Although this works perfectly  @hgm-kklingspor .
Could someone explain, why are we getting this error and does stopping this alert could cause any issues or missing out of any errors? It seems it's a fake alert?

**Comment by prashantkalkar** [comment]
I was able to get it working for kube-proxy and kube-controller-manager with following configuration for cluster created with kops on AWS. 

```
kubeControllerManager:
   enabled: false
   service: 
     enabled: true
     selector: 
       # make sure controller pod labels are added here
       k8s-app : kube-controller-manager 
   
kubeProxy:
  enabled: true
  service:
    enabled: true
    selector:
      # make sure proxy pod labels are added here
      k8s-app: kube-proxy
```
Apart from above configuration I also had to ensure that metric bind address is configured for kube-proxy pods as
`--metrics-bind-address=0.0.0.0:10249`

I am still not able to solve the KubeSchedulerDown alert so may be I will have to disable that for now.
