### ISSUE TITLE
[prometheus-kube-stack] Appears broken out of the box for v 25.1.0

### ISSUE THREAD

**Issue by brsolomon-deloitte** [prometheus-community/helm-charts#1625]
### Describe the bug a clear and concise description of what the bug is.

A deployment of prometheus-kube-stack appears to be broken out of the box for v 25.1.0 of the chart.

Two resources end up in `SyncFailed` state despite multiple sync attempts when deployed using ArgoCD UI.

### What's your helm version?

version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

25.1.0

### What happened?

Two resources end up in `SyncFailed` state despite multiple sync attempts.

![Screen Shot 2021-12-22 at 10 04 09 AM](https://user-images.githubusercontent.com/81818815/147112901-057b3730-955e-459f-8759-ed3ba59842af.png)
![Screen Shot 2021-12-22 at 10 04 24 AM](https://user-images.githubusercontent.com/81818815/147112910-d836a74e-8e82-4a50-a6d6-4ab823aba442.png)

apiextensions.k8s.io/v1/CustomResourceDefinition -> prometheuses.monitoring.coreos.com

> CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

monitoring.coreos.com/v1/Prometheus -> prometheus-stack-kube-prom-prometheus

> unable to recognize "/dev/shm/509431056": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1"

### What you expected to happen?

Chart should deploy successfully if I don't override any values and use the chart as-is.

### How to reproduce it?

Deploy with ArgoCD:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 25.1.0
    chart: kube-prometheus-stack
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

### Enter the changed values of values.yaml?

None

### Enter the command that you execute and failing/misfunctioning.

Deployed via ArgoCD UI.
