### ISSUE TITLE
[kube-prometheus-stack] Prometheus doesn't respect ServiceMonitor created by kube-state-metrics chart

### ISSUE THREAD

**Issue by skarj** [prometheus-community/helm-charts#1631]
### Describe the bug a clear and concise description of what the bug is.

Prometheus doesn't respect ServiceMonitor created by `kube-state-metrics` Helm chart by default

### What's your helm version?

3.7.0

### What's your kubectl version?

1.23.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

25.1.0

### What happened?

`kube-prometheus-stack` Helm chart creates `Prometheus` with 

```
  serviceMonitorSelector:
    matchLabels:
      release: prometheus-operator
```

`kube-state-metrics` Helm chart creates `ServiceMonitor` without a label `release: prometheus-operator`

so the `kube-state-metrics`  target doesn't appear in the Prometheus

### What you expected to happen?

`kube-prometheus-stack` default configuration should have working `kube-state-metrics` out of the box

### Enter the command that you execute and failing/misfunctioning.

applying using terraform

### Anything else we need to know?

Workarounds are:

```
kube-state-metrics:
  prometheus:
    monitor:
      enabled: true
      additionalLabels:
        release: prometheus-operator
```
or

`prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues: false`

**Comment by lud97x** [comment]
+1 I can reproduce this issue with the chart version v25.1.0

**Comment by monotek** [comment]
Not sure how a fix should look like as we don't know whats the releasename the user chooses for kube-prometheus-stack.

**Comment by groundhog2k** [comment]
Possibly using another label makes it more independent from the release name used for helm:
```
kube-state-metrics:
  prometheus:
    monitor:
      additionalLabels:
        app: kube-prometheus-stack-operator
```

**Comment by devent** [comment]
Can you at least document this in the docu? Here: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack

**Comment by monotek** [comment]
I guess adding the release label to kube-state-metrics would be easiest solution.
@mrueg 
thoughts?

**Comment by lud97x** [comment]
Hi, if it helps, we share the same helm release's name for our prometheus and kube state metric instance. So adding the label `release` might quickly solve the issue here https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/templates/_helpers.tpl#L59
```
release: {{ $.Release.Name | quote }}
```

**Comment by joeldeteves** [comment]
> Workarounds are:
> 
> ```
> kube-state-metrics:
>   prometheus:
>     monitor:
>       enabled: true
>       additionalLabels:
>         release: prometheus-operator
> ```
> 
> or
> 
> `prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues: false`

The fix for me was to set `release` to **kube-prometheus-stack**:

```
kube-state-metrics:
  prometheus:
    monitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
```

Thank you,
