### ISSUE TITLE
PV prometheus

### ISSUE THREAD

**Issue by mastermindhf** [prometheus-community/helm-charts#1632]
### Describe the bug a clear and concise description of what the bug is.

Hello , 
I want to add a pv for prometheus , so i modify in the storage section. 
but i did not find the pv .

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7+k3s1", GitCommit:"ac70570999c566ac3507d2cc17369bb0629c1cc0", GitTreeState:"clean", BuildDate:"2021-11-29T16:40:13Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1

### Which chart?

kube-prometheus-stack

### What's the chart version?

24.0.1

### What happened?

no pv

### What you expected to happen?

a pv for prometheus

### Enter the changed values of values.yaml?
```
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ""
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
  
  ```

### Enter the command that you execute and failing/misfunctioning.

helm install projet -f values.yaml  prometheus-community/kube-prometheus-stack --version 24.0.1
