### ISSUE TITLE
[prometheus-kube-stack] existingSecret for Grafana SMTP config not working

### ISSUE THREAD

**Issue by mindthevirt** [prometheus-community/helm-charts#1671]
### Describe the bug a clear and concise description of what the bug is.

I'm trying to have Grafana pick up existingSecret for the SMTP configuration but it's not working.
It looks like none of the values are being picked up. I decoded the secret and can see the values there but Grafana doesn't seem to be picking it up at all.

When I hardcode the creds in my values.yaml, everything works.
The following is set under

```
grafana
  grafana.ini
    smtp:
      enabled: true
      host: myhost
      existingSecret: ""
      from_address: <my-email>
      passwordKey: "password"
      userKey: "user"
```

### What's your helm version?

v3.7.0

### What's your kubectl version?

1.21

### Which chart?

prometheus-kube-stack

### What's the chart version?

27.0.0

### What happened?

Values aren't being picked up from the secret in grafana.

### What you expected to happen?

The secret to be read in

### How to reproduce it?

Create a secret holding username and password, reference it in grafana:grafana.ini:smtp

### Enter the command that you execute and failing/misfunctioning.

just updated my values.yaml
