### ISSUE TITLE
[kube-prometheus-stack] Unable to get the kubernetes metrics i.e. General / Kubernetes / *

### ISSUE THREAD

**Issue by vipinjn24** [prometheus-community/helm-charts#1696]
### Describe the bug a clear and concise description of what the bug is.

My metrics from the kubernetes cluster are not visible.
It shows no data.

Only ones in red box are in issue.
![image](https://user-images.githubusercontent.com/1639185/148781826-5cc451c1-2e49-4df9-831f-b1754b5efc2b.png)

![image](https://user-images.githubusercontent.com/1639185/148779924-a1280377-2626-4954-9776-52317fc3368e.png)
![image](https://user-images.githubusercontent.com/1639185/148779950-34e8ac45-d4fc-4a79-9f44-69088dfe4de4.png)
![image](https://user-images.githubusercontent.com/1639185/148779978-25341c48-4cea-4e2c-8fc0-9636d94b1a02.png)
![image](https://user-images.githubusercontent.com/1639185/148780013-6c737235-ba15-46a2-bf09-8f109e5e183a.png)
![image](https://user-images.githubusercontent.com/1639185/148780106-3d71a62f-de22-4087-9655-e623e1a3c99b.png)
![image](https://user-images.githubusercontent.com/1639185/148780158-d6d222e5-d5ff-432e-9fce-6e3a536e6f43.png)

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

28.0.1

### What happened?

No data is visible.

### What you expected to happen?

All data should have been visible.

### How to reproduce it?

# Kubernetes Setup
```
kubeadm config print init-defaults > /mnt/KUBE/dynamic/cluster-config.yaml
sudo sed -i -e '/kind: ClusterConfiguration/a controllerManager:\n  extraArgs:\n    bind-address: 0.0.0.0\nscheduler:\n  extraArgs:\n    address: 0.0.0.0\n    bind-address: 0.0.0.0' /mnt/KUBE/dynamic/cluster-config.yaml
sudo sed -i -e '/serviceSubnet:/a \ \ podSubnet: 10.244.0.0/16' /mnt/KUBE/dynamic/cluster-config.yaml
sudo sed -i -e 's/1.2.3.4/<My-Local-IP>/' /mnt/KUBE/dynamic/cluster-config.yaml
sudo sed -i -e '/controllerManager: {}/d' /mnt/KUBE/dynamic/cluster-config.yaml
sudo sed -i -e '/scheduler: {}/d' /mnt/KUBE/dynamic/cluster-config.yaml
sudo sed -i -e 's/criSocket: .*/criSocket: \/run\/containerd\/containerd.sock/' /mnt/KUBE/dynamic/cluster-config.yaml
cat <<EOF >> /mnt/KUBE/dynamic/cluster-config.yaml

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
EOF
sudo kubeadm init --config=/mnt/KUBE/dynamic/cluster-config.yaml
```

# Network Setup
```
sudo wget -O /mnt/KUBE/dynamic/tigera-operator.yaml https://docs.projectcalico.org/manifests/tigera-operator.yaml
sudo wget -O /mnt/KUBE/dynamic/tigera-custom-resources.yaml https://docs.projectcalico.org/manifests/custom-resources.yaml
sudo sed -i -e "s/cidr: 192.168.0.0\/16/cidr: 10.244.0.0\/16/" /mnt/KUBE/dynamic/tigera-custom-resources.yaml

kubectl apply -f /mnt/KUBE/dynamic/tigera-operator.yaml
kubectl apply -f /mnt/KUBE/dynamic/tigera-custom-resources.yaml
```

# Prometheus Setup
```
sudo kubectl -n monitoring create secret generic etcd-client-cert --from-file=etcd-client-ca.crt=/etc/kubernetes/pki/etcd/ca.crt --from-file=etcd-client.crt=/etc/kubernetes/pki/etcd/peer.crt --from-file=etcd-client.key=/etc/kubernetes/pki/etcd/peer.key

helm repo add prometheus https://prometheus-community.github.io/helm-charts && helm repo update

kubectl apply -f /mnt/KUBE/0700-prometheus.yaml
helm upgrade --install prometheus prometheus/kube-prometheus-stack -n monitoring --values=/mnt/KUBE/prometheus/values.yaml
```

### Enter the changed values of values.yaml?

```
global:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 20m
        memory: 128Mi
prometheusOperator:
  admissionWebhooks:
    patch:
      resources:
        requests:
          cpu: 20m
          memory: 128Mi
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
prometheus:
  prometheusSpec:
    scrapeInterval: 1m
    retention: 10d
    resources:
      requests:
        cpu: 20m
        memory: 128Mi
    secrets:
      - etcd-client-cert
    storageSpec:
      volumeClaimTemplate:
        spec:
          volumeName: prometheus-pv
          accessModes: ['ReadWriteOnce']
          resources:
            requests:
              storage: 8Gi
grafana:
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
  initChownData:
    resources:
      requests:
        cpu: 20m
        memory: 128Mi
  sidecar:
    resources:
      requests:
        cpu: 20m
        memory: 128Mi
  imageRenderer:
    resources:
      requests:
        cpu: 20m
        memory: 128Mi
  persistence:
    enabled: true
    size: 5Gi
    existingClaim: prometheus-grafana-pvc
kubeEtcd:
  serviceMonitor:
    scheme: https
    insecureSkipVerify: false
    caFile: /etc/prometheus/secrets/etcd-client-cert/etcd-client-ca.crt
    certFile: /etc/prometheus/secrets/etcd-client-cert/etcd-client.crt
    keyFile: /etc/prometheus/secrets/etcd-client-cert/etcd-client.key
kubeScheduler:
  service:
    port: 10259
    targetPort: 10259
  serviceMonitor:
    https: true
    insecureSkipVerify: true
    serverName: 127.0.0.1
kubeControllerManager:
  service:
    port: 10257
    targetPort: 10257
  serviceMonitor:
    https: true
    insecureSkipVerify: true
    serverName: 127.0.0.1
```

### Enter the command that you execute and failing/misfunctioning.

The metrics are not available on grafana.

### Anything else we need to know?

This also doesn't show any metrics on lens.
Let me know if this is an error in the application or an error at my end.
