### ISSUE TITLE
[kube-prometheus-stack] kubeControllerManager: {enabled: false} doesn't disable scraping config

### ISSUE THREAD

**Issue by shinebayar-g** [prometheus-community/helm-charts#1702]
### Describe the bug a clear and concise description of what the bug is.

I'm on EKS, so disabling these. However it still creates scraping config and dashboards for these components. This configuration was working before I upgrade, at least on `19.1.0`. It's fresh install.
```yml
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
```
![image](https://user-images.githubusercontent.com/3091558/148980598-a2b3e0d9-d3ae-4ffe-9b35-9b763d5f7549.png)

![image](https://user-images.githubusercontent.com/3091558/148980504-4ee008d7-feb3-4ccc-b456-0ee99afa6ad0.png)

![image](https://user-images.githubusercontent.com/3091558/148980445-acf52698-48a3-4124-9de0-0c4c50978908.png)

### What's your helm version?

```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
```

### What's your kubectl version?

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:52:11Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Which chart?

kube-prometheus-stack

### What's the chart version?

30.0.1

### What you expected to happen?

KubeControllerManager & KubeScheduler scraping config, dashboard, alerts are disabled.

### How to reproduce it?

1. Deploy kube-prometheus-stack with
```yml
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
```
2. Go to Prometheus Config

### Enter the changed values of values.yaml?

```yml
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
```

### Enter the command that you execute and failing/misfunctioning.

```
helm template kube-prometheus-stack prometheus-community/kube-prometheus-stack --values values.yaml --create-namespace --namespace monitoring --skip-crds --output-dir . --version 30.0.1
```
