### ISSUE TITLE
[prometheus-kube-stack] Chart is not deploying ServiceMonitors

### ISSUE THREAD

**Issue by appanycd** [prometheus-community/helm-charts#171]
**Describe the bug**
Chart is not deploying ServiceMonitors for kube-state-metrics, node-exporter, prometheus and grafana
So all provisioned grafana dashboards are empty

**Version of Helm and Kubernetes**:

Helm Version: 3.2.3

Kubernetes Version: 1.19.2

**Which chart**: prometheus-kube-stack
**Which version of the chart**: 9.4.5

**What happened**:
I tried:
```yaml
kube-state-metrics:
  prometheus:
    monitor:
      enabled: true
prometheus-node-exporter:
  prometheus:
    monitor:
      enabled: true
prometheus:
  serviceMonitor:
    selfMonitor: true
grafana:
  serviceMonitor:
    selfMonitor: true
```
But it is not working

**What you expected to happen**:
ServiceMonitors deployed

**How to reproduce it** (as minimally and precisely as possible):
Deploy kube-prometheus-stack chart, node-exporters and kube-state-metrics pods created, but all ServiceMonitors are not

**Anything else we need to know**:
ServiceMonitors from another charts deployed successfully

**Comment by kifeo** [comment]
do you have this error message in helm-operator logs ?

```ts=2020-10-04T11:22:16.005651123Z caller=release.go:316 component=release release=prometheus-stack targetNamespace=monitoring resource=monitoring:helmrelease/prometheus-operator helmVersion=v3 error="installation failed: ServiceMonitor.monitoring.coreos.com "prometheus-stack-grafana" is invalid: spec.endpoints.interval: Invalid value: "null": spec.endpoints.interval in body must be of type string: "null"" phase=install```

**Comment by appanycd** [comment]
No, i have not, default

I migrated from stable/prometheus-operator, all worked fine. Is it a breaking change? Should i set all ServiceMonitor

```yaml
# ...
prometheus:
  # ...
  prometheusSpec:
    # ...
    scrapeInterval: {{ prometheus.scrapeInterval }} # 30s
# ...
```
