### ISSUE TITLE
[kube-prometheus-stack] Cannot disable default alert 'KubeProxyDown'

### ISSUE THREAD

**Issue by slushysnowman** [prometheus-community/helm-charts#1718]
### Describe the bug a clear and concise description of what the bug is.

Disabling 'KubeProxyDown' default alert rule via values.yaml fails due to causing invalid spec:
```
error validating "": error validating data: ValidationError(PrometheusRule.spec.groups[0]): missing required field "rules" in com.coreos.monitoring.v1.PrometheusRule.spec.groups
```

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

30.0.1

### What happened?

I'm trying to disable the 'KubeProxyDown' alert by adding the following to the values.yaml:
```
defaultRules:
  create: true
  rules:
    kubernetesSystem: true
  disabled:
    KubeProxyDown: true
```
However, disabling this alert in this way fails:
```
error validating "": error validating data: ValidationError(PrometheusRule.spec.groups[0]): missing required field "rules" in com.coreos.monitoring.v1.PrometheusRule.spec.groups
```
Looking at the chart, this seems to be because [this is the only alert in the group](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kube-proxy.yaml), so disabling it causes the spec to be invalid

### What you expected to happen?

The alert should be disabled without causing an invalid spec, as currently disabling it causes deployment of helm chart to fail

### How to reproduce it?

Add the following to values.yaml for kube-prometheus-stack v30.0.1

```
defaultRules:
  create: true
  rules:
    kubernetesSystem: true
  disabled:
    KubeProxyDown: true
```

### Enter the changed values of values.yaml?

```
defaultRules:
  create: true
  rules:
    kubernetesSystem: true
  disabled:
    KubeProxyDown: true
```

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/kube-prometheus-stack --version 30.0.1 --values values.yaml

**Comment by hgranillo** [comment]
Hi @slushysnowman I encountered this same issue while trying to disable the alerts for kube-proxy (because can't scrap metrics in EKS while using the managed add-ons), as a workaround I managed to disable the alerts by just disabling the rule:

```
defaultRules:
  rules:
    kubeProxy: false
```

But removing the scrap rules won't make your Prometheus stop trying to scrap metrics, so in my case I just removed the scrap config of kube-proxy
```
kubeProxy:
  enabled: true
```

Hope this helps to mitigate this issue until it gets fixed.

**Comment by slushysnowman** [comment]
Aha! Thanks @hgranillo I think you might have supplied me a workaround that will actually work! I missed that we could do it via the .Values.defaultRules.rules.kubeProxy.

Thanks for the tip!

**Comment by apollie** [comment]
Also other rule files are having similar issues.
For instance the KubeScheduler: 
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-scheduler.yaml#L27
`rules` can't be empty, so the fix should probably look like this:
`rules:
  {{- if .Values.kubeScheduler.enabled }}
  ...  
  {{- else }}  
  {}  
  {{- end }}
`

**Comment by demahum** [comment]
As pointed above, the issue indeed is with the alerting rules that are coming from the files where there are no other alerting rules defined.

Hence, for example, it is possible to disable [AlertmanagerFailedReload](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/alertmanager.rules.yaml#L30), but disabling [KubeProxyDown](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kube-proxy.yaml#L28) yields an error.

**Comment by Aaron-ML** [comment]
Bumping, This is still an issue as of today.

**Comment by baznikin** [comment]
Same for KubeSchedulerDown and KubeControllerManagerDown !

**Comment by MichaelTrip** [comment]
Same. KubeProxy disabled doesn't work. Bump.

**Comment by ahsan-raza** [comment]
I have spent countless hours trying to implement this: https://stackoverflow.com/questions/73031228/getting-kubecontrollermanager-kubeproxy-kubescheduler-down-alert-in-kube-prome but finally I found this thread. I am facing the same problem on GKE that `kubeProxyDown` , `kubeControllerManagerDown` and `kubeSchedulerDown`are always firing. I have even tried to send them `null` receiver in alertmanager but does not work. Please resolve this!

**Comment by hitmatt** [comment]
I was able to get those 3 alerts not to fire. (kubeProxyDown , kubeControllerManagerDown and kubeSchedulerDown)

Flip them to false under the defaultRules, and then add 2 additional Disables for kubeControllerManager and kubeProxy.

` defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    configReloaders: true
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    **kubeControllerManager: false**
    kubelet: true
    **kubeProxy: false**
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    **kubeSchedulerAlerting: false**
    kubeSchedulerRecording: true
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true

<SNIP>

 kubeProxy:
  enabled: false

kubeControllerManager:
  enabled: false
`

**Comment by hgranillo** [comment]
Hi @takashoty disabling the default rules using `defaultRules.disabled.<rule>` won't make your Prometheus stop trying to scrap metrics and failing to do so and triggering the target down rule for that component. 

You can remove the targets  and everything related to those components with the following configuration:

```
# Disable creation of Targets, Alert|Recording Rules and Dashboards of resources we can't scrap
kubeProxy:
  enabled: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false
```

Link to the value file for reference: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1782

**Comment by javydekoning** [comment]
This worked for me:

```yaml
defaultRules:
  rules:
    # Disable KubeSchedulerDown, KubeProxyDown, KubeControllerManagerDown
    # because running in k3s
    kubeControllerManager: false
    kubeProxy: false
    kubeSchedulerAlerting: false
kubeProxy:
  enabled: false
kubeControllerManager:
  enabled: false
```

**Comment by laviniamnedelea** [comment]
Bumping, as I am experiencing this as well

**Comment by sunwenbo** [comment]
```
  disabled:
    InfoInhibitor: true
    Watchdog: true
    CPUThrottlingHigh: true
    KubeDaemonSetMisScheduled: true
```
This configuration can solve the problem of not automatically creating the specified rules
