### ISSUE TITLE
[kube-prometheus-stack] Allow to set grafana datasource UID

### ISSUE THREAD

**Issue by TeddyAndrieux** [prometheus-community/helm-charts#1720]
### Is your feature request related to a problem ?

No

### Describe the solution you'd like.

Since we should use UID to reference a Grafana Datasource from a Grafana dashboard, could be cool to be able to set the UID for Prometheus Datasource created from the helm chartPrometheus. (also rework a bit the layout so that we can set some variables for "default Datasource" and "replicas Datasource")

From helm option file being able to do something like that:
```yaml
grafana:
  sidecar:
    datasources:
      default:
        enabled: true
        uid: my-default-prometheus-ds
```

### Describe alternatives you've considered.

As an alternative solution with today helm chart we can just do it by disabling the default Datasource and creating an "additional" one with the UID

```yaml
grafana:
  sidecar:
    datasources:
      defaultDatasourceEnabled: false

  additionalDataSources:
    - name: Prometheus
      uid: my-default-prometheus-ds
      type: prometheus
      access: proxy
      isDefault: true
      url: <prometheus service URL>
      jsonData:
        timeInterval: 30s
```
