### ISSUE TITLE
[kube-prometheus-stack] Some metrics missing, therefore grafana have empty graphics

### ISSUE THREAD

**Issue by andrey-gava** [prometheus-community/helm-charts#1725]
### Describe the bug a clear and concise description of what the bug is.

Fresh install of chart. 
Part of Grafana dashboards missing values. For example CPU quota, CPU usage etc. 
Several dashboards a completely empty (Compute Resources Workload, Networking Namespace Workload)
I look in prometheus and there none metrics which have name that starts from "node_namespace_"
I tried uninstall and install version 30.0.0 but things are the same

![image](https://user-images.githubusercontent.com/59727632/150092006-bd0c61a3-00d4-4cf8-ba38-01f62dbdc9da.png)
![image](https://user-images.githubusercontent.com/59727632/150091743-aeef1c67-5a56-4411-86d1-8ad6b9defe11.png)
![image](https://user-images.githubusercontent.com/59727632/150091856-966ddb02-38ac-4d8a-a44c-a93ab0a8632b.png)
Screens from my external grafana, in the bundled grafana everything the same. 

### What's your helm version?

3.5.1

### What's your kubectl version?

v1.19

### Which chart?

kube-prometheus-stack

### What's the chart version?

30.0.1

### Enter the changed values of values.yaml?

```
defaultRules:
  create: false
alertmanager:
  enabled: false
grafana:
  enabled: true
prometheus:
  service:
    nodePort: 30090
    type: NodePort
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: true
    serviceMonitorSelectorNilUsesHelmValues: false
    remoteWrite:
     - url: http://192.168.3.100:8428/api/v1/write
    externalLabels:
      svc: kubernetes
      project: portal
    retention: 14d
kubeScheduler:
  enabled: false
  serviceMonitor:
    enabled: false
kubeEtcd:
  service:
    port: 2381
    targetPort: 2381
kubeControllerManager:
  enabled: false
  serviceMonitor:
    enabled: false
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install -n monitoring kube-prometheus-stack ./kube-prometheus-stack-30.0.1.tgz -f custom-values.yaml --atomic

**Comment by avakarev** [comment]
Hi @andrey-gava, try to add
```
kube-state-metrics:
  releaseLabel: true
```
To your chart values.

**Comment by andrey-gava** [comment]
> Hi @andrey-gava, try to add
> 
> ```
> kube-state-metrics:
>   releaseLabel: true
> ```
> 
> To your chart values.

Its already defined inside default values and set to true.
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1322

**Comment by altitudems** [comment]
Can confirm same issue here, also pointing to 30.0.1.

My `values.yaml`
```yaml
prometheus:
  prometheusSpec:
    retention: 3d
    replicas: 1
    podAntiAffinity: "hard"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 1Gi
nodeExporter:
  enabled: true
kubeStateMetrics:
  enabled: true
kube-state-metrics:
  releaseLabel: true
  selfMonitor:
    enabled: false
```
