### ISSUE TITLE
[kube-prometheus-stack] name label key is not standardized

### ISSUE THREAD

**Issue by dioguerra** [prometheus-community/helm-charts#1728]
### Describe the bug a clear and concise description of what the bug is.

The key on name label generated for kube-prometheus-stack-operator is not standard with the other pods on the deployment.
In the deployed version the label is 
```
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/instance: cern-magnum
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 20.0.1
    chart: kube-prometheus-stack-20.0.1
```
and it should be (to be standardized with the rest of the pods in the deployment)
```
  labels:
    app.kubernetes.io/name: kube-prometheus-stack-operator
    app.kubernetes.io/instance: cern-magnum
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 20.0.1
    chart: kube-prometheus-stack-20.0.1

```

### What's your helm version?

version.BuildInfo{Version:"v3.7", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}

### What's your kubectl version?

Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

20.0.1

### Enter the command that you execute and failing/misfunctioning.

kubectl get po -oyaml ...
