### ISSUE TITLE
[kube-prometheus-stack] Add `queueConfig` / `queue_config` to Prometheus CRD to add support AWS Managed Prometheus

### ISSUE THREAD

**Issue by bryankaraffa** [prometheus-community/helm-charts#1733]
### Is your feature request related to a problem ?

The PrometheusSpec / RemoteWriteSpec have support for `queueConfig` which is missing in the CRDs on the kube-prometheus-stack helm chart.

https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#remotewritespec
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#queueconfig

> QueueConfig allows the tuning of remote_write queue_config parameters. This object is referenced in the RemoteWriteSpec object.

[AWS Managed Prometheus Docs](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-ingest-metrics-existing-Prometheus.html) suggest using the queueConfig to tune the remoteWrite spec:
```yaml
prometheus:
  prometheusSpec:
    remoteWrite:
    - url: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-cebggdc1-abc1-23bc-1a9h-2ja4ef2ce823/api/v1/remote_write
      sigv4:
        region: us-east-1
      queue_config:
        max_samples_per_send: 1000
        max_shards: 200
        capacity: 2500
```

The error with this suggested configuration is a ValidationError:
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Prometheus.spec.remoteWrite[0]): unknown field "queue_config" in com.coreos.monitoring.v1.Prometheus.spec.remoteWrite`

I currently have the suggested `queue_config` commented out/disabled in my values, and the remote_write appears to be working so this is not an urgent or blocking issue.

Using kube-prometheus-stack chart version `30.1.0` [latest as of this writing]

### Describe the solution you'd like.

I would like to see the CRDs in kube-prometheus-stack chart to be updated to what's in the latest PrometheusOperator spec if possible.  If that scope of work is too large or blocked by something, it would be nice to add just the necessary queue_config specs to support AWS Managed Prometheus in the meantime.

### Describe alternatives you've considered.

One possible alternative is to switch from a single helm release using kube-prometheus-stack helm chart, to multiple releases using the "vanilla" prometheus chart which does not use PrometheusOperator

**Comment by dmitriyr333** [comment]
This worked for me with the latest CRD `prometheuses.monitoring.coreos.com` version `v0.6.2` 
```
prometheus:
  prometheusSpec:
    remoteWrite:
             - url: "REDACTED"
                sigv4:
                  region: us-east-1
                queueConfig:
                  maxSamplesPerSend: 1000
                  maxShards: 200
                  capacity: 2500
```

**Comment by seecsea** [comment]
> This worked for me with the latest CRD `prometheuses.monitoring.coreos.com` version `v0.6.2`
> 
> ```
> prometheus:
>   prometheusSpec:
>     remoteWrite:
>              - url: "REDACTED"
>                 sigv4:
>                   region: us-east-1
>                 queueConfig:
>                   maxSamplesPerSend: 1000
>                   maxShards: 200
>                   capacity: 2500
> ```

I use 0.6.2 too, but the final Prometheus(kube-prometheus-kube-prome-prometheus)'s remoteWrite configuration only have url and sigv4, no any about queue_config's configuration

spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: kube-prometheus-kube-prome-alertmanager
      namespace: prometheus-namespace
      pathPrefix: /
      port: http-web
  enableAdminAPI: false
  externalUrl: http://kube-prometheus-kube-prome-prometheus.prometheus-namespace:9090
  image: quay.io/prometheus/prometheus:v2.33.1
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: kube-prometheus
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: kube-prometheus
  remoteWrite:
  - sigv4:
      region: us-east-2
    url: https://aps-workspaces.us-east-2.amazonaws.com/workspaces/ws-0106f91a-1234-3456-5678-f054311c4cf2/api/v1/remote_write
  replicas: 1
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: kube-prometheus
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: amp-iamproxy-ingest-service-account
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: kube-prometheus
  shards: 1
  version: v2.33.1

**Comment by seecsea** [comment]
> This worked for me with the latest CRD `prometheuses.monitoring.coreos.com` version `v0.6.2`
> 
> ```
> prometheus:
>   prometheusSpec:
>     remoteWrite:
>              - url: "REDACTED"
>                 sigv4:
>                   region: us-east-1
>                 queueConfig:
>                   maxSamplesPerSend: 1000
>                   maxShards: 200
>                   capacity: 2500
> ```

I use 0.6.2 too, but the final Prometheus(kube-prometheus-kube-prome-prometheus)'s remoteWrite configuration only have url and sigv4, no any about queue_config's configuration

```
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: kube-prometheus-kube-prome-alertmanager
      namespace: prometheus-namespace
      pathPrefix: /
      port: http-web
  enableAdminAPI: false
  externalUrl: http://kube-prometheus-kube-prome-prometheus.prometheus-namespace:9090
  image: quay.io/prometheus/prometheus:v2.33.1
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: kube-prometheus
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: kube-prometheus
  remoteWrite:
  - sigv4:
      region: us-east-2
    url: https://aps-workspaces.us-east-2.amazonaws.com/workspaces/ws-0106f91a-1234-5678-3456-f054311c4cf2/api/v1/remote_write
  replicas: 1
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: kube-prometheus
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: amp-iamproxy-ingest-service-account
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: kube-prometheus
  shards: 1
  version: v2.33.1
```
this is install prometheus-community/kube-prometheus-stack, no queue_config's configuration

BUT install prometheus-community/prometheus everything are OK

**Comment by seecsea** [comment]
> This worked for me with the latest CRD `prometheuses.monitoring.coreos.com` version `v0.6.2`
> 
> ```
> prometheus:
>   prometheusSpec:
>     remoteWrite:
>              - url: "REDACTED"
>                 sigv4:
>                   region: us-east-1
>                 queueConfig:
>                   maxSamplesPerSend: 1000
>                   maxShards: 200
>                   capacity: 2500
> ```

I use 0.6.2 too, but the final Prometheus(kube-prometheus-kube-prome-prometheus)'s remoteWrite configuration only have url and sigv4, no any about queue_config's configuration

```
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: kube-prometheus-kube-prome-alertmanager
      namespace: prometheus-namespace
      pathPrefix: /
      port: http-web
  enableAdminAPI: false
  externalUrl: http://kube-prometheus-kube-prome-prometheus.prometheus-namespace:9090
  image: quay.io/prometheus/prometheus:v2.33.1
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: kube-prometheus
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: kube-prometheus
  remoteWrite:
  - sigv4:
      region: us-east-2
    url: https://aps-workspaces.us-east-2.amazonaws.com/workspaces/ws-0106f91a-1234-5678-3456-f054311c4cf2/api/v1/remote_write
  replicas: 1
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: kube-prometheus
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: amp-iamproxy-ingest-service-account
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: kube-prometheus
  shards: 1
  version: v2.33.1
```
this is install prometheus-community/kube-prometheus-stack, no queue_config's configuration

BUT install prometheus-community/prometheus everything are OK

**Comment by seecsea** [comment]
helm get manifest kube-prometheus -n prometheus-namespace >123.yaml
in 123.yaml，there has the queue_config configuration：
```
spec:
  alerting:
    alertmanagers:
      - namespace: prometheus-namespace
        name: kube-prometheus-kube-prome-alertmanager
        port: http-web
        pathPrefix: "/"
        apiVersion: v2
  image: "quay.io/prometheus/prometheus:v2.33.1"
  version: v2.33.1
  externalUrl: http://kube-prometheus-kube-prome-prometheus.prometheus-namespace:9090
  paused: false
  replicas: 1
  shards: 1
  logLevel:  info
  logFormat:  logfmt
  listenLocal: false
  enableAdminAPI: false
  retention: "10d"
  routePrefix: "/"
  serviceAccountName: amp-iamproxy-ingest-service-account
  serviceMonitorSelector:
    matchLabels:
      release: "kube-prometheus"

  serviceMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: "kube-prometheus"

  podMonitorNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: "kube-prometheus"

  probeNamespaceSelector: {}
  remoteWrite:
    - queue_config:
        capacity: 2500
        max_samples_per_send: 1000
        max_shards: 200
      sigv4:
        region: us-east-2
      url: https://aps-workspaces.us-east-2.amazonaws.com/workspaces/ws-0106f91a-1234-5678-3456-f054311c4cf2/api/v1/remote_write
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: "kube-prometheus"

  portName: http-web
```
