### ISSUE TITLE
[kube-prometheus-stack] Tighten securityContext to comply with restricted PSS

### ISSUE THREAD

**Issue by seilersTNG** [prometheus-community/helm-charts#1749]
### Is your feature request related to a problem ?

In the context of Pod Security Policy (PSP) deprecation (https://kubernetes.io/docs/concepts/policy/pod-security-policy/), I tried to enforce the new restricted Pod Security Standard (PSS) (https://kubernetes.io/docs/concepts/security/pod-security-standards/).

In the case of the alertmanager, I did not find a possibility to restrict the container securityContext. 

Background: findings for the restricted PSS were:
"allowPrivilegeEscalation != false, unrestricted capabilities, seccompProfile"

The latter two can be resolved by setting the pod securityContext to:
```
securityContext:
  seccompProfile:
    type: RuntimeDefault
```
Yet it is not possible to set `allowPrivilegeEscalation: false` as this is only possible in container securityContext

### Describe the solution you'd like.

I would be happy, if the container securityContext can be set for alertmanager.

### Describe alternatives you've considered.

NONE

### Additional context.

Generally, I thought it would be a good idea to have some of the securityContext settings that I had to make for complying with the restricted PSS, maybe as a default in the future because it would be possible for users to directly enforce the restricted PSS for the given namespace:
I want to share the settings I had to make in my case:

For alertmanager, prometheus and prometheusOperator, most problems were resolved by restricting the seccompProfile to RuntimeDefault:
```
securityContext:
  seccompProfile:
    type: RuntimeDefault
```
---

restricted PSS findings:
alertmanager: allowPrivilegeEscalation != false, unrestricted capabilities, seccompProfile
prometheus: allowPrivilegeEscalation != false, unrestricted capabilities, seccompProfile
prometheusOperator: unrestricted capabilities, seccompProfile

**Comment by xiefei001** [comment]
Any update? We are facing the same issue and can't set the `allowPrivilegeEscalation` at the container level for _alertmanager_ and _prometheus_.

**Comment by luislhl** [comment]
This is possible by using PrometheusOperator's strategic-merge-patch: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/strategic-merge-patch.md

The values should look something like this:
```yaml
alertmanager:
      alertmanagerSpec:
        containers:
        - name: alertmanager
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
            seccompProfile:
              type: RuntimeDefault
```
