### ISSUE TITLE
set up basic auth for Alermanager and Prometheus UI via kube-prometheus-stack

### ISSUE THREAD

**Issue by kotnn** [prometheus-community/helm-charts#1754]
### Is your feature request related to a problem ?

Possibility to set up basic auth for Alermanager and Prometheus UI via kube-prometheus-stack, and also basic auth for node exporters

### Describe the solution you'd like.

values.yaml and dependent charts don't provide values for p basic auth for Alermanager and Prometheus UI via kube-prometheus-stack, and also basic auth for node exporters.
The only thing available is certificates, but it is not what i want to see

### Describe alternatives you've considered.

-

**Comment by matejhasul** [comment]
IMHO this is possible, this is how my values file looks like:
```
    prometheus:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
          nginx.ingress.kubernetes.io/auth-realm: Authentication Required - whatever
          nginx.ingress.kubernetes.io/auth-secret: prometheus-server-basic-auth
          nginx.ingress.kubernetes.io/auth-secret-type: auth-map
          nginx.ingress.kubernetes.io/auth-type: basic
        enabled: true
        hosts:
        - p8s.example.com
        ingressClassName: nginx
        tls:
        - hosts:
          - p8s.example.com
          secretName: prometheus-server-tls
```
Same should be possible with alertmanager.

**Comment by dchiaramello** [comment]
Hello, I'm facing the same issue: I didn't find a way to add BasicAuth to my configuration...

For TLS, I'm using `prometheus.prometheusSpec.web.tlsConfig`, after I have manually created the corresponding `secret-certs` secret:
```
prometheus:
  prometheusSpec:
    web:
      tlsConfig:
        keySecret:
          name: secret-certs
          key: secret-key
        cert:
          secret:
            name: secret-certs
            key: secret-cert
        clientAuthType: NoClientCert
```
But I failed to find a solution to add BasicAuth on top of it. And my knowledge is too weak to be able to understand how to use ingress, as suggested by @matejhasul  above...

**Comment by alexei-bykovski** [comment]
Are there any update about using basic auth in kube-prometheus-stack?

**Comment by vhadianto** [comment]
Bump ...

I've been trying to enable Basic Authentication in kube-prometheus-stack. The documentation https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#apiserverconfig seems to indicate that I should be able to enable Basic Auth as follow:

```yaml
    apiserverConfig:
      # Prometheus host, have tried with/without svc.cluster.local
      host: prometheus-kube-pr-prometheus.prometheus.svc.cluster.local:9090
      basicAuth:
        username:
          name: prometheus-basic-auth
          key: username
        password:
          name: prometheus-basic-auth
          key: password
```

No luck ... I am still able to access Prometheus API without authentication.

**Comment by pen-pal** [comment]
were you able to achive the solution?
@vhadianto

**Comment by MariusMiricaBE** [comment]
@vhadianto Did you have any success?

**Comment by vhadianto** [comment]
@pen-pal / @MariusMiricaBE 

Unfortunately no, I haven't been able to solve this. We are changing tack with our Prometheus deployment so this is no longer a critical issue for us.

**Comment by pen-pal** [comment]
I did solve the issue after using nginx controller for prometheus.

**Comment by chegde20121** [comment]
Are there any way to add basic auth by using this chart?

**Comment by pen-pal** [comment]
> Are there any way to add basic auth by using this chart?

@chegde20121 you can do it using nginx controller for prometheus basic auth

**Comment by zhoulf1006** [comment]
### The ingress auth way:
**generate a password and bcrypt it**
https://kubernetes.github.io/ingress-nginx/examples/auth/basic/

**create a secret for auth:**
`kubectl -n monitoring create secret generic prometheus-basic-auth \
  --from-literal=auth='admin:<bcrypted password>'
`

**add the configs in the helm value files:**
```
prometheus:
  ingress:
    enabled: true
    ingressClassName: internal-nginx   # your ingressclass name you previously created
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    hosts:
    - <my-prom-fqdn>
    paths:
    - "/prometheus(/|$)(.*)"
  prometheusSpec:
    externalUrl: "https://<my-prom-fqdn>/prometheus"
```

Because you have exposed the url as `https://<my-prom-fqdn>/prometheus`, when visiting this url, you will be asked to input the user & password.
or use `curl` to test it:
```
curl http://<ingress-ip>/prometheus/ -u 'admin:<password>' -H 'host:<my-prom-fqdn>'
```

### Limitation:
After I have finished the auth on ingress, I have found the bottleneck of this solution.
I configure the datasource on grafana with auth, and getting data from prometheus, the nginx ingress pod cpu got obviously rised.
So if you want to use the ingress, you should create a seperate ingress only for prometheus usage, don't combine it with your exsiting one. Otherwise it would affect your applications.
