### ISSUE TITLE
[prometheus-operator] Relabeling in alert rule

### ISSUE THREAD

**Issue by KR411-prog** [prometheus-community/helm-charts#176]
I have a pod label as "test.com/team= teamA"

I used below expression to extract this label into alert rule,
"* on(namespace, pod) group_left(label_test_com_team) kube_pod_labels "

This works in the alert rule,
and the label name appears as "label_test_com_team" in the alerts.

But I want to use label as "test.com/team" in the alerts.
Does Relabeling help in this case?

If yes,I tried below config,but it fails with the error.
```
kubeStateMetrics:
  serviceMonitor:
    metricRelabelings:
    - sourceLabels: [label_test_com_team]
      targetLabel: test.com/team
      action: replace
```
Error:
(--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: \"test.com/team\" is invalid 'target_label' for replace action"

So I tried a simple targetLabel named "team".This time no error ,but I dont see the relabeling happened.The alert still shows label_test_com_team.

How to fix this relabelling and also with special characters "test.com/team"? 

Prometheus Operator chart version: 9.3.1

Insert image tag or Git SHA here

quay.io/coreos/prometheus-operator:v0.38.1

Kubernetes version information:

kubectl version 1.15

Kubernetes cluster kind: EKS

**Comment by finkr** [comment]
I have the same issue when the target label contains a dash

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
[..]
  targetLabels:
  - app_kubernetes_io_name
    app_kubernetes_io_part_of
  endpoints:
  - port: http-metrics
    path: /metrics
    metricRelabelings:
    - sourceLabels: [app_kubernetes_io_name]
      targetLabel: app
    - sourceLabels: [app_kubernetes_io_part_of]
      targetLabel: "part-of"
```



It would be nice to check Prometheus [data model](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels)
