### ISSUE TITLE
[alertmanager] add support for extraFlags in its helm chart

### ISSUE THREAD

**Issue by dmpe** [prometheus-community/helm-charts#1761]
### Is your feature request related to a problem ?

`extraFlags`  shall be added to the alarm manager helm chart

### Describe the solution you'd like.

Be able to say:

```
  extraFlags:
    - log-level=debug
```

### Describe alternatives you've considered.

The alternative would be:

```
alertmanagerFiles: 
  log.level: debug
  alertmanager.yml:
   .....
```
