### ISSUE TITLE
[prometheus-kube-stack] Failed to call webhook

### ISSUE THREAD

**Issue by fdarif** [prometheus-community/helm-charts#1762]
### Describe the bug a clear and concise description of what the bug is.

I am trying to install the `kube-prometheus-stack`  from the officiel `prometheus-community`  helm repo, I am using the command below
`helm install <release-name> prometheus-community/kube-prometheus-stack -n <namespace>-f values.yaml` .
And the error below has been occured.
`Error: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post "https://kube-prometheus-kube-prome-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=10s": service "kube-prometheus-kube-prome-operator" not found`

### What's your helm version?

Version:"v3.6.2"

### What's your kubectl version?

Client Version: v1.21.1 Server Version: v1.22.4

### Which chart?

prometheus-community/kube-prometheus-stack

### What's the chart version?

kube-prometheus-stack-30.2.0 

### Enter the changed values of values.yaml?

```
operator:
  affinity: {}
  configReloaderResources: {}
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    enabled: true
    readOnlyRootFilesystem: false
    runAsNonRoot: true
  enabled: true
  hostAliases: []
  image:
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/prometheus-operator
    tag: 0.50.0-debian-10-r8
  kubeletService:
    enabled: true
    namespace: kube-system
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 120
    path: /metrics
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  logFormat: logfmt
  logLevel: info
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  podSecurityContext:
    enabled: true
    fsGroup: 1002
    runAsUser: 1002
  priorityClassName: ""
  prometheusConfigReloader:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      enabled: true
      readOnlyRootFilesystem: false
      runAsNonRoot: true
    image: {}
    livenessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      enabled: true
      failureThreshold: 6
      initialDelaySeconds: 15
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 5
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 30
    path: /metrics
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  resources: {}
  schedulerName: ""
  service:
    annotations: {}
    clusterIP: ""
    externalTrafficPolicy: Cluster
    healthCheckNodePort: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePort: ""
    port: 8080
    type: ClusterIP
  serviceAccount:
    create: false
    name: ""
  serviceMonitor:
    enabled: true
    interval: ""
    metricRelabelings: []
    relabelings: []
  tolerations: []
```

### Enter the command that you execute and failing/misfunctioning.

None

### Anything else we need to know?

None

**Comment by obvionaoe** [comment]
I get this when:
```yaml
prometheusOperator:
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false
```
