### ISSUE TITLE
[prometheus-kube-stack] prometheus-grafana ServiceMonitor has null 'interval' value in generated YAML

### ISSUE THREAD

**Issue by tjmoyes** [prometheus-community/helm-charts#1776]
### Describe the bug a clear and concise description of what the bug is.

When running the `helm install prometheus prometheus-community/kube-prometheus-stack` command, most resources deploy successfully, until you get to the prometheus-grafana ServiceMonitor, where you get the following error:

`Error: ServiceMonitor.monitoring.coreos.com "prometheus-grafana" is invalid: spec.endpoints.interval: Invalid value: "null": spec.endpoints.interval in body must be of type string: "null"`

Manually entering a value (15s, from what I could find from an older deployment) and applying the YAML works. 

### What's your helm version?

version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1

### Which chart?

prometheus-kube-stack

### What's the chart version?

32.0.1

### What happened?

When running the `helm install prometheus prometheus-community/kube-prometheus-stack` command, most resources deploy successfully, until you get to the prometheus-grafana ServiceMonitor, where you get the following error:

`Error: ServiceMonitor.monitoring.coreos.com "prometheus-grafana" is invalid: spec.endpoints.interval: Invalid value: "null": spec.endpoints.interval in body must be of type string: "null" `

This error causes `helm list` to show no deployments but repeating `helm install` will not work until you clear out all of the Prometheus elements which were successfully deployed. 

Repeating this command with the `--dry-run` flag, and outputting to a YAML file reveals that the 'interval' value is indeed null, where it should have a value.

```
# Source: kube-prometheus-stack/charts/grafana/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-grafana
  labels:
    helm.sh/chart: grafana-6.21.2
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "8.3.4"
    app.kubernetes.io/managed-by: Helm
spec:
  endpoints:
  - interval:  # there should be a value here
    scrapeTimeout: 30s
    honorLabels: true
    port: http-web
    path: /metrics
    scheme: http
  jobLabel: "prometheus"
  selector:
    matchLabels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: prometheus
  namespaceSelector:
    matchNames:
      - monitor
```

### What you expected to happen?

I expected the deployment to succeed and give the confirmation message.

### How to reproduce it?

Simply run `helm install prometheus prometheus-community/kube-prometheus-stack`

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/kube-prometheus-stack

**Comment by tjmoyes** [comment]
I'd like to add that adding the `--version 31.0.2` flag to the install command succeeds, so this is an issue that is new to version 32.0.0 or 32.0.1

**Comment by kaykhancheckpoint** [comment]
Also just had this issue

**Comment by AnvilFox1965** [comment]
Same here

**Comment by kaykhancheckpoint** [comment]
> > 
> 
> No, it is not, at least not from what I can see.

Ye i just saw by default it does not create the pvc you have to set it.

**Comment by edumatrixx** [comment]
Facing the same issue here.

**Comment by cwrau** [comment]
Having the same problem, setting the interval to `"30"` doesn't help, the quotes get lost during the templating

**Comment by faiaz-halim** [comment]
Just to update here, following worked for me, chart version 32.1.0, 0.54.0
```

  serviceMonitor:
    # If true, a ServiceMonitor CRD is created for a prometheus operator
    # https://github.com/coreos/prometheus-operator
    #
    enabled: true

    # Path to use for scraping metrics. Might be different if server.root_url is set
    # in grafana.ini
    path: "/metrics"

    #  namespace: monitoring  (defaults to use the namespace this chart is deployed to)

    # labels for the ServiceMonitor
    labels: {}

    # Scrape interval. If not set, the Prometheus default scrape interval is used.
    #
    interval: "30s"
    scheme: http
    tlsConfig: {}
    scrapeTimeout: 30s
    
```
It expects time in string in interval section, not integer.

for prometheus pvc issue, following worked for me, (somehow "selector" is being shown as unknown field for helm chart deployment in com.coreos.monitoring.v1.Prometheus.spec.storage.volumeClaimTemplate, so disabled that. It gets bound to prometheus stateful pod without any problem)
```

    storageSpec:
    ## Using PersistentVolumeClaim
    ##
      volumeClaimTemplate:
        spec:
          storageClassName: your_storage_class
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
        # selector:
        #   matchLabels:
        #     app: prometheus

```
