### ISSUE TITLE
prometheus-json-exporter Support Secrets

### ISSUE THREAD

**Issue by cskinfill** [prometheus-community/helm-charts#1784]
### Is your feature request related to a problem ?

Currently, there's no way to use the helm chart for prometheus-json-exporter and add a secret to be used for an http basic auth password (for instance).  Providing a way to use an existing Secret would help.

### Describe the solution you'd like.

Add something like this to the values
```
existingSecret:
- name: <some secret in the same namespace>
  path: <if mounting the secret as a file>
  env: <if exposing secret as env vars>
```

### Describe alternatives you've considered.

Put the basic auth password in the configmap
