### ISSUE TITLE
[prometheus-kube-stack] AlertmanagerConfig CRD not getting merged with Alertmanager config

### ISSUE THREAD

**Issue by rhollins** [prometheus-community/helm-charts#1785]
### Describe the bug a clear and concise description of what the bug is.

I'm trying to customize Alertmanager with custom config using AlertmanagerConfig CDR and following this instruction: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/alerting.md

I have alert manager in debug mode and cant see any event when the CRD AlertmanagerConfig  is gettign created.

It does work when I replace secret `alertmanager-prometheus-kube-prometheus-alertmanager` `alertmanager.yaml` but would rather use CRD as the preferred method.

Here is Alertmanager resource:

```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
  generation: 2
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 30.2.0
    chart: kube-prometheus-stack-30.2.0
    heritage: Helm
    release: prometheus
  name: prometheus-kube-prometheus-alertmanager
  namespace: monitoring
spec:
  alertmanagerConfigNamespaceSelector: {}
  alertmanagerConfigSelector:
    matchLabels:
      release: prometheus
  externalUrl: ...
  forceEnableClusterMode: true
  image: quay.io/prometheus/alertmanager:v0.23.0
  listenLocal: false
  logFormat: logfmt
  logLevel: debug
  paused: false
  portName: http-web
  replicas: 1
  retention: 120h
  routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-kube-prometheus-alertmanager
  version: v0.23.0
```

AlertmanagerConfig resource

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-alertmanager
  labels:
    release: prometheus
spec:
  route:
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'slack'
  receivers:
  - name: 'slack'
    slackConfigs:
    - sendResolved: true
      apiURL:
        name: slack-secret
        key: url
      channel: '#some-monitoring'
      title: 'some alert title'
      text: 'some description'
```

Helm values for alertmanager:

```
    alertmanagerConfigSelector:
      matchLabels:
        release: prometheus
```

### What's your helm version?

v3.7.2

### What's your kubectl version?

v1.22.4

### Which chart?

prometheus-kube-stack

### What's the chart version?

30.2.0

### Enter the command that you execute and failing/misfunctioning.

n/a

**Comment by jeunii** [comment]
Hello. Im using kube-prometheus-stack chart version 39.5.0.
Im am trying to setup slack alerting and want to provide the slack webhook via k8s secret
https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1alpha1.SlackConfig

my config is
```
kube-prometheus-stack:
  alertmanager:
    config:
      receivers:
      - name: 'null'
      - name: slack-pe
        slack_configs:
          - channel: "#pe-infra-alerts"
            apiURL:
              key: 'webhookURL'
              name: 'slack-webhook'
            title: '{{ template "alertmanager.slack.titletext" . }}'
            title_link: '{{ .ExternalURL }}{{ template "alertmanager.slack.titlelink" . }}'
            text: '{{ template "alertmanager.slack.text" . }}'
            send_resolved: true
```
But alertmanager fails to come up with the following error
```
level=error ts=2022-08-11T14:40:19.889481716Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"monitoring/monitoring-kube-prometheus-alertmanager\" failed: provision alertmanager configuration: failed to initialize from secret: yaml: unmarshal errors:\n  line 13: field apiURL not found in type config.plain"
```
The secret is there
```
 k get secrets slack-webhook -o=jsonpath='{.data.webhookURL}'
aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDBKMTRQRDdFL0IwM1NWNUtCU1R.............%
```

is this config not supported yet ? (edited)
