### ISSUE TITLE
How Can we have dashboardProviders section in values.yaml under grafana settings

### ISSUE THREAD

**Issue by shashank-omre-cldcvr** [prometheus-community/helm-charts#1791]
### Is your feature request related to a problem ?

I want to setup folder structure in my kube-promethues-stack grafana.

grafana is getting install by [this](https://github.com/prometheus-community/helm-charts/blob/56006431524a2106a751bd0d2ff1b6e0ac7132b1/charts/kube-prometheus-stack/Chart.yaml#L51) dependency.

### Describe the solution you'd like.

It's very easy to setup in grafana helm repo "https://github.com/grafana/helm-charts/blob/2589a34a7df18a7c3f23e3b4c55ca12a075aa8b7/charts/grafana/values.yaml#L495".

I wanted to know how can i add "dashboardProviders" in my kube-promethues-stack helm chart.

### Describe alternatives you've considered.

i've tried to set this up like this but didn't worked.
```
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'folder-1'
        orgId: `1`
        type: file
        folder: 'folder-1'
        allowUiUpdates: true
        disableDeletion: false
        updateIntervalSeconds: 10
        editable: true
        options:
          path: /tmp/dashboards/folder-1
      - name: 'test-1'
        orgId: 1
        type: file
        folder: 'test-1'
        allowUiUpdates: true
        disableDeletion: false
        updateIntervalSeconds: 10
        editable: true
        options:
          path: /tmp/dashboards/test-1
```

### Additional context.

Is there any way we can setup folder structure in kube grafana?

**Comment by ogechivivian** [comment]
@shashank-omre-cldcvr  have you been able to resolved this

**Comment by YevheniiPokhvalii** [comment]
I'm note sure what issue you had, it works for me on `kube-prometheus-stack 18.0.11` (I also have a sidecar enabled)

```
        grafana:
          enabled: true
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
              folder: /tmp/dashboards
              provider:
                name: sidecarProvider
                orgid: 1
                folder: ''
                type: file
                disableDelete: false
                allowUiUpdates: false
                foldersFromFilesStructure: false
          dashboardProviders:
           dashboardproviders.yaml:
             apiVersion: 1
             providers:
             {{- range $key, $value := .Values.org }}
             - name: {{ $key }}-dashboard-provider
               orgId: {{ $value.grafana.orgID }}
               folder: ''
               type: file
               disableDeletion: true
               editable: true
               options:
                 path: /tmp/dashboards
             {{- end }}

```
