### ISSUE TITLE
 node-exporter not deployed on a master node

### ISSUE THREAD

**Issue by lk7777** [prometheus-community/helm-charts#1793]
### Describe the bug a clear and concise description of what the bug is.

 Kubernetes k3s

node-exporter not deployed on a master node

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:35:46Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5+k3s1", GitCommit:"405bf79da97831749733ad99842da638c8ee4802", GitTreeState:"clean", BuildDate:"2021-12-18T00:43:30Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

 helm-charts/charts/kube-prometheus-stack/

### What's the chart version?

kube-prometheus-stack-32.1.0

### What happened?

It looks like that this is a similar [issue](https://github.com/prometheus-operator/prometheus-operator/issues/570). 

```
kubectl get nodes
NAME           STATUS   ROLES                  AGE   VERSION
k3s-worker-2   Ready    <none>                 15d   v1.22.5+k3s1
k3s-master-1   Ready    control-plane,master   15d   v1.22.5+k3s1
k3s-worker-1   Ready    <none>                 15d   v1.22.5+k3s1

kubectl get pods -n monitoring
NAME                                                     READY   STATUS    RESTARTS       AGE
prometheus-kube-prometheus-operator-675f69cf55-lh6p5     1/1     Running   1 (13h ago)    24h
prometheus-prometheus-node-exporter-4gzpv                1/1     Running   1 (13h ago)    24h
prometheus-kube-state-metrics-57c988498f-cnstv           1/1     Running   1 (13h ago)    24h
prometheus-grafana-5cbbb44849-9hzjr                      3/3     Running   5 (13h ago)    24h
alertmanager-prometheus-kube-prometheus-alertmanager-0   2/2     Running   2 (13h ago)    24h
prometheus-prometheus-node-exporter-tcrbb                1/1     Running   9 (143m ago)   24h
prometheus-prometheus-kube-prometheus-prometheus-0       2/2     Running   2 (128m ago)   3h36m
```

### What you expected to happen?

node-exporter to be deployed on the master node as well

### How to reproduce it?

Proxmox server. 3 Ubuntu 20.04 VMs.

k3s cluster (1 master, 2 workers/agents)
The master installed by running the following command:

`curl -sfL https://get.k3s.io | sh -s - server --node-taint CriticalAddonsOnly=true:NoExecute`

I am not sure if **--node-taint** might block a node-exporter deployment. At least prometheus has been deployed without any error messages.

### Enter the changed values of values.yaml?

 storageSpec:
    ## Using PersistentVolumeClaim
    ##
      volumeClaimTemplate:
        spec:
          storageClassName: managed-nfs-storage
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 20Gi

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --values prometheus.values

**Comment by ogechivivian** [comment]
@lk7777  I am currently experiencing this, Did you find your way around it

**Comment by lk7777** [comment]
@ogechivivian Most likely it happens when a master node is tainted (--node-taint).
Switched from helm to yaml installation, and installed [this](https://prometheus.io/docs/guides/node-exporter/) node exporter.

**Comment by red-lichtie** [comment]
I have the same issue with k3s (v1.24.9+k3s2).

All controller nodes have the "CriticalAddonsOnly=true:NoExecute" taint.

How do I mark/change the daemonset to mark it as a critical addon?

**Comment by pjamenaja** [comment]
I've solved this issue on my RKE2 cluster, the 1st thing I did is to find the "taint" setting on my master nodes and it show in the snippet below.

```
  "--node-taint", 
   "node-role.kubernetes.io/control-plane:NoSchedule",
  "--node-taint",
  "node-role.kubernetes.io/etcd:NoExecute",
```

So I modified the tolerations of my prometheus-node-exporter as shown below (using helm values).
```
prometheus-node-exporter:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists                                                                                                                                                                                            
      effect: NoSchedule

    - key: node-role.kubernetes.io/etcd
      operator: Exists                                                                                                                                                                                            
      effect: NoExecute
```

**Comment by red-lichtie** [comment]
# Update for Node Exporter on Controller nodes

Controller nodes in k3s now have the taint "CriticalAddonsOnly"

```yaml
...
   taints:
   - effect: NoExecute
     key: CriticalAddonsOnly
     value: "true"
...
```

So that the node exporter can also run on these nodes the following toleration has to be added to the exporter daemonset

```yaml
...
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
...
```
