### ISSUE TITLE
[kube-prometheus-stack] Validation error on ports

### ISSUE THREAD

**Issue by samip5** [prometheus-community/helm-charts#1801]
### Describe the bug a clear and concise description of what the bug is.

There's a validation error because of missing required field.

```
kube-prometheus-stack   False   Helm install failed: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Endpoints.subsets[0].ports[0]): missing required field "port" in io.k8s.api.core.v1.EndpointPort   6s
```

### What's your helm version?

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.5"}
```
### What's your kubectl version?

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"archive", BuildDate:"2022-01-28T02:28:27Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"} 
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3+k3s1", GitCommit:"5fb370e53e0014dc96183b8ecb2c25a61e891e76", GitTreeState:"clean", BuildDate:"2022-01-27T02:14:38Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/arm64"}
```
### Which chart?

kube-prometheus-stack

### What's the chart version?

32.2.0

### Enter the changed values of values.yaml?

```yaml
    fullnameOverride: prom-stack
    alertmanager:
      config:
        global:
          slack_api_url: "${SECRET_ALERT_MANAGER_DISCORD_WEBHOOK}"
          resolve_timeout: 5m
        receivers:
          - name: "null"
          - name: "discord"
            slack_configs:
              - channel: "#prometheus"
                icon_url: https://avatars3.githubusercontent.com/u/3380462
                username: "Prometheus"
                send_resolved: true
                title: |-
                  [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if ne .CommonAnnotations.summary ""}}{{ .CommonAnnotations.summary }}{{ else }}{{ .CommonLabels.alertname }}{{ end }}
                text: >-
                  {{ range .Alerts -}}
                    **Alert:** {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
                  **Description:** {{ if ne .Annotations.description ""}}{{ .Annotations.description }}{{else}}N/A{{ end }}
                  **Details:**
                    {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                    {{ end }}
                  {{ end }}
        route:
          group_by: ["alertname", "job"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 6h
          receiver: "discord"
          routes:
            - receiver: "null"
              match:
                alertname: Watchdog
            - receiver: "discord"
              match_re:
                severity: critical
              continue: true
        inhibit_rules:
          - source_match:
              severity: "critical"
            target_match:
              severity: "warning"
            equal: ["alertname", "namespace"]
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - "alert-manager.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - "alert-manager.${SECRET_DOMAIN}"
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 1Gi
    nodeExporter:
      serviceMonitor:
        relabelings:
          - action: replace
            regex: (.*)
            replacement: $1
            sourceLabels:
              - __meta_kubernetes_pod_node_name
            targetLabel: kubernetes_node
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
    prometheus-node-exporter:
      fullnameOverride: node-exporter
    grafana:
      enabled: false
      forceDeployDashboards: true
    kubelet:
      enabled: true
      serviceMonitor:
        metricRelabelings:
          - action: replace
            sourceLabels:
              - node
            targetLabel: instance
    kubeApiServer:
      enabled: true
    kubeControllerManager:
      enabled: true
      endpoints:
        - 10.0.105.10
    kubeScheduler:
      enabled: true
      endpoints:
        - 10.0.105.10
    kubeProxy:
      enabled: true
      endpoints:
        - 10.0.105.10
    kubeEtcd:
      enabled: false
    # Setting this option to 0 disabled CPU limits
    prometheusOperator:
      configReloaderCpu: 0
    prometheus:
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - "prom.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - "prom.${SECRET_DOMAIN}"
      thanosService:
        enabled: false
      prometheusSpec:
        replicas: 1
        replicaExternalLabelName: "replica"
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        retention: 3h
        enableAdminAPI: true
        walCompression: true
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 10Gi
        addionalScrapeConfig:
          - job_name: 'blocky'
            honor_timestamps: true
            static_configs:
              - targets: ['blocky.networking.svc.cluster.local:4000']
```

### Enter the command that you execute and failing/misfunctioning.

GitOps managed cluster, unable to install helm release with my values.

**Comment by ephur** [comment]
I am facing the same issue, installing to minikube, with no values changes or customization:

```
helm install -n prometheus prom-operator prometheus-community/kube-prometheus-stack
Error: INSTALLATION FAILED: failed to create resource: ServiceMonitor.monitoring.coreos.com "prom-operator-grafana" is invalid: spec.endpoints.interval: Invalid value: "null": spec.endpoints.interval in body must be of type string: "null"
```

**Comment by ephur** [comment]
All of the 32.x releases have the same issue, the last working release (for me) is 31.0.2

**Comment by parsec** [comment]
Same here:

```
Normal  error  13m (x3 over 13m)  helm-controller  Helm install failed: unable to build kubernetes objects from release manifest: error │validating "": error validating data: ValidationError(Endpoints.subsets[0].ports[0]): missing required field "port" in io.k8s.api.core.v 1.EndpointPort
```

https://github.com/parsec/home-cluster/blob/main/cluster/apps/monitoring/kube-prometheus-stack/helm-release.yaml

Here's my YAML. Nothing all that out of the ordinary for configuration.

I'm running FluxCD v 0.26, Kubernetes v1.22.6+k3s1, have a Rook-Ceph deployment... using Traefik... I can't think of much else that should be relevant.

**Comment by bstrdsmkr** [comment]
Same issue, but a little progress. I'm deploying to k3s so (at least previously) I've had to specify endpoints for the kube components, ie:
```yaml
kubeControllerManager:
  enabled: true
  endpoints:
  - 10.10.248.160
  - 10.10.248.161
  - 10.10.248.162
```
I had to manually delete the relevant Services:
```
kube-prometheus-stack-kube-scheduler
kube-prometheus-stack-kube-controller-manager
kube-prometheus-stack-kube-etcd
kube-prometheus-stack-kube-proxy
kube-prometheus-stack-kube-state-metrics
```
Which I think is (poorly) alluded to here: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-29x-to-30x

After that and commenting out my kubeScheduler and  kubeControllerManager sections, I'm able to deploy. I haven't narrowed down the exact problem yet, but I suspect there's some broken logic in the rendering of those two services (the kubeProxy and kubeEtcd sections still render fine)
