### ISSUE TITLE
prometheus-kube-stack Datasources are not automaticallty created

### ISSUE THREAD

**Issue by dtroup-global** [prometheus-community/helm-charts#1806]
We have created datasources, from both secrets and from configmaps that should be created as part of the Grafana startup process. They are mounted into ```/etc/grafana/provisioning/datasources``` at pod creation by the sidecar, however, is appears that the grafana container is becoming ready too fast for this to pick up the data sources and tries to add their configuration via the API afterwards. This is causing a 401 Unauthorised message as there is oauth configured on the API it's trying to use.

If we run the ```grafana-server restart``` command within the pod then the data sources then appear as they should do as the config files are in place.

Is there a way we can delay the grafana container starting, and have it wait for the sidecar container to be ready?

Any help appreciated.

**Comment by gi8lino** [comment]
I have the same problem...

**Comment by DodgeCamaro** [comment]
I have the same problem.
helm chart version 34.8, grafana 8.4.5
And had this error at grafana-sc-datasources container
POST request sent to http://localhost:3000/api/admin/provisioning/datasources/reload. Response: 401 Unauthorized {"message":"Unauthorized"}

**Comment by zeritti** [comment]
Grafana chart enables making the datasource sidecar container additionally an init container via `grafana.datasources.initDatasources` (`false` by default). This would mount the datasources before any other container  in the pod starts. May be worth trying. If the sidecar cannot call Grafana API due to required auth, one may also skip reloads via `grafana.datasources.skipReload`. 

There are ways to block the next container in the list from starting up, e.g. via lifecycle, but this would require changes to the Grafana templates.

**Comment by WyriHaximus** [comment]
Setting `grafana.datasources.skipReload` to `true` works, but then it stops picking up dashboards across the cluster

**Comment by nokernel** [comment]
Still present on v34.9.0

**Comment by DodgeCamaro** [comment]
Still present on v34.10.0

**Comment by thuandt** [comment]
Still present on 35.2.0

**Comment by der-ali** [comment]
Still Present

**Comment by ki0** [comment]
Still present on 36.6.2

**Comment by joekrill** [comment]
For anyone still seeing this issue - I was seeing this because I had disabled basic auth. It was preventing my datasources from being updated correctly. I was able to "workaround" it by re-enabling basic auth in `grafana.ini`:

```yaml
grafana:
   grafana.ini:
     auth.basic:
      enabled: true
```

**Comment by edalford11** [comment]
Hours of work finally resolved. Thank you @joekrill

**Comment by elbandi** [comment]
> For anyone still seeing this issue - I was seeing this because I had disabled basic auth. It was preventing my datasources from being updated correctly. I was able to "workaround" it by re-enabling basic auth in `grafana.ini`:
> 
> grafana:
>    grafana.ini:
>      auth.basic:
>       enabled: true

not working :(

```
  grafana.ini:
    server:
      root_url: "https://%(domain)s/"
    auth.basic:
      enabled: true
    auth.generic_oauth:
      enabled: true
      name: Authentik
      client_id: grafana
      client_secret: xxxx
      auth_url: https://authentik.xxx/application/o/authorize/
      token_url: https://authentik.xxx/application/o/token/
      api_url: https://authentik.xx/application/o/userinfo/
      scopes: "openid profile email offline_access"
      allow_sign_up: true
      auto_login: true
      use_refresh_token: true
      role_attribute_path: "contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'"
  sidecar:
    datasources:
      alertmanager:
        enabled: false
```

Sidecar log:

     {"time": "2026-04-18T11:47:43.631924+00:00", "level": "INFO", "msg": "None sent to http://localhost:3000/api/admin/provisioning/datasources/reload. Response: 401 Unauthorized {\"extra\":null,\"message\":\"Unauthorized\",\"messageId\":\"auth.unauthorized\",\"statusCode\":401,\"traceID\":\"\"}\n"}
