### ISSUE TITLE
[kube-prometheus-stack] cAdvisor scrape errors should be reported as alerts

### ISSUE THREAD

**Issue by ErmakovDmitriy** [prometheus-community/helm-charts#1807]
### Is your feature request related to a problem ?

Hello team!
Thank you for your work and product!

I would like to offer an idea for cAdvisor alert rules which might help to catch cAdvisor scrape errors.

Kubelet publishes cAdvisor metrics under https://{{kubelet-ip}}:10250/metrics/cadvisor. These metrics are important for monitoring.
Unfortunately, there are reported issues that sometimes cAdvisor has problems with its cache and can not scrape metrics.
In this case the returned metrics have:

```
# HELP container_scrape_error 1 if there was an error while getting container metrics, 0 otherwise
# TYPE container_scrape_error gauge
container_scrape_error 1

# HELP machine_scrape_error 1 if there was an error while getting machine metrics, 0 otherwise.
# TYPE machine_scrape_error gauge
machine_scrape_error 0
```
and if there are machine metrics scrape error, then the metrics could have `machine_scrape_error == 1`.

I discovered that one of our Kubernetes nodes had this issue by accident: I had to check other metrics and saw that they were not available.
The workaround for cAdvisor is:

1. Discover the problematic Pod
2. Delete it.

P.S. You can take a look at the "additional context" section for an URL to a bug which has samples of kubelet's logs related to the metrics scrape issue of cAdvisor.

### Describe the solution you'd like.

It might be good, if the default rules of kube-prometheus-stack have the `container_scrape_error` and `machine_scrape_error` errors as critical alerts because these errors block other metrics.

Below are my alert rules which I added to one of our clusters:

```yaml
  - alert: ContainerScrapeError
    annotations:
      description: >-
        Kubelet cAdvisor on node {{ $labels.node }} has problems
        scraping container metrics. Take a look at
        https://elogy.maxiv.lu.se/logbooks/534/entries/26530/
      summary: cAdvisor container metrics scrape error
    expr: container_scrape_error == 1
    for: 10m
    labels:
      severity: critical
  - alert: MachineScrapeError
    annotations:
      description: >-
        Kubelet cAdvisor on node {{ $labels.node }} has problems
        scraping machine metrics.
      summary: cAdvisor machine metrics scrape error
    expr: machine_scrape_error == 1
    for: 10m
    labels:
      severity: critical
```

### Describe alternatives you've considered.

NONE

### Additional context.

Here are some links to issues related to cAdvisor:

https://github.com/google/cadvisor/pull/2868
https://bugzilla.redhat.com/show_bug.cgi?id=1950993 (this bug also contains samples of logs which can help to find the Pod which causes metrics scrape error - the workaround)
https://github.com/google/cadvisor/pull/3013
