### ISSUE TITLE
[kube-prometheus-stack] Thanos metrics exposed externally

### ISSUE THREAD

**Issue by DaveOHenry** [prometheus-community/helm-charts#1859]
### Describe the bug a clear and concise description of what the bug is.

I would like to expose the Thanos grpc port externally, but not the http port. Is this somehow possible? It looks like this is currently not supported:

https://github.com/prometheus-community/helm-charts/blob/ed35464b840173a39bb1be170bd85211170a8290/charts/kube-prometheus-stack/templates/prometheus/serviceThanosSidecarExternal.yaml#L30-L42

https://github.com/prometheus-community/helm-charts/blob/ed35464b840173a39bb1be170bd85211170a8290/charts/kube-prometheus-stack/values.yaml#L1814-L1842

Looks like the http port is always exposed and there is no way to override this behavior. 
I thought about adding another parameter to enable / disable the exposed ports individually, but maybe there is a better way.

### What's your helm version?

version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"a5e4de7e277a707bd28d448bd75de58b4f1cdc22", GitTreeState:"clean", BuildDate:"2021-11-16T01:09:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

33.2.0

### What happened?

```
# Source: kube-prometheus-stack/templates/prometheus/serviceThanosSidecarExternal.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-kube-promethe-thanos-external
  namespace: monitoring
  labels:

    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "33.2.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-33.2.0
    release: "RELEASE-NAME"
    heritage: "Helm"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 10902
    targetPort: http
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: RELEASE-NAME-kube-promethe-prometheus
---
```

### What you expected to happen?

```
# Source: kube-prometheus-stack/templates/prometheus/serviceThanosSidecarExternal.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-kube-promethe-thanos-external
  namespace: monitoring
  labels:

    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "33.2.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-33.2.0
    release: "RELEASE-NAME"
    heritage: "Helm"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: RELEASE-NAME-kube-promethe-prometheus
---
```

### How to reproduce it?

`helm template --set prometheus.thanosServiceExternal.enabled=true .`

### Enter the changed values of values.yaml?

prometheus.thanosServiceExternal.enabled: true

### Enter the command that you execute and failing/misfunctioning.

helm template --set prometheus.thanosServiceExternal.enabled=true .
