### ISSUE TITLE
[kube-prometheus-stack] [Help] Persistant Storage

### ISSUE THREAD

**Issue by kaykhancheckpoint** [prometheus-community/helm-charts#186]
Hi, I want it to be able to persist the data. 

I've modified the values file to include details about the storage. I have an existing storage class called gp2.

**values.yml**
```
    ## Prometheus StorageSpec for persistent data
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/storage.md
    ##
    storageSpec: {}
    volumeClaimTemplate:
      spec:
        storageClassName: gp2
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
      selector: {}
```
```
helm install monitoring -f values.yml prometheus-community/kube-prometheus-stack
```

However when i install using this configuration, there is no PVC automatically created. 

**storage class**

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
  selfLink: /apis/storage.k8s.io/v1/storageclasses/gp2
  uid: eab77778-b9cb-11e8-80c5-02f2d46d21aa
  resourceVersion: '35164321'
  creationTimestamp: '2018-09-16T16:16:50Z'
  labels:
    k8s-addon: storage-aws.addons.k8s.io
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"},"labels":{"k8s-addon":"storage-aws.addons.k8s.io"},"name":"gp2"},"parameters":{"type":"gp2"},"provisioner":"kubernetes.io/aws-ebs"}
    storageclass.beta.kubernetes.io/is-default-class: 'true'
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

With other helm charts such as mongodb the PVC was automatically created. Have i forgot to configure something here?

**Comment by Spritekin** [comment]
I had a similar problem... in my case I looked at the list of PVs and PVCs and found older PV created by the stack that was unbound. I deleted the PV and rerun the chart and all was ok.

Not sure why it happened.

**Comment by bentatham** [comment]
I had the same problem (plus, in addition, my endpoint for kube-prometheus-stack-prometheus didn't get assigned properly, so grafana couldn't talk to prometheus).

I rolled back to kube-prometheus-stack 9.4.8 with prometheusOperator.image.tag v0.38.1 (from v0.42.1) and both problems are now fixed.  I'm not sure if it is a bug in the updated helm chart or prometheus-operator itself, and I haven't had a chance to dig in to root causes.

**Comment by scottrigby** [comment]
Related to https://github.com/prometheus-community/helm-charts/pull/119

**Comment by fktkrt** [comment]
@kaykhancheckpoint If you're using those exact values you've mentioned in the opening post, that might be problematic.

In your sample, I can see:
```
    storageSpec: {}
    volumeClaimTemplate:
      spec:
        storageClassName: gp2
...
```

The problem here is that the `volumeClaimTemplate` should be part of the `storageSpec`, and your disabling that with adding `{}`, hence no PVC.

You can see the proper config at the `values.yaml`:

```
    ## Prometheus StorageSpec for persistent data
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/storage.md
    ##
    storageSpec: {}
    #  volumeClaimTemplate:
    #    spec:
...
```

Please let us know if that helped or not.

**Comment by kaykhancheckpoint** [comment]
@fktkrt yep that was the problem, i fixed it a lot time ago.

**Comment by sreenivas-ps** [comment]
@fktkrt : I'm deploying kube-prometheus-stack on gke cluster and would like to persist the prometheus data but it is not automatically creating the pvc. As a side note, it was able to create a pvc for grafana.

Here is what I've used: I've added this to values-ps.yaml

```
grafana:
  persistence:
    enabled: true
  service:
    type: "LoadBalancer"

prometheus:
  service:
    type: "LoadBalancer"
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: ""
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
      selector: {}
```
// helm3 command: 
helm install -n monitoring -f charts/kube-prometheus-stack/values.yaml -f charts/kube-prometheus-stack/values-ps.yaml monitor charts/kube-prometheus-stack.

i can see the following on my gke cluster:

k get sc
```
NAME                                             PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
storageclass.storage.k8s.io/premium-rwo          pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true                   40d
storageclass.storage.k8s.io/standard (default)   kubernetes.io/gce-pd    Delete          Immediate              true                   40d
storageclass.storage.k8s.io/standard-rwo         pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true                   40d
```

k get pv
```
NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                        STORAGECLASS   REASON   AGE
persistentvolume/pvc-9b6f481a-eebc-4df9-a63f-c1799f796b99   10Gi       RWO            Delete           Bound    monitoring/monitor-grafana   standard                172m
```

am i missing anything?

**Comment by sreenivas-ps** [comment]
i found the issue that the `storageSpec` should be with `prometheus.prometheusSpec`

the correct spec is:

```
grafana:
  persistence:
    enabled: true
  service:
    type: "LoadBalancer"

prometheus:
  service:
    type: "LoadBalancer"
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
```
