### ISSUE TITLE
[prometheus-kube-stack] Cannot use manual PVCs

### ISSUE THREAD

**Issue by ahgraber** [prometheus-community/helm-charts#1866]
### Describe the bug a clear and concise description of what the bug is.

Helm chart does not seem to respect (a) providing a custom/manual PVC or (b) treating `storageSpec` as a legitimate embeddedPersistentVolumeClaim

Related:
- https://github.com/prometheus-community/helm-charts/issues/1209
- https://github.com/prometheus-community/helm-charts/issues/1164
- https://github.com/prometheus-community/helm-charts/issues/957

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/arm64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

33.2.0

### What happened?

I have created manual PVCs for alertmanager and prometheus (because the [long default names](https://github.com/prometheus-community/helm-charts/pull/1752) cause errors in my storageclass).

When I specify the manual PVCs in the helm values `volumeClaimTemplate`, the chart creates PVCs with default name anyway.

Furthermore, if I try to treat `volumeClaimTemplate` as an actual template ([per the docs](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#storagespec)), no PVC is created at all

I _have_ disabled my default storage class.

### What you expected to happen?

I expect the chart to use the specified manually-create PVCs, or to respect the volumeClaimTemplate and overwrite the defaults

### How to reproduce it?

Create custom PVCs and specify them as `volumeClaimTemplate.spec.volumeName` in helm values

### Enter the changed values of values.yaml?

```yaml
prometheus:
  ingress:
    enabled: false
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            volumeName: prometheus-data  # name of my custom PVC

alertmanager:
  ingress:
    enabled: false
  alertmanagerSpec:
    retention: 120h
    storage:
      volumeClaimTemplate:
        spec:
          volumeName: alertmanager-data  # name of my custom PVC
```

or 

```yaml
prometheus:
  ingress:
    enabled: false
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-data
        spec:
          storageClassName: csi-truenas-iscsi
            resources:
              requests:
                  storage: 10Gi

alertmanager:
  ingress:
    enabled: false
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        metadata:
          name: alertmanager-data
        spec:
          storageClassName: csi-truenas-iscsi
            resources:
              requests:
                  storage: 1Gi
```

### Enter the command that you execute and failing/misfunctioning.

`helm install prom-stack prometheus-community/prometheus-kube-stack --version 33.2.0 --values values.yaml` is close enough.  
I use `fluxcd` which deploys based on matching the values.yaml in my repo

**Comment by weyderfs** [comment]
Here I'm a similar issue, There's deployed a Prometheus with 300Gi and now I have been trying expand to 500Gi and the Operator ignores the config on the `values.yaml`

**Comment by ahgraber** [comment]
After attempting some investigation, it appears that [`storageSpec` maps to a `storage` heading in the template](https://github.com/prometheus-community/helm-charts/blob/46c3cfaa6b845f25f9d182ff8bce591c2fb89566/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L210), but I'm not knowledgeable enough to trace this further to figure out what I'm doing wrong or why the existing PVC isn't respected.

**Comment by ahgraber** [comment]
More debugging attempts --

While attempting to follow [docs](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md):

Assuming a PVC:

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-truenas-iscsi
  resources:
    requests:
      storage: 3Gi
```

if I do (without the storageClassName) like the example:

```yaml
        storageSpec:
          volumeClaimTemplate:
            spec:
              # storageClassName: 
              resources:
                requests:
                  storage: 3Gi
              selector:
                matchLabels:
                  app.kubernetes.io/name: prometheus
```

The chart creates a new PVC instead of respecting the selector and the PVC errors because no storageClass is set

-------------------

if I specify a storageClassName

```yaml
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: csi-truenas-iscsi
              resources:
                requests:
                  storage: 3Gi
              selector:
                matchLabels:
                  app.kubernetes.io/name: prometheus
```

it does not respect the existing PVC and a new PVC provides error:

```txt
failed to provision volume with StorageClass "csi-truenas-iscsi": claim.Spec.Selector is not supported
```

-------------------

If I do (with a "-" storageClassName):

```yaml
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "-"
              resources:
                requests:
                  storage: 3Gi
              selector:
                matchLabels:
                  app.kubernetes.io/name: prometheus
```

I get error:

```txt
create Claim prometheus-prometheus-prometheus-db-prometheus-prometheus-prometheus-0 for Pod prometheus-prometheus-prometheus-0 in StatefulSet prometheus-prometheus-prometheus failed error: PersistentVolumeClaim "prometheus-prometheus-prometheus-db-prometheus-prometheus-prometheus-0" is invalid: spec.storageClassName: Invalid value: "-": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Comment by shaoye** [comment]
any temporary solutions? do we have to nuke everything then redeploy prometheus for a PVC size bump?

**Comment by rayui** [comment]
@ahgraber If you still need it, I've got it working. The trick was realising that I needed to use 'local-path' as the storageClassName value instead of 'manual'. With 'manual', prometheus wouldn't even provision for me on k3s. As follows...

`
...
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-volume
  labels:
    app.kubernetes.io/name: prometheus-storage
    type: local
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - giles
  hostPath:
    path: "/var/lib/rancher/prometheus-pv"
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prom-stack
  namespace: prom-stack
spec:
        ...
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "local-path"
              volumeName: "prometheus-pv-volume"
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 10Gi
              selector:
                matchLabels:
                  app.kubernetes.io/name: "prometheus-storage"`

**Comment by ahgraber** [comment]
@rayui Thanks for following up; I got it working with `rook-ceph` and have stopped trying to arrange a manually-specified PVC.

Regardless, I think your issue is slightly different; AFAIK there is no storageClassName of `manual` unless you have created such a storage class, while `local-path` should be automatically provisioned with a `k3s` setup.

**Comment by isc30** [comment]
Sharing my working `values.yaml`:

```
alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-2-replica
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
prometheus:
  enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-2-replica
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 12Gi
grafana:
  enabled: true
  defaultDashboardsInterval: 5s
  adminUser: admin
  adminPassword: 1234
  persistence:
    enabled: true
    storageClassName: longhorn-2-replica
    accessModes: ["ReadWriteOnce"]
    size: 4Gi
```
