### ISSUE TITLE
[prometheus-kube-stack] Install/Upgrade failing on EKS

### ISSUE THREAD

**Issue by repl-mike-roest** [prometheus-community/helm-charts#1899]
### Describe the bug a clear and concise description of what the bug is.

When I attempt to do a `helm install` or `helm upgrade --install` on EKS I get a pre-install failure
```
Error: failed pre-install: Delete "https://5818F5CF181BD28D0D5A73C71C46850D.gr7.us-west-2.eks.amazonaws.com/apis/rbac.authorization.k8s.io/v1/clusterroles/prometheus-kube-prometheus-admission": dial tcp: lookup 5818F5CF181BD28D0D5A73C71C46850D.gr7.us-west-2.eks.amazonaws.com: no such host
```
Note: 
 I have done this a bunch of times on this eks cluster but have been cleaning things up with
```
helm -n monitoring uninstall prometheus
kubectl delete crd alertmanagerconfigs.monitoring.coreos.com
kubectl delete crd alertmanagers.monitoring.coreos.com
kubectl delete crd podmonitors.monitoring.coreos.com
kubectl delete crd probes.monitoring.coreos.com
kubectl delete crd prometheuses.monitoring.coreos.com
kubectl delete crd prometheusrules.monitoring.coreos.com
kubectl delete crd servicemonitors.monitoring.coreos.com
kubectl delete crd thanosrulers.monitoring.coreos.com
kubectl delete namespace monitoring
kubectl delete clusterrolebindings prometheus-kube-prometheus-admission
kubectl delete clusterroles prometheus-kube-prometheus-admission
```

If I add the following to my values.yaml
```
prometheusOperator:
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false
```
The initial install will pass and prometheus/alertmanager/grafana will come up and communicate nicely.

If I then change a value in the values.yml (example changing the prometheus retention) or indeed even change nothing in the values.yml

And run

```
helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
  -n monitoring \
  --create-namespace \
  -f values.yml \
  --version 34.1.1
```

I get the following error
```
Error: UPGRADE FAILED: unable to build kubernetes objects from new release manifest: unable to recognize "": Get "https://5818F5CF181BD28D0D5A73C71C46850D.gr7.us-west-2.eks.amazonaws.com/api?timeout=32s": dial tcp: lookup 5818F5CF181BD28D0D5A73C71C46850D.gr7.us-west-2.eks.amazonaws.com: no such host
```

This hostname is the Cluster API endpoint of my cluster and is resolvable from my machine
```
;; ANSWER SECTION:
5818F5CF181BD28D0D5A73C71C46850D.gr7.us-west-2.eks.amazonaws.com. 24 IN	A 10.30.25.237
5818F5CF181BD28D0D5A73C71C46850D.gr7.us-west-2.eks.amazonaws.com. 24 IN	A 10.30.22.78
```
And accessible
```
❯ curl -k https://5818F5CF181BD28D0D5A73C71C46850D.gr7.us-west-2.eks.amazonaws.com
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {

  },
  "code": 403
}%
```

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1

### Which chart?

prometheus-kube-stack

### What's the chart version?

34.1.1

### What happened?

Install failed with Admission webhooks enabled
```
Error: failed pre-install: Delete "https://5818F5CF181BD28D0D5A73C71C46850D.gr7.us-west-2.eks.amazonaws.com/apis/rbac.authorization.k8s.io/v1/clusterroles/prometheus-kube-prometheus-admission": dial tcp: lookup 5818F5CF181BD28D0D5A73C71C46850D.gr7.us-west-2.eks.amazonaws.com: no such host
```
& 
Upgrade fails when Admission webhooks are disabled
```
Error: UPGRADE FAILED: unable to build kubernetes objects from new release manifest: unable to recognize "": Get "https://5818F5CF181BD28D0D5A73C71C46850D.gr7.us-west-2.eks.amazonaws.com/api?timeout=32s": dial tcp: lookup 5818F5CF181BD28D0D5A73C71C46850D.gr7.us-west-2.eks.amazonaws.com: no such host
```

### What you expected to happen?

The install or upgrade to succeed

### Enter the changed values of values.yaml?
```
prometheus:
  prometheusSpec:
    retention: 180d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: efs-sc
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 50Gi # efs-csi driver doesn't actually limit the size of the volume
# This section needs to be here for initial install to succeed
prometheusOperator:
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false
# End section
kubeProxy: # in EKS the kube-proxy metrics are not available https://github.com/aws/containers-roadmap/issues/657
  enabled: false
kubeControllerManager:
  enabled: false # EKS this is not available https://github.com/aws/containers-roadmap/issues/1298
kubeScheduler:
  enabled: false # EKS this is not available https://github.com/aws/containers-roadmap/issues/1298
```

### Enter the command that you execute and failing/misfunctioning.

```
helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
  -n monitoring \
  --create-namespace \
  -f values.yml \
  --version 34.1.1
```
or
```
helm install prometheus prometheus-community/kube-prometheus-stack \
  -n monitoring \
  --create-namespace \
  -f values.yml \
  --version 34.1.1
```

### Anything else we need to know?

EKS cluster was built using https://github.com/terraform-aws-modules/terraform-aws-eks
