### ISSUE TITLE
[kube-prometheus-stack] unknown field "secretProviderClass" in com.coreos.monitoring.v1.Prometheus.spec.thanos`

### ISSUE THREAD

**Issue by achede22** [prometheus-community/helm-charts#1900]
### Describe the bug a clear and concise description of what the bug is.

Try to connect with GCP by uncommenting secretProviderClass values

You will find an error
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Prometheus.spec.thanos): unknown field "secretProviderClass" in com.coreos.monitoring.v1.Prometheus.spec.thanos`



### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"archive", BuildDate:"2021-07-22T00:00:00Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6-gke.300", GitCommit:"df413ee6225aa3fc539e18ca3464a48d723bd3ea", GitTreeState:"clean", BuildDate:"2022-01-24T09:29:08Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

[kube-prometheus-stack]

### What's the chart version?

kube-prometheus-stack-34.1.1	0.55.0

### What happened?

helm install failed

### What you expected to happen?

helm install to deploy and connect GCP objectstore.yaml file

### How to reproduce it?

# FOUND
```
thanos: {}
      # secretProviderClass:
      #   provider: gcp
      #   parameters:
      #     secrets:
      #       - resourceName: "projects/$PROJECT_ID/secrets/testsecret/versions/latest"
      #         fileName: "objstore.yaml"
      # objectStorageConfigFile: /var/secrets/object-store.yaml
```

#Uncommented
```
    thanos:
      secretProviderClass:
        provider: gcp
        parameters:
          secrets:
            - resourceName: "projects/$PROJECT_ID/secrets/testsecret/versions/latest"
              fileName: "objstore.yaml"
      objectStorageConfigFile: /var/secrets/object-store.yaml
```

You will find an error
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Prometheus.spec.thanos): unknown field "secretProviderClass" in com.coreos.monitoring.v1.Prometheus.spec.thanos`

Already tried
- Create a new GKE cluster with Workload Identity or enable Workload Identity on an existing cluster. # WAS DISABLED # https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#console 

    - Install the Secret Store CSI Driver v1.0.1 or higher to the cluster. # https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation.html
    
    - Install the Google plugin DaemonSet & additional RoleBindings: # https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp 
                                                                      # kubectl apply -f deploy/provider-gcp-plugin.yaml
                                                                      
                                                                      
                                                                      
                                                                      also already tried uninstalling
                                                                      
helm uninstall telemetry
kubectl delete crd alertmanagerconfigs.monitoring.coreos.com
kubectl delete crd alertmanagers.monitoring.coreos.com
kubectl delete crd podmonitors.monitoring.coreos.com
kubectl delete crd probes.monitoring.coreos.com
kubectl delete crd prometheuses.monitoring.coreos.com
kubectl delete crd prometheusrules.monitoring.coreos.com
kubectl delete crd servicemonitors.monitoring.coreos.com
kubectl delete crd thanosrulers.monitoring.coreos.com
                                                                      
                                                                      

### Enter the changed values of values.yaml?

#Uncommented
```
    thanos:
      secretProviderClass:
        provider: gcp
        parameters:
          secrets:
            - resourceName: "projects/$PROJECT_ID/secrets/testsecret/versions/latest"
              fileName: "objstore.yaml"
      objectStorageConfigFile: /var/secrets/object-store.yaml
```

### Enter the command that you execute and failing/misfunctioning.

helm install telemetry prometheus-community/kube-prometheus-stack -f cision-gcp-sandbox-values.yaml -n telemetry --debug


### Anything else we need to know?

I spend the whole day looking for the Thanos sidecar container, I just can't find it.
