### ISSUE TITLE
prometheus kube-state-metrics sub-chart configurable values

### ISSUE THREAD

**Issue by omriarieli** [prometheus-community/helm-charts#1901]
### Describe the bug a clear and concise description of what the bug is.

Adding kube-state-metrics sub-chart configurable values to [prometheus values file](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L457-L465) does not add them

### What's your helm version?

version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10-gke.400", GitCommit:"c9335031652c356836fcfcee33c0e7a0ae48a4d8", GitTreeState:"clean", BuildDate:"2022-02-23T09:29:31Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-community/prometheus

### What's the chart version?

15.3.0

### What happened?

Trying to add labels and metricLabelsAllowlist to the kube-state-metrics sub-chart they do not get picked up or applied to the kube-state-metrics

### What you expected to happen?

expected the metrics from kube-state-metrics to come into prometheus with the added label.
our goal is to then include the added labels in alerts from alertmanager. e.g cluster, environment, team

### How to reproduce it?

add labels as described in "Enter the changed values of values.yaml" and helm upgrade after that you do not see the labels you added to kube-state-metrics in prometheus

### Enter the changed values of values.yaml?

`kubeStateMetrics:
  ## If false, kube-state-metrics sub-chart will not be installed
  ##
  enabled: true

##
  kube-state-metrics:
    metricLabelsAllowlist:
      - env=[*]
    customLabels:
      env: dev`

### Enter the command that you execute and failing/misfunctioning.

`helm upgrade --install --timeout 600s --namespace monitoring -f values.yaml prometheus-community/prometheus`

**Comment by zeritti** [comment]
The value `metricLabelsAllowlist` expects a list of Kubernetes resources each with a list of labels one wishes to allow for the given resource, e.g. allow all labels with deployments, pods and namespaces:
```
kube-state-metrics:
  metricLabelsAllowlist:
    - deployments=[*]
    - pods=[*]
    - namespaces=[*]
 ```

**Comment by zeritti** [comment]
`customLabels` is being used to set labels on the kube-state-metrics resources themselves, e.g. on deployment. They do not get added to time series coming out of KSM as far as I see.

**Comment by zeritti** [comment]
If I may suggest. To add new labels to the time series coming from KSM, you may wish to turn to `kube-state-metrics.prometheus.monitor.relabelings`. For instance, adding a label of key/value pair `env: dev` might look like this:
```
kube-state-metrics:
  prometheus:
    monitor:
      relabelings:
      - sourceLabels: [__address__]
        targetLabel: env
        replacement: dev
  ```
Similar works with `kube-prometheus-stack` where the KMS chart is also a subchart.

**Comment by storm1kk** [comment]
Hi all! I can confirm the issue. I have the same problem as @omriarieli  described. Values for the kube-state-metrics subchart are ignored. 
Here is a piece of my values.yaml:

`prometheus:
  server:
    resources:
      limits:
        cpu: 1
        memory: 16G
      requests:
        cpu: 250m
        memory: 512Mi  
    readinessProbeInitialDelay: 240
    livenessProbeInitialDelay: 120
    global:
      scrape_interval: 1m
      scrape_timeout: 10s
      evaluation_interval: 1m
    retention: "3d"
    persistentVolume:
      size: 64Gi
  kubeStateMetrics:
    enabled: true
    kube-state-metrics:
      metricLabelsAllowlist: pods=[component]`

And here is a piece from example:

`kubeStateMetrics:
  ## If false, kube-state-metrics sub-chart will not be installed
  ##
  enabled: true

## kube-state-metrics sub-chart configurable values
## Please see https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics
##
# kube-state-metrics:`

Should be working but :(

**Comment by bklar84** [comment]
@omriarieli @storm1kk 
I ran into this problem today and noticed that metricLabelsAllowlist being an array did not quite match what the template is attempting to do. Supply them as comma separated values as such:

```
metricLabelsAllowlist: pods=[label1,label2,label3],nodes=[nodeLabel1,nodeLabel2]
```

**Comment by Rohlik** [comment]
@bklar84 I hit on the same problem. Thank you for the workaround. Can you please make a fix? 🙏🏽

**Comment by melghors** [comment]
@bklar84 Hello! Could you provide more info? I checked this feature on helm chart:
`prometheus/kube-state-metrics        	5.16.0       	2.10.1`
and id doesn't work

**Comment by nice-pink** [comment]
Same for:
`prometheus-community/kube-state-metrics                 5.19.0          2.12.0`

The labels are not added to the metrics. 

From values.yaml
```
metricLabelsAllowlist:
- deployments=[subsystem]
- statefulsets=[subsystem]
- pods=[subsystem]
```

The args are passed to the pod:
```
        containers:
        - args:
            - '--port=8080'
            - >-
              --resources=deployments,nodes,poddisruptionbudgets,pods,statefulsets
            - >-
              --metric-labels-allowlist=deployments=[subsystem],statefulsets=[subsystem],pods=[subsystem]
            - >-
              --metric-allowlist=^kube_(node|deployment|statefulset|poddisruptionbudget|pod|pod_container)_status_.*$|^kube_pod_(info|labels|container_(info|resource_)).*$,^kube_node_spec_.*
          image: 'registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.12.0'
```
