### ISSUE TITLE
[prometheus-kube-stack] kube-state-metrics ServiceMonitor has lost app label

### ISSUE THREAD

**Issue by tringuyen-yw** [prometheus-community/helm-charts#1905]
### Describe the bug a clear and concise description of what the bug is.

The ServiceMonitor `${helm-releasename}-kube-state-metrics` created by the `kube-prometheus-stack` helm chart no longer has a label named `app`.

- Before (version 20.0.1 or maybe even until 29.x?): the `app` label was `app=kube-prometheus-stack-kube-state-metrics`
- Now (version 34.1.1): the label becomes `app.kubernetes.io/name=kube-state-metrics`

However, all other ServiceMonitors still have the "app" label with the key = `app`. eg

- `app=kube-prometheus-stack-alertmanager`
- `app=kube-prometheus-stack-apiserver`
- `app=kube-prometheus-stack-grafana`
- `app=kube-prometheus-stack-prometheus`
- etc...

### What's your helm version?

version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13", GitCommit:"4d46ddba34543ef2253f4f0b33ccad59e997efa4", GitTreeState:"clean", BuildDate:"2022-02-10T03:18:31Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

34.1.1

### What happened?

I configure my custom helm value so that Prometheus would emlist the built-in Service monitors `kube-prometheus-stack-???` as well as a few custom ServiceMonitors which have labels `app=myown-svcmonitor1` and `app=myown-svcmonitor2` of my own. Example:

```yaml
prometheus
  prometheusSpec
    serviceMonitorSelector:
      matchExpressions:
      - key: "app"
        operator: In
        values:
          - myown-svcmonitor1
          - myown-svcmonitor2
          - kube-prometheus-stack-alertmanager
          - kube-prometheus-stack-apiserver
          - kube-prometheus-stack-coredns
          - kube-prometheus-stack-grafana
          - kube-prometheus-stack-kube-state-metrics
          - etc...
```

As the label key `app` is common to all ServiceMonitors, Prometheus could discover all the underlying service. EXCEPT for `kube-state-metrics` ServiceMonitor which now has the label  `app.kubernetes.io/name=kube-state-metrics`. The label key `app.kubernetes.io/name` is no longer `app. As a result `kube-state-metrics` services are no longer discovered by Prometheus.

## PROPOSED SOLUTION

Make the "app" labels of all ServiceMonitors generated by `kube-prometheus-stack` to have the same key `app` or `app.kubernetes.io/name`. But do not mix.

### Enter the command that you execute and failing/misfunctioning.

Our `kube-prometheus-stack` helm chart was applied by a Terraform code. Which is equivalent to:

```shell
helm upgrade mykubepromstack prometheus-community/kube-prometheus-stack -n monitoring \
  --version 34.1.1 \
  --reuse-values \
  -f ./helm-values/custom_kube-prometheus-stack.yaml
```

Terraform configuration:

```hcl
resource "helm_release" "prometheus-stack" {
  name       = "mykubepromstack"
  repository = "https://prometheus-community.github.io/helm-charts"
  chart      = "kube-prometheus-stack"
  version    = "34.1.1"
  namespace  = "monitoring"

  values = [
    file("${path.module}/helm-values/custom_kube-prometheus-stack.yaml")
  ]
```

### Anything else we need to know?

The `kube-prometheus-stack` helm chart was successfully upgrade. Everything works OK. The only problem is the loss of all metrics from `kube-state-metrics`. The reason is explained in section "What happened?"
