### ISSUE TITLE
[prometheus-kube-stack] alertmanager config change ignored

### ISSUE THREAD

**Issue by tringuyen-yw** [prometheus-community/helm-charts#1926]
### Describe the bug a clear and concise description of what the bug is.

Update the custom helm values related to alertManager. In my case I deleted one route and one receiver.
Helm upgrade was successful. The AlertManager pod was recreated but still has the old configuration (checked in AlertManager UI, Status tab) 

### What's your helm version?

```
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

### What's your kubectl version?

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13", GitCommit:"4d46ddba34543ef2253f4f0b33ccad59e997efa4", GitTreeState:"clean", BuildDate:"2022-02-10T03:18:31Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Which chart?

`kube-prometheus-stack`

### What's the chart version?

34.1.1

### What happened?

- The secret `alertmanager-mykubepromstack-alertmanager` was correctly updated (the `alertmanager.yaml` key contain the updated config)

- The secret  `alertmanager-mykubepromstack-alertmanager-generated` still has the old config

The AlertManager pod was recreated but with the old config. Which I suppose is taken from the `alertmanager-mykubepromstack-alertmanager-generated` secret which is NOT updated.

### What you expected to happen?

The AlertManager pod must be recreated with the updated alertmanager config.

### How to reproduce it?

Make some changes related to alertmanager:

- rename something, `my-renamed-email-notifier` receiver in the example below
- add something, `bogus-webhook` receiver in this example

For example add the snippet below in your `mycustom-kubepromstack-values.yaml`

```yaml
alertmanager:
  config:
    receivers:
      - name: my-renamed-email-notifier
        email_configs:
          - to: user1@bogus.net    
      - name: bogus-webhook
        webhook_configs:
          - url: https://nowhere.net/bogus/webhook
            send_resolved: false
```

### Enter the command that you execute and failing/misfunctioning.

```shell
helm upgrade mykubepromstack prometheus-community/kube-prometheus-stack -n monitoring \
  --version 34.1.1 \
  --reuse-values \
  -f mycustom-kubepromstack-values.yaml
```
