### ISSUE TITLE
[prometheus] Cant setup HA alertmanager

### ISSUE THREAD

**Issue by local-master** [prometheus-community/helm-charts#193]
**Describe the bug**
When setting up alertmanager with values.tyaml I am unable to deploy HA Alertmanager with 3 replicas. First of all I am unable to setup cluster.listen-address through extraArgs. When I add the value it deploys alertmanager with cluster.listen-address entry duplicated in statefull set and the pod crashes due to duplicate values. 

```
alertmanager: error: flag 'cluster.listen-address' cannot be repeated, try --help
```

Next problem that I face is that I can't setup multiple entries for "cluster.peer" I am adding each peer by following entry in values.yaml

```
extraArgs:
    cluster.listen-address: $(POD_IP):9094
    cluster.peer: prometheus-alertmanager-0.prometheus-alertmanager-headless:9094
    cluster.peer: prometheus-alertmanager-1.prometheus-alertmanager-headless:9094
    cluster.peer: prometheus-alertmanager-2.prometheus-alertmanager-headless:9094
```

Only one value is added to the pod not 3. 

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: prometheus
**Which version of the chart**: prometheus-11.16.2

**What happened**:

Pod crash when setting up "cluster.listen-address"
Cant add multiple values for "cluster.peer"

**What you expected to happen**:
Deploy HA alertmanager with gosip to not dupcliate alerts and synchronize silences for alerts

**How to reproduce it** (as minimally and precisely as possible):

<~--
values.yaml for the alertmanager 

```
alertmanager:
  persistentVolume:
    storageClass: "managed-premium-zoned"
  replicaCount: 3
  statefulSet:
    enabled: true
    enableMeshPeer: true
    headless:
      servicePort: 9094
      ## Enable gRPC port on service to allow auto discovery with thanos-querier
      gRPC:
        enabled: true
        servicePort: 10901
  service:
    enableMeshPeer: true
    servicePort: 9094
  resources: 
    limits:
      cpu: 300m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 32Mi
  baseURL: http://my-url
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - my-url
  extraArgs:
    cluster.listen-address: $(POD_IP):9094
    cluster.peer: prometheus-alertmanager-0.prometheus-alertmanager-headless:9094
    cluster.peer: prometheus-alertmanager-1.prometheus-alertmanager-headless:9094
    cluster.peer: prometheus-alertmanager-2.prometheus-alertmanager-headless:9094
```

```
helm install prometheus prometheus-community/promethes  --values values.yaml
```

-->
