### ISSUE TITLE
[prometheus-blackbox-exporter] ServiceMonitor for blackbox /metrics endpoint

### ISSUE THREAD

**Issue by OneCricketeer** [prometheus-community/helm-charts#1936]
### Is your feature request related to a problem ?

It is not possible to use `serviceMonitor.enabled` + targets (for example, a target "loopback" to the exporter) to scrape the blackbox-exporter's `/metrics` endpoint itself; [the paths are all hard-coded as `/probe`.](https://github.com/prometheus-community/helm-charts/blob/prometheus-blackbox-exporter-5.5.1/charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml#L24)

### Describe the solution you'd like.

By default, with no "external" targets, there should be a ServiceMonitor for the blackbox-exporter Service itself, scraping `/metrics`. 

e.g.

```yml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-blackbox-exporter-monitor
  namespace: 'default' # example
  labels: {}
spec:
  endpoints:
  - path: /metrics
    interval: 30s
    port: http
    scheme: http
  namespaceSelector:
    matchNames:
      - 'default'  # example
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-blackbox-exporter
      app.kubernetes.io/name: prometheus-blackbox-exporter
```

### Describe alternatives you've considered.

Write my own ServiceMonitor (above)
