### ISSUE TITLE
[prometheus-kube-stack] opsgenie_configs update_alerts does not work

### ISSUE THREAD

**Issue by mariusandersen** [prometheus-community/helm-charts#1947]
### Describe the bug a clear and concise description of what the bug is.

If you add the following

```
alertmanager:
  config:
    receivers:
    - name: opsgenie-alert
      opsgenie_configs:
        - update_alerts: true
```

We expect installation to go fine and see different behavior itn Opsgenie.

Current behavior:

If you set this flag to true, alertmanager pod does not appear at all in the installation.

Without this flag alertmanager is installed OK.

The installation also pretends like the installation was OK but without alertmanager it should fail.

### What's your helm version?

3.8.1

### What's your kubectl version?

1.22.6

### Which chart?

prometheus-kube-stack

### What's the chart version?

34.6.0

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --namespace monitoring --install --values /home/vsts/work/1/s/Helmcharts/prometheus/values-prometheus.yaml --wait prometheus prometheus-community/kube-prometheus-stack
