### ISSUE TITLE
configure email smtp server for grafana for kube-prometheus-stack

### ISSUE THREAD

**Issue by yspassivelogic** [prometheus-community/helm-charts#1969]
### Is your feature request related to a problem ?

how do I configure configure email smtp server for grafana using kube-prometheus-stack helm chart values.yaml?

### Describe the solution you'd like.

configure the email smtp server for grafana

### Describe alternatives you've considered.

Using another helm chart

**Comment by dirsigler** [comment]
The Grafana installation in `kube-prometheus-stack` is just a subchart. 
So the `kube-prometheus-stack` merges the values.yaml from the subchart to configure Grafana.

That means you can look up the values.yaml of the subchart and check which configuration options exist there.
For SMTP you have to add the configuration in the [grafana.ini](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L570-L581).

In the `kube-prometheus-stack` you will have to add the configuration like so to your values.yaml:
```yaml
grafana:
  grafana.ini:
    smtp:
      enabled: true
      host: mail.host.com:25
      existingSecret: ""
      from_address: <from@address.com>
      passwordKey: "password"
      userKey: "user"
[...]
```

**Comment by cabal-chan** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/65152862/171976001-c526b8d9-9d31-4374-959e-09c8a0bdafd4.png">
Any idea why this would happen? I can't deploy when using the snake-case `from_address` but for w/e reason it's not using my "no-reply@myaddress.com" as the from email so it's failing. I put fromAddress: under smtp.fromAddress.

**Comment by Meet-S0ni** [comment]
I have configured smtp in my grafana but now 
I want to change smtp configurations like host and user but it is showing authentication failed 
I have setup new environment and in that env with fresh install new smtp is working 

I have changed smtp configuration in sub grafana chart and applied 
helm upgrade command

**Comment by varuncobain** [comment]
> I have configured smtp in my grafana but now I want to change smtp configurations like host and user but it is showing authentication failed I have setup new environment and in that env with fresh install new smtp is working
> 
> I have changed smtp configuration in sub grafana chart and applied helm upgrade command

can you tell me how did you set up the smtp?

**Comment by mike-pisman** [comment]
@varuncobain, I also have an issue setting up smtp https://github.com/prometheus-community/helm-charts/issues/4038

This are my values:
```yaml
grafana:
  grafana.ini:
    smtp:
      enabled: true
      host: smtp.purelymail.com:465
      startTLS: "NoStartTLS"
      passwordKey: '"""password"""'  # I use tripple quotes, because my password contains '#'
      userKey: "myemail@mydomain.com"
```

And this is what I see inside grafana.ini inside the container:
```ini
enabled = true
host = smtp.purelymail.com:465
password = """password"""
startTLS = NoStartTLS
user = myemail@mydomain.com
```
