### ISSUE TITLE
[prometheus-kube-stack] Add a my custom Grafana dashboard to Terraform project 

### ISSUE THREAD

**Issue by harelfar2** [prometheus-community/helm-charts#1971]
### Describe the bug a clear and concise description of what the bug is.

Grafana service did not load my dashboard that I made.

### What's your helm version?

v3.8.0

### What's your kubectl version?

1.23.4

### Which chart?

kube-prometheus-stack

### What's the chart version?

34.9.0

### What happened?

In some runs, Grafana presenting only the default dashboards, but not mine.
In other run I'm getting:
```
Error: Post "http://localhost/api/v1/namespaces/default/configmaps": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with module.monitoring.kubernetes_config_map.grafana-dashboards-istio,
│   on modules/monitoring/resources.tf line 1, in resource "kubernetes_config_map" "grafana-dashboards-istio":
│    1: resource "kubernetes_config_map" "grafana-dashboards-istio" {
```

### What you expected to happen?

To load my custom dashboard

### How to reproduce it?

I'm using prometheus in my EKS cluster like this:
```
resource "helm_release" "prometheus" {
  name             = "kube-prometheus-stack"
  chart            = "kube-prometheus-stack"
  repository       = "https://prometheus-community.github.io/helm-charts"
  version          = "34.9.0"
  wait             = false
  cleanup_on_fail  = true
  namespace        = "monitoring"
  create_namespace = true
}
```

I'm trying to load my own dashboard like this as I saw in [this issue](https://github.com/prometheus-community/helm-charts/issues/336) 
```
resource "kubernetes_config_map" "grafana-dashboards-istio" {
  metadata {
    name      = "grafana-dashboard-istio"
    namespace = "monitoring"

    labels = {
      grafana_dashboard = 1
    }

    annotations = {
      k8s-sidecar-target-directory = "/tmp/dashboards/istio"
    }
  }

  data = {
    "my-dash.json"             = file("${path.module}/grafana-dashboards/Cluster-dashboard-1649316050433.json")
  }
}
```

and it doesn't work

### Enter the changed values of values.yaml?

```
grafana: 
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      folder: /tmp/dashboards

      ## Annotations for Grafana dashboard configmaps
      ##
      annotations: 
        k8s-sidecar-target-directory: "/tmp/dashboards/kubernetes"
      multicluster:
        global:
          enabled: false
        etcd:
          enabled: false
      provider:
        allowUiUpdates: false
        foldersFromFilesStructure: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true

      uid: prometheus
```

### Enter the command that you execute and failing/misfunctioning.

terraform apply

### Anything else we need to know?

Maybe I'm in the wrong direction for this, but i'm just looking for loading my dashboard in this helm chart. I looked pretty hard for that and didn't find the solution.
Thanks ahead.
