### ISSUE TITLE
[prometheus-kube-stack] Unhealthy Targets:  kube-scheduler

### ISSUE THREAD

**Issue by mogody** [prometheus-community/helm-charts#1979]
### Describe the bug a clear and concise description of what the bug is.

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/10496478/163159277-7b926198-3610-4896-a55d-3975b3b30e56.png">

### What's your helm version?

v3.8.1

### What's your kubectl version?

v1.22.8

### Which chart?

kube-prometheus-stack-34.9.0

### What's the chart version?

34.9.0

### What happened?

After version 1.22 of k8s, the default listening port of Kube scheduler is 10259, not 10251, but in the _helpers.tpl file, it is defined that port 10259 should be monitored only when the version is higher than 1.23

```
{{/* Get value for kube-scheduler depending on insecure scraping availability */}}
{{- define "kube-prometheus-stack.kubeScheduler.insecureScrape" -}}
  {{- $values := index . 0 -}}
  {{- $insecure := index . 1 -}}
  {{- $secure := index . 2 -}}
  {{- $userValue := index . 3 -}}
  {{- include "kube-prometheus-stack.kubeVersionDefaultValue" (list $values ">= 1.23-0" $insecure $secure $userValue) -}}
{{- end -}}
```

### What you expected to happen?

```
{{/* Get value for kube-scheduler depending on insecure scraping availability */}}
{{- define "kube-prometheus-stack.kubeScheduler.insecureScrape" -}}
  {{- $values := index . 0 -}}
  {{- $insecure := index . 1 -}}
  {{- $secure := index . 2 -}}
  {{- $userValue := index . 3 -}}
  {{- include "kube-prometheus-stack.kubeVersionDefaultValue" (list $values ">= 1.22-0" $insecure $secure $userValue) -}}
{{- end -}}
```

### How to reproduce it?

No response

### Enter the changed values of values.yaml?

```
prometheusOperator:
  admissionWebhooks:
    patch:
      image:
        repository: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-webhook-certgen

kube-state-metrics:
  image:
    repository: ccr.ccs.tencentyun.com/mogody/kube-state-metrics
    tag: v2.4.2
  imagePullSecrets:
    - name: qcloudregistrykey
```

### Enter the command that you execute and failing/misfunctioning.

No response

### Anything else we need to know?

No response
