### ISSUE TITLE
[kube-prometheus-stack] Support separate grafana instance

### ISSUE THREAD

**Issue by Legion2** [prometheus-community/helm-charts#199]
**Is your feature request related to a problem? Please describe.**
I have already setup grafana in my cluster and what to reuse it for the monitoring of the cluster resources. So, I want to use the `kube-prometheus-stack` Chart but disable grafana, so that there is no second grafana instance deployed in my cluster. But when I set `grafana.enabled` to `false` the datasources and dashboards for grafana are not generated. I would have to set them up manually to integrate the existing grafana with prometheus.

**Describe the solution you'd like**
There should be a configuration option to generated  the `configmaps-datasources.yaml` and `configmap-dashboards.yaml` even when grafana is disabled. This allows the existing grafana instance to detect and include the datasources and the dashboards.

**Describe alternatives you've considered**
- Use the grafana instance deployed with `kube-prometheus-stack`. But this is not an option for me see **Additional context**.
- Setup the datasources and dashboards manually or copy-past them from this repo. But this is not a maintainable solution.

**Additional context**
The grafana is not only/mainly used for monitoring of the cluster, so I want it to be separately deployed and managed.

**Comment by WilliamCassanova** [comment]
**Is your feature request related to a problem? Please describe**
*Feature Related*
I believe I have a related use-case.  Let's assume I have a kube-stack-prometheus chart deployed currently.  Is it possible to have yet an additional grafana and an additional prometheus-instance deployed? Looking at https://github.com/prometheus-community/helm-charts/blob/1605c5cb1382b3acd6a7a8c867c62d3d2da13f30/charts/kube-prometheus-stack/README.md#multiple-releases I see `set kubeStateMetrics.enabled, nodeExporter.enabled and grafana.enabled to false`.  I really want to set these to true.

Let's assume I have 2 applications running in a given cluster named foo and bar.

Associated with foo:
- A set of dashboards only associated with foo will include kubeStateMetrics and nodeExporter Metrics as well as those dashboards associated with foo.  I have complete control of foo's application dashboards which we can insert manually or otherwise.
- A set of PVC's and Thanos volumes only associated with foo.
- The grafana instance would have a different URL associated with it.

Associated with bar:
- A set of dashboards only associated with bar will include kubeStateMetrics and nodeExporter Metrics as well as those dashboards associated with bar.  I have complete control of bars's application dashboards which we can insert manually or otherwise.
- A set of PVC's and Thanos volumes only associated with bar.
- The grafana instance would have a different URL associated with it.

**Describe alternatives you've considered**
- One complete kube-prometheus-stack named something like `prometheus-operator-foo`
- A second complete kube-prometheus-stack but named `prometheus-operator-bar` with the hope that the prometheus-instances, grafana-instances, and PVC names will follow suite and not remove the existing ones.  The name of the allocated PVC's seems to either follow the deployment, replicaset, or stateful set.  I am not sure which or if it simply creates a name like `prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0` or `prometheus-operator-grafana`.

There are some values overrides that may provide this functionality already --> https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L7-L25

**Comment by Legion2** [comment]
@WilliamCassanova When I understand you correctly, you want to reuse the kubeStateMetrics and nodeExporter but have separated prometheus and grafana instances? This would require the `kube-prometheus-stack` chart to generate the `configmaps-datasources.yaml` and `configmap-dashboards.yaml` for both instances or both use the same label on the configmaps, so thez are included by the grafana sidecar container.

I have found https://github.com/prometheus-operator/kube-prometheus/tree/master/manifests, which is used by the `kube-prometheus-stack` chart. It contains all the configuration files and can be used with kustomize. I'm currently trying to figure out how to use only single files and make it work with the `kube-prometheus-stack` chart when grafana is disabled.

**Comment by WilliamCassanova** [comment]
Thank you for the updates.

**Comment by Legion2** [comment]
I was able to import most of the dashboards by including the following `kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  grafana_dashboard: "1"
resources:
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/f0755dcaa83529f69ca0f999f22f883a00709ff4/manifests/grafana-dashboardDefinitions.yaml
```
For the grafana datasource i used:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-grafana-datasource
  labels:
    grafana_datasource: "1"
type: Opaque
stringData:
  prometheus-grafana-datasource.yaml: |-
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: "http://prometheus-kube-prometheus-prometheus:9090"
```
