### ISSUE TITLE
[prometheus-kube-stack] Alertmanager custom configuration causes alertmanager statefuleset to fail to create

### ISSUE THREAD

**Issue by ShenGuangYang** [prometheus-community/helm-charts#2003]
### Describe the bug a clear and concise description of what the bug is.

When I customize the alertmanager config, the alertmanager statefulset is not automatically created,and I do not configure the alertmanager config, the alertmanager statefulset can be created automatically。
The configuration I use is the content provided in the helm chart values.

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-aliyun.1", GitCommit:"d966b365d87fb2783deab0d244047d340f1be146", GitTreeState:"clean", BuildDate:"2022-01-19T01:10:01Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

34.10.0

### What happened?

When I customize the alertmanager config, the alertmanager statefulset is not automatically created,and I do not configure the alertmanager config, the alertmanager statefulset can be created automatically。
The configuration I use is the content provided in the helm chart values

### What you expected to happen?

Using custom configuration can generate alertmanager statefulset and inject normally

### How to reproduce it?

local create files: Chart.yaml 、values.yaml
Chart.yaml 
```
dependencies:
  - name: kube-prometheus-stack
    version: 34.10.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-prometheus-stack.enabled
```
helm dependency update 

### Enter the changed values of values.yaml?

```
alertmanager:
  alertmanagerSpec:
    storage:
     volumeClaimTemplate:
       spec:
         storageClassName: local-path
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 10Gi
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: [ 'alertname' ]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: "web.hook"
      routes:
        - match:
            alertname: Watchdog
          receiver: "null"
        - match:
            alertname: Watchdog1
          receiver: "web.hook"
    receivers:
      - name: 'null'
      - name: "web.hook"
        webhook_configs:
          url: 'https://xxx.com'

```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install monitoring . -f customer-values.yaml -n monitoring
