### ISSUE TITLE
[prometheus] Add extra K8s manifests field to deploy

### ISSUE THREAD

**Issue by govargo** [prometheus-community/helm-charts#2009]
### Is your feature request related to a problem ?

I use Prometheus chart on GKE cluster.

When I build ingress, I'd like to enable GKE [ManagedCertificate](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs) and [BackendConfig](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#configuring_ingress_features_through_backendconfig_parameters).

In current prometheus chart, there is no area to add these manifests.

### Describe the solution you'd like.

Add the extraObjects field into values.yaml and template file.

for example

```yaml
# -- Array of extra K8s manifests to deploy
extraObjects:
  - apiVersion: networking.gke.io/v1
     kind: ManagedCertificate
     metadata:
       name: prometheus-server
       labels:
         component: "server"
         app: prometheus
         release: prometheus
         chart: prometheus-15.8.5
         heritage: Helm
       namespace: prometheus
     spec:
       domains:
       - "example.com"
```

### Describe alternatives you've considered.

In current solution, I use Prometheus chart as subchart. And I added my resources(e.g. ManagedCertificate & BackendConfig).
