### ISSUE TITLE
How to access Grafana behind with an Ingress Controller?

### ISSUE THREAD

**Issue by cnukwas** [prometheus-community/helm-charts#201]
I have installed below kube-prometheus-stack and getting an error when trying to access Grafana dashboard using it's own Ingress URL. We're using TraefikEE and here is the Ingress definition.

Chart: kube-prometheus-stack-9.4.5
App Version: 0.38.1

When I navigate to https://myorg.grafanatest.com URL, I get redirected to https://myorg.grafanatest.com/login with following message. 

 If you're seeing this Grafana has failed to load its application files

1. This could be caused by your reverse proxy settings.

2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath. If not using a reverse proxy make sure to set serve_from_sub_path to true.

3. If you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarn build

4. Sometimes restarting grafana-server can help

TraefikEE IngressRoute YAML:

`

kind: IngressRoute
metadata:
  name: grafana-test
  namespace: prometheus
spec:
  tls: {}
  entryPoints:
    - websecure
  routes:
    - match: Host(`myorg.grafanatest.com`)
      kind: Rule
      services:
        - name: prometheus-grafana
          namespace: prometheus
          port: 80`

Unpacked kube-prometheus chart tar and updated below section in grafana/values.yaml, and re-installed the stack, but still getting same error. I have already created TraefikEE Ingressroute for Grafana and other services. What else I need to check or enable in ingress section or other places, to make this work?

grafana/values.yaml:

`

grafana.ini:
  server:
    # The full public facing url you use in browser, used for redirects and emails
    root_url: https://myorg.grafanatest.com`

Thanks

**Comment by monotek** [comment]
I guess you should ask questions for ingress route in the Trafik issue tracker as this is not part of the chart.

Please also use code tags next time, for better readability ;-)

**Comment by cnukwas** [comment]
I did use code tags, some how it still doesn't look right. On a side note, any clue on the changes need to be made, irrespective of the Ingress Controller since I took care of Ingress set up outside the chart?

Thanks

**Comment by monotek** [comment]
No. This is a completely chart unrelated topic.

**Comment by scottrigby** [comment]
@cnukwas For future ref, single ticks (`` ` ``) should only be used for inline code lines – multi-line code blocks should be "fenced" with 3 backticks (`` ``` ``).

To make it easier to explain, I updated your description above to use code blocks and `yaml` syntax highlighting. You can edit that to see how it works. For more info, check out https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks

Hope that helps 😄

**Comment by cnukwas** [comment]
Posting a solution here as well, in case someone runs into similar issues. Make sure to create a values.yaml with defaults using below command, to avoid updating anything in installed chart files. Not sure why it didn't work without enabling serve_from_sub_path, but it's ok as it's working now. Note that I didn't enable Ingress section since I have already created Ingress route outside the installation process.

`helm show values prometheus-com/kube-prometheus-stack > custom-values.yaml`

Then install by changing below values in custom-values.yaml. Change namespace as needed.

`helm -n monitoring install -f ./custom-values.yaml pg prometheus-com/kube-prometheus-stack`



```
grafana:
  enabled: true
  namespaceOverride: ""
  # set pspUseAppArmor to false to fix Grafana pod Init errors
  rbac:
    pspUseAppArmor: false
  grafana.ini:
    server:
      domain: mysb.grafanasite.com
      #root_url: "%(protocol)s://%(domain)s/"
      root_url: https://mysb.grafanasite.com/grafana/
      serve_from_sub_path: true

  ## Deploy default dashboards.
  ##
  defaultDashboardsEnabled: true

  adminPassword: prom-operator

  ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: false

    ## Annotations for Grafana Ingress
    ##
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

    ## Labels to be added to the Ingress
    ##
    labels: {}

    ## Hostnames.
    ## Must be provided if Ingress is enable.
    ##
    # hosts:
    #   - grafana.domain.com
    hosts:
      - mysb.grafanasite.com

    ## Path for grafana ingress
    path: /grafana/
```

**Comment by dummys** [comment]
@cnukwas can you post the full ingressRoute yaml file please ? I'm struggling with the same thing as you. My ingress looks like this:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: prometheus
  name: grafana-ingress-route
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`myhost`) && (PathPrefix(`/grafana`))
      kind: Rule
      services:
      - kind: Service
        name: grafana-service
        port: 80
      middlewares:
      - name: grafana-stripprefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: prometheus
  name: grafana-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /grafana
    forceSlash: true

```

My goal is to be able to access the grafana dashboard using `/grafana` on the traefik load balancer ip.
I'm not sure of my service config, because as I see in the default config it listen to port 3000 but in my case I can't access it.

**Comment by cnukwas** [comment]
I will have to check our IngressRoute and compare for anything, but your Ingress YAML looks fine. Try without stripprefix middleware and see if you're able to get to Grafana login page. One of the time consuming issue for me was trying to bring up without /grafana context path, but it started working fine once I had that in place as I mentioned in Helm values.yaml above.
Also try with `Host(`myhost`)` option only since Grafana loads resources from multiple paths.

**Comment by mikejoseph-ah** [comment]
@cnukwas hey, can you provide your ingressroute setup? I am trying to expose grafana using traefik also and getting into problems it's not working

traefik values:
```yaml
  ports:
    web:
      port: 80
    websecure:
      port: 443
  ingressRoute:
    dashboard:
      enabled: false
  additionalArguments:
    - --entryPoints.web.http.redirections.entryPoint.to: websecure
    - --entryPoints.web.http.redirections.entryPoint.scheme: https
  securityContext:
    capabilities:
      drop: [ALL]
      add: [NET_BIND_SERVICE]
    readOnlyRootFilesystem: true
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values:
            - general
```

kube-prom-stack values:
```yaml
  grafana:
    grafana.ini:
      auth.google:
        allow_sign_up: true
        allowed_domains: org.ai grafana.org.ai
        auth_url: https://accounts.google.com/o/oauth2/auth
        client_id: CLIENT_ID
        client_secret: CLIENT_SECRET
        enabled: true
        scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
        token_url: https://accounts.google.com/o/oauth2/token
      server:
        domain: grafana.org.ai
        #root_url: "%(protocol)s://%(domain)s/"
        root_url: https://grafana.org.ai/grafana/
        serve_from_sub_path: true
```

ingress-route yaml:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress-route
  namespace: ${kubernetes_namespace.monitoring-ns.metadata.0.name}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.org.ai/grafana`)
      kind: Rule
      services:
      - kind: Service
        name: kube-prometheus-stack-grafana
        port: 80
  tls:
    secretName: grafana-tls
```

cert yaml:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: ${kubernetes_namespace.monitoring-ns.metadata.0.name}
spec:
  dnsNames:
    - grafana.org.ai
  secretName: grafana-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
```
