### ISSUE TITLE
[prometheus-adapter] service account template can't render both serviceAccount.annotations and customAnnotations

### ISSUE THREAD

**Issue by JTarasovic** [prometheus-community/helm-charts#2011]
### Describe the bug a clear and concise description of what the bug is.

Unable to set both `serviceAccount.annotations` and `customAnnotations` for `prometheus-adapter`.

### What's your helm version?

`version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.18.1"}`

### What's your kubectl version?

`Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"archive", BuildDate:"2022-04-21T13:54:39Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-14c7a48", GitCommit:"35f06c94ad99b78216a3d8e55e04734a85da3f7b", GitTreeState:"clean", BuildDate:"2022-04-01T03:18:05Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}`

### Which chart?

prometheus-adapter

### What's the chart version?

3.2.1

### What happened?

```
Error: YAML parse error on prometheus-adapter/templates/serviceaccount.yaml: error converting YAML to JSON: yaml: line 15: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 15: did not find expected key
YAML parse error on prometheus-adapter/templates/serviceaccount.yaml
```

### What you expected to happen?

For both to be able to be set and render the combined set.

### How to reproduce it?

`helm template a prometheus-community/prometheus-adapter --set "serviceAccount.annotations.a"="b" --set "customAnnotations.c"="d" --debug`

### Enter the changed values of values.yaml?

serviceAccount.annotations

customAnnotations

### Enter the command that you execute and failing/misfunctioning.

`helm template a prometheus-community/prometheus-adapter --set "serviceAccount.annotations.a"="b" --set "customAnnotations.c"="d" --debug`

```
# Source: prometheus-adapter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: prometheus-adapter-3.2.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-adapter
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/instance: a
    app.kubernetes.io/version: "v0.9.1"
  name: a-prometheus-adapter
  namespace: metrics-server
  annotations:
      a: b
    c: d
 ```
