### ISSUE TITLE
[prometheus-kube-stack] additional scrape config doesn't work...

### ISSUE THREAD

**Issue by preethikarthi** [prometheus-community/helm-charts#203]
https://github.com/prometheus-operator/prometheus-operator/issues/3582

This was raised in there.. u can find the details of the issue.....

**Comment by jellevanhees** [comment]
this is not a stale issue we are experiencing the same behaviour on the 11.1.1 release.
somehow they if statement surrounding the additionalScrapeConfig.yaml is never true and the template is skiped even if config is present in the values file and prometheus is set to true.

**Comment by monotek** [comment]
Can reproduce. I have used them for Blackbox exporter lime this: 

```
prometheus:
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: 'prometheus-blackbox-exporter'
            metrics_path: /probe
            params:
              module: [http_2xx]
            static_configs:
              - targets:
                - https://grafana.dev.bike24.io
                - https://www.bike24.com
            relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                replacement: prometheus-blackbox-exporter.monitoring:9115
```

**Comment by jellevanhees** [comment]
@monotek 

We solved the blackbox exporter with the service monitor custom resource definition. so i would look in to that.
I also managed to get the scrape config working using the following values.
this issue for us was indents.
```
  - job_name: 'customconfig'
          ec2_sd_configs:
            - region: eu-west-1
              port: 9100
          relabel_configs:
          # Only monitor instances with a Name starting with "dev-"
            - source_labels: [ __meta_ec2_tag_CreatedBy ]
              regex: jelle
              action: keep
            - source_labels: [ __meta_ec2_tag_Name,__meta_ec2_instance_id ]
              target_label: instance
```
