### ISSUE TITLE
[prometheus-kube-stack] - How to disable node exporters & Grafana on GCP GKE - v1.21.10-gke.2000.

### ISSUE THREAD

**Issue by karlwowza** [prometheus-community/helm-charts#2037]
### Describe the bug a clear and concise description of what the bug is.

Hi there, 

I can disable node exporter deployment locally in k3d, but as it seems **i cant disable the deployment of node exporters and Grafana on my nodes (GCP GKE - v1.21.10-gke.2000.) in my GCP cluster**

I am using helm chart details below:

```
- name: kube-prometheus-stack
  version: "35.0.3"
  repository: "https://prometheus-community.github.io/helm-charts"
```

I used following command in my values.yaml.

```
kube-prometheus-stack:
  # Deploy node exporter as a daemonset to all nodes
  nodeExporter:
    enabled: false
```

Is there anything special about GCP that plays a role in the deployment of promethreus node exporters?

### What's your helm version?

version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}

### What's your kubectl version?

clientVersion:   buildDate: "2022-05-03T13:36:49Z"   compiler: gc   gitCommit: 4ce5a8954017644c5420bae81d72b09b735c21f0   gitTreeState: clean   gitVersion: v1.24.0   goVersion: go1.18.1   major: "1"   minor: "24"   platform: darwin/arm64 kustomizeVersion: v4.5.4

### Which chart?

kube-prometheus-stack

### What's the chart version?

35.0.3

### What you expected to happen?

I would like to disable node exporters on all gcp gke nodes.

### How to reproduce it?

Best would be to deploy the helm chart on GCP GKE - v1.21.10-gke.2000 nodes.

### Enter the changed values of values.yaml?

kube-prometheus-stack:
  # Deploy node exporter as a daemonset to all nodes
  nodeExporter:
    enabled: false

### Enter the command that you execute and failing/misfunctioning.

client.go:254: [debug] Starting delete for "monitoring-federation-kube-admission" Role
client.go:254: [debug] Starting delete for "monitoring-federation-kube-admission" RoleBinding
client.go:254: [debug] Starting delete for "monitoring-federation-kube-admission-patch" Job
NAME: monitoring-federation
LAST DEPLOYED: Fri May  6 22:48:23 2022
NAMESPACE: monitoring-federation
STATUS: deployed
REVISION: 1
USER-SUPPLIED VALUES:
chart_name: prometheus-federation
circleci_context: non-prod-g
helm_chart_name: prometheus-federation
helm_chart_version: 0.0.44
kube-prometheus-stack:
  grafana:
    adminPassword: XXX
    enabled: true
    ingress:
      enabled: true
      hosts:
      - XXX
      ingressClassName: nginx
      tls:
      - hosts:
        - XXX
        secretName: letsencrypt-prod-monitoring-crt
  nodeExporter:
    enabled: false

### Anything else we need to know?

**helm log excert**

```
client.go:254: [debug] Starting delete for "monitoring-federation-kube-admission" Role
client.go:254: [debug] Starting delete for "monitoring-federation-kube-admission" RoleBinding
client.go:254: [debug] Starting delete for "monitoring-federation-kube-admission-patch" Job
NAME: monitoring-federation
LAST DEPLOYED: Fri May  6 22:48:23 2022
NAMESPACE: monitoring-federation
STATUS: deployed
REVISION: 1
USER-SUPPLIED VALUES:
chart_name: prometheus-federation
circleci_context: non-prod-g
helm_chart_name: prometheus-federation
helm_chart_version: 0.0.44
kube-prometheus-stack:
  grafana:
    adminPassword: XXX
    enabled: true
    ingress:
      enabled: true
      hosts:
      - XXX
      ingressClassName: nginx
      tls:
      - hosts:
        - XXX
        secretName: letsencrypt-prod-monitoring-crt
  nodeExporter:
    enabled: false
```

**Comment by tanmx** [comment]
use this
```
kube-state-metrics:

nodeExporter:
  enabled: false
```

**Comment by karlwowza** [comment]
Hi @tanmx,

thanks. I tried the settings below:

```
kube-state-metrics:
nodeExporter:
  enabled: false
```

and 

```
kube-state-metrics:
  nodeExporter:
    enabled: false
```

but it does not really work as i expect it would: Grafana and gets always enabled / deployed and node exporters always deployed. 

I have also noticed that its not possible to disable **Grafana** as well. 

This is the actual "configuration" .yaml file i use

```
kube-prometheus-stack:
  grafana:
    enabled: false
    adminPassword: xxx
    ingress:
      enabled: false 
      ingressClassName: nginx
      hosts:
        - xxx
      tls:
        - secretName: letsencrypt-prod-monitoring-crt
          hosts:
            - xxx

  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - xxx
      tls:
        - secretName: letsencrypt-prod-monitoring-crt
          hosts:
            - xxx

    prometheusSpec:
      scrapeInterval: 1m
      scrapeTimeout: 1m

  ## Deploy node exporter as a daemonset to all nodes
  nodeExporter:
    enabled: false

  kubeStateMetrics:
    enabled: false

  ## Configuration for prometheus-node-exporter subchart
  prometheus-node-exporter:
    prometheus:
      monitor:
        enabled: true

  # prometheusOperator:
  #   admissionWebhooks:
  #     enabled: false
```

I appreciate any help!
