### ISSUE TITLE
[prometheus-blackbox-exporter] AdditionalRelabeling Runtime Error

### ISSUE THREAD

**Issue by j0sh3rs** [prometheus-community/helm-charts#2045]
### Describe the bug a clear and concise description of what the bug is.

Attempting to apply version 5.8.0 using flux's HelmRelease functionality results in an inability to leverage version 5.8.0 of the chart.  This is directly related to the recent merger of https://github.com/prometheus-community/helm-charts/commit/902a9561966d41fb2b33fa64dd70d67a930a3ee9 which adds the additionalRelabeling functionality. Deploying version 5.7.0 with flux succeeds.

```
Last Helm logs:
  Warning  error  4m53s (x286 over 2d20h)  helm-controller  reconciliation failed: Helm install failed: template: prometheus-blackbox-exporter/templates/servicemonitor.yaml:43:7: executing "prometheus-blackbox-exporter/templates/servicemonitor.yaml" at <concat .additionalRelabeling $.Values.serviceMonitor.defaults.additionalRelabeling>: error calling concat: runtime error: invalid memory address or nil pointer dereference
  Normal   info   107s (x2 over 2d20h)     helm-controller  HelmChart 'flux-system/monitoring-blackbox-exporter' is not ready
```

### What's your helm version?

version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:58Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/arm64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:58Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/arm64"}

### Which chart?

prometheus-blackbox-exporter

### What's the chart version?

5.8.0

### What happened?

Helm chart fails to install, citing a runtime error on the concat function.

### What you expected to happen?

Chart version 5.8.0 should deploy successfully with the default values for additionalRelabeling insideserviceMonitor

### How to reproduce it?

Upgrade to chart version 5.8.0, enable serviceMonitor as part of values.yaml definition. Do not override the default value for serviceMonitor.defaults.additionalRelabeling

### Enter the changed values of values.yaml?

```yaml
  values:
    allowIcmp: true
    config:
      modules:
        icmp:
          prober: icmp
          timeout: 30s
          icmp:
            preferred_ip_protocol: "ip4"
        http_2xx:
          prober: http
          timeout: 30s
          http:
            valid_http_versions: ["HTTP/1.0", "HTTP/1.1", "HTTP/2.0"]
            no_follow_redirects: false
            preferred_ip_protocol: "ip4"
        tcp_connect:
          prober: tcp
          timeout: 30s

    serviceMonitor:
      enabled: true
      defaults:
        labels:
          release: prometheus
        interval: 2m
        scrapeTimeout: 30s
      targets:
        - name: synology
          url: "192.168.35.5"
          module: icmp
        - name: rpi
          url: "192.168.35.8"
          module: icmp
        - name: mbp
          url: "192.168.35.4"
          module: icmp
        - name: xps
          url: "192.168.35.6"
          module: icmp

    prometheusRule:
      enabled: true
      additionalLabels:
        app: prometheus-operator
        release: prometheus
      rules:
        - alert: HostDown
          expr: probe_success == 0
          for: 10m
          labels:
            severity: critical
          annotations:
            message: The host {{"{{ $labels.target }}"}} is currently unreachable
        - alert: SlowResponseTime
          annotations:
            message: The response time for {{"{{ $labels.target }}"}} has been greater than 30 seconds for 5 minutes.
          expr: probe_duration_seconds > 30
          for: 15m
          labels:
            severity: warning
```

### Enter the command that you execute and failing/misfunctioning.

helm install blackbox-exporter prometheus-community/prometheus-blackbox-exporter -f values.yaml
