### ISSUE TITLE
[kube-prometheus-stack] set serviceMonitorSelector in serviceMonitor labels

### ISSUE THREAD

**Issue by Grounz** [prometheus-community/helm-charts#2051]
### Is your feature request related to a problem ?

Hi,

When i deploy kube-rometheus-stack with this `serviceMonitorSelector`:

```yaml
    serviceMonitorSelector:
    ## Example which selects ServiceMonitors with label "prometheus" set to "somelabel"
    # serviceMonitorSelector:
      matchLabels:
        prometheus.io/monitor: "true"
```

All serviceMonitor for prometheus  exporters available in chart will be created without this labels: `prometheus.io/monitor: "true"` but have  `release: prometheus` and other labels.

It's possible to have the possibility to set the labels defined in `serviceMonitorSelector` in all kube-prometheus-stack serviceMonitor ?

For the moment  i have add this labels `prometheus.io/monitor: "true"` in commonLabels value in values file.  

### Describe the solution you'd like.

When i set `serviceMonitorSelector` i want set this serviceMonitorSelector on all exporter of kube-prometehus-stack

### Describe alternatives you've considered.

For the moment  i have add this labels `prometheus.io/monitor: "true"` in commonLabels value in values file but all K8S ressources have this labels, is not very good :/

### Additional context.

Label is use here: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/exporters/kube-api-server/servicemonitor.yaml#L9

But just default labels is available to set. But for kube-state-metrics or nodeExporter it's possible to define additionnalLabels serviceMonitor: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml#L31
