### ISSUE TITLE
[kube-prometheus-stack] Unable to modify a pvc once created

### ISSUE THREAD

**Issue by FranAguiar** [prometheus-community/helm-charts#2078]
### Describe the bug a clear and concise description of what the bug is.

Cannot resize a PVC created with the chart. Seems to be the same issue described here:
https://github.com/prometheus-community/helm-charts/issues/957

### What's your helm version?

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}

### What's your kubectl version?

Flag --short has been deprecated, and will be removed in the future. The --short output will become the default. W0520 16:00:45.099484   18777 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead. To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke Client Version: v1.24.0 Kustomize Version: v4.5.4 Server Version: v1.22.8-gke.2200 WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1

### Which chart?

kube-prometheus-stack

### What's the chart version?

35.3.1

### What happened?

I'm new to k8s and helm world and maybe it isn't an issue and it's how it works. In that case this can be closed.

I'm just playing with the chart I want to create a PVC, I added it to the values.yaml, then install the chart. Everiything works, the pvc is created. Fine.

Now I want to resize that PVC, edit the yaml and change the storage (10Gi), upgrade the chart, no errors. But the PVC size is still 9Gi. If I go throught GKE UI, edit the yaml and save, I can resize the PVC
```
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: premium-rwo
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 9Gi
```

### What you expected to happen?

Resize the PVC created with the chart

### How to reproduce it?

Install and upgrade the chart with the values.yaml provided

### Enter the changed values of values.yaml?

storege: 10Gi

### Enter the command that you execute and failing/misfunctioning.

* helm install prometheus prometheus-community/kube-prometheus-stack --values values.yaml
* helm upgrade prometheus prometheus-community/kube-prometheus-stack --values values.yaml
