### ISSUE TITLE
[kube-prometheus-stack] Enable sigv4 auth in grafana

### ISSUE THREAD

**Issue by msharma24** [prometheus-community/helm-charts#2092]
### Is your feature request related to a problem ?

We have configured the prometheus to remoteWrite to the AWS Managed Prometheus  service endpoint, however there is no option in the Grafana deployed with kube-prometheus-stack to enable the "Sigv4" auth on the prometheus datasource —this is needed to configure the AWS Managed Prometheus query endpoint as datasource and use the Sigv4 to assume the ServiceAccount IAM Role permissions. 

Please advise if you have been able to solve this issue.

### Describe the solution you'd like.

Settings / values to enable the sigv4 auth for grafana

### Describe alternatives you've considered.

Deploy the https://github.com/grafana/helm-charts in a new namespace as the default installation allows to use "Sigv4" auth for the prometheus datasource.

**Comment by hoangtrucit** [comment]
@msharma24 You can override `grafana.ini` to enable `sigv4_auth_enabled`. This is my `values.yaml`

```
...
grafana:
  enabled: true
  namespaceOverride: ""
  grafana.ini: 
    auth:
      sigv4_auth_enabled: true 
...
```

**Comment by msharma24** [comment]
@hoangtrucit 

Thank you for your response. 
We figured the following settings worked for us .
```
grafana:
  serviceAccount:
    create: false
    name: iamproxy-service-account
  grafana.ini:
    auth:
      sigv4_auth_enabled: true
  additionalDataSources:
    - name: prometheus-amp
      editable: true
      jsonData:
        sigV4Auth: true
        sigV4Region: us-west-2
      type: prometheus
      isDefault: true
      url: https://aps-workspaces.us-west-2.amazonaws.com/workspaces/<ID>
prometheus:
  serviceAccount:
    create: false
    name:   iamproxy-service-account
      
  prometheusSpec:
    remoteWrite:
      -  url:  https://aps-workspaces.us-west-2.amazonaws.com/workspaces/<ID>
        sigv4:
          region: us-west-2
          roleArn:  IAM_ROLE_ARN

```
