### ISSUE TITLE
kube-prometheus-stack Grafana Import Dashboard button (Upload json file) not working with Version 8.5.3

### ISSUE THREAD

**Issue by jtgorny** [prometheus-community/helm-charts#2130]
### Describe the bug a clear and concise description of what the bug is.

When attempting to import a dashboard via the “Upload JSON File” button, nothing happens. The button is broken in Grafana 8.5.3. I either need to select the button via tabbing to it and hitting enter or copy+paste the content of the json file into the import via panel json. 

**Suggest moving to 8.5.4 where this bug is fixed.**

### What's your helm version?

version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"darwin/arm64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

35.5.1

### What happened?

Install worked fine. When attempting to upload custom dashboards, discovered the "Upload JSON File" button was broken.

### What you expected to happen?

The button to work (file explorer to open)  ¯\_(ツ)_/¯

### How to reproduce it?

Click the button and observe nothing happen. 

### Enter the command that you execute and failing/misfunctioning.

helm upgrade -i \
  -f ~/projects/foo-bar/values-dev.yaml \
    --version 35.5.1 \
  monitoring-dev \
    --namespace=monitoring \
  prometheus-community/kube-prometheus-stack

**Comment by jtgorny** [comment]
Overrode the default image being used by `kube-prometheus-stack-35.5.1` with:
```
  ## Grafana image pull override. (Overriding 8.5.3 due to bug with custom dashboard upload)
  image:
    repository: grafana/grafana
    # Overrides the Grafana image tag whose default is the chart appVersion
    tag: 8.5.4
    sha: ""
    pullPolicy: IfNotPresent
```
