### ISSUE TITLE
[kube-prometheus-stack] Reduce container metrics by default.

### ISSUE THREAD

**Issue by SuperQ** [prometheus-community/helm-charts#2133]
### Is your feature request related to a problem ?

Many users complain about memory use of Prometheus when using `kube-prometheus-stack`. One major contributor to this is kubelet cAdvisor `container_...` metrics.

There are a number of overlapping, less useful, or always zero metrics returned by cAdvisor.

### Describe the solution you'd like.

In order to improve on this, we should add a default `metricRelabelings` to the `ServiceMonitor`. This would more closely align with the recommended defaults in the [upstream kube-prmetheus manifests](https://github.com/prometheus-operator/kube-prometheus/blob/bfc49f2fe984fbc8de6a2f3bf14c7bc5d2cbce57/manifests/kubernetesControlPlane-serviceMonitorKubelet.yaml#L59-L74).

### Describe alternatives you've considered.

We could document this, but it would be much better to have sane defaults built in.

**Comment by SuperQ** [comment]
First proposal, this is the metricRelabeling I use in production.

```
kubelet:
  serviceMonitor:
    cAdvisorMetricRelabelings:
      # Drop less useful container CPU metrics.
      - sourceLabels: [__name__]
        action: drop
        regex: 'container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)'
      # Drop less useful container / always zero filesystem metrics.
      - sourceLabels: [__name__]
        action: drop
        regex: 'container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)'
      # Drop less useful / always zero  container memory metrics.
      - sourceLabels: [__name__]
        action: drop
        regex: 'container_memory_(mapped_file|swap)'
      # Drop less useful container process metrics.
      - sourceLabels: [__name__]
        action: drop
        regex: 'container_(file_descriptors|tasks_state|threads_max)'
      # Drop container spec metrics that overlap with kube-state-metrics.
      - sourceLabels: [__name__]
        action: drop
        regex: 'container_spec.*'
      # Drop cgroup metrics with no pod.
      - sourceLabels: [id, pod]
        action: drop
        regex: '.+;'
      # Drop cgroup metrics with no container.
      - sourceLabels: [id, container]
        action: drop
        regex: '.+;'
```
