### ISSUE TITLE
[prometheus] how to disable honor_labels without defining the whole job block in values.yaml

### ISSUE THREAD

**Issue by mo-saeed** [prometheus-community/helm-charts#2134]
### Describe the bug a clear and concise description of what the bug is.

Hello,

So recently there was this change [here](https://github.com/prometheus-community/helm-charts/pull/1957) which lead to our grafana dashboards to be broken coz we are using `exported_namespace` label which after this change reverted back to `namespace`

so now I would like to set `honor_labels`  to false so I don't need to change all my grafana dashboard and i tried to do this 
```
      prometheus.yml:
        scrape_configs:
          # disable honor_labels to use labels with prefix "exported_"
          # https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config
          - job_name: 'kubernetes-service-endpoints'
            honor_labels: false
          - job_name: 'kubernetes-service-endpoints-slow'
            honor_labels: false
          - job_name: 'kubernetes-services'
            honor_labels: false
          - job_name: 'kubernetes-pods'
            honor_labels: false
          - job_name: 'kubernetes-pods-slow'
            honor_labels: false
```
but that broke prometheus coz as I assume I need to add the whole job default config block in values.yaml which is not good as i will need always to maintain this block for the upgrades and that's un-needed work.

do you have a solution maybe?

### What's your helm version?

v3.5.2

### What's your kubectl version?

v1.20.2

### Which chart?

prometheus

### What's the chart version?

latest

### Enter the command that you execute and failing/misfunctioning.

no commands, it's just after successful helm upgrade. our grafana dashboards are broken due to the namespace label change.
