### ISSUE TITLE
[prometheus] Accept template string as server.extraObjects

### ISSUE THREAD

**Issue by katsew** [prometheus-community/helm-charts#2139]
### Is your feature request related to a problem ?

I try to deploy extra manifest like `ManagedCertificate` with the same labels as prometheus's chart use.
It could be achieved by using server.extraObjects.
However, this field couldn't help in my case.

e.g.

```yaml
server:
  extraObjects:
  - apiVersion: {{ template "prometheus.deployment.apiVersion" . }}
    kind: ManagedCertificate
    metadata:
      labels:
        {{- include "prometheus.server.labels" . | nindent 4 }} # this field is invalid as yaml
      name: "{{ template "prometheus.server.fullname" . }}"
```

### Describe the solution you'd like.

Introduce new field for accepting manifests as string.

```yaml
# values.yaml
server:
  extraObjects: []
  extraTemplates:
  - |
    apiVersion: {{ template "prometheus.deployment.apiVersion" . }}
    kind: ManagedCertificate
    metadata:
      labels:
        {{- include "prometheus.server.labels" . | nindent 4 }}
      name "{{ template "prometheus.server.fullname" . }}"

```

```
# templates/server/extra-manifests.yaml
{{ range .Values.server.extraObjects }}
---
{{ tpl (toYaml .) $ }}
{{ end }}

{{ range .Values.server.extraTemplates }}
---
{{  tpl . $ }}
{{ end }}
```

### Describe alternatives you've considered.

I've considered using [incubator/raw](https://github.com/helm/charts/tree/master/incubator/raw) as a sub chart to deploy additional manifests.
However `incubator/raw` is no longer maintained. ;(
