### ISSUE TITLE
podMonitorSelector present?

### ISSUE THREAD

**Issue by Tasmana-banana** [prometheus-community/helm-charts#2155]
### Describe the bug a clear and concise description of what the bug is.

Hello. I know inprometheus-operator support 
```
  prometheusSpec:
    podMonitorSelector:
      matchLabels:
```
But i can't search thies now. It's bug or feature?

### What's your helm version?

3

### What's your kubectl version?

1.22

### Which chart?

prometheus-community/prometheus

### What's the chart version?

15.8.5

### Enter the command that you execute and failing/misfunctioning.

I use ansible to deploy
```
  community.kubernetes.helm:
    name: 'prometheus'
    chart_ref: 'prometheus-community/prometheus'
    release_namespace: '{{ prometheus_namespace }}'
    chart_version: '15.8.5'
    release_values:
      serviceAccounts:
        server:
          create: true
          name: 'iamproxy-service-account'
          annotations:
            eks.amazonaws.com/role-arn: 'arn:aws:iam::{{ prometheus_account_id }}:role/EKS-AMP-ServiceAccount-Role'
      alertmanager:
        nodeSelector:
          application: 'monitoring'
      nodeExporter:
        nodeSelector:
          application: 'monitoring'
      pushgateway:
        nodeSelector:
          application: 'monitoring'
      server:
        nodeSelector:
          application: 'monitoring'
        serviceMonitorSelector:
          matchLabels:
            env: 'test'
        remoteWrite:
          - url: '{{ aps_url }}'
            sigv4:
              region: '{{ aws_region }}'
              role_arn: 'arn:aws:iam::{{ aps_account_id }}:role/EKS-AMP-Central-Role'
            queue_config:
              max_samples_per_send: 1000
              max_shards: 200
              capacity: 2500
        statefulSet:
          enabled: true
```
