### ISSUE TITLE
[kube-state-metrics] Add ingress for exposing metrics

### ISSUE THREAD

**Issue by dmpe** [prometheus-community/helm-charts#2157]
### Is your feature request related to a problem ?

I would love to have a helm chart feature, whereby kube state metrics would gain ingress resource so that metrics could be exposed (!, yes purposefully). By default, this would be of course disabled, but with `true` you could enable it. 

### Describe the solution you'd like.

```
{{ if .Values.entrypoints.metrics.ingress }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | indent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostRegexp(`metrics.{middle:.*}.devops.com`)
    kind: Rule
    services:
    - name: {{ include "kube-state-metrics.fullname" . }}
      port: {{ .Values.service.port }}
  tls:
    store:
      name: "default"
{{ end }}
```

this is my current solution for Traefik proxy, however a normal networking api v1 ingress resource would be more than enough. Just to make sure that different fields are fully customizable. 

### Describe alternatives you've considered.

None

**Comment by dmpe** [comment]
Not stale

**Comment by mikejoseph-ah** [comment]
@dmpe  hey, can you provide your ingressroute setup? I am trying to expose grafana using traefik also and getting into problems it's not working

traefik values:
```yaml
  ports:
    web:
      port: 80
    websecure:
      port: 443
  ingressRoute:
    dashboard:
      enabled: false
  additionalArguments:
    - --entryPoints.web.http.redirections.entryPoint.to: websecure
    - --entryPoints.web.http.redirections.entryPoint.scheme: https
  securityContext:
    capabilities:
      drop: [ALL]
      add: [NET_BIND_SERVICE]
    readOnlyRootFilesystem: true
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values:
            - general
```

kube-prom-stack values:
```yaml
  grafana:
    grafana.ini:
      auth.google:
        allow_sign_up: true
        allowed_domains: org.ai grafana.org.ai
        auth_url: https://accounts.google.com/o/oauth2/auth
        client_id: CLIENT_ID
        client_secret: CLIENT_SECRET
        enabled: true
        scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
        token_url: https://accounts.google.com/o/oauth2/token
      server:
        domain: grafana.org.ai
        #root_url: "%(protocol)s://%(domain)s/"
        root_url: https://grafana.org.ai/grafana/
        serve_from_sub_path: true
```

ingress-route yaml:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress-route
  namespace: ${kubernetes_namespace.monitoring-ns.metadata.0.name}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.org.ai/grafana`)
      kind: Rule
      services:
      - kind: Service
        name: kube-prometheus-stack-grafana
        port: 80
  tls:
    secretName: grafana-tls
```

cert yaml:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: ${kubernetes_namespace.monitoring-ns.metadata.0.name}
spec:
  dnsNames:
    - grafana.org.ai
  secretName: grafana-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
```
