### ISSUE TITLE
[kube-prometheus-stack] `additionalServiceMonitors` not taking into account `serviceMonitorSelector` and likewise for `additionalPodMonitors `

### ISSUE THREAD

**Issue by Morriz** [prometheus-community/helm-charts#2161]
### Describe the bug a clear and concise description of what the bug is.

Any `prometheus.additionalServiceMonitors` don't take into account what labels are given to `serviceMonitorSelector`, and the same goes for`additionalPodMonitors`.

This file should imo apply the labels from `serviceMonitorSelector` so that `additionalServiceMonitors` are pointing to the prometheus that is deployed with this chart. I don't see any reason why `additionalServiceMonitors` would be given otherwise. (This chart is hopefully not used as a delivery mechanism for deploying service monitors that are targeting _other_ prometheus instances _not_ delivered by this chart.

### What's your helm version?

version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:04:34Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

35.3.1

### What happened?

the `additionalServiceMonitors` are given default chart labels

### What you expected to happen?

the `additionalServiceMonitors` to be given the `serviceMonitorSelector` labels

### Enter the changed values of values.yaml?

```yaml
prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        prometheus: xx
  additionalServiceMonitors:
    - name: argocd-metrics
      namespace: argocd
      selector:
        matchLabels:
          app.kubernetes.io/name: argocd-metrics
      namespaceSelector:
        matchNames:
          - argocd
      endpoints:
        - port: metrics
```

### Enter the command that you execute and failing/misfunctioning.

helm install my-release prometheus-community/kube-prometheus-stack
