### ISSUE TITLE
[prometheus-kube-stack] Unable to enable sigv4 in remoteWrite

### ISSUE THREAD

**Issue by vishnu-anil** [prometheus-community/helm-charts#2164]
### Describe the bug a clear and concise description of what the bug is.

I am trying to enable sigv4 support to enable remotewrite to AWS Managed prometheus workspace from Prometheus server installed in EKS cluster.

When using the values.yaml given below I get the below error:
```
 Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Prometheus.spec.remoteWrite[0]): unknown field "sigv4" in com.coreos.monitoring.v1.Prometheus.spec.remoteWrite
│ 
```

My values.yaml
```
prometheus:
  prometheusSpec: %{ if external_prometheus }
    remoteWrite:
    - url: https://aps-workspaces.${aws_region}.amazonaws.com/workspaces/${workspace_id}/api/v1/remote_write
      sigv4:
        region: ${aws_region}
        roleArn: ${prometheus_ingestion_iamrole_arn}         
    externalLabels:
      AWS_Environment: ${environment}
    %{ endif }
    retention: 180d
    tolerations:
    - key: "taint"
      operator: "Equal"
      value: "monitoring"
      effect: "NoExecute"
    storageSpec: 
     volumeClaimTemplate:
       spec:
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 100Gi
  serviceAccount:
    create: true
    name: amp-iamproxy-ingest-service-account
    annotations: 
      eks.amazonaws.com/role-arn: ${prometheus_ingestion_iamrole_arn}   
```

### What's your helm version?

v3.8.2

### What's your kubectl version?

1.22

### Which chart?

prometheus-kube-stack

### What's the chart version?

36.0.2

### What happened?

My values.yaml looks like below

```
prometheus:
  prometheusSpec: %{ if external_prometheus }
    remoteWrite:
    - url: https://aps-workspaces.${aws_region}.amazonaws.com/workspaces/${workspace_id}/api/v1/remote_write
      sigv4:
        region: ${aws_region}
        roleArn: ${prometheus_ingestion_iamrole_arn}         
    externalLabels:
      AWS_Environment: ${environment}
    %{ endif }
    retention: 180d
    tolerations:
    - key: "taint"
      operator: "Equal"
      value: "monitoring"
      effect: "NoExecute"
    storageSpec: 
     volumeClaimTemplate:
       spec:
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 100Gi
  serviceAccount:
    create: true
    name: amp-iamproxy-ingest-service-account
    annotations: 
      eks.amazonaws.com/role-arn: ${prometheus_ingestion_iamrole_arn}   
```

When applying I get the below error:
```
 Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Prometheus.spec.remoteWrite[0]): unknown field "sigv4" in com.coreos.monitoring.v1.Prometheus.spec.remoteWrite
│ 
```

### What you expected to happen?

Helm installation completes error free

### How to reproduce it?

Use the values file below with latest version of the kube-prometheus helm chart

```
prometheus:
  prometheusSpec: %{ if external_prometheus }
    remoteWrite:
    - url: https://aps-workspaces.${aws_region}.amazonaws.com/workspaces/${workspace_id}/api/v1/remote_write
      sigv4:
         region: ${aws_region}
         roleArn: ${prometheus_ingestion_iamrole_arn}         
    externalLabels:
      AWS_Environment: ${environment}
    %{ endif }
    retention: 180d
    tolerations:
    - key: "taint"
      operator: "Equal"
      value: "monitoring"
      effect: "NoExecute"
    storageSpec: 
     volumeClaimTemplate:
       spec:
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 100Gi
  serviceAccount:
    create: true
    name: amp-iamproxy-ingest-service-account
    annotations: 
      eks.amazonaws.com/role-arn: ${prometheus_ingestion_iamrole_arn}   
```

### Enter the changed values of values.yaml?

```
prometheus:
  prometheusSpec: %{ if external_prometheus }
    remoteWrite:
    - url: https://aps-workspaces.${aws_region}.amazonaws.com/workspaces/${workspace_id}/api/v1/remote_write
      sigv4:
        region: ${aws_region}
        roleArn: ${prometheus_ingestion_iamrole_arn}         
    externalLabels:
      AWS_Environment: ${environment}
    %{ endif }
    retention: 180d
    tolerations:
    - key: "taint"
      operator: "Equal"
      value: "monitoring"
      effect: "NoExecute"
    storageSpec: 
     volumeClaimTemplate:
       spec:
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 100Gi
  serviceAccount:
    create: true
    name: amp-iamproxy-ingest-service-account
    annotations: 
      eks.amazonaws.com/role-arn: ${prometheus_ingestion_iamrole_arn}   
```

### Enter the command that you execute and failing/misfunctioning.

Its applied via terraform
