### ISSUE TITLE
[prometheus-kube-stack] Alertmanager in Sharded Prometheus

### ISSUE THREAD

**Issue by TomHellier** [prometheus-community/helm-charts#2168]
### Describe the bug a clear and concise description of what the bug is.

I'm investigating using AlertManager to collect alerts fired by prometheus instances running inside kubernetes clusters.

There are a lot of targets running inside my kubernetes cluster, and I target them using a scrape config which uses service discovery via annotations applied to kubernetes pods / services.

I've had to shard the prometheus to reduce the load on each individual instance, but this has given me some problems using Alerts generated by those prometheus instances.

For example:
* 3 instances of prometheus, scraping for the metric "ceph_health_status"
* Due to sharding, one one of those prometheus shard instances can actually see "ceph_health_status"
* The two other prometheus shard instances cannot see the metric "ceph_health_status", so they are generating alerts because there is not the expected metric name
* The AlertManager is receving the alerts from the two shards which cannot see the metric, and triggering AlertManager.

I use a thanos to aggregate these shards, and provide compaction so I can store metrics for longer, I can see that I could use alerts defined in Thanos Ruler to provide cluster level monitoring, but would rather use Prometheus->AlertManager->Pager than Prometheus->Thanos->ThanosRuler->AlertManager->Pager

Is this a known limitation of prometheus-kube-stack when using shards?

### What's your helm version?

3.7.1

### What's your kubectl version?

1.21

### Which chart?

kube-prometheus-stack

### What's the chart version?

16.12.1

### What happened?

Alerts were triggered by prometheus instances which, due to sharding, could not view the metric

### What you expected to happen?

AlertManager / Prometheus would provide some configuration to cope with sharding

### How to reproduce it?

Shard Prometheus using

```
    prometheusSpec:
      replicas: 2
      shards: 3

additionalScrapeConfigs
        - job_name: 'kubernetes-service-endpoints'
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [__address__]
              target_label: __tmp_hash
              modulus: 3  # must equal the shards
              action: hashmod
            - source_labels: [__tmp_hash]
              regex: $(SHARD)
              action: keep
```

Configure an AlertManager with following PrometheusRule
```
      groups:
        - name: ceph-cluster.rules
          rules:
            - alert: CephClusterStatus
              annotations:
                message: The Ceph Cluster is currently unhealthy
              expr: max(ceph_health_status) > 0 or absent(ceph_health_status)
              for: 1m
              labels:
                severity: critical
```

Only one of the shards persists the metric generated by the target which produces "ceph_health_status", and therefore, the other two shards start firing alerts at the AlertManager

### Enter the command that you execute and failing/misfunctioning.

n/a
