### ISSUE TITLE
[blackbox-exporter I ignored

### ISSUE THREAD

**Issue by mbaykara** [prometheus-community/helm-charts#2173]
### Describe the bug a clear and concise description of what the bug is.

I am monitoring ssl certificates including self-signed one, but the black box exporter ignore self-signed certificates. So the certificates that issued by trusted CA are will be monitored if ssl approach to expire but no metrics for self-signed certs.

### What's your helm version?

3. 9.0

### What's your kubectl version?

1.21.7

### Which chart?

prometheus-blackbox-exporter

### What's the chart version?

5.0.3

### What happened?

do not observe url with self-signed cert

### What you expected to happen?

send metrics if a self signed cert expire

### How to reproduce it?

with self signed certificate

### Enter the changed values of values.yaml?

```
USER-SUPPLIED VALUES:
prometheusRule:
  additionalLabels:
    app: kube-prometheus-stack
    release: prometheus
  enabled: true
  namespace: monitoring
  rules:
  - alert: SSLCertExpiringIn30Days
    annotations:
      description: 'SSL Certificate Expires:  {{ `{{` }} $value | humanizeDuration
        }}'
      summary: The tls certificate of  {{ `{{` }} $labels.instance }}  will expire
        in {{ `{{` }} $value | humanizeDuration }}. Please be aware of.
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
    for: 0m
    labels:
      ruleType: ssl
      severity: warning
      tls: internal
  - alert: SSLCertExpiringIn7Days
    annotations:
      description: 'SSL Certificate Expires:  {{ `{{` }} $value | humanizeDuration
        }}'
      summary: The tls certificate of  {{ `{{` }} $labels.instance }}  will expire
        in {{ `{{` }} $value | humanizeDuration }}. Please be aware of.
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
    for: 0m
    labels:
      ruleType: ssl
      severity: critical
      tls: internal
  - alert: Watchdog
    annotations:
      description: |
        This is an alert meant to ensure that the entire alerting pipeline is functional.
        This alert is always firing, therefore it should always be firing in Alertmanager
        and always fire against a receiver. There are integrations with various notification
        mechanisms that send a notification when this alert is not firing. For example the
        "DeadMansSnitch" integration in PagerDuty.
      summary: An alert that should always be firing to certify that Alertmanager
        is working properly.
    expr: vector(1)
    for: 0m
    labels:
      ruleType: ssl
      severity: none
      tls: internal
      type: Watchdog
serviceMonitor:
  bearerTokenFile: null
  defaults:
    additionalMetricsRelabels:
      app: blackbox-exporter-prometheus-blackbox-exporter:9115
      release: prometheus
    interval: 30s
    labels:
      app: blackbox-exporter-prometheus-blackbox-exporter:9115
      release: prometheus
    module: http_2xx
    scrapeTimeout: 30s
  enabled: true
  scheme: http
  targets:
  - labels:
      app: blackbox-exporter-prometheus-blackbox-exporter
      release: prometheus
    name: mydomain
    url: https://mydomain.com
```

### Enter the command that you execute and failing/misfunctioning.

helm install blackbox-exporter -f values.yml  prometheus-blackbox-exporter --version 5.0.3
