### ISSUE TITLE
[kube-prometheus-stack]

### ISSUE THREAD

**Issue by astropanic** [prometheus-community/helm-charts#2177]
### Describe the bug a clear and concise description of what the bug is.

I'm not able to turn the remote write API on. `/api/v1/receive` returns an HTTP 404 code.

I can't manage to pass the argument `--web.enable-remote-write-receiver` to the deployment of the `kube-prometheus-stack-operator` which seems to be necessary. Following the [docs](https://prometheus.io/docs/prometheus/latest/feature_flags/):

> Remote Write Receiver
--enable-feature=remote-write-receiver
The remote write receiver allows Prometheus to accept remote write requests from other Prometheus servers. More details can be found [here](https://prometheus.io/docs/prometheus/latest/storage/#overview).
Activating the remote write receiver via a feature flag is deprecated. Use --web.enable-remote-write-receiver instead. This feature flag will be ignored in future versions of Prometheus.

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5-gke.2400", GitCommit:"edad26ea7e78d44536b547193f30209b03e954c9", GitTreeState:"clean", BuildDate:"2022-04-15T09:31:56Z", GoVersion:"go1.17.8b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

33.2.1

### What happened?

I'm missing the `--web.enable-remote-write-receiver` argument passed in the deployment `kube-prometheus-stack-operator`.

The `/api/v1/receive` is returing an 404 HTTP status code.

```
 k get deployment -n monitoring kube-prometheus-stack-operator -o yaml | k neat
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 33.2.1
    chart: kube-prometheus-stack-33.2.1
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-stack-operator
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-prometheus-stack-operator
      release: kube-prometheus-stack
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-prometheus-stack-operator
        app.kubernetes.io/instance: kube-prometheus-stack
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 33.2.1
        chart: kube-prometheus-stack-33.2.1
        heritage: Helm
        release: kube-prometheus-stack
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kube-prometheus-stack-kubelet
        - --localhost=127.0.0.1
        - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.54.1
        - --config-reloader-cpu-request=100m
        - --config-reloader-cpu-limit=100m
        - --config-reloader-memory-request=50Mi
        - --config-reloader-memory-limit=50Mi
        - --thanos-default-base-image=quay.io/thanos/thanos:v0.24.0
        - --web.enable-tls=true
        - --web.cert-file=/cert/cert
        - --web.key-file=/cert/key
        - --web.listen-address=:10250
        - --web.tls-min-version=VersionTLS13
        image: quay.io/prometheus-operator/prometheus-operator:v0.54.1
        imagePullPolicy: IfNotPresent
        name: kube-prometheus-stack
        ports:
        - containerPort: 10250
          name: https
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cert
          name: tls-secret
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccount: kube-prometheus-stack-operator
      serviceAccountName: kube-prometheus-stack-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tls-secret
        secret:
          defaultMode: 420
          secretName: kube-prometheus-stack-admission 
```

### What you expected to happen?

I expect the `/api/v1/receive` is working, allowing me to use prometheus in agent mode to write to this endpoint.

### How to reproduce it?

```
cat  <<EOF > ./values.yaml
prometheus:
  prometheusSpec:
    enableFeatures:
    - remote-write-receiver
    enableRemoteWriteReceiver: true
EOF

helm install bugfix prometheus-community/kube-prometheus-stack --version 33.2.1 --values ./values.yml

kubectl get deployment bugfix-kube-prometheus-stack-operator -o yaml | grep enable-remote-write-receiver || echo "argument not found"

kubectl port-forward svc/bugfix-kube-prometheus-stack-prometheus 9090:9090

curl -sI localhost:9090/api/v1/receive
```

### Enter the changed values of values.yaml?

```
prometheus:
  prometheusSpec:
    enableFeatures:
    - remote-write-receiver
    enableRemoteWriteReceiver: true
  service:
    annotations:
      cloud.google.com/neg: '{"ingress": true}'
```

### Enter the command that you execute and failing/misfunctioning.

```
kubectl port-forward svc/bugfix-kube-prometheus-stack-prometheus 9090:9090

curl -sI localhost:9090/api/v1/receive
```
