### ISSUE TITLE
[kube-prometheus-stack] Grafana persistence parameters missing in values.yaml

### ISSUE THREAD

**Issue by MarkusBauerBE** [prometheus-community/helm-charts#2178]
### Is your feature request related to a problem ?

As it stands the official values.yaml for the kube-prometheus-stack does not contain the persistence parameters for Grafana (aka it isn't officially documented how you tell Grafana to go ahead and grab a PVC, even though this option exists). Through googling I found the following:

```
grafana:
    persistence:
      enabled: True
      type: pvc
      storageClassName: <storageClassNameHere>
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      finalizers:
        - kubernetes.io/pvc-protection
``` 
Now I am not sure if this is already deprecated or if there is any other reason why this isn't included in the values.yaml but as it stands, this is missing in the kube-prometheus-stack values.yaml
Either way it definitely does work - in that it leads to Grafana requesting a PVC - and it was at least a topic in another issue - unfortunately I don't have the issue number at hand for reference. 

### Describe the solution you'd like.

If there is no reason speaking against it i'd like to add this setting to the official values.yaml as a comment.

### Describe alternatives you've considered.

Alternatively this could (and should) be added to the official documentation about storage for kube-prom-stack.
