### ISSUE TITLE
[kube-prometheus-stack] if `loki-stack` helm chart is present only `loki` data source is created in Grafana

### ISSUE THREAD

**Issue by yellowhat** [prometheus-community/helm-charts#2191]
### Describe the bug a clear and concise description of what the bug is.

Hi,
I would like to deploy the `kube-prometheus-stack` and `loki-stack` helm charts with grafana enabled.
If I deploy the `loki-stack` helm chart before the `kube-prometheus-stack`, grafana will automatically create only the `loki` data source but not the `prometheus` one.
Instead if I deploy only the `kube-prometheus-stack` helm chart it will create the `prometheus` data source as expected.

Any ideas?

Thanks

### What's your helm version?

v3.9.0

### What's your kubectl version?

v1.22.11

### Which chart?

kube-prometheus-stack

### What's the chart version?

36.0.3

### Enter the changed values of values.yaml?

```yaml
grafana:
  adminPassword: brKQMobb
  adminUser: admin
  ingress:
    annotations:
      acme.cert-manager.io/http01-edit-in-place: "true"
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    enabled: true
    hosts:
    - <hostname>
    tls:
    - hosts:
      - <hostname>
      secretName: tls-grafana
```

### Enter the command that you execute and failing/misfunctioning.

```bash
$ helm upgrade --install loki --version 2.6.5 --namespace monitoring grafana/loki-stack
$ helm upgrade --install prometheus --version 36.0.3 --namespace monitoring prometheus/kube-prometheus-stack -f values.yaml
```

**Comment by yellowhat** [comment]
With the update `36.2.0`, if I deploy with this `values.yaml`:

```yaml
grafana:
  adminPassword: brKQMobb
  adminUser: admin
  ingress:
    annotations:
      acme.cert-manager.io/http01-edit-in-place: "true"
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    enabled: true
    hosts:
    - <hostname>
    tls:
    - hosts:
      - <hostname>
      secretName: tls-grafana
```
It will automatically create the `prometheus` data source as expected.

Instead if I use:

```yaml
grafana:
  additionalDataSources:
  - access: proxy
    isDefault: false
    name: loki
    orgId: 1
    type: loki
    url: http://<loki_service_name>:3100
    version: 1
  adminPassword: HpXFiOVp
  adminUser: admin
  ingress:
    annotations:
      acme.cert-manager.io/http01-edit-in-place: "true"
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    enabled: true
    hosts:
    - <hostname>
    tls:
    - hosts:
      - <hostname>
      secretName: tls-grafana
```

It will automatically create the `prometheus` (default) and `loki` data sources as expected.

Thanks
