### ISSUE TITLE
prometheus-kube-stack: unable to add additionalScrapeConfigs

### ISSUE THREAD

**Issue by RakeshNagarajan** [prometheus-community/helm-charts#2192]
### Describe the bug a clear and concise description of what the bug is.

Values.yaml file pasted below
```
prometheus:
  enabled: true # true by default
  service:
    type: NodePort  
    nodePort: 30090
  prometheusSpec:
    additionalScrapeConfigs: 
  - job_name: 'blackbox-https'
    scrape_timeout: 15s
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
    - targets:
        - https://example.com
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: prometheus-blackbox-exporter:9115
```

Error message i got while deploying 
```
Error: INSTALLATION FAILED: PrometheusRule.monitoring.coreos.com "kube-prometheus-stack-1" is invalid: spec.groups: Invalid value: "null": spec.groups in body must be of type array: "null"
```

So the fix should be somewhere here 
https://github.com/prometheus-community/helm-charts/blob/09534e674f1fc2015a84e1ca268e09214a8bc347/charts/kube-prometheus-stack/templates/prometheus/additionalPrometheusRules.yaml#L38-L39 

### What's your helm version?

v3.7.2

### What's your kubectl version?

v1.23.1

### Which chart?

prometheus-kube-stack

### What's the chart version?

15.4.3

### What happened?

I am trying to add 'additionalScrapeConfigs' in my values file and its not adding for any target

### Enter the command that you execute and failing/misfunctioning.

helm install staging-monitoring-prometheus-community prometheus-community/kube-prometheus-stack --values prometheus-community.yaml
