### ISSUE TITLE
[prometheus-kube-stack] `alertmanager.config` isn't mounted to the alertmanager pod

### ISSUE THREAD

**Issue by YuKitsune** [prometheus-community/helm-charts#2193]
### Describe the bug a clear and concise description of what the bug is.

When customising the configuration using the `alertmanager.config` value, the specified config is not mounted in the alertmanager pod.

### What's your helm version?

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11", GitCommit:"38d3c1f3d5306401bcf39a71bad3b5a5106033d7", GitTreeState:"clean", BuildDate:"2022-03-16T14:02:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

36.2.0

### What happened?

Two secrets get created, `alertmanager-prometheus-stack-kube-prom-alertmanager`, and `alertmanager-prometheus-stack-kube-prom-alertmanager-generated`.

The `alertmanager-prometheus-stack-kube-prom-alertmanager` secret contains my custom config options.
The `alertmanager-prometheus-stack-kube-prom-alertmanager-generated` secret doesn't contain my config.

The alertmanager pod has the `alertmanager-prometheus-stack-kube-prom-alertmanager-generated` secret mounted, and the secret with my custom confit isn't mounted anywhere.

### What you expected to happen?

I would expect the secret with my custom config to take precedence over the `-generated` one.

### How to reproduce it?

**values.yaml**:
```yaml
alertmanager:
  config:
    receivers:
      - name: 'MyReceiverName'
        webhook_configs:
          - url: 'MyWebhookReceiverUrl'
```

```
helm upgrade --install prometheus-stack prometheus-community/kube-prometheus-stack -f ./values.yaml --namespace monitoring
```

### Enter the changed values of values.yaml?
```yaml
alertmanager:
  config:
    receivers:
      - name: 'MyReceiverName'
        webhook_configs:
          - url: 'MyWebhookReceiverUrl'
```

### Enter the command that you execute and failing/misfunctioning.

```
helm upgrade --install prometheus-stack prometheus-community/kube-prometheus-stack -f ./values.yaml --namespace monitoring
```

**Comment by YuKitsune** [comment]
I've managed to find an alternative to this.
Instead of using `alertmanager.config`, I'm now using `alertmanager.alertmanagerSpec.alertmanagerConfiguration` and targeting a custom resource definition.

Example:

```yaml
# receiver-config.yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: monitoring
spec:
  receivers:
    - name: '<receiver name>'
      webhookConfigs:
        - url: '<webhook url>'

  route:
    receiver: '<receiver name>'
```

```yaml
# values.yaml
alertmanager:
  alertmanagerSpec:
    alertmanagerConfiguration:
      name: alertmanager-config
...
```

This seems to work as expected, but looking at the CRD, this seems experimental.
This also makes me question what the point of `alertmanager.config` is, and how it's supposed to be used.

**Comment by Lp-Francois** [comment]
Hello, Same bug here this values in my helm chart:

```yaml
    alertmanager:
      enabled: true
      config:
        route:
          group_by: ['job']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: 'null'
          routes:
            - match:
              alertname: heartbeat
              receiver: 'amixr-heartbeat'
              group_wait: 0s
              group_interval: 1m
              repeat_interval: 50s
            - match:
              alertname: Watchdog
              receiver: 'null'
            - receiver: 'grafana_oncall'
              group_by: [job]
        receivers:
          - name: 'grafana_oncall'
            webhook_configs:
            - url: https://xxxxxxxxxxxx
              send_resolved: true
          - name: 'amixr-heartbeat'
            webhook_configs:
              - url: https://xxxxxxxxxxx
                send_resolved: false
```

And 2 secrets are created:
- alertmanager-monitoring-kube-prometheus-alertmanager (with the custom config added in the helm chart)
- alertmanager-monitoring-kube-prometheus-alertmanager-generated (without the new config)

In the volumes mounted, I can only find the generated one:

```yaml
     volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager/config
        ...
```

`config-volume` being the generated secret:

```yaml
  volumes:
    - name: config-volume
      secret:
        secretName: alertmanager-monitoring-kube-prometheus-alertmanager-generated
        defaultMode: 420
```

I am also using the AlertManagerConfig as a workaround, but [not stable](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/design.md#alertmanagerconfig) as stated before by @YuKitsune  :(
