### ISSUE TITLE
[kube-prometheus-stack] cannot add the external nodes as targets to prometheus

### ISSUE THREAD

**Issue by ikozar** [prometheus-community/helm-charts#2195]
### Describe the bug a clear and concise description of what the bug is.

I triied to set up  value "endpoints" in "charts/prometheus-node-exporter/values.yaml", to add IP node_exporter deployed outside of the cluster, but it doesn't work

I was able to add an external node export after applying the following endpoint
```
apiVersion: v1
kind: Endpoints
metadata:
  name: my-prometeus-prometheus-node-exporter
  namespace: monitoring
  labels:
    app: prometheus-node-exporter
    heritage: Helm
    release: my-prometeus
    chart: prometheus-node-exporter-3.3.0
subsets:
  - addresses:
      - ip: <minikube node IP>
      - ip: <external IP>
    ports:
      - name: http-metrics
        port: 9100
        protocol: TCP
```
it made possible to getting metrics from external node too, but after some time the external IP was lost

### What's your helm version?

version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"windows/386"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

36.2.0

### How to reproduce it?

deploy node_exporter on server outside of the cluster and add its IP in "endpoints" of "charts/prometheus-node-exporter/values.yaml"

### Enter the changed values of values.yaml?

endpoints: ["192.168.0.123"]

### Enter the command that you execute and failing/misfunctioning.

helm install my-prometeus prometheus-community/kube-prometheus-stack -f .\charts\prometheus-node-exporter\values.yaml -n monitoring
