### ISSUE TITLE
[prometheus-kube-stack] admission-webhooks last-applied-configuration missing

### ISSUE THREAD

**Issue by via-justa** [prometheus-community/helm-charts#2196]
### Describe the bug a clear and concise description of what the bug is.

Deploying the chart via ArgoCD produces an error `resource clusterroles/<deployment name>-admission is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by apply` for all the admission jobs
```
clusterrole.rbac.authorization.k8s.io/prometheus-stack-kube-prom-admission reconciled. reconciliation required create missing rules added: {Verbs:[get update] APIGroups:[admissionregistration.k8s.io] Resources:[validatingwebhookconfigurations mutatingwebhookconfigurations] ResourceNames:[] NonResourceURLs:[]}. clusterrole.rbac.authorization.k8s.io/prometheus-stack-kube-prom-admission configured. Warning: resource clusterroles/prometheus-stack-kube-prom-admission is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by apply. apply should only be used on resources created declaratively by either create --save-config or apply. The missing annotation will be patched automatically.
clusterrolebinding.rbac.authorization.k8s.io/prometheus-stack-kube-prom-admission reconciled. reconciliation required create missing subjects added: {Kind:ServiceAccount APIGroup: Name:prometheus-stack-kube-prom-admission Namespace:monitoring-agents}. clusterrolebinding.rbac.authorization.k8s.io/prometheus-stack-kube-prom-admission configured. Warning: resource clusterrolebindings/prometheus-stack-kube-prom-admission is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by apply. apply should only be used on resources created declaratively by either create --save-config or apply. The missing annotation will be patched automatically.
role.rbac.authorization.k8s.io/prometheus-stack-kube-prom-admission reconciled. reconciliation required create missing rules added: {Verbs:[get create] APIGroups:[] Resources:[secrets] ResourceNames:[] NonResourceURLs:[]}. role.rbac.authorization.k8s.io/prometheus-stack-kube-prom-admission configured. Warning: resource roles/prometheus-stack-kube-prom-admission is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by apply. apply should only be used on resources created declaratively by either create --save-config or apply. The missing annotation will be patched automatically.
rolebinding.rbac.authorization.k8s.io/prometheus-stack-kube-prom-admission reconciled. reconciliation required create missing subjects added: {Kind:ServiceAccount APIGroup: Name:prometheus-stack-kube-prom-admission Namespace:monitoring-agents}. rolebinding.rbac.authorization.k8s.io/prometheus-stack-kube-prom-admission configured. Warning: resource rolebindings/prometheus-stack-kube-prom-admission is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by apply. apply should only be used on resources created declaratively by either create --save-config or apply. The missing annotation will be patched automatically.
```
searching the issues on the repo I only found references to the CRDs that I deployed as mentioned in the documentation.

### What's your helm version?

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/arm64"}

### Which chart?

kibe-prometheus-stack

### What's the chart version?

35.0.3

### What happened?

Updating the chart configuration via ArgoCD produces an endless sync status due to the pre-sync hooks unable to complete. 
![image](https://user-images.githubusercontent.com/25720282/175886708-bf0d3872-43bc-4503-ae60-646892d18fb5.png)

### What you expected to happen?

Admission hooks finish successfully

### How to reproduce it?

Deploy kibe-prometheus-stack with default admission settings via ArgoCD

### Enter the changed values of values.yaml?

<details>
  <summary>Click to expand!</summary>
  
    defaultRules:
      create: true
      rules:
        alertmanager: true
        etcd: false
        configReloaders: true
        general: true
        k8s: true
        kubeApiserver: true
        kubeApiserverAvailability: true
        kubeApiserverSlos: true
        kubelet: true
        kubeProxy: false
        kubePrometheusGeneral: true
        kubePrometheusNodeRecording: true
        kubernetesApps: false
        kubernetesResources: true
        kubernetesStorage: true
        kubernetesSystem: true
        kubeScheduler: false
        kubeStateMetrics: true
        network: true
        node: true
        nodeExporterAlerting: true
        nodeExporterRecording: true
        prometheus: true
        prometheusOperator: true
      additionalRuleLabels:
        cloud: gcp
        env: staging
  
    kube-state-metrics:
      prometheus:
        monitor:
          enabled: true
          honorLabels: true
          additionalLabels:
            cluster: staging-application-cluster
            release: kube-prometheus-stack
            env: staging
  
    alertmanager:
      enabled: true
      extraSecret:
        name: alertmanager-auth
        data:
          auth: <path:kv/data/infrastructure/monitoring/alertmanager#grafana_basic_auth_htpassword>
      alertmanagerSpec:
        replicas: 2
  
        storage:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 30Gi
  
      config:
        global:
          slack_api_url: '<path:kv/data/infrastructure/monitoring/alertmanager#slack_api_url>'
  
        receivers:
          - ...
  
        route:
          group_by: ['alertname', 'severity']
          group_wait: 10s
          group_interval: 5m
          receiver: "slack-staging-sre"
          repeat_interval: 3h
  
          routes:
            - ...
  
          inhibit_rules:
            - source_matchers: [severity="critical"]
              target_matchers: [severity="warning"]
            
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-issuer"
          external-dns.alpha.kubernetes.io/hostname: ****
          external-dns.alpha.kubernetes.io/ttl: "120"
          nginx.ingress.kubernetes.io/auth-type: "basic"
          nginx.ingress.kubernetes.io/auth-secret: "alertmanager-auth"
        hosts:
          - ****
  
        tls:
          - secretName: alertmanager-general-tls
            hosts:
              - ****
  
    prometheus:
      thanosServiceExternal:
        enabled: true
        loadBalancerIP: <path:kv/data/infrastructure/clusters/application#ingress>
  
      prometheusSpec:
        externalLabels: 
          cloud: gcp
          env: staging
</details>

### Enter the command that you execute and failing/misfunctioning.

Installed via ArgoCD
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-agents
  project: monitoring-agents
  source:
    path: charts/monitoring/kube-prometheus-stack
    repoURL: https://github.com/****
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: ARGOCD_APP_NAMESPACE
          value: $ARGOCD_APP_NAMESPACE
        - name: HELM_ARGS
          value: -f ../../../staging-application-cluster/monitoring-agents/kube-prometheus-stack.yaml --skip-crds
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
```
