### ISSUE TITLE
[prometheus-redis-exporter] support multiple targets

### ISSUE THREAD

**Issue by LeoQuote** [prometheus-community/helm-charts#2198]
### Is your feature request related to a problem ?

Now redis-exporter has supported multiple target, through `/scrape` https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts 

```
scrape_configs:
  ## config for the multiple Redis targets that the exporter will scrape
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://first-redis-host:6379
        - redis://second-redis-host:6379
        - redis://second-redis-host:6380
        - redis://second-redis-host:6381
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <<REDIS-EXPORTER-HOSTNAME>>:9121

  ## config for scraping the exporter itself
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - <<REDIS-EXPORTER-HOSTNAME>>:9121
```
This could be useful when we have many redis to scrape and only want one single exporter

### Describe the solution you'd like.

We can render multiple service monitor like blackbox exporter did in the chart https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml 

### Describe alternatives you've considered.

NONE
