### ISSUE TITLE
[prometheus-<any>-exporter] Request to introduce Static configs to allow additional label for all metrics

### ISSUE THREAD

**Issue by vishnu-anil** [prometheus-community/helm-charts#2221]
### Is your feature request related to a problem ?

Yes. I am trying to add the below so as to have a label added to all the metrics from the exporter
```
      - job_name: serviceMonitor/monitoring/redis-exporter-prometheus-redis-exporter/0
        static_configs:
          - labels:
              environment: myenv
```

I do not see an option enabled to allow job creation with static configs

### Describe the solution you'd like.

I would like to enable static configs or any other mechanism to add new label to all the metrics scraped for the exporter jobs

### Describe alternatives you've considered.

Nothing so far
