### ISSUE TITLE
[kube-prometheus-stack] contact points help needed

### ISSUE THREAD

**Issue by ox7a59** [prometheus-community/helm-charts#2223]
### Describe the bug a clear and concise description of what the bug is.

There's no documentation or example of how to add contact points for Grafana and configure alertmanager through yaml values file.

### What's your helm version?

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"archive", BuildDate:"2022-06-18T07:33:51Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

36.2.1

### What happened?

I do not known how to create contact points that will survive pod restarting and provide possibility of IaC storing.

### Enter the command that you execute and failing/misfunctioning.

```bash
helm install prometheus-stack prometheus-community/kube-prometheus-stack
```

**Comment by aDingil** [comment]
You have override values for the grafana chart which is a dependecy for kube-prometheus
[Link](https://artifacthub.io/packages/helm/grafana/grafana?modal=values)
Here is an example for slack
```yaml
    alerting:
      contactpoints.yaml: 
        apiVersion: 1
        contactPoints:
          - orgId: 1
            name: 
            receivers:
              - uid: provisioned_uid_3
                type: slack
                settings:
                  recipient: 
                  username: 
                  # token can be left empty
                  token: ""
                  url: 
```

If you want to set up another provider you have to track the payload while creating it over the gui
