### ISSUE TITLE
[kube-prometheus-stack] invalid Yaml document separator: null

### ISSUE THREAD

**Issue by Moep90** [prometheus-community/helm-charts#2239]
### Describe the bug a clear and concise description of what the bug is.

I'm unable to deploy the kube-prometheus-stack because it renders with a `--- null` in at least five occasions

### What's your helm version?

helm version version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: v1.24.2 Kustomize Version: v4.5.4 Server Version: v1.21.12

### Which chart?

kube-prometheus-stack

### What's the chart version?

36.2.1

### What happened?

After rendering the chart I get 
```
$ kubectl apply --recursive -f compiled/...../kube-prometheus-stack.yml
error: error parsing compiled/...../kube-prometheus-stack.yml: invalid Yaml document separator: null
```

This is caused by every occasion of:
```yaml
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: []
  storedVersions: []
--- null <----- THIS causes the issue
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
```

### What you expected to happen?

The output should look like this:
```yaml
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: []
  storedVersions: []
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
```

### How to reproduce it?

Render the Chart using the following values below

### Enter the changed values of values.yaml?
```yaml
alertmanager:
  enabled: false
  podAntiAffinityTopologyKey: kubernetes.io/hostname
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
coreDns:
  enabled: true
defaultRules:
  create: false
  rules:
    alertmanager: true
    configReloaders: true
    etcd: true
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubeProxy: true
    kubeScheduler: true
    kubeStateMetrics: true
    kubelet: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true
global:
  rbac:
    create: true
    pspEnabled: true
grafana:
  enabled: false
  serviceMonitor:
    interval: 30s
    scheme: http
    scrapeTimeout: 30s
    tlsConfig: {}
kubeApiServer:
  enabled: true
  tlsConfig:
    insecureSkipVerify: false
    serverName: kubernetes
kubeControllerManager:
  enabled: true
kubeEtcd:
  enabled: true
kubeProxy:
  enabled: true
kubeScheduler:
  enabled: true
kubelet:
  enabled: true
  namespace: kube-system
nameOverride: kube-prometheus-stack
namespaceOverride: monitoring
prometheus:
  enabled: true
  prometheusSpec:
    logFormat: json
    logLevel: info
    podAntiAffinityTopologyKey: kubernetes.io/hostname
    resources:
      limit:
        memory: 2048Mi
    retention: 2h
    shards: null
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: ceph-block
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccount:
    create: true
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
prometheusOperator:
  admissionWebhooks:
    enabled: false
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  enabled: true
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 1m
    memory: 1Mi
  resources: null
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
  serviceAccount:
    create: true
logformat: json
loglevel: info
namespace: monitoring
persistence:
retention:
  size: '10'
  time: 2h
storageclass: ceph-block
```
### Enter the command that you execute and failing/misfunctioning.
```
helm template my-release prometheus-community/kube-prometheus-stack --values values.yml
```
