### ISSUE TITLE
[prometheus-kube-stack] Additional datasource are not added to configmap correctly

### ISSUE THREAD

**Issue by lusu007** [prometheus-community/helm-charts#2251]
### Describe the bug a clear and concise description of what the bug is.

If I add an additional data source via `values.yaml` to Grafana the configured data source doesn't show up in Grafana.
I checked `kube-prometheus-stack-grafana-datasource` configmap and the additional data source is missing there too. 

Furthermore, I get the following error message in the logs of the pod running Grafana:
```
logger=provisioning t=2022-07-07T20:39:27.2826172Z level=error msg="Failed to provision data sources" error="Datasource provisioning error: datasource.yaml config is invalid. Only one datasource per organization can be marked as default"
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-07-07T20:39:27.2827584Z level=error msg= error="Datasource provisioning error: datasource.yaml config is invalid. Only one datasource per organization can be marked as default" remote_addr=[::1] traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-07-07T20:39:27.2829082Z level=error msg="Request Completed" method=POST path=/api/admin/provisioning/datasources/reload status=500 remote_addr=[::1] time_ms=11 duration=11.7521ms size=80 referer= traceID=00000000000000000000000000000000
```

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.4 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-23T22:20:14Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

36.2.1

### What happened?

Only the Prometheus data source shows up in Grafana.

### What you expected to happen?

Both data sources should show up in Grafana.

### How to reproduce it?

1. Deploy loki-stack
```bash
helm repo add grafana https://grafana.github.io/helm-charts && run helm repo update grafana
helm upgrade -i loki -n monitoring --create-namespace grafana/loki-stack
```
3. Deploy prometheus-stack with `values.yaml` given below
```bash
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && run helm repo update prometheus-community
helm upgrade -i kube-prometheus-stack -n monitoring --create-namespace prometheus-community/kube-prometheus-stack -f values.yaml
```

### Enter the changed values of values.yaml?

```yaml
grafana:
  defaultDashboardsTimezone: Europe/Berlin
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.placeholder.net
  additionalDatasources:
    - name: Loki
      type: loki
      isDefault: false
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
      version: 1
prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.placeholder.net
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade -i kube-prometheus-stack -n monitoring --create-namespace prometheus-community/kube-prometheus-stack -f values.yaml

### Anything else we need to know?

Seems similar to #2191
