### ISSUE TITLE
How to add persistent plugins in prometheus-stack grafana

### ISSUE THREAD

**Issue by urbaman** [prometheus-community/helm-charts#2263]
Hi,

I found out how to add persistent dashboards (via config maps) to grafana.

Is there a way to also add persistent plugins, without using persistent volumes?

Thanks,

**Comment by reefland** [comment]
Try something like below in your `values.yaml` fin the grafana section to enable additional plugins:
```
        grafana:
          enabled: true
          ...
          plugins:
            - grafana-piechart-panel
            - grafana-clock-panel
```
