### ISSUE TITLE
[prometheus-kube-stack] Make sure CertManager Certificate is RFC 5280 compliant

### ISSUE THREAD

**Issue by Moep90** [prometheus-community/helm-charts#2266]
### Describe the bug a clear and concise description of what the bug is.

The Cert-manager reports:

> Certificate will be issued with an empty Issuer DN, which contravenes RFC 5280 and could break some strict clients

### What's your helm version?

helm version version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: v1.24.2 Kustomize Version: v4.5.4 Server Version: v1.21.12

### Which chart?

kube-prometheus-stack

### What's the chart version?

36.2.1

### Enter the changed values of values.yaml?

```yaml
certManager:
  enabled: true
prometheusOperator:
  enabled: true
  admissionWebhooks:
    enabled: true
    certManager:
      enabled: true
      rootCert:
        duration: "5y"
      admissionCert:
        duration: "1y"
```

### Enter the command that you execute and failing/misfunctioning.

kubectl apply -f <path/to/the/manifest

### Anything else we need to know?
[rfc5280](https://datatracker.ietf.org/doc/html/rfc5280)
