### ISSUE TITLE
[kube-prometheus-stack] [regression?] prometheus.service.nodePort not exposed on each node

### ISSUE THREAD

**Issue by dchiaramello** [prometheus-community/helm-charts#2285]
### Describe the bug a clear and concise description of what the bug is.

Hello.
Last week, we updated our solution's kube-prometheus-stack from 36.0.0 to 37.2.0. The solution is composed of 3 master nodes and some worker nodes.
We attempted a new deployment (using helm upgrade --install, but in practice it was an install only, not an update), but we noticed that on none of the nodes (masters and workers), the nodePort specified was in LISTENING state, while it used to be the case with 36.0.0 and previous versions...
Here is an extract of the values file provided to kube-prometheus-stack:
```
prometheus:
  enabled: true
  service:
    port: 9090
    targetPort: 9090
    nodePort: 30900
    type: NodePort
```

### What's your helm version?

version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:30:55Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

37.2.0

### What happened?

The port number specified as prometheus.service.nodePort is not exposed on the each node constituting our solution

### What you expected to happen?

The port number specified as prometheus.service.nodePort used to be exposed (LISTEN state) on each k8s node constituting our solution with 36.0.0 version of kube-prometheus-stack and before, and was "belonging" to kube-proxy application on these nodes.

```
[ops@GTODFW40WOUvSOTA-S1-TH-K8M-001 ~]$ sudo netstat -laputen | grep 30900
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:30900           0.0.0.0:*               LISTEN      0          118703     11187/kube-proxy
```

### How to reproduce it?

Here is an extract of the values.yaml file used, I'm not sure that it's enough...
```
prometheus:
  enabled: true
  service:
    port: 9090
    targetPort: 9090
    nodePort: 30900
    type: NodePort
```

### Enter the changed values of values.yaml?

```
defaultRules:
  create: false
global:
  rbac:
    pspEnabled: true
alertmanager:
  enabled: false
grafana:
  enabled: false
kubelet:
  serviceMonitor:
    resourcePath: "/metrics/resource"
kubeControllerManager:
  endpoints: <list of IPs>
  service:
    port: 10257
    targetPort: 10257
    https: true
    insecureSkipVerify: true
kubeEtcd:
  endpoints: <list of IPs>
  serviceMonitor:
    scheme: https
    insecureSkipVerify: true
    serverName: localhost
    caFile: "/etc/prometheus/secrets/etcd-certs/etcd-ca"
    certFile: "/etc/prometheus/secrets/etcd-certs/etcd-cert"
    keyFile: "/etc/prometheus/secrets/etcd-certs/etcd-key"
kubeScheduler:
  endpoints: <list of IPs>
  service:
    port: 10259
    targetPort: 10259
  serviceMonitor:
    insecureSkipVerify: true
kubeProxy:
  enabled: false
nodeExporter:
  enabled: false
prometheusOperator:
  logFormat: json
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  prometheusConfigReloader:
    resources:
      requests:
        cpu: 100m
      limits:
        cpu: 100m
prometheus:
  service:
    nodePort: 30900
    type: NodePort
  serviceMonitor:
    scheme: "https"
    tlsConfig:
      insecureSkipVerify: true
  prometheusSpec:
    web:
      tlsConfig:
        keySecret:
          name: etcd-certs
          key: etcd-key
        cert:
          secret:
            name: etcd-certs
            key: etcd-cert
        clientAuthType: NoClientCert
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    secrets:
      - etcd-certs
    serviceMonitorSelectorNilUsesHelmValues: false
    replicas: 2
    logFormat: json
    podAntiAffinity: "hard"
    portName: "web"

```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install prometheus-operator /opt/ops/charts/kube-prometheus-stack.tgz --namespace monitoring -f -

- /opt/ops/charts/kube-prometheus-stack.tgz is the archive retrieved from https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-37.2.0/kube-prometheus-stack-37.2.0.tgz
- we provide the values file as stdin
