### ISSUE TITLE
[prometheus-kube-stack] additionalScrapeConfigs never updates

### ISSUE THREAD

**Issue by Rahulsharma0810** [prometheus-community/helm-charts#229]
**Describe the bug**
when adding new targets, in helm value file, targets never update in Prometheus.
```
    additionalScrapeConfigs:
    - job_name: 'pihole'
      static_configs:
        - targets: ['10.244.0.196:9617']
```
`helm upgrade -f custom-value.yml prom-stack prometheus-community/kube-prometheus-stack` simultaneously if I uninstall and reinstall it came back in Prometheus dashboard. 

**Version of Helm and Kubernetes**:

Helm Version: v3.3.3

Kubernetes version: v19

**Which chart**: kube-prometheus-stack
**Which version of the chart**:  v10.1.0

**What happened**: Did not sync updated targets 

**What you expected to happen**: target updated or added

**How to reproduce it** (as minimally and precisely as possible):

Update the values file with the new target

```
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'pihole'
      static_configs:
        - targets: ['10.244.0.196:9617']
    - job_name: 'dummy-metic'
      static_configs:
        - targets: ['dummy-ops-cluster-dummy-master.mysql:9125']
```
`helm upgrade -f custom-value.yml prom-stack prometheus-community/kube-prometheus-stack`
