### ISSUE TITLE
Enable Grafana embeds

### ISSUE THREAD

**Issue by apgapg** [prometheus-community/helm-charts#2291]
### Is your feature request related to a problem ?

Currently all blogs out there directs to create a new grafana.ini file to enable embeds.
How can we enable embeds when installing via helm way.

Ref: https://akshaybobade777.medium.com/embed-grafana-dashboards-in-your-web-application-17df196dcdec#:~:text=Login%20into%20Grafana%20dashboard%20and,code%20into%20your%20HTML%20page.

```
allow_embedding = true
[auth.anonymous]
# enable anonymous access
enabled = true
```

### Describe the solution you'd like.

Some way to add above settings via helm values way

### Describe alternatives you've considered.

Couldn't find other way

**Comment by maxpain** [comment]
Any updates?

**Comment by apgapg** [comment]
I have solved this via env variables.
Something like helm values

```yaml
controller:
  metrics:
    port: 10254
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
    serviceMonitor:
      enabled: true
      namespace: monitoring
      namespaceSelector:
        any: true

grafana:
  service:
    type: LoadBalancer
  grafana.ini:
    allow_embedding: true
    auth.anonymous: true
    # enable anonymous access
    enabled: true
  env:
    GF_SECURITY_ALLOW_EMBEDDING: true
    GF_AUTH_ANONYMOUS_ENABLED: true

prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

```
