### ISSUE TITLE
[prometheus] subchart gets included via kubeStateMetrics but can be configured via kube-state-metrics

### ISSUE THREAD

**Issue by guidoiaquinti** [prometheus-community/helm-charts#2299]
### Is your feature request related to a problem ?

By default, the `prometheus` chart installs the additional dependent charts [kube-state-metrics](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics). We toggle its installation via the `kubeStateMetrics.enabled` value but to then configure the subchart we need to use `kube-state-metrics` ending up with a `values.yaml` like:

```
prometheus:
  enabled: false
  
  kubeStateMetrics:
    enabled: true
  
  kube-state-metrics:
    resources:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
```

Maybe this is intentional/by design but personally I found this a bit confusing. I know this can be considered a cosmetic issue that can be addressed only via a breaking change but it took me good 10 min to understand why my overrides were not applied to the subchart. Feel free to close as won't do if you think it's a UX issue not worth fixing. 

### Describe the solution you'd like.

The subchart can be configured using a single stanza, example:

```
prometheus:
  enabled: false
  
  kubeStateMetrics:
    enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
```

### Describe alternatives you've considered.

Do nothing.

### Additional context.
N/A

Thank you very much, have a good day! 🙇

**Comment by bklar84** [comment]
The comments in values.yaml do make this clear:
```
kubeStateMetrics:
...
## kube-state-metrics sub-chart configurable values
## Please see https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics
##
# kube-state-metrics:
```

However, I tend to agree because the `kube-prometheus-stack` chart does this as well, but becomes a tad muddy in that it uses `grafana` as a dependency and ther'es only a singular top level key to enable and configure grafana:

```
grafana:
  enabled: true
  namespaceOverride: ""

  ## ForceDeployDatasources Create datasource configmap even if grafana deployment has been disabled
  ##
  forceDeployDatasources: false

  ## ForceDeployDashboard Create dashboard configmap even if grafana deployment has been disabled
  ##
  forceDeployDashboards: false
  ...
```
