### ISSUE TITLE
[Prometheus] serverFiles parser overlapping

### ISSUE THREAD

**Issue by dmytro-zhernosiekov-rft** [prometheus-community/helm-charts#230]
**Describe the bug**
I need to extend `Prometheus` configuration with `blackbox_exporter` support and add targets to prometheus config. We use terraform, so I used `helm_release` resource in terraform. I need to add next configuration:

```
  prometheus.yml: |
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090
        - prometheus-blackbox-exporter:9115
```

and 
```
    - job_name: 'blackbox'
      metrics_path: /probe
      params:
        module: [http_2xx]  # Look for a HTTP 200 response.
      static_configs:
        - targets:
          - http://consul-server.consul.svc:8500
          - http://server.opa.svc:8181
          - http://vault.vault.svc:8200
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: prometheus-blackbox-exporter:9115  # The blackbox exporter's real hostname:port.
```
so I add `prometheus.yml` template and try to render template into config. File beginning: 
```
global:
  evaluation_interval: 30s
  scrape_interval: 30s
  scrape_timeout: 10s
rule_files:
- /etc/config/recording_rules.yml
- /etc/config/alerting_rules.yml
- /etc/config/rules
- /etc/config/alerts
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
    - prometheus-blackbox-exporter:9115
.......
```
Terraform code:
```
data "template_file" "prometheus_server_config" {
  template = file("${path.module}/templates/prometheus-server-config.yaml.tpl")
  vars = {
    deployment_name = local.deployment_name
    environment = var.environment 
  }
}

resource "helm_release" "prometheus" {

  name       = "prometheus"
  count      = var.prometheus_enabled ? 1 : 0
  repository = var.prometheus_helm_repository
  chart      = var.prometheus_chart
  version    = var.prometheus_chart_version

  depends_on = [kubernetes_namespace.monitoring]

  namespace = var.namespace
  timeout   = 600

  set {
    name  = "serverFiles.prometheus\\.yml"
    value = data.template_file.prometheus_server_config.rendered
  }  
}
```

But when I apply configuration, terraform failed to run server by timeout.

**Version of Helm and Kubernetes**:

Helm Version:

```console
helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

Kubernetes Version:

```console
$> kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:  prometheus 
**Which version of the chart**: 11.16.2
**What happened**:
prometheus-server ConfigMap looks not good:
```
apiVersion: v1
data:
  alerting_rules.yml: |
    {}
  alerts: |
    {}
  prometheus.yml: |
    global:
      evaluation_interval: 1m
      scrape_interval: 1m
      scrape_timeout: 10s
    |-
      global:
        evaluation_interval: 30s
        scrape_interval: 30s
        scrape_timeout: 10s
```
it seems that helm chart proceed with global parameters at the first and then try to apply whole file. I tried to:
```
  set {
    name  = "server.global"
    value = ""
  }  
```
and got:
```
apiVersion: v1
data:
  alerting_rules.yml: |
    {}
  alerts: |
    {}
  prometheus.yml: |
    global:
      ""
    |-
      global:
        evaluation_interval: 30s
        scrape_interval: 30s
        scrape_timeout: 10s
```

**What you expected to happen**:
Correct Prometheus configmap render and applied. Steps I performed look quite logical, but maybe there is much simpler way to do it? If not, parser need to be fixed to apply only file if no parameters set.

**How to reproduce it** (as minimally and precisely as possible):
Just reuse code from description.

**Anything else we need to know**:
