### ISSUE TITLE
[prometheus-kube-stack] k8s.rules for RKE2 k8s 1.24

### ISSUE THREAD

**Issue by xadcoh** [prometheus-community/helm-charts#2303]
### Describe the bug a clear and concise description of what the bug is.

It looks like a newer RKE2 kubelet (1.24+) doesn't enreach metrics with the `image` label. Grafana `Kubernetes / Compute Resources / Pod` dashboard doesn't show cpu usage.

### What's your helm version?

3.9.0

### What's your kubectl version?

v1.22.6

### Which chart?

prometheus-kube-stack

### What's the chart version?

38.0.0

### What happened?

kubelet stopped ship some labels with `container_cpu_usage_seconds_total` metric

### What you expected to happen?

Grafana should be able to render cpu usage

### How to reproduce it?

Install prometheus-kube-stack on a k8s 1.24+ cluster

### Enter the changed values of values.yaml?

```
        alertmanager:
          enabled: false        
        grafana:
          enabled: false
        prometheus:
          enabled: true
          prometheusSpec:
            remoteWrite:
              - url: http://<internal_ip>:9090/api/v1/write
        kubeEtcd:
          service:
            port: 2381
            targetPort: 2381
        defaultRules:
          create: false
```

### Enter the command that you execute and failing/misfunctioning.

None

### Anything else we need to know?

Didn't find an option to add a label to the metric
I'm using RKE2 k8s
v1.23.6 ships the `image` label in kubelet metrics
Here is a line [example](https://github.com/prometheus-community/helm-charts/blob/dad1b54be2ba302267bfc8e4460da54d2e3e62a9/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/k8s.rules.yaml#L29) with `image!=""` , perhaps we can remove this requirement from the rule
