### ISSUE TITLE
[prometheus-node-exporter] apparmor policy prevents usage of systemd collector 

### ISSUE THREAD

**Issue by sigurdblueface** [prometheus-community/helm-charts#2304]
Hello, everyone.

I want to collect metrics of systemd services, running on nodes of k3s cluster, into prometheus instance installed inside the same cluster. 

Tried to use following configuration:
```yaml
prometheus-node-exporter:
  extraArgs:
    - --collector.systemd

  extraHostVolumeMounts: 
    - name: systemd-socket
      mountPath: /var/run/dbus/system_bus_socket
      hostPath: /var/run/dbus/system_bus_socket
      readOnly: true
```
this results in:

```
ts=2022-06-20T11:40:29.127Z caller=collector.go:169 level=error msg="collector failed" name=systemd duration_seconds=0.006307937 err="couldn't get dbus connection: An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\"(null)\" (inactive) interface=\"org.freedesktop.DBus\" member=\"Hello\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.DBus\" (bus)”
```

I'm running k3s v1.21.2 and I blush to admit that I never had anything to do with AppArmor. Google also hasn't really explained what I should be doing now. 

So I'm asking for a kind advice from someone, who had made it working on what I should do, or on a link on some useful human-friendly documentation about managing apparmor policies, or an explanation why I shouldn't collect these metrics this way. (As a quick workaround I just installed additional node exporters directly on nodes with only enabled systemd collector).

Thanks in advance.

**Comment by SadeghHayeri** [comment]
Hi, I fixed this issue using [this](https://kubernetes.io/docs/tutorials/security/apparmor/#profile-reference) annotation. but I don't know if this is a proper way to do that or not, but it does the job!

```yaml
prometheus-node-exporter:
  extraArgs:
    - --collector.systemd

  extraHostVolumeMounts:
    - name: systemd-socket
      mountPath: /var/run/dbus/system_bus_socket
      hostPath: /var/run/dbus/system_bus_socket
      readOnly: true
      mountPropagation: None

  podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    container.apparmor.security.beta.kubernetes.io/node-exporter: "unconfined"
```
