### ISSUE TITLE
[kube-prometheus-stack] Error: INSTALLATION FAILED: create: failed to create: Secret "sh.helm.release.v1.kube-prometheus-stack.v1" is invalid: data: Too long: must have at most 1048576 bytes

### ISSUE THREAD

**Issue by XDavidT** [prometheus-community/helm-charts#2307]
### Describe the bug a clear and concise description of what the bug is.

I tried to use one helm to all kube-prometheus-stack and made a new chart,
The Chart.yaml:
```
apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart for kube-prometheus-stack

type: application

version: 0.0.1

appVersion: "0.0.1"
dependencies:
  - name: kube-prometheus-stack
    version: 38.0.2
    repository: https://artifactory.amat.com/artifactory/prometheus-remote
```
and values is empty (I tried with my values, but it didn't worked, so cleared to see if the issue is in my values)

### What's your helm version?

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.22) and server (1.24) exceeds the supported minor version skew of +/-1

### Which chart?

kube-prometheus-stack

### What's the chart version?

38.0.2

### What happened?

Got this error:

> Error: INSTALLATION FAILED: create: failed to create: Secret "sh.helm.release.v1.kube-prometheus-stack.v1" is invalid: data: Too long: must have at most 1048576 bytes

### How to reproduce it?

Use my chart, with empty values file, run `helm dependency update` and run `helm install  kube-prometheus-stack .`

### Enter the command that you execute and failing/misfunctioning.

helm install  kube-prometheus-stack

### Anything else we need to know?

I have my custom values file, but didn't use it to check it without and see it's working.
