### ISSUE TITLE
 [kube-prometheus-stack] Unable to update data sources from garfana dashboard

### ISSUE THREAD

**Issue by pen-pal** [prometheus-community/helm-charts#2312]
### Describe the bug a clear and concise description of what the bug is.

I deployed kube prometheus stack with additional data sources as described in the README. However, upon adding the datasources successfully on grafana using the `kube-prometheus-stack` helm chart, I can no longer update or make changes on the datasources that were added from chart. If however, I add a data source manually, I can make all the changes as per requirement without any issues at all

### What's your helm version?

3.6.3

### What's your kubectl version?

1.24

### Which chart?

kube-prometheus-stack

### What's the chart version?

38.0.2

### What happened?

I deployed the stack by adding  datasources on the additonalDatasourcesSection, but once the data sources are added on the grafana, I **can no longer go ahead and make changes on them from grafana dashboard ** 

![image](https://user-images.githubusercontent.com/61139563/181263203-8b029573-7090-471a-b112-e5ebfc1ce13a.png)

### What you expected to happen?

Able to update the datasources added from helm chart in the garfana ui

### How to reproduce it?

  add this configuration under grafana

```
grafana:
## ref: http://docs.grafana.org/administration/provisioning/#datasources
  additionalDataSources:
    - name: Loki
      type: loki
      isDefault: false
      editable: true
      access: proxy
      url: http://loki.monitor.svc.cluster.local:3100
      uid: loki
      version: 1
      jsonData:
        manageAlerts: true
        derivedFields:
          - name: "traceID"
            matcherRegex: "(?:traceID|trace_id|tid|TraceID)=(\\w+)"
            url: "$${__value.raw}"
            datasourceUid: tempo
    - name: Tempo
      type: tempo
      editable: true
      isDefault: false
      access: proxy
      url: http://tempo.monitor.svc:3100
      uid: tempo
      version: 1
      jsonData:
        httpMethod: GET
        tracesToLogs:
          datasourceUid: loki
        serviceMap:
          datasourceUid: 'prometheus'
        search:
          hide: false
        nodeGraph:
          enabled: true
        lokiSearch:
          datasourceUid: loki
```

### Enter the changed values of values.yaml?

 ```
 additionalDataSources:
    - name: Loki
      type: loki
      isDefault: false
      editable: true
      access: proxy
      url: http://loki.monitor.svc.cluster.local:3100
      uid: loki
      version: 1
      jsonData:
        manageAlerts: true
        derivedFields:
          - name: "traceID"
            matcherRegex: "(?:traceID|trace_id|tid|TraceID)=(\\w+)"
            url: "$${__value.raw}"
            datasourceUid: tempo
    - name: Tempo
      type: tempo
      editable: true
      isDefault: false
      access: proxy
      url: http://tempo.monitor.svc:3100
      uid: tempo
      version: 1
      jsonData:
        httpMethod: GET
        tracesToLogs:
          datasourceUid: loki
        serviceMap:
          datasourceUid: 'prometheus'
        search:
          hide: false
        nodeGraph:
          enabled: true
        lokiSearch:
          datasourceUid: loki

```

### Enter the command that you execute and failing/misfunctioning.

`helm upgrade --install monitor prometheus-community/kube-prometheus-stack -f values.yaml`

### Anything else we need to know?

1. how do I make sure I can edit the datasource created from helm chart?
