### ISSUE TITLE
[kube-prometheus-stack] Consider removing the “job” and “metrics_path” labels in the rules expression

### ISSUE THREAD

**Issue by imroc** [prometheus-community/helm-charts#2327]
### Is your feature request related to a problem ?

Public cloud kubernetes engine like [TKE](https://intl.cloud.tencent.com/ind/products/tke) (Tencent Kubernetes Engine), supports virtual node, which every pod is a virtual machine if pod scheduled into the virtual node. And its' cadvisor metrics(`container_xxx`) and kubelet metrics(`kubelet_xxx`) is both exposed on pod ip and port 9100 with the same metrics path `/metrics`, so the `values.yaml` of `prometheus-kube-stack` should like this:

```yaml
kubelet:
  enabled: false
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: "virtualnode" # both cadvisor and kubelet metrics of virutal node are included here.
      honor_timestamps: true
      metrics_path: '/metrics'
      scheme: http
      kubernetes_sd_configs:
      - role: pod
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        insecure_skip_verify: true
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_tke_cloud_tencent_com_pod_type] # only the pod on virtual node
        regex: eklet
        action: keep
      - source_labels: [__meta_kubernetes_pod_phase]
        regex: Running
        action: keep
      - source_labels: [__meta_kubernetes_pod_ip]
        separator: ;
        regex: (.*)
        target_label: __address__
        replacement: ${1}:9100
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: pod_name
        replacement: ${1}
        action: replace
      metric_relabel_configs:
      - source_labels: [__name__]
        separator: ;
        regex: (container_.*)
        replacement: $1
        action: keep
      - source_labels: [pod_name]
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
    - job_name: "kubelet" # kubelet metrics for normal node.
      scheme: https
      metrics_path: /metrics
      tls_config:
        insecure_skip_verify: true
      authorization:
        credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - source_labels: [__meta_kubernetes_node_label_node_kubernetes_io_instance_type] # exclude virtual node
        regex: eklet
        action: drop
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
    - job_name: "cadvisor" # cadvisor metrics for normal node.
      scheme: https
      metrics_path: /metrics/cadvisor
      tls_config:
        insecure_skip_verify: true
      authorization:
        credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - source_labels: [__meta_kubernetes_node_label_node_kubernetes_io_instance_type] # exclude virtual node
        regex: eklet
        action: drop
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
```

As a result, a lot of the default grafana dashboard will not display any data, because  many metrics are calculated by rules, and rules use fixed label such as job and metrics_path query data, for example, k8s.rules:
```yaml
spec:
  groups:
  - name: k8s.rules
    rules:
    - expr: |-
        sum by (cluster, namespace, pod, container) (
          irate(container_cpu_usage_seconds_total{job="kubelet", metrics_path="/metrics/cadvisor", image!=""}[5m])
        ) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (
          1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=""})
        )
      record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate
```

`job="kubelet", metrics_path="/metrics/cadvisor"` will not match my `additionalScrapeConfigs`, and there is no data will be returned.

### Describe the solution you'd like.

Remove  “job” and “metrics_path” labels in the rules expression and promql in dashboards, or provide an option to remove those labels.

### Describe alternatives you've considered.

Fork and batch remove labels by myself.
