### ISSUE TITLE
[kube-prometheus-stack] podAnnotations option not available for Alertmanager 

### ISSUE THREAD

**Issue by rohit-co3046** [prometheus-community/helm-charts#2347]
### Is your feature request related to a problem ?

We want to setup podAnnotations for Alertmanager but we don’t see any options in below helm charts. We have enabled consul injection so sidecar always enabled for each pod. So using podAnnotation we can disable but i don’t see any options on this chart.
name: kube-prometheus-stack
version: 39.2.0

### Describe the solution you'd like.

Enabling podAnnotations feature will help us to implement kube-prometheus-stack  

### Describe alternatives you've considered.

NONE

**Comment by lukashass** [comment]
I just figured out which properties to set:

```yml
alertmanager:
  alertmanagerSpec:
    podMetadata:
      annotations:
        annotation-1: test-value-123
```

The same is possible for prometheus.
