### ISSUE TITLE
[prometheus-kube-stack] Kubernetes network metrics are gone

### ISSUE THREAD

**Issue by namirsab** [prometheus-community/helm-charts#2362]
### Describe the bug a clear and concise description of what the bug is.

Networking  Grafana charts stopped working

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: v1.24.3 Kustomize Version: v4.5.4 Server Version: v1.23.2

### Which chart?

prometheus-kube-stack

### What's the chart version?

kube-prometheus-stack-37.2.0

## Observed
Out of sudden (probably related to an update or something) I cannot see networking charts in the default grafana charts. Everything related to network has not data.
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/6980777/184089510-d89e2fed-4520-43a5-8dea-38a80973efc2.png">

## Expected
I should get networking charts as I did before.

### How to reproduce it?

I don't know, I wish i knew :( 

### Enter the changed values of values.yaml?

```yaml
alertmanager:
  config:
    route:
      receiver: 'calert'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      group_by: ['job']
    receivers:
    - name: 'null'
    - name: 'calert'
      webhook_configs:
      - url: 'http://calert:6000/dispatch'
  alertmanagerSpec:
    externalUrl: "https://xxx"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: scw-bssd
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 10Gi

grafana:
  deploymentStrategy:
    type: Recreate 
  persistence:
    enabled: true
  
  dashboards:
    redis-exporter:
      redis-exporter-default:
        json: | 
          {"__inputs":[],"__requires":[{"type":"grafana","id":"grafana","name":"Grafana","version":"7.2.0"},{"type":"panel","id":"graph","name":"Graph","version":""},{"type":"datasource","id":"prometheus","name":"Prometheus","version":"1.0.0"}],"annotations":{"list":[{"builtIn":1,"datasource":"-- Grafana --","enable":true,"hide":true,"iconColor":"rgba(0, 211, 255, 1)","name":"Annotations & Alerts","type":"dashboard"}]},"description":"A quickstart to setup the Prometheus Redis Exporter with preconfigured dashboards, alerting rules, and recording rules.","editable":true,"gnetId":14091,"graphTooltip":1,"id":24,"iteration":1602758020790,"links":[],"panels":[{"collapsed":false,"datasource":null,"gridPos":{"h":1,"w":24,"x":0,"y":0},"id":24,"panels":[],"title":"Performance","type":"row"},{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":"$datasource","description":"Average taken across instances","editable":true,"error":false,"fieldConfig":{"defaults":{"custom":{}},"overrides":[]},"fill":1,"fillGradient":0,"grid":{},"gridPos":{"h":7,"w":8,"x":0,"y":1},"hiddenSeries":false,"id":18,"isNew":true,"legend":{"avg":false,"current":false,"hideEmpty":false,"hideZero":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"connected","options":{"dataLinks":[]},"percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":true,"steppedLine":false,"targets":[{"expr":"avg(irate(redis_commands_total{instance=~\"$instance\"} [1m])) by (cmd)","format":"time_series","interval":"","intervalFactor":2,"legendFormat":"{{cmd}}","metric":"redis_command_calls_total","refId":"A","step":240}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Commands per second","tooltip":{"msResolution":true,"shared":true,"sort":2,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":"$datasource","description":"Average taken across instances","editable":true,"error":false,"fieldConfig":{"defaults":{"custom":{}},"overrides":[]},"fill":1,"fillGradient":0,"grid":{},"gridPos":{"h":7,"w":8,"x":8,"y":1},"hiddenSeries":false,"id":20,"isNew":true,"legend":{"avg":false,"current":false,"hideEmpty":false,"hideZero":true,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"connected","options":{"dataLinks":[]},"percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"avg(irate(redis_commands_duration_seconds_total{instance=~\"$instance\"}[1m])) by (cmd)\n  /\navg(irate(redis_commands_total{instance=~\"$instance\"}[1m])) by (cmd)\n","format":"time_series","interval":"","intervalFactor":2,"legendFormat":"{{ cmd }}","metric":"redis_command_calls_total","refId":"A","step":240}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Command latency per second","tooltip":{"msResolution":true,"shared":true,"sort":2,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"s","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"aliasColors":{"Hit ratio":"blue"},"bars":false,"dashLength":10,"dashes":false,"datasource":"$datasource","decimals":2,"description":"Hit rate shows the percentage of key space lookups that hit a key.","editable":true,"error":false,"fieldConfig":{"defaults":{"custom":{}},"overrides":[]},"fill":1,"fillGradient":0,"grid":{},"gridPos":{"h":7,"w":8,"x":16,"y":1},"hiddenSeries":false,"id":1,"isNew":true,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"connected","options":{"dataLinks":[]},"percentage":true,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[{"alias":"/Target/","color":"#56A64B","dashes":true,"fill":0,"hideTooltip":true,"linewidth":1}],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"avg(irate(redis_keyspace_hits_total{instance=~\"$instance\"}[1m]) / (irate(redis_keyspace_misses_total{instance=~\"$instance\"}[1m]) + irate(redis_keyspace_hits_total{instance=~\"$instance\"}[1m]))) by (instance)","format":"time_series","hide":false,"interval":"","intervalFactor":2,"legendFormat":"{{instance}}","metric":"","refId":"A","step":240,"target":""},{"expr":"1","interval":"","legendFormat":"Target hit ratio for cache","refId":"B"}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Hit ratio per instance","tooltip":{"msResolution":false,"shared":true,"sort":0,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"percentunit","label":"","logBase":1,"max":null,"min":0,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"collapsed":false,"datasource":null,"gridPos":{"h":1,"w":24,"x":0,"y":8},"id":22,"panels":[],"title":"Memory","type":"row"},{"aliasColors":{"max":"#BF1B00"},"bars":false,"dashLength":10,"dashes":false,"datasource":"$datasource","description":"Total taken across instances","editable":true,"error":false,"fieldConfig":{"defaults":{"custom":{}},"overrides":[]},"fill":1,"fillGradient":0,"grid":{},"gridPos":{"h":7,"w":8,"x":0,"y":9},"hiddenSeries":false,"id":7,"isNew":true,"legend":{"avg":false,"current":false,"hideEmpty":false,"hideZero":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"null as zero","options":{"dataLinks":[]},"percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[{"alias":"/max/","color":"#E02F44","dashes":true,"fill":0,"linewidth":1}],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"sum(redis_memory_used_bytes{instance=~\"$instance\"})","format":"time_series","interval":"","intervalFactor":2,"legendFormat":"Used Memory","metric":"","refId":"A","step":240,"target":""},{"expr":"sum(redis_memory_max_bytes{instance=~\"$instance\"})","format":"time_series","hide":false,"interval":"","intervalFactor":2,"legendFormat":"Configured max memory","refId":"B","step":240},{"expr":"sum(redis_memory_used_rss_bytes{instance=~\"$instance\"})","interval":"","legendFormat":"Used RSS memory","refId":"C"}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Total Memory Usage","tooltip":{"msResolution":false,"shared":true,"sort":0,"value_type":"cumulative"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"bytes","label":null,"logBase":1,"max":null,"min":0,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"aliasColors":{"Recommend restart redis":"red"},"bars":false,"dashLength":10,"dashes":false,"datasource":"$datasource","editable":true,"error":false,"fieldConfig":{"defaults":{"custom":{}},"overrides":[]},"fill":1,"fillGradient":0,"grid":{},"gridPos":{"h":7,"w":8,"x":8,"y":9},"hiddenSeries":false,"id":10,"isNew":true,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"connected","options":{"dataLinks":[]},"percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[{"alias":"/restart/","color":"#E02F44","dashes":true,"fill":0,"linewidth":1}],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"redis_memory_fragmentation_ratio{instance=~\"$instance\"}","hide":false,"interval":"","legendFormat":"{{instance}}","refId":"C"}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Memory fragmentation ratio per instance","tooltip":{"msResolution":true,"shared":true,"sort":0,"value_type":"cumulative"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"aliasColors":{"Evictions":"red","evicts":"#890F02","memcached_items_evicted_total{instance=\"172.17.0.1:9150\",job=\"prometheus\"}":"#890F02","reclaims":"#3F6833","{container=\"redis-exporter\", instance=\"redis-86cb5d76d7-fcdln:redis-exporter:redis-metrics\", job=\"default/redis\", namespace=\"default\", pod=\"redis-86cb5d76d7-fcdln\"}":"red","{instance=\"redis-86cb5d76d7-fcdln:redis-exporter:redis-metrics\"}":"red"},"bars":false,"dashLength":10,"dashes":false,"datasource":"$datasource","editable":true,"error":false,"fieldConfig":{"defaults":{"custom":{}},"overrides":[]},"fill":1,"fillGradient":0,"grid":{},"gridPos":{"h":7,"w":8,"x":16,"y":9},"hiddenSeries":false,"id":8,"isNew":true,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"connected","options":{"dataLinks":[]},"percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[{"alias":"reclaims","yaxis":2}],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"irate(redis_evicted_keys_total{instance=~\"$instance\"}[1m])","format":"time_series","interval":"","intervalFactor":2,"legendFormat":"{{instance}}","refId":"B","step":240}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Key evictions per second per instance","tooltip":{"msResolution":false,"shared":true,"sort":0,"value_type":"cumulative"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"collapsed":false,"datasource":null,"gridPos":{"h":1,"w":24,"x":0,"y":16},"id":26,"panels":[],"title":"Basic activity","type":"row"},{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":"$datasource","description":"Sum taken across instances","fieldConfig":{"defaults":{"custom":{}},"overrides":[]},"fill":1,"fillGradient":0,"gridPos":{"h":7,"w":8,"x":0,"y":17},"hiddenSeries":false,"id":16,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"null","options":{"dataLinks":[]},"percentage":false,"pointradius":2,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"sum(redis_connected_clients{instance=~\"$instance\"})","format":"time_series","interval":"","intervalFactor":1,"legendFormat":"Connected","refId":"A"},{"expr":"sum(redis_blocked_clients{instance=~\"$instance\"})","format":"time_series","interval":"","intervalFactor":1,"legendFormat":"Blocked","refId":"B"}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Connected/Blocked Clients","tooltip":{"shared":true,"sort":0,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"aliasColors":{"db1":"yellow"},"bars":false,"dashLength":10,"dashes":false,"datasource":"$datasource","description":"Sum taken across instances","editable":true,"error":false,"fieldConfig":{"defaults":{"custom":{}},"overrides":[]},"fill":1,"fillGradient":0,"grid":{},"gridPos":{"h":7,"w":8,"x":8,"y":17},"hiddenSeries":false,"id":5,"isNew":true,"legend":{"alignAsTable":false,"avg":false,"current":false,"hideEmpty":false,"hideZero":true,"max":false,"min":false,"rightSide":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"null","options":{"dataLinks":[]},"percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":true,"steppedLine":false,"targets":[{"expr":"sum (redis_db_keys{instance=~\"$instance\"}) by (db)","format":"time_series","interval":"","intervalFactor":1,"legendFormat":"{{ db }}","refId":"A","step":240,"target":""}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Total Items per DB","tooltip":{"msResolution":false,"shared":true,"sort":1,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"none","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":"$datasource","description":"Sum taken across instances","editable":true,"error":false,"fieldConfig":{"defaults":{"custom":{}},"overrides":[]},"fill":1,"fillGradient":0,"grid":{},"gridPos":{"h":7,"w":8,"x":16,"y":17},"hiddenSeries":false,"id":13,"isNew":true,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"connected","options":{"dataLinks":[]},"percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":true,"steppedLine":false,"targets":[{"expr":"sum (redis_db_keys{instance=~\"$instance\"}) - sum (redis_db_keys_expiring{instance=~\"$instance\"})","format":"time_series","hide":false,"interval":"","intervalFactor":2,"legendFormat":"Not expiring","refId":"A","step":240,"target":""},{"expr":"sum(redis_db_keys_expiring{instance=~\"$instance\"})","format":"time_series","interval":"","intervalFactor":2,"legendFormat":"Expiring","metric":"","refId":"B","step":240}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Expiring vs Not-Expiring Keys","tooltip":{"msResolution":false,"shared":true,"sort":0,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":"$datasource","description":"This metric will only be non-zero if the instance is a master","fieldConfig":{"defaults":{"custom":{}},"overrides":[]},"fill":1,"fillGradient":0,"gridPos":{"h":7,"w":8,"x":0,"y":24},"hiddenSeries":false,"id":28,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"nullPointMode":"null","options":{"dataLinks":[]},"percentage":false,"pointradius":2,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"sum(redis_connected_slaves{instance=~\"$instance\"}) by (instance)","interval":"","legendFormat":"{{instance}}","refId":"A"}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Connected slaves by instance","tooltip":{"shared":true,"sort":0,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":"$datasource","description":"This metric is only exported if the instance is a slave.","fieldConfig":{"defaults":{"custom":{}},"overrides":[]},"fill":1,"fillGradient":0,"gridPos":{"h":7,"w":8,"x":8,"y":24},"hiddenSeries":false,"id":30,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"nullPointMode":"null","options":{"dataLinks":[]},"percentage":false,"pointradius":2,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"redis_master_last_io_seconds_ago{instance=~\"$instance\"}","interval":"","legendFormat":"{{instance}}","refId":"A"}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Time since last master connection","tooltip":{"shared":true,"sort":0,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"s","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}}],"refresh":false,"schemaVersion":25,"style":"dark","tags":["prometheus","redis"],"templating":{"list":[{"allValue":null,"current":{"selected":true,"tags":[],"text":"redisdb-7d6b98cd98-kjt5x + redisdb-7d6b98cd98-pbkg6","value":["redisdb-7d6b98cd98-kjt5x","redisdb-7d6b98cd98-pbkg6"]},"datasource":"${datasource}","definition":"label_values(redis_up, instance)","hide":0,"includeAll":false,"label":null,"multi":true,"name":"instance","options":[],"query":"label_values(redis_up, instance)","refresh":2,"regex":"","skipUrlSync":false,"sort":1,"tagValuesQuery":"","tags":[],"tagsQuery":"","type":"query","useTags":false},{"current":{"selected":false,"text":"prometheus","value":"prometheus"},"hide":0,"includeAll":false,"label":null,"multi":false,"name":"datasource","options":[],"query":"prometheus","queryValue":"","refresh":1,"regex":"","skipUrlSync":false,"type":"datasource"}]},"time":{"from":"now-12h","to":"now"},"timepicker":{"refresh_intervals":["10s","30s","1m","5m","15m","30m","1h","2h","1d"],"time_options":["5m","15m","1h","6h","12h","24h","2d","7d","30d"]},"timezone":"browser","title":"Redis Exporter Quickstart and Dashboard","uid":"bRd48yKMdd","version":5}
          


prometheus:
  prometheusSpec:
    externalUrl: "https://prometheus.internal.ampere.cloud"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: scw-bssd
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    # External nodes not part of Kubernetes
    additionalScrapeConfigs:
      - job_name: "node-exporter"
        scheme: http
        static_configs:
          - targets: 
            - ...
        metrics_path: xxx
        basic_auth:
          username: xxx
          password: xxx
      - job_name: "redis-exporter"
        scheme: http
        static_configs:
          - targets: 
            - ...
        metrics_path: /redis-exporter/metrics/
        basic_auth:
          username: xxx
          password: xx

## Disabling this rule for now because is creating too much noise
## This should be investigated 
defaultRules:
  create: true
  disabled: 
    NodeHighNumberConntrackEntriesUsed: false
  

## Re-adding the disabled rule but with a higher threshold
additionalPrometheusRulesMap:
  custom-alerts:
    groups:
      - name: NodeHighNumberConntrackEntriesUsedCustom
        rules:
          - alert: NodeHighNumberConntrackEntriesUsed
            annotations:
              description: '{{`{{`}} $value | humanizePercentage {{`}}`}} of conntrack entries are used.'
              summary: Number of conntrack are getting close to the limit.
            expr: (node_nf_conntrack_entries / node_nf_conntrack_entries_limit) > 0.85
            labels:
              severity: warning
  redis-exporter:
    groups:
    - name: redis_rules
      rules:
      - expr: redis_memory_used_rss_bytes / redis_memory_used_bytes
        record: redis_memory_fragmentation_ratio
    - name: redis_alerts
      rules:
      - alert: RedisDown
        annotations:
          description: |-
            Redis instance is down
              VALUE = {{ $value }}
              LABELS: {{ $labels }}
          summary: Redis down (instance {{ $labels.instance }})
        expr: redis_up == 0
        for: 5m
        labels:
          severity: critical
      - alert: RedisOutOfMemory
        annotations:
          description: |-
            Redis is running out of memory (> 90%)
              VALUE = {{ $value }}
              LABELS: {{ $labels }}
          summary: Redis out of memory (instance {{ $labels.instance }})
        expr: redis_memory_used_bytes / redis_total_system_memory_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
      - alert: RedisTooManyConnections
        annotations:
          description: |-
            Redis instance has too many connections
              VALUE = {{ $value }}
              LABELS: {{ $labels }}
          summary: Redis too many connections (instance {{ $labels.instance }})
        expr: redis_connected_clients > 100
        for: 5m
        labels:
          severity: warning
```

### Enter the command that you execute and failing/misfunctioning.

There is no command 

### Anything else we need to know?

The only thing I "changed" before I realized that networking charts where not working, was adding additionalScrapeConfigs
