### ISSUE TITLE
unable  to configure spring boot application metrices in Prometheus using helm chart

### ISSUE THREAD

**Issue by ASingh14** [prometheus-community/helm-charts#2380]
I deployed Prometheus (kube-prometheus-stack) using helm chart , now I want to configure metrices related to spring boot api in Prometheus, below code i used in my values.yaml but it is not working 
same  scrape_configs is working in prometheus.yaml and deployed using kubectl

```
prometheus:
  prometheusOperator:
    admissionWebhooks:
      enabled: false
  scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
      
    - job_name: 'micrometer'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      static_configs: 
        - targets: ['localhost:6065','localhost:6061']
```

kindly suggest the approach for configuration in helm chart .
