### ISSUE TITLE
Helm chart template kube-prometheus-stack not support hostAliases.

### ISSUE THREAD

**Issue by tannguyen244** [prometheus-community/helm-charts#2383]
### Describe the bug a clear and concise description of what the bug is.

Helm chart template kube-prometheus-stack not support hostAliases.

```
  prometheusSpec:
    ## If true, pass --storage.tsdb.max-block-duration=2h to prometheus. This is already done if using Thanos
    ##
    hostAliases:
    - hostnames:
      - abc.com
      - xyz.com
      ip: 10.31.0.3
```

### What's your helm version?

v3.9.0

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-dispatcher-dirty", GitCommit:"2b63bf75320745c39af440c6717fccf55b93c046", GitTreeState:"dirty", BuildDate:"2022-05-10T19:57:08Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/arm64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10-gke.600", GitCommit:"2c921d7b040ed9c5a3a1f9407fb109b74d72d0a4", GitTreeState:"clean", BuildDate:"2022-06-02T09:20:24Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

0.58.0

### What happened?

Helm chart template kube-prometheus-stack not support hostAliases.

```
  prometheusSpec:
    ## If true, pass --storage.tsdb.max-block-duration=2h to prometheus. This is already done if using Thanos
    ##
    hostAliases:
    - hostnames:
      - abc.com
      - xyz.com
      ip: 10.31.0.3
```

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus-stack prometheus-community/kube-prometheus-stack
