### ISSUE TITLE
[prometheus-kube-stack] `remote_write` to grafana cloud doesn't work

### ISSUE THREAD

**Issue by cp-weng** [prometheus-community/helm-charts#2386]
### Describe the bug a clear and concise description of what the bug is.

My grafana cloud doesn't receive any data.

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10-gke.600", GitCommit:"2c921d7b040ed9c5a3a1f9407fb109b74d72d0a4", GitTreeState:"clean", BuildDate:"2022-06-02T09:20:24Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

39.9.0

### What happened?

```
kubectl port-forward --namespace monitoring svc/kube-prometheus-stack-prometheus 9090:9090
```

According to grafana cloud's [doc](https://grafana.com/docs/grafana-cloud/kubernetes-monitoring/prometheus/remote_write_helm_operator/), 
> Navigate to http://localhost:9090 in your browser, and then Status and Configuration. Verify that the remote_write block you appended above has propagated to your running Prometheus instances.

But there is no such `remote_write` block, also grafana cloud doesn't receive any data.

### Enter the changed values of values.yaml?

```
prometheus:
  prometheusSpec:
    remote_write:
    - url: https://prometheus-prod-18-prod-ap-southeast-0.grafana.net/api/prom/push
      basic_auth:
        username:
          name: secret-grafana-cloud
          key: username
        password:
          name: secret-grafana-cloud
          key: password
```

### Enter the command that you execute and failing/misfunctioning.

```
helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack \
              --install \
              --force \
              --reset-values \
              -n monitoring \
              --create-namespace \
              -f ./helm-charts/kube-prometheus-stack/values-all.yaml
```
