### ISSUE TITLE
[prometheus-kube-stack] Upgrade fails for chart version 36.0.3

### ISSUE THREAD

**Issue by wahani** [prometheus-community/helm-charts#2391]
### Describe the bug a clear and concise description of what the bug is.

I try to upgrade the version of my prometheus-kube-stack installation from version 36.0.3 to a higher version. It fails with

```
Error: UPGRADE FAILED: template: kube-prometheus-stack/templates/thanos-ruler/servicemonitor.yaml:1:18: executing "kube-prometheus-stack/templates/thanos-ruler/servicemonitor.yaml" at <.Values.thanosRuler.enabled>: nil pointer evaluating interface {}.enabled
```

### What's your helm version?

version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.17.13"}

### What's your kubectl version?

v1.24.4

### Which chart?

kube-prometheus-stack

### What's the chart version?

36.0.3

### What happened?

I try to upgrade the version of my prometheus-kube-stack installation from version 36.0.3 to a higher version. It fails with

```
Error: UPGRADE FAILED: template: kube-prometheus-stack/templates/thanos-ruler/servicemonitor.yaml:1:18: executing "kube-prometheus-stack/templates/thanos-ruler/servicemonitor.yaml" at <.Values.thanosRuler.enabled>: nil pointer evaluating interface {}.enabled
```

To upgrade to the next higher version I use:

```
helm upgrade --reuse-values --version 36.1.0 --namespace monitoring prometheus prometheus-community/kube-prometheus-stack
```

I have tested this for different versions in 36.x and 37.x and get the same result. I get the same error message when I try to upgrade to the latest chart version. 

### What you expected to happen?

That I can upgrade to a new version of the chart.

### Enter the changed values of values.yaml?

No values have changed, I use `--reuse-values`. The original `values.yaml` looks like:

```yml
nameOverride: po

fullnameOverride: po

grafana:
  deploymentStrategy:
    type: Recreate

  ingress:
    enabled: true

    annotations:
      traefik.ingress.kubernetes.io/router.tls: "true"

    hosts: ['my.url.com']

    paths:
    - /

  persistence:
    enabled: true

prometheus:
  server:
    persistentVolume:
      enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --reuse-values --version 36.1.0 --namespace monitoring prometheus prometheus-community/kube-prometheus-stack
helm upgrade --reuse-values --namespace monitoring prometheus prometheus-community/kube-prometheus-stack
