### ISSUE TITLE
Where is Prometheus.yml file? 

### ISSUE THREAD

**Issue by jcquiles** [prometheus-community/helm-charts#2393]
Hello I am currently using this chart for Prom and Grafana on a GKE cluster and I am trying to scrape metrics for my applications. However I cannot locate the prometheus.yml file, where would that be located when using this particular chart? I tried looking in the usual `/etc/prometheus `folder also but that doesn't exist for me. 

Here are the services in my current monitoring folder
```
NAME                                                         READY   STATUS    RESTARTS   AGE
pod/alertmanager-prometheus-kube-prometheus-alertmanager-0   2/2     Running   0          22h
pod/prometheus-grafana-c7468cfd7-5x92f                       3/3     Running   0          23h
pod/prometheus-kube-prometheus-operator-557f9866b6-gxgvg     1/1     Running   0          23h
pod/prometheus-kube-state-metrics-6697746755-s8lbk           1/1     Running   0          23h
pod/prometheus-prometheus-kube-prometheus-prometheus-0       2/2     Running   0          22h

NAME                                              TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                      AGE
service/alertmanager-operated                     ClusterIP   None          <none>        9093/TCP,9094/TCP,9094/UDP   22h
service/prometheus-grafana                        ClusterIP   10.85.2.191   <none>        80/TCP                       23h
service/prometheus-kube-prometheus-alertmanager   ClusterIP   10.85.3.80    <none>        9093/TCP                     23h
service/prometheus-kube-prometheus-operator       ClusterIP   10.85.2.210   <none>        443/TCP                      23h
service/prometheus-kube-prometheus-prometheus     ClusterIP   10.85.0.144   <none>        9090/TCP                     23h
service/prometheus-kube-state-metrics             ClusterIP   10.85.3.64    <none>        8080/TCP                     23h
service/prometheus-operated                       ClusterIP   None          <none>        9090/TCP                     22h

NAME                                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/prometheus-grafana                    1/1     1            1           23h
deployment.apps/prometheus-kube-prometheus-operator   1/1     1            1           23h
deployment.apps/prometheus-kube-state-metrics         1/1     1            1           23h

NAME                                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/prometheus-grafana-c7468cfd7                     1         1         1       23h
replicaset.apps/prometheus-kube-prometheus-operator-557f9866b6   1         1         1       23h
replicaset.apps/prometheus-kube-state-metrics-6697746755         1         1         1       23h

NAME                                                                    READY   AGE
statefulset.apps/alertmanager-prometheus-kube-prometheus-alertmanager   1/1     22h
statefulset.apps/prometheus-prometheus-kube-prometheus-prometheus       1/1     22h
```

**Comment by cp-weng** [comment]
Consider using `ServiceMonitor` CRD to scrape metrics from your k8s `Service`.

let's say you have a service like next:

```yml
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.project.name }}
  labels: # [^1]
    app.selector: {{ .Values.project.name }}
spec:
  selector:
    app: {{ .Values.project.name }}
  ports:
  - name: web # [^2]
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
```

then you can add `ServiceMonitor` like next:

```yml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.project.name }}
  namespace: monitoring # [^3]
  labels:
    release: kube-prometheus-stack # [^4]
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels: # [^1]
      app.selector: {{ .Values.project.name }}
  endpoints:
    - path: /metrics
      port: web # [^2]
```

with following gotcha:

- 1: you should add a label to let ServiceMonitor to select
- 2: must use port `name` rather than port `number`
- 3: should be the same namespace of `Prometheus` instance
- 4: should match exactly what your prometheus defines
  ```shell
  $ kubectl -n monitoring describe prometheus kube-prometheus-stack-prometheus
  ...
  Spec:
    ...
    Service Monitor Selector:
      Match Labels:
        Release:  kube-prometheus-stack # use this release
  ...
  ```
