### ISSUE TITLE
prometheus-kube-stack- Prometheus  not accepting image from AWS ECR or Local 

### ISSUE THREAD

**Issue by srreddy2020** [prometheus-community/helm-charts#2399]
### Describe the bug a clear and concise description of what the bug is.

Hello All,
Recently I installed kube-prometheus-stack in my environment. version: 39.9.0,appVersion: 0.58.0.

All the images which are required for this stack , we uploaded to our AWS ECR.

When I try to deploy the stack with helm chart, Alertmanager and prometheus  statefulsets are not deploying.
statefulset.apps/kube-prometheus-alertmanager
statefulset.apps/kube-prometheus-prometheus.
I observed that if i use the images for above statefulsets from Internet, everything is working fine.
Which means kube-prometheus-stack statefulsets are not accepting AWS ECR or Local Image which we downloaded from internet, though the versions are same.

One more thing after deploying the kube-prometheus stack as it is from internet ,if i edit the statefulsets  and change the image location to our ECR and save the file, but still its not changing and taking from internet.

There is no issue in communicating to AWS ECR, as other deployments are working with ECR image like grafana,node-exporter,kubestate-metrics etc.

### What's your helm version?

version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}

### What's your kubectl version?

Client Version: v1.22.5 Server Version: v1.22.10-eks-84b4fe6

### Which chart?

kube-prometheus-stack

### What's the chart version?

version: 39.9.0,appVersion: 0.58.0

### What happened?

All the images which are required for this stack , we uploaded to our AWS ECR.

When I try to deploy the stack with helm chart, Alertmanager and prometheus  statefulsets are not deploying.
statefulset.apps/kube-prometheus-alertmanager
statefulset.apps/kube-prometheus-prometheus.
I observed that if i use the images for above statefulsets from Internet, everything is working fine.
Which means kube-prometheus-stack statefulsets are not accepting AWS ECR or Local Image which we downloaded from internet, though the versions are same.

One more thing after deploying the kube-prometheus stack as it is from internet ,if i edit the statefulsets  and change the image location to our ECR and save the file, but still its not changing and taking from internet.

### What you expected to happen?

I want to use (statefulset.apps/kube-prometheus-alertmanager ,statefulset.apps/kube-prometheus-prometheus.) the image which we uploaded to AW ECR

### How to reproduce it?

Take the image versions of Prometheus and alertmanager  from stack values file and  upload the docker images to AWS ECR .
Replace the Images which are uploaded to AWS ECR

### Enter the changed values of values.yaml?

```
alertmanager:
  alertmanagerSpec:
    nodeSelector: 
      platts-node-group: common
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: aws-efs
          accessModes: 
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
    image:
      repository: aws-ecr-repo/alertmanager-image
      tag: alertmanager-v0.24.0
```
----------------------------
prometheus:
  prometheusSpec:
    scrapeInterval: "10s"
    nodeSelector: 
      platts-node-group: common
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: aws-efs
          accessModes: 
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
    image:
      repository: AWS-ECR-repo/prometheus-image
      tag: prometheus-v2.37.0

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install monitoring prometheus-community/kube-prometheus-stack -n namespace -f values.yaml
