### ISSUE TITLE
[prometheus-kube-stack] prometheus is not deploying

### ISSUE THREAD

**Issue by jeremydescamps** [prometheus-community/helm-charts#2400]
### Describe the bug a clear and concise description of what the bug is.

Hi guys,

I am using your chart in version `36.0.0` with a custom `values.yaml` file that contains the following :

```yaml
alertmanager:
  alertManagerSpec:
    image:
      repository: xxxx.dkr.ecr.eu-west-3.amazonaws.com/kube-prometheus-stack_docker_images
      tag: alertmanager-v0.24.0
    retention: 4320h

grafana:
  enabled: true
  image:
    repository: xxxx.dkr.ecr.eu-west-3.amazonaws.com/kube-prometheus-stack_docker_images
    tag: grafana-v9.0.5
  testFramework:
    enabled: true
    repository: xxxx.dkr.ecr.eu-west-3.amazonaws.com/kube-prometheus-stack_docker_images
    tag: bats-v1.4.1
  downloadDashboardsImage:
    repository: xxxx.dkr.ecr.eu-west-3.amazonaws.com/kube-prometheus-stack_docker_images
    tag: curl-v7.73.0
  initChownData:
    enabled: false
  imageRenderer:
    repository: xxxx.dkr.ecr.eu-west-3.amazonaws.com/kube-prometheus-stack_docker_images
    tag: grafana-image-renderer-latest
  sidecar:
    image:
      repository: xxxx.dkr.ecr.eu-west-3.amazonaws.com/kube-prometheus-stack_docker_images
      tag: k8s-sidecar-v1.19.2

kube-state-metrics:
  image:
    repository: xxxx.dkr.ecr.eu-west-3.amazonaws.com/kube-prometheus-stack_docker_images
    tag: kube-state-metrics-v2.5.0

prometheus-node-exporter:
  image:
    repository: xxxx.dkr.ecr.eu-west-3.amazonaws.com/kube-prometheus-stack_docker_images
    tag: node-exporter-v1.3.1

prometheusOperator:
  image:
    repository: xxxx.dkr.ecr.eu-west-3.amazonaws.com/kube-prometheus-stack_docker_images
    tag: prometheus-operator-v0.58.0
  admissionWebhooks:
    enabled: true
    patch:
      image:
        repository: xxxx.dkr.ecr.eu-west-3.amazonaws.com/kube-prometheus-stack_docker_images
        tag: kube-webhook-certgen-v1.2.0
  prometheusConfigReloader:
    image:
      repository: xxxx.dkr.ecr.eu-west-3.amazonaws.com/kube-prometheus-stack_docker_images
      tag: prometheus-config-reloader-v0.57.0

prometheus:
  enabled: true
  prometheusSpec:
    image:
      repository: xxxx.dkr.ecr.eu-west-3.amazonaws.com/kube-prometheus-stack_docker_images
      tag: prometheus-v2.37.0
    retention: 180d #metric retain
```

When deployed, I can see the following pods : 

```sh
 kubectl get pods -n prometheus
NAME                                                     READY   STATUS    RESTARTS   AGE
alertmanager-prometheus-kube-prometheus-alertmanager-0   2/2     Running   0          13m
prometheus-grafana-75d7546bb5-rjl4j                      3/3     Running   0          13m
prometheus-kube-prometheus-operator-6676fd8777-wh9q2     1/1     Running   0          13m
prometheus-kube-state-metrics-7b7549454c-84gsq           1/1     Running   0          13m
prometheus-prometheus-node-exporter-8f9nn                0/1     Pending   0          13m
prometheus-prometheus-node-exporter-g9n4z                1/1     Running   0          13m
prometheus-prometheus-node-exporter-jm8qt                0/1     Pending   0          13m
prometheus-prometheus-node-exporter-nsqlx                0/1     Pending   0          13m
prometheus-prometheus-node-exporter-s4h5z                1/1     Running   0          13m
prometheus-prometheus-node-exporter-sgxm6                0/1     Pending   0          13m
prometheus-prometheus-node-exporter-t6dwg                0/1     Pending   0          13m
prometheus-prometheus-node-exporter-vr7ps                0/1     Pending   0          13m
prometheus-prometheus-node-exporter-w8pbg                0/1     Pending   0          13m
prometheus-prometheus-node-exporter-xh96c                0/1     Pending   0          13m
```

As you can see, there is not an existing pod dedicated to prometheus application itself.
When looking for logs in prometheus-operator : 

```
level=warn ts=2022-08-26T15:00:11.810572793Z caller=operator.go:2250 component=prometheusoperator msg="skipping servicemonitor" error="failed to parse Prometheus version: Invalid character(s) found in major number \"0prometheus-v2\"" servicemonitor=prometheus/prometheus-kube-prometheus-kubelet namespace=prometheus prometheus=prometheus-kube-prometheus-prometheus
level=error ts=2022-08-26T15:00:11.820573274Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="sync \"prometheus/prometheus-kube-prometheus-prometheus\" failed: creating config failed: failed to parse Prometheus version: Invalid character(s) found in major number \"0prometheus-v2\""
```

So yeah that's probably the reason , but I don't have `0prometheus-v2` version referenced anywhere. So I am surprised about this error message.

I've tried to delete/redeploy without any success.
Regards.

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"} [jdescamps@lgdci0007 ~]$ kubectl version Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:13:28Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-6d3986b", GitCommit:"8877a3e28d597e1184c15e4b5d543d5dc36b083b", GitTreeState:"clean", BuildDate:"2022-07-20T22:05:32Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"} [jdescamps@lgdci0007 ~]

### Which chart?

prometheus-kube-stack

### What's the chart version?

36.0.0

### Enter the command that you execute and failing/misfunctioning.

I am deploying it with argocd
