### ISSUE TITLE
[prometheus] misconfiguration in an IPv6-only environment

### ISSUE THREAD

**Issue by inistor** [prometheus-community/helm-charts#241]
**Describe the bug**
In an IPv6 only environment (where $(POD_IP) is an IPv6 address), some components are incorrectly configured:
```
MacBook-Pro:prometheus user$ grep "(POD_IP)" -R  *
templates/alertmanager/deploy.yaml:            - --cluster.advertise-address=$(POD_IP):6783
templates/alertmanager/sts.yaml:            - --cluster.advertise-address=$(POD_IP):6783
```

This results in the combination of address port being unparsable - in IPv6, the correct syntax is `[IPv6 Address]:port`.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
prometheus

**Which version of the chart**:
11.16.3

**What happened**:
In an IPv6 only environment (where $(POD_IP) is an IPv6 address), some components are incorrectly configured.

**What you expected to happen**:
The chart should work in an IPv6 only environment.

**How to reproduce it** (as minimally and precisely as possible):
Use an IPv6 only Kubernetes cluster.
Deploy the prometheus 11.16.3 chart.

localconfig.yaml (only put values which differ from the defaults)

```
alertmanager:
  persistentVolume:
    size: 1Gi
    storageClass: "ion-sc"
server:
  persistentVolume:
    size: 1Gi
    storageClass: "ion-sc"
```

```
helm install prom-instance prometheus-community/prometheus  -f localconfig.yaml
```

**Anything else we need to know**:

**Comment by monotek** [comment]
Hmm. I guess there is no automatic way to get it in the right format so solution would be to add an "ipv6Only: false" to the values file. If set to true the "[" & "]" could be added to the ipv6 address.

Has anybody a better idea to solve this?

**Comment by inistor** [comment]
Indeed, and this also needs to take into account the relatively recent dualStack feature of k8s.
From where I see it, there are the following options:

1. relinquish the port, if this is the default:
Instead of:
```
          args:
            - --cluster.advertise-address=$(POD_IP):6783
```
use
```
          args:
            - --cluster.advertise-address=$(POD_IP)
```
If 6783 is the default, this should address the problem - of course, with no option for users when they want to use a different port.

2. use the pod's name instead of IP, relying on the k8s DNS
```
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          args:
            - --cluster.advertise-address=$(POD_NAME):6783
```
Of course, this has the drawback of relying on the k8s DNS, but, afaik, this is built-in and guaranteed to work
Both methods should work in IPv6 only and dualStack environments, plus they do work on earlier versions of k8s as well.
