### ISSUE TITLE
[prometheus-kube-stack] Configuring additional datasources does not trigger redeployment of Grafana

### ISSUE THREAD

**Issue by sbr82** [prometheus-community/helm-charts#2424]
### Describe the bug a clear and concise description of what the bug is.

Configuring additional datasources in the values.yaml, updates the ConfigMap kube-prometheus-grafana-datasource correctly, but does not trigger redeployment of the grafana pod, one needs to manually restart for changes to take effect.

values.yaml
```
  grafana:
    additionalDataSources:        
      - name: Logging
        type: loki
        access: proxy
        url: http://logging-loki-loki-distributed-gateway.logging
```

the content generated config map, kube-prometheus-grafana-datasource:
```
apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  url: http://prometheus-kube-prometheus-prometheus.monitoring:9090/
  access: proxy
  isDefault: true
  jsonData:
    timeInterval: 30s
- access: proxy
  name: Logging
  type: loki
  url: http://logging-loki-loki-distributed-gateway.logging
```

The reason for this is because this ConfigMap is not included in the checksum annotations of the grafana pod.

```
apiVersion: v1
kind: Pod
metadata:
  name: prometheus-grafana-564cf6bd9f-fx6jh
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  annotations:
    checksum/config: <checksum>
    checksum/dashboards-json-config: <checksum>
    checksum/sc-dashboard-provider-config: <checksum>
    checksum/secret: <checksum>
```

Is there a possibility to include the checksum of kube-prometheus-grafana-datasource?

### What's your helm version?

v3.9.1

### What's your kubectl version?

v1.21.6

### Which chart?

prometheus-kube-stack

### What's the chart version?

39.11.0

### Enter the command that you execute and failing/misfunctioning.

the deployment is triggered by flux2

**Comment by trallnag** [comment]
@sbr82, are you still facing this issue?

**Comment by sbr82** [comment]
yes this is still an issue

**Comment by trallnag** [comment]
@aek-arm, I can't. I don't have the required permissions.

**Comment by aek-arm** [comment]
Thanks @trallnag - opened a new issue referencing this one

**Comment by chis0m** [comment]
Though this issue is already closed, but adding this for any who needs it. To solve the problem of grafana not loading datasources automatically, I had to add a. job to handle the restarting of grafana server within the grafana pod deployed by kube-prometheus stack. Here you go

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-reload-job
  namespace: monitoring
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: monitoring-grafana
      containers:
        - name: kubectl-exec
          image: bitnami/kubectl:latest
          command: ["/bin/sh"]
          args:
            - -c
            - |
              POD=$(kubectl get pod -n monitoring -l app.kubernetes.io/name=grafana -o jsonpath="{.items[0].metadata.name}")
              kubectl exec -it -n monitoring $POD -- sh -c "kill \$(ps aux | grep '[g]rafana server' | awk '{print \$1}')"
      restartPolicy: Never
```

The service account is the that created by the helm chart. I just attached it to the job.
