### ISSUE TITLE
[kube-prometheus-stack] adding wmi exporter targets 

### ISSUE THREAD

**Issue by Quinnzoel** [prometheus-community/helm-charts#2433]
### Describe the bug a clear and concise description of what the bug is.

Is there anyway to pull metrics from an external machine? I have a wmi exporter running on a windows server on port 9115 so it configured my prometheus.yml like this:
`rule_files:
- /etc/prometheus/rules/prometheus-prom-kube-prometheus-stack-prometheus-rulefiles-0/*.yaml
scrape_configs:
- job_name: 'WMI_Exporter'
  scrape_interval: 5s
  scrape_timeout: 5s
  static_configs:
  - targets: ['192.168.1.240:9115']
- job_name: serviceMonitor/monitor/prom-kube-prometheus-stack-alertmanager/0
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true`
``

but it doesn't show on prometheus targets section.

### What's your helm version?

v3.9.4

### What's your kubectl version?

1.25

### Which chart?

kube-prometheus-stack

### What's the chart version?

v39.11

### What happened?

What am i doing wrong?

### What you expected to happen?

Prometheus targets wmi exporter metrics

### Enter the command that you execute and failing/misfunctioning.

elm install -n monitor prom prometheus-community/kube-prometheus-stack -f values.yaml -f rules.yaml -f prometheus.yml

**Comment by zeritti** [comment]
Yes, there is. You can add external targets to the configuration via `additionalScrapeConfigs` in you values file. For example,
```
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'WMI_Exporter'
        scrape_interval: 5s
        scrape_timeout: 5s
        static_configs:
          - targets: ['192.168.1.240:9115']
```
It is useful to check the operator's logs and the resulting Prometheus' configuration in its console.
