### ISSUE TITLE
[prometheus-kube-stack|ThanosRuler] Cannot configure alertmanager using alertmanagerconfig

### ISSUE THREAD

**Issue by ritaCanavarro** [prometheus-community/helm-charts#2435]
### Describe the bug a clear and concise description of what the bug is.

Currently, we are trying to connect our Thanos Ruler instance to our instances of Alert Manager (replicas are 3 for HA). In order to do that, we are using AlertManagersConfig as suggested [here](https://thanos.io/tip/components/rule.md/#flags). However when we try to deploy Thanos Ruler with the following configuration:

```
        alertmanagersConfig:
           api_version: v1
           static_configs:
              - monitoring-alertmanager:9093
           scheme: http
           timeout: 30s
```

We get the following error:

`error validating data: [ValidationError(ThanosRuler.spec.alertmanagersConfig): unknown field "api_version" in com.coreos.monitoring.v1.ThanosRuler.spec.alertmanagersConfig, ValidationError(ThanosRuler.spec.alertmanagersConfig): unknown field "scheme" in com.coreos.monitoring.v1.ThanosRuler.spec.alertmanagersConfig, ValidationError(ThanosRuler.spec.alertmanagersConfig): unknown field "static_configs" in com.coreos.monitoring.v1.ThanosRuler.spec.alertmanagersConfig, ValidationError(ThanosRuler.spec.alertmanagersConfig): unknown field "timeout" in com.coreos.monitoring.v1.ThanosRuler.spec.alertmanagersConfig, ValidationError(ThanosRuler.spec.alertmanagersConfig): missing required field "key" in com.coreos.monitoring.v1.ThanosRuler.spec.alertmanagersConfig]`

Can you please help us understand the issue?

### What's your helm version?

v3.8.0+gd141386

### What's your kubectl version?

v1.23.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

39.8.0

### How to reproduce it?

Launch a Thanos Ruler instance with the configuration that is presented in this bug issue.

### Enter the changed values of values.yaml?

    alertmanagersConfig:
       - api_version: v1
         static_configs:
           - monitoring-alertmanager:9093
         scheme: http
         timeout: 30s

Changed this configuration under ThanosRulerSpec.

### Enter the command that you execute and failing/misfunctioning.

We installed it via ArgoCD.

**Comment by zeritti** [comment]
Field `thanosRuler.thanosRulerSpec.alertmanagersConfig` does not hold the configuration itself as it is *SecretKeySelector* ([API](https://github.com/prometheus-operator/prometheus-operator/blob/v0.58.0/Documentation/api.md#thanosrulerspec)). That is, it points to a secret given in the field `name` and its key set in the field `key` that is holding the configuration you wish to pass to the ruler. 

For instance, if secret `thanos_ruler_config` holds the ruler configuration under the key `config`, one might then define something like the following:
```
thanosRuler:
  thanosRulerSpec:
    alertmanagersConfig:
      name: thanos_ruler_config
      key: config
```

**Comment by ritaCanavarro** [comment]
Hi @zeritti, thanks for answering. We ended up figuring it out by comparing this with the Prometheus Configuration and the secret structure by checking the source code of Thanos. 

However, a future improvement could be to update the example on the [values](https://github.com/prometheus-community/helm-charts/blob/61812c804f404707e2ab1b4bb0975008601e1b07/charts/kube-prometheus-stack/values.yaml#L3250) as it does not reflect the use of a SecretKeySelector.

Our final solution was similar to this:
```
        alertmanagersConfig:
          key: alertmanager-configs.yaml
          name: monitoring-thanosruler-am-confg

      extraSecret:
        name: "monitoring-thanosruler-am-confg"
        data: 
          alertmanager-configs.yaml: |
            alertmanagers:
            - static_configs: ["monitoring-alertmanager:9093"]
              scheme: http
              timeout: 30s
              api_version: v1
```
