### ISSUE TITLE
[kube-prometheus-stack]-`additionalScrapeConfigs` does not seems to work

### ISSUE THREAD

**Issue by rdeville-pro** [prometheus-community/helm-charts#2438]
### Describe the bug a clear and concise description of what the bug is.

`metric_relabel_configs` in `additionalScrapeConfigs` in `values.yaml` are present on the prometheus operator but not applied.

### What's your helm version?

version.BuildInfo{Version:“v3.6.2”, GitCommit:“ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:“clean”, GoVersion:“go1.16.5"}

### What's your kubectl version?

Client Version: [version.Info](http://version.Info){Major:“1”, Minor:“25", GitVersion:“v1.25.0”, GitCommit:“a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:“clean”, BuildDate:“2022-08-23T17:36:43Z”, GoVersion:“go1.19”, Compiler:“gc”, Platform:“darwin/arm64”}

### Which chart?

kube-prometheus-stack

### What's the chart version?

39.4.0

### What happened?

When using following `values.yaml` in the helm chart to add `scrape_config` to prometheus operator. The job is present in the prometheus operator configuration, i.e. it is present in http://prometheuip:9090/config as well as in the container.

But the metrics starting with `etcd_` are still present when we request it using promQL. Label `id` is still present too and metrics `apiserver_request_duration_seconds_bucket` still have label `__name__` (this one is checked on grafana as it is a special label added by prometheus).

```yaml
# Small extract of the file values.yaml used to deploy the chart
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: foo
        honor_timestamps: true
        scrape_interval: 15s
        metric_relabel_configs:
          - action: labeldrop
            regex: 'id'
          - source_labels: [__name__]
            action: drop
            regex: 'etcd_.*'
          - source_labels: [__name__]
            regex: 'apiserver_request_duration_seconds_bucket'
            action: replace
            target_label: foo
```

### What you expected to happen?

If we refer to the [documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config), `metric_relabel_configs` should :

* drop label `id` on every metrics
* drop every metrics starting with `etcd_`
* rename label `__name__` to `foo` for metrics `apiserver_request_duration_seconds_bucket`

### How to reproduce it?

* Set above configuration in your file `values.yaml`,
* Deploy the helm chart using this values.
* Enter the pod prometheus operator and ensure that config is present with following commands (to run within the container):

```bash
# In the container
grep -A 13 'job_name: foo' /etc/prometheus/config_out/prometheus.env.yaml
```

* Ensure configuration is valid:

```bash
# Still in the container
promtool query instant 'http://localhost:9090' 'etcd_request_duration_seconds_bucket'
```

This will output values while it should not.

### Enter the changed values of values.yaml?

```yaml
# Small extract of the file values.yaml used to deploy the chart
fullnameOverride: "prom-operator"

defaultRules:
  create: true
  rules:
    etcd: false

serviceMonitor:
  interval: "30s"

prometheus:
  prometheusSpec:
    scrape_interval: "30s"

    image:
      repository: quay.io/prometheus/prometheus
      tag: v2.37.0
      sha: ""

    externalLabels:
      prometheus_instance: prom-instance-name
      __tenant_id__: prom-instance-name

    prometheusExternalLabelName: ""

    probeSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

    additionalScrapeConfigs:
      - job_name: foo
        honor_timestamps: true
        scrape_interval: 15s
        metric_relabel_configs:
          - action: labeldrop
            regex: 'id'
          - source_labels: [__name__]
            action: drop
            regex: 'etcd_.*'
          - source_labels: [__name__]
            regex: 'apiserver_request_duration_seconds_bucket'
            action: replace
            target_label: foo
```

### Enter the command that you execute and failing/misfunctioning.

helm install my-release prometheus-community/kube-prometheus-stack --version 39.4.0 -f values.yaml -n monitoring

**Comment by rdeville-pro** [comment]
We finally found were the issue come from. 

The fact is our job `foo` were not responsible for the scrape of the metrics we wanted to drop. For instance, metrics `etcd_.*` were scraped by `apiserver` job from a service monitor.

So we had to put our rules in in the corresponding key in the `values.yaml`. For instance, for the `etcd_.*` metrics:

```yaml
---
# Small extract of the file values.yaml used to deploy the chart
fullnameOverride: "prom-operator"
## Component scraping the kube api server
kubeApiServer:
  enabled: true
  ## MetricRelabelConfigs to apply to samples after scraping, but before ingestion.
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
  ##
  serviceMonitor:
    metricRelabelings: 
    # Drop excessively noisy apiserver buckets.
     - source_labels: [__name__]
       action: drop
       regex: 'etcd_.*'


```

**Comment by sojjan1337** [comment]
Hello!
I'm trying to remove/drop two metric/label's in Prometheus but with no luck. Using the kube-prometheus-stack helm-chart. When i'm searching for the 10 biggest metrics in grafana/explorer i found two of them that i want drop/remove.
`topk(10, count by (name)({name=~".+"}))`
In the prometheus GUI i find it by typing this:
`{job="kubelet", name="DynamicCABundle-client-ca-bundle"}`
I have tried with the following:
```
prometheus:
  prometheusSpec:

    remoteWrite:
      - url: https://mimir.test.com/api/v1/push
    additionalScrapeConfigs:
      - job_name: test
        metric_relabel_configs:
        - regex: (DynamicCABundle-client-ca-bundle|DynamicClientCertificate)
          action: labeldrop
```
Thanks for all help i can get! :)

**Comment by sojjan1337** [comment]
worked with:

kubelet:
  serviceMonitor:
    cAdvisorMetricRelabelings:
      - sourceLabels: [__name__]
        action: drop
        regex: 'DynamicC.+'

**Comment by sojjan1337** [comment]
also tried with:

```
kubelet:
  serviceMonitor:
    cAdvisorMetricRelabelings:
      - sourceLabels: [name]
        action: drop
        regex: 'DynamicC.+'
```
