### ISSUE TITLE
prometheus-blackbox-exporter: fails rendering PrometheusRule containing {{ }}-substitutions

### ISSUE THREAD

**Issue by mkoertgen** [prometheus-community/helm-charts#2450]
### Describe the bug a clear and concise description of what the bug is.

The blackbox-exporter chart uses `tpl (toYaml .)` which breaks the usual substitutions `{{ $labels.instance }}` used in rules like, e.g.

```
serviceMonitor:
      enabled: true
      prometheusRule:
        enabled: true
        rules: # Some examples from https://awesome-prometheus-alerts.grep.to/rules.html#loki
          - alert: LokiProcessTooManyRestarts
            expr: changes(process_start_time_seconds{job=~"loki-headless"}[15m]) > 2
            for: 0m
            labels:
              severity: warning
              namespace: observability
            annotations:
              summary: Loki process too many restarts (instance {{ $labels.instance }})
              description: "A loki process had too many restarts (target {{ $labels.instance }})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```

Here is the mentioned line
- [charts/prometheus-blackbox-exporter/templates/prometheusrule.yaml#L18](https://github.com/prometheus-community/helm-charts/blob/61812c804f404707e2ab1b4bb0975008601e1b07/charts/prometheus-blackbox-exporter/templates/prometheusrule.yaml#L18)

Most other charts I know (grafana/*, ingress-nginx) just use "toYaml" directly, no need to pipe this again through the go/heml teplating.

I will be happy to submit a short PR for this, unless I would need to jump to too many hoops.

### What's your helm version?

version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}

### What's your kubectl version?

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.                                                                            Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"windows/a md64"}                                                                                                                                                                                                                                         Kustomize Version: v4.5.7                                                                                                                                                                                                                      Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-15T05:51:30Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/a md64"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

### Which chart?

prometheus-blackbox-exporter

### What's the chart version?

5.8.2 (latest at the time of writing)

### What happened?

Flux upgrade failed. Output

```slack
helmrelease/blackbox-exporter.observability
reconciliation failed: Helm upgrade failed: template: prometheus-blackbox-exporter/templates/prometheusrule.yaml:18:16: executing "prometheus-blackbox-exporter/templates/prometheusrule.yaml" at <tpl (toYaml .) $>: error calling tpl: error during tpl function execution for "- alert: BlackboxProbeFailed\n  annotations:\n    dashboard: [https://grafana.usst-prod.thieme.de/d/blackbox-exporter\n](https://grafana.usst-prod.thieme.de/d/blackbox-exporter/n)    description: |-\n      Probe failed\n        VALUE = {{ $value }}\n        LABELS = {{ $labels }}\n    summary: Blackbox probe failed (instance {{ $labels.instance }})\n  expr: probe_success == 0\n  for: 1m\n  labels:\n    severity: critical\n- alert: BlackboxSlowProbe\n  annotations:\n    dashboard: [https://grafana.usst-prod…](https://grafana.usst-prod.thieme.de/d/blackbox-exporter/n) Show more
revision
5.8.2
```

### What you expected to happen?

The rules to be rendered without templating (see above)

### How to reproduce it?

Render the chart using the following values

```yaml
#--- my-values.yaml
prometheusRule:
   enabled: true
   rules:
      - alert: BlackboxProbeFailed
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Blackbox probe failed (instance {{ $labels.instance }})
          description: "Probe failed\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
          dashboard: https://grafana.${domain_name}/d/blackbox-exporter
```

On the terminal

```shell
$ helm template prometheus-community/prometheus-blackbox-exporter -f my-values.yaml

Error: template: prometheus-blackbox-exporter/templates/prometheusrule.yaml:18:16: executing "prometheus-blackbox-exporter/templates/prometheusrule.yaml" at <tpl (toYaml .) $>: error calling tpl: error during tpl function execution for "- alert: BlackboxProbeFailed\n  annotations:\n    dashboard: https://grafana.${domain_name}/d/blackbox-exporter\n    description: |-\n      Probe failed\n        VALUE = {{ $value }}\n        LABELS = {{ $labels }}\n    summary: Blackbox probe failed (instance {{ $labels.instance }})\n  expr: probe_success == 0\n  for: 1m\n  labels:\n    severity: critical": parse error at (prometheus-blackbox-exporter/templates/prometheusrule.yaml:6): undefined variable "$value"
```

### Enter the changed values of values.yaml?

prometheusRule:
   enabled: true
   rules:
      - alert: BlackboxProbeFailed
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Blackbox probe failed (instance {{ $labels.instance }})
          description: "Probe failed\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
          dashboard: https://grafana.${domain_name}/d/blackbox-exporter


### Enter the command that you execute and failing/misfunctioning.

```shell
$ helm template prometheus-community/prometheus-blackbox-exporter -f my-values.yaml

Error: template: prometheus-blackbox-exporter/templates/prometheusrule.yaml:18:16: executing "prometheus-blackbox-exporter/templates/prometheusrule.yaml" at <tpl (toYaml .) $>: error calling tpl: error during tpl function execution for "- alert: BlackboxProbeFailed\n  annotations:\n    dashboard: https://grafana.${domain_name}/d/blackbox-exporter\n    description: |-\n      Probe failed\n        VALUE = {{ $value }}\n        LABELS = {{ $labels }}\n    summary: Blackbox probe failed (instance {{ $labels.instance }})\n  expr: probe_success == 0\n  for: 1m\n  labels:\n    severity: critical": parse error at (prometheus-blackbox-exporter/templates/prometheusrule.yaml:6): undefined variable "$value"
```

### Anything else we need to know?

_No response_

**Comment by mkoertgen** [comment]
Workaround: escape the substitutions like this

```yaml
prometheusRule:
  enabled: true
  rules:
    - alert: BlackboxProbeFailed
      expr: probe_success == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Blackbox probe failed (instance {{`{{ $labels.instance }}`}})
        description: "Probe failed\n  VALUE = {{`{{ $value }}`}}\n  LABELS = {{`{{ $labels }}`}}"
        dashboard: https://grafana.${domain_name}/d/blackbox-exporter
```
