### ISSUE TITLE
kube-prometheus-stack  additional grafana dashboard while installing helm chart

### ISSUE THREAD

**Issue by sp-90** [prometheus-community/helm-charts#2477]
### Is your feature request related to a problem ?

Unable to add  required grafana dashboard while installing the helm charts 

### Describe the solution you'd like.

we can have values alone with the dashboard folder,  to import the grafana id  in the value file 
dashboards:
    default:
      kubernetes-cluster:
        gnetId: 7249
        datasource: Prometheus

### Describe alternatives you've considered.

we can have values alone with the dashboard folder,  to import the grafana id  in the value file 
dashboards:
    default:
      kubernetes-cluster:
        gnetId: 7249
        datasource: Prometheus

### Additional context.

can some one help to resolve the issue

**Comment by jgourmelen** [comment]
+1 :)

**Comment by zeritti** [comment]
I am afraid that `default` dashboard provider does not get created, at least I did not find one in the Grafana container (apart from the `sidecarProvider`).

Basically, though, what you can do is defining your own dashboard provider and importing dashboards in that provider, for example:

```
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: provider-site
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/provider-site
# now using that provider to import dashboards
  dashboards:
    provider-site:
      node-exporter-full:
        # url: https://grafana.com/api/dashboards/1860/revisions/27/download
        gnetId: 1860
        revision: 27
        datasource: Prometheus
```
