### ISSUE TITLE
[all] support global config

### ISSUE THREAD

**Issue by lusson-luo** [prometheus-community/helm-charts#2493]
### Is your feature request related to a problem ?

Consider offering support global config, for registry, imagePullSecrets, storageClass etc common config

```
## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""
```

### Describe the solution you'd like.

add a common chart to handle global config, like bitnami/common 
https://github.com/bitnami/charts/tree/master/bitnami/common

### Describe alternatives you've considered.

now I have made a go cmd, configured by regex, and replaced in values
