### ISSUE TITLE
prometheus-blackbox-exporter is invalid: spec.endpoints.relabelings: Invalid value: "null": spec.endpoints.relabelings in body must be of type array

### ISSUE THREAD

**Issue by davidg-datascene** [prometheus-community/helm-charts#2498]
### Describe the bug a clear and concise description of what the bug is.

When installing the  prometheus-blackbox-exporter the following error message is displayed:

ServiceMonitor.monitoring.coreos.com "prometheus-blackbox-exporter-delivery" is invalid: spec.endpoints.relabelings: Invalid value: "null": spec.endpoints.relabelings in body must be of type array: "null"

### What's your helm version?

version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}

### What's your kubectl version?

version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"767d382613a87705d5ee3e6b1adf6c041089f27f", GitTreeState:"clean", BuildDate:"2022-06-21T17:11:30Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-blackbox-exporter

### What's the chart version?

'>= 5.8.0'

### What happened?

ServiceMonitor fails to install

### What you expected to happen?

The ServiceMonitor to install correctly as part of the helm template.

### How to reproduce it?

my-values.yaml
```yaml
USER-SUPPLIED VALUES:
serviceMonitor:
  defaults:
    labels:
      release: prometheus-operator
  enabled: true
  targets:
  - name: delivery
    url: https://mysite.com/auth/login
```
```bash
helm upgrade -i -n monitoring bb-test  prometheus-community/prometheus-blackbox-exporter --version v7.0.1 -f /tmp/my-values.yaml
```

### Enter the changed values of values.yaml?

```yaml
USER-SUPPLIED VALUES:
serviceMonitor:
  defaults:
    labels:
      release: prometheus-operator
  enabled: true
  targets:
  - name: delivery
    url: https://mysite.com/auth/login
```

### Enter the command that you execute and failing/misfunctioning.

```bash
helm upgrade -i -n monitoring bb-test  prometheus-community/prometheus-blackbox-exporter --version v7.0.1 -f /tmp/my-values.yaml
```

### Anything else we need to know?

It works if I pass a key-value for **_additionalRelabeling_**

```yaml
USER-SUPPLIED VALUES:
serviceMonitor:
  defaults:
    labels:
      release: prometheus-operator
   additionalRelabeling:
      - ignore: "false"
  enabled: true
  targets:
  - name: delivery
    url: https://mysite.com/auth/login
```
