### ISSUE TITLE
[kube-prometheus-stack] add env to thanos-sidecar

### ISSUE THREAD

**Issue by daveoy** [prometheus-community/helm-charts#2513]
(Forwarded from slack)

What is the mechanism through which I can propagate env variables to a thanos sidecar using the Prometheus operator? I didn’t see anywhere in the thanosSpec here https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#thanosspec. There doesn’t appear to be any keys in the values.yaml of the kube-prometheus-stack either. 

I need to set http_proxy, https_proxy and no_proxy to facilitate object storage replication by thanos in a very unique networking environment.

**Comment by daveoy** [comment]
trying the suggestion here: https://github.com/prometheus-operator/prometheus-operator/pull/2445#issuecomment-529986334 will report back and close in case someone else comes looking for this

**Comment by daveoy** [comment]
looks like this works:

```
      prometheusSpec:
        containers:
        - name: thanos-sidecar
          env:
          - name: OBJSTORE_CONFIG
            valueFrom:
              secretKeyRef:
                key: object-store.yaml
                name: thanos-gcs-config
          - name: HTTPS_PROXY
            value: "squid-b:3128"
          - name: HTTP_PROXY
            value: "squid-b:3128"
          - name: NO_PROXY
            value:  "172.16.104.0/21,172.16.96.0/21,10.0.0.0/8,127.0.0.1,localhost,.monitoring.svc.cluster.local,.svc.cluster.local
```

hope it helps someone else!
