### ISSUE TITLE
[kube-prometheus-stack] expose livenessProbe and readinessProbe

### ISSUE THREAD

**Issue by Tocknicsu** [prometheus-community/helm-charts#252]
**Is your feature request related to a problem? Please describe.**  
  
I use longhorn as storageclass for prometheus. And after longhorn restart, all containers using longhorn storage need to restart. Longhorn officially provide a [solution](https://longhorn.io/docs/0.8.0/users-guide/recover-volume/#recommended-setup-when-using-longhorn-volumes) that use livenessProbe to solve this problem. However, I can't find an easy way to do it in kube-prometheus-stack helm chart.
  
**Describe the solution you'd like**  
Expose prometheus livenessProbe and readinessProbe, so we can just edit it in values.yaml.

**Comment by RangelReale** [comment]
I'm having problems with this too, I am deploying in GKE, and the default readinessProbe is only 5 seconds, but my container is taking more than this at startup, and I can't seem to be able to change this.

**Comment by RangelReale** [comment]
I discovered in  prometheus-operator/prometheus-operator#3587 that it is possible to do this:

```
  prometheusSpec:
    # Set absurdly high thresholds as a workaround for not being able to disable these and not having enough time to WAL replay
    containers:
    - name: prometheus
      livenessProbe:
        failureThreshold: 1000
      readinessProbe:
        failureThreshold: 1000
```
This fixed my problem.
