### ISSUE TITLE
[prometheus] Support secret in extraEnv for alertmanager

### ISSUE THREAD

**Issue by MateuszKuchniak-TomTom** [prometheus-community/helm-charts#253]
**Is your feature request related to a problem? Please describe.**
Support for secrets in extraEnv for Alert manager. For example I would like to setup secrets for Alertmanager integrations with PagerDuty or Slack. I don't want store the integration keys in plain text therefore I would like to set them up from K8S secrets. 

**Describe the solution you'd like**
possibility to set secretKeyRef in values.yaml for extraEnv in alertmanager. 

Example from values.yaml

```
extraEnv:
  - name: MY_ENV_SECRET
    valueFrom:
      secretKeyRef:
        name: my-k8s-secret
        key: my-k8s-secret-key
```

At the moment when I try to set this up i receive following error: 
```
coalesce.go:196: warning: cannot overwrite table with non table for extraEnv (map[])
coalesce.go:196: warning: cannot overwrite table with non table for extraEnv (map[])
```

Kind Regards
