### ISSUE TITLE
[kube-prometheus-stack] Incorrect label for Prometheus Pod anti-affinity

### ISSUE THREAD

**Issue by gordonm** [prometheus-community/helm-charts#2548]
### Describe the bug a clear and concise description of what the bug is.

Firstly, thanks for this chart!

In the Prometheus operator spec, one `matchExpression` for Pod anti-affinity does not work as expected if `values.cleanPrometheusOperatorObjectNames` is defined, the label is set here:

https://github.com/prometheus-community/helm-charts/blob/92a69db2825845e3032a6834dec21e9ec6a5f557/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L242

If I'm reading the helpers correctly, I believe the template value here should be `{{ template "kube-prometheus-stack.prometheus.crname" . }}`, which should fall back to the current value if `crname` is not used:

https://github.com/prometheus-community/helm-charts/blob/51b62aba4e145056c7b4a8f39a1145c076636d54/charts/kube-prometheus-stack/templates/_helpers.tpl#L32-L39

### What's your helm version?

version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10", GitCommit:"7e54d50d3012cf3389e43b096ba35300f36e0817", GitTreeState:"clean", BuildDate:"2022-08-17T18:32:54Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.10-eks-15b7512", GitCommit:"cd6399691d9b1fed9ec20c9c5e82f5993c3f42cb", GitTreeState:"clean", BuildDate:"2022-08-31T19:17:01Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

40.3.1

### What happened?

With `values.fullnameOverride: kps`, the anti-affinity `matchExpression` label `prometheus` has a value of `kps-prometheus`, rather than the expected `kps` which means Prometheus Pods can be scheduled on the same node.

### What you expected to happen?

Anti-affinity `matchExpressions` labels all match and all Prometheus Pod replicas are scheduled on diverse nodes.

### How to reproduce it?

Define `values.fullnameOverride: <something>` and `values.cleanPrometheusOperatorObjectNames: true`

### Enter the changed values of values.yaml?

```
USER-SUPPLIED VALUES:
alertmanager:
  alertmanagerSpec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: karpenter.sh/capacity-type
              operator: Exists
    podAntiAffinity: hard
    podAntiAffinityTopologyKey: topology.kubernetes.io/zone
    replicas: 2
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 50Mi
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: gp3-encrypted
  podDisruptionBudget:
    enabled: true
cleanPrometheusOperatorObjectNames: true
fullnameOverride: kps
grafana:
  enabled: false
kube-state-metrics:
  fullnameOverride: kps-kube-state-metrics
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi
kubeEtcd:
  enabled: false
prometheus:
  podDisruptionBudget:
    enabled: true
  prometheusSpec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: karpenter.sh/capacity-type
              operator: Exists
    podAntiAffinity: hard
    podAntiAffinityTopologyKey: topology.kubernetes.io/zone
    replicas: 2
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 100Mi
    retention: 10d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: io1-encrypted
    walCompression: true
prometheus-node-exporter:
  fullnameOverride: kps-node-exporter
  resources:
    limits:
      cpu: 200m
      memory: 50Mi
    requests:
      cpu: 100m
      memory: 30Mi
prometheusOperator:
  admissionWebhooks:
    patch:
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 64Mi
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
```

### Enter the command that you execute and failing/misfunctioning.

N/A: chart installs normally
