### ISSUE TITLE
[prometheus] No affinity in prometheus-node-exporter chart

### ISSUE THREAD

**Issue by andrewhibbert** [prometheus-community/helm-charts#2551]
### Describe the bug a clear and concise description of what the bug is.

No affinity in prometheus-node-exporter chart

### What's your helm version?

3.8.2

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-6d3986b", GitCommit:"d4be14f563712c4e1964fe8a4171ca353b6e7e1a", GitTreeState:"clean", BuildDate:"2022-07-20T22:04:24Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1

### Which chart?

prometheus

### What's the chart version?

latest

### Enter the command that you execute and failing/misfunctioning.

Review the helm chart

**Comment by monotek** [comment]
why do you want affinity for a deamonset?

**Comment by andrewhibbert** [comment]
To stop it trying to run on fargate:
```
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
            - key: kubernetes.io/arch
              operator: In
              values:
              - amd64
              - arm64
            - key: eks.amazonaws.com/compute-type
              operator: NotIn
              values:
              - fargate
              ```

**Comment by monotek** [comment]
why not using taints and tolerations?

**Comment by andrewhibbert** [comment]
Could do just have quite a lot of taints so would prefer not to

**Comment by kaisbaccour** [comment]
I had this same issue but solved it.
I run `prometheus-community` prometheus chart
I have some nodes that run with fargate and some with karpenter.
I just added this to the helm chart.

```yaml
prometheus-node-exporter:
  nodeSelector:
        karpenter.sh/registered : "true"
```

The node exporter chart from that repo has this

```yaml
{{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
 {{- end }}
```
Which means it has the flexibility to do what you need. Just make sure you find the right labels that are not fargate
