### ISSUE TITLE
[prometheus-cloudwatch-exporter] Template uses deprecated apiObject version for ingress

### ISSUE THREAD

**Issue by JamesWojewoda** [prometheus-community/helm-charts#2557]
### Describe the bug a clear and concise description of what the bug is.

The extensions/v1beta1 and networking.k8s.io/v1beta1 API versions of Ingress is no longer served as of v1.22.

[https://github.com/prometheus-community/helm-charts/blob/96fb933cbdedacf5cbea5da4372509f83419a970/charts/prometheus-cloudwatch-exporter/templates/_helpers.tpl#L67-L76](https://github.com/prometheus-community/helm-charts/blob/96fb933cbdedacf5cbea5da4372509f83419a970/charts/prometheus-cloudwatch-exporter/templates/_helpers.tpl#L67-L76)

### What's your helm version?

3.8.2

### What's your kubectl version?

v1.22.6

### Which chart?

prometheus-cloudwatch-exporter

### What's the chart version?

0.15.0

### What happened?

Our k8s cluster is on 1.23, and we haven't upgraded this chart in a long time. After upgrading I noticed the ingress object is attempting to use a deprecated apiobject version, clusters on 1.22 and greater should recognize `networking.k8s.io/v1`

### Enter the changed values of values.yaml?

```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/zone-type: private
    external-dns.alpha.kubernetes.io/hostname: cloudwatch.us-east-1a.foo.com
  labels: {}
  path: /
  hosts:
    - cloudwatch.us-east-1a.foo.com
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade cw-exporter --namespace monitoring ~/cw-exporter/ -f ~/cw-exporter/values.yaml
