### ISSUE TITLE
[prometheus-postgres-exporter] Use template functions to merge default queries with user defined queries

### ISSUE THREAD

**Issue by AlexDHoffer** [prometheus-community/helm-charts#2588]
### Is your feature request related to a problem ?

As it stands, you can either go with the default queries (https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-postgres-exporter/values.yaml#L153) in this chart or override them entirely (https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-postgres-exporter/templates/configmap.yaml#L14).

It would be nice to be able to use these default upstream queries, but override them as needed or add more as needed. Currently, I maintain a lot of unnecessary sql code because some instances of my exporter I like to have different queries for.

### Describe the solution you'd like.

You can use templating functions like so: https://github.com/grafana/helm-charts/commit/91bbc571f3bad5610a8ef07ef76c5e2c20f739e5

This should permit users to use the default queries but override them as needed.

### Describe alternatives you've considered.

Currently, I override the entire ``queries`` block.

**Comment by AlexDHoffer** [comment]
For instance, a quick sketch of what this might look like:

_configmap.yaml_

````
data:
  config.yaml: |
    {{- tpl (mergeOverwrite (tpl .Values.config.queries . | fromYaml)
    .Values.config.userQueries | toYaml) . | nindent 4 }}
````

_values.yaml_

````
queries: |
    pg_replication:
      query: "SELECT EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp())) as lag"
      master: true
      metrics:
        - lag:
            usage: "GAUGE"
            description: "Replication lag behind master in seconds"
````

_uservalues.yaml_

````
  userQueries:
    pg_postmaster:
      query: "SELECT pg_postmaster_start_time as start_time_seconds from pg_postmaster_start_time()"
      master: true
      metrics:
        - start_time_seconds:
            usage: "GAUGE"
            description: "Time at which postmaster started"
````
