### ISSUE TITLE
[prometheus-kube-stack] Enabling persistence => Prometheus fails to start

### ISSUE THREAD

**Issue by jloisel** [prometheus-community/helm-charts#2624]
### Describe the bug a clear and concise description of what the bug is.

When enabling persistence, Prometheus fails to start and complains about being unable to write the "/prometheus/queries.active" file.

### What's your helm version?

version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

latest

### What happened?

What I did try, without success:
- The host path mapped to persistent volume claim / persistent volume has uid 1000 / gui 2000, (given the securityContext has been left as is in values.yml)
- chmod 777 the host path folder,
- try another host path folder (the previous one was on a mounted NFS share),
- Check every possible solution in already existing issues.

No matter what I try, persistence doesn't work. Prometheus won't start. When persistence is disabled, Prometheus uses an emptyDir volume which works fine (but data is lost on upgrade).

### What you expected to happen?

Persistence should work.

### How to reproduce it?

Enable persistence.

### Enter the changed values of values.yaml?

In values.yml:

```
prometheus:
  enabled: true

  prometheusSpec:
    ## Prometheus StorageSpec for persistent data
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
    ##
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          volumeName: prometheus-db
          resources:
            requests:
              storage: 10Gi
```

My persistent volume:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-db
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/nfs/prometheus
    type: DirectoryOrCreate
  storageClassName: ''
```

### Enter the command that you execute and failing/misfunctioning.

```
KUBECTL = kubectl --kubeconfig ../../config
HELM = helm --kubeconfig ../../config

NAME = kube-prometheus-stack
NAMESPACE = monitoring
CHART = prometheus-community/$(NAME)
HELM_CMD = --dependency-update -n $(NAMESPACE) --create-namespace -f values.yml $(NAME)

repo:
	helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

repo.update:
	helm repo update

create-volume:
	$(KUBECTL) create -f pv.yml

delete-volume:
	-$(KUBECTL) delete -f pv.yml

install:
	$(HELM) install $(HELM_CMD) $(CHART)
	-$(KUBECTL) create -f basic-auth.yml

```

```bash
make repo repo.update create-volume install
```

### Anything else we need to know?

Kubernetes cluster v1.23.10.

**Comment by jloisel** [comment]
OK found how to fix the issue:

```yml
prometheus:
  enabled: true

  prometheusSpec:
    ## Prometheus StorageSpec for persistent data
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
    ##
    storageSpec:
      disableMountSubPath: true
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          volumeName: prometheus-data
          storageClassName: local
          resources:
            requests:
              storage: 10Gi
```

`disableMountSubPath: true` must be set, otherwise "permission denied" (even thought I created a `prometheus` folder inside the volume itself.

It should be documented at the very least as I spend days figuring out this tricky issue.
