### ISSUE TITLE
[prometheus-kube-stack] AlertManager CRD templateFiles changes don't trigger reload

### ISSUE THREAD

**Issue by carlosjgp** [prometheus-community/helm-charts#2629]
### Describe the bug a clear and concise description of what the bug is.

Changes on `alertmanager.templateFiles` do not trigger configuration reload on Alertmanager

### What's your helm version?

version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.13-eks-15b7512", GitCommit:"94138dfbea757d7aaf3b205419578ef186dd5efb", GitTreeState:"clean", BuildDate:"2022-08-31T19:15:48Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

41.5.0

### What happened?

When using Alertmanager `alertmanager.templateFiles` changing them does not reload Alertmanager so the new changes are not picked up

### What you expected to happen?

Changes on `alertmanager.config` and `alertmanager.templateFiles` trigger Alertmanager reload

### How to reproduce it?

helm upgrade --install am-reload promethues-community/promethues-kube-stack --version 41.5.0 --values values.yaml

using this `values.yaml`
```yaml
alertmanager:
  enabled: true

  config:
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'

    route:
      group_by:
        - 'namespace'
        - 'alertname'
      group_wait: 1m
      group_interval: 5m
      repeat_interval: 6h
      receiver: 'slack'
      routes:
        - receiver: 'null'
          matchers:
            - alertname =~ "Watchdog"

    receivers:
      - name: 'null'
      - name: 'slack'
        slack_configs:
          - channel: '#{{- template "slack.alert_channel" . -}}'
            send_resolved: true
    
    templates:
      - '/etc/alertmanager/config/*.tmpl'

  templateFiles:
    namespace_routing.tmpl: |-

      {{ define "slack.alert_channel" -}}
          channel-1
      {{- end }}
```

Change any bit on `alertmanager.config` and observe Alertmanager being reloaded

Change the content of the `namespace_routing.tmpl` file and nothing happens. 
I can imagine that adding a new template file would do nothing either but I haven't tested it

### Enter the changed values of values.yaml?

alertmanager:
  enabled: true

  config:
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'

    route:
      group_by:
        - 'namespace'
        - 'alertname'
      group_wait: 1m
      group_interval: 5m
      repeat_interval: 6h
      receiver: 'slack'
      routes:
        - receiver: 'null'
          matchers:
            - alertname =~ "Watchdog"

    receivers:
      - name: 'null'
      - name: 'slack'
        slack_configs:
          - channel: '#{{- template "slack.alert_channel" . -}}'
            send_resolved: true
    
    templates:
      - '/etc/alertmanager/config/*.tmpl'

  templateFiles:
    namespace_routing.tmpl: |-

      {{ define "slack.alert_channel" -}}
          channel-1
      {{- end }}

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install am-reload promethues-community/promethues-kube-stack --version 41.5.0  --values values.yaml

### Anything else we need to know?

The Alertmanager config-reloader is only looking at the `gz` file generated by the operator
```yaml
   - args:
     - --listen-address=:8080
     - --reload-url=http://127.0.0.1:9093/-/reload
     - --config-file=/etc/alertmanager/config/alertmanager.yaml.gz
     - --config-envsubst-file=/etc/alertmanager/config_out/alertmanager.env.yaml
     - --log-level=warn
```

It looks like the config reloader functionality can manage multiple directories (files?)
https://github.com/prometheus-operator/prometheus-operator/blob/9c0db5656f04e005de6a0413fd8eb8f11ec99757/pkg/operator/config-reloader_test.go#L46
