### ISSUE TITLE
[kube-prometheus-stack] Add a URL of custom dashboard

### ISSUE THREAD

**Issue by patsevanton** [prometheus-community/helm-charts#2647]
### Is your feature request related to a problem ?

Manual installation of a custom dashboard

### Describe the solution you'd like.

I want to set https://github.com/jenkins-x-charts/grafana-dashboard/blob/master/charts/grafana-dashboard/dashboards/loki.json in values.yaml as custom dashboard.

### Describe alternatives you've considered.

NONE

### Additional context.

For example:
```
dashboards:
  default:
   some-dashboard:
     json: |
       $RAW_JSON
   custom-dashboard:
     file: dashboards/custom-dashboard.json
   prometheus-stats:
     gnetId: 2
     revision: 2
     datasource: Prometheus
   local-dashboard:
     url: https://example.com/repository/test.json
     token: ''
   local-dashboard-base64:
     url: https://example.com/repository/test-b64.json
     token: ''
     b64content: true
   local-dashboard-gitlab:
     url: https://example.com/repository/test-gitlab.json
     gitlabToken: ''
   local-dashboard-bitbucket:
     url: https://example.com/repository/test-bitbucket.json
     bearerToken: ''
```
