### ISSUE TITLE
[kube-prometheus-stack] Thanos Bad Gateway when enabled

### ISSUE THREAD

**Issue by mamu-reply** [prometheus-community/helm-charts#2656]
### Describe the bug a clear and concise description of what the bug is.

After configuring thanos in values when I try to access its host I always get Bad Gateway

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:33:06Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"} Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.6.1

### What happened?

On my EKS i've installed the helm of kube-prometheus-stack and i've enabled Thanos, but when i try to open his url i get only a Bad Gateway page

### What you expected to happen?

See Thanos UI

### How to reproduce it?

Install kube-prometheus-stack and pass to true thanos values and add an ingress

### Enter the changed values of values.yaml?

```
prometheus:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'cert-manager-letsencrypt-${local.cert_manager_issuer}-route53'
      ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    hosts:
      - '${local.prometheus_url}'
    paths:
      - /
    athType: Prefix
    tls:
      - secretName: '${local.prometheus_url}'
        hosts:
          - '${local.prometheus_url}'
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
  thanosServiceExternal:
    enabled: true
  thanosIngress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'cert-manager-letsencrypt-${local.cert_manager_issuer}-route53'
      ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    hosts:
      - '${local.thanos_url}'
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: '${local.thanos_url}'
        hosts:
          - '${local.thanos_url}'

grafana:
  adminPassword: '${local.grafana_admin_password}'
  ingress:
    enabled: 'true'
    annotations:
      cert-manager.io/cluster-issuer: 'cert-manager-letsencrypt-${local.cert_manager_issuer}-route53'
      ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    path: /
    hostname: '${local.grafana_url}'
    tls:
      - secretName: '${local.grafana_url}'
        hosts:
          - '${local.grafana_url}'
```

### Enter the command that you execute and failing/misfunctioning.

No commands, i don't receive any error
