### ISSUE TITLE
[kube-prometheus-stack] allow template values for serviceMonitorSelector in prometheus template

### ISSUE THREAD

**Issue by jsanda** [prometheus-community/helm-charts#266]
**Is your feature request related to a problem? Please describe.**
I am using the kube-prometheus-stack chart as a dependency in my chart. I want to configure the `.spec.serviceMonitorSelector` property in the prometheus template as follows:

```
matchLabels:
  app.kubernetes.io/instance: {{ .Release.Name }}
  app.kubernetes.io/part-of: my-chart
  # other labels...
```
and I have a ServiceMonitor template with labels as follows:

```
labels:
  app.kubernetes.io/instance: {{ .Release.Name }}
  app.kubernetes.io/part-of: my-chart
  # other labels...
```
**Describe the solution you'd like**
The template currently gets me part of the way there. Here is the relevant code:

```
{{- if .Values.prometheus.prometheusSpec.serviceMonitorSelector }}
  serviceMonitorSelector:
{{ toYaml .Values.prometheus.prometheusSpec.serviceMonitorSelector | indent 4 }}
{{ else if .Values.prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues  }}
  serviceMonitorSelector:
    matchLabels:
      release: {{ $.Release.Name | quote }}
{{ else }}
  serviceMonitorSelector: {}
{{- end }}
```
When `serviceMonitorSelectorNilUsesHelmValues` is `true` which I believe it is by default, the release name is used. This is great, but I would like the ability to also use additional labels, possibly some of which are generated dynamically.

**Describe alternatives you've considered**
I could just defer setting `serviceMonitrSelector` to the user. I think it can be error prone, and I anticipate users winding up with missing and/or extra, unintended scrape targets.
