### ISSUE TITLE
[kube-prometheus-stack] Makes default prometheus rules more flexible

### ISSUE THREAD

**Issue by talset** [prometheus-community/helm-charts#2662]
### Is your feature request related to a problem ?

By default, the charts create many useful prometheus rules. But for some, it could make sense to override params such `label.severity` or `for`.

Currently, those values are hardcoded so users have to disable the rule and "fork it" on their value.yml

### Describe the solution you'd like.

To allow "customization" on alerts, a map could be created and exposed on value.yml.

Example:
To change the `for` and `label.severity` from `KubePodNotReady` alert (https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml#L62-L64)

on **values.yaml**
```
defaultRules:
  customize:
    KubePodNotReady:
      for: 5m
      labels:
        severity: critical
```

on **templates/prometheus/rules-1.14/kubernetes-apps.yaml**

```
    - alert: KubePodNotReady
...
      for: {{ .Values.defaultRules.customize.KubePodNotReady.for | default "15m" }}
      labels:
        severity: {{ .Values.defaultRules.customize.KubePodNotReady.labels.severity | default "warning" }}
```

Of course, the structure/naming needs to be thought to allow more advanced usecases (add more labels on the alert, change some parts of expr ...)

### Describe alternatives you've considered.

NONE

### Additional context.

issues linked:
* https://github.com/prometheus-community/helm-charts/issues/2409
