### ISSUE TITLE
[kube-prometheus-stack] Unable to install prometheus server if prometheus-operator disabled

### ISSUE THREAD

**Issue by anthosz** [prometheus-community/helm-charts#2663]
### Describe the bug a clear and concise description of what the bug is.

Hello,

My goal is to use custom metrics for Horizontal Pod Autoscalers following this doc: https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/walkthrough.md but I don't need prometheus-operator.

What I want is simply to add all deps needed to be able to use prometheus-adapter.

With prometheus-community/prometheus, it's not possible to "kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1"

I tried prometheus-community/kube-prometheus-stack and it works but the issue is that I cannot install prometheus server without prometheus-operator.

You can find here the stack values:
```
defaultRules:
  rules:
    etcd: false
    alertmanager: false
    prometheusOperator: false
    kubeProxy: false
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false

alertmanager:
  enabled: false
grafana:
  enabled: false
prometheusOperator:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
```

### What's your helm version?

3.10.1

### What's your kubectl version?

1.23.6

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.7.3/0.60.1

### What happened?

Cannot install prometheus server without prometheus-operator

### What you expected to happen?

Install prometheus server without prometheus-operator

### How to reproduce it?

Install the chart with these values:
```
defaultRules:
  rules:
    etcd: false
    alertmanager: false
    prometheusOperator: false
    kubeProxy: false
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false

alertmanager:
  enabled: false
grafana:
  enabled: false
prometheusOperator:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
```

prometheus server will not spawn.

Workaround found:
Set to true the operator -> install the chart -> set to false the operator -> upgrade the chart

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -f values.yaml -n monitoring

### Anything else we need to know?

If possible, I can  use prometheus-community/prometheus instead but didn't find the way to add all the monitoring stuff to be able to use the prometheus-adapter.
