### ISSUE TITLE
[prometheus-adapter] LabelSelector not alterable when using metrics from an ingress controller

### ISSUE THREAD

**Issue by brconnell4** [prometheus-community/helm-charts#2667]
### Describe the bug a clear and concise description of what the bug is.

I have an ingress controller, HaProxy, reporting prometheus metrics that I am able to query with the adapter and expose in the custom api successfully. But when I set up my HPA on a service that I am serving the metrics on from the ingress controller, it is querying the custom api with a "labelSelector=" field that is including the app label of my deployment that the metrics are not being ingested from.

Since my app that I am querying metrics on has a different app label than where metrics are being queried from, the api call is successful but returns no data. There should be a way to define what labelSelectors are being used or at least remove this from the api calls. 

Example Query from Logs:

```
HTTP" verb="GET" URI="/apis/custom.metrics.k8s.io/v1beta1/namespaces/bconnell/pods/%2A/dfs_requests_per_second?labelSelector=app%3Dmwg-digital-faq-service%2Crelease%3Dbconnell" latency="5 │
│ 7.377872ms" userAgent="vpa-recommender/v0.0.0 (linux/amd64) kubernetes/$Format/kuba-horizontal-pod-autoscaler" audit-ID="768a33c9-7acd-4cd2-bcc5-8d4354e2b68f" srcIP="10.44.7.78:56020" resp=200

Response: 

{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {},
  "items": []
}
```

app=mwg-digital-faq-service is the name of the deployment label that I have my HPA pointed to. 

But because these metrics are coming from my ingress controller and not this pod, the metrics get tied to my app name instead.

```
➜  ~ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/bconnell/pods/%2A/dfs_requests_per_second?" | jq
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {},
  "items": [
    {
      "describedObject": {
        "kind": "Pod",
        "namespace": "bconnell",
        "name": "bconnell-mwg-path-routing-service-774d4f4f95-g22wd",
        "apiVersion": "/v1"
      },
      "metricName": "dfs_requests_per_second",
      "timestamp": "2022-11-09T15:36:21Z",
      "value": "166m",
      "selector": null
    }
  ]
}
```

 If I update the label selector name manually, it works with as well

```
➜  ~ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/bconnell/pods/%2A/dfs_requests_per_second?labelSelector=app%3Dmwg-path-routing-service%2Crelease%3Dbconnell" | jq
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {},
  "items": [
    {
      "describedObject": {
        "kind": "Pod",
        "namespace": "bconnell",
        "name": "bconnell-mwg-path-routing-service-774d4f4f95-g22wd",
        "apiVersion": "/v1"
      },
      "metricName": "dfs_requests_per_second",
      "timestamp": "2022-11-09T15:37:10Z",
      "value": "900m",
      "selector": null
    }
  ]
}
```

More info if its helpful:

My HPA: 

```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: bconnell-mwg-digital-faq-service
  labels:
    release: bconnell
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bconnell-mwg-digital-faq-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: dfs_requests_per_second
        target:
          type: AverageValue
          averageValue: 500m

```

My Configmap for the adapter

```

apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-adapter
    meta.helm.sh/release-namespace: prometheus
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prometheus-adapter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/part-of: prometheus-adapter
    app.kubernetes.io/version: v0.10.0
    helm.sh/chart: prometheus-adapter-3.4.1
  name: prometheus-adapter
  namespace: prometheus
data:
  config.yaml: |
    rules:
      - seriesQuery: 'haproxy_backend_http_requests_total{namespace!="", pod!="", proxy="digital-faq-service"}'
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: "^(.*)_total$"
          as: "dfs_requests_per_second"
        metricsQuery: 'sum(rate(haproxy_backend_http_requests_total{namespace!="", pod!="", proxy="digital-faq-service"}[2m])) by (<<.GroupBy>>)'
```

### What's your helm version?

3.9.3

### What's your kubectl version?

1.21.14

### Which chart?

prometheus-adapter 

### What's the chart version?

3.4.2

### What happened?

labelSelector automatically being added in from selector from deployment, but app label differs due to metrics being collected from an ingress controller whose app label is different

### What you expected to happen?

There should be a way to override the labelSelector field or turn it off and use metricSelector instead in api v2

### How to reproduce it?

Requires an ingress controller and an ingress behind it
Set up Prometheus adapater and config
Set up ingress controller - in this case Haproxy
Collect metrics from ingress controller
set up HPA on ingress / deployment 
Use metrics collected from ingress controller to scale hpa 
adapater adds labelSelector to fields

### Enter the changed values of values.yaml?

url - points to prometheus frontend that is collecting metrics on GKE

### Enter the command that you execute and failing/misfunctioning.

None, collected by logs

```
│ I1109 15:40:22.223779       1 httplog.go:131] "HTTP" verb="GET" URI="/apis/custom.metrics.k8s.io/v1beta1/namespaces/bconnell/pods/%2A/dfs_requests_per_second?labelSelector=app%3Dmwg-digital-faq-service%2Crelease%3Dbconnell" latency="6 │
│ 4.998128ms" userAgent="vpa-recommender/v0.0.0 (linux/amd64) kubernetes/$Format/kuba-horizontal-pod-autoscaler" audit-ID="775bdbf7-9ada-4fb7-880f-ce6b1688c6ed" srcIP="10.44.17.106:58330" resp=200
```

### Anything else we need to know?

None
