### ISSUE TITLE
grafana pod stuck at "crashloopbackoff"

### ISSUE THREAD

**Issue by sureshkachwa** [prometheus-community/helm-charts#2675]
### Describe the bug a clear and concise description of what the bug is.

Trying to install kube-prometheus-stack (39.8.0) and everything went well, now there is a requirement - where grafana pod needs to have a persistent vol with oci-fss as a storage class, below is my values.yaml file 
.
```
grafana:
  initChownData:
    enabled: false
  persistence:
    enabled: true
    type: pvc
    storageClassName: oci-fss
    accessModes:
    - ReadWriteMany
    size: 50Gi
    finalizers:
    - kubernetes.io/pvc-protection
   ```
grafana pod status is:
```
pod/prometheus-grafana-54cdc8774f-blfqx                      2/3     CrashLoopBackOff
```
pod logs:
```
kubectl logs -f  pod/prometheus-grafana-54cdc8774f-blfqx -n prometheus
Defaulted container "grafana-sc-dashboard" out of: grafana-sc-dashboard, grafana-sc-datasources, grafana
{"time": "2022-11-11T08:07:40.625012+00:00", "level": "INFO", "msg": "Starting collector"}
{"time": "2022-11-11T08:07:40.625190+00:00", "level": "WARNING", "msg": "No folder annotation was provided, defaulting to k8s-sidecar-target-directory"}
{"time": "2022-11-11T08:07:40.625329+00:00", "level": "INFO", "msg": "Loading incluster config ..."}
{"time": "2022-11-11T08:07:40.626083+00:00", "level": "INFO", "msg": "Config for cluster api at 'https://10.96.0.1:443' loaded..."}
{"time": "2022-11-11T08:07:40.626199+00:00", "level": "INFO", "msg": "Unique filenames will not be enforced."}
{"time": "2022-11-11T08:07:40.626283+00:00", "level": "INFO", "msg": "5xx response content will not be enabled."}
```

### What's your helm version?

v3.7.1

### What's your kubectl version?

v1.25.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

39.8.0

### What happened?

grafana stuck at "crashloopbackoff"

### What you expected to happen?

I expect my values.yaml to be correct and grafana to have a pv and to make it work

### How to reproduce it?

---

### Enter the changed values of values.yaml?

```
grafana:
  initChownData:
    enabled: false
  persistence:
    enabled: true
    type: pvc
    storageClassName: oci-fss
    accessModes:
    - ReadWriteMany
    size: 50Gi
    finalizers:
    - kubernetes.io/pvc-protection
    ```

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/kube-prometheus-stack --namespace prometheus --create-namespace \
    --values additional_values.yaml --version $2

### Anything else we need to know?

---
