### ISSUE TITLE
kube-prometheus-stack - grafana OS user privileges needs to be defined correctly

### ISSUE THREAD

**Issue by sureshkachwa** [prometheus-community/helm-charts#2677]
### Describe the bug a clear and concise description of what the bug is.

Trying to install kube-prometheus-stack (39.8.0) and everything went well, now there is a requirement - where grafana pod needs to have a persistent vol with oci-fss as a storage class, below is my values.yaml file.

```
grafana:
  initChownData:
    enabled: false
  persistence:
    enabled: true
    type: pvc
    storageClassName: oci-fss
    accessModes:
    - ReadWriteMany
    size: 50Gi
    finalizers:
    - kubernetes.io/pvc-protection
    ```
saw thatt grafana pod never came into ready state since grafana init container couldn't write into the PV created.
It was filesystem storage issue, I mounted it locally and changed the permission to 777 and pod was ready then.
Internally grafana at OS level has a user with id 472 and it was trying to write something in /var where it didnot have proper permissions.

### What's your helm version?

v3.7.1

### What's your kubectl version?

v1.25.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

39.8.0

### What happened?

grafana user with id 472 doesn't have proper permissions set to write into /var directory

### What you expected to happen?

user with id 472 needs to have proper permissions set

### How to reproduce it?

use below values.yaml and try to install kube-prometheus-stack with OCI filesystem as PV.

```
grafana:
  initChownData:
    enabled: false
  persistence:
    enabled: true
    type: pvc
    storageClassName: oci-fss
    accessModes:
    - ReadWriteMany
    size: 50Gi
    finalizers:
    - kubernetes.io/pvc-protection
    ```

### Enter the changed values of values.yaml?

```
grafana:
  initChownData:
    enabled: false
  persistence:
    enabled: true
    type: pvc
    storageClassName: oci-fss
    accessModes:
    - ReadWriteMany
    size: 50Gi
    finalizers:
    - kubernetes.io/pvc-protection
    ```

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/kube-prometheus-stack --namespace prometheus --create-namespace \
    --values additional_values.yaml --version $2 \

### Anything else we need to know?

---
