### ISSUE TITLE
Line break issue in labels

### ISSUE THREAD

**Issue by ziouf** [prometheus-community/helm-charts#2681]
When extra labels are defined with `podLabels` field, there is a line break issue like following example

```yaml
# values.yaml
podLabels:
  app: node-exporter

# generated output
  labels:
    helm.sh/chart: prometheus-node-exporter-4.5.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.3.1"app: node-exporter

# expected output
  labels:
    helm.sh/chart: prometheus-node-exporter-4.5.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.3.1"
    app: node-exporter
```

I think the issue is that we should not find a dash (`-`) at the oppenning mustache (`{{`) :
https://github.com/prometheus-community/helm-charts/blob/4da088ca394f4ae1bcce30f69a67aad5964e5800/charts/prometheus-node-exporter/templates/_helpers.tpl#L47
