### ISSUE TITLE
[kube-prometheus-stack] Prometheus Retention value not respected

### ISSUE THREAD

**Issue by nushkovg** [prometheus-community/helm-charts#2703]
### Describe the bug a clear and concise description of what the bug is.

Hi!

I have this chart deployed with Helm through ArgoCD and I have added the retention values 1 week after I've installed it, because I noticed that the PV was getting filled up, which caused Prometheus to crash and the metrics were unavailable to my Grafana dashboards. Specifically, I have set the following:

```
prometheus:
          prometheusSpec:
            retention: 5d
            retentionSize: 40GB
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 50Gi
```

I can also see that the arguments are added in the pod spec:

```
spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --web.console.templates=/etc/prometheus/consoles
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --storage.tsdb.retention.time=5d
        - --storage.tsdb.retention.size=40GB
        - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
        - --storage.tsdb.path=/prometheus
        - --web.enable-lifecycle
        - --web.external-url=http://prometheus-kube-prometheus-prometheus.monitoring:9090
        - --web.route-prefix=/
        - --storage.tsdb.wal-compression
        - --web.config.file=/etc/prometheus/web_config/web-config.yaml
```

But after 12 days, Longhorn (the storage class I am using) shows that the volume has 43/50Gi used. I am not sure if I need to set anything else as my understanding of Prometheus is quite low, but from what I read, when the retention time and size are both set, the first one to reach the value will get executed and Prometheus will remove old metrics. However, as I mentioned, this is not the case and it will lead to the same PV filling up issue that I had before.

Thanks in advance, and please let me know if I can provide more information about my environment or the chart itself.

### What's your helm version?

version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}

### What's your kubectl version?

v1.24.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.7.3

### What happened?

The retention size or time values don't get respected and Prometheus does not remove old metrics, which leads to my persistent volume filling up and crashes of the prometheus pod, which leads to Grafana not getting metrics.

### What you expected to happen?

The retention size and/or time values get respected and Prometheus removes old metrics.

### How to reproduce it?

Set the values for retention size and time and deploy the chart. For example:

```
prometheus:
          prometheusSpec:
            retention: 5d
            retentionSize: 40GB
```

### Enter the changed values of values.yaml?

prometheus:
    prometheusSpec:
        retention: 5d
        retentionSize: 40GB

### Enter the command that you execute and failing/misfunctioning.

Helm installation with ArgoCD application.
