### ISSUE TITLE
[kube-prometheus-stack] disabling the defaultRule KubeAPIErrorBudgetBurn results in a ValidationError

### ISSUE THREAD

**Issue by rrednoss** [prometheus-community/helm-charts#2704]
### Describe the bug a clear and concise description of what the bug is.

If the value _.Values.defaultRules.disabled.KubeAPIErrorBudgetBurn_ is set to true, an invalid PrometheusRule is rendered. If an attempt is made to install it in the cluster via helm install or helm upgrade the following error message occurs.

**Error Message:**
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(PrometheusRule.spec.groups[0]): missing required field "rules" in com.coreos.monitoring.v1.PrometheusRule.spec.groups
`

**Invalid PrometheusRule:**
```
# Source: kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-slos.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-kube-prometheus-kube-apiserver-slos
  namespace: default
  labels:
    app: kube-prometheus-stack    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "41.9.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-41.9.0
    release: "prometheus"
    heritage: "Helm"
spec:
  groups:
  - name: kube-apiserver-slos
    rules:
```

### What's your helm version?

3.10.2

### What's your kubectl version?

v1.23.13

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.9.0

### How to reproduce it?

Use the standard Helm chart with standard values. Update the values by disabling the default rule for KubeAPIErrorBudgetBurn.

### Enter the changed values of values.yaml?

Standard values.yaml with the below modification:

```
defaultRules:
  disabled:
    KubeAPIErrorBudgetBurn: true
```

### Enter the command that you execute and failing/misfunctioning.

helm install --dry-run -f values.yaml -n default prometheus prometheus-community/kube-prometheus-stack
