### ISSUE TITLE
[kube-prometheus-stack] Add Drop All Capability to securityContext for Operator

### ISSUE THREAD

**Issue by JuanPabloSGU** [prometheus-community/helm-charts#2705]
### Is your feature request related to a problem ?

Current it seems that

```YAML
capabilites:
  drop: 
    - ALL
```

is missing from the container security context. If the container does not require those capabilities, would it be possible to drop them by default?

### Describe the solution you'd like.

I would like to see the drop all capabilities in the 

```YAML
prometheusOperator:
  securityContext:
     capabilites:
       drop: 
         - ALL
```

As I believe that it would increase the security posture of the chart and the cluster that use it.

### Describe alternatives you've considered.

NONE
