### ISSUE TITLE
prometheus-kube-stack AlertmanagerConfig not being picked up.

### ISSUE THREAD

**Issue by jacobmammoliti** [prometheus-community/helm-charts#2707]
### Describe the bug a clear and concise description of what the bug is.

I have deployed the prometheus-kube-stack with the following Helm Values for alertmanager:
```
   alertmanager:
      alertmanagerSpec:
        alertmanagerConfigSelector:
          matchLabels:
            alertmanager: config
```
I have also deployed the following AlertmanagerConfig :
```
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-config
  namespace: monitoring
  labels:
    alertmanager: config
    release: prometheus-community
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: slack
    matchers:
      - name: severity
        value: none
  receivers:
    - name: slack
      slackConfigs:
        - sendResolved: true
          apiURL:
            name: slack-webhook-url
            key: webhook-url
          channel: '#alerts'
          title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
          text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
```

The issue is that it does not seem that alertmanager is picking up the configuration change. I went to view the pod logs and found it never refreshed the settings:

```
 kubectl logs alertmanager-kube-prometheus-stack-alertmanager-0 -n monitoring -f
````

### What's your helm version?

version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

### What's your kubectl version?

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/arm64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.9.0

### What happened?

I have deployed the AlertmanagerConfig to my cluster and the settings never seem to be applied to Alertmanager.

### What you expected to happen?

I expected that the AlertmanagerConfig would cause Alertmanager to update its settings and I expected that to be reflected in the alertmanager pod.

### How to reproduce it?

Deploy kube-prometheus-stack with the Values from above and try to deploy the AlertmanagerConfig.

### Enter the changed values of values.yaml?

```
    alertmanager:
      alertmanagerSpec:
        alertmanagerConfigSelector:
          matchLabels:
            alertmanager: config
```

### Enter the command that you execute and failing/misfunctioning.

I'm using Flux. There isn't any issues rolling the manifests out.

**Comment by tr3mor** [comment]
Config should be picked up by prometheus operator, so I would start from its logs:
```
kubectl logs <release_name>-kube-prometheus-operator-<hash>
```

**Comment by jacobmammoliti** [comment]
@tr3mor Had a look at the logs and it looks like its being picked up now. However, I'm still not getting notifications in Slack.
Here is the updated alertmanagerconfig:
```yaml
 ---
 apiVersion: monitoring.coreos.com/v1alpha1
 kind: AlertmanagerConfig
 metadata:
   name: slack-config
   namespace: monitoring
   labels:
     alertmanager: config
 spec:
   route:
     groupBy: ["job", "alertname"]
     groupWait: 30s
     groupInterval: 5m
     repeatInterval: 1m
     receiver: "slack-receiver"
     routes:
       - receiver: "slack-receiver"
         continue: true
   receivers:
     - name: "slack-receiver"
       slackConfigs:
         - sendResolved: true
           apiURL:
             name: slack-webhook-url
             key: webhook-url
             optional: false
           channel: alerts
           title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
           text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
```

And here is the config that gets generated in Alertmanager:
```
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
route:
  receiver: "null"
  group_by:
  - namespace
  continue: false
  routes:
  - receiver: monitoring/slack-config/slack-receiver
    group_by:
    - job
    - alertname
    matchers:
    - namespace="monitoring"
    continue: true
    routes:
    - receiver: monitoring/slack-config/slack-receiver
      continue: true
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1m
  - receiver: "null"
    matchers:
    - alertname=~"InfoInhibitor|Watchdog"
    continue: false
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
inhibit_rules:
- source_matchers:
  - severity="critical"
  target_matchers:
  - severity=~"warning|info"
  equal:
  - namespace
  - alertname
- source_matchers:
  - severity="warning"
  target_matchers:
  - severity="info"
  equal:
  - namespace
  - alertname
- source_matchers:
  - alertname="InfoInhibitor"
  target_matchers:
  - severity="info"
  equal:
  - namespace
receivers:
- name: "null"
- name: monitoring/slack-config/slack-receiver
  slack_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
    api_url: <secret>
    channel: alerts
    username: '{{ template "slack.default.username" . }}'
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    title: |-
      {{ range .Alerts }}{{ .Annotations.summary }}
      {{ end }}
    title_link: '{{ template "slack.default.titlelink" . }}'
    pretext: '{{ template "slack.default.pretext" . }}'
    text: |-
      {{ range .Alerts }}{{ .Annotations.description }}
      {{ end }}
    short_fields: false
    footer: '{{ template "slack.default.footer" . }}'
    fallback: '{{ template "slack.default.fallback" . }}'
    callback_id: '{{ template "slack.default.callbackid" . }}'
    icon_emoji: '{{ template "slack.default.iconemoji" . }}'
    icon_url: '{{ template "slack.default.iconurl" . }}'
    link_names: false
templates:
- /etc/alertmanager/config/*.tmpl
```

Looking at that config, any ideas as to why it isn't coming through?

**Comment by tr3mor** [comment]
@jacobmammoliti It is hard without seeing the alert you are trying to send. One common confusing part with AlertmanagerConfig is that it is namespace specific. So the alert should have the label "namespace" and it should be equal to the namespace AlertmanagerConfig is deployed.
In your config:
```
    matchers:
    - namespace="monitoring"
```
So first I would check label namespace in your alert, but it is hard to debug such issues without the original alert

**Comment by jacobmammoliti** [comment]
@tr3mor I have a specific alert firing now that has the label namespace="media" (along with other labels) and have updated my AlertmanagerConfig as below:
```
 apiVersion: monitoring.coreos.com/v1alpha1
 kind: AlertmanagerConfig
 metadata:
   name: slack-config
   namespace: monitoring
   labels:
     alertmanager: config
 spec:
   route:
     groupBy: ["job", "alertname"]
     groupWait: 30s
     groupInterval: 5m
     repeatInterval: 1m
     receiver: "slack-receiver"
     routes:
       - receiver: "slack-receiver"
         continue: true
         matchers:
           - name: namespace
             value: media
   receivers:
     - name: "slack-receiver"
       slackConfigs:
         - sendResolved: true
           apiURL:
             name: slack-webhook-url
             key: webhook-url
             optional: false
           channel: "#alerts"
           title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
           text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
```

After adding that matcher, the alert still isn't coming through to Slack. The config in the alertmanager UI looks like it has updated correctly.

**Comment by jacobmammoliti** [comment]
I realized the issue - I needed to move the AlertmanagerConfig to the namespace I was trying to alert on. Specifically in this case, I needed to move it to the `media` namespace since that is where the alert was firing from.

**Comment by jamescamdenrb** [comment]
In case anyone else finds themselves stuck, there is a proposed solution in https://github.com/prometheus/alertmanager/issues/3437

**Comment by danielstankw** [comment]
> In case anyone else finds themselves stuck, there is a proposed solution in [prometheus/alertmanager#3437](https://github.com/prometheus/alertmanager/issues/3437)

Thank you a ton!

**Comment by alshoaili96** [comment]
i setup my configuration for alertmanager to send notification to teams channel, however i am getting nothing, this is my configuration so far:
````yaml
config:
    global:
      resolve_timeout: 5m
    inhibit_rules: []
      #- source_matchers:
      #    - 'severity = critical'
      #  target_matchers:
      #    - 'severity = warning' #original is (- 'severity =~ warning|info')
      #  equal:
      #    - 'namespace'
      #    - 'alertname'
      #- source_matchers: uncomment later
      #    - 'severity = warning'
      #  target_matchers:
      #    - 'severity = info'
      #  equal:
      #    - 'namespace'
      #    - 'alertname'
      #- source_matchers:
      #    - 'alertname = InfoInhibitor'
      #  target_matchers:
      #    - 'severity = info'
      #  equal:
      #    - 'namespace'
      #- target_matchers:
      #    - 'alertname = InfoInhibitor'
    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'MS-TEAMS' #original value is 'null'
      routes: []
      #- receiver: 'null'
      #  matchers:
      #    - alertname="Watchdog"
    receivers:
    - name: 'null'
    - name: 'MS-TEAMS'
      msteams_config:
        - send_resolved: true
          webhook_url: "webhook_url"
          title: "{{ template \"msteams.default.title\" . }}"  # Default title template
          summary: "{{ .CommonAnnotations.summary | default \"No summary available\" }}"  # Ensures a default value
          text: "{{ .CommonAnnotations.description | default .CommonAnnotations.summary }}"  # Fallback to summary if description is missing
          #http_config: #added, remove later 
          #  follow_redirects: true
          #  enable_http2: true
          max_alerts: 1  # Optional, sends alerts individually, remove later
    templates:
    - '/etc/alertmanager/config/*.tmpl'
````
