### ISSUE TITLE
[kube-prometheus-stack] Relabelings Assuming Action

### ISSUE THREAD

**Issue by JuanPabloSGU** [prometheus-community/helm-charts#2708]
### Describe the bug a clear and concise description of what the bug is.

It seems that 

```YAML
relabelings:
  - action: replace
```

is being detected by Argocd. 

### What's your helm version?

version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersio n:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7

### Which chart?

kube-prometheus-stack

### What's the chart version?

v41.7.4

### What happened?

I have updated the `kube-prometheus-stack` version from 39.0.1 to 41.7.4 and going from client side apply to server side apply.  When updating Argocd had syncing issues with the recent updated chart. It specified that `kube-prometheus-stack-kubelet (service monitor)` was out of sync. 

Desired Manifest 
```YAML
  relabelings:
    - sourceLabels:
      - __metrics_path__
        targetLabel: metrics_path
```

Life Manifest
```YAML
relabelings:
  - action: replace
    - sourceLabels:
      - __metrics_path__
        targetLabel: metrics_path
```

Argocd noticed the difference and would be unable to sync with the new version of the chart. 

### What you expected to happen?

I've followed all of the chart upgrade steps to a newer version of the chart and would have expected it to not run into too many issues. 

### How to reproduce it?

The solution that I had to do is to provide an ignoreDifferences to the deployment within Argocd to allow the new chart to sync. Without this ignoreDifference the application would be out of sync and Argocd would keep trying to delete the missing "replace" and "replace" would be added back.  

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

NA - Argocd handles it
