### ISSUE TITLE
[kube-prometheus-stack] field time_intervals not found in type alertmanager.alertmanagerConfig

### ISSUE THREAD

**Issue by neuwerld2** [prometheus-community/helm-charts#2711]
### Describe the bug a clear and concise description of what the bug is.

I am trying to get time_intervals to work with kube-prometheus-stack helm chart but the Prometheus operator is logging:

`level=error ts=2022-11-21T12:02:15.043658787Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"monitoring/kube-prometheus-stack-alertmanager\" failed: provision alertmanager configuration: failed to initialize from secret: yaml: unmarshal errors:\n  line 65: field active_time_intervals not found in type alertmanager.route\n  line 72: field time_intervals not found in type alertmanager.alertmanagerConfig`

I have followed the documentation found here https://prometheus.io/docs/alerting/0.24/configuration/#time_interval but it seems that the Prometheus operator will not allow this configuration. 
Looking at the helm chart it seems that it is version 0.24.0 of Alertmanager that is being installed and therefore from what I can see this configuration should work.
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L461

### What's your helm version?

v3.10.1

### What's your kubectl version?

1.25

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.5.1

### What happened?

I made configuration to control the time when routing should be done using time_intervals element in Alertmanager configuration.

### What you expected to happen?

Expected Prometheus operator to validate the configuration given.

### Enter the changed values of values.yaml?

```yaml
  config:
    global:
      resolve_timeout: 5m
      slack_api_url: 'SLACK_URL'
    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
    time_intervals:
    - name: workhours
      time_intervals:
      - times:
        - start_time: '08:00'
          end_time: '17:00'
      - weekdays: ['monday:friday']
    route:
      group_by: [cluster, alertname]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 15m
      receiver: 'slack-notifications'
      routes:
      - receiver: 'slack-notifications'
        active_time_intervals:
          - workhours
        matchers:
          - alertname =~ "InfoInhibitor|Watchdog"
    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#prometheus-alerts'
        send_resolved: true
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        actions:
          - type: button
            text: 'Runbook :green_book:'
            url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
          - type: button
            text: 'Query :mag:'
            url: '{{ (index .Alerts 0).GeneratorURL }}'
          - type: button
            text: 'Dashboard :chart_with_upwards_trend:'
            url: '{{ (index .Alerts 0).Annotations.dashboard_url }}'
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.instance }}
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
          *Description:* {{ .Annotations.description }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
    templates:
    - '/etc/alertmanager/config/*.tmpl'
```

### Enter the command that you execute and failing/misfunctioning.

Using ArgoCD to deploy the helm chart and everything seems to be ok until the operator tries to provision the Alertmanager configuration.
