### ISSUE TITLE
[prometheus-node-exporter] Allow valueFrom syntax when configuring environment variables

### ISSUE THREAD

**Issue by slyt** [prometheus-community/helm-charts#2712]
### Is your feature request related to a problem ?

I want to add an init-container to my node-exporter pod to enrich the node-exporter data by modifying the pod labels and using prometheus `relabling` feature to get the pod labels. However, my init-container needs the name of the pod that it is running on in order to do so.

Normally I could change the Pod spec in the Daemonset to make use of the [Kubernetes Downward API](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/) to expose POD_NAME as an environment variable. The node-exporter helm chart does not currently support adding environment variables from the K8s downward API (e.g. I cannot specifying `valueFrom.fieldRef.fieldPath` for an environment variable).

### Describe the solution you'd like.

Change the `env` parameter in values.yaml to support the Pod spec syntax:

For normal environment variables it would be:
```
env:
- name: DEMO_GREETING
  value: "Hello from the environment"
```

Also be able to specify `valueFrom` in the `env` helm parameter:
```
env:
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
``` 

### Describe alternatives you've considered.

For now I will use the `HOSTNAME` variable already exists inside of the node-exporter pod's containers. `HOSTNAME` matches the node name that the pod is executing on.

Then, working backward, I can get all of the pods and check their `spec.nodeName`. If `spec.nodeName` matches `HOSTNAME` environment variable, then I know what pod I'm running on.

This workaround only works because node-exporter is a daemonset where there is 1 pod per node. A potential edge case could be if there are pods being created and destroyed, then there might appear to be multiple pods per node.

**Comment by slyt** [comment]
It turns out that the `extraInitContainers` parameter actually supports environment variables using `valueFrom`.

So my values.yaml looks like this:
```yaml
extraInitContainers:
  - name: node-exporter-init
    image: "docker.example.com/node-exporter-init:999999"
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
```

Then the POD_NAME is accessible in the init container. Example python code:
```python
import os
POD_NAME = os.environ.get("POD_NAME")
print("POD_NAME:", POD_NAME)
```

You can see the output of the print statement in the pod logs. Note that you must pass `--all-containers=true` flag into kubectl logs in order to see output from the init container.

```
kubectl logs prometheus-prometheus-node-exporter-8txvv -n monitoring --all-containers=true
POD_NAME: prometheus-prometheus-node-exporter-8txvv
```
