### ISSUE TITLE
[kube-prometheus-stack] Thanos don't work - address already in use

### ISSUE THREAD

**Issue by mamu-reply** [prometheus-community/helm-charts#2716]
### Describe the bug a clear and concise description of what the bug is.

After the configuration of thanos into the values.yaml of kube-prometheus-stack helm, thanos don't respond, but everything is up and running.

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:33:06Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"} Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.6.1

### What happened?

in values.yaml to configure thanos:
```yaml
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
```
but i don't see any new metrics on prometheus and when i execute this command:
`thanos query --store=dnssrv+_grpc._tcp.kube-prometheus-stack-kube-prom-thanos-discovery.kube-prometheus-stack.svc.cluster.local`

i receive this:
```
level=info ts=2022-11-22T11:12:53.989698Z caller=options.go:26 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2022-11-22T11:12:53.990698Z caller=query.go:776 msg="starting query node"
level=info ts=2022-11-22T11:12:53.99092Z caller=intrumentation.go:56 msg="changing probe status" status=ready
level=info ts=2022-11-22T11:12:53.991111Z caller=intrumentation.go:75 msg="changing probe status" status=healthy
level=info ts=2022-11-22T11:12:53.991272Z caller=http.go:73 service=http/server component=query msg="listening for requests and metrics" address=0.0.0.0:10902
level=warn ts=2022-11-22T11:12:53.991296Z caller=intrumentation.go:67 msg="changing probe status" status=not-ready reason="listen gRPC on address 0.0.0.0:10901: listen tcp 0.0.0.0:10901: bind: address already in use"
level=info ts=2022-11-22T11:12:53.991306Z caller=http.go:84 service=http/server component=query msg="internal server is shutting down" err="listen gRPC on address 0.0.0.0:10901: listen tcp 0.0.0.0:10901: bind: address already in use"
level=info ts=2022-11-22T11:12:53.991314Z caller=http.go:103 service=http/server component=query msg="internal server is shutdown gracefully" err="listen gRPC on address 0.0.0.0:10901: listen tcp 0.0.0.0:10901: bind: address already in use"
level=info ts=2022-11-22T11:12:53.991319Z caller=intrumentation.go:81 msg="changing probe status" status=not-healthy reason="listen gRPC on address 0.0.0.0:10901: listen tcp 0.0.0.0:10901: bind: address already in use"
level=info ts=2022-11-22T11:12:53.991378Z caller=grpc.go:138 service=gRPC/server component=query msg="internal server is shutting down" err=null
level=info ts=2022-11-22T11:12:53.991602Z caller=grpc.go:151 service=gRPC/server component=query msg="gracefully stopping internal server"
level=info ts=2022-11-22T11:12:53.991611Z caller=grpc.go:164 service=gRPC/server component=query msg="internal server is shutdown gracefully" err=null
level=error ts=2022-11-22T11:12:53.994331Z caller=main.go:161 err="listen tcp 0.0.0.0:10901: bind: address already in use\nlisten gRPC on address 0.0.0.0:10901\ngithub.com/thanos-io/thanos/pkg/server/grpc.(*Server).ListenAndServe\n\tgithub.com/thanos-io/thanos/pkg/server/grpc/grpc.go:127\nmain.runQuery.func17\n\tgithub.com/thanos-io/thanos/cmd/thanos/query.go:769\ngithub.com/oklog/run.(*Group).Run.func1\n\tgithub.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\truntime/asm_arm64.s:1172\nquery command failed\nmain.main\n\tgithub.com/thanos-io/thanos/cmd/thanos/main.go:161\nruntime.main\n\truntime/proc.go:250\nruntime.goexit\n\truntime/asm_arm64.s:1172"
```

### What you expected to happen?

That thanos work, i can see metrics in prometheus and that it listen on correct port, and that is not already used.

### How to reproduce it?

Install kube-prometheus-stack in a namespace named kube-prometheus-stack with thanos enabled and exec this command 
`thanos query --store=dnssrv+_grpc._tcp.kube-prometheus-stack-kube-prom-thanos-discovery.kube-prometheus-stack.svc.cluster.local`

### Enter the changed values of values.yaml?

```yaml
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
prometheus:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'cert-manager-letsencrypt-production-route53'
      ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    hosts:
      - 'prometheus.my-cluster.my-region.com'
    paths:
      - /
    athType: Prefix
    tls:
      - secretName: 'prometheus.my-cluster.my-region.com'
        hosts:
          - 'prometheus.my-cluster.my-region.com'
  prometheusSpec:
    remoteWriteDashboards: true
    enableRemoteWriteReceiver: true
    serviceMonitorSelectorNilUsesHelmValues: true
    podMonitorSelectorNilUsesHelmValues: true
    probeSelectorNilUsesHelmValues: true
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
  thanosIngress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'cert-manager-letsencrypt-production-route53'
      ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    hosts:
      - 'thanos.my-cluster.my-region.com'
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: 'thanos.my-cluster.my-region.com'
        hosts:
          - 'thanos.my-cluster.my-region.com'
grafana:
  adminPassword: 'XXXXXXX'
  ingress:
    enabled: 'true'
    annotations:
      cert-manager.io/cluster-issuer: 'cert-manager-letsencrypt-production-route53'
      ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    path: /
    hostname: 'grafana.my-cluster.my-region.com'
    tls:
      - secretName: 'grafana.my-cluster.my-region.com'
        hosts:
          - 'grafana.my-cluster.my-region.com'
```

### Enter the command that you execute and failing/misfunctioning.

`thanos query --store=dnssrv+_grpc._tcp.kube-prometheus-stack-kube-prom-thanos-discovery.kube-prometheus-stack.svc.cluster.local`

### Anything else we need to know?

I've tryied to install thanos as separate helm, but the result don't change.
I don't see any thanos sidecar in any pod.
