### ISSUE TITLE
Endpoints configuration

### ISSUE THREAD

**Issue by gulecroc** [prometheus-community/helm-charts#2729]
### Is your feature request related to a problem ?

When configuring component scraping with endpoints, only IP can be configured.

For exemple in kubeEtcd endpoint chart :

```
subsets:
  - addresses:
      {{- range .Values.kubeEtcd.endpoints }}
      - ip: {{ . }}
      {{- end }}
```

So in metric scraped, only instance is available :

```
etcd_cluster_version{cluster_version="3.4", endpoint="http-metrics", instance="1.2.3.4.5:2381", job="kube-etcd", namespace="kube-system", service="kube-prometheus-stack-kube-etcd"}
```

### Describe the solution you'd like.

I would like to add other adresses properties : https://kubernetes.io/docs/reference/kubernetes-api/service-resources/endpoints-v1/

For exemple adding `nodeName`, prometheus add the discovered label `__meta_kubernetes_endpoint_node_name` (see : https://github.com/prometheus-operator/prometheus-operator/pull/2089).

Finally with relabeling, I obtain `node` label directly with the metric scraping :

```
kubeEtcd:
  enabled: true
  endpoints:
    - ip: 1.2.3.4
      nodeName: myNodeName
  serviceMonitor:
    relabelings:
      - action: replace
        regex: ^(.*)$
        replacement: $1
        separator: ;
        sourceLabels:
          - __meta_kubernetes_endpoint_node_name
        targetLabel: node
```

```
etcd_cluster_version{cluster_version="3.4", endpoint="http-metrics", instance="1.2.3.4.5:2381", job="kube-etcd", namespace="kube-system", node="myNodeName", service="kube-prometheus-stack-kube-etcd"}
```

Components impacted are :
* kubeControllerManager
* kubeEtcd
* kubeProxy
* kubeScheduler

### Describe alternatives you've considered.

For the moment I edit manually the Endpoints created with the charts
