### ISSUE TITLE
[prometheus] AlertManager is not discovered after upgrade to v18

### ISSUE THREAD

**Issue by comphilip** [prometheus-community/helm-charts#2745]
### Describe the bug a clear and concise description of what the bug is.

After upgrade `Prometheus` chart from v17 to v18, alert manager is not discovered.

## Root Cause
`Prometheus` chart not adding service discovery labels and annotations to alert manager pod:
### Default AlertManager SD Config
```yaml
  - source_labels: [__meta_kubernetes_pod_label_app]
      separator: ;
      regex: prometheus
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_pod_label_component]
      separator: ;
      regex: alertmanager
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_probe]
      separator: ;
      regex: .*
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      separator: ;
      regex: "9093"
      replacement: $1
      action: keep
    kubernetes_sd_configs:
    - role: pod
      kubeconfig_file: ""
      follow_redirects: true
      enable_http2: true
```

### What's your helm version?

version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}

### What's your kubectl version?

v1.25.3

### Which chart?

prometheus

### What's the chart version?

18.0.0

### What happened?

Prometheus cannot discover AlertManager

### What you expected to happen?

Prometheus discovers AlertManager

### Enter the changed values of values.yaml?

```yaml
    prometheus-pushgateway:
      enabled: false
    alertmanager:
      persistence:
        enabled: false
      config:
        route:
          group_by: ["alertname", "cluster", "job"]
          group_wait: 10s
          group_interval: 1m
          repeat_interval: 24h
          receiver: next-system-web-hook
          routes:
            - continue: true
              receiver: next-system-web-hook
        inhibit_rules:
          - source_match:
              severity: "critical"
            target_match:
              severity: "warning"
            equal: ["alertname", "cluster", "job"]
        receivers:
          - name: "next-system-web-hook"
            webhook_configs:
              - url: https://internal.mock.com/v1/IT/alerts
              - url: https://internal.mock.com/v1/IT/alerts
    server:
      strategy:
        type: Recreate
      baseURL: https://hkdc-prometheus.mock.com
      retention: 5d
      persistentVolume:
        enabled: true
        existingClaim: prometheus-pvc
      extraVolumeMounts:
      - name: rule-volume
        mountPath: /etc/prometheus-rules
        readOnly: true
    configmapReload:
      prometheus:
        extraVolumeDirs:
        - /etc/prometheus-rules
        extraConfigmapMounts:
        - name: rule-volume
          mountPath: /etc/prometheus-rules
          subPath: ""
          readOnly: true  
          configMap: prometheus-rule-cm
    serverFiles:
      prometheus.yml:
        rule_files:
        - /etc/prometheus-rules/*-rules.yml
    prometheus-node-exporter:
      service:
        annotations:
          "prometheus.io/scrape": "false" # managed by netbox discovery

```

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/prometheus --version 18.0.0 --values values.yaml

**Comment by monotek** [comment]
@zanac1986 changed that in https://github.com/prometheus-community/helm-charts/pull/2717 so he might be able to help.

**Comment by jmpalomar** [comment]
Seems that alertmanager pod after 18.0 does not have labels required for discovery.
Before:
```  
labels:
    app: prometheus
    chart: prometheus-16.0.0
    component: alertmanager
    controller-revision-hash: prometheus-alertmanager-6b68b4b46c
    heritage: Helm
    release: prometheus
    statefulset.kubernetes.io/pod-name: prometheus-alertmanager-0
```
After:
```
labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: alertmanager
    controller-revision-hash: prometheus-alertmanager-5f6645fc54
    statefulset.kubernetes.io/pod-name: prometheus-alertmanager-0
```

**Comment by zanac1986** [comment]
> Seems that alertmanager pod after 18.0 does not have labels required for discovery. Before:
> 
> ```
> labels:
>     app: prometheus
>     chart: prometheus-16.0.0
>     component: alertmanager
>     controller-revision-hash: prometheus-alertmanager-6b68b4b46c
>     heritage: Helm
>     release: prometheus
>     statefulset.kubernetes.io/pod-name: prometheus-alertmanager-0
> ```
> 
> After:
> 
> ```
> labels:
>     app.kubernetes.io/instance: prometheus
>     app.kubernetes.io/name: alertmanager
>     controller-revision-hash: prometheus-alertmanager-5f6645fc54
>     statefulset.kubernetes.io/pod-name: prometheus-alertmanager-0
> ```

@jmpalomar 
So should we change the configuration side, the chart itself side, or both?

**Comment by jmpalomar** [comment]
@zanac1986 as a workaround you must configure this labels in helm release:
```
alertmanager:

  podLabels:
      app: prometheus
      component: alertmanager

```

`app` value must be what you put on `prometheus.name`.

There are two options to fix this, one is add that configuration on `values.yaml` at prometheus chart, second option would be change `templates/server/cm.yaml` default value when `server.alertmanagers` is not present to match with labels alertmanager chart produces.

This is the piece of code that must be changed at `templates/server/cm.yaml`:
```
      alertmanagers:
{{- if $root.Values.server.alertmanagers }}
{{ toYaml $root.Values.server.alertmanagers | indent 8 }}
{{- else }}
      - kubernetes_sd_configs:
          - role: pod
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        {{- if $root.Values.alertmanager.prefixURL }}
        path_prefix: {{ $root.Values.alertmanager.prefixURL }}
        {{- end }}
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          regex: {{ $root.Release.Namespace }}
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_app]
          regex: {{ template "prometheus.name" $root }}
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_component]
          regex: alertmanager
          action: keep
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_probe]
          regex: {{ index $root.Values.alertmanager.podAnnotations "prometheus.io/probe" | default ".*" }}
          action: keep
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          regex: "9093"
          action: keep
{{- end -}}
```

**Comment by zanhsieh** [comment]
@monotek @jmpalomar @comphilip 
Could you guys review this PR #2765 please?

**Comment by jmpalomar** [comment]
> @monotek @jmpalomar @comphilip Could you guys review this PR #2765 please?

I think change will not work if someone overrides prometheus name or alertmanager name.

If you check alertmanager chart selection labels are created using this function:

```yaml
{{- define "alertmanager.selectorLabels" -}}
app.kubernetes.io/name: {{ include "alertmanager.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
```

So I think that for `app.kubernetes.io/instance` you need the following:
```yaml
  - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
    regex: {{ $root.Release.Name }}
    action: keep
```

And i think for `app.kubernetes.io/name` you need something like this:
```yaml
  - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
    regex: {{ default "alertmanager" $root.Values.alertmanager.name | trunc 63 | trimSuffix "-" -}}
    action: keep
```

Again I did not have the opportunity to test above changes 😞
