### ISSUE TITLE
Invalid Image Name for monitoring-kube-prometheus-admission-create

### ISSUE THREAD

**Issue by sfxworks** [prometheus-community/helm-charts#2751]
### Describe the bug a clear and concise description of what the bug is.

```yaml
      spec:
        containers:
        - args:
          - create
          - --host=monitoring-kube-prometheus-operator,monitoring-kube-prometheus-operator.monitoring.svc
          - --namespace=monitoring
          - --secret-name=monitoring-kube-prometheus-admission
          image: /k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.3.0
          imagePullPolicy: IfNotPresent
          name: create
```
Job errornously rendendered with / at beginning of image name on upgrade

### What's your helm version?

version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}

### What's your kubectl version?

Client Version: v1.25.4 Kustomize Version: v4.5.7 Server Version: v1.25.3

### Which chart?

kube-prometheus-stack

### What's the chart version?

42.1.0

### What happened?

Upgrading my stack to adjust log retention. It rendered a job with an invalid image name.

### What you expected to happen?

The image to work

### How to reproduce it?

Upgrade with altert manager configs im assuming.

### Enter the changed values of values.yaml?

```
alertmanager:
  config:
    global:
      resolve_timeout: 5m
      slack_api_url: http://my-discord-webhook/slack
    receivers:
    - name: "null"
    - name: slack
      slack_configs:
      - channel: '#monitoring'
        send_resolved: false
        text: |-
          {{ range .Alerts }}
            **Alert:** {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            **Description:** {{ .Annotations.description }}
            **Graph*:* <{{ .GeneratorURL }}| graph-link > :chart_with_upwards_trend:
            **Details:**
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing
          | len }}{{ end }}] Monitoring Event Notification'
    route:
      group_by:
      - job
      group_interval: 5m
      group_wait: 30s
      receiver: "null"
      repeat_interval: 12h
      routes:
      - match:
          alertname: DeadMansSwitch
        receiver: "null"
      - continue: true
        receiver: slack
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    enabled: true
    hosts:
    - alerts.mcsh.red
    tls:
    - hosts:
      - redacted
      secretName: alerts-cert
global:
  serviceMonitor:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
            storageClassName: nvmeblock
grafana:
  grafana.ini:
    auth:
      disable_login_form: false
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
      org_name: MC Server Hosting LLC
      org_role: Viewer
    users:
      viewers_can_edit: false
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    enabled: true
    hosts:
    - grafana.mcsh.red
    tls:
    - hosts:
      - grafana.mcsh.red
      secretName: grafana-cert
  persistence:
    enabled: true
    storageClassName: nvmeblock
prometheus:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    enabled: true
    hosts:
    - metrics.mcsh.red
    tls:
    - hosts:
      - metrics.mcsh.red
      secretName: metrics-cert
  podDisruptionBudget:
    enabled: true
  prometheusSpec:
    retention: 365d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
          storageClassName: nvmeblock
```

### Enter the command that you execute and failing/misfunctioning.

`helm repo upgrade -n monitoring monitoring prometheus-community/kube-prometheus-stack --reuse-values --set prometheus.prometheusSpec.retention=365d`

### Anything else we need to know?

I removed the job and it appears the helm deployment also disappeared. So my release is broken.

```
    ~  kubectl get secrets -n monitoring | grep helm                                                                                                                                               ✔  red ⎈ 
sh.helm.release.v1.monitoring.v1                                    helm.sh/release.v1   1      28d
sh.helm.release.v1.monitoring.v2                                    helm.sh/release.v1   1      28d
sh.helm.release.v1.monitoring.v3                                    helm.sh/release.v1   1      11m
sh.helm.release.v1.monitoring.v4                                    helm.sh/release.v1   1      3m28s
    ~  helm list -n monitoring                                                                                                                                                                     ✔  red ⎈ 
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
    ~  helm upgrade -n monitoring monitoring prometheus-community/kube-prometheus-stack -f promstack.yaml                                                                                          ✔  red ⎈ 
Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress
    ~                                                                                                                                                                                                    1 ✘ 
```
