### ISSUE TITLE
[prometheus-kube-stack] msg="Notify for alerts failed" template not defined ERROR after upgrading 39.10.0->40.0.0

### ISSUE THREAD

**Issue by rhollins** [prometheus-community/helm-charts#2763]
### Describe the bug a clear and concise description of what the bug is.

After upgrading 39.10.0->40.0.0 alertmanager no longer can send alerts due to following error:

`ts=2022-12-01T12:57:10.734Z caller=dispatch.go:354 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="name-slack-notifications/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: template: :1:12: executing \"\" at <{{template \"name.slack.footer\" .}}>: template \"name.slack.footer\" not defined"`

Template is defined in helm values file

```
alertmanager:
  templateFiles:
    template_1.tmpl: |-
        {{ define "name.slack.footer" }}Prometheus Alerts{{ if eq .Status "firing" }} | since {{(index .Alerts 0).StartsAt.Format "3:04 PM" }}{{ else }} | resolved {{ (index .Alerts 0).EndsAt.Format "3:04 PM" }}{{ end }}{{ end }}
```

Then after deployment it is located inside alertmanager pod inside` /etc/alertmanager/config/template_1.tmpl`

`{{ define "name.slack.footer" }}Prometheus Alerts{{ if eq .Status "firing" }} | since {{(index .Alerts 0).StartsAt.Format "3:04 PM" }}{{ else }} | resolved {{ (index .Alerts 0).EndsAt.Format "3:04 PM" }}{{ end }}{{ end }}`

Here is the receiver definition that is using the template file:

```
- name: 'name-slack-notifications'
  slack_configs:
  - api_url: ...
    channel: ...
    username: '...'
    title: '{{ .Status}} {{ if eq .Status "firing" }}{{ .Alerts.Firing | len }}{{ end }}'
    color: '{{ template "name.name-exporter.slack.color" . }}'
    footer: '{{ template "name.slack.footer" . }}'
    text: >-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
        *Description:* {{ .Annotations.description }}
      {{ end }}
    send_resolved: true
```

I can also see that `/etc/alertmanager/config/alertmanager.yaml `has defined path to templates at the bottom:

```
templates:
- '*.tmpl'
```

which on the alertmanager website under Status points to:

```
templates:
- /etc/alertmanager/config/*.tmpl
```

### What's your helm version?

v3.9.0

### What's your kubectl version?

v1.25.2

### Which chart?

prometheus-kube-stack

### What's the chart version?

stopped working since 40.0.0

### Enter the command that you execute and failing/misfunctioning.

deployment works fine
