### ISSUE TITLE
[kube-prometheus-stack] Grafana not deployed after upgrading to 42.2.0

### ISSUE THREAD

**Issue by irizzant** [prometheus-community/helm-charts#2788]
### Describe the bug a clear and concise description of what the bug is.

I had the chart deployed at version 42.0.2, with the following `grafana.persistence` section:
```
grafana:
  persistence:
    type: statefulset
    enabled: true
    storageClassName: rook-ceph-block
    accessModes:
      - ReadWriteOnce
    size: 10Gi
```

Before [this Grafana commit](https://github.com/grafana/helm-charts/commit/45f71da2c9055f6de23761434a8fc2472559ca53)  this was enough to get Grafana deployed with a StatefulSet.

After upgrading to chart version 42.2.0 Grafana StatefulSet disappeared.

This is because version 42.2.0 bumped Grafana chart to 6.45.0 which introduced the mentioned commit.

I didn't find this documented anywhere, the chart major version is still 42 and there's no way users can take the required actions to prepare for this upgrade.

I think this should be documented with a major version change.

### What's your helm version?

version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

42.2.0

### What happened?

Grafana Pod was not deployed

### What you expected to happen?

Grafana Pod should be deployed

### How to reproduce it?

Deploy version 42.2.0 with:
```
grafana:
  persistence:
    type: statefulset
    enabled: true
    storageClassName: rook-ceph-block
    accessModes:
      - ReadWriteOnce
    size: 10Gi
```

### Enter the changed values of values.yaml?

```
grafana:
  persistence:
    type: statefulset
    enabled: true
    storageClassName: rook-ceph-block
    accessModes:
      - ReadWriteOnce
    size: 10Gi
```

### Enter the command that you execute and failing/misfunctioning.

helm install --release-name kube-prometheus-stack --namespace monitoring --version 42.2.0 -f values.yaml --include-crds prometheus-community/kube-prometheus-stack
