### ISSUE TITLE
[kube-prometheus-stack] tplConfig option for prometheusSpec

### ISSUE THREAD

**Issue by postmaxin** [prometheus-community/helm-charts#2791]
### Is your feature request related to a problem ?

I am including `kube-prometheus-stack` as a subchart so that I can template the same few variances in options out over a bunch of clusters.

### Describe the solution you'd like.

A `tplConfig` option for Prometheus just like there is for AlertManager

### Describe alternatives you've considered.

I've played around with a few options over the past few hours. This would really make the upstream config a lot easier.

### Additional context.

For example, because I can use `tplConfig` with AlertManager, my upstream config can contain this:

```
global:
  slack:
    channel: "#alerts-dev-cluster"
    apiUrl: https://hooks.slack.com/...
```

However, because I can not use `tplConfig` with Prometheus itself, I have to shove all of these values in even though I am only interested in setting the IAM role and Writer url:

```
kube-prometheus-stack:
  prometheus:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: ...
    prometheusSpec:
      remoteWrite:
        - queueConfig:
            capacity: 2500
            maxSamplesPerSend: 1000
            maxShards: 200
          sigv4:
            region: us-west-2
          url: https://...
```

Given that AlertManager already has this feature, it sounds like it should be possible to add it to Prometheus without too much trouble?
