### ISSUE TITLE
[prometheus-kube-stack] Prometheus server pod cannot come up when Prometheus Operator is disabled

### ISSUE THREAD

**Issue by anthosz** [prometheus-community/helm-charts#2792]
### Describe the bug a clear and concise description of what the bug is.

Unable to deploy prometheus (server) if prometheus operator disabled

### What's your helm version?

v3.10.1

### What's your kubectl version?

v1.23.6

### Which chart?

kube-prometheus-stack-42.2.1

### What's the chart version?

0.60.1

### What happened?

If we disable Prometheus operator, it didn't deploy prometheus server even if Prometheus is enabled

### What you expected to happen?

Deploying prometheus server pods

### How to reproduce it?

Use the following values.yam & deploy it

### Enter the changed values of values.yaml?

```yaml
defaultRules:
  rules:
    etcd: false
    alertmanager: false
    prometheusOperator: false
    kubeProxy: false
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false

alertmanager:
  enabled: false
grafana:
  enabled: false
prometheusOperator:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
prometheus:
  enabled: true
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -f values.yaml -n monitoring

### Anything else we need to know?

Before, I used the chart prometheus-community/prometheus that worked well but the blocking point is that I need to use the Prometheus-adapter + kube states metrics (to be able to use metrics for the horizontal scaling) via prometheus-kube-stack to be able to use it.

My goal is to use prometheus server+prom node exporter+telegraf like operator  (+ the states metrics & adapter needed for metrics usage)
