### ISSUE TITLE
[alertmanager] use of PDB throws YAML parsing error

### ISSUE THREAD

**Issue by toVersus** [prometheus-community/helm-charts#2795]
### Describe the bug a clear and concise description of what the bug is.

We encountered the following error when upgrading Alertmanager chart version to 0.22.1:

```console
❯ helm template alertmanager -n monitoring .
Error: YAML parse error on alertmanager/templates/pdb.yaml: error converting YAML to JSON: yaml: line 15: mapping values are not allowed in this context
```

We could confirm that missing line break on the field `maxUnavailable`:

```yaml
---
# Source: alertmanager/templates/pdb.yaml

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: alertmanager
  labels:
    helm.sh/chart: alertmanager-0.22.1
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/version: "v0.24.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/instance: alertmanager  maxUnavailable: 1
```

It seems that a regression regarding to PDB is introduced in the part of refactoring. (#2781)

### What's your helm version?

version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.19.2"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}

### Which chart?

alertmanager

### What's the chart version?

0.22.1

### What you expected to happen?

We can generate manifests without any errors:

```yaml
---
# Source: alertmanager/templates/pdb.yaml

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: alertmanager
  labels:
    helm.sh/chart: alertmanager-0.22.1
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/version: "v0.24.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/instance: alertmanager
  maxUnavailable: 1
```

### How to reproduce it?

Enable PDB on default values file:

```yaml
podDisruptionBudget:
  maxUnavailable: 1
```

Generate manifests using Helm template:

```console
❯ helm template alertmanager . --debug
install.go:192: [debug] Original chart version: ""
install.go:209: [debug] CHART PATH: /Users/toVersus/Documents/prometheus-community/helm-charts/charts/alertmanager

---
# Source: alertmanager/templates/pdb.yaml

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: alertmanager
  labels:
    helm.sh/chart: alertmanager-0.22.1
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/version: "v0.24.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/instance: alertmanager  maxUnavailable: 1
```

### Enter the command that you execute and failing/misfunctioning.

helm template alertmanager . --debug
