### ISSUE TITLE
[prometheus-kube-stack] Grafana panel: `Storage IO - Distribution` not showing

### ISSUE THREAD

**Issue by xinbinhuang** [prometheus-community/helm-charts#2803]
### Describe the bug a clear and concise description of what the bug is.

Under the `Kubernetes / Compute Resources / Cluster` dashboard, the Grafana panel: `Storage IO - Distribution` is not showing any data[0]. However, when I "inspect" the panel, the data seems to be queried successfully[1].

[0]
<img width="1633" alt="Screen Shot 2022-12-10 at 1 59 55 PM" src="https://user-images.githubusercontent.com/27927454/206876859-5e9fde4a-126d-49dc-8dd3-82d801fc19b5.png">

[1]
<img width="1725" alt="Screen Shot 2022-12-10 at 2 03 08 PM" src="https://user-images.githubusercontent.com/27927454/206876962-98486622-a061-47d7-a53d-c57524fafb2d.png">

### What's your helm version?

version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}

### What's your kubectl version?

Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

42.3.0

### What happened?

Panel not showing data.

### What you expected to happen?

Panel should show correct data.

### Enter the changed values of values.yaml?

```
  grafana:
    enabled: true
    serviceMonitor:
      enabled: true
    persistence:
      enabled: true

  nodeExporter:
    enabled: false

  prometheus:
    enabled: true

    prometheusSpec:

      enableAdminAPI: true

      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false

      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 30Gi

  kubeApiServer:
    enabled: true
  kubeEtcd:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false
```

### Enter the command that you execute and failing/misfunctioning.

na
