### ISSUE TITLE
Ignore a namespace when scraping

### ISSUE THREAD

**Issue by miladino43** [prometheus-community/helm-charts#2817]
Hello 
I was wondering if it's possible to drop scraping a particular namespace? 

by default the stack will deploy the kubelet servicemonitor which will get the metrics from /metrics/cadvisor path. 

I tried editing this service monitor with 

```
  cAdvisorRelabelings:
     - sourceLables: [ __meta_kubernetes_namespace ]
     action: drop
     regex: mynamespace
```

but i realized that this service monitor is just determining the targets which are kubelets. Therefore whatever i put here will not stop scraping the namespace i want.

Any ideas how to tell prometheus that i dont want it to scrape any resource in a particular namespace?
