### ISSUE TITLE
[prometheus-node-exporter] `.Values.sidecarVolumeMount` used in incorrect scope in `templates/daemonset.yaml`

### ISSUE THREAD

**Issue by jsolbrig** [prometheus-community/helm-charts#2824]
### Describe the bug a clear and concise description of what the bug is.

I am attempting to deploy `prometheus-node-exporter` either directly or as a part of `kube-prometheus-stack`. I am attempting to use a sidecar. When I add a sidecar `helm template` fails with the following error:

```
Error: template: prometheus-node-exporter/templates/daemonset.yaml:150:27: executing "prometheus-node-exporter/templates/daemonset.yaml" at <.Values.sidecarVolumeMount>: can't evaluate field Values in type []interface {}
helm.go:84: [debug] template: prometheus-node-exporter/templates/daemonset.yaml:150:27: executing "prometheus-node-exporter/templates/daemonset.yaml" at <.Values.sidecarVolumeMount>: can't evaluate field Values in type []interface {}
```

I believe that this is due to a scope error in `templates/daemonset.yaml`.

### What's your helm version?

version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:38:19Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.4 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:31:40Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-node-exporter

### What's the chart version?

4.8.0

### What happened?

I am attempting to deploy `prometheus-node-exporter` either directly or as a part of `kube-prometheus-stack`. I am attempting to use a sidecar. When I add a sidecar `helm template` fails with the following error:

```
Error: template: prometheus-node-exporter/templates/daemonset.yaml:150:27: executing "prometheus-node-exporter/templates/daemonset.yaml" at <.Values.sidecarVolumeMount>: can't evaluate field Values in type []interface {}
helm.go:84: [debug] template: prometheus-node-exporter/templates/daemonset.yaml:150:27: executing "prometheus-node-exporter/templates/daemonset.yaml" at <.Values.sidecarVolumeMount>: can't evaluate field Values in type []interface {}
```

This appears to be caused by the use of `.Values.sidecarVolumeMount` at line 150 in `templates/daemonset.yaml` because `Values` is out of scope at that point. On line 148 the context is switched to `.Values.sidecars` so, I believe, the block in lines 148-164 should read:
```mustache
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
          {{- if or $.Values.sidecarVolumeMount $.Values.sidecarHostVolumeMounts }}
          volumeMounts:
            {{- range $_, $mount := $.Values.sidecarVolumeMount }}
            - name: {{ $mount.name }}
              mountPath: {{ $mount.mountPath }}
              readOnly: {{ $mount.readOnly }}
            {{- end }}
            {{- range $_, $mount := $.Values.sidecarHostVolumeMounts }}
            - name: {{ $mount.name }}
              mountPath: {{ $mount.mountPath }}
              readOnly: {{ $mount.readOnly }}
            {{- if $mount.mountPropagation }}
              mountPropagation: {{ $mount.mountPropagation }}
            {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
```

### What you expected to happen?

I expected `helm template` to correctly render the chart.

### How to reproduce it?

1. Pull the chart and CD into it:
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm pull prometheus-community/prometheus-node-exporter
tar -xvf prometheus-node-exporter-4.8.0.tgz
cd prometheus-node-exporter/
```

2. Edit `values.yaml` to make lines 225-227 read:
```yaml
sidecars:                                                                                                                                                                                                                                                                                                                     
  - name: nvidia-dcgm-exporter
    image: nvidia/dcgm-exporter:1.4.3
```

3. Run `helm template node-exporter .`

This will result in the following error:
```
> helm template node-exporter .
Error: template: prometheus-node-exporter/templates/daemonset.yaml:150:27: executing "prometheus-node-exporter/templates/daemonset.yaml" at <.Values.sidecarVolumeMount>: can't evaluate field Values in type []interface {}

Use --debug flag to render out invalid YAML
```


### Enter the changed values of values.yaml?

```yaml
sidecars:                                                                                                                                                                                                                                                                                                                     
  - name: nvidia-dcgm-exporter
    image: nvidia/dcgm-exporter:1.4.3
```

### Enter the command that you execute and failing/misfunctioning.

helm template node-exporter .

### Anything else we need to know?

This appears to be a variable scope error in `templates/daemonset.yaml` on lines 150, 152, and 157. If those lines are edited to use `$.Values.sidecarVolumeMount` and `$.Values.sidecarHostVolumeMounts` the chart renders correctly.
