### ISSUE TITLE
kube-prometheus-stack: Impossible to expose Grafana behind an Nginx ingress using subpath /grafana

### ISSUE THREAD

**Issue by J-Are** [prometheus-community/helm-charts#2837]
### Describe the bug a clear and concise description of what the bug is.

Hi, I would like to deploy kube-prometheus-stack chart in version **41.7.3** and expose Grafana behin a **/grafana** subpath.

I followed the configuration for the ingress and grafana.ini from the chart's readme: https://github.com/grafana/helm-charts/tree/main/charts/grafana#example-ingress-with-path
Once it is done, I tried to access to the application and I meet this error page:
![image](https://user-images.githubusercontent.com/17073117/208921725-2161cd2c-3a56-4fbd-96ba-56a5dde36bc3.png)

I successfully deployed an older version of the kube-prometheus-stack (**32.2.1**) , I used this configuration snippet into my values.yaml file: https://github.com/grafana/helm-charts/tree/main/charts/grafana#how-to-serve-grafana-with-a-path-prefix-grafana and it worked. I was able to login to Grafana.

I don't understand why it does not work for the **41.7.3** version.

### What's your helm version?

v3.5.4

### What's your kubectl version?

v1.20.2

### Which chart?

kube-prometheus-chart

### What's the chart version?

41.7.3

### What happened?

I meet this error page 
![image](https://user-images.githubusercontent.com/17073117/208922746-4bc1f2fe-49d6-4b43-ac3c-198857051ca8.png)

### What you expected to happen?

Access to Grafana login page when I try to access to https://<my_domain>/grafana from my browser.

### How to reproduce it?

1. Create and paste the following content of the values.yaml file. Please replace "my_domain" by your custom domain.
2. Run the helm install command: helm upgrade --install prometheus-stack prometheus-community/kube-prometheus-stack -n prometheus-stack -f ./values.yaml --version 41.7.3
3. Try to access from your browser to https://your_custom_domain/grafana

### Enter the changed values of values.yaml?

```
grafana: 
  testFramework:
    enabled: false
  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: nginx
    }
    hosts:
      - "my_domain"
    pathType: Prefix
    path: /grafana
  grafana.ini:
    server:
      domain: "my_domain"
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true
  admin: 
    existingSecret: grafana-admin-credentials
    serviceMonitor:
      enabled: true
    podDisruptionBudget:
      minAvailable: 1
    persistence: 
      enabled: true
      storageClassName: default
alertmanager:
  podDisruptionBudget:
    enabled: true
prometheus:
  podDisruptionBudget:
    enabled: true
  prometheusSpec: 
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: default
          accessModes: ["ReadWriteOnce"]
          resources:
            requests: 
              storage: 50Gi
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install prometheus-stack prometheus-community/kube-prometheus-stack -n prometheus-stack -f ./values.yaml --version 41.7.3

### Anything else we need to know?

After I have meet this issue, I tried to deploy an older version of the kube-prometheus-stack in version **32.2.1**.
I used this configuration snippet into my values.yaml file: https://github.com/grafana/helm-charts/tree/main/charts/grafana#how-to-serve-grafana-with-a-path-prefix-grafana. Finally, it works as expected and I was able to login to Grafana. I think this issue is related with the version of the chart/Grafana.

**Comment by Jeroen0494** [comment]
With the following config in values.yaml:
```
grafana:
  ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: true

    ## IngressClassName for Grafana Ingress.
    ## Should be provided if Ingress is enable.
    ##
    ingressClassName: nginx

    ## Annotations for Grafana Ingress
    ##
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer

    ## Labels to be added to the Ingress
    ##
    labels: {}

    ## Hostnames.
    ## Must be provided if Ingress is enable.
    ##
    hosts:
      - MYHOST

    ## Path for grafana ingress
    path: /grafana

    ## TLS configuration for grafana Ingress
    ## Secret must be manually created in the namespace
    ##
    tls:
      - secretName: "grafana-tls-key"
        hosts:
        - MYHOST

  grafana.ini:
    security:
      cookie_secure: false
    server:
      domain: mediaserver.fritz.box
      protocol: http
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: true
```

I am happily serving my Grafana instance behind a proxy with a (self-signed) certificate. I think you have forgotten the port number in your `root_url` definition, and are missing the protocol definition as well. Also, the ingress class shouldn't be set using annotation anymore.
