### ISSUE TITLE
[prometheus-postgres-exporter] Container securityContext in values actually configures pod securityContext

### ISSUE THREAD

**Issue by jawnsy** [prometheus-community/helm-charts#2840]
### Describe the bug a clear and concise description of what the bug is.

There's an indentation and placement issue in the Helm chart, which results in the container security context actually configuring the pod security context, and a placement issue that results in the security context configuring the last container, rather than the actual application container.

### What's your helm version?

version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.19.3"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/arm64"}

### Which chart?

prometheus-postgres-exporter

### What's the chart version?

4.0.0

### What happened?

The way the security contexts are set up, we end up with two securityContext indented 8 levels, which sets the pod security context in the deployment. It is not actually possible to configure the container security context.

This is because of this section -- the indent should be 12, not 8: https://github.com/prometheus-community/helm-charts/blob/e09e9879ad75f1e787eadbeb9d73f1aafb86c226/charts/prometheus-postgres-exporter/templates/deployment.yaml#L150-L151

The indent should match the extra volumes we're mounting into the container: https://github.com/prometheus-community/helm-charts/blob/e09e9879ad75f1e787eadbeb9d73f1aafb86c226/charts/prometheus-postgres-exporter/templates/deployment.yaml#L144-L146

Additionally, because the securityContext is below the `extraContainers`, the security context would apply to whatever container happens to be placed last, rather than to the application container.

### What you expected to happen?

I expected the pod security context to configure the pod security context, while the securityContext would configure the container security context. As it stands, the pod security context works, and the container security context setting simply overrides it, but makes it impossible to set options like `readOnlyRootFilesystem`, which only support container security contexts.

### Enter the changed values of values.yaml?

If you specify values like this:

```yaml
podSecurityContext:
  runAsUser: 65534
  runAsGroup: 65534
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContext:
  runAsUser: 65534
  runAsGroup: 65534
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"
  seccompProfile:
    type: RuntimeDefault
```

And then run `helm template` with this file (I used `helm template release prometheus-community/prometheus-postgres-exporter --values=test.values.yaml | yq`), you get:

```yaml
# Source: prometheus-postgres-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-prometheus-postgres-exporter
  labels:
    app: prometheus-postgres-exporter
    chart: prometheus-postgres-exporter-4.0.0
    release: release
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-postgres-exporter
      release: release
  template:
    metadata:
      labels:
        app: prometheus-postgres-exporter
        release: release
      annotations:
        checksum/config: ebe64e6e36fb02d17d103c04c3690dba67b592d3d7c6178ef606f7174b955118
    spec:
      serviceAccountName: release-prometheus-postgres-exporter
      securityContext:
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: prometheus-postgres-exporter
          args:
            - "--extend.query-path=/etc/config.yaml"
          env:
            - name: DATA_SOURCE_URI
              value: "%!s(<nil>):5432/?sslmode=disable"
            - name: DATA_SOURCE_USER
              value: postgres
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: release-prometheus-postgres-exporter
                  key: data_source_password
          image: "quay.io/prometheuscommunity/postgres-exporter:v0.11.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9187
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 0
            timeoutSeconds: 1
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 0
            timeoutSeconds: 1
            httpGet:
              path: /
              port: http
          resources: {}
          volumeMounts:
            - name: queries
              mountPath: /etc/config.yaml
              subPath: config.yaml
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - configMap:
            defaultMode: 420
            name: release-prometheus-postgres-exporter
          name: queries
```

### Enter the command that you execute and failing/misfunctioning.

helm template release prometheus-community/prometheus-postgres-exporter --values=test.values.yaml | yq
