### ISSUE TITLE
[prometheus-adapter] Add option to add environment variables to the prometheus-adapter container

### ISSUE THREAD

**Issue by david-gang** [prometheus-community/helm-charts#2842]
### Is your feature request related to a problem ?

We use a hosted prometheus in grafana cloud and want to connect to it with basic authentication.
This is possible through passing the[ --prometheus-header](https://github.com/kubernetes-sigs/prometheus-adapter/issues/439#issuecomment-896730036) flag to the adapter,  which can be achieved by setting the extraArguments variable of the values.yaml 

The problem is that there is no way to inject an environment variable to the container

This means that i cannot use gitops to deploy this chart as i need to have the password hardcoded in the values.yaml

### Describe the solution you'd like.

Have an option to inject environment variables from secrets to this container and use them as extra arguments

### Describe alternatives you've considered.

I considered to create a kubeconfig file which contains the username and password

```
apiVersion: v1
clusters:
- name: prom
  cluster:
    server: http://hosted-prometheus.com:9090
contexts:
- name: prom-context
  context:
    cluster: prom
    user: prom-user
current-context: prom-context
users:
- name: prom-user
  user:
    username: admin
    password: password123
```

then i could add it as secret and mount this to a file which can be referenced by the prometheus-auth-config flag in the adapter

Evrything would be in place for this, because i can use extraVolumes and extraVolumeMounts

I have two problems:

1. it is complex
2. Per https://github.com/kubernetes-sigs/prometheus-adapter/issues/439#issuecomment-896718145 this was not possible
