### ISSUE TITLE
[prometheus-kube-stack] Grafana Persistent Storage option

### ISSUE THREAD

**Issue by abhiptl** [prometheus-community/helm-charts#2848]
### Describe the bug a clear and concise description of what the bug is.

I installed "prometheus-kube-stack" helm chart(43.1.3) and installed on my EKS cluster(1.24). If new dashboard/folder is created in Grafana then it is not getting persisted if pod is restarted.

 "prometheus-kube-stack" helm chart doesn't have configuration option to include persistenVolume config for grafana. Though, it's [dependent chart](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L309-L316) has this option.

Am I missing any configuration or feature itself not available?

### What's your helm version?

v3.8.2

### What's your kubectl version?

v1.24.7-eks-fb459a0

### Which chart?

prometheus-kube-stack

### What's the chart version?

43.1.3

### What happened?

ad

### What you expected to happen?

ad

### How to reproduce it?

ad

### Enter the changed values of values.yaml?

ad

### Enter the command that you execute and failing/misfunctioning.

resource "helm_release" "prometheus_heml" {
  count            = var.prometheus_config.enabled ? 1 : 0
  namespace        = "prometheus"
  create_namespace = true

  name       = "kube-prometheus-stack"
  repository = "https://prometheus-community.github.io/helm-charts"
  chart      = "kube-prometheus-stack"
  version    = var.prometheus_config.chart_version

  values = [
    file("templates/prometheus.values.yaml")
  ]

  depends_on = [module.eks, helm_release.aws_ebs_csi_driver, kubectl_manifest.gp3_storageclass]
}

**Comment by zeritti** [comment]
The Grafana chart being included as a dependency, i.e. subchart, does support [persistence](https://github.com/grafana/helm-charts/blob/3c1ca3991c46c90fada061d67bbab26095b49081/charts/grafana/values.yaml#L309) as you write. You can use any of the chart's value in your kube-prometheus-stack's values file underneath `grafana:` (`grafana.persistence` is by default set to `enabled: false`, though), e.g.
```
grafana:
  persistence:
    type: pvc
    enabled: true
    storageClassName: default
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    # selectorLabels: {}
    # subPath: ""
    # existingClaim:
    # extraPvcLabels: {}
```

**Comment by Mihai-CMM** [comment]
Hello
this doesn't seems to work for me either though i have bellow syntax

```
grafana:
  enabled: true
  persistence:
    enabled: true
    type: pvc
    storageClassName: ceph-blook
    accessModes:
    - ReadWriteOnce
    size: 4Gi
    finalizers:
    - kubernetes.io/pvc-protection
  namespaceOverride: ""
```

**Comment by mossroy** [comment]
It worked for me with:
```

grafana:
  (...)
  persistence:
    type: pvc
    enabled: true
    storageClassName: my-favorite-storage-class
    accessModes: ["ReadWriteOnce"]
    size: 500Mi
```
(with version 45.9.1 of the prometheus-kube-stack Helm chart)

**Comment by batchenr** [comment]
> It worked for me with:
> 
> ```
> 
> grafana:
>   (...)
>   persistence:
>     type: pvc
>     enabled: true
>     storageClassName: my-favorite-storage-class
>     accessModes: ["ReadWriteOnce"]
>     size: 500Mi
> ```
> 
> (with version 45.9.1 of the prometheus-kube-stack Helm chart)

Have the same issue this didnt work for me, anyone else? data just doesn't get saved after pod delete

**Comment by pashtet04** [comment]
It doesn't work on my current version 52.1.0 and higher, if first Grafana was created without PVC and then you enabled it then it fails

`Deployment.apps "prometheus-grafana" is invalid: [spec.template.spec.volumes[1].persistentVolumeClaim: Forbidden: may not specify more than 1 volume type, spec.template.spec.containers[2].volumeMounts[1].name: Not found: "storage", spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: "storage"]`

But it still works on version 45.26.0, for example.

**Comment by teq0** [comment]
I'm finding that some things are persisted but some things aren't, like user preferences. For example all starred dashboards are no longer starred, the default dashboard setting disappears etc.

And if the grafana pod(s) get recreated or updated, it takes a while for all the dashboads to actually appear in the list (I'm guessing this may be something to do with the init container).

**Comment by mattssll** [comment]
here is a working solution, 
first create a storage_class with provisioned (this will work for EKS):
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: ebs.csi.aws.com  # AWS EBS CSI driver
reclaimPolicy: Retain  # Retain the volume after the pod is deleted
```

next, here is my config in values.yaml

```
grafana:
  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    storageClassName: gp3
```

then I go to ec2>ebs, and see the disk there!
