### ISSUE TITLE
How to set google OAuth2 authentication in kube-prometheus helm chart

### ISSUE THREAD

**Issue by rfuelsh** [prometheus-community/helm-charts#2862]
### Is your feature request related to a problem ?

Trying to enable google Oauth2 authentication for grafana deployed via kubernetes prometheus helm chart

### Describe the solution you'd like.

how to enable google Oauth2 authentication with kubernetes prometheus helm chart 

### Describe alternatives you've considered.

Not sure how to customize grafana.ini

**Comment by zeritti** [comment]
Grafana has an article in its documentation: [Configure Google OAuth2 authentication](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/google/#configure-google-oauth2-authentication) (v9.3) and [authentication](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/). 

With respect to storing and retrieving `client_id` and `client_secret`, the Grafana chart's [README](https://github.com/grafana/helm-charts/tree/main/charts/grafana#how-to-securely-reference-secrets-in-grafanaini.) may help.

**Comment by rfuelsh** [comment]
hi @zeritti - thank you for your response, the main issue in kube-prometheus helm chart values.yaml

there seems to be no section for grafana.ini it seems and how to customize it:

```
grafana.ini:
  [auth.generic_oauth]
  enabled = true
  client_id = $__file{/etc/secrets/auth_generic_oauth/client_id}
  client_secret = $__file{/etc/secrets/auth_generic_oauth/client_secret}
```

I am looking for ways to setup the generic oauth using the values.yaml of kube-prometheus or something similar - https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

**Comment by zeritti** [comment]
You can use all the Grafana chart's [values](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml) underneath `grafana` in the stack's values file. Many subcharts' fields are not present as the file would otherwise be massive. E.g. inserting `grafana.grafana.ini` in the values file like this:
```
grafana:
  grafana.ini:
    check_for_updates: false
    reporting_enabled: false
    server:
      enable_gzip: true
    security:
      disable_gravatar: true
    dashboards:
      min_refresh_interval: 60s
    auth.google:
      enabled = true
      client_id = CLIENT_ID
      client_secret = CLIENT_SECRET
      scopes = https://www.googleapis.com/auth/userinfo.profile 
      https://www.googleapis.com/auth/userinfo.email
      auth_url = https://accounts.google.com/o/oauth2/auth
      token_url = https://accounts.google.com/o/oauth2/token
      allowed_domains = mycompany.com mycompany.org
      allow_sign_up = true
```

**Comment by rfuelsh** [comment]
thank you @zeritti - yu are awesome

I tried the code blob above with out client ID and client secret and got this

```
% helm upgrade kube-prometheus prometheus-community/kube-prometheus-stack --values values.yaml --install --create-namespace --namespace=monitoring --wait --timeout 8000s --debug --version ^34

history.go:56: [debug] getting history for release kube-prometheus
upgrade.go:142: [debug] preparing upgrade for kube-prometheus
Error: UPGRADE FAILED: template: kube-prometheus-stack/charts/grafana/templates/deployment.yaml:36:28: executing "kube-prometheus-stack/charts/grafana/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: kube-prometheus-stack/charts/grafana/templates/configmap.yaml:19:33: executing "kube-prometheus-stack/charts/grafana/templates/configmap.yaml" at <$value>: range can't iterate over enabled
```

any idea?

**Comment by zeritti** [comment]
@rfuelsh My apologies, thinking about ini, I overlooked that the auth.google config was not yaml. This should be correct:
```
grafana:
  grafana.ini:
    check_for_updates: false
    reporting_enabled: false
    server:
      enable_gzip: true
    security:
      disable_gravatar: true
    dashboards:
      min_refresh_interval: 60s
    auth.google:
      enabled: true
      client_id: CLIENT_ID
      client_secret: CLIENT_SECRET
      scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
      auth_url: https://accounts.google.com/o/oauth2/auth
      token_url: https://accounts.google.com/o/oauth2/token
      allowed_domains: mycompany.com mycompany.org
      allow_sign_up: true
```
