### ISSUE TITLE
[kube-prometheus-stack] alertmanager.config from existing secret

### ISSUE THREAD

**Issue by AurimasNav** [prometheus-community/helm-charts#2871]
### Is your feature request related to a problem ?

Currently I have `values.yaml` configured like this:
```yaml
alertmanager:
  config:
    global:
      resolve_timeout: 5m
      opsgenie_api_key: #{opsgenie_api_key}#
      opsgenie_api_url: https://api.opsgenie.com
    receivers:
    - name: heartbeat-receiver
      webhook_configs:
      - url: 'https://api.opsgenie.com/v2/heartbeats/prometheus/ping'
        send_resolved: true
        http_config:
          authorization:
            type: GenieKey
            credentials: #{opsgenie_api_key}#
...
```
I would like to move away from helm deployment pipeline to gitops style deployment with argocd, but obviously I don't want to commit secrets to git.

### Describe the solution you'd like.

I would like a way to provide those secrets to alertmanager.config from an existing secret resources which I can deploy beforehand with other tools (like external-secrets) or if there is already a way to do that, I would love a link to docs.
Could be something similar grafana's `sidecar.datasources` to https://github.com/grafana/helm-charts/tree/main/charts/grafana#sidecar-for-datasources

### Describe alternatives you've considered.

I've seen that there is a way to specify alertmanager config via `AlertmanagerConfig` CRD, but it does not solve issue with secrets values.
I've considered using sealed secrets for this, but upon further investigation it seems like a pain to manage across multiple environments.
