### ISSUE TITLE
[prometheus-kube-stack] Unable to add the basic authentication for prometheus

### ISSUE THREAD

**Issue by rshiva777** [prometheus-community/helm-charts#2878]
### Describe the bug a clear and concise description of what the bug is.

How to enable basic authentication for prometheus using the helm chart.

I have tried with adding extrasecrets to the prometheus, mounted into prometheus statefulset. But i am unable to updated the  **web.config.file** path, or override an existing secret that is created by prometheus automatically which is mounted to 
/etc/prometheus/web_config/web-config.yaml

for reference, statefulset args for prometheus
```
      containers:
      - args:
        - --web.console.templates=/etc/prometheus/consoles
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --storage.tsdb.retention.time=10d
        - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
        - --storage.tsdb.path=/prometheus
        - --web.enable-lifecycle
        - --web.external-url=http://bew.com
        - --web.route-prefix=/
        **- --web.config.file=/etc/prometheus/web_config/web-config.yaml**

```

### What's your helm version?

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9+vmware.1", GitCommit:"21eeb4527eefb360eb251addc358cea6997e8335", GitTreeState:"clean", BuildDate:"2022-05-04T00:18:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9+vmware.1", GitCommit:"21eeb4527eefb360eb251addc358cea6997e8335", GitTreeState:"clean", BuildDate:"2022-05-04T00:13:17Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

39.8.0

### What happened?

Unable to enable basic authentication for prometheus

### What you expected to happen?

enable basic authentication for prometheus

### How to reproduce it?

what parameters need to be enabled for enabling authentication for promethes in values.yaml

### Enter the command that you execute and failing/misfunctioning.

helm install prom ./kube-prometheus-stack -n promstack

**Comment by zeritti** [comment]
The web config file and value `prometheus.prometheusSpec.web` has also been discussed in issue #2828 which may provide some clarification.

**Comment by hostalp** [comment]
I've got it working via the ingress controller only (not directly if that's even possible). The config is as follows (I actually use the Nginx Inc ingress controller which uses slightly different configuration where I also have to modify the secret after it's been created, but the following should work fine for the more common one):
```yaml
prometheus:
  ## ExtraSecret can be used to store various data in an extra secret
  ## (use it for example to store hashed basic auth credentials)
  extraSecret:
    data:
      # htpasswd -nbB user password
      auth: |
        user:$2y$05$wbdg4wHEwDd00xQEEP8hMOyJOFcoTXoi.9hOJmncEgLmiGPoxRXRO

  ingress:
    enabled: true

    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    ingressClassName: nginx

    annotations:
      # CUSTOM: HTTP basic authentication
      # https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#authentication
      # https://kubernetes.github.io/ingress-nginx/examples/auth/basic/
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: prometheus-kube-prometheus-stack-extra
      nginx.ingress.kubernetes.io/auth-realm: 'Prometheus'
```
