### ISSUE TITLE
Redis prometheus exporter with multiple targets is not working

### ISSUE THREAD

**Issue by shubhamsetia05** [prometheus-community/helm-charts#2879]
### Describe the bug a clear and concise description of what the bug is.

Based on this pull request - https://github.com/prometheus-community/helm-charts/pull/2199

We are trying to monitor multiple redis using the redis exporter via helm, we tried with 1 redis earlier and it worked like a charm but when we are trying to do it for multiple redis, it simply doesn't work and we are not getting any metrics in prometheus, I have attached our values.yml file here. We tried both with and without telemetrypath but the result was the same.

[redis-values.yml.zip](https://github.com/prometheus-community/helm-charts/files/10334592/redis-values.yml.zip)

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.7-eks-fb459a0", GitCommit:"c240013134c03a740781ffa1436ba2688b50b494", GitTreeState:"clean", BuildDate:"2022-10-24T20:36:26Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-redis-exporter-5.3.0

### What's the chart version?

5.3.0

### What happened?

We are trying to monitor multiple redis using redis exporter but it doesn't seem to be working.

### What you expected to happen?

As per this pull request, we should be able to monitor multiple Redis
https://github.com/prometheus-community/helm-charts/pull/2199

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install redis-monitoring prometheus-community/prometheus-redis-exporter -f redis-values.yaml -n redis-monitoring

**Comment by shubhamsetia05** [comment]
@LeoQuote can you please help with this?

**Comment by LeoQuote** [comment]
Good, I checked the values file and found nothing wrong about it, let's start debugging with some standard steps:
1. check if the metric is available through service ip,  try `curl http://<service-ip>:9121/scrape?target=redis://<redis-server-1>:6379` on one of the k8s node. Expect to see `redis_up` metric , if not seen, this could be the exporter issue, try to debug the issue with exporter logs.
2. check if the service targets are discovered in prometheus, try to find it in prometheus `targets` or `service discovery` page, it should be present. expect to see the redis exporter targets in these page, if not , check the `serviceMonitor` resource, see if it's generated correctly, if it's discoveried by prometheus correctly.

if these above all seems to be good, I think that would be problem of prometheus or something else, certainly not the helm chart issue.

**Comment by shubhamsetia05** [comment]
@LeoQuote Thanks, we tried both the things:

1.  When we checked the metrics for different redis server from k8s(eks) worker node using the curl, we are able to see the metrics.
2. When we used `telemetrypath: /scrape` in values file, we checked the targets from prometheus and we could see server returned http status 400 bad request. Pod logs showed that metrics are available at `:9121:/metrics`

When we used `telemetrypath: /metrics`, prometheus target seems connected but `redis_up` gives 0 as an output, when we checked pod logs, we are seeing this error.
`level=error msg="Couldn't connect to redis instance (redis://myredis:6379)"`

Is it the problem with our prometheus scrape config since we are using static_config but trying to monitor multiple redis servers? This is our scrape config (snippet from helm values file)

`
      - job_name: "redis-monitoring"
         scrape_interval: 15s
         metrics_path: /scrape (or /metrics - based on the telemetry path)
         static_configs:
         - targets: ['<service-ip>:9121']
 `

Is there a way to use service discovery here?

**Comment by LeoQuote** [comment]
hi , could you just paste curl command you use and the output ? I'm not sure you're following.

**Comment by LeoQuote** [comment]
400 bad request could be a good start, you should get the relating logs and figure out why is this happening. misconfigure or network error, or outdated exporter image.

**Comment by shubhamsetia05** [comment]
@LeoQuote Here is the curl output.

```
curl http://<service-ip>:9121/scrape?target=redis://<redis-server-1>:6379 | grep redis_up
# HELP redis_up Information about the Redis instance
# TYPE redis_up gauge
redis_up 1
# HELP redis_uptime_in_seconds uptime_in_seconds metric
# TYPE redis_uptime_in_seconds gauge
redis_uptime_in_seconds 1.175622e+06

------------------------------
 curl http://<service-ip>:9121/scrape?target=redis://<redis-server-2>:6379 | grep redis_up
# HELP redis_up Information about the Redis instance
# TYPE redis_up gauge
redis_up 1
# HELP redis_uptime_in_seconds uptime_in_seconds metric
# TYPE redis_uptime_in_seconds gauge
redis_uptime_in_seconds 3.067443e+06
```

We will again try to use `telemetrypath: /scrape` and then try to debug the logs to see if we can find anything. Could you please confirm if our prometheus scrape config looks fine?

```
- job_name: "redis-monitoring"
  scrape_interval: 15s
  metrics_path: /scrape (or /metrics - based on the telemetry path)
  static_configs:
  - targets: ['<service-ip>:9121']
 ```

**Comment by LeoQuote** [comment]
seems the exporter it self is working good, problem should be the prometheus or servicemonitor config

this config looks good to me , below is mine , generated by prometheus operator( not a complete version)

```
- job_name: serviceMonitor/monitoring/redis-exporter-prometheus-redis-exporter/0
  honor_timestamps: true
  params:
    target:
    - redis://my-redis:6456
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /scrape
  scheme: http
  follow_redirects: true
```

you can read more about the prometheus config at [redis-exporter](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts)

`serviceMonitor` does not support multiple `target` or did not support multiple `target` at that time, the chart implemented it as multiple `endpoints` instead

**Comment by shubhamsetia05** [comment]
@LeoQuote Thanks, yes it was the problem with prometheus scrape config as exporter was able to retrieve the metrics. When we used the prometheus scrape in following format, it worked and we are able to see Elasticache (AWS managed redis) metrics in Prometheus --> Thanos --> Grafana

```
       - job_name: "elasticache-redis-monitoring"
         scrape_interval: 15s
         static_configs:
         - targets:
           - redis://<redis-server-1>:6379
           - redis://<redis-server-2>:6379
           - redis://<redis-server-3>:6379
           - redis://<redis-server-4>:6379
         metrics_path: /scrape
         relabel_configs:
           - source_labels: [__address__]
             target_label: __param_target
           - source_labels: [__param_target]
             target_label: instance
           - target_label: __address__
             replacement: <redis-exporter-svc-ip>:9121
```

1 last question, before we close this issue, we are also looking to do something similar with AWS RDS, we came across https://github.com/percona/rds_exporter and https://mash213.wordpress.com/2016/05/05/graphing-amazon-rds-mysql-metrics-with-prometheus-grafana/ but didn't see any provision for multiple targets, do you have any idea, how we can go about it?

Once again, thanks for all your help 🙏

**Comment by LeoQuote** [comment]
First the exporter itself should support multi target scrape model, if not supported you can contribute to this project and make it possible , you can use redis exporter and black box exporter as an example.

and btw, seems you tried to use the helm chart and did not work? You seems to be using raw config of Prometheus instead of servicemonitor, is there any problem? I’m happy to help with that.

**Comment by shubhamsetia05** [comment]
@LeoQuote We are using helm for prometheus as well, but when we used below config, it simply didn't work and on prometheus console we could see HTTP 400 error. We tried checking the logs of redis exporter as well as promethues but couldn't find anything.

```
- job_name: "redis-monitoring"
  scrape_interval: 15s
  metrics_path: /scrape (or /metrics - based on the telemetry path)
  static_configs:
  - targets: ['<service-ip>:9121']
  ```

So we moved on to the different approach & used the following code in prometheus scrape in helm values file & it started working.

```
       - job_name: "elasticache-redis-monitoring"
         scrape_interval: 15s
         static_configs:
         - targets:
           - redis://<redis-server-1>:6379
           - redis://<redis-server-2>:6379
           - redis://<redis-server-3>:6379
           - redis://<redis-server-4>:6379
         metrics_path: /scrape
         relabel_configs:
           - source_labels: [__address__]
             target_label: __param_target
           - source_labels: [__param_target]
             target_label: instance
           - target_label: __address__
             replacement: <redis-exporter-svc-ip>:9121
```

Now can you tell us are we doing anything wrong?

**Comment by LeoQuote** [comment]
This certainly would not work, I advice you read the Prometheus document https://prometheus.io/docs/guides/multi-target-exporter/ , after that , you should be able to understand why this is happening.

**Comment by LeoQuote** [comment]
Can you try installing the helm chart with debug flag and provide all the log?

The servicemonitor resource could help me to see what could go wrong.

**Comment by shubhamsetia05** [comment]
@LeoQuote I have added both the config as well as debug logs.
```
serviceMonitor:
  # When set true then use a ServiceMonitor to configure scraping
  enabled: true
  multipleTarget: true
  telemetryPath: /scrape
  namespace: monitoring
  targets:
  # for every targets, url and name must be set,
  # an individual additionalRelabeling can be set for every target
  - url: redis://<redis-server-1>:6379
    name: redis-server-1
  - url: redis://<redis-server-2>:6379
    name: redis-server-2
```

*redis-exporter logs*

```
time="2023-01-09T08:18:51Z" level=info msg="Redis Metrics Exporter v1.44.0    build date:     sha1: 19f7b036bb46869858eec74d8d3fc2186d641399    Go: go1.19    GOOS: linux    GOARCH: amd64"
time="2023-01-09T08:18:51Z" level=debug msg="Enabling debug output"
time="2023-01-09T08:18:51Z" level=debug msg="NewRedisExporter options: exporter.Options{User:\"\", Password:\"\", Namespace:\"redis\", PasswordMap:map[string]string{}, ConfigCommandName:\"CONFIG\", CheckKeys:\"\", CheckSingleKeys:\"\", CheckStreams:\"\", CheckSingleStreams:\"\", CheckKeysBatchSize:1000, CheckKeyGroups:\"\", MaxDistinctKeyGroups:100, CountKeys:\"\", LuaScript:[]uint8(nil), ClientCertFile:\"\", ClientKeyFile:\"\", CaCertFile:\"\", InclConfigMetrics:false, RedactConfigMetrics:true, InclSystemMetrics:false, SkipTLSVerification:false, SetClientName:true, IsTile38:false, IsCluster:false, ExportClientList:false, ExportClientsInclPort:false, ConnectionTimeouts:15000000000, MetricsPath:\"/metrics\", RedisMetricsOnly:false, PingOnConnect:false, Registry:(*prometheus.Registry)(0xc0000ca960), BuildInfo:exporter.BuildInfo{Version:\"v1.44.0\", CommitSha:\"19f7b036bb46869858eec74d8d3fc2186d641399\", Date:\"\"}}"
time="2023-01-09T08:18:51Z" level=debug msg="parseKeyArg(): Got empty key arguments, parsing skipped"
time="2023-01-09T08:18:51Z" level=debug msg="keys: []exporter.dbKeyPair(nil)"
time="2023-01-09T08:18:51Z" level=debug msg="parseKeyArg(): Got empty key arguments, parsing skipped"
time="2023-01-09T08:18:51Z" level=debug msg="singleKeys: []exporter.dbKeyPair(nil)"
time="2023-01-09T08:18:51Z" level=debug msg="parseKeyArg(): Got empty key arguments, parsing skipped"
time="2023-01-09T08:18:51Z" level=debug msg="streams: []exporter.dbKeyPair(nil)"
time="2023-01-09T08:18:51Z" level=debug msg="parseKeyArg(): Got empty key arguments, parsing skipped"
time="2023-01-09T08:18:51Z" level=debug msg="singleStreams: []exporter.dbKeyPair(nil)"
time="2023-01-09T08:18:51Z" level=debug msg="parseKeyArg(): Got empty key arguments, parsing skipped"
time="2023-01-09T08:18:51Z" level=debug msg="countKeys: []exporter.dbKeyPair(nil)"
time="2023-01-09T08:18:51Z" level=info msg="Providing metrics at :9121/metrics"
time="2023-01-09T08:18:51Z" level=debug msg="Configured redis addr: \"redis://myredis:6379\""
```

Not sure why it says redis address as `myredis:6379`

Here is the Prometheus scrape config

```
- job_name: "redis-monitoring"
  scrape_interval: 15s
  metrics_path: /scrape
  static_configs:
  - targets: ['<service-ip>:9121']
```


`prometheus logs`

```
ts=2023-01-09T08:23:03.862Z caller=scrape.go:1328 level=debug component="scrape manager" scrape_pool=redis-monitoring target=http://172.20.13.54:9121/scrape msg="Scrape failed" err="server returned HTTP status 400 Bad Request"
ts=2023-01-09T08:23:18.863Z caller=scrape.go:1328 level=debug component="scrape manager" scrape_pool=redis-monitoring target=http://172.20.13.54:9121/scrape msg="Scrape failed" err="server returned HTTP status 400 Bad Request"
```
