### ISSUE TITLE
[prometheus-community/prometheus] How can I easily add labels to all metrics in prometheus

### ISSUE THREAD

**Issue by danilo-lopes** [prometheus-community/helm-charts#2884]
### Describe the bug a clear and concise description of what the bug is.

I'm using Prometheus and Grafana by AWS to monitor some EKS clusters on different AWS accounts. The prometheus remoteWrite on this EKS clusters are sending the metrics to one centrilized prometheus(AWS managed) in one centrilized AWS account.

I need to know which metric is from which environment, then I believe labels will help me.

But I couldn't understand how can I label all metrics or specific metrics to do this..

### What's your helm version?

v3.10.3

### What's your kubectl version?

v1.25.2

### Which chart?

prometheus

### What's the chart version?

15.17.0

### What happened?

I tried this configuration:

```
server:
  remoteWrite:
    - url: <ommited>
      sigv4:
        region: <ommited>
        role_arn: <ommited>
      queue_config:
        max_samples_per_send: 1000
        max_shards: 200
        capacity: 2500
      write_relabel_configs:
      - source_labels: [__address__]
        target_label: environment
        replacement: hml
        action: keep
```

and this:

```
server:
  global:
    external_labels:
      environment: hml
  remoteWrite:
    - url: <ommited>
      sigv4:
        region: <ommited>
        role_arn: <ommited>
      queue_config:
        max_samples_per_send: 1000
        max_shards: 200
        capacity: 2500
```

None of them worked

### What you expected to happen?

To possibly label metrics and see them like this:

```
kube_node_info{...,environment="hml", foo="bar"}
```

### Enter the changed values of values.yaml?

```
serviceAccounts:
  server:
    name: <ommited>
    annotations: 
      <ommited>
server:
  remoteWrite:
    - url: <ommited>
      sigv4:
        region: <ommited>
        role_arn: <ommited>
      queue_config:
        max_samples_per_send: 1000
        max_shards: 200
        capacity: 2500
  persistentVolume:
    storageClass: "gp2"
    size: 100Gi
  resources:
    limits:
      cpu: 1500m
      memory: 3000Mi
    requests:
      cpu: 1500m
      memory: 3000Mi
  retention: "3d"
```

### Enter the command that you execute and failing/misfunctioning.

`helm upgrade --install aws-prometheus prometheus-community/prometheus --version 15.17.0 -n aws-prometheus -f hml-aws-prometheus-values.yml`

**Comment by danilo-lopes** [comment]
This configuration worked:

```
server:
  global:
    external_labels:
      environment: hml
```

But this labels are showed only on the centrilized prometheus, not on the local ones.
