### ISSUE TITLE
[prometheus] (19.3.0)breaking changes by removing VPA v1beta2

### ISSUE THREAD

**Issue by arukiidou** [prometheus-community/helm-charts#2893]
### Describe the bug a clear and concise description of what the bug is.

- #2875 has a breaking change occurs. but it was not major bump.
  -  see: https://github.com/prometheus-community/helm-charts/pull/2875#pullrequestreview-1239247167
- Affected users: If all apply
  - Upgrade (not a fresh install)
  - Set values `.Values.verticalPodAutoscaler.enabled` on this chart
  - Users who can only use VPA v1beta1

### What's your helm version?

version.BuildInfo{Version:"v3.10", GitCommit:"", GitTreeState:"", GoVersion:"go1.19"}

### What's your kubectl version?

Client Version: v1.25.2 Kustomize Version: v4.5.7 Server Version: v1.25.3

### Which chart?

prometheus

### What's the chart version?

19.3.0

### How to reproduce it?

- install autoscaling.k8s.io/v1beta2(VerticalPodAutoscaler)
- install prometheus charts(19.2.2) with `.Values.verticalPodAutoscaler.enabled`
- upgrade prometheus charts(19.3.0)

```
kind create cluster --image=kindest/node:v1.16.15
git clone https://github.com/kubernetes/autoscaler.git
git switch vpa-release-0.9
cd autoscaler/vertical-pod-autoscaler/
./hack/vpa-up.sh
```

### Enter the changed values of values.yaml?

```
server:
  verticalAutoscaler:
    ## If true a VPA object will be created for the controller (either StatefulSet or Deployemnt, based on above configs)
    enabled: true
    updateMode: "Auto"
    containerPolicies:
    - containerName: 'prometheus-server'
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade prometheus prometheus-community/prometheus --version 19.3.0 --reuse-values
