### ISSUE TITLE
kube-prometheus-stack: prometheus-node-exporter nodeAffinity

### ISSUE THREAD

**Issue by cdenneen** [prometheus-community/helm-charts#2908]
### Is your feature request related to a problem ?

Currently prometheus-node-exporter tries to run on all nodes, Fargate ones remain Pending.

### Describe the solution you'd like.

Need a PromNodeExporterSpec to allow for nodeAffinity like:

```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - prod
```

### Describe alternatives you've considered.

helm post-renderer but shouldn't have to do this as other components allow for the spec modifications, this should follow suit.

**Comment by zeritti** [comment]
The prometheus-node-exporter chart (a subchart in this context) supports [affinity](https://github.com/prometheus-community/helm-charts/blob/067eb7a60f38c69a13aa0ed8bfc4501af52fc3fb/charts/prometheus-node-exporter/values.yaml#L161) that can be used in your chart's values file:
```
nodeExporter:
  enabled: true

prometheus-node-exporter:
  affinity: {}
```
