### ISSUE TITLE
[kube-prometheus-stack] webhook configuration should respect operators namespace filter

### ISSUE THREAD

**Issue by a-thaler** [prometheus-community/helm-charts#2915]
### Is your feature request related to a problem ?

When configuring the operator to (not) interact with resources for specific namespaces only by using the `prometheusOperator.namespaces` or `prometheusOperator. denyNamespaces` I would expect that also the webhooks are not getting triggered for the excluded namespaces. Indeed, the webhooks are ignoring that options and are getting triggered for all namespaces.

### Describe the solution you'd like.

I would expect that the webhooks are respecting the namespaces configuration id present, so that there is also no interaction from apiserver to the operator instance for specific namespaces.

So translating the mentioned options above to an addition to the webhook configuration like:
```yaml
namespaceSelector:
  matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - "myDeniedNamespace"
```

### Describe alternatives you've considered.

Alternatively the webhook namespaceSelector could be configurable via values.yaml independently, but a re-usage of the mentioned operator values sounds more reasonable.

### Additional context.

If that request sounds reasonable, I could provide a PR for the change.
