### ISSUE TITLE
Service monitor is not being create in Blackbox exporter

### ISSUE THREAD

**Issue by codeRuslan** [prometheus-community/helm-charts#2918]
I have tried to install Blackbox exporter, and just changed this standard values in values.yaml in helm chart
```

namespaceOverride: "monitoring"

serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a prometheus operator
  ## https://github.com/coreos/prometheus-operator for blackbox-exporter itself
  ##
  selfMonitor:
    enabled: false
    additionalMetricsRelabels: {}
    additionalRelabeling: []
    labels: {}
    interval: 30s
    scrapeTimeout: 30s

  ## If true, a ServiceMonitor CRD is created for a prometheus operator
  ## https://github.com/coreos/prometheus-operator for each target
  ##
  enabled: true
```
So I only changed serviceMonitor.enabled: true and override default namespace, however serviceMonitor just will not being created, even just using helm template resulted in showing no output of servicemonitor.yaml, which is supposed to be created, as I changed value serviceMonitor.enabled to true

Maybe, this additional information will be helpful (For prometheus I used prometheus-stack):

```
NAME                                                                  READY   STATUS    RESTARTS   AGE
pod/alertmanager-monitoring-prometheus-stac-alertmanager-0            2/2     Running   1          26m
pod/monitoring-black-box-exporter-prometheus-blackbox-exporter6c4fw   1/1     Running   0          26m
pod/monitoring-prometheus-stac-operator-85779b977b-9qm87              1/1     Running   0          26m
pod/monitoring-prometheus-stack-grafana-65884866bd-wb5tg              3/3     Running   0          26m
pod/monitoring-prometheus-stack-kube-state-metrics-8bc9fdfdc-btb6k    1/1     Running   0          26m
pod/monitoring-prometheus-stack-prometheus-node-exporter-5kfx5        1/1     Running   0          26m
pod/monitoring-prometheus-stack-prometheus-node-exporter-ggkzg        1/1     Running   0          26m
pod/prometheus-monitoring-prometheus-stac-prometheus-0                2/2     Running   0          26m

NAME                                                                 TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
service/alertmanager-operated                                        ClusterIP      None             <none>        9093/TCP,9094/TCP,9094/UDP   26m
service/monitoring-black-box-exporter-prometheus-blackbox-exporter   ClusterIP      10.96.129.197    <none>        9115/TCP                     26m
service/monitoring-prometheus-stac-alertmanager                      ClusterIP      10.102.199.86    <none>        9093/TCP                     26m
service/monitoring-prometheus-stac-operator                          ClusterIP      10.99.153.124    <none>        443/TCP                      26m
service/monitoring-prometheus-stac-prometheus                        LoadBalancer   10.96.255.5      <pending>     9090:31686/TCP               26m
service/monitoring-prometheus-stack-grafana                          ClusterIP      10.108.117.184   <none>        80/TCP                       26m
service/monitoring-prometheus-stack-kube-state-metrics               ClusterIP      10.104.194.135   <none>        8080/TCP                     26m
service/monitoring-prometheus-stack-prometheus-node-exporter         ClusterIP      10.98.194.5      <none>        9100/TCP                     26m
service/prometheus-operated                                          ClusterIP      None             <none>        9090/TCP                     26m

NAME                                                                  DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/monitoring-prometheus-stack-prometheus-node-exporter   2         2         2       2            2           <none>          26m

NAME                                                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/monitoring-black-box-exporter-prometheus-blackbox-exporter   1/1     1            1           26m
deployment.apps/monitoring-prometheus-stac-operator                          1/1     1            1           26m
deployment.apps/monitoring-prometheus-stack-grafana                          1/1     1            1           26m
deployment.apps/monitoring-prometheus-stack-kube-state-metrics               1/1     1            1           26m

NAME                                                                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/monitoring-black-box-exporter-prometheus-blackbox-exporter-5ff87bdc7   1         1         1       26m
replicaset.apps/monitoring-prometheus-stac-operator-85779b977b                         1         1         1       26m
replicaset.apps/monitoring-prometheus-stack-grafana-65884866bd                         1         1         1       26m
replicaset.apps/monitoring-prometheus-stack-kube-state-metrics-8bc9fdfdc               1         1         1       26m

NAME                                                                    READY   AGE
statefulset.apps/alertmanager-monitoring-prometheus-stac-alertmanager   1/1     26m
statefulset.apps/prometheus-monitoring-prometheus-stac-prometheus       1/1     26m
```

Is there something that I'm missing from documentation ?

**Comment by zeritti** [comment]
The service monitor gets created if enabled and per each target as set in `serviceMonitor.targets[]`. If there is no target defined in the targets list, no service monitor will be created.

**Comment by codeRuslan** [comment]
@zeritti But what if I just setted up targets inside additionalScrapeConfig in prometheus, in order to configure targets to scrape from, would not it work?

```
    additionalScrapeConfigs: 
    - job_name: 'blackbox-external-targets'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://www.google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-blackbox-prometheus-blackbox-exporter:9115
```
