### ISSUE TITLE
[kube-prometheus-stack] - Unable to create additionalPrometheusRulesMap from a file.

### ISSUE THREAD

**Issue by jpicara** [prometheus-community/helm-charts#2930]
### Describe the bug a clear and concise description of what the bug is.

Hi,
I was trying to add some additional Prometheus Rules Map in order to monitor some specific applications in our Stack. I could do it on the easy way by just adding additionalPrometheusRulesMap: into the value.yaml and list there all the alerts. As an example:
```
additionalPrometheusRulesMap:
  rule-name:
    groups:
      - name: kafka-alerts
        rules:
          - alert: KafkaAbsentConsumerConnectionCDREventReceiver
          ....
          ....

```
However I would like to avoid to have a huge values.yaml and structure the alerts into some specific folders to be read from values.yaml file. I do not find anything like that in the documentation so I tried to create a separate file as PrometheusRule but it was not taking into the deployment.
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: monitoring-platform-kube-p-kafka.rules
  namespace: {{Release.namespace}}
  generation: 1
  annotations:
    meta.helm.sh/release-name: monitoring-platform
    meta.helm.sh/release-namespace: platform
  labels:
    app: kube-prometheus-stack
    release: monitoring-platform
spec:
  groups:
  - name: kafka.alerts
    rules:
```
Could someone help me on this of taking alerts coming from a different files than values file?

### What's your helm version?

version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

### Enter the command that you execute and failing/misfunctioning.

helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack -n kube-prometheus
