### ISSUE TITLE
[kube-prometheus-stack] Unable to install chart from OCI via Flux

### ISSUE THREAD

**Issue by thezanke** [prometheus-community/helm-charts#2940]
### Describe the bug

Applying the manifest found at https://github.com/fluxcd/flux2/manifests/monitoring/kube-prometheus-stack, which uses the OCI registry for the "41.x" branch for KPS, my HelmChart resource for kube-prometheus-stack is unhealthy and gives me the following reason:

```
chart verification error: failed to verify oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack:41.7.3: no matching signatures:                                
  error getting target ctfe.pub by usage: error verifying local metadata; local cache may be corrupt: tuf: failed to decode snapshot.json: expired at 2023-01-22 00:08:42 +0000 UTC
```

As far as I can tell this is the only chart having any issues.

### What's your helm version?

```
version.BuildInfo{Version:"v3.9.1", GitCommit:"a7c043acb5ff905c261cfdc923a35776ba5e66e4", GitTreeState:"clean", GoVersion:"go1.18.4"}
```

### What's your kubectl version?

```
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.22.15-eks-fb459a0
```

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.x

### What happened?

Received the error:

```
chart verification error: failed to verify oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack:41.7.3: no matching signatures:                                
  error getting target ctfe.pub by usage: error verifying local metadata; local cache may be corrupt: tuf: failed to decode snapshot.json: expired at 2023-01-22 00:08:42 +0000 UTC
```

### What you expected to happen?

Synchronize HelmChart successfully

### How to reproduce it?

Add resources to flux-powered cluster:

```
apiVersion: v1
kind: List
items:
  - apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: GitRepository
    metadata:
      name: flux-monitoring
      namespace: flux-system
    spec:
      interval: 30m0s
      ref:
        branch: main
      url: https://github.com/fluxcd/flux2
  - apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    kind: Kustomization
    metadata:
      name: kube-prometheus-stack
      namespace: flux-system
    spec:
      interval: 1h0m0s
      path: ./manifests/monitoring/kube-prometheus-stack
      prune: true
      sourceRef:
        kind: GitRepository
        name: flux-monitoring
```

### Enter the command that you execute and failing/misfunctioning.

flux reconcile kustomization kube-prometheus-stack -n flux-system
