### ISSUE TITLE
[prometheus-pushgatweay] Unable to set NodePort

### ISSUE THREAD

**Issue by sepulworld** [prometheus-community/helm-charts#2955]
### Describe the bug a clear and concise description of what the bug is.

Hi! New chart install trying to use node port gives me following error (k8s 1.21, latest helm chart for pushgateway)

```yaml
service:
  type: NodePort
  port: 9091
  targetPort: 9091
  nodePort: 31001
```

```
Error: UPGRADE FAILED: failed to create resource: Service "push-gateway" is invalid: spec.clusterIPs[0]: Invalid value: "None": may not be set to 'None' for NodePort services
```

### What's your helm version?

3

### What's your kubectl version?

1.21

### Which chart?

prometheus-pushgateway

### What's the chart version?

2.0.3

### What happened?

```
Error: UPGRADE FAILED: failed to create resource: Service "push-gateway" is invalid: spec.clusterIPs[0]: Invalid value: "None": may not be set to 'None' for NodePort services
```

When using the following service config (statefulset)

```yaml
runAsStatefulSet: true

service:
  type: NodePort
  port: 9091
  targetPort: 9091
  nodePort: 31004

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
```

### What you expected to happen?

Service gets created using nodeport 

### How to reproduce it?

Deploy with above config

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install push-gateway \
  --namespace default
