### ISSUE TITLE
[kube-prometheus-stack] Support attachMetadata in the kubelet ServiceMonitor Template

### ISSUE THREAD

**Issue by Daniel-Vaz** [prometheus-community/helm-charts#2961]
### Is your feature request related to a problem ?

We need to grab Node Labels from the Kubelet scrape jobs for some of our dashboards. 

### Describe the solution you'd like.

Setting the following values inside the Kubelet servicemonitor
```
attachMetadata:
  node: true
```

### Describe alternatives you've considered.

We disable the Servicemonitor creation from the base values and create the servicemonitor ourselves.

**Comment by zeritti** [comment]
Adding the parameter to a custom podMonitor and a custom serviceMonitor created through `additionaServiceMonitors` works as expected with e.g. labels `__meta_kubernetes_node_label*` being attached to the targets. Based on this, Prometheus works as expected with the configuration against the role `endpoints`. 

For the kubelet serviceMonitor, no, the node metadata do not get attached. Prometheus configuration seems correct, though, with e.g.
```
- job_name: serviceMonitor/monitoring/kube-prometheus-stack-kubelet/0
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
...
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
    namespaces:
      own_namespace: false
      names:
      - kube-system
    attach_metadata:
      node: true
```
Unfortunately, Prometheus does not say a word about it in debug mode. At the moment, I cannot pinpoint the cause of this result. It might have something to do with the fact that kubelet is the node.
