### ISSUE TITLE
Confusion in sidecar setup with ingress for external access

### ISSUE THREAD

**Issue by hauks96** [prometheus-community/helm-charts#2968]
I'm attempting to set up multi cluster monitoring with kube-prometheus-stack. But I am unsure of how the sidecar can actually be exposed outside the cluster on a custom domain to be reachable by an observer cluster.

There are 2 services for the thanos sidecar. Both of which can be either enabled or disabled in the helm chart.
- [serviceThanosSidecar.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/serviceThanosSidecar.yaml)
```yaml
 # Service for thanos service discovery on sidecar
  # Enable this can make Thanos Query can use
  # `--store=dnssrv+_grpc._tcp.${kube-prometheus-stack.fullname}-thanos-discovery.${namespace}.svc.cluster.local` to discovery
  # Thanos sidecar on prometheus nodes
  # (Please remember to change ${kube-prometheus-stack.fullname} and ${namespace}. Not just copy and paste!)
  thanosService:
    enabled: false
    annotations: {}
    labels: {}
```
- [serviceThanosSidecarExternal.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/serviceThanosSidecarExternal.yaml)
```yaml
 # Service for external access to sidecar
  # Enabling this creates a service to expose thanos-sidecar outside the cluster.
  thanosServiceExternal:
    enabled: false
```

- The serviceThanosSidecar has ClusterIP: None
- The serviceThanosSidecarExternal is type LoadBalancer for some reason? Why not ClusterIP?

There is one [ingressThanosSidecar.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/ingressThanosSidecar.yaml) that according to the [comments on artifacthub](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=values&path=prometheus.thanosIngress) should expose the sidecar externally:
```yaml
# Ingress exposes thanos sidecar outside the cluster
  thanosIngress:
    enabled: false
```

- The ingress is configured to expose the prometheus service, not the serviceThanosSidecarExternal or serviceThanosSideCar, how is this ingress supposed to expose the sidecar externally? Do I need create my own ingress for serviceThanosSidecarExternal to be able to actually access the sidecar externally?

Here is my configuration, the result of which does not get me a response with\
 `$ curl https://thanos-gateway.dev-cluster.example.com`\
as defined in the thanosIngress section. Also going to the actual url in browser gives 404 not found which is the default response for traefik.

I am running a K3S kubernetes cluster which uses traefik router. The cluster is hosted on amazon, and all traffic to *.dev-cluster.example.com from TCP/80 TCP/443 is routed to the cluster via a public network load balancer.

```yaml
  # Disable grafana
  grafana:
    enabled: false

  # Extra labels
  defaultRules:
    additionalRuleLabels:
      cluster: my-dev-cluster
      stage: dev
      region: eu-west-1

  # Disable
  kubelet:
    enabled: false
  kubeControllerManager:
    enabled: false
  coreDns:
    enabled: false
  kubeApiServer:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false

  # Enable
  kubeStateMetrics:
    enabled: true
  nodeExporter:
    enabled: true

  # Prometheus additions
  prometheus:
    # Thanos service discovery
    thanosService:
      enabled: true
    thanosServiceMonitor:
      enabled: true
    # Externally accessible service
    thanosServiceExternal:
      enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: public-domain-production-acme-issuer
      hosts:
        - prometheus.dev-cluster.example.com
      path: /
      pathType: Prefix
      tls:
        - secretName: public-domain-production-tls
          hosts:
            - prometheus.dev-cluster.example.com
    prometheusSpec:
      # Should be enabled according to thanos docs
      enableAdminAPI: true
      # Metric label additions
      externalLabels:
        cluster: dev-cluster
        stage: dev
        region: eu-west-1
      # Sidecar using shared S3 storage
      thanos:
        image: "quay.io/thanos/thanos:v0.30.1"
        version: "v0.30.1"
        objectStorageConfig:
          name: "thanos-objstore-config"
          key: "s3-bucket.yaml"
      scrapeInterval: "2m"
      scrapeTimeout: "60s"
      evaluationInterval: "2m"
      retention: 2d
    # Expose thanos sidecar outside the cluster
    thanosIngress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "public-domain-production-acme-issuer"
      hosts:
        - thanos-gateway.dev-cluster.example.com
      paths:
        - /
      pathType: Prefix
      tls:
        - secretName: public-domain-production-tls
          hosts:
            -  thanos-gateway.dev-cluster.example.com
```
