### ISSUE TITLE
[prometheus] Scrape config jobs have insecure_skip_verify enabled by default

### ISSUE THREAD

**Issue by nicely-dunn** [prometheus-community/helm-charts#3002]
### Describe the bug a clear and concise description of what the bug is.

The default Prometheus scrape jobs that contain `tls_config` all have `insecure_skip_verify: true`

Based on the comment block above `insecure_skip_verify`, this should be commented out and disabling verification be a choice made by the user, and not the default configuration.
```
tls_config:
  ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  # If your node certificates are self-signed or use a different CA to the
  # master CA, then disable certificate verification below. Note that
  # certificate verification is an integral part of a secure infrastructure
  # so this should only be disabled in a controlled environment. You can
  # disable certificate verification by uncommenting the line below.
  #
  insecure_skip_verify: true
```

### What's your helm version?

version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-18T19:15:31Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.4 Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.8-eks-ffeb93d", GitCommit:"abb98ec0631dfe573ec5eae40dc48fd8f2017424", GitTreeState:"clean", BuildDate:"2022-11-29T18:45:03Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus

### What's the chart version?

19.3.3

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/prometheus
