### ISSUE TITLE
[prometheus-kube-stack] small amount of metrics based on scrape interval

### ISSUE THREAD

**Issue by jpedro1992** [prometheus-community/helm-charts#3006]
### Describe the bug a clear and concise description of what the bug is.

Modifying the global scrape interval works until a certain extend. I can clearly see that Prometheus scrapes every 3 or 1 second depending on the scrape interval that was set up, however, I only get around 5/4 samples which means that I only get a data point every 10 seconds. 

Do I need to modify something in kubelet/cadvisor to make this work? The goal is to have metrics (e.g., CPU and memory usage from pods) every 5 seconds.  

Thanks in advance.

@mielverkerken

### What's your helm version?

version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.15", GitCommit:"1d79bc3bcccfba7466c44cc2055d6e7442e140ea", GitTreeState:"clean", BuildDate:"2022-09-21T12:12:26Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack-40.1.2

### What's the chart version?

kube-prometheus-stack-40.1.2

### What happened?

As you can see, the number of scrapes and the number of metrics do not match.

![image](https://user-images.githubusercontent.com/8495553/217531890-9220e4b9-ccb2-4933-abb4-3e3b3542eb22.png)

![image (1)](https://user-images.githubusercontent.com/8495553/217531893-e915ca35-68ab-457f-a132-c163cb27e505.png)

![image (2)](https://user-images.githubusercontent.com/8495553/217531906-e2ad7646-be64-4dd3-808b-eab9ab66ce0f.png)

![image (3)](https://user-images.githubusercontent.com/8495553/217531914-63a389e5-50a7-43ca-80d1-ae76fce809b7.png)

### What you expected to happen?

The number of scrapes and the number of metrics to match.

### How to reproduce it?

Kubeadm version: v.1.22.4

Also, failed with kubeadm v1.24.4 and kube-prometheus-stack-44.4.1

### Enter the changed values of values.yaml?

```
prometheus:
  prometheusSpec:
      disableCompaction: false
      apiserverConfig: {}
      additionalArgs: []
      scrapeInterval: "3s"
      scrapeTimeout: "3s"
      evaluationInterval: "5s"
      logLevel: debug

kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    interval: "1s"

```

### Enter the command that you execute and failing/misfunctioning.

not applicable.
