### ISSUE TITLE
[kube-prometheus-stack] Persistent volume claim not being deleted on uninstall

### ISSUE THREAD

**Issue by otto-joe** [prometheus-community/helm-charts#3009]
### Describe the bug a clear and concise description of what the bug is.

Running a `helm uninstall` of the `kube-prometheus-stack` chart does not remove the Prometheus PVC.

### What's your helm version?

version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:38:15Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.9.1

### What happened?

I'm defining a volume claim template in the values file for persistent storage of the Prometheus DB. When uninstalling the chart, the PVC is left dangling and is not removed. Note that kube-prometheus-stack is a dependency of a higher level chart.

We are using local storage, here is the storage class definition:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

Because we are using local storage, we define a persistent volume:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $release }}-prometheus-pv
  namespace: {{ $namespace }}
  labels:
    type: cluster-monitoring
    application: prometheus
spec:
  storageClassName: local-storage
  capacity:
    storage: "20Gi"
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/var/lib/app/monitoring/prometheus"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "db"
          operator: Exists
```
In the chart's values, we define persistent storage for Promtheus:

```yaml
kube-prometheus-stack:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-storage
          accessModes: ["ReadWriteOnce"]
          selector:
            matchLabels:
              type: cluster-monitoring
              application: prometheus
          resources:
            requests:
              storage: 20Gi
```

When uninstalling, only the PV is deleted, but the PVC remains:

```shell
❯ helm uninstall -n prometheus cluster-monitoring --debug                                  
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/jloesch/.kube/k8s-16
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/jloesch/.kube/k8s-16
uninstall.go:95: [debug] uninstall: Deleting cluster-monitoring
client.go:299: [debug] Starting delete for "cluster-monitoring-ingress" Ingress
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-prometheus" Service
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kube-proxy" Service
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-state-metrics" Service
client.go:299: [debug] Starting delete for "cluster-monitoring-prometheus-node-exporter" Service
client.go:299: [debug] Starting delete for "cluster-monitoring-grafana" Service
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-operator" Service
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-coredns" Service
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kube-etcd" Service
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-operator" Deployment
client.go:299: [debug] Starting delete for "cluster-monitoring-grafana" Deployment
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-state-metrics" Deployment
client.go:299: [debug] Starting delete for "cluster-monitoring-prometheus-node-exporter" DaemonSet
client.go:299: [debug] Starting delete for "cluster-monitoring-grafana" RoleBinding
client.go:299: [debug] Starting delete for "cluster-monitoring-grafana" Role
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-prometheus" ClusterRoleBinding
client.go:299: [debug] Starting delete for "cluster-monitoring-grafana-clusterrolebinding" ClusterRoleBinding
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-state-metrics" ClusterRoleBinding
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-operator" ClusterRoleBinding
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-prometheus" ClusterRole
client.go:299: [debug] Starting delete for "cluster-monitoring-grafana-clusterrole" ClusterRole
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-state-metrics" ClusterRole
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-operator" ClusterRole
client.go:299: [debug] Starting delete for "cluster-monitoring-prometheus-pv" PersistentVolume
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-apiserver" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-alertmanager-overview" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-namespace-by-workload" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-k8s-resources-namespace" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-etcd" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-prometheus" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-proxy" ConfigMap
client.go:299: [debug] Starting delete for "grafana-config" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-k8s-resources-node" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-node-cluster-rsrc-use" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-nodes" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-cluster-total" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kubelet" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-scheduler" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-node-rsrc-use" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-pod-total" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-k8s-resources-pod" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-k8s-resources-cluster" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-persistentvolumesusage" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-controller-manager" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-k8s-coredns" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-nodes-darwin" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-grafana-overview" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-k8s-resources-workloads-namespace" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-grafana-config-dashboards" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-grafana-datasource" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-grafana" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-k8s-resources-workload" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-namespace-by-pod" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-workload-total" ConfigMap
client.go:299: [debug] Starting delete for "cluster-monitoring-grafana" Secret
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-prometheus" ServiceAccount
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-state-metrics" ServiceAccount
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-operator" ServiceAccount
client.go:299: [debug] Starting delete for "cluster-monitoring-grafana" ServiceAccount
client.go:299: [debug] Starting delete for "cluster-monitoring-prometheus-node-exporter" ServiceAccount
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-admission" MutatingWebhookConfiguration
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-prometheus" Prometheus
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kube-apiserver-slos" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-prometheus" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kube-prometheus-general.rules" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kubernetes-system-kube-proxy" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-alertmanager.rules" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-k8s.rules" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kube-apiserver-burnrate.rules" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kube-prometheus-node-recording.rules" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kubernetes-system" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kube-apiserver-histogram.rules" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kube-scheduler.rules" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kubelet.rules" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-node-exporter.rules" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kube-apiserver-availability.rules" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-prometheus-operator" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kubernetes-system-controller-manager" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-general.rules" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kubernetes-resources" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kubernetes-system-apiserver" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kube-state-metrics" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-node-network" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-etcd" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-node.rules" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kubernetes-system-kubelet" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kubernetes-system-scheduler" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-config-reloaders" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kubernetes-apps" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kubernetes-storage" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-node-exporter" PrometheusRule
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kube-scheduler" ServiceMonitor
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-state-metrics" ServiceMonitor
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kubelet" ServiceMonitor
client.go:299: [debug] Starting delete for "cluster-monitoring-prometheus-node-exporter" ServiceMonitor
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-prometheus" ServiceMonitor
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kube-etcd" ServiceMonitor
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kube-proxy" ServiceMonitor
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-coredns" ServiceMonitor
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-apiserver" ServiceMonitor
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-kube-controller-manager" ServiceMonitor
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-operator" ServiceMonitor
client.go:299: [debug] Starting delete for "cluster-monitoring-grafana" ServiceMonitor
client.go:299: [debug] Starting delete for "cluster-monitoring-kube-pr-admission" ValidatingWebhookConfiguration
uninstall.go:144: [debug] purge requested for cluster-monitoring
release "cluster-monitoring" uninstalled
```
Is this expected or should the PVC also be getting cleaned up?

### What you expected to happen?

I'd expect that all the resources would be removed, including the defined PVC.

### How to reproduce it?

Deploy the chart using local storage with a volume claim template pointed to an externally created PV. Uninstall the chart and the PVC created during installation will remain.

### Enter the changed values of values.yaml?

```yaml
kube-prometheus-stack:
  alertmanager:
    enabled: false

  grafana:
    envFromConfigMaps:
      - name: grafana-config
        optional: false

  prometheus:
    prometheusSpec:
      scrapeInterval: "30s"
      retention: 30d
      retentionSize: 15GB
          
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-storage
            accessModes: ["ReadWriteOnce"]
            selector:
              matchLabels:
                type: cluster-monitoring
                application: prometheus
            resources:
              requests:
                storage: 20Gi

  kubeControllerManager:
    ## If using kubeControllerManager.endpoints only the port and targetPort are used
    ##
    service:
      enabled: false
      ## If null or unset, the value is determined dynamically based on target Kubernetes version due to change
      ## of default port in Kubernetes 1.22.
      ##
      port: null
      targetPort: null
      selector:
        component: kube-controller-manager

  kubeScheduler:
    enabled: true

    ## If using kubeScheduler.endpoints only the port and targetPort are used
    ##
    service:
      enabled: false
      ## If null or unset, the value is determined dynamically based on target Kubernetes version due to change
      ## of default port in Kubernetes 1.23.
      ##
      port: null
      targetPort: null
      selector:
        component: kube-scheduler
```

### Enter the command that you execute and failing/misfunctioning.

`helm install -n prometheus cluster-monitoring myrepo/top-level-chart --set hostname=hostname`

`helm uninstall -n prometheus cluster-monitoring

### Anything else we need to know?

`kube-prometheus-stack` is a dependency of an internal chart. The top-level chart only defines an ingress and the PV.
