### ISSUE TITLE
[kube-prometheus-stack] Allow specifying Additional Labels per Alert 

### ISSUE THREAD

**Issue by Daniel-Vaz** [prometheus-community/helm-charts#3014]
### Is your feature request related to a problem ?

**Issue:**

Currently we only are able to add additional labels to the default rules using the `defaultRules.additionalRuleLabels` value. This Value is applied to every single Alert under `helm-charts/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/`.

In our setup we heavily rely on a `instance` label that identifies the target in the alert receivers like Slack, PagerDuty, etc. 

Since each alert addresses different objects\targets, and we want to set the `instance` label to identify those targets, we can't do that by adding a common `defaultRules.additionalRuleLabels` value since the labels will change depending on the alerts expressions of course. 

For example: 

- Setting `instance: '{{ $labels.namespace }}/{{ $labels.deployment }}'` will correctly identify the alerts that have the "namespace" and "deployment" labels, but for example alerts regarding cronjobs or even statefullsets would break and\or appear empty. 

### Describe the solution you'd like.

We would need to have the possibility to edit **Per Alert** the `additionalRuleLabels` value so that we can have a more fine-grained Control on what labels we add to what alerts. 

Something similar to the following values.yaml structure:

```yaml
  defaultRules:
    create: true
    rules:
      alertmanager:
        AlertmanagerFailedReload:
          enabled: true
          additionalRuleLabels: {}
          additionalRuleAnnotations: {}
        AlertmanagerMembersInconsistent:
          enabled: true
          additionalRuleLabels: {}
          additionalRuleAnnotations: {}
# (etc...)
```

### Describe alternatives you've considered.

Alternative we can just disable all default rules and manage them ourselves but this would defeat the purpose of using the kube-prometheus-stack for getting automatically community approved patches, recommendations and updates. 

### Additional context.

We currently are migrating from a "legacy" Prom\Alertman\Grafana stack to Kube-Prometheus-stack and this changes to the overall helm templates really would make a difference in this migration.
