### ISSUE TITLE
[prometheus-kube-stack] Default Thanos Ruler name too long

### ISSUE THREAD

**Issue by ryanmcafee** [prometheus-community/helm-charts#3020]
### Describe the bug a clear and concise description of what the bug is.

When deploying the Thanos Ruler with default values, the generated name for volumes attached to pods is too long, blocking it (more than 63 chars).

It creates a volume named thanos-ruler-<release_name>-kube-prometheus-stack-thanos-ruler-rulefiles-0, and then I get this error:

$ kubectl get events
[29s         Warning   FailedCreate       statefulset/thanos-ruler-prom-o11y-kube-prometheus-stack-thanos-ruler   create Pod thanos-ruler-prom-o11y-kube-prometheus-stack-thanos-ruler-0 in StatefulSet thanos-ruler-prom-o11y-kube-prometheus-stack-thanos-ruler failed error: Pod "thanos-ruler-prom-o11y-kube-prometheus-stack-thanos-ruler-0" is invalid: [spec.volumes[0].name: Invalid value: "thanos-ruler-prom-o11y-kube-prometheus-stack-thanos-ruler-rulefiles-0": must be no more than 63 characters, spec.containers[0].volumeMounts[1].name: Not found: "thanos-ruler-prom-o11y-kube-prometheus-stack-thanos-ruler-rulefiles-0", spec.containers[1].volumeMounts[0].name: Not found: "thanos-ruler-prom-o11y-kube-prometheus-stack-thanos-ruler-rulefiles-0"]]`](url)
The name can be less than 63 characters if the release name is "only" 2 chars long, which is a little bit short ;)

### What's your helm version?

version.BuildInfo{Version:"v3.11.0", GitCommit:"472c5736ab01133de504a826bd9ee12cbe4e7904", GitTreeState:"clean", GoVersion:"go1.19.5"}

### What's your kubectl version?

Client Version: v1.26.1 Kustomize Version: v4.5.7 Server Version: v1.22.16-eks-ffeb93d

### Which chart?

prometheus-kube-stack

### What's the chart version?

45.0.0

### What happened?

Enable the thanosRuler in custom values.

### What you expected to happen?

Thanos Ruler pod shoud be created

### How to reproduce it?

Enable Thanos Ruler

### Enter the changed values of values.yaml?

```
thanosRuler:
  enabled: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: ${iam_role_arn}
  podDisruptionBudget:
    enabled: true
    minAvailable: ""
    maxUnavailable: 2
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
    # Run thanos-ruler in high availability clustered mode
    replicas: 3
    # Thanos s3 config that allows it to access thanos data
    objectStorageConfig:
      name: ${s3_config_secret_name}
      key: ${s3_config_secret_key}
    # External labels needed to deduplicate alerts on
    labels:
      cluster: ${cluster_name}
      environment: ${environment}
      region: ${region}
```
The above is interpolated with terraform templatefile and passed to helm_release.

### Enter the command that you execute and failing/misfunctioning.

helm install prom-o11y prometheus-community/kube-prometheus-stack -f custom-values.yaml --version 45.0.0

### Anything else we need to know?

Related to closed issue: https://github.com/prometheus-community/helm-charts/issues/2408
