### ISSUE TITLE
[prometheus-redis-exporter] did you support aws-elasticache(redis)?

### ISSUE THREAD

**Issue by xyfleet** [prometheus-community/helm-charts#3024]
### Describe the bug a clear and concise description of what the bug is.

Tried to use this chart to monitor my elasticache-redis on aws, but got error message:

`time="2023-02-10T19:38:06Z" level=error msg="Couldn't connect to redis instance (redis://xxx.xxx.xxx.xxx.cache.amazonaws.com:6379)"`

my redis cluster
Encryption at rest: Enabled
I can connect to my redis through redis-cli -h xxx.xxx.xxx.xxx.cache.amazonaws.com:6379 --tls -a yyy -p 6379. But the redis exporter pod cannot connect to it. Not sure why. 
So, I have some config below, any suggestion will be appreciated. 

```
redisAddress: redis://xxx.xxx.xxx.xxx.cache.amazonaws.com:6379

redisTlsConfig:
  # Use TLS configuration
  enabled: true
  # Whether to to skip TLS verification
  skipTlsVerification: true

auth:
  enabled: true
  redisPassword: xxxxxxx
```

In the servicemonitor section, do I need to add targets again, since I have setup the redisAddress?

### What's your helm version?

v3.6.3

### What's your kubectl version?

v1.22.0

### Which chart?

prometheus-redis-exporter

### What's the chart version?

5.3.0

### Enter the command that you execute and failing/misfunctioning.

through terraform helm_release resource
