### ISSUE TITLE
Follow up of #2424 [prometheus-kube-stack] Configuring additional datasources does not trigger redeployment of Grafana

### ISSUE THREAD

**Issue by aek-arm** [prometheus-community/helm-charts#3029]
### Describe the bug a clear and concise description of what the bug is.

As per https://github.com/prometheus-community/helm-charts/issues/2424#issuecomment-1293513922 this is still open.

Configuring additional datasources in the values.yaml, updates the ConfigMap kube-prometheus-grafana-datasource correctly, but does not trigger redeployment of the grafana pod, one needs to manually restart for changes to take effect.

values.yaml

```
  grafana:
    additionalDataSources:        
      - name: Logging
        type: loki
        access: proxy
        url: http://logging-loki-loki-distributed-gateway.logging
```

the content generated config map, kube-prometheus-grafana-datasource:

```
apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  url: http://prometheus-kube-prometheus-prometheus.monitoring:9090/
  access: proxy
  isDefault: true
  jsonData:
    timeInterval: 30s
- access: proxy
  name: Logging
  type: loki
  url: http://logging-loki-loki-distributed-gateway.logging
```

The reason for this is because this ConfigMap is not included in the checksum annotations of the grafana pod.

```
apiVersion: v1
kind: Pod
metadata:
  name: prometheus-grafana-564cf6bd9f-fx6jh
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  annotations:
    checksum/config: <checksum>
    checksum/dashboards-json-config: <checksum>
    checksum/sc-dashboard-provider-config: <checksum>
    checksum/secret: <checksum>
```

Is there a possibility to include the checksum of kube-prometheus-grafana-datasource?

### What's your helm version?

v3.9.1

### What's your kubectl version?

v1.22.17

### Which chart?

prometheus-kube-stack

### What's the chart version?

39.11.0

### Enter the command that you execute and failing/misfunctioning.

the deployment is triggered by flux2

**Comment by aek-arm** [comment]
Hi @zeritti - Thanks for the feedback and the detailed explanation. As we use https on Grafana we'll then have to look for a solution to manually restart.

**Comment by brandonros** [comment]
I'm not so sure if this should be closed, if what I ran into is similar

ArgoCD representation of the config map:

![image](https://github.com/prometheus-community/helm-charts/assets/8949910/91117675-80c4-427f-ae91-a03d313a90c4)

The sources not "coming over" into Grafana on a clean install:

![image](https://github.com/prometheus-community/helm-charts/assets/8949910/4588c2bb-b033-4ebb-8e68-72cc2b882f2a)

```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: monitoring
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: kube-prometheus-stack
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: main
    path: ./charts/kube-prometheus-stack
    helm:
      values: |
        grafana:
          additionalDataSources:
            - name: loki
              type: loki
              url: http://loki-stack.monitoring.svc:3100
            - name: jaeger
              type: jaeger
              url: http://jaeger-jaeger-all-in-one.jaeger.svc:16686
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
```

Do I have something wrong or is there a bug that prevents additionalDataSources -> `kube-prometheus-stack-grafana-datasource` ConfigMap from actually wiring itself up 1:1 with what `GET http://kube-prometheus-stack-grafana.monitoring/api/datasources` returns?
