### ISSUE TITLE
[prometheus-kube-stack] Service Monitor {} is not working as intended

### ISSUE THREAD

**Issue by rufreakde** [prometheus-community/helm-charts#3030]
### Describe the bug a clear and concise description of what the bug is.

# Solution:

So the issue is that in version `44.4.1` of the operator chart the `{}`is not used correctly for the `serviceMeshSelector`!

To fix this I just set it explicitly! This seems to be a bug. As it should work as mentioned here: https://github.com/prometheus-operator/prometheus-operator/issues/731#issuecomment-371412289 
```
        prometheus:
          prometheusSpec:
            serviceMonitorNamespaceSelector: {}
            serviceMonitorSelector:
              matchExpressions:
                - {key: app, operator: Exists}

```

### What's your helm version?

N/A

### What's your kubectl version?

Not related

### Which chart?

prometheus-kube-stack

### What's the chart version?

44.4.1

### What happened?

Service Monitor Discovery for „all“ {} is not working

### What you expected to happen?

ServiceMonitor gets found

### How to reproduce it?

Just install chart without configuring the selector 

### Enter the changed values of values.yaml?

N/A

### Enter the command that you execute and failing/misfunctioning.

N/A

### Anything else we need to know?

Had an Issue open here https://github.com/prometheus-operator/prometheus-operator/issues/5332#issuecomment-1428267709

But it seems to be more related to the chart itself?
