### ISSUE TITLE
[prometheus] How do I customize alertmanager.yml in v19.5.0

### ISSUE THREAD

**Issue by lz000** [prometheus-community/helm-charts#3034]
I'm upgrading the prometheus chart from 15.3.0 to 19.5.0. There used to be a `alertmanagerFiles` block with `alertmanager.yml` allowing me to deploy a custom alertmanager.yml so I can add slack receiver. In the 19.5.0 default values I don't see this block, and I don't see a way to customize alertmanager.yml. I tried adding
```
  alertmanagerFiles:
    alertmanager.yml:
       ...
```
But this does not work. I checked the alertmanager pod, here is the content of the alertmanager.yml

```
global: {}
receivers:
- name: default-receiver
route:
  group_interval: 5m
  group_wait: 10s
  receiver: default-receiver
  repeat_interval: 3h
templates:
- /etc/alertmanager/*.tmpl
```

Any idea?

**Comment by leoslf** [comment]
Sorry to comment on a closed issue.

[TL;DR] For those who encountered this configuring alertmanager, in general helm would pass the entry with **the subchart's name** (`alertmanager` in this case, please refer to `Chart.yaml` for the chart dependencies) in your `values.yaml` to the subchart

For example,
```yaml
alertmanager:
  extraSecretMounts:
    # - name: telegram
    #   mountPath: /etc/secrets/telegram
    #   subPath: ""
    #   secretName: telegram
    #   readOnly: true
    - name: email
      mountPath: /etc/secrets/email
      subPath: ""
      secretName: email
      readOnly: true

  config:
    global:
       # The default SMTP From header field.
       smtp_from: Prometheus <sysadmin@{{ .Values.jxRequirements.ingress.domain }}>
       smtp_smarthost: smtp.{{ .Values.jxRequirements.ingress.domain }}:465
       smtp_hello: {{ .Values.jxRequirements.ingress.domain }}
       smtp_auth_username: sysadmin@{{ .Values.jxRequirements.ingress.domain }}
       smtp_auth_password_file: /etc/secrets/email/PASSWORD
       smtp_require_tls: true
    route:
      receiver: email-alert
      group_by:
        - namespace
        # - job
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes:
        - receiver: email-alert
          matchers:
            - alertname =~ "InfoInhibitor|Watchdog"
    receivers:
      - name: "null"
      - name: telegram-alert
        telegram_configs:
          sendResolved: false
          botToken: {{ requiredEnv "PROMETHEUS_TELEGRAM_BOT_TOKEN" | quote }}
          chatID: {{ requiredEnv "PROMETHEUS_TELEGRAM_CHAT_ID" | int64 }}
          # (optional) message template
          # message: 
          disableNotifications: false
      - name: email-alert
        emailConfig:
          - to: System Admin <sysadmin@{{ .Values.jxRequirements.ingress.domain }}>
```

Ref: https://helm.sh/docs/chart_template_guide/subcharts_and_globals/
