### ISSUE TITLE
[kube-prometheus-stack] support extraSecret type customization to allow HTTP Basic Authentication for NGINX Inc ingress controller

### ISSUE THREAD

**Issue by hostalp** [prometheus-community/helm-charts#3052]
### Is your feature request related to a problem ?

The NGINX Inc ingress controller (the one directly from the NGINX developers) supports HTTP Basic Authentication with slightly different requirements for the secret (than what the more common NGINX ingress controller from the Kubernetes developers requires).

The secret needs to be of type `nginx.org/htpasswd` (instead of Opaque) and the authentication entries must be present in `data.htpasswd` (instead od data.auth)
See https://github.com/nginxinc/kubernetes-ingress/tree/main/examples/ingress-resources/basic-auth

While it's easy to change the latter, the former can't be currently changed via Helm chart (the extraSecret type is always Opaque), so one has to modify the secret after the Helm chart installation (and because the type field is immutable, the whole secret has to be actually recreated).

Please make it possible to set the type of the extraSecret.

### Describe the solution you'd like.

Example for `prometheus` (but extraSecret can be also specified for `alertmanager` and `hanosRuler`):
```yaml
## Deploy a Prometheus instance
##
prometheus:
  ## ExtraSecret can be used to store various data in an extra secret
  ## (use it for example to store hashed basic auth credentials)
  extraSecret:
    data:
      # htpasswd -nbB user password
      htpasswd: |
        user:$2y$05$wbdg4wHEwDd00xQEEP8hMOyJOFcoTXoi.9hOJmncEgLmiGPoxRXRO
    type: nginx.org/htpasswd
```

### Describe alternatives you've considered.

Workaround to recreate the secret with the correct type:
```sh
kubectl get secret -n monitoring prometheus-kube-prometheus-stack-extra -o yaml > prometheus-kube-prometheus-stack-extra-secret.yaml
sed -i 's/^type: Opaque&/type: nginx.org\/htpasswd/g' prometheus-kube-prometheus-stack-extra-secret.yaml
kubectl delete secret -n monitoring prometheus-kube-prometheus-stack-extra
kubectl apply -n monitoring -f prometheus-kube-prometheus-stack-extra-secret.yaml
rm -f prometheus-kube-prometheus-stack-extra-secret.yaml
```
