### ISSUE TITLE
Some of the basic dashboards not working right

### ISSUE THREAD

**Issue by XDavidT** [prometheus-community/helm-charts#3058]
### Describe the bug a clear and concise description of what the bug is.

Screenshots: https://tinyurl.com/2exxpskb https://tinyurl.com/2qdrsk5b https://tinyurl.com/2hfq6zrl 
Networking: https://tinyurl.com/2otnavgt
In this example, we not even see namespaces: https://tinyurl.com/2pbekvbz
I've used a screenshot cause it's the best easy what to use it
Where to start? what components to check? or query?

### What's your helm version?

v3.11.1

### What's your kubectl version?

Client v1.25.0 Server v1.24.9

### Which chart?

kube-prometheus-stack

### What's the chart version?

45.2.0

### What happened?

I've tried to look at some of the basic dashboards to investigate the usage of my new Jenkins and found that most of the dashboard doesn't provide information.

### Enter the changed values of values.yaml?

```
kube-prometheus-stack:
  prometheus:
    service:
      type: NodePort
      nodePort: 30090
    prometheusSpec:
      additionalScrapeConfigs:
      - job_name: nexus
        scrape_interval: 30s
        static_configs:
          - targets: [ "nexus.local:8081" ]
        metrics_path: /service/metrics/prometheus
        basic_auth:
          username: metrics
          password: metrics
      - job_name: postgresql
        scrape_interval: 10s
        static_configs:
          - targets: ["pg.local:9187"]
      - job_name: netapp
        scrape_interval: 10s
        static_configs:
          - targets: ["poller-cluster-01:13000"]
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: netapp-storage
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
  grafana:
    service:
      type: NodePort
      nodePort: 30091
    persistence:
      existingClaim: kube-prometheus-stack-netapp-pvc
    additionalDataSources:
     - name: Prometheus-cnvrg
       basicAuth: true
       basicAuthPassword: *********
       basicAuthUser: user
       jsonData:
           tlsSkipVerify: true
       orgId: 1
       type: prometheus
       url: http://host.local:32216/

```

### Enter the command that you execute and failing/misfunctioning.

None

### Anything else we need to know?
I have 2 Prometheus sources (1 old from another system added to Grafana manauly, and one new that came with kube-prom-stack), and now I've checked dashboard: `kubernetes-compute-resources-node-pods`, and saw CPU metric looks for `sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster="$cluster", node=~"$node"}) by (pod)`, on the explorer page I've looked for `node_namespace_pod_container` but didn't find it their, only from old promethues, but this metric not available for the new one.

Is there any chance metric are updated, but dashboards aren't?

**Comment by yashiang1986** [comment]
I have the same issue.
My k8s version is 1.25.6 and helm-chart is 45.2.0.

**Comment by zeritti** [comment]
You are specifically mentioning `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate`. This is a recording defined in `k8s.rules.yaml` including the metric
`container_cpu_usage_seconds_total` produced by job `kubelet` and endpoint `/metrics/cadvisor`. 

If you cannot see any time series of this metric/endpoint in Grafana or Prometheus UI, Prometheus has likely not discovered/scraped that specific kubelet endpoint. The Status/Targets page in Prometheus UI shows info on discovered targets. 

BTW The corresponding service monitors get created through
```
kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    cAdvisor: true
```
and the service through
```
prometheusOperator:
  kubeletService:
    enabled: true
    namespace: kube-system
```
Both are enabled by default.
