### ISSUE TITLE
[kube-prometheus-stack] Add security context CAP_NET_RAW

### ISSUE THREAD

**Issue by jascsch** [prometheus-community/helm-charts#3063]
### Is your feature request related to a problem ?

We need to add the following security context to all containers even initContainer of the kube-prometheus-stack helm chart.
securityContext:
  capabilities:
    drop:
      - CAP_NET_RAW

Unfortunately the values.yaml of the helm chart does not give the possibility to do this.

### Describe the solution you'd like.

Please add the settings to the values.yaml which allows the CAP_NET_RAW security context to all containers/initContainer.

### Describe alternatives you've considered.

There is no other workaround.

**Comment by zeritti** [comment]
> Unfortunately the values.yaml of the helm chart does not give the possibility to do this.

In some cases, indeed, it does not:
- With respect to the `alertmanagers`, `prometheuses` and `thanosrulers` CRDs, these, and hence Prometheus Operator, do not currently support container security context, only [pod security context](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#podsecuritycontext-v1-core) through e.g. `prometheus.spec.securityContext`.

  The only way to apply a container-specific security context parameter onto these resources might be through a [patch](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/strategic-merge-patch.md), e.g. on to `prometheus.spec.containers` for Prometheus.

Otherwise, support for container security context is:
- Prometheus operator: present
- Webhook jobs: present
- Dependency charts: kube-state-metrics present, node-exporter present, grafana present, including its sidecars. Please, note that you may have to refer to the charts' values as not all the subcharts' values are listed in the kube-prometheus-stack's values file. You just need to insert the fields in the corresponding subchart's scope.
- As to usual `initContainers[]` and `extraContainers[]`, these are commonly fully in users' control and taken over "as is", i.e. we define them in full. HTH

**Comment by jascsch** [comment]
Thanks for your quick answer.
Unfortunately the container security context [pod security context] through e.g. prometheus.spec.securityContext does not allow to add the capabilities like this:
```
prometheus:
  prometheusSpec:
    securityContext:
      capabilities:
        drop:
          - CAP_NET_RAW
```
This leads to the following error message:
`error validating data: ValidationError(Prometheus.spec.securityContext): unknown field "capabilities" in com.coreos.monitoring.v1.Prometheus.spec.securityContext`

Could you please try to help us here to find a solution?

**Comment by zeritti** [comment]
> This leads to the following error message:

That is correct as Prometheus operator knows that the field is invalid in that context. One cannot use the values in this way.

For this case my comment above on patching was meant. One can eventually patch the prometheus resource through `prometheus.spec.containers`. 

With the chart, though, you should be able to use the values file like this:
```
prometheus:
  prometheusSpec:
    containers:
    - name: prometheus
      securityContext:
        capabilities:
          drop:
          - NET_RAW
```
> Containers allows injecting additional containers or modifying operator generated containers. This can be used to allow adding an authentication proxy to a Prometheus pod or to change the behavior of an operator generated container. Containers described here modify an operator generated container if they share the same name and modifications are done via a strategic merge patch. The current container names are: prometheus, config-reloader, and thanos-sidecar. Overriding containers is entirely outside the scope of what the maintainers will support and by doing so, you accept that this behaviour may break at any time without notice.

One can also verify the behaviour manually in a test. If I have a `prometheus` resource named `kube-prometheus-stack-prometheus` in namespace `monitoring`, I can patch the prometheus container introducing the capabilities with this manifest:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: self
  name: kube-prometheus-stack-prometheus
  namespace: monitoring
spec:
  containers:
  - name: prometheus
    securityContext:
      capabilities:
        drop:
        - NET_RAW
```
Stored in file `patch.yaml`, I apply the patch:
```
$ kubectl apply -f patch.yaml
```

Checking the result, I see that the patch was applied on to the resource:
```
$ kubectl get prometheus kube-prometheus-stack-prometheus \
  -o jsonpath='{.spec.containers[]}' \
  | jq ''
{
  "name": "prometheus",
  "securityContext": {
    "capabilities": {
      "drop": [
        "NET_RAW"
      ]
    }
  }
}
```
and the container itself:
```
$ kubectl get po prometheus-kube-prometheus-stack-prometheus-0 \
  -o jsonpath='{.spec.containers[0].securityContext}' \
  | jq ''
{
  "allowPrivilegeEscalation": false,
  "capabilities": {
    "drop": [
      "NET_RAW"
    ]
  },
  "readOnlyRootFilesystem": true
}
```
