### ISSUE TITLE
[prometheus-cloudwatch-exporter] rule is not working as expected

### ISSUE THREAD

**Issue by xyfleet** [prometheus-community/helm-charts#3068]
### Describe the bug a clear and concise description of what the bug is.

Configured the cloudwatch exporter with this setting:
```
serviceMonitor:
  enabled: true

config: |-
  # This is the default configuration for prometheus-cloudwatch-exporter
  region: "us-east-1"
  period_seconds: 300
  metrics:
  - aws_namespace: AWS/SQS
    aws_metric_name: ApproximateNumberOfMessagesVisible
    aws_dimensions: [QueueName]
    aws_statistics: [Average]

prometheusRule:
  enabled: true
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
  rules:
     - alert: ApproximateNumberOfMessagesVisible
       expr: aws_sqs_approximate_number_of_messages_visible_average{queue_name="abc-queue"} > 10
       for: 10m
       labels:
         severity: warning
       annotations:
         description: The number of messages available for retrieval from the queue
         summary: The number of messages in the queue, abc-queue, is > 10
```
From :9106/metrics, I can see the metrics. But in the Prometheus webpage, I cannot see the value when I query it in the Table tab. If you click the Graph tab, you can get what you want.  
![Screenshot2023_02_23_171209](https://user-images.githubusercontent.com/113627389/221070615-a8001b02-32d3-4523-9a91-8ba0f2f2f06c.jpg)

Why cann't I get the value from Table. As a result, my rule cannot be triggered here. 

### What's your helm version?

v3.6.3

### What's your kubectl version?

1.22

### Which chart?

prometheus-cloudwatch-exporter

### What's the chart version?

0.24.0

### Enter the command that you execute and failing/misfunctioning.

```
aws_sqs_approximate_number_of_messages_visible_average
```
