### ISSUE TITLE
labeldrop is not working on label "id" for container metrics

### ISSUE THREAD

**Issue by kimcagayat** [prometheus-community/helm-charts#3082]
labeldrop is not working on label "id" for container metrics

<html>
<body>

**container_cpu_usage_seconds_total**{cluster="cl1-esop-prod", clusterName="cl1-esop", cluster_type="openshift", clustertype="openshift", container="POD", cpu="total", endpoint="https-metrics", **id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod014f1ae0_2134_4c56_8754_185b611a42d7.slice/crio-1575f6eefbd4ad663da3b2b2ec604c255a9024f520d4e117c70069adedad6725.scope"**, inc="servicenow", instance="172.23.152.143:10250", job="kubelet", metrics_path="/metrics/cadvisor", name="k8s_POD_multus-additional-cni-plugins-fm5bx_openshift-multus_014f1ae0-2134-4c56-8754-185b611a42d7_0", namespace="openshift-multus", node="cl1-esop-ocp-worker-prod-vm-9", pod="multus-additional-cni-plugins-fm5bx", prometheus="openshift-monitoring/k8s", prometheus_replica="prometheus-k8s-0", region="westus", service="kubelet", serviceCI="Openshift Container Platform (ESOP)", snowprod="prod"}
--

<br class="Apple-interchange-newline">
</body>
</html>

This is the job that we are using:
    - job_name: 'kubelet'
      metrics_path: /metrics/cadvisor
      metric_relabel_configs:
      - action: labeldrop
        regex: id

**Comment by darioef** [comment]
Please try this. It's working for me:

```
kubelet:
  serviceMonitor:
    cAdvisorMetricRelabelings:
      - sourceLabels: [__name__]
        action: drop
        regex: 'container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)'
      # Drop less useful container / always zero filesystem metrics.
      - sourceLabels: [__name__]
        action: drop
        regex: 'container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)'
      # Drop less useful / always zero container memory metrics.
      - sourceLabels: [__name__]
        action: drop
        regex: 'container_memory_(mapped_file|swap)'
      # Drop less useful container process metrics.
      - sourceLabels: [__name__]
        action: drop
        regex: 'container_(file_descriptors|tasks_state|threads_max)'
      # Drop container spec metrics that overlap with kube-state-metrics.
      - sourceLabels: [__name__]
        action: drop
        regex: 'container_spec.*'
      # Drop cgroup metrics with no pod.
      - sourceLabels: [id, pod]
        action: drop
        regex: '.+;'
      # Drop id label from all metrics
      - action: labeldrop
        regex: 'id'
```

The first lines refer to the default lines in the values.yaml file. However, we need to add the labeldrop for the "id" label, which cannot be merged with the default lines. Therefore, you will need to write both the default lines again and the new labeldrop block.

**Comment by kimcagayat** [comment]
Thanks Dario. Do you mean something like this?

kubelet:
  serviceMonitor:
    cAdvisorMetricRelabelings:
      # Drop cgroup metrics with no pod.
      - sourceLabels: [id, pod]
        action: drop
        regex: '.+;'
      # Drop id label from all metrics
      - action: labeldrop
        regex: 'id'

**Comment by kimcagayat** [comment]
I tried to add but having this error though. 

      Message:   ts=2023-03-07T12:02:11.503Z caller=main.go:450 level=error msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: found multiple scrape configs with job name \"serviceMonitor/espr-prometheus-nonprod/prometheus-kube-prometheus-kubelet/0\""

**Comment by zeritti** [comment]
I can confirm the following works (KPS 45.2.0, no other custom metric relabelings in place for cadvisor, for context)
```
cAdvisorMetricRelabelings:
- regex: ^id$
  action: labeldrop
```

**Comment by darioef** [comment]
> I can confirm the following works (KPS 45.2.0, no other custom metric relabelings in place for cadvisor, for context)
> 
> ```
> cAdvisorMetricRelabelings:
> - regex: ^id$
>   action: labeldrop
> ```

But I think you are droping the defaults relabels included in the default values.yaml since Helm don't merge the default values with the relabels you provided (only in that context but yes for different keys).

Take a look to: https://github.com/prometheus-community/helm-charts/blob/ae45be4faa5b000c44d0d93a8e3593837b494180/charts/kube-prometheus-stack/values.yaml#L1060

Check the result of your deploy with "helm template" and look the result of the render. You'll find that the defaults will be missed and only the values you provided will be rendered.

**Comment by kimcagayat** [comment]
How do I add the the job_name on the yaml file?

**Comment by kimcagayat** [comment]
Tried adding cAdvisorMetricRelabelings but it's not working from me.

Here's the content of my yaml file:

    - job_name: 'kubelet'
      metrics_path: /metrics/cadvisor
        :
      - action: labeldrop
        regex: ^id$ 

and here's the error:

    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   ts=2023-03-08T00:36:35.434Z caller=main.go:450 level=error msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: yaml: unmarshal errors:\n  line 2661: field cAdvisorMetricRelabelings not found in type config.ScrapeConfig"

**Comment by kimcagayat** [comment]
Got below error when I tried:

 Error: UPGRADE FAILED: error validating "": error validating data:
│ [ValidationError(ServiceMonitor.spec.endpoints[1].metricRelabelings[0]):
│ unknown field "source_labels" in
│ com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints.metricRelabelings,
│ ValidationError(ServiceMonitor.spec.endpoints[1].metricRelabelings[1]):
│ unknown field "source_labels" in
│ com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints.metricRelabelings,
│ ValidationError(ServiceMonitor.spec.endpoints[1].metricRelabelings[2]):
│ unknown field "source_labels" in
│ com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints.metricRelabelings,


Here's the additional lines in  yaml:

kubelet:
  serviceMonitor:
    cAdvisorMetricRelabelings:
      - source_labels: [__name__]
        separator: ;
        regex: container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)
        replacement: $1
        action: drop
      - source_labels: [__name__]
        separator: ;
        regex: container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)
        replacement: $1
        action: drop
      - source_labels: [__name__]
        separator: ;
        regex: container_memory_(mapped_file|swap)
        replacement: $1
        action: drop
      - source_labels: [__name__]
        separator: ;
        regex: container_(file_descriptors|tasks_state|threads_max)
        replacement: $1
        action: drop
      - source_labels: [__name__]
        separator: ;
        regex: container_spec.*
        replacement: $1
        action: drop
      - source_labels: [id, pod]
        separator: ;
        regex: .+;
        replacement: $1
        action: drop
      # Drop id label from all metrics
      - action: labeldrop
        regex: 'id'

**Comment by kimcagayat** [comment]
Tried to ad it using "kubectl edit servicmobitors <name>"

- job_name: serviceMonitor/espr-prometheus-nonprod/prometheus-kube-prometheus-kubelet/1
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics/cadvisor
  scheme: https
  authorization:
    type: Bearer
    credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [job]
    separator: ;
    regex: (.*)
    target_label: __tmp_prometheus_job_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name, __meta_kubernetes_service_labelpresent_app_kubernetes_io_name]
    separator: ;
    regex: (kubelet);true
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_service_label_k8s_app, __meta_kubernetes_service_labelpresent_k8s_app]
    separator: ;
    regex: (kubelet);true
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: https-metrics
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Node;(.*)
    target_label: node
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Pod;(.*)
    target_label: pod
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: (.*)
    target_label: container
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_phase]
    separator: ;
    regex: (Failed|Succeeded)
    replacement: $1
    action: drop
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_label_k8s_app]
    separator: ;
    regex: (.+)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: https-metrics
    action: replace
  - source_labels: [__metrics_path__]
    separator: ;
    regex: (.*)
    target_label: metrics_path
    replacement: $1
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    modulus: 1
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: "0"
    replacement: $1
    action: keep
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: container_memory_(mapped_file|swap)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: container_(file_descriptors|tasks_state|threads_max)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: container_spec.*
    replacement: $1
    action: drop
  - source_labels: [id, pod]
    separator: ;
    regex: .+;
    replacement: $1
    action: drop
  - separator: ;
    regex: ^id$
    replacement: $1
    action: labeldrop
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
    namespaces:
      own_namespace: false
      names:
      - kube-system




It was added but still the container_* metric ids are still existing:

![image](https://user-images.githubusercontent.com/96174080/226517182-76ec87c7-9db3-4fb1-a6a0-f7e55a9cb122.png)

**Comment by alt-dima** [comment]
Strange, for me works fine
```
kubelet:
  enabled: true
  serviceMonitor:
    cAdvisorMetricRelabelings:
      # Drop less useful container CPU metrics.
      - sourceLabels: [__name__]
        action: drop
        regex: 'container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)'
      # Drop less useful container / always zero filesystem metrics.
      - sourceLabels: [__name__]
        action: drop
        regex: 'container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)'
      # Drop less useful / always zero container memory metrics.
      - sourceLabels: [__name__]
        action: drop
        regex: 'container_memory_(mapped_file|swap)'
      # Drop less useful container process metrics.
      - sourceLabels: [__name__]
        action: drop
        regex: 'container_(file_descriptors|tasks_state|threads_max)'
      # Drop container spec metrics that overlap with kube-state-metrics.
      - sourceLabels: [__name__]
        action: drop
        regex: 'container_spec.*'
      # Drop cgroup metrics with no pod.
      - sourceLabels: [id, pod]
        action: drop
        regex: '.+;'
      - action: labeldrop
        regex: id
```
