### ISSUE TITLE
 [kube-prometheus-stack] Chart installation failed with ArgoCD

### ISSUE THREAD

**Issue by chewdevs** [prometheus-community/helm-charts#3122]
### Describe the bug a clear and concise description of what the bug is.

I'm trying to install the kube-prometheus-stack helm chart with ArgoCD from fresh but I got this error 

`error validating data: ValidationError(ServiceMonitor.spec.endpoints[0]): unknown field "enableHttp2" in com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints`

I tried to upgrade the CRDs as described in #2633 and like this installation finished. But if I update the release with Argo with new values, it failed with the same error. To fix that, I have to re-apply again the CRDs manually.

I checked the description of `servicemonitors.monitoring.coreos.com`. Just after the manual apply of CRDs, the `enableHttp2` field is defined in the CRD. But after ArgoCD has finished the installation or the update of the chart, this field is no longer present in the CRD.

### What's your helm version?

version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}

### What's your kubectl version?

v1.24.9

### Which chart?

kube-prometheus-stack]

### What's the chart version?

45.7.1

### What happened?

Got the error 

`error validating data: ValidationError(ServiceMonitor.spec.endpoints[0]): unknown field "enableHttp2" in com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints`

### What you expected to happen?

Installation or update the chart to be successful 

### How to reproduce it?

Create this ArgoCD application
```apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: kube-prometheus-stack
      skipCrds: true
      valueFiles:
      - dev/values.yaml
    path: k8s-argocd/infrastructure/kube-prometheus-stack
    repoURL: https://gitlab.com/#####
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
```

Create this `Chart.yaml` file in the repo watched by Argo:
```
apiVersion: v2
name: apache
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: kube-prometheus-stack
  version: 45.7.1
  repository: https://prometheus-community.github.io/helm-charts
```

`values.yaml` file:
```
kube-prometheus-stack:
  prometheusOperator:
    admissionWebhooks:
      annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
      patch:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
```

### Enter the changed values of values.yaml?

```
prometheusOperator:
    admissionWebhooks:
      annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
      patch:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
```

### Enter the command that you execute and failing/misfunctioning.

Run ArgoCD

**Comment by martinrw** [comment]
are you definitely using the latest Schemas? - this should have been fixed here - https://github.com/datreeio/CRDs-catalog/pull/107/files

**Comment by epikichi** [comment]
I experienced this behavior after installing the Loki Helm chart at v4.8.0. 

After looking into it a bit more, the Loki chart on my target revision depends on the [grafana-agent-operator](https://github.com/grafana/helm-charts/blob/grafana-agent-operator-0.2.3/charts/agent-operator/crds/monitoring.coreos.com_servicemonitors.yaml) chart on `0.2.3`, which has not introduced enableHTTP2` field to the SerrviceMonitor CRD schema.

ArgoCD seems to be validating the schema off this CRD rather than the one the one installed via `kube-prometheus-stack`.

The validation error went away after resolving the CRD conflict (disabling grafana-agent in Loki). Alternatively, [disabling schema validation](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#disable-kubectl-validation) in the sync options might help get around it until the source charts update the dependencies.

**Comment by anthonyalayo** [comment]
I encountered the same issue, and disabling the grafana-agent in Loki was a little more complicated than described above.

This is what I had to configure:
```
  test:
    enabled: false
  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
```
