### ISSUE TITLE
[prometheus] Using --set on server.remoteWrite.0.url causes helm template to fail

### ISSUE THREAD

**Issue by dvarga-hi** [prometheus-community/helm-charts#3129]
### Describe the bug a clear and concise description of what the bug is.

When overwriting the `server.remoteWrite.0.url` value with the helm `--set` parameter, an error occurs as described.

### What's your helm version?

v3.11.2

### What's your kubectl version?

v1.26.2

### Which chart?

prometheus

### What's the chart version?

19.7.2

### What happened?

Command `helm template prometheus-community/prometheus -f ./values.yaml --set server.remoteWrite.0.url='https://foobar.com'` fails with output:
```
coalesce.go:223: warning: destination for prometheus.server.remoteWrite is a table. Ignoring non-table value ([])
coalesce.go:223: warning: destination for prometheus.server.remoteWrite is a table. Ignoring non-table value ([])
Error: values don't meet the specifications of the schema(s) in the following chart(s):
prometheus:
- server.remoteWrite: Invalid type. Expected: array, given: object
```

### What you expected to happen?

Generate manifests according to overwritten remote write url eg.:

```yaml
# Source: prometheus/templates/cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: "server"
    app: prometheus
    release: release-name
    chart: prometheus-19.7.2
    heritage: Helm
  name: release-name-prometheus-server
  namespace: default
data:
  prometheus.yml: |
    remote_write:
    - name: mimir
      url: https://foobar.com 
#          ^^^^^^^^^^^^^^^^^^ i want to set this value
[...]
```

### How to reproduce it?

Use values.yaml:
```yaml
server:
  remoteWrite:
    - name: mimir
      url: 'https://foo.com'
```
exec `helm template prometheus-community/prometheus -f ./values.yaml --set server.remoteWrite.0.url='https://foobar.de'`

### Enter the changed values of values.yaml?
```yaml
server:
  remoteWrite:
    - name: mimir
      url: 'https://foo.com'
```

### Enter the command that you execute and failing/misfunctioning.

`helm template prometheus-community/prometheus -f ./values.yaml --set server.remoteWrite.0.url='https://foobar.com'`
