### ISSUE TITLE
[kube-prometheus-stack] Grafana missing label release: prometheus

### ISSUE THREAD

**Issue by bmgante** [prometheus-community/helm-charts#3131]
Hi all,

Just starting with this helm chart and noticed that values.yaml does not include the label "release: prometheus" for grafana servicemonitor, meaning that prometheus will not discover it as serviceMonitorSelector is set to match with that specific label.

```
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: prometheus
```

Thanks

**Comment by gracedo** [comment]
Just an FYI, this has been reported in a past issue https://github.com/prometheus-community/helm-charts/issues/1867 which was closed due to inactivity.

https://github.com/prometheus-community/helm-charts/blob/1f865e4b023d08df6b1f50446b6db4708b150260/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L146-L150
Unfortunately, the label is dynamic based on the release name, so it wouldn't be as easy as setting the labels on the grafana serviceMonitor via values.yaml (by default) since we can't always predict what the release name would be.

If the user instead set the label selector statically in the values file (as in your example above),
```
  serviceMonitorSelector:
    matchLabels:
      release: prometheus
```
I think it would be reasonable then to set the label on grafana's serviceMonitor as well.
```
grafana:
  serviceMonitor:
    labels:
      release: prometheus
```

As for the "default" installation values, since the user is in control of the release name, the only fix right now would be to set that label selecter on grafana's serviceMonitor explicitly.
