### ISSUE TITLE
[kube-prometheus-stack] prometheus pod not starting due to endless WAL recovery loop

### ISSUE THREAD

**Issue by thomas-vt** [prometheus-community/helm-charts#3134]
### Describe the bug a clear and concise description of what the bug is.

Issue is similar to https://github.com/prometheus-operator/prometheus-operator/issues/3391

It's in endless WAL recovery loop and failing on startup probe.

We have tried adding the following to the values.yaml.. but it does not take effect

    livenessProbe:
      failureThreshold: 1000
    readinessProbe:
      failureThreshold: 1000
    startupProbe:
      failureThreshold: 1000

  

### What's your helm version?

v3.11.2

### What's your kubectl version?

v1.25.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

0.57.0

### What happened?

Prometheus pod terminated and is unable to startup

### Enter the command that you execute and failing/misfunctioning.

kubectl -n <namespace> rollout restart statefulset prometheus-kube-prometheus-stack-prometheus

**Comment by xgt001** [comment]
I think you are running into the following issue: https://github.com/prometheus/prometheus/issues/6934
Allocate slightly higher memory for prometheus during the startup by expanding the limits as a workaround. Something around the lines of 

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kube-prometheus-stack-prometheus
spec:
 ...
  resources:
    limits:
      cpu: 3072m
      memory: 18000Mi  <- is dramatically higher to allow it some breathing room, or remove it entirely
    requests:
      cpu: 2048m
      memory: 4096Mi
```
