### ISSUE TITLE
[prometheus-kube-stack] Target Kube-state-metrics shows server returned HTTP status 401 Unauthorized

### ISSUE THREAD

**Issue by Whisper40** [prometheus-community/helm-charts#3143]
### Describe the bug a clear and concise description of what the bug is.

The prometheus target is showing a 401 error for kube-state-metrics

### What's your helm version?

3.10.1

### What's your kubectl version?

v1.21.11

### Which chart?

prometheus-kube-stack

### What's the chart version?

45.7.1

### What happened?

We installed successfully the chart, but "kube-state-metrics" target shows "server returned HTTP status 401 Unauthorized"
All components are enabled, rbac is installed by the helm chart, clean install.

### What you expected to happen?

It should work out of the box :) 

### How to reproduce it?

Deploy (on latest version available) : 
kube-prometheus-stack
prometheus-adapter
prometheus-blackbox-exporter

Go to -> https://prometheus.domain.fr/targets?search=state-metrics
![image](https://user-images.githubusercontent.com/30440458/226872034-f2fb004a-b035-48a0-bdcb-5dc8a0d3b9f8.png)

### Enter the changed values of values.yaml?
```
values:
    defaultRules:
      rules:
        kubeProxy: false
    global:
      rbac:
        pspEnabled: true
      imageRegistry: docker-remote.registry.saas.cagip.group.gca
    alertmanager:
      repository: docker-remote.registry.saas.cagip.group.gca/prometheus/alertmanager
      serviceAccount:
        create: true
      serviceMonitor:
        interval: 30s
      alertmanagerSpec:
        logLevel: error
        replicas: 3
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        podAntiAffinity: hard
        podAntiAffinityTopologyKey: failure-domain.beta.kubernetes.io/zone
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: failure-domain.beta.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app: alertmanager
    grafana:
      enabled: false
    kubeApiServer:
      enabled: true
      tlsConfig:
        serverName: kubernetes
      serviceMonitor:
        interval: 30s
        metricRelabelings:
          - action: labeldrop
            regex: (endpoint|service|namespace|metrics_path)
          - action: drop
            regex: apiserver_storage_envelope_transformation_cache_misses_total
            sourceLabels:
              - __name__
          - action: drop
            regex: kubelet_(pod_worker_latency_microseconds|pod_start_latency_microseconds|cgroup_manager_latency_microseconds|pod_worker_start_latency_microseconds|pleg_relist_latency_microseconds|pleg_relist_interval_microseconds|runtime_operations|runtime_operations_latency_microseconds|runtime_operations_errors|eviction_stats_age_microseconds|device_plugin_registration_count|device_plugin_alloc_latency_microseconds|network_plugin_operations_latency_microseconds)
            sourceLabels:
              - __name__
          - action: drop
            regex: scheduler_(e2e_scheduling_latency_microseconds|scheduling_algorithm_predicate_evaluation|scheduling_algorithm_priority_evaluation|scheduling_algorithm_preemption_evaluation|scheduling_algorithm_latency_microseconds|binding_latency_microseconds|scheduling_latency_seconds)
            sourceLabels:
              - __name__
          - action: drop
            regex: apiserver_(request_count|request_latencies|request_latencies_summary|dropped_requests|storage_data_key_generation_latencies_microseconds|storage_transformation_failures_total|storage_transformation_latencies_microseconds|proxy_tunnel_sync_latency_secs)
            sourceLabels:
              - __name__
          - action: drop
            regex: kubelet_docker_(operations|operations_latency_microseconds|operations_errors|operations_timeout)
            sourceLabels:
              - __name__
          - action: drop
            regex: reflector_(items_per_list|items_per_watch|list_duration_seconds|lists_total|short_watches_total|watch_duration_seconds|watches_total)
            sourceLabels:
              - __name__
          - action: drop
            regex: etcd_(helper_cache_hit_count|helper_cache_miss_count|helper_cache_entry_count|request_cache_get_latencies_summary|request_cache_add_latencies_summary|request_latencies_summary)
            sourceLabels:
              - __name__
          - action: drop
            regex: transformation_(transformation_latencies_microseconds|failures_total)
            sourceLabels:
              - __name__
          - action: drop
            regex: (admission_quota_controller_adds|crd_autoregistration_controller_work_duration|APIServiceOpenAPIAggregationControllerQueue1_adds|AvailableConditionController_retries|crd_openapi_controller_unfinished_work_seconds|APIServiceRegistrationController_retries|admission_quota_controller_longest_running_processor_microseconds|crdEstablishing_longest_running_processor_microseconds|crdEstablishing_unfinished_work_seconds|crd_openapi_controller_adds|crd_autoregistration_controller_retries|crd_finalizer_queue_latency|AvailableConditionController_work_duration|non_structural_schema_condition_controller_depth|crd_autoregistration_controller_unfinished_work_seconds|AvailableConditionController_adds|DiscoveryController_longest_running_processor_microseconds|autoregister_queue_latency|crd_autoregistration_controller_adds|non_structural_schema_condition_controller_work_duration|APIServiceRegistrationController_adds|crd_finalizer_work_duration|crd_naming_condition_controller_unfinished_work_seconds|crd_openapi_controller_longest_running_processor_microseconds|DiscoveryController_adds|crd_autoregistration_controller_longest_running_processor_microseconds|autoregister_unfinished_work_seconds|crd_naming_condition_controller_queue_latency|crd_naming_condition_controller_retries|non_structural_schema_condition_controller_queue_latency|crd_naming_condition_controller_depth|AvailableConditionController_longest_running_processor_microseconds|crdEstablishing_depth|crd_finalizer_longest_running_processor_microseconds|crd_naming_condition_controller_adds|APIServiceOpenAPIAggregationControllerQueue1_longest_running_processor_microseconds|DiscoveryController_queue_latency|DiscoveryController_unfinished_work_seconds|crd_openapi_controller_depth|APIServiceOpenAPIAggregationControllerQueue1_queue_latency|APIServiceOpenAPIAggregationControllerQueue1_unfinished_work_seconds|DiscoveryController_work_duration|autoregister_adds|crd_autoregistration_controller_queue_latency|crd_finalizer_retries|AvailableConditionController_unfinished_work_seconds|autoregister_longest_running_processor_microseconds|non_structural_schema_condition_controller_unfinished_work_seconds|APIServiceOpenAPIAggregationControllerQueue1_depth|AvailableConditionController_depth|DiscoveryController_retries|admission_quota_controller_depth|crdEstablishing_adds|APIServiceOpenAPIAggregationControllerQueue1_retries|crdEstablishing_queue_latency|non_structural_schema_condition_controller_longest_running_processor_microseconds|autoregister_work_duration|crd_openapi_controller_retries|APIServiceRegistrationController_work_duration|crdEstablishing_work_duration|crd_finalizer_adds|crd_finalizer_depth|crd_openapi_controller_queue_latency|APIServiceOpenAPIAggregationControllerQueue1_work_duration|APIServiceRegistrationController_queue_latency|crd_autoregistration_controller_depth|AvailableConditionController_queue_latency|admission_quota_controller_queue_latency|crd_naming_condition_controller_work_duration|crd_openapi_controller_work_duration|DiscoveryController_depth|crd_naming_condition_controller_longest_running_processor_microseconds|APIServiceRegistrationController_depth|APIServiceRegistrationController_longest_running_processor_microseconds|crd_finalizer_unfinished_work_seconds|crdEstablishing_retries|admission_quota_controller_unfinished_work_seconds|non_structural_schema_condition_controller_adds|APIServiceRegistrationController_unfinished_work_seconds|admission_quota_controller_work_duration|autoregister_depth|autoregister_retries|kubeproxy_sync_proxy_rules_latency_microseconds|rest_client_request_latency_seconds|non_structural_schema_condition_controller_retries)
            sourceLabels:
              - __name__
          - action: drop
            regex: etcd_(debugging|disk|server).*
            sourceLabels:
              - __name__
          - action: drop
            regex: apiserver_admission_controller_admission_latencies_seconds_.*
            sourceLabels:
              - __name__
          - action: drop
            regex: apiserver_admission_step_admission_latencies_seconds_.*
            sourceLabels:
              - __name__
          - action: drop
            regex: apiserver_request_duration_seconds_bucket;(0.15|0.25|0.3|0.35|0.4|0.45|0.6|0.7|0.8|0.9|1.25|1.5|1.75|2.5|3|3.5|4.5|6|7|8|9|15|25|30|50)
            sourceLabels:
              - __name__
              - le
    kubelet:
      enabled: true
      namespace: kube-system
      serviceMonitor:
        interval: 30s
        cAdvisorMetricRelabelings:
          - action: drop
            regex: container_(network_tcp_usage_total|network_udp_usage_total|tasks_state|cpu_load_average_10s)
            sourceLabels:
              - __name__
          - action: drop
            regex: (container_spec_.*|container_file_descriptors|container_sockets|container_threads_max|container_threads|container_start_time_seconds|container_last_seen);;
            sourceLabels:
              - __name__
              - pod
              - namespace
          - action: drop
            regex: (container_blkio_device_usage_total);.+
            sourceLabels:
              - __name__
              - container
        metricRelabelings:
          - action: drop
            regex: kubelet_(pod_worker_latency_microseconds|pod_start_latency_microseconds|cgroup_manager_latency_microseconds|pod_worker_start_latency_microseconds|pleg_relist_latency_microseconds|pleg_relist_interval_microseconds|runtime_operations|runtime_operations_latency_microseconds|runtime_operations_errors|eviction_stats_age_microseconds|device_plugin_registration_count|device_plugin_alloc_latency_microseconds|network_plugin_operations_latency_microseconds)
            sourceLabels:
              - __name__
          - action: drop
            regex: scheduler_(e2e_scheduling_latency_microseconds|scheduling_algorithm_predicate_evaluation|scheduling_algorithm_priority_evaluation|scheduling_algorithm_preemption_evaluation|scheduling_algorithm_latency_microseconds|binding_latency_microseconds|scheduling_latency_seconds)
            sourceLabels:
              - __name__
          - action: drop
            regex: apiserver_(request_count|request_latencies|request_latencies_summary|dropped_requests|storage_data_key_generation_latencies_microseconds|storage_transformation_failures_total|storage_transformation_latencies_microseconds|proxy_tunnel_sync_latency_secs)
            sourceLabels:
              - __name__
          - action: drop
            regex: kubelet_docker_(operations|operations_latency_microseconds|operations_errors|operations_timeout)
            sourceLabels:
              - __name__
          - action: drop
            regex: reflector_(items_per_list|items_per_watch|list_duration_seconds|lists_total|short_watches_total|watch_duration_seconds|watches_total)
            sourceLabels:
              - __name__
          - action: drop
            regex: etcd_(helper_cache_hit_count|helper_cache_miss_count|helper_cache_entry_count|object_counts|request_cache_get_latencies_summary|request_cache_add_latencies_summary|request_latencies_summary)
            sourceLabels:
              - __name__
          - action: drop
            regex: transformation_(transformation_latencies_microseconds|failures_total)
            sourceLabels:
              - __name__
          - action: drop
            regex: (admission_quota_controller_adds|admission_quota_controller_depth|admission_quota_controller_longest_running_processor_microseconds|admission_quota_controller_queue_latency|admission_quota_controller_unfinished_work_seconds|admission_quota_controller_work_duration|APIServiceOpenAPIAggregationControllerQueue1_adds|APIServiceOpenAPIAggregationControllerQueue1_depth|APIServiceOpenAPIAggregationControllerQueue1_longest_running_processor_microseconds|APIServiceOpenAPIAggregationControllerQueue1_queue_latency|APIServiceOpenAPIAggregationControllerQueue1_retries|APIServiceOpenAPIAggregationControllerQueue1_unfinished_work_seconds|APIServiceOpenAPIAggregationControllerQueue1_work_duration|APIServiceRegistrationController_adds|APIServiceRegistrationController_depth|APIServiceRegistrationController_longest_running_processor_microseconds|APIServiceRegistrationController_queue_latency|APIServiceRegistrationController_retries|APIServiceRegistrationController_unfinished_work_seconds|APIServiceRegistrationController_work_duration|autoregister_adds|autoregister_depth|autoregister_longest_running_processor_microseconds|autoregister_queue_latency|autoregister_retries|autoregister_unfinished_work_seconds|autoregister_work_duration|AvailableConditionController_adds|AvailableConditionController_depth|AvailableConditionController_longest_running_processor_microseconds|AvailableConditionController_queue_latency|AvailableConditionController_retries|AvailableConditionController_unfinished_work_seconds|AvailableConditionController_work_duration|crd_autoregistration_controller_adds|crd_autoregistration_controller_depth|crd_autoregistration_controller_longest_running_processor_microseconds|crd_autoregistration_controller_queue_latency|crd_autoregistration_controller_retries|crd_autoregistration_controller_unfinished_work_seconds|crd_autoregistration_controller_work_duration|crdEstablishing_adds|crdEstablishing_depth|crdEstablishing_longest_running_processor_microseconds|crdEstablishing_queue_latency|crdEstablishing_retries|crdEstablishing_unfinished_work_seconds|crdEstablishing_work_duration|crd_finalizer_adds|crd_finalizer_depth|crd_finalizer_longest_running_processor_microseconds|crd_finalizer_queue_latency|crd_finalizer_retries|crd_finalizer_unfinished_work_seconds|crd_finalizer_work_duration|crd_naming_condition_controller_adds|crd_naming_condition_controller_depth|crd_naming_condition_controller_longest_running_processor_microseconds|crd_naming_condition_controller_queue_latency|crd_naming_condition_controller_retries|crd_naming_condition_controller_unfinished_work_seconds|crd_naming_condition_controller_work_duration|crd_openapi_controller_adds|crd_openapi_controller_depth|crd_openapi_controller_longest_running_processor_microseconds|crd_openapi_controller_queue_latency|crd_openapi_controller_retries|crd_openapi_controller_unfinished_work_seconds|crd_openapi_controller_work_duration|DiscoveryController_adds|DiscoveryController_depth|DiscoveryController_longest_running_processor_microseconds|DiscoveryController_queue_latency|DiscoveryController_retries|DiscoveryController_unfinished_work_seconds|DiscoveryController_work_duration|kubeproxy_sync_proxy_rules_latency_microseconds|non_structural_schema_condition_controller_adds|non_structural_schema_condition_controller_depth|non_structural_schema_condition_controller_longest_running_processor_microseconds|non_structural_schema_condition_controller_queue_latency|non_structural_schema_condition_controller_retries|non_structural_schema_condition_controller_unfinished_work_seconds|non_structural_schema_condition_controller_work_duration|rest_client_request_latency_seconds|storage_operation_errors_total|storage_operation_status_count)
            sourceLabels:
              - __name__
    kubeControllerManager:
      service:
        enabled: true
        port: 10257
        targetPort: 10257
        selector:
          component: kube-controller-manager
      serviceMonitor:
        https: true
        interval: 30s
        insecureSkipVerify: true
        metricRelabelings:
          - action: drop
            regex: kubelet_(pod_worker_latency_microseconds|pod_start_latency_microseconds|cgroup_manager_latency_microseconds|pod_worker_start_latency_microseconds|pleg_relist_latency_microseconds|pleg_relist_interval_microseconds|runtime_operations|runtime_operations_latency_microseconds|runtime_operations_errors|eviction_stats_age_microseconds|device_plugin_registration_count|device_plugin_alloc_latency_microseconds|network_plugin_operations_latency_microseconds)
            sourceLabels:
              - __name__
          - action: drop
            regex: scheduler_(e2e_scheduling_latency_microseconds|scheduling_algorithm_predicate_evaluation|scheduling_algorithm_priority_evaluation|scheduling_algorithm_preemption_evaluation|scheduling_algorithm_latency_microseconds|binding_latency_microseconds|scheduling_latency_seconds)
            sourceLabels:
              - __name__
          - action: drop
            regex: apiserver_(request_count|request_latencies|request_latencies_summary|dropped_requests|storage_data_key_generation_latencies_microseconds|storage_transformation_failures_total|storage_transformation_latencies_microseconds|proxy_tunnel_sync_latency_secs)
            sourceLabels:
              - __name__
          - action: drop
            regex: kubelet_docker_(operations|operations_latency_microseconds|operations_errors|operations_timeout)
            sourceLabels:
              - __name__
          - action: drop
            regex: reflector_(items_per_list|items_per_watch|list_duration_seconds|lists_total|short_watches_total|watch_duration_seconds|watches_total)
            sourceLabels:
              - __name__
          - action: drop
            regex: etcd_(helper_cache_hit_count|helper_cache_miss_count|helper_cache_entry_count|request_cache_get_latencies_summary|request_cache_add_latencies_summary|request_latencies_summary)
            sourceLabels:
              - __name__
          - action: drop
            regex: transformation_(transformation_latencies_microseconds|failures_total)
            sourceLabels:
              - __name__
          - action: drop
            regex: (admission_quota_controller_adds|crd_autoregistration_controller_work_duration|APIServiceOpenAPIAggregationControllerQueue1_adds|AvailableConditionController_retries|crd_openapi_controller_unfinished_work_seconds|APIServiceRegistrationController_retries|admission_quota_controller_longest_running_processor_microseconds|crdEstablishing_longest_running_processor_microseconds|crdEstablishing_unfinished_work_seconds|crd_openapi_controller_adds|crd_autoregistration_controller_retries|crd_finalizer_queue_latency|AvailableConditionController_work_duration|non_structural_schema_condition_controller_depth|crd_autoregistration_controller_unfinished_work_seconds|AvailableConditionController_adds|DiscoveryController_longest_running_processor_microseconds|autoregister_queue_latency|crd_autoregistration_controller_adds|non_structural_schema_condition_controller_work_duration|APIServiceRegistrationController_adds|crd_finalizer_work_duration|crd_naming_condition_controller_unfinished_work_seconds|crd_openapi_controller_longest_running_processor_microseconds|DiscoveryController_adds|crd_autoregistration_controller_longest_running_processor_microseconds|autoregister_unfinished_work_seconds|crd_naming_condition_controller_queue_latency|crd_naming_condition_controller_retries|non_structural_schema_condition_controller_queue_latency|crd_naming_condition_controller_depth|AvailableConditionController_longest_running_processor_microseconds|crdEstablishing_depth|crd_finalizer_longest_running_processor_microseconds|crd_naming_condition_controller_adds|APIServiceOpenAPIAggregationControllerQueue1_longest_running_processor_microseconds|DiscoveryController_queue_latency|DiscoveryController_unfinished_work_seconds|crd_openapi_controller_depth|APIServiceOpenAPIAggregationControllerQueue1_queue_latency|APIServiceOpenAPIAggregationControllerQueue1_unfinished_work_seconds|DiscoveryController_work_duration|autoregister_adds|crd_autoregistration_controller_queue_latency|crd_finalizer_retries|AvailableConditionController_unfinished_work_seconds|autoregister_longest_running_processor_microseconds|non_structural_schema_condition_controller_unfinished_work_seconds|APIServiceOpenAPIAggregationControllerQueue1_depth|AvailableConditionController_depth|DiscoveryController_retries|admission_quota_controller_depth|crdEstablishing_adds|APIServiceOpenAPIAggregationControllerQueue1_retries|crdEstablishing_queue_latency|non_structural_schema_condition_controller_longest_running_processor_microseconds|autoregister_work_duration|crd_openapi_controller_retries|APIServiceRegistrationController_work_duration|crdEstablishing_work_duration|crd_finalizer_adds|crd_finalizer_depth|crd_openapi_controller_queue_latency|APIServiceOpenAPIAggregationControllerQueue1_work_duration|APIServiceRegistrationController_queue_latency|crd_autoregistration_controller_depth|AvailableConditionController_queue_latency|admission_quota_controller_queue_latency|crd_naming_condition_controller_work_duration|crd_openapi_controller_work_duration|DiscoveryController_depth|crd_naming_condition_controller_longest_running_processor_microseconds|APIServiceRegistrationController_depth|APIServiceRegistrationController_longest_running_processor_microseconds|crd_finalizer_unfinished_work_seconds|crdEstablishing_retries|admission_quota_controller_unfinished_work_seconds|non_structural_schema_condition_controller_adds|APIServiceRegistrationController_unfinished_work_seconds|admission_quota_controller_work_duration|autoregister_depth|autoregister_retries|kubeproxy_sync_proxy_rules_latency_microseconds|rest_client_request_latency_seconds|non_structural_schema_condition_controller_retries)
            sourceLabels:
              - __name__
          - action: drop
            regex: etcd_(debugging|disk|request|server).*
            sourceLabels:
              - __name__
    coreDns:
      enabled: true
      service:
        selector:
          k8s-app: kube-dns
      serviceMonitor:
        interval: 15s
        metricRelabelings:
          - action: keep
            regex: (coredns_forward_request_duration_seconds_bucket|process_resident_memory_bytes|process_cpu_seconds_total|go_goroutines|coredns_cache_misses_total|coredns_build_info|coredns_dns_responses_total|coredns_forward_requests_total|coredns_panics_total|coredns_dns_request_duration_seconds_bucket|coredns_dns_requests_total|coredns_cache_entries|coredns_cache_hits_total|coredns_dns_requests_total|coredns_dns_response_size_bytes_bucket|coredns_dns_request_size_bytes_bucket)
            sourceLabels:
              - __name__
    kubeEtcd:
      enabled: true
      service:
        selector:
          k8s-app: etcd
      serviceMonitor:
        enabled: true
        interval: 30s
        scheme: https
        serverName: etcd-cluster
        caFile: /etc/prometheus/secrets/kube-etcd-client-certs/etcd-client-ca.crt
        certFile: /etc/prometheus/secrets/kube-etcd-client-certs/etcd-client.crt
        keyFile: /etc/prometheus/secrets/kube-etcd-client-certs/etcd-client.key
        metricRelabelings:
          - action: labeldrop
            regex: (endpoint|service|namespace|metrics_path)
          - action: keep
            regex: (grpc_server_started_total|grpc_server_handled_total|etcd_debugging_mvcc_db_total_size_in_bytes|etcd_disk_wal_fsync_duration_seconds_bucket|etcd_disk_backend_commit_duration_seconds_bucket|etcd_network_client_grpc_received_bytes_total|etcd_network_client_grpc_sent_bytes_total|etcd_network_peer_received_bytes_total|etcd_network_peer_sent_bytes_total|etcd_server_proposals_failed_total|etcd_server_proposals_pending|etcd_server_proposals_committed_total|etcd_server_proposals_applied_total|etcd_server_leader_changes_seen_total|etcd_disk_wal_fsync_duration_seconds_sum|etcd_disk_backend_commit_duration_seconds_sum|process_resident_memory_bytes)
            sourceLabels:
              - __name__
    kubeScheduler:
      enabled: true
      service:
        enabled: true
        selector:
          k8s-app: kube-scheduler
      serviceMonitor:
        enabled: true
        interval: 30s
        insecureSkipVerify: true
    kubeProxy:
      enabled: false
      service:
        enabled: true
        selector:
          k8s-app: kube-proxy
      serviceMonitor:
        enabled: true
        interval: 30s
    kubeStateMetrics:
      enabled: true
    kube-state-metrics:
      selfMonitor:
        enabled: true
        telemetryHost: 127.0.0.1
        telemetryPort: 9443
      service: 
        port: 8443
      resources:
        requests:
          memory: 2Gi
          cpu: 200m
        limits:
          memory: 2Gi
      extraArgs:
        - --metric-labels-allowlist=nodes=[topology.kubernetes.io/region,topology.kubernetes.io/zone,failure-domain.beta.kubernetes.io/region,failure-domain.beta.kubernetes.io/zone,heat,ingress,ingress,kubernetes.io/hostname,node-role.kubernetes.io/control-plane]
      kubeRBACProxy:
        enabled: true
        extraArgs:
          - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        resources:
          requests:
            memory: 64Mi
            cpu: 10m
          limits:
            memory: 64Mi
      prometheus:
        monitor:
          enabled: true
          interval: 30s
          scheme: "https"
          tlsConfig:
            insecureSkipVerify: true
          scrapeTimeout: 30s
          metricRelabelings:
            - action: labeldrop
              regex: (endpoint|service|metrics_path|pod_uid|image_id)
            - action: drop
              regex: kube_pod_(nodeselectors|container_status_waiting|container_status_waiting_reason|runtimeclass_name_info|kube_pod_spec_volumes_persistentvolumeclaims_info|kube_pod_spec_volumes_persistentvolumeclaims_readonly|kube_pod_tolerations)
              sourceLabels:
                - __name__
    nodeExporter:
      enabled: true
    prometheus-node-exporter:
      nodeSelector:
        kubernetes.io/os: linux 
      prometheus:
        monitor:
          enabled: true
          interval: 15s
          metricRelabelings:
            - action: labeldrop
              regex: (endpoint|service|namespace|metrics_path)
            - action: drop
              regex: (promhttp_|go_).*
              sourceLabels:
                - __name__
            - action: drop
              regex: node_ipvs_backend_(connections_inactive|weight)
              sourceLabels:
                - __name__
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: instance
      rbac:
        pspEnabled: true
    prometheusOperator:
      serviceAccount:
        create: true
        name: "alertmanager-main"
      admissionWebhooks:
        timeoutSeconds: 30
        enabled: true
        patch:
          enabled: true
      logLevel: info
      resources:
        requests:
          memory: 500Mi
          cpu: 100m
        limits:
          memory: 500Mi
      dnsConfig:
        options:
          - name: ndots
            value: "2"
    prometheus:
      enabled: true
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      ingress: # SOUCIS ICI
        enabled: true
        ingressClassName: nginx
        paths: 
          - /
        pathType: Prefix
      serviceMonitor:
        selfMonitor: true
        #scheme: https
        tlsConfig:
          insecureSkipVerify: true
        bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      prometheusSpec:
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: failure-domain.beta.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app: prometheus
        secrets: 
          - kube-etcd-client-certs
        serviceMonitorNamespaceSelector:
          matchExpressions:
            - key: creator
              operator: NotIn
              values:
                - kubi
            - key: app.kubernetes.io/name
              operator: NotIn
              values:
                - ingress-nginx
        retention: 24h
        replicas: 2
        logLevel: info
        podAntiAffinity: hard
        podAntiAffinityTopologyKey: failure-domain.beta.kubernetes.io/zone
        resources:
          requests:
            memory: 15Gi
          limits:
            memory: 40Gi
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-custom-values
```
### Enter the command that you execute and failing/misfunctioning.

NONE

### Anything else we need to know?

If we set bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token" on the prometheus serviceMonitor manually, we have 403 error. (not possible to set with this chart)
Kube-state-metrics is using the good serviceAccount name
