### ISSUE TITLE
[kube-prometheus-stack] Selectively enable Default Grafana Dashboards and allow annotations

### ISSUE THREAD

**Issue by martinrw** [prometheus-community/helm-charts#3160]
### Is your feature request related to a problem ?

I would like to be able choose which default dashboards to enable for grafana and have the ability to add annotations to them so that I can place them into specific folders.

### Describe the solution you'd like.

For it to work selectively it would look somewhat similar to the default alert manager rules which are enabled like this:

```
defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    configReloaders: false
    general: true
```
We could potentially take it one step further and then allow custom annotations for each one, in the end it would be enabled something like this:

```
defaultDashboards:
  create: true
  dashboards: 
    kubernetes_api_server:
      enabled: true
      annotations:
        - k8s-sidecar-target-directory: /tmp/dashboards/Kubernetes
    kubernetes_compute_resources_pod:
      enabled: true
      annotations:
        - k8s-sidecar-target-directory: /tmp/dashboards/Kubernetes
 ```
 If you didn't specify an annotation it can just be set to {} or just not included at all

### Describe alternatives you've considered.

none, I don't see any other approach at the moment other than copying the dashboard code and deploying them separately
