### ISSUE TITLE
[kube-prometheus-stack] Grafana github oauth redirect problems

### ISSUE THREAD

**Issue by sondrelg** [prometheus-community/helm-charts#3169]
### Describe the bug a clear and concise description of what the bug is.

I am trying to configure Github-oauth for Grafana, using the kube-prometheus-chart.

## Background
The request made to the `auth_url` (https://github.com/login/oauth/authorize in my case) contains the following parameters:

```
client_id: <client-id>
redirect_uri: http://<my-domain>:3000/login/github
response_type: code
scope: user:email read:org
state: <state>
```

The authorization is successful and I'm eventually redirected back to http://<my-domain>:3000/login/github?code=<valid-code>&state=<state>.

## The problem

The problem is that this is not a valid login url. If I drop the `:3000` from the login url, it successfully logs me in as the code received is valid.

I don't know why the :3000 is used in the redirect URI and I don't think this is configurable in the chart - at least not as far as I've been able to see.

## Notes

I cannot change my redirect url to not contain `:3000` as that will cause a redirect_uri mismatch error. The root of the issue seems to be that it's included in the original request to the auth_url endpoint in the first place - but I'm very open to the possibility that this is wrong

--------------------

Any tips on how to proceed?

### What's your helm version?

version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.17.12"}

### What's your kubectl version?

Client Version: v1.24.3 Kustomize Version: v4.5.4 Server Version: v1.25.6-eks-48e63af

### Which chart?

kube-prometheus-stack

### What's the chart version?

45.8.0

### How to reproduce it?

This is my config:

```yaml
  grafana.ini:
    server:
      domain: <my-domain>

    auth:
      disable_login_form: true
      signout_redirect_url: https://<my-domain>/login

    auth.github:
      enabled: true
      allow_sign_up: true
      auto_login: true
      client_id: $__file{/etc/secrets/grafana_credentials/client_id}
      client_secret: $__file{/etc/secrets/grafana_credentials/client_secret}
      scopes: user:email,read:org
      auth_url: https://github.com/login/oauth/authorize
      token_url: https://github.com/login/oauth/access_token
      api_url: https://api.github.com/user
      allowed_organizations: <my-org>

  tls:
    - secretName: <secret-name>
      hosts:
        - <my-domain>

  ingress:
    enabled: true
    hosts: [ "<my-domain>" ]
    annotations:
      kubernetes.io/ingress.class: traefik
      kubernetes.io/ingress.allow-http: "false"

  podDisruptionBudget:
    minAvailable: 1

  extraSecretMounts:
    - name: grafana-credentials-secret-mount
      secretName: grafana-credentials  # we created this manually
      defaultMode: 0440
      mountPath: /etc/secrets/grafana_credentials
      readOnly: true
```

### Enter the command that you execute and failing/misfunctioning.

We are using terraform to apply the helm chart
