### ISSUE TITLE
[kube-prometheus-stack] Storage not increased after helm upgrade

### ISSUE THREAD

**Issue by cotoman** [prometheus-community/helm-charts#3177]
### Describe the bug a clear and concise description of what the bug is.

Hello! We're trying to increase the storage for our prometheus instance via Helm, unfortunately after upgrading the chart with the correct values, the volume doesn't seems to be changed.
Below are the relevant values from our chart:

```
    prometheus:
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
              storageClassName: managed-csi-premium
```

Storage class associated with it allows expansion on the volume (in Azure).

### What's your helm version?

v3.7.2

### What's your kubectl version?

v1.26.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

45.7.1

### What happened?

We installed kube-prometheus-stack chart with version 45.7.1 with storage set to 16Gi, now we want to increase it. After changing chart's value and upgrading it, the statefulset/PV/PVC aren't changed.

### What you expected to happen?

We are expecting the chart to point to a new storage that was expanded to 50Gi.

### How to reproduce it?

1. Install the chart with x Gi set on storage.
2. Upgrade the chart with x+1 Gi set on storage.

### Enter the changed values of values.yaml?

```
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 16Gi
```

->
```
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade prometheus prometheus-community/kube-prometheus-stack --namespace monitoring -f ./values.yaml
