### ISSUE TITLE
Using values in helmfile environments does not work for additionalScrapeConfig

### ISSUE THREAD

**Issue by codeRuslan** [prometheus-community/helm-charts#3182]
I have this value defined in environmnets/default using helmfile like this:
```

prometheus:
  prometheusSpec:
    additionalScrapeConfigs: 
      - job_name: 'blackbox-external-targets'
        metrics_path: /probe
        params:
          module: [http_2xx] # module used, inside it is which HTTP code to count valid could be setted up 
        static_configs:
          - targets: # Websites to probe
            - https://google.com
        relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: prometheus-blackbox-exporter.monitoring:9115 
      - job_name: 'TeamCity'
        metrics_path: /app/metrics
        params:
          experimental: ['true']
        scheme: https
        bearer_token: dfsfdsfsdfdsfdfsd
        static_configs:
        - targets: ['teamcity.com']
      - job_name: 'NGINX xenoss.io'
        metrics_path: /metrics
        static_configs: 
        - targets: ['000.000.00.000:31415']
      - job_name: 'NGINX Controller'
        scrape_interval: 15s
        metrics_path: /metrics
        static_configs:
        - targets: ['000.000.00.000:31415']
```
And here is how it is defined in helmfile:

```
releases:
  - name: kube-prometheus
    createNamespace: true
    namespace: monitoring
    chart: ./charts/kube-prometheus-stack
    values:
      - ./environments/default/system-values.yaml
      - ./environments/default/monitoring-values.yaml

  - name: prometheus-blackbox-exporter
    createNamespace: true
    namespace: monitoring
    chart: ./charts/prometheus-blackbox-exporter
    values:
      - ./environments/default/system-values.yaml
      - ./environments/default/monitoring-values.yaml    
```

All my other values are used from values.yaml from _environments/default/monitoring-values.yaml_ , however only additionalScrapeConfigs are not used from it and I have to define it externaly in charts/kube-prometheus-stack/values.yaml in the chart itself. What could be the problem?
