### ISSUE TITLE
[kube-state-metrics] Strong `NetworkPolicy` for `kube-state-metrics` pods

### ISSUE THREAD

**Issue by jcpunk** [prometheus-community/helm-charts#3210]
### Is your feature request related to a problem ?

When hardening kubernetes network access, it would be helpful if `kube-state-metrics` had a default recommendation for its network requirements.  It may not be viable to deploy it by default.

### Describe the solution you'd like.

A `NetworkPolicy` object for the `kube-state-metrics` containers.

### Describe alternatives you've considered.

Building it by hand

### Additional context.

https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by QuentinBisson** [comment]
@jcpunk you are free to contribute if you want. KSM should only have access to the kube-apiserver but the issue with it is that in regular network policy, you need to know the api server ip so there is no one fit all solution.

using https://github.com/prometheus-community/helm-charts/blob/6a67d96103b7277670351f941c12a2bf75c2ee8a/charts/kube-state-metrics/templates/networkpolicy.yaml#L14 should cover our use case

**Comment by jcpunk** [comment]
```yaml
networkPolicy:
  enabled: true
  egress:
    - ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
      - protocol: TCP
        port: 443
      - protocol: TCP
        port: 6443
```

Seems to work for me, but more eyes on this would be better.  If other folks can validate it, I'll put together a patch extending [helm-charts/charts/kube-state-metrics/templates/networkpolicy.yaml](https://github.com/prometheus-community/helm-charts/blob/6a67d96103b7277670351f941c12a2bf75c2ee8a/charts/kube-state-metrics/templates/networkpolicy.yaml#L14)

**Comment by jcpunk** [comment]
I'd still like to see this resolved.

**Comment by QuentinBisson** [comment]
@jcpunk can you give me your config? Because I cannot make it work on my clusters

**Comment by jcpunk** [comment]
```yaml
networkPolicy:
  enabled: true
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
    - port: 443
      protocol: TCP
```

Is what I'm using to test on KiND.  It seems to work there...
