### ISSUE TITLE
[kube-prometheus-stack] operator `NetworkPolicy` stronger egress filter

### ISSUE THREAD

**Issue by jcpunk** [prometheus-community/helm-charts#3220]
### Is your feature request related to a problem ?

When trying to ensure rational network controls.

### Describe the solution you'd like.

Update `kube-prometheus-stack/templates/prometheus-operator/networkpolicy.yaml` to have an egress filter that matches its needs. Currently all egress is allowed.

perhaps something like:
```yaml
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
    - port: 443
      protocol: TCP
```

### Describe alternatives you've considered.

Some sort of local patching

### Additional context.

https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-egress-traffic
