### ISSUE TITLE
[kube-prometheus-stack] update  prometheus-node-exporter chart to 4.15 or higher

### ISSUE THREAD

**Issue by youwalther65** [prometheus-community/helm-charts#3226]
### Is your feature request related to a problem ?

prometheus-node-exporter Helm chart 4.15.0 added support for attaching node metadata to discovered targets, see [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml#L111-L114).

### Describe the solution you'd like.

I'd like to be able to pass attachMetadata to prometheus-node-exporter sub chart:
```ttach node metadata to discovered targets.
prometheus-node-exporter:
  prometheus:
    monitor:
    attachMetadata:
      node: true
```

### Describe alternatives you've considered.

Patch node-exporter ServiceMonitor after Helm deployment, but this is "ugly"
```yaml
$ k get smon -n prometheus kube-prometheus-stack-prometheus-node-exporter -o yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
...
  name: kube-prometheus-stack-prometheus-node-exporter
  namespace: prometheus
spec:
  attachMetadata:
    node: true
  endpoints:
  - port: http-metrics
    relabelings:
    - action: replace
...
```

### Additional context.

I want to filter node-exporter metrics based on additional labels like node group name etc.
