### ISSUE TITLE
[prometheus] prometheus-config-reloader is not working with basic auth enabled

### ISSUE THREAD

**Issue by Thamizhvanan-R** [prometheus-community/helm-charts#3239]
If i enable basic auth for prometheus using

```
serverFiles:
  web.config.yml:
    basic_auth_users:
      username: <password>
```

the **prometheus-config-reloader** doesn't work, with the previous **configmap-reload** there is an option to pass additional **webhook url  using extraArgs** but with the new image there is no such option to pass the basic auth details
