### ISSUE TITLE
[prometheus] Cannot override kube-state-metrics.image.registry

### ISSUE THREAD

**Issue by davidshen84** [prometheus-community/helm-charts#3297]
### Describe the bug a clear and concise description of what the bug is.

I cannot override the `kube-state-metrics.image.registry` value. I can override other values, like `kube-state-metrics.resources`.

But if I use the `kube-state-metrics` chart directly, I can override the `image.registry` value.

### What's your helm version?

version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}

### What's your kubectl version?

Client Version: v1.27.1 Kustomize Version: v5.0.1 Server Version: v1.26.3

### Which chart?

prometheus

### What's the chart version?

21.0.1

### What happened?

With below scripts, I cannot override the `kube-state-metrics.image.registry` value. I can override other values, like `kube-state-metrics.resources`.

But if I use the `kube-state-metrics` chart directly, I can override the `image.registry` value.

### What you expected to happen?

The image registry value of the Deployment of the `kube-state-metrics` chart should be overridden.

### How to reproduce it?

```shell
  helm template  --namespace prometheus \
       --values ./values.yaml \
       prometheus-community/prometheus
```

### Enter the changed values of values.yaml?

```yaml
server:
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

kube-state-metrics:
  image:
    registry: my-acr.azurecr.io
    pullPolicy: Always

  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
```

### Enter the command that you execute and failing/misfunctioning.

  helm template  --namespace prometheus \
       --values ./values.yaml \
       prometheus-community/prometheus
