### ISSUE TITLE
Expose thanos-sidecar HTTP port via service - kube-prometheus-stack

### ISSUE THREAD

**Issue by LozanoMatheus** [prometheus-community/helm-charts#331]
**Is your feature request related to a problem? Please describe.**
I'm trying to set up the `additionalScrapeConfigs` to use the thanos-sidecar HTTP port, but the service is exposing only the web and grpc.

```yaml
    additionalScrapeConfigs:
      - job_name: 'sidecar'
        dns_sd_configs:
          - names:
              - '_http._tcp.prometheus-operated.<NAMESPACE>.svc.cluster.local'
```

https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L266-L312

**Describe the solution you'd like**
It would be great if I could use the DNS SVR register to get the HTTP port.

**Describe alternatives you've considered**

**Additional context**

```text
describe svc prometheus-operated
Name:              prometheus-operated
Namespace:         <NAMESPACE>
Labels:            operated-prometheus=true
Annotations:       <none>
Selector:          app=prometheus
Type:              ClusterIP
IP:                None
Port:              web  9090/TCP
TargetPort:        web/TCP
Endpoints:         <IP_Replica001>:9090,<IP_Replica002>:9090
Port:              grpc  10901/TCP
TargetPort:        grpc/TCP
Endpoints:         <IP_Replica001>:10901,<IP_Replica002>:10901
Session Affinity:  None
Events:            <none>
```
