### ISSUE TITLE
[prometheus] extraManifests does not work after v21.0.0

### ISSUE THREAD

**Issue by igrikus** [prometheus-community/helm-charts#3328]
### Describe the bug a clear and concise description of what the bug is.

Unable to use `extraManifests` after [this PR](https://github.com/prometheus-community/helm-charts/pull/3287):

```
Error: INSTALLATION FAILED: template: prometheus/templates/extra-manifests.yaml:3:7: executing "prometheus/templates/extra-manifests.yaml" at <.>: wrong type for value; expected string; got map[string]interface {}
```

### What's your helm version?

version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"dirty", GoVersion:"go1.20.2"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"archive", BuildDate:"2023-03-19T19:47:22Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10+rke2r1", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-19T17:41:09Z", GoVersion:"go1.19.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus

### What's the chart version?

22.0.1

### Enter the changed values of values.yaml?

```yaml
extraManifests:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: prometheus-auth
    data:
      auth: "Zm9vOiRhcHIxJERUUXUzRU5FJGVYUGxxQjI3Ui4xT3NNNXZCUWZiUC4K"
    type: Opaque
```

### Enter the command that you execute and failing/misfunctioning.

```bash
helm -n prometheus install prometheus prometheus \
--create-namespace --repo https://prometheus-community.github.io/helm-charts \
-f values.yaml
```

**Comment by igrikus** [comment]
### It can be fixed

Right now It can work only with this format:
```yaml
extraManifests:
  - |
    apiVersion: v1
    kind: Secret
    metadata:
      name: prometheus-auth
    data:
      auth: "Zm9vOiRhcHIxJERUUXUzRU5FJGVYUGxxQjI3Ui4xT3NNNXZCUWZiUC4K"
    type: Opaque
```

Note the prefix `-|` before the manifest.

---
### What causes the problem?
I think this is now a documentation problem, namely an incorrect example in `values.yaml`:
```yaml
extraManifests: []
  # - apiVersion: v1
  #   kind: ConfigMap
  #   metadata:
  #   labels:
  #     name: prometheus-extra
  #   data:
  #     extra-data: "value"
```

In this example, there is no `-|` prefix and therefore you cannot use `extraManifests` right away
