### ISSUE TITLE
[kube-prometheus-stack] Missing templating for some fields within values.yaml

### ISSUE THREAD

**Issue by ryan-dyer-sp** [prometheus-community/helm-charts#333]
**Describe the bug**
There are various places where templating from the values.yaml file is configured within the templates (eg prometheus.ingress.hosts), but other related entities are not (eg. prometheus.ingress.tls)

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

Kubernetes Version:

```console
$ kubectl version
na
```

**Which chart**: kube-prometheus-stack
**Which version of the chart**: 11.1.1

**What happened**:  Unable to use templating within values.yaml for certain fields where related options are enabled.

**What you expected to happen**: Better ability to use templating within values.yaml

**How to reproduce it** (as minimally and precisely as possible):

values.yaml (only put values which differ from the defaults)

```
domain: tld.com
prometheus:
  ingress:
    hosts:
    - prometheus.{{ .Values.domain }}
    tls:
    - secretName: prometheus-tls
      hosts:
      - prometheus.{{ .Values.domain }}
```

```
helm template prom prometheus-community/kube-prometheus-stack -f values.yaml
```

Look at the prometheus ingress.  Note the hosts field did get templated out properly; the tls field did not.  
Also note if the same is done for alertmanager, the same occurs.  Also for alertmanager the externalUrl is not rendered properly in the alertmanager resource.
-->

**Anything else we need to know**:
Will submit PR shortly to resolve these issues.
