### ISSUE TITLE
[prometheus-node-exporter] prometheus fails to get node-exporter metrics with kube-rabc-proxy enabled

### ISSUE THREAD

**Issue by rnyrnyrny** [prometheus-community/helm-charts#3338]
### Describe the bug a clear and concise description of what the bug is.

I turned on `kubeRBACProxy` of prometheus-node-exporter when deploying kube-prometheus-stack, and found that prometheus couldn't get metrics from node-exporters:
```
count:up0{container="kube-rbac-proxy", job="node-exporter", namespace="monitoring"} | 10
```
Calling node-exporter's api using prometheus' sa token returns `Forbidden`:
```
# curl -H "Authorization: Bearer $token" -k https://kube-prometheus-stack-prometheus-node-exporter.monitoring:9100
Forbidden (user=system:serviceaccount:monitoring:kube-prometheus-stack-prometheus, verb=get, resource=services, subresource=kube-prometheus-stack-prometheus-node-exporter)
```
`$token` is taken from `/var/run/secrets/kubernetes.io/serviceaccount/token` in the prometheus pod.

I believe this is due to the follow line in `prometheus-node-exporter/templates/rbac-configmap.yaml`:
```
subresource: {{ template "prometheus-node-exporter.fullname" . }}
```
As there is no such subresource called `kube-prometheus-stack-prometheus-node-exporter`

### What's your helm version?

version.BuildInfo{Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.4+k3s1", GitCommit:"8d0255af07e95b841952563253d27b0d10bd72f0", GitTreeState:"clean", BuildDate:"2023-04-20T00:33:18Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack and prometheus-node-exporter

### What's the chart version?

45.25.0

### Enter the changed values of values.yaml?

```yaml
prometheus-node-exporter:
  kubeRBACProxy:
    enabled: true
    extraArgs:
    - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    containerSecurityContext:
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
  prometheus:
    monitor:
      enabled: true
      interval: "1m"
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
      - action: labeldrop
        regex: (service|endpoint)
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels:
        - __meta_kubernetes_pod_node_name
        targetLabel: instance
      metricRelabelings:
      - action: keep
        regex: node_(uname|network)_info|node_cpu_.+|node_memory_Mem.+_bytes|node_memory_SReclaimable_bytes|node_memory_Cached_bytes|node_memory_Buffers_bytes|node_network_(.+_bytes_total|up)|node_network_.+_errs_total|node_nf_conntrack_entries.*|node_disk_.+_completed_total|node_disk_.+_bytes_total|node_filesystem_files|node_filesystem_files_free|node_filesystem_avail_bytes|node_filesystem_size_bytes|node_filesystem_free_bytes|node_filesystem_readonly|node_load.+|node_timex_offset_seconds|node_filefd_allocated|node_context_switches_total|node_procs_.*|node_disk_.*|node_sockstat_.*|node_netstat_.*
        sourceLabels:
        - __name__
```

### Enter the command that you execute and failing/misfunctioning.

helm install -n monitoring -f stack-values.yaml kube-prometheus-stack prometheus-community/kube-prometheus-stack

**Comment by zeritti** [comment]
> I believe this is due to the follow line in prometheus-node-exporter/templates/rbac-configmap.yaml

Yes, that is indeed the case. The requests have been successfully authenticated but failed to be authorized since the Prometheus' cluster role does not fullfill the proxy's requirements as set in its config file. 

What you can do is patch the Prometheus' cluster role accordingly through value `prometheus.additionalRulesForClusterRole`.

**Comment by r0bj** [comment]
I'm also experiencing this issue. Maybe use of `rbac-configmap.yaml` ConfigMap could be optional as in some cases such authorization is just too strict. For example in kube-prometheus project it's not used it at all by default: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/nodeExporter-daemonset.yaml

**Comment by NumberNot** [comment]
I'd also faced with this problem and It took little bit time to deal with it
Clarifying @zeritti's answer it should be

```yaml
prometheus:
  additionalRulesForClusterRole:
   - apiGroups: [ "" ]
     resources:
       - services/kube-prometheus-stack-prometheus-node-exporter
     verbs: [ "get", "list", "watch" ]
```
