### ISSUE TITLE
How to add Grafana datasources, dashboards and users via cli using sidecar and configmaps?

### ISSUE THREAD

**Issue by dwlian** [prometheus-community/helm-charts#336]
I have installed kube-prometheus-stack version 9.4.10 onto a rancher project using the below command:
`rancher apps install --namespace kube-system --values po-values.yaml --version 9.4.10 cattle-global-data:prometheus-community-kube-prometheus-stack prometheus-operator` 
(Rancher refers to the catalog pointing to the prometheus-community helm chart).

For this command I use a custom values yaml file called 'po-values.yaml'. In my po-values.yaml file, I have configured settings for grafana, aiming to enable sidecar to search and apply for configmaps for dashboards and datasources. Please see below for the grafana section of my po-values.yaml:
```
 grafana:
  enabled: true
  ingress:
    enabled: disabled
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
    annotations: {}
    labels: {}
    portName: service
  sidecar:
    image:
      repository: kiwigrid/k8s-sidecar
      tag: 1.1.0
      sha: ""
    imagePullPolicy: IfNotPresent
    skipTlsVerify: true
    enableUniqueFilenames: false
    dashboards:
      enabled: true
      SCProvider: true
      label: grafana_dashboard
      folder: /tmp/dashboards
      defaultFolderName: null
      searchNamespace: ALL
      folderAnnotation: null
      provider:
        name: sidecarProvider
        orgid: 1
        folder: ''
        type: file
        disableDelete: false
        allowUiUpdates: true
        foldersFromFilesStructure: false
    datasources:
      enabled: true
      label: grafana_datasource
      searchNamespace: ALL
```
In the same directory as the po-values.yaml file, I have 2 configmap files configured. One for a datasource and one for a dashboard; 'configmap-datasource-PRF1-Prometheus.yaml' and 'configmap-dashboards-app-config.yaml' respectively. These configmap files are set up with the following config:

configmap-datasource-PRF1-Prometheus.yaml:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-configmap-Prometheus
  labels:
    grafana_datasource: "true"
data:
  datasource-PRF1-Prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: PRF1 Prometheus
        type: prometheus
        url: https://prometheus.prf1.net/
        access: Server
        isDefault: true
        basicAuth: true
        basicAuthPassword: prom-operator
        basicAuthUser: admin

configmap-dashboards-app-config.yaml:
> apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-configmap-app-status
  labels:
     grafana_dashboard: "1"
data:
  app-status.json: |-
    {
    _- json contents go here_
    }
```
However, when I run this/run an upgrade of kube-prometheus-stack afterwards, Grafana is not being populated with the custom datasource/dashboard.

How do I get my installation of kube-prometheus-stack to detect these Grafana datasource and dashboard configmaps and use them to update grafana upon/after installation?

Do I need to store the configmaps elsewhere or set something in my values yaml file? Are my configmaps set up correctly?

Based off the documentation, I would create one configmap per dashboard/datasource. How do I ensure kube-prometheus-stack picks up all the configmaps?

Can something similar be done to set up users for Grafana?

Thanks for your help.

Note: the indentation did not import correctly when I inserted my code as quotes, apologies.

**Comment by fktkrt** [comment]
What I am doing is having my own charts to handle the deployments of such resources (dashboards, rules, datasources).
You can find the upstream helm templates for dashboards and data sources here: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/grafana

Basically, you can create your own charts to roll out your dashboards, just like a regular helm release.
I am using this method to achieve multi-tenancy in my clusters, as each of the applications can have their separate charts, and I can easily manage those this way.

**Comment by etho201** [comment]
@fktkrt -- Can you elaborate on what you're doing to deploy your own custom dashboards? Could you possibly provide an example? Also, with your approach, do you still get the ones included from the "[kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin)"?

**Comment by CCJY** [comment]
Hello.

I am not sure about this issue, but it would be similar. Also, I want to get default dashboards with custom dashboards like below this.
![image](https://user-images.githubusercontent.com/5335259/102270132-a2882480-3eeb-11eb-9a99-7902c43fa113.png)

# Solution

## Keep default dashboards in Kubernetes folder by using annotations.
```
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards
      provider: 
        foldersFromFilesStructure: true

      ## Annotations for Grafana dashboard configmaps
      ##
      annotations: 
        k8s-sidecar-target-directory: "/tmp/dashboards/kubernetes"
```
## Add Custom dashboards
### Create configmap for custom dashboards By using cli with yaml
>If you want to use cli, you should add annotations.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-configmap-app-status
  labels:
     grafana_dashboard: "1"
  annotations:
      k8s-sidecar-target-directory = "/tmp/dashboards/[FODLER]"
data:
  app-status.json: |-
    {
    _- json contents go here_
    }
```
### Create configmap for custom dashboards By using terraform
>I used adding configmap by using terraform, thus I put an example in there.
```
resource "kubernetes_config_map" "grafana-dashboards-istio" {
  metadata {
    name      = "grafana-dashboard-istio"
    namespace = kubernetes_namespace.monitoring.metadata[0].name

    labels = {
      grafana_dashboard = 1
    }

    annotations = {
      k8s-sidecar-target-directory = "/tmp/dashboards/istio"
    }
  }

  data = {
    "istio-mesh-dashboard.json"        = file("${path.root}/config/grafana/dashboards/istio/istio-mesh-dashboard.json")
    "istio-performance-dashboard.json" = file("${path.root}/config/grafana/dashboards/istio/istio-performance-dashboard.json")
    "istio-service-dashboard.json"     = file("${path.root}/config/grafana/dashboards/istio/istio-service-dashboard.json")
    "istio-workload-dashboard.json"    = file("${path.root}/config/grafana/dashboards/istio/istio-workload-dashboard.json")
    "pilot-dashboard.json"             = file("${path.root}/config/grafana/dashboards/istio/pilot-dashboard.json")
  }
}
```

> **Please let me know if you know any other way, or if my way is wrong.**
