### ISSUE TITLE
[Prometheus] update chart from 19.3.3 to 22.4.1 fails

### ISSUE THREAD

**Issue by nicolasporta-xite** [prometheus-community/helm-charts#3367]
### Describe the bug a clear and concise description of what the bug is.

Hello!.

I'm trying to update the chart to the latest version from 19.3.3, and it's failing with the error: `Error: YAML parse error on prometheus/templates/sts.yaml: error converting YAML to JSON: yaml: line 104: did not find expected key`

I have thanos in my setups as a sidecard container, and I think after the addition of values.schema.json in February, it's failing as the sidecard part is declared to be an object, and previous to that I believe was an array. 

I'm not 100% sure this is the case, that's why I'm asking for helm.

```
alertmanager:
  enabled: false
pushgateway:
  enabled: false
server:
  extraArgs:
    log.level: debug
    storage.tsdb.min-block-duration: 2h
    storage.tsdb.max-block-duration: 2h
  retention: 4h
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9090"
  statefulSet:
    enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10902"
  sidecarContainers:
    name: thanos-sidecar
    image: quay.io/thanos/thanos:v0.31.0
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/secret/sa.json
    args:
    - "sidecar"
    - "--log.level=debug"
    - "--tsdb.path=/data/"
    - "--prometheus.url=http://127.0.0.1:9090"
    - "--objstore.config={type: GCS, config: {bucket:}}"
    - "--reloader.config-file=/etc/prometheus-config/prometheus.yml"
    - "--reloader.config-envsubst-file=/etc/prometheus-shared/prometheus.yml"
    - "--reloader.rule-dir=/etc/prometheus-config/rules"
    ports:
    - name: sidecar-http
      containerPort: 10902
    - name: grpc
      containerPort: 10901
    - name: cluster
      containerPort: 10900
    volumeMounts:
    - name: storage-volume
      mountPath: /data
    - name: thanos-storage-secret
      mountPath: /etc/secret
    - name: config-volume
      mountPath: /etc/prometheus-config
      readOnly: false
    - name: prometheus-config-shared
      mountPath: /etc/prometheus-shared/
      readOnly: false
```

### What's your helm version?

v3.11.2

### What's your kubectl version?

Client Version: v1.25.7 Kustomize Version: v4.5.7 Server Version: v1.24.10-gke.2300

### Which chart?

prometheus

### What's the chart version?

Client Version: v1.25.7 Kustomize Version: v4.5.7 Server Version: v1.24.10-gke.2300

### Enter the command that you execute and failing/misfunctioning.

    helm upgrade metrics-prometheus prometheus/prometheus --install --namespace=monitoring -f prometheus-test.yml --timeout=5m0s --history-max=0 --set configmapReload.image.tag=v0.5.0 --set-string kubeStateMetrics.image.tag=v2.8.2 --set-string nodeExporter.image.tag=v1.5.0 --set-string server.image.tag=v2.43.1

**Comment by zeritti** [comment]
A type other than the one required by the schema would by reported by Helm quite accurately. Please, consider this:
```
sidecarContainers:
  thanos-sidecar:
    image: quay.io/thanos/thanos:v0.31.0
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/secret/sa.json
    args:
    - "sidecar"
    - "--log.level=debug"
    - "--tsdb.path=/data/"
    - "--prometheus.url=http://127.0.0.1:9090"
    - "--objstore.config={type: GCS, config: {bucket:}}"
    - "--reloader.config-file=/etc/prometheus-config/prometheus.yml"
    - "--reloader.config-envsubst-file=/etc/prometheus-shared/prometheus.yml"
    - "--reloader.rule-dir=/etc/prometheus-config/rules"
    ports:
    - name: sidecar-http
      containerPort: 10902
    - name: grpc
      containerPort: 10901
    - name: cluster
      containerPort: 10900
    volumeMounts:
    - name: storage-volume
      mountPath: /data
    - name: thanos-storage-secret
      mountPath: /etc/secret
    - name: config-volume
      mountPath: /etc/prometheus-config
      readOnly: false
    - name: prometheus-config-shared
      mountPath: /etc/prometheus-shared/
      readOnly: false
```
