### ISSUE TITLE
[kube-prometheus-stack] kube-scheduler and kube-controller-manager monitor not working

### ISSUE THREAD

**Issue by bmgante** [prometheus-community/helm-charts#3368]
Hi,

EKS 1.25 and cannot get metrics from kube-scheduler and kube-controller-manager. 
Below values.yaml for kube-scheduler (similar for kube-controller-manager).

```
## Component scraping kube scheduler
##
kubeScheduler:
  enabled: true

  ## If your kube scheduler is not deployed as a pod, specify IPs it can be found on
  ##
  endpoints: []
  # - 10.141.4.22
  # - 10.141.4.23
  # - 10.141.4.24

  ## If using kubeScheduler.endpoints only the port and targetPort are used
  ##
  service:
    enabled: true
    ## If null or unset, the value is determined dynamically based on target Kubernetes version due to change
    ## of default port in Kubernetes 1.23.
    ##
    port: null
    targetPort: null
    # selector:
    #   component: kube-scheduler

  serviceMonitor:
    enabled: true
    ## Scrape interval. If not set, the Prometheus default scrape interval is used.
    ##
    interval: ""

    ## SampleLimit defines per-scrape limit on number of scraped samples that will be accepted.
    ##
    sampleLimit: 0

    ## TargetLimit defines a limit on the number of scraped targets that will be accepted.
    ##
    targetLimit: 0

    ## Per-scrape limit on number of labels that will be accepted for a sample. Only valid in Prometheus versions 2.27.0 and newer.
    ##
    labelLimit: 0

    ## Per-scrape limit on length of labels name that will be accepted for a sample. Only valid in Prometheus versions 2.27.0 and newer.
    ##
    labelNameLengthLimit: 0

    ## Per-scrape limit on length of labels value that will be accepted for a sample. Only valid in Prometheus versions 2.27.0 and newer.
    ##
    labelValueLengthLimit: 0

    ## proxyUrl: URL of a proxy that should be used for scraping.
    ##
    proxyUrl: ""
    ## Enable scraping kube-scheduler over https.
    ## Requires proper certs (not self-signed) and delegated authentication/authorization checks.
    ## If null or unset, the value is determined dynamically based on target Kubernetes version.
    ##
    https: null

    ## Skip TLS certificate validation when scraping
    insecureSkipVerify: null

    ## Name of the server to use when validating TLS certificate
    serverName: null

    ## MetricRelabelConfigs to apply to samples after scraping, but before ingestion.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
    ##
    metricRelabelings: []
    # - action: keep
    #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
    #   sourceLabels: [__name__]

    ## RelabelConfigs to apply to samples before scraping
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
    ##
    relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   targetLabel: nodename
    #   replacement: $1
    #   action: replace

    ## Additional labels
    ##
    additionalLabels: {}
    #  foo: bar
```

Servicemonitor created by helm-chart:
```
% kubectl get servicemonitor prometheus-kube-prometheus-kube-scheduler -o yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2023-04-10T17:02:45Z"
  generation: 1
  labels:
    app: kube-prometheus-stack-kube-scheduler
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 45.7.1
    chart: kube-prometheus-stack-45.7.1
    heritage: Helm
    release: prometheus
  name: prometheus-kube-prometheus-kube-scheduler
  namespace: monitoring
  resourceVersion: "6339940"
  uid: 85c428a8-dee8-4a29-a122-4770d2498099
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: http-metrics
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: kube-prometheus-stack-kube-scheduler
      release: prometheus

```

SVC created by helm-chart:

```
% kubectl get svc prometheus-kube-prometheus-kube-scheduler -n kube-system
NAME                                        TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE
prometheus-kube-prometheus-kube-scheduler   ClusterIP   None         <none>        10259/TCP   30d
```

**Comment by bmgante** [comment]
I guess the problem are the endpoints which were empty because kube-scheduler and kube-controller-manager are not pods. Then, i tried to specify the IPs of the EKS instances but prometheus scrapping was failing. Tried also to change the endpoint for kube-scheduler for lease holder 10.0.105.9 but scrape fails as well with "Get "https://10.0.105.9:10259/metrics": context deadline exceeded".

```
# kubectl get endpoints -n kube-system
....
prometheus-kube-prometheus-kube-controller-manager   <none>                                                                     30d
prometheus-kube-prometheus-kube-etcd                 <none>                                                                     30d
prometheus-kube-prometheus-kube-scheduler            10.0.105.9:10259                                                           9m9s
...
```
Any idea on how to address this?

**Comment by QuentinBisson** [comment]
@bmgante can you access the scheduler metrics endpoint from a container in the cluster (create a container in any namespace and try a curl)?

**Comment by zeritti** [comment]
Managed Kubernetes services do not generally make control plane's metrics endpoints accessible to customers, except for kube-api-server. This is also true for EKS (to provide at least some important scheduler's metrics, EKS planned to make them available through Cloudwatch).

**Comment by bmgante** [comment]
Ok thanks. I’ve just disabled that monitoring on values.yaml to avoid
having alerts.


zeritti ***@***.***> escreveu em qui., 25/05/2023 às 22:11 :

**Comment by diego-ojeda-binbash** [comment]
@bmgante Could you share the update that you had to do to the values.yaml to achieve the disabling of those 2 alerts?
I tried using this:
```
defaultRules:
  disabled:
    Watchdog: true
    KubeControllerManagerDown: true
    KubeSchedulerDown: true
```
but it fails with this when I tried to apply that update:
```
Error: error validating "": error validating data: ValidationError(PrometheusRule.spec.groups[0]): missing required field "rules" in com.coreos.monitoring.v1.PrometheusRule.spec.groups
```

Thanks!

**Comment by bmgante** [comment]
Hi @diego-ojeda-binbash 
I think it was just this:

```
## Component scraping kube scheduler
##
kubeScheduler:
  enabled: false
```

```
## Component scraping kube scheduler
##
kubeScheduler:
  enabled: false
```


```
## Create default rules for monitoring the cluster
##
defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    configReloaders: true
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubeControllerManager: false
    kubelet: true
    kubeProxy: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true
```

**Comment by admitriev-ppro** [comment]
I assume service selector does not match ... maybe because of old version of kubernetes ...

```
selector:
    component: kube-scheduler
```

when the real label assigned to scheduler pod is `k8s-app=kube-scheduler`

**Comment by JulesLalu** [comment]
This workaround should normally solve the problem, if you still want to monitor kube-scheduler and kube-controller-manager : https://github.com/prometheus-community/helm-charts/issues/3368#issuecomment-1563510980

**Comment by rudolfbyker** [comment]
> ## Create default rules for monitoring the cluster
> ##
> defaultRules:
>   create: true
>   rules:
>     ...

Any idea where the documentation for each of these rules is? I can see they are all being used here https://github.com/prometheus-community/helm-charts/blob/11127a45423d6cf468e476e9ee5a800b7a6c29af/charts/kube-prometheus-stack/hack/sync_prometheus_rules.py but I can't figure out the meaning of some of them.

**Comment by Daemoen** [comment]
This should actually be included in the documentation.  I had to jump through issues to find this.

**Comment by cristianrgreco** [comment]
My setup with microk8s had the `kube-scheduler`, `kube-controller-manager`, and `kube-proxy` alerts firing. I had to disable them via these Helm chart values:

```yaml
values:
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false
```

I tried setting the endpoint values as described in the [microk8s docs](https://microk8s.io/docs/configure-host-interfaces) but it didn't work.
