### ISSUE TITLE
[prometheus-kube-stack] Missing statefulSet - prometheus-monitoring-kube-prometheus-prometheus 

### ISSUE THREAD

**Issue by ChenTsungYu** [prometheus-community/helm-charts#3383]
### Describe the bug a clear and concise description of what the bug is.

Hello,

I got a problem when I wanted to provision Prometheus-stack service, there was one missing service - `prometheus-kube-prometheus-kube-prome-prometheus` in statefulset from the provisioning.

`$ kubectl get statefulset -n monitoring`

From the `kubectl` command  above to check existing statefulset, I get only "one" statefulset from the output:
```
NAME                                                   READY   AGE
alertmanager-kube-prometheus-kube-prome-alertmanager   1/1     72m
```

As per checking the pods, I can still see some pods related to prometheus(e.g. node exporter) and Grafana is also working.

`$ kubectl get po -n monitoring`
```
NAME                                                     READY   STATUS    RESTARTS      AGE
alertmanager-kube-prometheus-kube-prome-alertmanager-0   2/2     Running   1 (33m ago)   33m
kube-prometheus-grafana-cff86d54-58cvl                   3/3     Running   0             33m
kube-prometheus-grafana-cff86d54-tgfhm                   3/3     Running   0             33m
kube-prometheus-kube-prome-operator-5c8486d994-x54xj     1/1     Running   0             33m
kube-prometheus-kube-state-metrics-7f85cdfd8c-kq6rm      1/1     Running   0             33m
kube-prometheus-prometheus-node-exporter-p7ttt           1/1     Running   0             33m
kube-prometheus-prometheus-node-exporter-sjg7h           1/1     Running   0             33m
kube-prometheus-prometheus-node-exporter-st55q           1/1     Running   0             33m
kube-prometheus-prometheus-node-exporter-zf5pq           1/1     Running   0             33m
```

Not sure not why the there is only one missing pod is related to the statefulset - `prometheus-kube-prometheus-kube-prome-prometheus`.

### What's your helm version?

version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}

### What's your kubectl version?

{   "clientVersion": {     "major": "1",     "minor": "25",     "gitVersion": "v1.25.2",     "gitCommit": "5835544ca568b757a8ecae5c153f317e5736700e",     "gitTreeState": "clean",     "buildDate": "2022-09-21T14:25:45Z",     "goVersion": "go1.19.1",     "compiler": "gc",     "platform": "darwin/arm64"   },   "kustomizeVersion": "v4.5.7",   "serverVersion": {     "major": "1",     "minor": "24+",     "gitVersion": "v1.24.10-eks-48e63af",     "gitCommit": "9176fb99b52f8d5ff73d67fea27f3a638f679f8a",     "gitTreeState": "clean",     "buildDate": "2023-01-24T19:17:48Z",     "goVersion": "go1.19.5",     "compiler": "gc",     "platform": "linux/amd64"   } }

### Which chart?

kube-prometheus

### What's the chart version?

45.2.0

### What you expected to happen?

There should be "two" stateful sets in the monitoring namespace

`$ kubectl get statefulset -n monitoring`

Expected  output:
```
NAME                                                   READY   AGE
alertmanager-kube-prometheus-kube-prome-alertmanager   1/1     144d
prometheus-kube-prometheus-kube-prome-prometheus       1/1     160d
```

### How to reproduce it?

```
helm upgrade 'kube-prometheus' prometheus-community/kube-prometheus-stack --install --version "45.2.0" --create-namespace --debug --atomic \
    --namespace monitoring \
    --values "$override_file_name" \
    --set "storage.tsdb.wal-compression=true" \
    --set "storage.tsdb.max-block-duration=2h"
```

### Enter the changed values of values.yaml?

The file for overriding values is below:
```
prometheus:
  serviceAccount:
    name: "xxxx-sa" # service account name
  prometheusSpec:
    retention: 5d # customize by env
    externalLabels:
      cluster: xxxx
      environment: xxxx
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "prometheus" # mapping node-group config
        effect: "NoSchedule"
    nodeSelector:
      dedicated: prometheus # mapping node-group config
      lifecycle: on-demand
    storageSpec: ## Using PersistentVolumeClaim
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 15Gi

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: "xxx-int" 
      alb.ingress.kubernetes.io/group.order: "394"
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    hosts:
      - xxxx.com 
    paths:
      - /*
      
kubeconfig:
  enabled: true
## prometheusOperator
prometheusOperator:
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "prometheus" # mapping node-group config
      effect: "NoSchedule"
  nodeSelector:
    dedicated: prometheus # mapping node-group config
    lifecycle: on-demand
  admissionWebhooks:
    patch:
      podAnnotations:
        linkerd.io/inject: disabled
## grpc
kubelet:
  serviceMonitor:
    https: true
## alertmanager
alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: "xxxx-int" # ingress group
      alb.ingress.kubernetes.io/group.order: "392"
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    hosts:
      - xxxx.com # host name
    paths:
      - /*
  alertmanagerSpec:
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "prometheus" # mapping node-group config
        effect: "NoSchedule"
    nodeSelector:
      dedicated: prometheus # mapping node-group config
      lifecycle: on-demand
## grafana
grafana:
  image:
    tag: "latest"
  sidecar:
    dashboards:
      multicluster:
        global:
          enabled: true
  adminPassword: xxxxxxx
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "prometheus" # mapping node-group config
      effect: "NoSchedule"
  nodeSelector:
    dedicated: prometheus # mapping node-group config
    lifecycle: on-demand
  replicas: 2
  grafana.ini:
    auth:
      sigv4_auth_enabled: true
    server:
      domain: xxxx.com # domain
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true
    database:
      type: postgres
      host: xxxx-db.xxxx.ap-northeast-1.rds.amazonaws.com:5432 # mapping RDS endpoint
      name: grafana # mapping inital DB name
      user: xxxx
      password: xxxx
    smtp:
      enabled: true
      host: email-smtp.us-west-2.amazonaws.com:587 
      user: xxxx
      password: xxxx
      skip_verify: true
      startTLS_policy: MandatoryStartTLS
      from_address: "no-reply@xxxx.com" # domain
      from_name: "Grafana alert"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: "xxxx-xxx" # ingress group
      alb.ingress.kubernetes.io/group.order: "396"
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=10800 
    labels: {}
    path: /

    pathType: Prefix

    hosts:
      - "xxxx.com" # host
    extraPaths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: kube-prometheus-grafana
            port:
              number: 80
```

### Enter the command that you execute and failing/misfunctioning.

```
helm upgrade 'kube-prometheus' prometheus-community/kube-prometheus-stack --install --version "45.2.0" --create-namespace --debug --atomic \
    --namespace monitoring \
    --values "$override_file_name" \
    --set "storage.tsdb.wal-compression=true" \
    --set "storage.tsdb.max-block-duration=2h"
```

**Comment by maheen-sajid** [comment]
Hi, I am facing the excact same issue, is there a solution to this?

**Comment by ghdwlsgur** [comment]
Hi, I am facing the excact same issue, too.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kube-prometheus-stack-prometheus
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/version: "58.1.3"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-58.1.3
    release: "kube-prometheus-stack"
    heritage: "Helm"
spec:
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: kube-prometheus-stack-alertmanager
        port: http-web
        pathPrefix: "/"
        apiVersion: v2
  image: "quay.io/prometheus/prometheus:v2.51.2"
  version: v2.51.2 
  paused: false
  replicas: 1
  shards: 1
  logLevel: info
  logFormat: logfmt
  listenLocal: false
  enableAdminAPI: false
  scrapeInterval: 15s
  scrapeTimeout: 10s
  evaluationInterval: 15s
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 500Mi
  retention: "14d"
  retentionSize: "10GiB"
  tsdb:
    outOfOrderTimeWindow: 0s
  walCompression: true
  routePrefix: "/"
  serviceAccountName: kube-prometheus-stack-prometheus
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: "kube-prometheus-stack"

  probeNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: "kube-prometheus-stack"

  # scrapeConfigSelector:
  #   matchLabels:
  #     release: "kube-prometheus-stack"

  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: nks-block-storage
  portName: http-web
  hostNetwork: false

```

**Comment by ghdwlsgur** [comment]
> Hi, I am facing the excact same issue, is there a solution to this?


Don't install just some crds, install them all
```bash
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.73.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.73.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.73.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.73.0/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.73.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.73.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.73.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.73.0/example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.73.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.73.0/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
```

**Comment by NicolasPyl** [comment]
I have the same issue too

**Comment by leonix2** [comment]
Check correct of settings and syntax of PrometheusSpec directive. In my case problem was in string "scrapeTimeout: 60s" it was too much for scrapeInterval 15s.

> I have the same issue too

**Comment by NicolasPyl** [comment]
We've solved the problem by changing the storageClassName. 
This is due to the rebuild of the cluster AKS on multi-region instead of single region.

`    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: managed-premium-retain
          storageClassName: managed-premium-retain-zrs
          accessModes: ["ReadWriteOnce"]
    resources:
      limits:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: managed-premium-retain
          storageClassName: managed-premium-retain-zrs
          accessModes: ["ReadWriteOnce"]
`

**Comment by Vineet-Sharma29** [comment]
still facing same issue - `
shard 0: statefulset prometheus/prometheus-prometheus-kube-prometheus-prometheus not found`

**Comment by gabrielfsousa** [comment]
i have the same issue, how can we soolve it ?

**Comment by NicolasPyl** [comment]
@gabrielfsousa i changed storageClassName fiels to  "storageClassName: managed-premium-retain-zrs"

**Comment by gabrielfsousa** [comment]
i have this

```
nameOverride: prome
grafana:
  enabled: false
kubeStateMetrics:
  enabled: true

prometheus:
  enabled: true
  prometheusSpec:
    replicas: 2
    retention: 7d
    podAntiAffinity: "hard"
    podAntiAffinityTopologyKey: "kubernetes.io/hostname"
    prometheusExternalLabelName: "prome"
    walCompression: true
    enableLifecycle: true
    scrapeInterval: "30s"
    scrapeTimeout: "10s"
    evaluationInterval: "30s"
    priorityClassName: "system-cluster-critical"

    resources:
      limits:
        cpu: 1000m
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 2Gi

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "ebs-gp3-default"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: galp.com/node-pool-purpose
              operator: In
              values: ["system"]

    tolerations:
    - key: CriticalAddonsOnly
      operator: Equal
      value: "true"
      effect: NoSchedule



alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 3

    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: galp.com/node-pool-purpose
              operator: In
              values: ["system"]

    tolerations:
    - key: CriticalAddonsOnly
      operator: Equal
      value: "true"
      effect: NoSchedule

    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 5Gi
```
