### ISSUE TITLE
[kube-prometheus-stack] Makes default prometheus rules more flexible

### ISSUE THREAD

**Issue by talset** [prometheus-community/helm-charts#3384]
### Is your feature request related to a problem ?

By default, the charts create many useful prometheus rules. But for some, it could make sense to override params such `label.severity` or `for`.

Currently, those values are hardcoded so users have to disable the rule and "fork it" on their value.yml

### Describe the solution you'd like.

To allow "customization" on alerts, a map could be created and exposed on value.yml.

Example:
To change the `for` and `label.severity` from `KubePodNotReady` alert (https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml#L62-L64)

on **values.yaml**
```
defaultRules:
  customize:
    KubePodNotReady:
      for: 5m
      labels:
        severity: critical
```

on **templates/prometheus/rules-1.14/kubernetes-apps.yaml**

```
    - alert: KubePodNotReady
...
      for: {{ .Values.defaultRules.customize.KubePodNotReady.for | default "15m" }}
      labels:
        severity: {{ .Values.defaultRules.customize.KubePodNotReady.labels.severity | default "warning" }}
```

Of course, the structure/naming needs to be thought to allow more advanced usecases (add more labels on the alert, change some parts of expr ...)

### Describe alternatives you've considered.

NONE

### Additional context.

issues linked:
* https://github.com/prometheus-community/helm-charts/issues/2409
* https://github.com/prometheus-community/helm-charts/issues/2662

**Comment by Var091** [comment]
Update here? This is also needed for us

**Comment by gopinathgct** [comment]
This would be a great option, we need this.

**Comment by qmonitoring** [comment]
For alert routing, it is highly desirable for the severity parameter to be configurable.

**Comment by mkocaks** [comment]
+1!!!!

**Comment by mkocaks** [comment]
Having to recreate the same alert and then direct the hardcoded ones to null via alert routing is a pain.
I had an ide where maybe we can read back the config map for rules - modify - then apply back but again not fool proof for future updates etc....

**Comment by buckleyGI** [comment]
This already comes in really handy to let maintenance of the rules come through while preserving custom tweaks.

Short question, why not generalise so that we can apply labels? 

```
customRules:
  KubePodNotReady:
    severity: error
    labels:
      target: opsgenie
      slack: channelX
```
Seems only logical to allow this no? Was this thought of and discarded for some reason?
