### ISSUE TITLE
[prometheus-kube-stack] Panel Memory Usage for pod not correct

### ISSUE THREAD

**Issue by buddy-yao** [prometheus-community/helm-charts#341]
**Describe the bug**
When using the chart [prometheus-kube-stack], Panel Memory Usage for pod not correct In grafana's [Kubernetes / Compute Resources / Pod] dashboard.
wrong:
![image](https://user-images.githubusercontent.com/19948569/98778484-66196280-242d-11eb-9b4d-c3d030bbcf2a.png)
correct: 
![image](https://user-images.githubusercontent.com/19948569/98778547-7e897d00-242d-11eb-9f86-eb5fa79da0c9.png)
memory usage not same, but the same pod.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: kube-prometheus-stack
**Which version of the chart**: 11.1.1

**What happened**:
memory usage not same, but the same pod.

**What you expected to happen**:
memory usage should same for the same pod.

**How to reproduce it** (as minimally and precisely as possible):
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add stable https://charts.helm.sh/stable
helm repo update
helm -n monitor install -f ./values.yaml monitor prometheus-community/kube-prometheus-stack
```

values.yaml (only put values which differ from the defaults)

```
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: mysql
      static_configs:
      - targets: ['mysql-exporter-master-service:9104']
        labels:
          instance: master
      - targets: ['mysql-exporter-background-slave-service:9104']
        labels:
          instance: background_slave
      - targets: ['mysql-exporter-read-slave1-service:9104']
        labels:
          instance: read_slave1
      - targets: ['mysql-exporter-read-slave2-service:9104']
        labels:
          instance: read_slave2
      - targets: ['mysql-exporter-read-slave3-service:9104']
        labels:
          instance: read_slave3
    - job_name: nginx
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - default
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: ^(api.*)|(callback.*)|(article.*)|(mkt-api.*)|(review)|(sapi.*)|(short-url)|(websocket)$
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_should_be_scraped]
        action: keep
        regex: true
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_scrape_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_env]
        action: replace
        target_label: env
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_app]
        action: replace
        target_label: app
    - job_name: redis
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - monitor
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: ^.*redis-exporter$
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_should_be_scraped]
        action: keep
        regex: true
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_scrape_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_instance]
        action: replace
        target_label: instance
    - job_name: fpm
      metrics_path: /fpm_metrics/
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - default
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: ^(api.*)|(callback.*)|(article.*)|(mkt-api.*)|(review)|(sapi.*)|(short-url)$
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_fpm_should_be_scraped]
        action: keep
        regex: true
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_scrape_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_env]
        action: replace
        target_label: env
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_app]
        action: replace
        target_label: app
    - job_name: elasticsearch
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - monitor
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: ^.*elasticsearch-exporter$
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_should_be_scraped]
        action: keep
        regex: true
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_scrape_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_cluster]
        action: replace
        target_label: cluster
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: instance
grafana:
  service:
    type: LoadBalancer
    port: 3000
    targetPort: 3000
    annotations:
      service.beta.kubernetes.io/ucloud-load-balancer-id: "xxxxx"
      service.beta.kubernetes.io/ucloud-load-balancer-type: "xxxxx"
  grafana.ini:
    server:
      protocol: http
      domain: localhost
```

**Anything else we need to know**:
nothing else. thx.
