### ISSUE TITLE
[kube-prometheus-stack] Set append default values instead of NilUsesHelmValues

### ISSUE THREAD

**Issue by mohsenmottaghi** [prometheus-community/helm-charts#3414]
### Is your feature request related to a problem ?

In the `kube-prometheus-stack` helm chart, I find these keys `serviceMonitorSelectorNilUsesHelmValues` and `podMonitorSelectorNilUsesHelmValues` that try to define some default configuration on Prometheus like:
```yaml
{{- if .Values.prometheus.prometheusSpec.serviceMonitorSelector }}
  serviceMonitorSelector:
{{ toYaml .Values.prometheus.prometheusSpec.serviceMonitorSelector | indent 4 }}
{{ else if .Values.prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues  }}
  serviceMonitorSelector:
    matchLabels:
      release: {{ $.Release.Name | quote }}
{{ else }}
  serviceMonitorSelector: {}
{{- end }}
```
This configuration can have multiple results:
1. if  `serviceMonitorSelectorNilUsesHelmValues` is true and `serviceMonitorSelector` is null, then it will use default values
2. if `serviceMonitorSelectorNilUsesHelmValues` is false  and `serviceMonitorSelector` is null, then it will be null
3. if  `serviceMonitorSelectorNilUsesHelmValues` is true and `serviceMonitorSelector` is not null, then the user's values will be used ( can be problematic)
4. if `serviceMonitorSelectorNilUsesHelmValues` is false and `serviceMonitorSelector` is not null, then the user's values will be used 

all of the situations are fine, but about the 3rd one, it's a little confusing because people have expected the resulted Prometheus should start scrapping Kubernetes and matched selector at the same time, but it will happen until they add another condition under that match with default behavior:
```yaml
    matchLabels:
      release: {{ $.Release.Name | quote }}
```

### Describe the solution you'd like.

In my opinion, something like `serviceMonitorSelectorNilUsesHelmValues` is not clear enough, and I want to ask if it's okay; I can create a PR and change this key to `serviceMonitorSelectorAppendDefaultValues` and also change conditions to match the condition "if this environment variable is true" in the helm values, to append it to the current configurations and let people decide about that.

### Describe alternatives you've considered.

Alternatively, we can keep the current structure.
