### ISSUE TITLE
[kube-prometheus-stack] Alerts deleted after helm upgrade

### ISSUE THREAD

**Issue by aDingil** [prometheus-community/helm-charts#3424]
### Describe the bug a clear and concise description of what the bug is.

Similar to the dashboards, alerts which have been created via the gui are been deleted after an helm upgrade.

### What's your helm version?

v3.9.2

### What's your kubectl version?

Client Version: v1.25.9, Kustomize Version: v4.5.7, Server Version: v1.26.4+k3s1

### Which chart?

kube-prometheus-stack

### What's the chart version?

45.31.1

### What happened?

See  concise description

### What you expected to happen?

Alerts been untouched

### How to reproduce it?

Install chart, create alert, upgrade chart

### Enter the changed values of values.yaml?
```yaml
kube-prometheus-stack:
  enabled: true
  namespaceOverride: watchdog
  grafana:
    name: grafana
    ## Configure grafana dashboard providers
    ## ref: http://docs.grafana.org/administration/provisioning/#dashboards
    ##
    ## `path` must be /var/lib/grafana/dashboards/<provider_name>
    ##
    dashboardProviders:
     dashboardproviders.yaml:
       apiVersion: 1
       providers:
       - name: 'default'
         orgId: 1
         folder: ''
         type: file
         disableDeletion: false
         editable: true
         options:
           path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        # https://grafana.com/grafana/dashboards/12541-traefik-2-2/
        traefik-dashboard:
          gnetId: 12541
          datasource: Prometheus
        # https://grafana.com/grafana/dashboards/16829-kubernetes-tanzu-velero/
        velero-dashboard:
          gnetId: 16829
        # https://github.com/crowdsecurity/grafana-dashboards
        crowdsec-v4-overview:
          url: https://raw.githubusercontent.com/crowdsecurity/grafana-dashboards/master/dashboards_v4/Crowdsec%20Overview.json
          datasource: Prometheus
        crowdsec-v4-details-per-machine:
          url: https://raw.githubusercontent.com/crowdsecurity/grafana-dashboards/master/dashboards_v4/Crowdsec%20Details%20per%20Machine.json
          datasource: Prometheus
    port: 80
    hostname: REDACTED
    enabled: true
    namespaceOverride: watchdog
    sidecar:
      datasources:
        defaultDatasourceEnabled: true
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki-loki-distributed-query-frontend.watchdog:3100
    ## Pass the plugins you want installed as a list.
    ##
    plugins: 
      - grafana-piechart-panel
      - grafana-worldmap-panel
      # - digrich-bubblechart-panel
      # - grafana-clock-panel
      ## You can also use other plugin download URL, as long as they are valid zip files,
      ## and specify the name of the plugin after the semicolon. Like this:
      # - https://grafana.com/api/plugins/marcusolsson-json-datasource/versions/1.3.2/download;marcusolsson-json-datasource

  prometheus:
    name: prometheus
    port: 9090
    hostname: REDACTED
    enabled: true
    namespaceOverride: watchdog
    prometheusSpec:
      # select all service monitors, otherwise application discovery could run into problems
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
      nodeSelector:
        node.kubernetes.io/server-usage: watchdog

      ## AdditionalScrapeConfigs allows specifying additional Prometheus scrape configurations. Scrape configurations
      ## are appended to the configurations generated by the Prometheus Operator. Job configurations must have the form
      ## as specified in the official Prometheus documentation:
      ## https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config. As scrape configs are
      ## appended, the user is responsible to make sure it is valid. Note that using this feature may expose the possibility
      ## to break upgrades of Prometheus. It is advised to review Prometheus release notes to ensure that no incompatible
      ## scrape configs are going to break Prometheus after the upgrade.
      ## AdditionalScrapeConfigs can be defined as a list or as a templated string.
      ##
      ## The scrape configuration example below will find master nodes, provided they have the name .*mst.*, relabel the
      ## port to 2379 and allow etcd scraping provided it is running on all Kubernetes master nodes
      ##
      
      additionalScrapeConfigs: 
        # https://traefik.io/blog/capture-traefik-metrics-for-apps-on-kubernetes-with-prometheus/
        - job_name: 'traefik-pods'
          kubernetes_sd_configs:
            - role: pod
              selectors:
                - role: pod
                  label: app.kubernetes.io/instance=traefik-traefik
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
              action: replace
              regex: ([^:]+)(?::\\d+)?;(\\d+)
              replacement: $1:$2
              target_label: __address__
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
              action: replace
              target_label: __scheme__
              regex: (https?)
        - job_name: 'velero-pods'
          kubernetes_sd_configs:
            - role: pod
              selectors:
                - role: pod
                  label: component=velero
        - job_name: 'crowdsec-pods'
          kubernetes_sd_configs:
            - role: pod
              selectors:
                - role: pod
                  label: k8s-app=crowdsec
  prometheusOperator:
    admissionWebhooks:
      patch:
        nodeSelector:
          node.kubernetes.io/server-usage: watchdog
    nodeSelector:
      node.kubernetes.io/server-usage: watchdog
  prometheus-node-exporter:
    namespaceOverride: watchdog
    nodeSelector:
      node.kubernetes.io/server-usage: watchdog
  thanosRuler:
    thanosRulerSpec:
      nodeSelector:
        node.kubernetes.io/server-usage: watchdog
```

### Enter the command that you execute and failing/misfunctioning.

```bash
helm upgrade grafana-stack . -f values.yaml
```

### Anything else we need to know?

Contact points and dashboards are been deleted too, maybe other stuff too?!
Version out of sync between github and artifact.io?!
