### ISSUE TITLE
[kube-prometheus-stack] - Alertmanager integration with opsgenie

### ISSUE THREAD

**Issue by bmgante** [prometheus-community/helm-charts#3429]
Hi, does anyone could share an optimised and working values.yaml config for alertmanager integration with opsgenie? 
Thanks

**Comment by aki263** [comment]
If you are using helm to deploy you can using something like this, I am not 100% sure. 

```
alertmanager:
  enabled: true
  config:
    route:
      receiver: 'default-receiver'
      routes:
        - match:
            severity: critical
          receiver: 'opsgenie-notifications'
    receivers:
      - name: 'default-receiver'
      - name: 'opsgenie-notifications'
        opsgenie_configs:
          - api_key: 'your-opsgenie-api-key'
            teams:
              - team: 'your-opsgenie-team'

```
