### ISSUE TITLE
[prometheus-kafka-exporter] Servicemonitor is not able to find endpoints for kafka-exporter target (shows 0/0 up)

### ISSUE THREAD

**Issue by GaykarSanket** [prometheus-community/helm-charts#343]
**Describe the bug**
I've deployed prometheus-kafka-exporter chart(Versions defined below) with servicemonitor enabled with additional labels set, so that prometheus is able to find service monitor and updated the target. The target is displayed in prometheus but it's not able to find the endpoints. In target it shows: **xyz-prod-monitor/kafka-exporter-prometheus-kafka-exporter/0 (0/0 up)**

![prometheus-target](https://user-images.githubusercontent.com/29541659/98800250-260aad80-2436-11eb-9d93-3c3d7cd34079.jpg)

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

```

**Which chart**:
kube-prometheus-stack
prometheus-kafka-exporter

**Which version of the chart**:
kube-prometheus-stack with helm chart version: 9.4.5 and apiVersion: 0.38.1 and
prometheus-kafka-exporter with helm chart version: 0.1.4 and apiVersion: v1.2.0

**What happened**:
Unable to see endpoints in prometheus target ui for kafka-exporter target: 

**What you expected to happen**:
Endpoints must be displayed in target for kafka-exporter

**How to reproduce it**:
Install kube-prometheus-stack:
```
helm install kube-prom prometheus-community/kube-prometheus-stack -n xyz-prod-monitor
```

Install prometheus-kafka-exporter with updated values.yaml as mentioned below (enable servicemonitor):

Updated contents of values.yaml for prometheus-kafka-exporter are as follows:
```
kafkaServer:
  - kafka.xyz-prod-ext.svc:9092

prometheus:
  serviceMonitor:
    enabled: true
    namespace: xyz-prod-monitor
    interval: "30s"
    additionalLabels:
      release: kube-prom
```
All other values used as default.

```
helm install kafka-exporter prometheus-community/prometheus-kafka-exporter -n xyz-prod-monitor
```

This deploys the kafka-exporter with service monitor. When I do  **curl clusterIP:9308/metrics** I'm able to get the kafka metrics.

**Comment by GaykarSanket** [comment]
@gkarthiks Can you please help us in this issue?

**Comment by gkarthiks** [comment]
hi @GaykarSanket do you want to do a PR pls?

**Comment by GaykarSanket** [comment]
Selector labels in serviceMonitor are not matching with the pod labels
```
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus-kafka-exporter.name" . }}
      helm.sh/chart: {{ include "prometheus-kafka-exporter.chart" . }}
```

Changed above labels with

```
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: {{ template "prometheus-kafka-exporter.name" . }}
      release: {{ .Release.Name }}
```
to match with pods labels


Also after describing the endpoints found that portName is **http** which should be **exporter-port** as we've specified in serviceMonitor
```
kubectl describe endpoints kafka-exporter-prometheus-kafka-exporter -n xyz-prod-monitor

Name:         kafka-exporter-prometheus-kafka-exporter
Namespace:    xyz-prod-monitor
Labels:       app=prometheus-kafka-exporter
              app.kubernetes.io/managed-by=Helm
              chart=prometheus-kafka-exporter-0.1.4
              heritage=Helm
              release=kafka-exporter
Annotations:  endpoints.kubernetes.io/last-change-trigger-time: 2020-11-18T02:53:11Z
Subsets:
  Addresses:          10.39.0.8
  NotReadyAddresses:  <none>
  Ports:
    Name  Port  Protocol
    ----  ----  --------
    http  9308  TCP

Events:  <none>
```

Changed port name in service.yaml from http to exporter-port.
