### ISSUE TITLE
[kube-prometheus-stack] alertmanager.alertmanagerSpec.secrets value is ignored

### ISSUE THREAD

**Issue by BennyDjo** [prometheus-community/helm-charts#3430]
### Describe the bug a clear and concise description of what the bug is.

Hello, 

Trying to add extra template by creating them as secret, and adding them through alertmanager.alertmanagerSpec.secrets.
I created a new secret with this chart:
                                                                                                                                                                                                                                                                                                                                                          
```
apiVersion: v1 
kind: Secret
metadata:
    name: alertmanager-templates
data:
    mytemplate.tmpl: e3sgZGVmaW5lICJteXRlbXBsYXRlIn19IFRlc3QgYWxhcm0ge3sgZW5kIH19
```

Then I configure alertmanager through helm by adding:
```
alertmanager:
  alertmanagerSpec
    secrets:
    - alertmanager-templates

```

But when I describe the *.-genereted, it does not contain my custom secret. 

Note that if I configure the template directly in helm with templateFiles it works well, template will be added as key in the default secret alertmanager-myinstall.
```

alertmanager:
  templateFiles:
    mytemplate.tmpl: {{ define "mytemplate"}} Test alarm {{ end }}

```

If I observe the operator log, at no point I see log hitting secrets/alertmanager-templates. 



### What's your helm version?

version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

45.7.1

### What happened?

alertmanager.alertmanagerSpec.secrets values are not added to secret alertmanager-*-generated 

### What you expected to happen?

When doing a kubectl describe secret alertmanager-myinstall-generated, I expect to see my additional secrets as part of the data


### How to reproduce it?

Update alertmanager.alertmanagerSpec.secrets with existing secret

### Enter the changed values of values.yaml?
```
alertmanager:
  serviceAccount:
    create: false
    name: kube-myinstall-alertmanager
  alertmanagerSpec:
    secrets:
      - alertmanager-templates
    alertmanagerConfigMatcherStrategy:
      type: None     
    alertmanagerConfigSelector:
      matchExpressions:
        - key: equipe
          operator: In
          values:
            - systeme
            - test
```
### Enter the command that you execute and failing/misfunctioning.

basic helm install

### Anything else we need to know?

_No response_
