### ISSUE TITLE
[kube-prometheus-stack] - ARM support

### ISSUE THREAD

**Issue by bmgante** [prometheus-community/helm-charts#3443]
Hi everyone, can someone confirm if we can deploy this helm chart in arm (aws graviton) instances?
Is there any change required to do that?
Thanks

**Comment by alexwiedermann** [comment]
<img width="1391" alt="image" src="https://github.com/prometheus-community/helm-charts/assets/18265511/5f57b74c-a406-4089-a047-d87b5e773926">
All kube-prometheus-stack images are multi-arch. https://quay.io/repository/prometheus-operator/prometheus-operator?tab=tags so just deploy normally.

**Comment by bmgante** [comment]
Thanks @alexwiedermann

**Comment by QuentinBisson** [comment]
@bmgante if you managed to make it run with a custom set of values, do you mind providing that in the documentation of this chart?

**Comment by elcomtik** [comment]
If you have cluster with mixed arch nodes or just testing if it will run on arm arch you can specify something like this

```yaml
   prometheus:
     prometheusSpec:
       nodeSelector:
         kubernetes.io/arch: "arm64"
   alertmanager:
     alertmanagerSpec:
       nodeSelector:
         kubernetes.io/arch: "arm64"
   grafana:
     nodeSelector:
       kubernetes.io/arch: "arm64"
   ```
