### ISSUE TITLE
[kube-prometheus-stack] add `serviceMonitor.additionalEndpoints` field

### ISSUE THREAD

**Issue by TheRealNoob** [prometheus-community/helm-charts#3499]
### Is your feature request related to a problem ?

Hello.  First of all I just want to share my appreciation for everyone that's contributed to this project!  I can't state enough how much of a time save it is for everyone.  Amazing project, and also amazing keeping everything so tightly integrated and laid out well.  Very impressive.

I have added oauth2-proxy as a sidecar to my prometheus and alertmanager pods, and configured the ingress to point to this sidecar.  I have no issues with this setup - it is all nicely laid out in the comments of the values file.  However, oauth2-proxy supports exposing prometheus metrics on another port (so as to not conflict with the proxy port) and the only way to tell prometheus to scrape this new port is to create a new serviceMonitor.  Seeing as there already exists a serviceMonitor that points to this pod, I think a cleaner solution would be to add a new endpoint inside this serviceMonitor.

If this design is implemented, the same feature could be used for scraping any prometheus sidecar, not just oauth proxy.

I am planning to work on this feature request.  I just thought I should check here first to see if any the maintainers have thoughts before I start writing.

Thank you.

### Describe the solution you'd like.

I think the ideal solution would look like below.

```yaml
prometheus:
  serviceMonitor:
    additionalEndpoints:
      - path: /metrics
        port: oauth-metrics
alertmanager:
  serviceMonitor:
    additionalEndpoints:
      - path: /metrics
        port: oauth-metrics
```

### Describe alternatives you've considered.

currently what I have implemented is below.  As you can see it is much more verbose and redundant than appending onto existing serviceMonitor.

```yaml
prometheus:
  additionalServiceMonitors:
    # prometheus oauth-metrics
    - name: prometheus-prometheus-oauth
      selector:
        matchLabels:
          app: kube-prometheus-stack-prometheus
          release: prometheus
          self-monitor: 'true'
      endpoints:
        - path: /metrics
          port: oauth-metrics
    # alertmanager oauth-metrics
    - name: prometheus-alertmanager-oauth
      selector:
        matchLabels:
          app: kube-prometheus-stack-alertmanager
          release: prometheus
          self-monitor: 'true'
      endpoints:
        - path: /metrics
          port: oauth-metrics
```

### Additional context.

I am including a more full spec of my implementation so you can grasp it better incase I haven't explained it well.  I am including only the configuration for Prometheus for sake of brevity.

```yaml
prometheus:
  service:
    additionalPorts:
      - name: oauth-proxy
        port: 8081
        targetPort: 8081
      - name: oauth-metrics
        port: 8082
        targetPort: 8082
  ingress:
    enabled: true
    servicePort: 8081
  extraSecret:
    name: prometheus-oauth-config
    data:
      <REDACTED>
  prometheusSpec:
    containers:
      - name: oauth-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
        args:
          - --upstream=http://127.0.0.1:9090
          - --http-address=0.0.0.0:8081
          - <more args>
          - --metrics-address=0.0.0.0:8082
        envFrom:
          - secretRef:
              name: prometheus-oauth-config
              optional: false
        ports:
          - containerPort: 8081
            name: oauth-proxy
            protocol: TCP
          - containerPort: 8082
            name: oauth-metrics
            protocol: TCP
  additionalServiceMonitors:
    # prometheus oauth-metrics
    - name: prometheus-prometheus-oauth
      selector:
        matchLabels:
          app: kube-prometheus-stack-prometheus
          release: prometheus
          self-monitor: 'true'
      endpoints:
        - path: /metrics
          port: oauth-metrics
```
