### ISSUE TITLE
[kube-prometheus-stack] Image registry for kube-state-metrics are overwritten by kube-prometheus-stack.global.imageRegistry

### ISSUE THREAD

**Issue by fanbel** [prometheus-community/helm-charts#3501]
### Describe the bug a clear and concise description of what the bug is.

In our use case we pull the images/charts via a private registry, therefore we need to set specific addresses for e.g. the node-exporter dependency. Since most of the images lie under quay.io, we set the kube-prometheus-stack.global.imageRegistry to the respective quay.io-registry. But in this way the registry for the kube-state-metrics image gets also set to quay.io, which ends in an error, since its located under registry.k8s.io. Because of that we set on the base of the depending chart from kube-state-metrics the following value in the kube-prometheus-stack values: kube-state-metrics.image.registry: <registry-k8s-io.priv.reg.>
In our expectation the image.registry value should overwrite the global.value for the image.registry, since most of the images are pulled from quay.io

### What's your helm version?

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"windows/amd64"} Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:47:37Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-community/kube-prometheus-stack

### What's the chart version?

45.10.1

### What happened?

The beforementioned specific value for kube-state-metrics gets overwritten by the global.imageRegistry value from the kube-prometheus-stack_chart

### What you expected to happen?

We expect that the specific image.registry paramter doesn't get overwritten if it is set manually.

### How to reproduce it?

Template the specific values as describe at kube-state-metrics.image.registry in the kube-prometheus-stack_chart.

### Enter the changed values of values.yaml?

```
kube-prometheus-stack:
  global:
    imagePullSecrets:
      - name: xxxx
    imageRegistry: <quay.priv.reg.>
  grafana:
    sidecar:
      dashboards:
        searchNamespace: "ALL"
    persistence:
      enabled: true
      storageClassName: rwo-dynamic-block-volume
      size: 50Gi
    enabled: false
    admin:
      existingSecret: xxx
      userKey: xxxx
      passwordKey: xxx
    ingress:
      enabled: true
      ingressClassName: nginx
    deploymentStrategy:
      type: Recreate
    grafana.ini:
      server:
        root_url: changeme
        router_logging: true
      security:
        disable_initial_admin_creation: false
      auth.basic:
        enabled: true
      analytics:
        check_for_updates: true
      auth:
        disable_login_form: false
      auth.generic_oauth:
        enabled: true
        name: xxx
        client_id: xxxx
        client_secret: xxx
        scopes: xxxx
        auth_url: changeme
        token_url: changeme
        api_url: changeme
        allow_sign_up: false
        tls_skip_verify_insecure: true
    serviceMonitor:
      enabled: true
  kubeEtcd:
    enabled: true
    service:
      enabled: true
      port: xx
      targetPort: xx
  kube-state-metrics:
    image:
      registry: <registry.k8s.io.priv.reg.>
    global:
      imageRegistry: <registry.k8s.io.priv.reg.>
    enabled: true
```

### Enter the command that you execute and failing/misfunctioning.

helm template .
