### ISSUE TITLE
[prometheus] Exceeded quota by 500m cpu for the prometheus server

### ISSUE THREAD

**Issue by Montek30** [prometheus-community/helm-charts#3502]
### Describe the bug a clear and concise description of what the bug is.

Hi, 
I am deploying the prometheus on the aws eks 1.27 using the flux. After deploying it the replicaset utilizes all the memory and I'm getting Exceeded quota error everytime even after inreasing the cpu and memory limits.

My HelmrRelease:
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus-for-amp
  interval: 5m0s
  chart:
    spec:
      chart: prometheus
      version: 22.6.4
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    serviceAccounts:
      server:
        annotations:
          eks.amazonaws.com/role-arn: xxx
        name: prometheus
    server:
      resources:
        limits:
          cpu: 16000m
          memory: 8Gi
        requests:
          cpu: 16000m
          memory: 8Gi
      remoteWrite:
        - url:xxx
          sigv4:
            region: eu-west-2
          queue_config:
            max_samples_per_send: 1000
            max_shards: 200
            capacity: 2500
---
```

Error:
  Warning  FailedCreate  0s (x4 over 18s)  replicaset-controller  (combined from similar events): Error creating: pods "prometheus-for-amp-server-68d9d76799-t28pt" is forbidden: exceeded quota: monitoring, requested: limits.cpu=16500m,limits.memory=8320Mi, used: limits.cpu=0,limits.memory=0, limited: limits.cpu=16,limits.memory=8Gi

monitoring namespace:
<img width="998" alt="image" src="https://github.com/prometheus-community/helm-charts/assets/51479379/35c93e83-cf97-44ab-9f2d-021066782cd6">

<img width="678" alt="image" src="https://github.com/prometheus-community/helm-charts/assets/51479379/9a1eaf69-b15f-487f-8ed0-7746a987e43b">
 

Current flux version: v2.0.0-rc.5

### What's your helm version?

version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}

### What's your kubectl version?

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:39:03Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"darwin/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.1-eks-2f008fe", GitCommit:"abfec7d7e55d56346a5259c9379dea9f56ba2926", GitTreeState:"clean", BuildDate:"2023-04-14T20:40:28Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus

### What's the chart version?

22.6.4

### What happened?

I am deploying the prometheus on the aws eks 1.27 using the flux. After deploying it the replicaset utilizes all the memory and I'm getting Exceeded quota error everytime even after inreasing the cpu and memory limits.

```

Error:
  Warning  FailedCreate  0s (x4 over 18s)  replicaset-controller  (combined from similar events): Error creating: pods "prometheus-for-amp-server-68d9d76799-t28pt" is forbidden: exceeded quota: monitoring, requested: limits.cpu=16500m,limits.memory=8320Mi, used: limits.cpu=0,limits.memory=0, limited: limits.cpu=16,limits.memory=8Gi

monitoring namespace:
<img width="978" alt="image" src="https://github.com/prometheus-community/helm-charts/assets/51479379/5e655214-d73c-449f-a009-bfc7c0f5e7dc">

<img width="678" alt="image" src="https://github.com/prometheus-community/helm-charts/assets/51479379/9a1eaf69-b15f-487f-8ed0-7746a987e43b">
 

Current flux version: v2.0.0-rc.5


### What you expected to happen?

Run prometheus on the cluster and remote write to the aws managed prometheus

### How to reproduce it?

applying the above helm release

### Enter the changed values of values.yaml?

values:
    serviceAccounts:
      server:
        annotations:
          eks.amazonaws.com/role-arn: xxx
        name: prometheus
    server:
      resources:
        limits:
          cpu: 16000m
          memory: 8Gi
        requests:
          cpu: 16000m
          memory: 8Gi
      remoteWrite:
        - url:xxx
          sigv4:
            region: eu-west-2
          queue_config:
            max_samples_per_send: 1000
            max_shards: 200
            capacity: 2500

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus-for-amp prometheus-community/prometheus -n monitoring

### Anything else we need to know?

_No response_
