### ISSUE TITLE
[node-exporter] No ability to disable scrape annotation 

### ISSUE THREAD

**Issue by mpostument** [prometheus-community/helm-charts#3517]
### Describe the bug a clear and concise description of what the bug is.

https://github.com/prometheus-community/helm-charts/blob/f02d1eefab96029dff9466f65bdf57cc977f4642/charts/prometheus-node-exporter/templates/service.yaml#L15

### What's your helm version?

version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.5"}

### What's your kubectl version?

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-0a21954", GitCommit:"cd5c12c51b0899612375453f7a7c2e7b6563f5e9", GitTreeState:"clean", BuildDate:"2023-04-15T00:32:27Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1

### Which chart?

node-exporter

### What's the chart version?

4.18.0

### What happened?

In older version of the chart (4.8.1) there was ability to disable scraping annotation in such way

```yaml
  service:
    port: 9101
    targetPort:
    annotations:
      prometheus.io/scrape: "false"
```

When i have this set to true i am receiving metrics duplicates, because they scraped by job with automatic discovery. But also i am scraping node exporter endpoint with otel daemonset

```yaml
      prometheus:
        config:
          scrape_configs:
            - job_name: node
              scrape_interval: 25s
              static_configs:
                - targets:
                    - $${K8S_NODE_NAME}:9101
              metric_relabel_configs:
                - target_label: cluster
                  replacement: ${clusterName}
```

And after this PR i am no longer have ability to disable scraping annotation 

### What you expected to happen?

Have ability set  prometheus.io/scrape to false

### How to reproduce it?

All required info should be in What happened? section

### Enter the command that you execute and failing/misfunctioning.

helm update
