### ISSUE TITLE
[prometheus-elasticsearch-exporter] podSecurityContext togglable for openshift compatibility

### ISSUE THREAD

**Issue by SylivanKenobi** [prometheus-community/helm-charts#3532]
### Is your feature request related to a problem ?

The current podSecurityContext defaults don't work with openshift. Our current workaround is overwriting the default values with null. Disabling a feature via toggle is much more reliable than overwriting the default values with null.

### Describe the solution you'd like.

podSecurityContext can be disabled via feature toggle:

```
podSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: "RuntimeDefault"
```

### Describe alternatives you've considered.

NONE
