### ISSUE TITLE
[kube-prometheus-stack] not able to setup  pod prometheus-prometheus-kube-prometheus-prometheus-0 affinity

### ISSUE THREAD

**Issue by cduv** [prometheus-community/helm-charts#3561]
### Is your feature request related to a problem ?

I'm not able to setup affinity in pod prometheus-prometheus-kube-prometheus-prometheus-0 that is related to a statefulset that creates the helm chart.

### Describe the solution you'd like.

Be able to setup affinity of this statefulset or something that let control this pod affinity to the nodes.

### Describe alternatives you've considered.

I've been investigating how to setup affinity or something to control pod prometheus-prometheus-kube-prometheus-prometheus-0 pod that depends of statefulset.
Has someone been able to control through the helm chart the affinity or other control to point to a type of nodes?

I have been reviewing the code to find the origin of this statfulset but haven't found it. But checked that deleting and running the helm chart recreates it.

### Additional context.
My context is that we are working with autoscaling using Karpenter  with different provisioners. The problem is that this pods  gets in a node that should only be working with Big data tasks, it prevents it to be automatically destroyed when the task ends.
Edited

**Comment by deutschj** [comment]
You can set the affinity for the Prometheus StatefulSet using the `affinity `section [here](https://github.com/prometheus-community/helm-charts/blob/a7b58da706001a1282fad26b4e568467c8aae712/charts/kube-prometheus-stack/values.yaml#L3176).

For example, the config that I tested:

```yaml
prometheus:
  prometheusSpec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - <hostname-to-prevent-scheduling-on>
```

**Comment by cduv** [comment]
@deutschj I am doing the test with the following code and overriding helm values.yaml file.

My tested code looking to get in a node that doesn't have th key karpenter.sh/provisioner-name=default
```
prometheusSpec:
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: karpenter.sh/provisioner-name
            operator: NotIn
            values:
            - default
   ```  

When I delete a node  or pod containing  prometheus-prometheus-kube-prometheus-prometheus-0 pod it's getting in a node with value  karpenter.sh/provisioner-name=default or other values. Seems erratic. There are nodes with other values that are available or should schedule it with Karpenter. Seems that is not finding this configuration or I'm doing something wrong.
I have to manually cordon the nodes with label default, and deleting the pod gets in a node with the other label esb-app. Otherwise I can get a big node block without tasks and not getting deleted when it has finished.

Note: From your example code, I'm not adding the prometheus: level, as I saw in [values.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2834)
Tell me if you need more information.
