### ISSUE TITLE
[kube-prometheus-stack] alertmanager-kube-prometheus-stack-alertmanager-0 spawning in wrong node node

### ISSUE THREAD

**Issue by kaykhan** [prometheus-community/helm-charts#3592]
Hi we use kube-prometheus-stack and we tried to modfy a node group recently and cluster-autoscaler reported, this is the first time seeing this error:

> 1 cluster.go:162] node ip-10-0-4-83.us-east-2.compute.internal cannot be removed: pod with local storage present: alertmanager-kube-prometheus-stack-alertmanager-0

We are confused why it was spawned on this node-group in the first place becuase we have the following set: Is there some other nodeSelector we must modify to get the above pod to spawn in the correct node group?

```
alertManager:
  alertManagerSpec:
    nodeSelector:
      acme/node-type: ops
```
