### ISSUE TITLE
What is the use of adding stable and incubator in releaser

### ISSUE THREAD

**Issue by gkarthiks** [prometheus-community/helm-charts#36]
In the GH Actions, we have the following in [L30-L33](https://github.com/prometheus-community/helm-charts/blob/main/.github/workflows/release.yaml#L30-L33). What is the purpose of adding those repo?

```yaml
      - name: Add dependency chart repos
        run: |
          helm repo add stable https://kubernetes-charts.storage.googleapis.com/
          helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
```
