### ISSUE TITLE
[kube-prometheus-stack] prometheus-kube statefulset nodeselector

### ISSUE THREAD

**Issue by kmentch** [prometheus-community/helm-charts#3600]
### Describe the bug a clear and concise description of what the bug is.

After setting all nodeslectors for all available items in the chart, there is still a resource thats not using a nodeselector and it is the [prometheus-prometheus-kube-prometheus-prometheus-0] pod. Is there an option to have this statefulset pod use a nodeselector?

### What's your helm version?

v3.12.0

### What's your kubectl version?

v1.24.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

48.1.1

### What happened?

Set all nodeselectors for all supported items in values file. Install helm and find `prometheus-prometheus-kube-prometheus-prometheus-0` pod has no nodeselector in its yaml config.

### What you expected to happen?

For the prometheus-prometheus-kube-prometheus-prometheus-0 pod to be in the nodeselectors listed.

### Enter the changed values of values.yaml?

```yaml
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
alertmanager:
  alertmanagerSpec:
    nodeSelector:
      cloud.google.com/gke-nodepool: ${nodepool}
prometheusOperator:
  nodeSelector:
    cloud.google.com/gke-nodepool: ${nodepool}
kube-state-metrics:
  nodeSelector:
    cloud.google.com/gke-nodepool: ${nodepool}
prometheusSpec:
  nodeSelector:
    cloud.google.com/gke-nodepool: ${nodepool}
thanosRulerSpec:
  nodeSelector:
    cloud.google.com/gke-nodepool: ${nodepool}
grafana:
  nodeSelector:
    cloud.google.com/gke-nodepool: ${nodepool}
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafan.example.com
    tls:
      - secretName: example
        hosts:
          - grafana.example.com
  adminPassword: ${admin_password}
```

### Enter the command that you execute and failing/misfunctioning.

I am using terraform to install this helm chart, so I don't have the exact command.

**Comment by zeritti** [comment]
> Is there an option to have this statefulset pod use a nodeselector?

Yes, there is the field `prometheus.prometheusSpec.nodeSelector`. Your value

```
prometheusSpec:
  nodeSelector:
    cloud.google.com/gke-nodepool: ${nodepool}
```

was probably meant to read

```
prometheus:
  prometheusSpec:
    nodeSelector:
      cloud.google.com/gke-nodepool: ${nodepool}
```
