### ISSUE TITLE
[kube-prometheus-stack] Issue with TSDB series deletion and Thanos sidecar upload

### ISSUE THREAD

**Issue by ermiaqasemi** [prometheus-community/helm-charts#3609]
### Describe the bug a clear and concise description of what the bug is.

I am experiencing an issue with a large number of TSDB series in our Prometheus setup. It seems that after Prometheus flushes data to storage every 2 hours, the corresponding block is immediately deleted, preventing the Thanos sidecar from uploading it to our S3 bucket. As a temporary workaround, I have reduced the flush interval to 30 minutes, which has significantly decreased memory usage.

However, I would like to find a permanent solution and revert back to the original 2-hour flush interval. I am currently using the kube-prometheus stack v48.1.1.

Environment:

Prometheus version: kube-prometheus stack v48.1.1
EKS: 1.27

```
grafana:
  enabled: false
prometheus:
  enabled: true
  prometheusSpec:
    nodeSelector:
      node.sweetops.io/lifecycle: "ondemand"
    externalLabels:
      cluster: ${CLUSTER_NAME}
    additionalArgs:
      - name: storage.tsdb.min-block-duration
        value: 30m
      - name: storage.tsdb.max-block-duration
        value: 30m
    walCompression: false
    retention: 2h
    retentionSize: 2GB
    scrapeInterval: 10s
    scrapeTimeout: 10s
    evaluationInterval: 10s
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    thanos:
      objectStorageConfig:
        key: objstore.yml
        name: thanos-storage-config
    additionalScrapeConfigs:
      - job_name: "linkerd-controller"
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - "linkerd"
                - "linkerd-viz"
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_container_port_name
            action: keep
            regex: admin-http
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: replace
            target_label: component

      - job_name: "linkerd-service-mirror"
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_label_linkerd_io_control_plane_component
              - __meta_kubernetes_pod_container_port_name
            action: keep
            regex: linkerd-service-mirror;admin-http$
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: replace
            target_label: component

      - job_name: "linkerd-proxy"
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_container_name
              - __meta_kubernetes_pod_container_port_name
              - __meta_kubernetes_pod_label_linkerd_io_control_plane_ns
            action: keep
            regex: ^linkerd-proxy;linkerd-admin;linkerd$
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod
          # special case k8s' "job" label, to not interfere with prometheus' "job"
          # label
          # __meta_kubernetes_pod_label_linkerd_io_proxy_job=foo =>
          # k8s_job=foo
          - source_labels: [__meta_kubernetes_pod_label_linkerd_io_proxy_job]
            action: replace
            target_label: k8s_job
          # drop __meta_kubernetes_pod_label_linkerd_io_proxy_job
          - action: labeldrop
            regex: __meta_kubernetes_pod_label_linkerd_io_proxy_job
          # __meta_kubernetes_pod_label_linkerd_io_proxy_deployment=foo =>
          # deployment=foo
          - action: labelmap
            regex: __meta_kubernetes_pod_label_linkerd_io_proxy_(.+)
          # drop all labels that we just made copies of in the previous labelmap
          - action: labeldrop
            regex: __meta_kubernetes_pod_label_linkerd_io_proxy_(.+)
          # __meta_kubernetes_pod_label_linkerd_io_foo=bar =>
          # foo=bar
          - action: labelmap
            regex: __meta_kubernetes_pod_label_linkerd_io_(.+)
          # Copy all pod labels to tmp labels
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
            replacement: __tmp_pod_label_$1
          # Take `linkerd_io_` prefixed labels and copy them without the prefix
          - action: labelmap
            regex: __tmp_pod_label_linkerd_io_(.+)
            replacement: __tmp_pod_label_$1
          # Drop the `linkerd_io_` originals
          - action: labeldrop
            regex: __tmp_pod_label_linkerd_io_(.+)
          # Copy tmp labels into real labels
          - action: labelmap
            regex: __tmp_pod_label_(.+)
        metric_relabel_configs:
          - action: drop
            source_labels: [le]
            regex: "2.*|3.*|4.*|5.*"
      - job_name: "grafana"
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ["linkerd-viz"]
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_container_name
            action: keep
            regex: ^grafana$
```

### What's your helm version?

version.BuildInfo{Version:"v3.11.3", GitCommit:"66a969e7cc08af2377d055f4e6283c33ee84be33", GitTreeState:"clean", GoVersion:"go1.20.3"}

### What's your kubectl version?

Client Version: v1.27.1 Kustomize Version: v5.0.1 Server Version: v1.27.3-eks-a5565ad

### Which chart?

prometheus-kube-stack

### What's the chart version?

v48.1.1

### Enter the command that you execute and failing/misfunctioning.

.
