### ISSUE TITLE
[kube-prometheus-stack] Grafana not showing Data

### ISSUE THREAD

**Issue by urbaman** [prometheus-community/helm-charts#3631]
### Describe the bug a clear and concise description of what the bug is.

Grafana shows "no data " in each and every dashboard, even if Prometheus showa all of the targets up and they are perfectly querable.

### What's your helm version?

3.10.1

### What's your kubectl version?

1.27.2

### Which chart?

kube-prometheus-chart

### What's the chart version?

46.5.0

### What happened?

Opened Grafana, all dashboards present, but showing "No Data", even if Prometheus shows targets up and querable.

### What you expected to happen?

I expect to see data form the Prometheus datasource

### How to reproduce it?

Well, probably just installing it, with longhorn storage.
Probably happened afeter a cluster restart.

### Enter the changed values of values.yaml?

```yaml
  namespaces:
    releaseNamespace: true
    additional:
      - calico-apiserver
      - calico-system
      - cert-manager
      - default
      - kube-node-lease
      - kube-public
      - kube-system
      - longhorn-system
      - metallb-system
      - tigera-operator
      - traefik
```

Disable the internal etcd scraping:

```yaml
kubeEtcd:
  enabled: false
```

And define Alertmanager notifications by email:

```yaml
    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - receiver: 'null'
        matchers:
          - alertname =~ "InfoInhibitor|Watchdog"
      - receiver: 'mail'
        matchers:
          - alertname =~ "InfoInhibitor|Watchdog"
    receivers:
    - name: 'null'
    - name: 'mail'
      email_configs:
      - to: 'tomail@domain.com'
        from: 'frommail@domain.com'
        smarthost: smtp.domain.com:587
        auth_username: 'tomail@domain.com'
        auth_identity: 'tomail@domain.com'
        auth_password: 'password'
        send_resolved: true
```

Under the grafana header, add some plugins:

```yaml
  plugins:
    - grafana-piechart-panel
    - grafana-clock-panel
```

Finally, set the storage specs for dynamic persistent storage:

```yaml
alertmanager:
  alertmanagerSpec:
    storage:
     volumeClaimTemplate:
       spec:
         storageClassName: longhorn
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 50Gi
prometheus:
  prometheusSpec:    
    storageSpec: 
     volumeClaimTemplate:
       spec:
         storageClassName: longhorn
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 50Gi
```

And install:

```bash
helm install --namespace monitoring --create-namespace kube-prometheus-stack prometheus-community/kube-prometheus-stack --values prom-stack.yaml
```

### Enter the command that you execute and failing/misfunctioning.

Not a single command, it all works, but grafana do not see data.

**Comment by urbaman** [comment]
Here's what I see trying to query Prometheus from Grafana:

![Immagine](https://github.com/prometheus-community/helm-charts/assets/26753344/03d1c7d4-b7b4-4294-ab0f-4fe9e22f6048)

**Comment by urbaman** [comment]
Another debugging step.

- If I access Grafana through Traefik and VPN, it works.
- If I access Grafana through Teleport, and Traefik (no VPN), it shows no data with the origin not allowed error.

**Comment by urbaman** [comment]
The problem was accessing Grafana trhough Teleport, without forcing the Host and Origin headers.
Solved adding them to the Teleport config for Grafana:

```
    app_service:
      enabled: true
      apps:
      - name: grafana
        uri: https://grafana.domain.com
        labels:
          env: monitoring
          context: homelab
        rewrite:
          headers:
          - "Origin: https://grafana.domain.com"
          - "Host: grafana.domain.com"
      [... other apps ...]
```
