### ISSUE TITLE
[prometheus-rabbitmq-exporter] Broken set password for auth

### ISSUE THREAD

**Issue by wirwolf** [prometheus-community/helm-charts#3634]
### Describe the bug a clear and concise description of what the bug is.

After refactoring in this mr https://github.com/prometheus-community/helm-charts/pull/3582 my release is broken. 
I see error
```
time="2023-07-24T15:17:28Z" level=error msg="Error while retrieving data from rabbitHost" error="<nil>" host="https://rabbitmq.domain.org:15672" statusCode=401
```
Autor refactor code and remove set password from helm values.

### What's your helm version?

v3.10.2

### What's your kubectl version?

v1.23.7

### Which chart?

prometheus-rabbitmq-exporter

### What's the chart version?

1.8.0

### What happened?

Exporter can not connect to rabbitmq and export metrics

### What you expected to happen?

In pipeline job run  command ``` helm upgrade --install ``` with some argsthe 

### How to reproduce it?

install chart using version 1.6.0 and upgrade to 1.8.0

### Enter the changed values of values.yaml?

```
rabbitmq:
  capabilities: bert,no_sort
  configMapOverrideReference: ""
  excludeMetrics: ""
  existingPasswordSecret: null
  existingPasswordSecretKey: password
  exporters: exchange,node,overview,queue
  include_queues: .*
  include_vhost: .*
  max_queues: 0
  output_format: TTY
  password: *redacted*
  skip_queues: ^delay_.*$
  skip_verify: "true"
  skip_vhost: ^$
  timeout: 30
  url: https://rabbitmq.*redacted*.org:15672
  user: *redacted*
replicaCount: 1
resources:
  limits:
    cpu: 300m
    memory: 100Mi
  requests:
    cpu: 150m
    memory: 50Mi
```

### Enter the command that you execute and failing/misfunctioning.

```
      helm upgrade \
        --install ${RELEASE_NAME}-exporter \
        --namespace ${KUBE_NAMESPACE} \
        --atomic \
        --wait \
        prometheus-community/prometheus-rabbitmq-exporter \
        \
        -f .helm/services/${HELM_APP_NAME}-exporter.yaml \
        \
        --set fullnameOverride=${RELEASE_NAME}-exporter \
        \
        --set rabbitmq.url=${RABBITMQ_MANAGEMENT_PROTOCOL}://${RABBITMQ_HOST}:${RABBITMQ_MANAGEMENT_PORT} \
        --set rabbitmq.user=${RABBITMQ_MANAGEMENT_USER} \
        --set rabbitmq.password=${RABBITMQ_MANAGEMENT_PASS} 
```
