### ISSUE TITLE
[kube-prometheus-stack] Kubernetes / Persistent Volumes Grafana dashboard empty

### ISSUE THREAD

**Issue by drewhemm** [prometheus-community/helm-charts#3637]
### Describe the bug a clear and concise description of what the bug is.

This dashboard shows no data because the metric names referenced are not available in Prometheus:

![image](https://github.com/prometheus-community/helm-charts/assets/4614943/5324c036-eb2a-49d9-ae3d-820505da8d83)

`kubelet_volume_stats_capacity_bytes` and `kubelet_volume_stats_available_bytes` are not found, while `kube_persistentvolume_capacity_bytes` and `kube_persistentvolumeclaim_resource_requests_storage_bytes` are.

The metrics also have different labels, which means that swapping out the metric names alone will not work. 

### What's your helm version?

v3.11.3

### What's your kubectl version?

v1.26.4

### Which chart?

kube-prometheus-stack

### What's the chart version?

48.2.0

### What happened?

The Kubernetes / Persistent Volumes dashboard does not display any data:

![image](https://github.com/prometheus-community/helm-charts/assets/4614943/a1835146-6ca6-465b-8f9c-2705f9e22355)

### What you expected to happen?

I expect to see data in the Kubernetes / Persistent Volumes dashboard. 

### How to reproduce it?

- Deploy kube-prometheus-stack chart
- Open the Kubernetes / Persistent Volumes dashboard in Grafana and you should see no data
- Open the Prometheus Graph page
- Search for metric names `kubelet_volume_stats_capacity_bytes` or `kubelet_volume_stats_available_bytes`; you will not find them

### Enter the changed values of values.yaml?

```
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - disableDeletion: false
        editable: true
        name: default
        options:
          path: /var/lib/grafana/dashboards/default
        orgId: 1
        type: file
  initChownData:
    enabled: false
  persistence:
    enabled: true
    storageClassName: efs
prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: efs
```

### Enter the command that you execute and failing/misfunctioning.

helm install kube-prometheus-stack https://prometheus-community.github.io/helm-charts/kube-prometheus-stack --version 48.2.0 --values values.yaml
