### ISSUE TITLE
[prometheus-kafka-exporter] Add fields relabelings and metricRelabelings in servicemonitor

### ISSUE THREAD

**Issue by speedfl** [prometheus-community/helm-charts#3639]
### Is your feature request related to a problem ?

When using Prometheus Kafka Exporter we may need to add `relabelings` or `metricRelabelings`. 
Ie:

```yaml
metricRelabelings:
      - regex: .*([0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}).*
        replacement: $1
        sourceLabels:
        - consumergroup
        targetLabel: customerid
```

### Describe the solution you'd like.

Add in service monitor:

```yaml
    {{- if .Values.prometheus.serviceMonitor.relabelings }}
    relabelings:
    {{- toYaml .Values.prometheus.serviceMonitor.relabelings | nindent 6 }}
    {{- end }}
    {{- if .Values.prometheus.serviceMonitor.metricRelabelings }}
    metricRelabelings:
    {{- toYaml .Values.prometheus.serviceMonitor.metricRelabelings | nindent 6 }}
    {{- end }}
```

### Describe alternatives you've considered.

N/A
