### ISSUE TITLE
[kube-prometheus-stack] Prometheus recording rule is not selected

### ISSUE THREAD

**Issue by weipingc** [prometheus-community/helm-charts#3648]
### Describe the bug a clear and concise description of what the bug is.

Helm installed `prometheus-kube-stack` without any customization, then created a `PrometheusRule` which is a recording rule, but I could not find the rule at Prometheus's rules page. I'm not sure if I deployed the `PrometheusRule` in a right way.

Per the comments on [values.yaml](https://github.com/prometheus-community/helm-charts/blob/cb4aa6648ba6f3e72d1f7bcb16fa8a8cbba4ec48/charts/kube-prometheus-stack/values.yaml#L2978-L2994), this rule should be selected and appears on [Prometheus's rules page](http://localhost:9090/rules)

### What's your helm version?

version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.20.2"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:48Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/amd64"} Kustomize Version: v5.0.1 Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5-gke.1400", GitCommit:"4eb57372b0f0ac0023caca078161b75185febeef", GitTreeState:"clean", BuildDate:"2023-06-05T09:29:48Z", GoVersion:"go1.19.9 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

48.2.2

### What happened?

kubectl port-forward service/kube-prometheus-stack-prometheus http-web

I navigate to http://localhost:9090/rules
can't find `mytest.record.rules`

### What you expected to happen?

I should be able to find `mytest.record.rules`

### How to reproduce it?

```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack
```

```
helm history kube-prometheus-stack
```

```
REVISION	UPDATED                 	STATUS  	CHART                       	APP VERSION	DESCRIPTION
1       	Mon Jul 31 10:47:22 2023	deployed	kube-prometheus-stack-48.2.2	v0.66.0    	Install complete
```

```
cat > single-record-rule.yaml << EOF
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: prometheus-rulefiles
  name: mytest-resources
  namespace: default
  # namespace: infrastructure
spec:
  groups:
    - name: ./mytest.record.rules
      rules:
        - expr: |
            max by (app, job) (label_replace(container_memory_usage_bytes,"app", "$1", "container", "(.+)"))
          record: mytest:container_memory_usage_bytes:max
EOF
```

```
kubectl apply -f single-record-rule.yaml
```

### Enter the changed values of values.yaml?

none

### Enter the command that you execute and failing/misfunctioning.

helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack
