### ISSUE TITLE
[kube-prometheus-stack] prometheus-kube-prometheus-thanos-gateway ingress use the wrong serviceName

### ISSUE THREAD

**Issue by outscale-vbr** [prometheus-community/helm-charts#3650]
### Describe the bug a clear and concise description of what the bug is.

 prometheus-kube-prometheus-thanos-gateway ingress uses the wrong serviceName

### What's your helm version?

version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.17.13"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.11", GitCommit:"5824e3251d294d324320db85bf63a53eb0767af2", GitTreeState:"clean", BuildDate:"2022-06-16T05:33:55Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

48.2.2

### What happened?

Ingress for thanos sidecar:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
  name: prometheus-kube-prometheus-thanos-gateway
  namespace: default
  labels:
    app: kube-prometheus-stack-prometheus
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "48.2.2"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-48.2.2
    release: "prometheus"
    heritage: "Helm"
spec:
  rules:
    - host: thanos-sidecar-dev.148-253-83-29.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 10901
  tls:
    - hosts:
      - thanos-sidecar-dev.148-253-83-29.sslip.io
      secretName: thanos-sidecar-dev.148-253-83-29.sslip.io-tls
```
Thanos discovery service:
```
apiVersion: v1
kind: Service
metadata:
  name: prometheus-kube-prometheus-thanos-discovery
  namespace: default
  labels:
    app: kube-prometheus-stack-thanos-discovery
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "48.2.2"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-48.2.2
    release: "prometheus"
    heritage: "Helm"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 10902
    targetPort: http
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
```
spec.rules[0].http.paths[0].backend.service.name is prometheus-kube-prometheus-prometheus instead of prometheus-kube-prometheus-thanos-discovery

### What you expected to happen?

Ingress for thanos sidecar:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
  name: prometheus-kube-prometheus-thanos-gateway
  namespace: default
  labels:
    app: kube-prometheus-stack-prometheus
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "48.2.2"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-48.2.2
    release: "prometheus"
    heritage: "Helm"
spec:
  rules:
    - host: thanos-sidecar-dev.148-253-83-29.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-thanos-discovery
                port:
                  number: 10901
  tls:
    - hosts:
      - thanos-sidecar-dev.148-253-83-29.sslip.io
      secretName: thanos-sidecar-dev.148-253-83-29.sslip.io-tls
```
Thanos discovery service.
```
apiVersion: v1
kind: Service
metadata:
  name: prometheus-kube-prometheus-thanos-discovery
  namespace: default
  labels:
    app: kube-prometheus-stack-thanos-discovery
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "48.2.2"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-48.2.2
    release: "prometheus"
    heritage: "Helm"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 10902
    targetPort: http
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
```
spec.rules[0].http.paths[0].backend.service.name is  prometheus-kube-prometheus-thanos-discovery

### How to reproduce it?

You can use cert-manager and ingress-nginx.
And you can also use this tutorial:
https://particule.io/en/blog/thanos-monitoring/

### Enter the changed values of values.yaml?

```
grafana:
  enabled: false
prometheus: 
  enabled: true
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
  thanosIngress:
    enabled: true
    pathType: "Prefix"
    tls:
      - secretName: thanos-sidecar-dev.169-254-169-254.sslip.io-tls
        hosts:
          - thanos-sidecar-dev.169-254-169-254.sslip.io
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-staging
      acme.cert-manager.io/http01-edit-in-place: "true"
    hosts:
      - thanos-sidecar-dev.169-254-169-254.sslip.io
    paths:
      - /
  prometheusSpec:
    thanos:
      objectStorageConfig:
        name: thanos-objstore
        key: objstore.yml
      baseImage: quay.io/thanos/thanos
      version: v0.31.0
    replicas: 1
    retention: 2d
    retentionSize: "6GB"
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: "ebs-sc"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi 
```

### Enter the command that you execute and failing/misfunctioning.

 helm install prometheus  prometheus-community/kube-prometheus-stack -f kube-prometheus-stack-thanos.yaml 

### Anything else we need to know?

Possible Solution:
in https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/ingressThanosSidecar.yaml#L3C1-L4C1
Replace:
```
{{- $serviceName := printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "prometheus" }}
```
By:
```
{{- $serviceName := printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "thanos-discovery" }}

```
