### ISSUE TITLE
[prometheus] Alerts in a configmap function failed. Retrying in next tick

### ISSUE THREAD

**Issue by 23ewrdtf** [prometheus-community/helm-charts#3660]
### Describe the bug a clear and concise description of what the bug is.

I installed prometheus-community/prometheus with `helm upgrade prometheus-community prometheus-community/prometheus -f values.yaml --debug`

I created below configmap with `kubectl apply -f rules.yaml`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerting-rules
  namespace: default
data:
  alerting_rules.yml: |
    alerts:
      rules:
        groups:
        - name: EmbeddedExporter
          rules:
          - alert: PrometheusJobMissing
            expr: 'absent(up{job="prometheus"})'
            for: 0m
            labels:
              severity: warning
            annotations:
              summary: Prometheus job missing (instance {{ $labels.instance }})
              description: "A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

          - alert: PrometheusTargetMissing
            expr: 'up == 0'
            for: 0m
            labels:
              severity: critical
            annotations:
              summary: Prometheus target missing (instance {{ $labels.instance }})
              description: "A Prometheus target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```

I added below to values.yaml line 72:

```
    extraConfigmapMounts:
      - name: prometheus-alerting-rules
        mountPath: /etc/config/alerts/alerts.yaml
        subPath: ""
        configMap: prometheus-alerting-rules
        readOnly: true
```

After upgrading the helm release I get below error:

```
kubectl logs prometheus-community-server-54b88864d-dxvww -f
Defaulted container "prometheus-server-configmap-reload" out of: prometheus-server-configmap-reload, prometheus-server
level=info ts=2023-08-02T16:10:06.263425202Z caller=main.go:115 msg="Starting prometheus-config-reloader" version="(version=0.66.0, branch=refs/tags/v0.66.0, revision=e21bdb5675e24d94504d530fd19fb89627a631a3)"
level=info ts=2023-08-02T16:10:06.263493693Z caller=main.go:116 build_context="(go=go1.20.4, platform=linux/amd64, user=Action-Run-ID-5269793792, date=20230614-16:50:23, tags=unknown)"
level=info ts=2023-08-02T16:10:06.264101197Z caller=reloader.go:235 msg="started watching config file and directories for changes" cfg= out= dirs=/etc/config
level=error ts=2023-08-02T16:10:17.802398613Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 500 Internal Server Error; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2023-08-02T16:10:17.836249858Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": EOF"
level=error ts=2023-08-02T16:10:18.239970835Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": dial tcp 127.0.0.1:9090: connect: connection refused"
level=error ts=2023-08-02T16:10:29.505522368Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": EOF"
level=error ts=2023-08-02T16:10:29.50581754Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": dial tcp 127.0.0.1:9090: connect: connection refused"
level=error ts=2023-08-02T16:10:33.23902753Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": dial tcp 127.0.0.1:9090: connect: connection refused"
```

### What's your helm version?

version.BuildInfo{Version:"v3.12.2", GitCommit:"1e210a2c8cc5117d1055bfaa5d40f51bbc2e345e", GitTreeState:"clean", GoVersion:"go1.20.6"}

### What's your kubectl version?

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:48Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/arm64"} Kustomize Version: v5.0.1 Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-a5565ad", GitCommit:"54df329fed2192decd6adb7a5b548344cdd8f4f2", GitTreeState:"clean", BuildDate:"2023-06-15T21:18:40Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.27) and server (1.21) exceeds the supported minor version skew of +/-1

### Which chart?

prometheus-community/prometheus

### What's the chart version?

23.1.0

### Enter the command that you execute and failing/misfunctioning.

helm upgrade prometheus-community prometheus-community/prometheus -f values.yaml --debug

### Anything else we need to know?

Prometheus works fine if I put the alerting rules directly inside the value files but I would like to move them to a separate configmap.

**Comment by eremcan** [comment]
> As config-reloader cannot contact prometheus, I reckon the latter is crash looping due to the fact that it cannot compose its configuration. The main problem is the volume mount (note that `/etc/config/alerts` is an existing file).
> 
> With respect to configmap mount, the simplest case with a new directory:
> 
> ```yaml
> extraConfigmapMounts:
>   - name: prometheus-alerting-rules
>     mountPath: /etc/config/custom_rules
>     subPath: ""
>     configMap: prometheus-alerting-rules
>     readOnly: true
> ```
> 
> The resulting file will be `/etc/config/custom_rules/alerting_rules.yml`.
> 
> Make prometheus consider files in the directory by adding a line with the path
> 
> ```yaml
> serverFiles:
>   prometheus.yml:
>     rule_files:
>       - "/etc/config/custom_rules/*.yml"
> ```
> 
> If you wish that config-reloader watch the file for changes and make prometheus reload its configuration then, you can enter
> 
> ```yaml
> configmapReload:
>   prometheus:
>     extraArgs:
>       watched-dir: /etc/config/custom_rules
> ```
> 
> Regarding your config map, it should contain a valid rules configuration (you can use [promtool](https://prometheus.io/docs/prometheus/latest/command-line/promtool/) to validate them before creating the config map). You should replace
> 
> ```yaml
> data:
>   alerting_rules.yml: |
>     alerts:
>       rules:
>         groups:
> ```
> 
> with
> 
> ```yaml
> data:
>   alerting_rules.yml: |
>     groups:
> ```
> 
> Hope this will get you going.

It looks like there are 2 extraConfigmapMounts. It was a little confusing as a newbie. So Thanks to @zeritti 's recommandation, I have managed that way and wanted to demonstrate an example values yaml below,
```
server:
  ## Prometheus server container name
  name: server
  persistentVolume:
    ## If true, Prometheus server will create/use a Persistent Volume Claim
    enabled: true
    size: 40Gi
  ## Use a StatefulSet if replicaCount needs to be greater than 1 (see below)
  replicaCount: 1
  statefulSet:
    ## If true, use a statefulset instead of a deployment for pod management.
    ## This allows to scale replicas to more than 1 pod
    enabled: false
  extraConfigmapMounts:
    - name: prometheus-alerts
      mountPath: /etc/config/custom_rules
      subPath: ""
      configMap: prometheus-alerts
      readOnly: true
configmapReload:
  prometheus:
    extraArgs:
      watched-dir: /etc/config/custom_rules
serverFiles:
  prometheus.yml:
    rule_files:
      - /etc/config/custom_rules/*.yml

alertmanager:
  ## If false, alertmanager will not be installed
  enabled: true

  persistence:
    size: 10Gi

```
