### ISSUE TITLE
[kube-prometheus-stack] Using multiple imagePullSecrets with Operator

### ISSUE THREAD

**Issue by njgibbon** [prometheus-community/helm-charts#3662]
### Describe the bug a clear and concise description of what the bug is.

A YAML templating error is thrown when using multiple `imagePullSecrets`.

### What's your helm version?

version.BuildInfo{Version:"v3.12.2", GitCommit:"1e210a2c8cc5117d1055bfaa5d40f51bbc2e345e", GitTreeState:"clean", GoVersion:"go1.20.5"}

### What's your kubectl version?

_

### Which chart?

kube-prometheus-stack

### What's the chart version?

48.2.3

### What happened?

```
Error: YAML parse error on kube-prometheus-stack/templates/prometheus-operator/deployment.yaml: error converting YAML to JSON: yaml: line 36: did not find expected key
```
This is rendered:
```
    spec:
      imagePullSecrets:
        - name: secret-1
  - name: secret-2
      containers:
```

### What you expected to happen?
Both `imagePullSecrets` should be populated in all templates where they want to be used.
```
    spec:
      imagePullSecrets:
        - name: secret-1
        - name: secret-2
```
### How to reproduce it?

Download latest chart. Change values as shown. Run helm template as shown.

### Enter the changed values of values.yaml?
```
global:
  imagePullSecrets:
  - name: "secret-1"
  - name: "secret-2"
```

### Enter the command that you execute and failing/misfunctioning.
```
helm template ./ --values ./values.yaml --debug
```

### Anything else we need to know?

Important to note that when using 1 secret in the list that the whole process succeeds. And when using 2 secrets in the list the 2 are rendered in many other templates that use `imagePullSecrets` but only fail in this case!

This issue was identified when using the terraform helm provider at 2.9.0 - https://github.com/hashicorp/terraform-provider-helm - and reproduced by downloading the chart and just manually templating.

Given the list of secrets works fine in most cases I am sure it is a subtle templating thing - probably indentation. I've been trial and erroring but not got to the correct result yet. Will raise PR soon.
