### ISSUE TITLE
[kube-prometheus-stack] ValidationError(Prometheus.spec): unknown field "scrapeConfigNamespaceSelector"

### ISSUE THREAD

**Issue by david-nano** [prometheus-community/helm-charts#3680]
### Describe the bug a clear and concise description of what the bug is.

When trying to upgrade the stack from version `45.6.0` to `48.3.0`, the `helm upgrade` return error:
```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Prometheus.spec): unknown field "scrapeConfigNamespaceSelector" in com.coreos.monitoring.v1.Prometheus.spec, ValidationError(Prometheus.spec): unknown field "scrapeConfigSelector" in com.coreos.monitoring.v1.Prometheus.spec]
```

### What's your helm version?

version.BuildInfo{Version:"v3.12.2", GitCommit:"1e210a2c8cc5117d1055bfaa5d40f51bbc2e345e", GitTreeState:"clean", GoVersion:"go1.20.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v5.0.1 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"9710807c82740b9799453677c977758becf0acbb", GitTreeState:"clean", BuildDate:"2022-12-08T10:08:06Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.27) and server (1.24) exceeds the supported minor version skew of +/-1

### Which chart?

kube-prometheus-stack

### What's the chart version?

45.6.0 -> 48.3.0

### What happened?

Getting error as desribe

### What you expected to happen?

Do helm upgrade without doing anything

### How to reproduce it?

Use the same values the fit the stack like I've provided (simple as that) and install it on your own cluster.
Once it deployed, try to change version and do `helm upgrade`

### Enter the changed values of values.yaml?

```
kube-prometheus-stack:
  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      tls:
      hosts:
        - prometheus.dc-infra.local
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: nginx-controller
          scrape_interval: 10s
          static_configs:
            - targets: [ "ingress-nginx-controller-controller-metrics.nginx-controller.svc.cluster.local:10254" ]
```

### Enter the command that you execute and failing/misfunctioning.

`helm upgrade -n monitoring kube-prometheus-stack kube-prometheus-stack-umbrella/`
 (the umbrella since I'm getting other stuff)
