### ISSUE TITLE
[prometheus-node-exporter] Liveness probe fails with http status code 401 when configured with http basic auth

### ISSUE THREAD

**Issue by shoce** [prometheus-community/helm-charts#3688]
### Describe the bug a clear and concise description of what the bug is.

To enable basic auth on :9100 used below configuration:

```
# values.yaml

extraHostVolumeMounts:
- name: cfg
  hostPath: /cfg/
  mountPath: /cfg/
  readOnly: true

extraArgs:
- --web.config.file=/cfg/prometheus-node-exporter.web.yaml
```

```
# /cfg/prometheus-node-exporter.web.yaml

basic_auth_users:
  prom: $2a$10$Pug/CFeweUoIbq4Q8sc2Yux8VVoREAb98uIpJJolRV20fEBFh8s2e
```

`curl -s -S --head http://127.1:9100/metrics` gives 401
`curl -s -I --user prom:password http://127.1:9100/metrics` gives 200 OK with metrics

But readiness and liveness probes fail with status code 401 and the pod gets restarted all the time. 

### What's your helm version?

version.BuildInfo{Version:"v3.12.2", GitCommit:"1e210a2c8cc5117d1055bfaa5d40f51bbc2e345e", GitTreeState:"clean", GoVersion:"go1.20.5"}

### What's your kubectl version?

Client Version: v1.27.4   Kustomize Version: v5.0.1   Server Version: v1.27.4+k0s

### Which chart?

prometheus-node-exporter

### What's the chart version?

4.22.0

### What happened?

Readiness and liveness probes fail if web.config.file with basic_auth_users defined.

### What you expected to happen?

Expected to configure http basic auth in helm `values.yaml` file and correct readiness and liveness probes.

### How to reproduce it?

In the description of the issue.

### Enter the changed values of values.yaml?
```
extraHostVolumeMounts:
- name: cfg
  hostPath: /cfg/
  mountPath: /cfg/
  readOnly: true

extraArgs:
- --web.config.file=/cfg/prometheus-node-exporter.web.yaml
```

### Enter the command that you execute and failing/misfunctioning.

`helm install prometheus-node-exporter-my-server -n prometheus-node-exporter-my-server --version 4.22.0 -f /cfg/prometheus-node-exporter.values.yaml ` goes well and the daemonset and the pod are starting but after some time the pod gets restarted due to failing readiness and liveness probes.

### Anything else we need to know?

It would be best to have web basic auth configuration in `values.yaml` and avoid using additional config file. This would allow easy usage of the credentials for the readiness and liveness probes.

**Comment by shoce** [comment]
Temporary solution adding to `values.yaml`:
```
readinessProbe:
  httpGet:
    httpHeaders:
    - name: Authorization
      value: 'Basic cHJvbTpwYXNzd29yZA=='

livenessProbe:
  httpGet:
    httpHeaders:
    - name: Authorization
      value: 'Basic cHJvbTpwYXNzd29yZA=='
```

helped
