### ISSUE TITLE
[prometheus] Liveness probe fails with http status code 401 when configured with http basic auth

### ISSUE THREAD

**Issue by vkamlesh** [prometheus-community/helm-charts#3701]
### Describe the bug a clear and concise description of what the bug is.

I have installed Prometheus on the Kubernetes cluster using a helm chart with basic auth option. The Liveness and Readiness HTTP prob failing with status code 401.
Helm Chart Name: prometheus-community/prometheus
Chart Version: 22.7.0

### What's your helm version?

3.12

### What's your kubectl version?

1.26

### Which chart?

prometheus-community/prometheus

### What's the chart version?

22.7.0

### What happened?

After deployment, Prometheus pod stuck in CrashLoopBackOff. 

  prometheus-server-configmap-reload:
    Container ID:  containerd://8a9c0e553837ba62621335ddc1a16bd8ca0057b08997b541acb7ecbd41d5bbef
    Image:         quay.io/prometheus-operator/prometheus-config-reloader:v0.66.0
    Image ID:      quay.io/prometheus-operator/prometheus-config-reloader@sha256:b7493034219c1465ff84d47dc8a8f337ed15465d1143e6ef3af3ba995d128a5c
    Port:          <none>
    Host Port:     <none>
    Args:
      --watched-dir=/etc/config
      --reload-url=http://127.0.0.1:9090/-/reload
    State:          Running
      Started:      Thu, 17 Aug 2023 15:47:13 +0530
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/config from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-hwsm8 (ro)
  prometheus-server:
    Container ID:  containerd://2ed16569444bcda613a9b8e1497e0bcc723adef33e898190b54ae7fb9551216f
    Image:         quay.io/prometheus/prometheus:v2.45.0
    Image ID:      quay.io/prometheus/prometheus@sha256:9309deb7c981e8a94584d9ed689fd62f7ac4549d816fd3881550311cf056a237
    Port:          9090/TCP
    Host Port:     0/TCP
    Args:
      --storage.tsdb.retention.time=15d
      --config.file=/etc/config/prometheus.yml
      --storage.tsdb.path=/data
      --web.console.libraries=/etc/prometheus/console_libraries
      --web.console.templates=/etc/prometheus/consoles
      --enable-feature=expand-external-labels
      --web.enable-lifecycle
      --web.route-prefix=/
      --web.external-url=https://prio.xyz.com/prometheus/
      --web.enable-remote-write-receiver
      --web.config.file=/etc/config/http/web.yaml
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 17 Aug 2023 16:08:13 +0530
      Finished:     Thu, 17 Aug 2023 16:08:13 +0530
    Ready:          False
    Restart Count:  9
    Liveness:       http-get http://:15020/app-health/prometheus-server/livez delay=30s timeout=10s period=15s #success=1 #failure=3
    Readiness:      http-get http://:15020/app-health/prometheus-server/readyz delay=30s timeout=4s period=5s #success=1 #failure=3
    Environment:
      environment:  <set to the key 'environment' of config map 'common'>  Optional: false
    Mounts:

### What you expected to happen?

Readiness and Liveness probe should pass.

### How to reproduce it?

Use values.yaml file and run the following command.

`helm upgrade --install ke-prometheus prometheus-community/prometheus --version 22.7.0 -f prometheus_values.yaml --namespace monitoring --debug --wait`

### Enter the changed values of values.yaml?

```
server:
  remoteWrite:
    - url: https://prio.xyz.com/prometheus/api/v1/write
      name: meta
      queue_config:
        max_samples_per_send: 1000
        max_shards: 200
        capacity: 2500
      write_relabel_configs:
        - source_labels: [ '__name__' ]
          regex: 'etcd_request_duration_seconds_bucket|apiserver_request_slo_duration_seconds_bucket|apiserver_request_duration_seconds_bucket|rest_client_rate_limiter_duration_seconds_bucket|rest_client_request_duration_seconds_bucket|etcd_request_duration_seconds_bucket|container_tasks_state'
          action: 'drop'
  env:
    - name: environment
      valueFrom:
        configMapKeyRef:
          name: common
          key: environment

  global:
    external_labels:
      environment: ${environment}

  extraFlags:
    - enable-feature=expand-external-labels
    - web.enable-lifecycle
    - web.route-prefix=/
    - web.external-url=https://prio.xyz.com/prometheus/
    - web.enable-remote-write-receiver
    - web.config.file=/etc/config/http/web.yaml
  extraSecretMounts:
    - name: prometheus-secret
      mountPath: /etc/secrets
      secretName: istio-ingressgateway-certs
      readOnly: true
  extraConfigmapMounts:
    - name: prometheus-http
      mountPath: /etc/config/http
      configMap: prometheus-http
      readOnly: true
  probeHeaders:
    - name: "Authorization"
      value: "Basic YWRtaW46YTIvTlhyOGp...g=="
extraManifests:
   - |
     apiVersion: v1
     data:
       web.yaml: |-
         basic_auth_users:
           admin: $2a$12$rS56Yy9/adjahdshahashahasldhasldhasldhsal #Dummy
     kind: ConfigMap
     metadata:
       name: prometheus-http
       namespace: monitoring
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install ke-prometheus prometheus-community/prometheus --version 22.7.0 -f prometheus_values.yaml --namespace monitoring --debug --wait
