### ISSUE TITLE
[prometheus] app.kubernetes.io/version not removed from Kubernetes Service selectors 

### ISSUE THREAD

**Issue by stephan2012** [prometheus-community/helm-charts#3709]
### Describe the bug a clear and concise description of what the bug is.

The `app.kubernetes.io/version` label selector was removed in v22.0.0, causing side effects in the Kubernetes Service `prometheus-server` when upgrading the Helm chart `prometheus` from v21.0 to v23.4.0: Since the label was not explicitly set to `null`, Helm merges them with the old ones, resulting in

```yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: prometheus
  […]
spec:
  […]
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: v2.43.0
  […]
```

The resulting list of endpoints will be empty, making the service unavailable.

### What's your helm version?

version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}

### What's your kubectl version?

v1.27.4

### Which chart?

prometheus

### What's the chart version?

v23.4.0

### What happened?

See description

### What you expected to happen?

The chart must explicitly set `app.kubernetes.io/version` to `null` to fix the Kubernetes Service.

### How to reproduce it?

Install the chart version v21.0.0, then upgrade.

### Enter the changed values of values.yaml?

N/A

### Enter the command that you execute and failing/misfunctioning.

N/A

### Anything else we need to know?

I will submit a PR shortly.

**Comment by zeritti** [comment]
> Install the chart version v21.0.0, then upgrade.

I attempted to manually reproduce the behaviour (helm 3.12.3, kind 1.27.3). The merged selector you are describing came never up. An example of a basic upgrade below.

1. Install 21.0.0
```
helm install prometheus prometheus-community/prometheus --version 21.0.0 \
  -n monitoring --create-namespace --set server.statefulSet.enabled=true
```
The service's selector does include the affected version label as expected:
```
...
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: v2.43.0
```
2. Pre-upgrade task
```
kubectl delete sts prometheus-server --cascade=orphan -n monitoring
```

3. Upgrade to 23.4.0
```
helm upgrade prometheus prometheus-community/prometheus --version 23.4.0 \
  -n monitoring --set server.statefulSet.enabled=true
```

The resulting service includes the selector without the version label.
```
...
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
```
The service `prometheus-server` also shows an active endpoint after the upgrade:
```
$ kubectl get ep
NAME                                  ENDPOINTS          AGE
kubernetes                            172.18.0.2:6443    80m
prometheus-alertmanager               10.244.0.75:9093   10m
prometheus-alertmanager-headless      10.244.0.75:9093   10m
prometheus-kube-state-metrics         10.244.0.74:8080   10m
prometheus-prometheus-node-exporter   172.18.0.2:9100    10m
prometheus-prometheus-pushgateway     10.244.0.76:9091   10m
prometheus-server                     10.244.0.77:9090   10m
prometheus-server-headless            10.244.0.77:9090   10m
```

The above procedure is basically the one described in README. Did you apply a specific one or use a specific tool to upgrade your release?
