### ISSUE TITLE
[postgres-exporter] Lack of server label - Multi-Target Support 

### ISSUE THREAD

**Issue by rafal-skurka** [prometheus-community/helm-charts#3714]
### Describe the bug a clear and concise description of what the bug is.

I have a problem with lack of "server" label in multi-target. Some of the metrics have this label but not all, it's quite problematic because we can't distinguish database servers. I have reported this issue on `postgres_exporter` repository but they reply it's an issue on Prometheus relabeling, not in the postgres exporter application - https://github.com/prometheus-community/postgres_exporter/issues/888 

Could you help how to configure this relabeling to obtain "server" label on all metrics? 

### What's your helm version?

3.8.2

### What's your kubectl version?

1.27

### Which chart?

prometheus-postgres-exporter

### What's the chart version?

5.0.0

### What you expected to happen?

All metrics will have "server" label

### How to reproduce it?

For example this metrics doesn't have "server" label:
`pg_database_size_bytes`

This example have "server" label:
`pg_settings_autovacuum`

### Enter the changed values of values.yaml?

```
  config:
    extraArgs: [ "--collector.stat_statements" ]
    datasourceSecret:
      name: postgres-exporter-datasources
      key: datasources

  serviceMonitor:
    enabled: true
    labels:
      monitoring: "prometheus"
    relabelings:
      - sourceLabels: [ __address__ ]
        targetLabel: __param_target
      - sourceLabels: [ __param_target ]
        targetLabel: instance
      - targetLabel: __address__
        replacement: prometheus-postgres-exporter:80
```

### Enter the command that you execute and failing/misfunctioning.

helm install postgres-exporter prometheus-community/prometheus-postgres-exporter -f postgres-values.yaml --namespace monitoring
