### ISSUE TITLE
[kube-prometheus-stack] AlertManagerConfig won't be applied

### ISSUE THREAD

**Issue by alifiroozi80** [prometheus-community/helm-charts#3736]
### Describe the bug a clear and concise description of what the bug is.

Hello everyone
I want to update the alert-manager-config.
Since we have CRD, I would rather use that instead of updating the `alertmanager-prom-alertmanager` secret.
Here is my manifest:

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alert-manager-config
  namespace: monitoring
  labels:
    app: prom
    release: prom
spec:
  receivers:
  - name: "robusta"
    webhookConfigs:
    - url: "http://robusta-runner.robusta.svc.cluster.local/api/alerts"
      sendResolved: true
  route:
    routes:
    - receiver: "robusta"
      group_by: [ '...' ]
      group_wait: 1s
      group_interval: 1s
      matchers:
        - severity =~ ".*"
      repeat_interval: 4h
      continue: true

```

---

It shows that it's there:

```shell
$ k -n monitoring get alertmanagerconfig
NAME                   AGE
alert-manager-config   9m2s
```

Here is its description:

```shell
$ k -n monitoring describe alertmanagerconfig alert-manager-config 
Name:         alert-manager-config
Namespace:    monitoring
Labels:       app=prom
              release=prom
Annotations:  <none>
API Version:  monitoring.coreos.com/v1alpha1
Kind:         AlertmanagerConfig
Metadata:
  Creation Timestamp:  2023-08-29T09:59:54Z
  Generation:          1
  Resource Version:    8014374
  UID:                 66deb9f2-5687-44f5-9745-06a6b723e024
Spec:
  Receivers:
    Name:  robusta
    Webhook Configs:
      Send Resolved:  true
      URL:            http://robusta-runner.robusta.svc.cluster.local/api/alerts
  Route:
    Routes:
      Continue:  true
      group_by:
        ...
      group_interval:  1s
      group_wait:      1s
      Matchers:
        severity =~ ".*"
      Receiver:         robusta
      repeat_interval:  4h
Events:                 <none>
```

Also, here are the alert-manger pod logs:

```shell
$ k -n monitoring logs pod/alertmanager-prom-alertmanager-0 
ts=2023-08-29T08:37:31.021Z caller=main.go:240 level=info msg="Starting Alertmanager" version="(version=0.25.0, branch=HEAD, revision=258fab7cdd551f2cf251ed0348f0ad7289aee789)"
ts=2023-08-29T08:37:31.021Z caller=main.go:241 level=info build_context="(go=go1.19.4, user=root@abe866dd5717, date=20221222-14:51:36)"
ts=2023-08-29T08:37:31.078Z caller=coordinator.go:113 level=info component=configuration msg="Loading configuration file" file=/etc/alertmanager/config_out/alertmanager.env.yaml
ts=2023-08-29T08:37:31.078Z caller=coordinator.go:126 level=info component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config_out/alertmanager.env.yaml
ts=2023-08-29T08:37:31.086Z caller=tls_config.go:232 level=info msg="Listening on" address=[::]:9093
ts=2023-08-29T08:37:31.086Z caller=tls_config.go:271 level=info msg="TLS is disabled." http2=false address=[::]:9093
ts=2023-08-29T08:37:31.470Z caller=coordinator.go:113 level=info component=configuration msg="Loading configuration file" file=/etc/alertmanager/config_out/alertmanager.env.yaml
ts=2023-08-29T08:37:31.471Z caller=coordinator.go:126 level=info component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config_out/alertmanager.env.yaml
```

But when I check the Alert-Manager Dashboard, I still see the same old configs.

What should I do?

### What's your helm version?

v3.12.2

### What's your kubectl version?

v1.27.4

### Which chart?

kube-prometheus-stack

### What's the chart version?

48.3.1

### Enter the command that you execute and failing/misfunctioning.

k apply -f <FILENEME>

**Comment by alifiroozi80** [comment]
Hello @zeritti 
Sorry for my late response.
I tried a couple of things and none of them worked actually...

---

1) `alertmanager.alertmanagerSpec.alertmanagerConfigSelector`

```yaml
alertmanagerSpec:
    alertmanagerConfigSelector:
      matchExpressions:
        - key: app
          operator: In
          values:
            - alert-manager-config
```

and 

```yaml
alertmanagerSpec:
    alertmanagerConfigSelector:
       matchLabels:
         app: alert-manager-config
```

---

2) `alertmanager.config`

```yaml
alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - receiver: 'robusta'
        group_by: [ '...' ]
        group_wait: 1s
        group_interval: 1s
        matchers:
          - severity =~ ".*"
        repeat_interval: 4h
        continue: true
      - receiver: 'null'
        matchers:
          - alertname =~ "InfoInhibitor|Watchdog"
    receivers:
    - name: 'null'
    - name: 'robusta'
      webhookConfigs:
      - url: 'http://robusta-runner.robusta.svc.cluster.local/api/alerts'
        sendResolved: true
    templates:
    - '/etc/alertmanager/config/*.tmpl'
```

---

Still, doesn't. show anything...

**Comment by alifiroozi80** [comment]
Hello again @zeritti 
Looked at the Prometheus Operator logs and find this line:

```shell
level=warn ts=2023-09-02T08:48:04.491362455Z caller=operator.go:1087 component=alertmanageroperator msg="skipping alertmanagerconfig" error="root route must define a receiver" alertmanagerconfig=monitoring/alert-robusta-config namespace=monitoring alertmanager=prom-alertmanager
```

---

So, I guess now, with your solution and have this lines in my `values.yaml` file, alert-manger can see the new config.

```yaml
alertmanagerSpec:
    alertmanagerConfigSelector:
       matchLabels:
         app: alert-manager-config
```

---

The question is: is that a syntax error?

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alert-robusta-config
  namespace: monitoring
  labels:
    app: alert-manager-config
spec:
  receivers:
  - name: "robusta"
    webhookConfigs:
    - url: "http://robusta-runner.robusta.svc.cluster.local/api/alerts"
      sendResolved: true
  route:
    routes:
    - receiver: "robusta"
      group_by: [ '...' ]
      group_wait: 1s
      group_interval: 1s
      matchers:
        - severity =~ ".*"
      repeat_interval: 4h
      continue: true
```


If yes, then why I applied it without any error in K8s?

**Comment by mihaico** [comment]
first you need to change the matchers to use these api definitions https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1alpha1.Matcher
 and keeping the `alertmanagerConfigSelector` config, you need to define a root route (not sure why one is required) in your `AlertmanagerConfig` - this will then be merged with the main config.
 
 e.g. 
 ```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alert-robusta-config
  namespace: monitoring
  labels:
    app: alert-manager-config
spec:
  receivers:
  - name: "robusta"
    webhookConfigs:
    - url: "http://robusta-runner.robusta.svc.cluster.local/api/alerts"
      sendResolved: true
  route:
    receiver: "robusta"
    group_by: [ '...' ]
    group_wait: 1s
    group_interval: 1s
    matchers:
    - name: severity
      matchType: =~
      value: ".*"
    repeat_interval: 4h
    continue: true
    routes:
      <other sub receivers if needed>
```
