### ISSUE TITLE
[kube-prometheus-stack] namespace does not exists 

### ISSUE THREAD

**Issue by urbaman** [prometheus-community/helm-charts#3741]
### Describe the bug a clear and concise description of what the bug is.

Hi,

I'm trying to add the cert-manager namespace to the scoped namespaces, and added it in the helm chart:

```
  namespaces:
    releaseNamespace: true
    additional:
      - calico-apiserver
      - calico-system
      - cert-manager
      - cloudflared
      - default
      - gpu-feature-discovery
      - heimdall
      - homer
      - kube-node-lease
      - kube-public
      - kube-system
      - kubernetes-dashboard
      - kubescape
      - longhorn-system
      - metallb-system
      - monitoring
      - nfs-provisioning
      - node-feature-discovery
      - nvidia-device-plugin
      - portainer
      - teleport-agent
      - teleport-cluster
      - tigera-operator
      - traefik
      - traefik-external
```

But it does not seem to work properly:

`msg="get namespace to enqueue Prometheus instances failed: namespace \"cert-manager\" does not exist"`

And it does exists:

```
kubectl get namespaces
NAME                     STATUS   AGE
calico-apiserver         Active   27h
calico-system            Active   27h
cert-manager             Active   4h
default                  Active   27h
gpu-feature-discovery    Active   7h31m
k8tz                     Active   7h12m
kube-node-lease          Active   27h
kube-public              Active   27h
kube-system              Active   27h
longhorn-system          Active   10h
metallb-system           Active   22h
monitoring               Active   10h
nfs-provisioning         Active   5h40m
node-feature-discovery   Active   7h32m
nvidia-device-plugin     Active   7h19m
tigera-operator          Active   27h
```

How to make it work?

Both cert-manager and kube-prometheus-stack in the last version. Kubeadm cluster 1.28.1

### What's your helm version?

3.10.1

### What's your kubectl version?

1.28.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

49.2.0

### What happened?

Added namespaces to monitor in the helm values, added a servicemonitor in cert-manager namespace, the servicemonitor does not appear in prometheus. The other namespaces work properly.

### What you expected to happen?

I would expect the servicemonitor to appear in prometheus

### How to reproduce it?

Install the prometheus-stack chart and the cert-manager chart with servicemonitor enabled.

### Enter the changed values of values.yaml?

See description

### Enter the command that you execute and failing/misfunctioning.

Helm install for both prometheus-stack and cert-manager
