### ISSUE TITLE
[prometheus-mysql-exporter] Add support for multiple target 

### ISSUE THREAD

**Issue by Remy-Mollandin-SK5** [prometheus-community/helm-charts#3750]
### Is your feature request related to a problem ?

mysqld_exporter support multiple target since the release 0.15.0. https://github.com/prometheus/mysqld_exporter/releases/tag/v0.15.0 

The implementation use a new route named `/probe` and credentials for each target are managed in the config file `config.cnf`. The current chart doesn't allow serviceMonitor path overide or adding params.

### Describe the solution you'd like.

An implementation close to prometheus-redis-export would be ideal: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-redis-exporter/values.yaml#L108

```yaml
serviceMonitor:
  # When set true then use a ServiceMonitor to configure scraping
  enabled: false
  multipleTarget: false
  targets: []
  # for every targets, url and name must be set, port is optionnal
  # an individual additionalRelabeling can be set for every target
  # - endpoint: mysql1.dns.local
  #   name: mysql1
  #   port: 3307
  # - endpoint: mysql2.dns.local
  #   name: mysql2
```

The name could be used as key to retrieve the database credentials in `config.cnf`

```
[client.mysql1]
user=mysql1_user
password=mysql1_password
[client.mysql2]
user=mysql2_user
password=mysql2_password
```

### Describe alternatives you've considered.

NONE
