### ISSUE TITLE
[kube-prometheus-stack] url_field can't be used

### ISSUE THREAD

**Issue by Maleware** [prometheus-community/helm-charts#3758]
### Describe the bug a clear and concise description of what the bug is.

Currently if you have something like this:

```
alertmanager:
  config:
    receivers:
    # Currently not working without having "null", known bug at this moment
    - name: "null"
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#my-pretty-channel'
        send_resolved: true
        api_url_file: /etc/alertmanager/secrets/monitoring-secrets/slackwebhook
    - name: 'DeadMansSwitch'
      webhook_configs:
      - send_resolved: false
        url_file: /etc/alertmanager/secrets/monitoring-secrets/hcwebhook

    route:
      receiver: 'slack-notifications'
      group_interval: 1m
      group_wait: 0s
      repeat_interval: 1m
      routes:
      - receiver: 'DeadMansSwitch'
        matchers:
          - severity="DeadMansSwitch"

  alertmanagerSpec:
    secrets:
      - monitoring-secrets
```

the url_filed file can't be resolved with the error message:
`url_file field not available in config.plain`

As far as I know this should be possible as seen in the Alertmanager documentation.

### What's your helm version?

ArgoCD version 47.0.0

### What's your kubectl version?

ArgoCD version 47.0.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.0.0

### What you expected to happen?

I expect url_file working since I want to pull the webhook from a secret as I did with slack.

### How to reproduce it?

Copy the alertmanager config file, create a secret called monitoring-secrets with a field called slackwebhook and hcwebhook and deploy the chart with this configs. 

### Enter the command that you execute and failing/misfunctioning.

since this was managed by ArgoCD not a real command can be provided.
