### ISSUE TITLE
[kube-prometheus-stack]Alertmanager RoutePrefix Configuration Issue in Prometheus Helm Chart

### ISSUE THREAD

**Issue by AichaDevOps** [prometheus-community/helm-charts#3765]
**Issue Description:**

I have deployed Prometheus using Fleet and customized the Helm Chart configuration for different environments. I overridden certain values in the values.yaml file of the Prometheus Helm Chart. Specifically, I changed the value alertmanager.alertmanagerSpec.routePrefix to /alertmanager. 

However, I am encountering an issue where the Alertmanager continues to make HTTP POST requests to an incorrect API endpoint as highlighted in the in the following screenshot.

![Capture d’écran du 2023-09-07 12-21-59](https://github.com/prometheus-community/helm-charts/assets/144331579/603a37bb-97cc-4c4a-9529-83f3e8210ce8)

**Configuration Details:**

Here is my Prometheus global configuration:
```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    prometheus: monitoring/prometheus-default-monitor-prometheus
    prometheus_replica: prometheus-prometheus-default-monitor-prometheus-0
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    path_prefix: /
    timeout: 10s
    api_version: v2
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: prometheus-default-monitor-alertmanager
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: http-web
      replacement: $1
      action: keep
    kubernetes_sd_configs:
    - role: endpoints
      kubeconfig_file: ""
      follow_redirects: true
      enable_http2: true
      namespaces:
        own_namespace: false
        names:
        - monitoring

```

Below is the Helm chart configuration:
```
helm:
  chart: https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-48.0.0/kube-prometheus-stack-48.0.0.tgz
targetCustomizations:
- name: dev
  helm:
    values:
      serviceMonitor:
        enabled: true
      alertmanager:
        alertmanagerSpec:
          routePrefix: /alertmanager
          externalUrl: https://monitoring.**************.com/alertmanager  
        ingress:
          enabled: true
          hosts: [monitoring.dev.*********.com]
          paths: 
            - /alertmanager
          ingressClassName: nginx
          tls:
          - hosts:
            - monitoring.dev.*******.com
            secretName: *********   
      namespaceOverride: monitoring
```

**Symptoms:**

1.    Alertmanager is not displaying any alerts despite the Prometheus configuration.
2.    The routePrefix in the Alertmanager configuration does not seem to take effect, and it still posts to an incorrect API endpoint.

**Issue Details:**

Despite changing the routePrefix to /alertmanager, Alertmanager is still posting to an incorrect API endpoint. I need assistance in identifying and resolving this issue.

I would appreciate any insights or suggestions on how to correct this configuration to ensure that Alertmanager uses the correct route prefix.

Thank you for your help!
