### ISSUE TITLE
[kube-prometheus-stack] Alerts firing randomly

### ISSUE THREAD

**Issue by pausanchezv** [prometheus-community/helm-charts#3794]
### Describe the bug a clear and concise description of what the bug is.

As soon as I deploy the chart, port-forward prometheus and go to the alerts page I notice there are a bunch of alerts firing. Not only is it annoying because nothing is wrong with the cluster but it also keeps sending emails with alerts firing for no reason.

1) Firing randomly
![Screenshot 2023-09-13 at 8 41 07 AM](https://github.com/prometheus-community/helm-charts/assets/16424328/29bcb737-c08f-441c-be8e-9ff86cf6f890)

2) Firing randomly
![Screenshot 2023-09-13 at 8 42 30 AM](https://github.com/prometheus-community/helm-charts/assets/16424328/640bb30f-5e90-4096-afe4-a5b8f3b70a20)

3) Another
![Screenshot 2023-09-13 at 8 43 03 AM](https://github.com/prometheus-community/helm-charts/assets/16424328/8760b1c2-2ead-4294-b60a-5c60fdcd4323)

4) Another
![Screenshot 2023-09-13 at 8 43 29 AM](https://github.com/prometheus-community/helm-charts/assets/16424328/bc374b61-d9de-4841-b6d7-b8f3d7f03e90)

And there's a couple more I'll not add...

Please give me a solution for this as it's super annoying. Thanks.

### What's your helm version?

v3.11.0"

### What's your kubectl version?

Client Version: v1.26.0

### Which chart?

prometheus-kube-stack

### What's the chart version?

latest

### What happened?

As soon as I deploy the chart, port-forward prometheus and go to the alerts page I notice there are a bunch of alerts firing. Not only is it annoying because nothing is wrong with the cluster but it also keeps sending emails with alerts firing for no reason.

1) Firing randomly
![Screenshot 2023-09-13 at 8 41 07 AM](https://github.com/prometheus-community/helm-charts/assets/16424328/29bcb737-c08f-441c-be8e-9ff86cf6f890)

2) Firing randomly
![Screenshot 2023-09-13 at 8 42 30 AM](https://github.com/prometheus-community/helm-charts/assets/16424328/640bb30f-5e90-4096-afe4-a5b8f3b70a20)

3) Another
![Screenshot 2023-09-13 at 8 43 03 AM](https://github.com/prometheus-community/helm-charts/assets/16424328/8760b1c2-2ead-4294-b60a-5c60fdcd4323)

4) Another
![Screenshot 2023-09-13 at 8 43 29 AM](https://github.com/prometheus-community/helm-charts/assets/16424328/bc374b61-d9de-4841-b6d7-b8f3d7f03e90)

And there's a couple more I'll not add...

Please give me a solution for this as it's super annoying. Thanks.

### What you expected to happen?

No alerts firing for no reason. My cluster is new and healthy.

### How to reproduce it?

Deploy the chart and alerts will start firing. It happened to me in two clusters. Exact same alerts firing.

### Enter the changed values of values.yaml?

```
fullnameOverride: prometheus

defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    configReloaders: true
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubelet: true
    kubeProxy: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeScheduler: true
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true

alertmanager:
  fullnameOverride: alertmanager
  enabled: true
  ingress:
    enabled: false

  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: 'email'
      group_by: ['namespace']
      routes:
        - receiver: 'email'
          matchers:
            - alertname =~ "InfoInhibitor|Watchdog"
    receivers:
      - name: 'email'
        email_configs:
          - to: 'xxx@xxx.xxx'
            from: 'xxx@xxx.xxx'
            smarthost: smtp.gmail.com:587
            auth_username: 'xxx@xxx.xxx'
            auth_identity: 'xxx@xxx.xxx'
            auth_password: 'xxx'
            send_resolved: true
          - to: 'xxx@xxx.xxx'
            from: 'xxx@xxx.xxx'
            smarthost: smtp.gmail.com:587
            auth_username: 'xxx@xxx.xxx'
            auth_identity: 'xxx@xxx.xxx'
            auth_password: 'xxx'
            send_resolved: true

grafana:
  enabled: true
  fullnameOverride: grafana
  forceDeployDatasources: false
  forceDeployDashboards: false
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: utc
  serviceMonitor:
    enabled: true
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password

kubeApiServer:
  enabled: true

kubelet:
  enabled: true
  serviceMonitor:
    metricRelabelings:
      - action: replace
        sourceLabels:
          - node
        targetLabel: instance

kubeControllerManager:
  enabled: true

coreDns:
  enabled: true

kubeDns:
  enabled: false

kubeEtcd:
  enabled: true
  service:
    enabled: true
    port: 2381
    targetPort: 2381

kubeScheduler:
  enabled: true

kubeProxy:
  enabled: true

kubeStateMetrics:
  enabled: true

kube-state-metrics:
  fullnameOverride: kube-state-metrics
  selfMonitor:
    enabled: true
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: kubernetes_node

nodeExporter:
  enabled: true
  serviceMonitor:
    relabelings:
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels:
          - __meta_kubernetes_pod_node_name
        targetLabel: kubernetes_node

prometheus-node-exporter:
  fullnameOverride: node-exporter
  podLabels:
    jobLabel: node-exporter
  service:
    portName: http-metrics
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: kubernetes_node
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 2048Mi

prometheusOperator:
  enabled: true
  prometheusConfigReloader:
    resources:
      requests:
        cpu: 200m
        memory: 50Mi
      limits:
        memory: 100Mi

prometheus:
  fullnameOverride: prometheus
  enabled: true
  prometheusSpec:
    replicas: 1
    replicaExternalLabelName: "replica"
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    retention: 5d
    enableAdminAPI: true
    walCompression: true

    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: standard-rwo
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

    additionalScrapeConfigs:
      - job_name: "redis-exporter"
        scrape_interval: 15s
        static_configs:
          - targets: [ 'redis-exporter-prometheus-redis-exporter.monitoring.svc.cluster.local:9121' ]
      - job_name: "postgres-exporter"
        scrape_interval: 15s
        static_configs:
          - targets: [ 'postgres-exporter-prometheus-postgres-exporter.monitoring.svc.cluster.local:80' ]

thanosRuler:
  enabled: false
```

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring -f values-prod.yaml
