### ISSUE TITLE
[kube-prometheus-stack] prometheus-prometheus-prometheus-0 status pending

### ISSUE THREAD

**Issue by MNovruzov** [prometheus-community/helm-charts#3805]
### Describe the bug a clear and concise description of what the bug is.

The chart installation completes successfully even though not all pods are in the Running state.

### What's your helm version?

3.6.3

### What's your kubectl version?

1.24.15

### Which chart?

kube-prometheus-stack

### What's the chart version?

36.2.0

### What happened?

Hello everyone.
I'm sorry if the issue lies with Helm, but I don't quite understand why it's behaving this way.

When installing kube-prometheus-stack using Helm with the atomic flag, if Grafana is not in the Running state, the installation goes into rollback. This is working as expected.

However, if prometheus-prometheus-prometheus-0 is in the pending state, Helm considers everything to be normal, and the installation completes successfully

I've gone through all the documentation, both for Helm and the chart, but unfortunately, I don't understand what I need to write in values.yaml to make the installation wait for the prometheus-prometheus-prometheus-0 pod to reach the Running state.

### What you expected to happen?

I would like the installation to also go into rollback when the prometheus-prometheus-prometheus-0 pod is in the pending state.

### How to reproduce it?

Install the chart on a small node where not all instances can fit.

### Enter the changed values of values.yaml?

```
grafana:
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  adminPassword: "" 
  ingress:
    enabled: true
    hosts:
      - *nda*
    paths:
      - /
    tls:
      - secretName: client-certs
  nodeSelector: {}
  tolerations: []
  persistence:
    enabled: true
    storageClassName: "*nda*"
    accessModes:
    - ReadWriteOnce
    size: 1Gi
  sidecar:
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
      limits:
        cpu: 200m
        memory: 128Mi
    image:
      repository: "*nda*"
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /var/lib/grafana/dashboards
  initChownData:
    resources:
      limits:
        cpu: 50m
        memory: 32Mi
    image:
      repository: "*nda*"
  image:
    repository: "*nda*"
  deploymentStrategy:
    type: Recreate

prometheus:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        location /metrics {
          deny all;
          return 403;
        }
    hosts:
      - *nda*
    paths:
      - /
    tls:
      - secretName: client-certs
  additionalServiceMonitors:
  - name: prometheus-calico
    selector:
      matchLabels:
        k8s-app: calico-node
    namespaceSelector:
      matchNames:
      - kube-system
    endpoints:
    - port: metrics
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    secrets:
    - client-certs
    image:
      repository: "*nda*"
    retention: "14d"
    nodeSelector: {}
    tolerations: []
    resources:
      requests:
        cpu: 250m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 2000Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "*nda*"
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

```

### Enter the command that you execute and failing/misfunctioning.

    helm upgrade -i -n prometheus-monitoring kube-prometheus-stack mcs/kube-prometheus-stack \
      --debug \
      --atomic \
      --timeout=600s \
      --version v36.2.0 \
      --values values.yaml
