### ISSUE TITLE
[kube-prometheus-stack] Do not set Default Resource Requests and Limits for Prometheus Config Reloader

### ISSUE THREAD

**Issue by mmianl** [prometheus-community/helm-charts#3812]
### Is your feature request related to a problem ?

At the moment, it's not possible to unset resource requests and/or limits because the default values file specifies these values:
```yaml
prometheusConfigReloader:
  resources:
      requests:
        cpu: 200m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 50Mi
```
The other components in the chart do not specify any default resources which makes sense because it leaves the user with the option to not set cpu and memory requests and limits which is preferred by some users (especially regarding cpu limits).

### Describe the solution you'd like.

Remove the default Prometheus Config Reloader resources.

### Describe alternatives you've considered.

NONE
