### ISSUE TITLE
[alertmanager] cannot use default ingressClass

### ISSUE THREAD

**Issue by jmnote** [prometheus-community/helm-charts#3823]
### Describe the bug a clear and concise description of what the bug is.

Default ingressClass cannot be used in ingress for alertmanager.

### What's your helm version?

version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.17.13"}

### What's your kubectl version?

Client Version: v1.28.2 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.25.10-gke.2700

### Which chart?

alertmanager

### What's the chart version?

1.6.0

### What happened?

values.yaml
```yaml
prometheus:
  alertmanager:
    ingress:
      enabled: true
      hosts:
      - host: alertmanager.example.com
        paths:
        - path: /
          pathType: ImplementationSpecific
  server:
    ingress:
      enabled: true
      hosts: ["prometheus.example.com"]
```

The CLASS for my-alertmanager is displayed as <none>.

```console
$ kubectl get ing
NAME                   CLASS    HOSTS                        ADDRESS     PORTS     AGE
my-alertmanager        <none>   alertmanager.example.com     10.0.2.55   80, 443   3h2m
my-prometheus-server   class1   prometheus.example.com       10.0.2.55   80, 443   3h2m
```
class1 is default ingressClass.

### How to reproduce it?

```bash
cat <<EOF > values.yaml
alertmanager:
  ingress:
    enabled: true
    hosts:
    - host: alertmanager.example.com
      paths:
      - path: /
        pathType: ImplementationSpecific
server:
  ingress:
    enabled: true
    hosts: ["prometheus.example.com"]
EOF

helm pull prometheus-community/prometheus --version=24.5.0

helm template my prometheus-24.5.0.tgz -f values.yaml | grep 'kind: Ingress' -A14
```
```yaml
--
kind: Ingress
metadata:
  name: my-alertmanager
  labels:
    helm.sh/chart: alertmanager-1.6.0
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: my
    app.kubernetes.io/version: "v0.26.0"
    app.kubernetes.io/managed-by: Helm
  namespace: default
spec:
  ingressClassName:      ################ HERE
  rules:
    - host: "alertmanager.example.com"
      http:
--
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: my
    app.kubernetes.io/version: v2.47.0
    helm.sh/chart: prometheus-24.5.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: prometheus
  name: my-prometheus-server
  namespace: default
spec:
  rules:
    - host: prometheus.example.com
```

For the ingressClassName field, an empty string is not sufficient to use the default ingressClass. It should be omitted.

### Enter the changed values of values.yaml?

→ How to reproduce it?

### Enter the command that you execute and failing/misfunctioning.

→ How to reproduce it?

### Anything else we need to know?

alertmanager ingress
https://github.com/prometheus-community/helm-charts/blob/alertmanager-1.6.0/charts/alertmanager/templates/ingress.yaml#L15-L17
```
spec:
  ingressClassName: {{ .Values.ingress.className }}
```

prometheus ingress
https://github.com/prometheus-community/helm-charts/blob/alertmanager-1.6.0/charts/prometheus/templates/ingress.yaml
```
spec:
  {{- if and $ingressSupportsIngressClassName .Values.server.ingress.ingressClassName }}
  ingressClassName: {{ .Values.server.ingress.ingressClassName }}
  {{- end }}
```
