### ISSUE TITLE
[kube-prometheus-stack] Agent mode doesn't allow to specify role_arn and queue_config in remoteWrite config.

### ISSUE THREAD

**Issue by juanchovelezpro** [prometheus-community/helm-charts#3829]
### Describe the bug a clear and concise description of what the bug is.

Hi, I'm deploying the helm chart enabling prometheus agentMode, I want to push metrics to a centralized Amazon Managed Prometheus Workspace from multiple accounts. I want to specify which role it should assume to be able to push metrics to the AMP workspace, but it seems that the helm chart is not allowing to specify the role_arn in remoteWrite.sigv4 and also does not recognize the queue_config field in remoteWrite.

### What's your helm version?

Using Flux CD to sync 

### What's your kubectl version?

Using Flux CD to sync

### Which chart?

kube-prometheus-stack

### What's the chart version?

51.2.0

### What happened?

When I try to specify "role_arn" I get the following error:

![image](https://github.com/prometheus-community/helm-charts/assets/38393696/e320ee8b-d7d4-433a-a0f5-a1780fa52f86)

Also as you can see, it is saying that queue_config is an unknown field too (I supposed this was working on 51.0.3 but when I saw the YAML for PrometheusAgent object I have 
![image](https://github.com/prometheus-community/helm-charts/assets/38393696/b0776644-9baa-4e4d-bf7f-77c2887dd7f2)
)

### What you expected to happen?

Deploy the helm chart specifying the "queue_config" in remoteWrite and "role_arn" in remoteWrite.sigv4, to be able to push metrics to AMP using a role_arn to assume in a different account.

### How to reproduce it?

Installing the helm chart with values provided.

### Enter the changed values of values.yaml?

```yaml
alertmanager:
  enabled: false
grafana:
  enabled: false
kubeApiServer:
  enabled: false
kubeEtcd:
  enabled: false
prometheus:
  agentMode: true
  ingress:
    enabled: true
    hosts:
    - prometheus.mydomain.com
    ingressClassName: nginx-dev
  prometheusSpec:
    externalLabels:
      cluster: my-cluster
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    priorityClassName: system-cluster-critical
    remoteWrite:
    - queue_config:
        capacity: 2500
        max_samples_per_send: 1000
        max_shards: 200
      sigv4:
        region: us-east-1
        role_arn: my-role-arn
      url: https://myworkspace-url/api/v1/remote_write
    scrapeInterval: 30s
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
  serviceAccount:
    create: false
    name: amp-ingester
prometheus-node-exporter:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: eks.amazonaws.com/compute-type
            operator: NotIn
            values:
            - fargate
```

### Enter the command that you execute and failing/misfunctioning.

Using fluxcd to sync.

**Comment by juanchovelezpro** [comment]
I provided the wrong values. These are the values:

```yaml
alertmanager:
  enabled: false
grafana:
  enabled: false
kubeApiServer:
  enabled: false
kubeEtcd:
  enabled: false
prometheus:
  agentMode: true
  ingress:
    enabled: true
    hosts:
    - prometheus.mydomain.com
    ingressClassName: nginx-dev
  prometheusSpec:
    externalLabels:
      cluster: my-cluster
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    priorityClassName: system-cluster-critical
    remoteWrite:
    - queue_config:
        capacity: 2500
        max_samples_per_send: 1000
        max_shards: 200
      sigv4:
        region: us-east-1
        role_arn: my-role-arn
      url: https://myworkspace-url/api/v1/remote_write
    scrapeInterval: 30s
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
  serviceAccount:
    create: false
    name: amp-ingester
prometheus-node-exporter:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: eks.amazonaws.com/compute-type
            operator: NotIn
            values:
            - fargate

```
