### ISSUE TITLE
[prometheus] `prometheus-node-exporter.enable: false` is only partially working. There's daemon and service deployed regardless of it being disabled 

### ISSUE THREAD

**Issue by pixelsoccupied** [prometheus-community/helm-charts#3842]
### Describe the bug a clear and concise description of what the bug is.

Hello,  I needed simple prometheus deployment without any of the subchart.  
```
alertmanager:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enable: false
prometheus-pushgateway:
  enabled: false
```

But for some reason node-exporter's service and daemonset is always included. 

### What's your helm version?

v3.12.3

### What's your kubectl version?

v1.28.0

### Which chart?

prometheus

### What's the chart version?

25.0.0

### What you expected to happen?

Nothing from node-exporter chart should be in the deployment (just like the other subcharts)

### Enter the changed values of values.yaml?

```
alertmanager:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enable: false
prometheus-pushgateway:
  enabled: false
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade -f values.yaml lab prometheus-community/prometheus --install  --debug
