### ISSUE TITLE
[grafana] Extra volumemounts are being mounted by an emptyDir instead of the secret/configMap

### ISSUE THREAD

**Issue by droslean** [prometheus-community/helm-charts#3851]
### Describe the bug a clear and concise description of what the bug is.

values.yaml
```yaml
grafana:
  extraConfigmaps:
    - grafana-datasources
    - grafana-dashboard

  extraSecrets:
    - grafana-contact-points

  extraVolumeMounts:
    - name: grafana-datasources
      mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
      subPath: datasources.yaml
      readOnly: true
    - name: grafana-contact-points
      mountPath: /etc/grafana/provisioning/notifiers/contact-points.yaml
      subPath: contact-points.yaml
      readOnly: true

  extraVolumes:
    - name: grafana-datasources
      configMap:
        name: grafana-datasources
    - name: grafana-contact-points
      secret:
        secretName: grafana-contact-points
```

pod volumeMounts
```yaml
    - mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
      name: grafana-datasources
      readOnly: true
      subPath: datasources.yaml
    - mountPath: /etc/grafana/provisioning/notifiers/contact-points.yaml
      name: grafana-contact-points
      readOnly: true
      subPath: contact-points.yaml
```

pod volumes
```yaml
  volumes:
....
  - emptyDir: {}
    name: grafana-datasources
  - emptyDir: {}
    name: grafana-contact-points
.....
```

Also, grafana is failing because of:

```console
logger=provisioning t=2023-10-02T11:41:29.650485606Z level=error msg="Failed to provision data sources" error="Datasource provisioning error: read /etc/grafana/provisioning/datasources/datasources.yaml: is a directory"
Error: ✗ not healthy, 0 terminated, 1 failed: [invalid service state: Failed, expected: Running, failure: Datasource provisioning error: read /etc/grafana/provisioning/datasources/datasources.yaml: is a directory]

```

### What's your helm version?

version.BuildInfo{Version:"v3.11", GitCommit:"", GitTreeState:"", GoVersion:"go1.20.1"}

### What's your kubectl version?

v1.27.4

### Which chart?

prometheus-community/kube-prometheus-stack

### What's the chart version?

kube-prometheus-stack-51.2.0

### Enter the command that you execute and failing/misfunctioning.

helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack -f values.yaml -n monitoring
