### ISSUE TITLE
[prometheus-operator-crd] Enable or disable some CRDs

### ISSUE THREAD

**Issue by achetronic** [prometheus-community/helm-charts#3860]
### Is your feature request related to a problem ?

Some other collectors, such as Grafana Agent or OpenTelemetry Collector commonly are able to use ServiceMonitor, PodMonitor and PrometheusRule CRs, but not the rest of them

### Describe the solution you'd like.

It would be great if we could select which to deploy or not, like this:

```yaml
  crds:
    podMonitor:
      enable: false
    serviceMonitor:
      enable: false
    prometheusRule:
      enable: false
```

### Describe alternatives you've considered.

The other alternative is to create a meta-chart with some of the CRDs included. The problem of this solution is more or less the same, as if you have several environments, you probably want to disable PrometheusRule CR in other environments that is not the main one having the metrics DB. For example, when you use Mimir, in order to upload Prometheus rules without exposing the Ruler (to send rules over internet through the Mimir Ruler API, which is increasing the attack surface)
