### ISSUE TITLE
[kube-prometheus-stack] Chart Installation Failure Since 10/05

### ISSUE THREAD

**Issue by nitinjagjivan** [prometheus-community/helm-charts#3866]
### Describe the bug a clear and concise description of what the bug is.

prometheus-kube-stack installation was working till 10/04. It started failing from yesterday.
Command that we run for installation:

`helm upgrade --namespace monitoring prom-operator --set prometheus.service.nodePort=30009 --set grafana.service.type=NodePort --set grafana.adminPassword=xxxxxx  --set grafana.service.nodePort=31111 --set grafana."grafana.ini".server.domain=xx.xx.xxx-xxx.com --set grafana."grafana.ini".server.root_url=http://xxx.xxx.xxx-xxx.com/grafana/ --set grafana."grafana.ini".server.serve_from_sub_path=true --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false -i prometheus-community/kube-prometheus-stack -f grafana-nginx.yml`

grafana-nginx.yml file:
```

grafana:
  ## Configure grafana dashboard providers
  ## ref: http://docs.grafana.org/administration/provisioning/#dashboards
  ##
  ## `path` must be /var/lib/grafana/dashboards/<provider_name>
  ##
  dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'extra'
       orgId: 1
       folder: 'Extra'
       type: file
       disableDeletion: true
       editable: true
       options:
         path: /var/lib/grafana/dashboards/extra

  ## Configure grafana dashboard to import
  ## NOTE: To use dashboards you must also enable/configure dashboardProviders
  ## ref: https://grafana.com/dashboards
  ##
  ## dashboards per provider, use provider name as key.
  ##
  dashboards:
   extra:
     nginx-ingress:
       gnetId: 9614
       datasource: Prometheus
     nginx-ingress-stats:
       gnetId: 10690
       datasource: Prometheus
     jvm-dashboard:
       gnetId: 10519
       datasource: Prometheus
     node-exporter-dashboard:
       gnetId: 12486
       datasource: Prometheus
     OracleDB Monitoring performance and table space stats:
       gnetId: 13555
       datasource: Prometheus
```

### What's your helm version?

3.11.3

### What's your kubectl version?

1.27

### Which chart?

prometheus-kube-stack

### What's the chart version?

latest

### What happened?

**Error:**
Release "prom-operator" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: unable to decode "": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.labels of type string

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --namespace monitoring prom-operator --set prometheus.service.nodePort=30009 --set grafana.service.type=NodePort --set grafana.adminPassword=xxxxxx  --set grafana.service.nodePort=31111 --set grafana."grafana.ini".server.domain=xx.xx.xxx-xxx.com --set grafana."grafana.ini".server.root_url=http://xxx.xxx.xxx-xxx.com/grafana/ --set grafana."grafana.ini".server.serve_from_sub_path=true --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false -i prometheus-community/kube-prometheus-stack -f grafana-nginx.yml

**Comment by larivierec** [comment]
Same thing for me, I was thinking it was my setup

**Comment by SnGmng** [comment]
I get the same error when trying to upgrade to `51.3.0` from verson `51.2.0` of kube-prometheus-stack

This is the error:
`Helm upgrade failed: unable to decode "": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.labels of type string`

This is my values.yaml:
```yaml
grafana:
  grafana.ini:
    server:
      domain: grafana.${host}
    security:
      allow_embedding: true
      cookie_samesite: none
      cookie_secure: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      istio-mesh:
        gnetId: 7639
      istio-service:
        gnetId: 7636
      istio-workload:
        gnetId: 7630
      istio-performance:
        gnetId: 11829
      istio-controlplane:
        gnetId: 7645

prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    
prometheusOperator:
  admissionWebhooks: 
    certManager: 
      enabled: true
```

Helm upgrade logs (using flux helmcontroller):
```
Status:
  Conditions:
    Last Transition Time:  2023-10-06T11:12:00Z
    Message:               Helm upgrade failed: unable to decode "": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.labels of type string
    Reason:                UpgradeFailed
    Status:                False
    Type:                  Ready
    Last Transition Time:  2023-10-06T11:12:00Z
    Message:               Helm upgrade failed: unable to decode "": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.labels of type string

Last Helm logs:

preparing upgrade for kube-prometheus-stack
resetting values to the chart's original version
    Reason:                        UpgradeFailed
    Status:                        False
    Type:                          Released
  Failures:                        1
  Helm Chart:                      monitoring/monitoring-kube-prometheus-stack
  Last Applied Revision:           51.2.0
  Last Attempted Revision:         51.3.0
  Last Attempted Values Checksum:  e005cd67c32c2bc1722456c6d3220a46fa913528
  Observed Generation:             1
  Upgrade Failures:                1
Events:
  Type     Reason  Age                   From             Message
  ----     ------  ----                  ----             -------
  Normal   info    4m48s (x74 over 14d)  helm-controller  Helm upgrade has started
  Warning  error   4m44s (x71 over 15h)  helm-controller  Helm upgrade failed: unable to decode "": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.labels of type string

Last Helm logs:

preparing upgrade for kube-prometheus-stack
resetting values to the chart's original version
  Warning  error  4m44s (x71 over 15h)  helm-controller  reconciliation failed: Helm upgrade failed: unable to decode "": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.labels of type string
```
