### ISSUE TITLE
[alertmanager] Service port and targetPort are confused

### ISSUE THREAD

**Issue by zerkms** [prometheus-community/helm-charts#3874]
### Describe the bug a clear and concise description of what the bug is.

They are currently defined as:

https://github.com/prometheus-community/helm-charts/blob/f57ff6651817b23c21daa7d5cd087649add5836e/charts/alertmanager/templates/services.yaml#L27-L28

which renders to

```yaml
  ports:
  - name: http
    port: 9093
    protocol: TCP
    targetPort: http
```

while it should be the other way around: port 80 (http), and target port 9093

### What's your helm version?

version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.3"}

### What's your kubectl version?

Client Version: v1.28.2

### Which chart?

alertmanager

### What's the chart version?

1.7.0

### Enter the command that you execute and failing/misfunctioning.

n/a

**Comment by Meet-S0ni** [comment]
The `targetPort` in the template service is correctly set to "http" to match the specified target port in the actual service.

```
   ```yaml
   spec:
     clusterIP: None
     ports:
       - port: {{ .Values.service.port }}
         targetPort: http
         protocol: TCP
         name: http
```
The actual service is configured with the correct "http" target port.
```
ports:
  - name: http
    port: 9093
    protocol: TCP
    targetPort: http
```
The port and clusterPort in values.yaml of alertmanager are set to the desired values (in this case, 9093).
```
service:
  annotations: {}
  labels: {}
  type: ClusterIP
  port: 9093
  clusterPort: 9094
  loadBalancerIP: ""  # Assign ext IP when Service type is LoadBalancer
  loadBalancerSourceRanges: []  # Only allow access to loadBalancerIP from these IPs
```
