### ISSUE TITLE
[kube-prometheus-stack] missing ec2SDConfigs in the ScrapeConfig

### ISSUE THREAD

**Issue by mzupan** [prometheus-community/helm-charts#3895]
### Describe the bug a clear and concise description of what the bug is.

Trying to lint a scrapeconfig but it's missing from the CRD defination

```
ScrapeConfig prometheus-scrapeconfig-db is invalid: For field spec: Additional property ec2SDConfigs is not allowed
```

```
➜  ~ grep ec2SDConfigs monitoring.coreos.com_scrapeconfigs.yaml
➜  ~
```

Trying this

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  labels:
    prometheus: kube-prometheus-prometheus
    role: scrape-config
  name: prometheus-scrapeconfig-db
spec:  
  metricsPath: /_metrics
  scheme: HTTPS
  tlsConfig:
    insecureSkipVerify: true
  ec2SDConfigs:
    region: us-west-2
    port: 443
    filters:
      - name: tag:Service
        values:
          - db

```

### What's your helm version?

v3.12.1

### What's your kubectl version?

v1.27.3

### Which chart?

prometheus-kube-stack

### What's the chart version?

51.0.0

### Enter the command that you execute and failing/misfunctioning.

uses kubeconform
