### ISSUE TITLE
Prometheus federation labels not propagating

### ISSUE THREAD

**Issue by KR411-prog** [prometheus-community/helm-charts#392]
I am facing issue in propagating labels in Prometheus Federation..

I have my EKS cluster without any external labels in it and it has Prometheus enabled,Alertmanager disabled.

In the EKS Federation cluster, I have Prometheus enabled,Alertmanager enabled.
Here is the config in the EKS Federation cluster
```
  prometheusSpec:
    resources: {}
    storageSpec: {}
    externalLabels:
      federation_datacenter: aws_us-east-1
      federation_cluster: mon
      federation_environment: global
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
    - job_name: federation
      metrics_path: /federate
      scrape_interval: 60s
      scrape_timeout: 55s
      honor_labels: true
      params:
        'match[]':
          - "{__name__ =~ '^.+'}"
      static_configs:
        - targets: 
            - '{{ssm: /cluster/mon/prometheus/vpc_endpoint_sandbox}}'
          labels:
            cluster: 'cluster-sandbox'
            datacenter: 'aws_us-east-1'
            environment: 'sandbox'
        - targets: 
            - '{{ssm: /cluster/mon/prometheus/vpc_endpoint_qa}}'
          labels:
            cluster: 'cluster-qa'
            datacenter: 'aws_us-east-1'
            environment: 'qa'
      metric_relabel_configs:
        # We should remove all 'record' metrics, because our Prometheus will calculate them by
        # record metrics always contain semicolon in name
        - source_labels: ['__name__']
          regex: '.*:.*'
          action: 'drop'
        - source_labels: ['__name__','name']
          regex: 'node_systemd_unit_state;dev-.*'
          action: 'drop'
```
Even though the labels are set in static_configs, the labels are not propagated when the alerts sent to OpsGenie.
I dont find cluster,datacenter,environment labels in the alert received.
I have set honor_labels: true. I am not sure what I am missing here.Any help on this?

<img width="669" alt="image" src="https://user-images.githubusercontent.com/14121261/99613441-cdf31e80-29d4-11eb-9bc4-cc198fbd1461.png">
