### ISSUE TITLE
[kube-prometheus-stack] additionalDataSources reference password from provided Secret

### ISSUE THREAD

**Issue by teceP** [prometheus-community/helm-charts#3928]
### Is your feature request related to a problem ?

Since we do not want to push our plain text passwords to a git repository, we use SealedSecrets.

I know about the secureJsonData, but for my understanging we would still push it in plain text to a repository and grafana will encrypt it when placing it into the container. 

### Describe the solution you'd like.

The solution for this would be same as we do it for the grafana admin password, referencing it from a provided secret(-name).

Like this:
```yaml
grafana:
  admin:
    existingSecret: granafa-envs
    userKey: admin-user
    passwordKey: admin-password
```

But for every additional datasource, something like this:
```yaml
grafana:
   sidecar:
     dashboards:
        additionalDataSources:
          - name: MariaDB
            basicAuth: true
            url: http://mariadb.differentnamespace:3306
            database: mariadbname
            existingSecret: mariadb-envs
            userKey: user
            passwordKey: password
```

### Describe alternatives you've considered.

NONE
