### ISSUE TITLE
[kube-prometheus-stack] Missing msteamsConfigs in the alertmanagerconfigs crd

### ISSUE THREAD

**Issue by vibin18** [prometheus-community/helm-charts#3933]
### Describe the bug a clear and concise description of what the bug is.

Error thrown while applying the configuration : 
```AlertmanagerConfig in version "v1alpha1" cannot be handled as a AlertmanagerConfig: strict decoding error: unknown field "spec.receivers[0].msteamsConfigs"```

Msteams ```msteamsConfigs``` are missing in the alertmanagerconfigs CRD : [charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml](url)

### What's your helm version?

v3.13.0

### What's your kubectl version?

v1.28.2

### Which chart?

prometheus-operator

### What's the chart version?

0.68.0

### What happened?

Integrate MSteams with ```Prometheus Alertmanager 0.26```  as documented here :- [https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1beta1.MSTeamsConfig](url)
 
AlertmanagerConfigSpec
```
receivers:
  - name: 'warning'
    msteamsConfigs:
    - sendResolved: true
      webhookUrl:
        credentials:
          name: example
          key: WEBHOOK_URL

```

Error thrown while applying the configuration : 
```AlertmanagerConfig in version "v1alpha1" cannot be handled as a AlertmanagerConfig: strict decoding error: unknown field "spec.receivers[0].msteamsConfigs"```

### Enter the command that you execute and failing/misfunctioning.

kubectl  -n example  create -f prom-msteams-example.yaml

AlertmanagerConfigSpec
```
receivers:
  - name: 'warning'
    msteamsConfigs:
    - sendResolved: true
      webhookUrl:
        credentials:
          name: example
          key: WEBHOOK_URL

```

**Comment by SergkeiM** [comment]
Hi @vibin18 I think is the same issue as #3724 or at least related.

**Comment by toredash** [comment]
I think this can be closed @vibin18

**Comment by skoenig** [comment]
Can confirm that the issue is solved in kube-prometheus-stack 70.3.0 / prometheus-operator v0.81.0 / alertmanager v0.28.1

This is a valid alertmanager config object:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  annotations:
  name: example-config
  namespace: monitoring
spec:
  receivers:
    - msteamsConfigs:
      - sendResolved: true
        text: '{{ template "msteams.webhook.default.text" . }}'
        title: '{{ template "msteams.default.title" . }}'
        webhookUrl:
          key: MSTeams_WEBHOOK_URL_DEFAULT
          name: alertmanager-secrets
      name: example-receiver
  route:
    matchers:
    - matchType: =
      name: namespace
      value: monitoring
    receiver: example-receiver
```
