### ISSUE TITLE
[prometheus-snmp-exporter] SNMPv3 auth

### ISSUE THREAD

**Issue by iPenguin** [prometheus-community/helm-charts#3940]
### Describe the bug a clear and concise description of what the bug is.

Hi,

I'm trying to get the SNMP Exporter to deliver metrics to Prometheus with SNMPv3 auth turned on. I am able to see data when I bring up https://snmp-exporter.milco.info/snmp?target=192.168.100.5&module=apcups&auth=snmpv3

However when I open Prometheus and check the Target Status it shows as down and the URL that Prometheus is checking is missing the `auth` parameter.

The relevant bits from the helm chart values.yaml file are below. My expectation is that the `auth` section in the params would be passed to Prometheus like the `module` and `target` and that it would be added to the url so that Prometheus can get the data. This is guess work on my part as I haven't been able to find much documentation around using the new configuration format for `auths`.

Any help is much appreciated.

Thanks,
Brian

### What's your helm version?

v3.12.1

### What's your kubectl version?

v1.28.2

### Which chart?

prometheus-snmp-exporter

### What's the chart version?

1.8.1

### What happened?

Prometheus returns the error: 

server returned HTTP status 400 Bad Request

### What you expected to happen?

Prometheus to show status up and collect the data from the exporter

### How to reproduce it?

`helm upgrade --install -n monitoring snmp-exporter prometheus-community/prometheus-snmp-exporter --version 1.8.1 -f ~/projects/prometheus/snmp.yaml`

Open: https://prom-admin.milco.info/prometheus/targets
find the snmp entries and view the status.

### Enter the changed values of values.yaml?

```
image:
  tag: "v0.24.1"

serviceMonitor:
  params:
    - name: apc-pdu-0
      target: 192.168.100.5
      auth:
        - snmpv3
      module:
        - apcups

config: |-
  auths:
    snmpv3:
      version: 3
      security_level: authPriv
      auth_protocol: SHA
      username: snmp_user
      password: auth_password
      priv_protocol: AES
      priv_password: priv_password
  modules:
    apcups:
      walk:
      - 1.3.6.1.4.1.318.1.1.1.12
      - 1.3.6.1.4.1.318.1.1.1.2
      - 1.3.6.1.4.1.318.1.1.1.3
      - 1.3.6.1.4.1.318.1.1.1.4
      [cut for brevity]
```

### Enter the command that you execute and failing/misfunctioning.

`helm upgrade --install -n monitoring snmp-exporter prometheus-community/prometheus-snmp-exporter --version 1.8.1 -f ~/projects/prometheus/snmp.yaml`
