### ISSUE TITLE
[kube-prometheus-stack] Custom rules are not applied via additionalPrometheusRulesMap

### ISSUE THREAD

**Issue by ratkokorlevski** [prometheus-community/helm-charts#3968]
### Describe the bug a clear and concise description of what the bug is.

I am trying to create some custom rule and also disable KubeSchedulerDown since is happening all the time (I am not sure if this is actual alarm since the EKS cluster is running without any errors).

I have spend few days and can't achieve these rules to be applied

Everything is deployed via Helm + Terraform

This is the setup of the helm chart:

```
resource "helm_release" "kube-prometheus-stack" {
  name       = "kube-prometheus-stack"
  repository = "https://prometheus-community.github.io/helm-charts"
  chart      = "kube-prometheus-stack"
  version    = "48.3.1"
  namespace  = "monitoring"
  values = [
    file("./helm-values/prometheus.yaml"),
    file("./helm-values/alertmanager.yaml"),
    file("./helm-values/grafana.yaml")
  ]


  set {
    name  = "grafana.adminPassword"
    value = data.aws_ssm_parameter.grafana-admin-password.value
  }
}
```

As for the prometheus values yml file:
```
prometheus:
  enabled: "true"
  annotations:
    prometheus.io/scrape: "true"
  defaultRules:
    create: true
    rules:
      alertmanager: true
      etcd: true
      configReloaders: true
      general: true
      k8s: true
      kubeApiserverAvailability: true
      kubeApiserverBurnrate: true
      kubeApiserverHistogram: true
      kubeApiserverSlos: true
      kubeControllerManager: false
      kubelet: false
      kubeProxy: true
      kubePrometheusGeneral: true
      kubePrometheusNodeRecording: true
      kubernetesApps: true
      kubernetesResources: true
      kubernetesStorage: true
      kubernetesSystem: true
      kubeSchedulerAlerting: false
      kubeSchedulerRecording: false
      kubeScheduler: false
      kubeStateMetrics: true
      network: true
      node: true
      nodeExporterAlerting: true
      nodeExporterRecording: true
      prometheus: true
      prometheusOperator: true
      windows: true
  kubeControllerManager:
    enabled: false

  ingress:
    enabled: "true"
    hosts:
      - "prometheus.test.com"
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"

    tls:
      - secretName: "prometheus-tls"
        hosts:
          - "prometheus.test.com"
  disabled:
    KubeSchedulerDown: true  

  additionalPrometheusRulesMap:
    prometheus.rules:
      groups:
        - name: custom-rules
          rules:
            - alert: PodContainerOOMKilled
              annotations:
                description: 'Container {{ $labels.container }} in pod {{ $labels.exported_namespace }}/{{ $labels.exported_pod }} has been killed as a result of running out of memory (OOMKilled) {{ printf "%.2f" $value }} time(s) in the last 5 minutes.'
                summary: A pod container was OOMKilled
              expr: rate(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[5m]) * 60 * 5 > 0
              for: 5m
              labels:
                severity: warning
            - alert: PodContainerOOMKilledRate
              annotations:
                description: 'Container {{ $labels.container }} in pod {{ $labels.exported_namespace }}/{{ $labels.exported_pod }} has been killed as a result of running out of memory (OOMKilled) {{ printf "%.2f" $value }} time(s) in the last 60 minutes.'
                summary: A pod container was OOMKilled
              expr: kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 60m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[60m]) > 0
              labels:
                severity: warning
            - alert: NodeDiskPressure
              annotations:
                description: "{{ $labels.node }} - DiskPressure condition is true"
                summary: Node disk pressure on instance {{ $labels.instance }}
              expr: kube_node_status_condition{condition="DiskPressure", status="true"} > 0
              for: 5m
              labels:
                severity: warning
            - alert: NodeOutOfDisk
              annotations:
                description: "{{ $labels.node }} - OutOfDisk condition is true"
                summary: Node out of disk on instance {{ $labels.instance }}
              expr: kube_node_status_condition{condition="OutOfDisk", status="true"} > 0
              for: 5m
              labels:
                severity: critical
            - alert: NodeMemoryPressure
              annotations:
                description: "{{ $labels.node }} - MemoryPressure condition is true"
                summary: Node memory pressure on instance {{ $labels.instance }}
              expr: kube_node_status_condition{condition="MemoryPressure", status="true"} > 0
              for: 5m
              labels:
                severity: warning
            - alert: NodePIDPressure
              annotations:
                description: "{{ $labels.node }} - PIDPressure condition is true"
                summary: Node PID pressure on instance {{ $labels.instance }}
              expr: kube_node_status_condition{condition="PIDPressure", status="true"} > 0
              for: 5m
              labels:
                severity: warning
            - alert: NodeNotReady
              annotations:
                description: "{{ $labels.node }} - Ready condition is false"
                summary: Node Not Ready (instance {{ $labels.instance }})
              expr: kube_node_status_condition{condition="Ready", status="false"} > 0
              for: 5m
              labels:
                severity: warning
            - alert: NodeCountHigh
              annotations:
                summary: The number of nodes ({{ $value }}) is over the desired upper limit
              expr: count(kube_node_info) > 10
              for: 1h
              labels:
                severity: info
            - alert: NodeCountLow
              annotations:
                summary: The number of nodes ({{ $value }}) is below the desired lower limit
              expr: count(kube_node_info) < 2
              for: 1h
              labels:
                severity: warning
            - alert: NodeMemoryLow
              annotations:
                description: Node memory is filling up and there's {{ $value | printf "%.2f" }}% of memory left
                summary: Node memory low (< 15% left on instance {{ $labels.instance }})
              expr: node_memory_MemAvailable_bytes{job="node-exporter"} /    node_memory_MemTotal_bytes{job="node-exporter"} * 100 < 15
              for: 15m
              labels:
                severity: warning
            - alert: NodeDiskSpaceLow
              annotations:
                description: Node disk is filling up and there's {{ $value |  printf "%.2f" }}% of disk left
                summary: Node disk space low (< 15% left on instance {{ $labels.instance }})
              expr: node_filesystem_free_bytes{job="node-exporter", mountpoint ="/"} / node_filesystem_size_bytes{job="node-exporter",mountpoint="/"} * 100 < 15
              for: 15m
              labels:
                severity: warning
            - alert: NodeCpuLoadHigh
              annotations:
                description: CPU load is at {{ $value | printf "%.2f" }}%
                summary: Node CPU load high (> 90% on instance {{ $labels.    instance }})
              expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total {job="node-exporter",mode="idle"}[5m])) * 100) > 90
              for: 15m
              labels:
                severity: warning
            - alert: NodeUnusualDiskWriteRate
              annotations:
                description: "Disk write rate is at {{ $value }} MB/s"
                summary: "Unusual disk write rate (> 100 MB/s on instance {{  $labels.instance }})"
              expr: sum by (instance) (irate(node_disk_written_bytes_total    {job="node-exporter"}[2m])) / 1024 / 1024 > 100
              for: 15m
              labels:
                severity: warning
            - alert: NodeUnusualDiskReadRate
              annotations:
                description: Disk read rate is at {{ $value }} MB/s
                summary: "Unusual disk read rate (> 100 MB/s on instance {{ $labels.instance }})"
              expr: sum by (instance) (irate(node_disk_read_bytes_total {job="node-exporter"}[2m])) / 1024 / 1024 > 100
              for: 15m
              labels:
                severity: warning
            - alert: NodeUnusualNetworkThroughputIn
              annotations:
                description: Host network interfaces are receiving {{ $value }} MB/s
                summary: "Unusual network receive rate (> 100 MB/s on instance {{ $labels.instance }})"
              expr: sum by (instance) (irate(node_network_receive_bytes_total   {job="node-exporter"}[2m])) / 1024 / 1024 > 100
              for: 15m
              labels:
                severity: warning


```

### What's your helm version?

version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.4"}

### What's your kubectl version?

Client Version: v1.24.0 Kustomize Version: v4.5.4 Server Version: v1.25.14-eks-f8587cb

### Which chart?

kube-prometheus-stack

### What's the chart version?

48.3.1

### What happened?

When trying to add custom rules on top of the default ones , the specified rules were not added. I referred  how to add custom rules in values.yml 

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

Also KubeSchedulerDown is constantly triggering, I tried to mute that as well with the 'disabled' key

### What you expected to happen?

Rules to apply and I can see them in Prometheus UI

KubeSchedulerDown alert to get mutted (I dont know why is always happening in AWS EKS if someone can advise me on that)

### Enter the command that you execute and failing/misfunctioning.

terraform apply
