### ISSUE TITLE
[kube-prometheus-stack] How to find metrics in other namespaces

### ISSUE THREAD

**Issue by hobbesuk** [prometheus-community/helm-charts#3992]
Using 52.1.0 of the kube-prometheus-stack what is the correct way to get metrics running in other namespaces.

I have a windows-exporter running on port 5000 named metrics under a different namespace and I've followed many blogs / guides etc but none seem to have done the trick of getting the metrics collected.

Are there some docs on how to do this? Or a way to debug why its not being picked up.

I have this in my values.yaml but it doesn't seem to be enough to find the endpoint which I'm assuming is because my target is running in a sidecar container in a different namespace to where my prometheus stack is running.

```
  prometheus:
    enabled: true

    additionalServiceMonitors:
    - name: "prometheus-windows-pod-exporter-monitor"
      selector:
        matchLabels:
          appType: web
      endpoints:
        - port: "metrics"
```

**Comment by wallchristopher** [comment]
You can try to adding `namespaceSelector` to the service monitor. I had to do this for one of my applications as well.

[Within the kube-promtheus-stack values.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L3628)

[Servicemonitor chart namespace reference](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml#L633)

So the above would be:
```yaml
  prometheus:
    enabled: true

    additionalServiceMonitors:
    - name: "prometheus-windows-pod-exporter-monitor"
      selector:
        matchLabels:
          appType: web
      endpoints:
        - port: "metrics"
      namespaceSelector:
        matchNames:
        - YOURNAMESPACE
```
