### ISSUE TITLE
[prometheus-json-exporter] coalesce.go:160: warning: skipped value for deployment: Not a table.

### ISSUE THREAD

**Issue by ale9412** [prometheus-community/helm-charts#4003]
Given that affinity parameter in values files is set to a list, when trying to overwrite this value on a parent chart it throws the warning `coalesce.go:237: warning: skipped value for prometheus-json-exporter.prometheus-json-exporter.affinity: Not a table.`

```
prometheus-json-exporter:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: "label-key"
            operator: In
            values:
            - "label-value"
```

This parameter should be set to a map:
`affinity: {}`
In order to be able to overwrite it correctly. The same I assume it will happen with nodeSelector

### What's your helm version?

3.13.1

### What's your kubectl version?

1.28.3

### Which chart?

prometheus-json-exporter

### What's the chart version?

0.8.0

### Enter the changed values of values.yaml?

affinity: []

### Enter the command that you execute and failing/misfunctioning.

helm template json-exporter .
