### ISSUE TITLE
[prometheus-blackbox-exporter] `_helpers.tpl` produces invalid yaml

### ISSUE THREAD

**Issue by cruwe** [prometheus-community/helm-charts#4011]
https://github.com/prometheus-community/helm-charts/blob/1ff5e72a287484ae817c234ab2623cb2b2f91eb5/charts/prometheus-blackbox-exporter/templates/_helpers.tpl#L153

First, thanks for developing these helm-charts and providing them to the community.

When rendering `initContainers`,  the deployment gets templated as in
```yaml
      initContainers:  - args:
          - -c
          - cat /etc/ssl/certs/ca-certificates.crt /tls/ca.crt > /tls-processed/ca.crt
          command:
          - /bin/bash
      ....
```

Changing `_helpers.tpl` to 
```
{{- with .Values.extraInitContainers }}
initContainers:
{{ toYaml . | indent 2 }}
{{- end }}
```
fixes the problem.

I'd submit a PR, but somehow I fear I am missing the original intent, so I do not want to contribute to any hassle.

Thanks for your consideration.
