### ISSUE TITLE
[prometheus-kube-stack] Field evolution error when grafana.sidecar.datasources.createPrometheusReplicasDatasources: true and exemplarTraceIdDestinations configured

### ISSUE THREAD

**Issue by wesbrownfavor** [prometheus-community/helm-charts#4027]
### Describe the bug a clear and concise description of what the bug is.

When I try to render helm with

```yaml
grafana:
  sidecar:
    datasources:
      createPrometheusReplicasDatasources: true
      
      exemplarTraceIdDestinations:
          datasourceUid: tempo
          traceIdLabelName: traceID
```

Helm fails trying to evaluate string fields as int

### What's your helm version?

version.BuildInfo{Version:"v3.11.0", GitCommit:"472c5736ab01133de504a826bd9ee12cbe4e7904", GitTreeState:"clean", GoVersion:"go1.19.5"}

### What's your kubectl version?

Client Version: v1.28.3

### Which chart?

kube-prometheus-stack

### What's the chart version?

54.1.0

### What happened?

❯ helm template kube-prometheus-stack . -f values.yaml  --debug                     
install.go:193: [debug] Original chart version: ""

Error: template: kube-prometheus-stack/charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml:54:35: executing "kube-prometheus-stack/charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml" at <.Values.grafana.sidecar.datasources.exemplarTraceIdDestinations.datasourceUid>: can't evaluate field Values in type int
helm.go:84: [debug] template: kube-prometheus-stack/charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml:54:35: executing "kube-prometheus-stack/charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml" at <.Values.grafana.sidecar.datasources.exemplarTraceIdDestinations.datasourceUid>: can't evaluate field Values in type int

### How to reproduce it?

Set the following in your values.yaml

```yaml
grafana:
  sidecar:
    datasources:
      createPrometheusReplicasDatasources: true
      
      exemplarTraceIdDestinations:
          datasourceUid: tempo
          traceIdLabelName: traceID
```

You must have `createPrometheusReplicasDatasources: true` as well as the exemplar values.

### Enter the changed values of values.yaml?

```yaml
grafana:
  sidecar:
    datasources:
      createPrometheusReplicasDatasources: true
      
      exemplarTraceIdDestinations:
          datasourceUid: tempo
          traceIdLabelName: traceID
```

### Enter the command that you execute and failing/misfunctioning.

helm template kube-prometheus-stack . -f values.yaml  --debug

### Anything else we need to know?

This issue is almost the same as this:
https://github.com/prometheus-community/helm-charts/issues/2254

That being said it would appear that fixing this would be as easy as updating lines 58 and 59 in [templates/grafana/configmaps-datasources.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml#L58:L59)

from:
```yaml
        - datasourceUid: {{ .Values.grafana.sidecar.datasources.exemplarTraceIdDestinations.datasourceUid }}
          name: {{ .Values.grafana.sidecar.datasources.exemplarTraceIdDestinations.traceIdLabelName }}
```

to:
```yaml
        - datasourceUid: {{ $.Values.grafana.sidecar.datasources.exemplarTraceIdDestinations.datasourceUid }}
          name: {{ $.Values.grafana.sidecar.datasources.exemplarTraceIdDestinations.traceIdLabelName }}
```
