### ISSUE TITLE
[prometheus-kube-stack] Additional ServiceMonitor not used

### ISSUE THREAD

**Issue by PaulRudin** [prometheus-community/helm-charts#4030]
### Describe the bug a clear and concise description of what the bug is.

Custom serviceMonitor ignored.

### What's your helm version?

version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}

### What's your kubectl version?

Client Version: v1.28.2 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.25.10-gke.2700 WARNING: version difference between client (1.28) and server (1.25) exceeds the supported minor version skew of +/-1

### Which chart?

kube-prometheus-stack

### What's the chart version?

54.1.0

### What happened?

I have created an additional serviceMonitor as follows:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: locust-exporter-http
  labels:
    k8s-apps: http
spec:
  jobLabel: locust
  selector:
    matchExpressions:
    - {key: performance-test-pod-name, operator: Exists}
  namespaceSelector:
    matchNames:
    - locust
  endpoints:
  - port: prometheus-metrics
    interval: 15s
```
and in my values I have:
```
 prometheus:
    prometheusSpec:
      # all serviceMonitors in all namespaces
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
```
When visiting the service-discovery page in the prometheus web UI I don't see anything for this serviceMonitor

### What you expected to happen?

I expected to see this serviceMonitor mentioned.

### How to reproduce it?

Create a seriveMonitor as described above and use the helm chart with the values described.

### Enter the changed values of values.yaml?
```
kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      # all serviceMonitors in all namespaces
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
```

### Enter the command that you execute and failing/misfunctioning.

helm -n locust upgrade locust locust/
where the Chart.yaml includes:
```
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: "54.1.0"
```
### Anything else we need to know?

I'm using kube-prometheus-stack as a subchart - but I don't think that's relevant
