### ISSUE TITLE
[HELP]: SMTP setting clarification 

### ISSUE THREAD

**Issue by mike-pisman** [prometheus-community/helm-charts#4038]
Hi, can someone clarify how to set smtp settings?

I am trying to set up Alertmanager and Grafana notification, but neither is working... I would appreciate if someone could share their values for email setup.

Alertmanager config

```yaml
alertmanager:
  config:
    receivers:
    - name: 'email'
      email_configs:
      - to: 'myemail@mydomain.com'
        from: 'alertmanager@mydomain.com'
        smarthost: 'smtp.purelymail.com:465'
        authUsername: 'myemail'
        authPassword:
          name: smtp-password
          key: password
```

Grafana config

```yaml
grafana:
  grafana.ini:
    smtp:
      enabled: true
      host: smtp.purelymail.com:465
      from_address: "alertmanager@mydomain.com"
      passwordKey: '"""password"""'  # I use tripple quotes, because my password contains '#'
      userKey: "myemail@mydomain.com"
```

Do I miss something?

**Comment by szalaicsabi** [comment]
https://github.com/prometheus-community/helm-charts/issues/1969#issuecomment-1119567241

**Comment by mike-pisman** [comment]
@szalaicsabi, thanks for sharing I have fixed the values, but still get the same error.

I have checked the `grafana.ini` file and I see all the correct values:
```ini
enabled = true
host = smtp.purelymail.com:465
password = """password"""
startTLS = NoStartTLS
user = myemail@mydomain.com
```

Yet, I still get the error `535: Authentication failed`

**Comment by mike-pisman** [comment]
Not sure what changed, but it finally worked.

**Comment by cequencer** [comment]
Hi @mike-pisman ,

I ran into the same issue getting smtp config to work for Grafana as you have originally described.  The password contains special characters like `#`, which requires special extra characters to wrap it.  

I can confirm your grafana.ini works, where it is using single-quote to wrap triple-double-quote around the password was necessary.  

```
grafana:
  grafana.ini:
    smtp:
      enabled: true
      host: smtp.server.com:465
      from_address: "alertmanager@mydomain.com"
      passwordKey: '"""password"""'  # I use tripple quotes, because my password contains '#'
      userKey: "myemail@mydomain.com"
```

Thank you for posting and sharing this thread.

**Comment by giovannicandido** [comment]
Is working but you have to config like that:

```yaml
grafana:
  smtp:
    existingSecret: "grafana-smtp-secret"
    passwordKey: "password"
    userKey: "user"
  grafana.ini:
    smtp:
      enabled: true
      host: host.com:587
      from_address: alerts@example.com
```

By the way, there is a orientation to put tripple quotes if you password has special characters, that is not necessary here.
