### ISSUE TITLE
[prometheus] prometheus to node exporter context deadline exceeded

### ISSUE THREAD

**Issue by vmwarelab** [prometheus-community/helm-charts#4055]
### Describe the bug a clear and concise description of what the bug is.

Get "http://10.244.0.130:9100/metrics": context deadline exceeded    <--- Master node
Get "http://10.244.0.131:9100/metrics": context deadline exceeded   <--- Worker node
Get "http://10.244.0.132:9100/metrics": context deadline exceeded   <--- Worker node
Get "http://10.244.0.133:9100/metrics": context deadline exceeded   <--- Worker node

### What's your helm version?

version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.7-eks-4721010", GitCommit:"b77d9473a02fbfa834afa67d677fd12d690b195f", GitTreeState:"clean", BuildDate:"2022-06-27T22:22:16Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9+vmware.1", GitCommit:"d1d7c19c9b6265a8dcd1b2ab2620ec0fc7cee784", GitTreeState:"clean", BuildDate:"2022-12-14T06:23:39Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-community/prometheus

### What's the chart version?

what ever the latest is

### What happened?

everything is working fine except i see these 4 errors within the kubernetes-service-endpoints (3/7 up) under status -> targets within the Prometheus UI which accessible via a LoadBalancer targeting port 9090

Get "http://10.244.0.130:9100/metrics": context deadline exceeded    <--- Master node
Get "http://10.244.0.131:9100/metrics": context deadline exceeded   <--- Worker node
Get "http://10.244.0.132:9100/metrics": context deadline exceeded   <--- Worker node
Get "http://10.244.0.133:9100/metrics": context deadline exceeded   <--- Worker node

if I inspect the DaemonSet sepc section below.  Are we supposed to pass/configre  a HOST_IP ?  

```
      spec:
        automountServiceAccountToken: false
        containers:
        - args:
          - --path.procfs=/host/proc
          - --path.sysfs=/host/sys
          - --path.rootfs=/host/root
          - --path.udev.data=/host/root/run/udev/data
          - --web.listen-address=[$(HOST_IP)]:9100
```

### What you expected to happen?

kubernetes-service-endpoints (7/7 up)   is what I expecting to see

### How to reproduce it?

Just standard helm deployment  with the addition of 
`kubectl expose service prometheus-server --type=LoadBalancer --target-port=9090 --name=prometheus-server-external`

### Enter the command that you execute and failing/misfunctioning.

nothing failing with the command itself
