### ISSUE TITLE
[kube-state-metrics] Bad ServiceAccount yaml if `serviceAccount.imagePullSecrets` override not provided

### ISSUE THREAD

**Issue by cmontemuino** [prometheus-community/helm-charts#4059]
### Describe the bug a clear and concise description of what the bug is.

ServiceAccount gets rendered with an empty `imagePullSecrets` element when an override for `serviceAccount.imagePullSecrets` is not provided.

### What's your helm version?

version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.20.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.7+rke2r1", GitCommit:"07a61d861519c45ef5c89bc22dda289328f29343", GitTreeState:"clean", BuildDate:"2023-10-18T16:30:12Z", GoVersion:"go1.20.10 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v5.0.1

### Which chart?

kube-state-metrics

### What's the chart version?

5.15.2

### What happened?

ServiceAccount contains an empty `imagePullSecrets` element when using default values:

```yaml
```yaml
# Source: kube-state-metrics/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: kube-state-metrics-5.15.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: kube-state-metrics
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/instance: stable
    app.kubernetes.io/version: "2.10.1"
  name: stable-kube-state-metrics
  namespace: argocd
imagePullSecrets:
```

### What you expected to happen?

Get this resource:

```yaml
# Source: kube-state-metrics/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: kube-state-metrics-5.15.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: kube-state-metrics
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/instance: stable
    app.kubernetes.io/version: "2.9.2"
  name: stable-kube-state-metrics
  namespace: monitoring
```

### How to reproduce it?

```sh
helm template stable prometheus-community/kube-state-metrics --version 5.15.2
```

### Enter the command that you execute and failing/misfunctioning.

```sh
helm template stable prometheus-community/kube-state-metrics --version 5.15.2
```

### Anything else we need to know?

This is already handled by other charts. For example: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/templates/serviceaccount.yaml#L13
