### ISSUE TITLE
[kube-prometheus-stack] AlertManager can not load the custom config

### ISSUE THREAD

**Issue by halohsu** [prometheus-community/helm-charts#4068]
### Describe the bug a clear and concise description of what the bug is.

I created a custom Helm configuration:
```yaml
namespaceOverride: "monitoring"
alertmanager:
  enabled: true
  alertmanagerSpec:
    logLevel: warn
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 10Gi
  config:
    global:
      resolve_timeout: 10m 
    route: 
      group_interval: 5s
      group_wait: 5s
      repeat_inteval: 5s
      receiver: 'prombot'
    receivers:
      - name: 'prombot'
        webhook_configs:
          - url: 'http://prometheus-alert-center.monitoring.svc.cluster.local:9327/prometheusalert?type=fs&tpl=prometheus-fs&fsurl=xxx'
```

But on the AlertManager page, it is still the default configuration, and the custom configuration has not taken effect.

The configuration seen from the AlertManager page is:
```yaml
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
  webex_api_url: https://webexapis.com/v1/messages
route:
  receiver: "null"
  group_by:
  - namespace
  continue: false
  routes:
  - receiver: "null"
    matchers:
    - alertname=~"InfoInhibitor|Watchdog"
    continue: false
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
inhibit_rules:
- source_matchers:
  - severity="critical"
  target_matchers:
  - severity=~"warning|info"
  equal:
  - namespace
  - alertname
- source_matchers:
  - severity="warning"
  target_matchers:
  - severity="info"
  equal:
  - namespace
  - alertname
- source_matchers:
  - alertname="InfoInhibitor"
  target_matchers:
  - severity="info"
  equal:
  - namespace
receivers:
- name: "null"
templates:
- /etc/alertmanager/config/*.tmpl
```

### What's your helm version?

version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.21.4"}

### What's your kubectl version?

Client Version: v1.28.4 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.26.3 WARNING: version difference between client (1.28) and server (1.26) exceeds the supported minor version skew of +/-1

### Which chart?

kube-prometheus-stack-55.0.0

### What's the chart version?

55.0.0

### What happened?

The custom configuration does not take effect, and/etc/alertmanager. yml in Pod is the default.

### What you expected to happen?

Use custom config.

### How to reproduce it?

```shell
helm pull prometheus-community/kube-prometheus-stack --untar
helm install --namespace monitoring kube-prometheus-stack ./kube-prometheus-stack -f kube-prometheus-stack_h800_values.yaml
```

### Enter the changed values of values.yaml?

```yaml
namespaceOverride: "monitoring"
alertmanager:
  enabled: true
  alertmanagerSpec:
    logLevel: warn
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 10Gi
  config:
    global:
      resolve_timeout: 10m 
    route: 
      group_interval: 5s
      group_wait: 5s
      repeat_inteval: 5s
      receiver: 'prombot'
    receivers:
      - name: 'prombot'
        webhook_configs:
          - url: 'http://prometheus-alert-center.monitoring.svc.cluster.local:9327/prometheusalert?type=fs&tpl=prometheus-fs&fsurl=xxx'
```

### Enter the command that you execute and failing/misfunctioning.

No command.

### Anything else we need to know?

nth.
