### ISSUE TITLE
[kube-prometheus-stack] Grafana deleteDatasource not deleting the data source

### ISSUE THREAD

**Issue by WTPascoe** [prometheus-community/helm-charts#4070]
### Describe the bug a clear and concise description of what the bug is.

I am attempting to delete the Prometheus datasource as I want a Thanos Query datasource to be the default, and Grafana won't allow 2 defaults at the same time. After making the changes that I believe should be needed, Prometheus remains as a datasource in Grafana, and is the default.

I'm using the following in my `grafana` values. I've tried changing the order so that `deleteDatasources` comes first with the same result. I'm doing a `rollout restart deployment prometheus-stack-grafana` after every change to the configmap and waiting for new pods before checking.

![Screenshot 2023-12-08 at 11 38 01](https://github.com/prometheus-community/helm-charts/assets/58910271/ba6eef19-b0fc-491f-816b-3c5495c3bf0d)

### What's your helm version?

version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.21.4"}

### What's your kubectl version?

Client Version: v1.28.4 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.28.3-gke.1203000

### Which chart?

prometheus-kube-stack

### What's the chart version?

54.2.2

### What happened?

Looking in the Grafana logs at startup, I see that the Prometheus datasource is deleted, but then inserted again.

```
logger=provisioning.datasources t=2023-12-08T11:01:53.11147604Z level=info msg="deleted datasource based on configuration" name=Prometheus
logger=provisioning.datasources t=2023-12-08T11:01:53.120534987Z level=info msg="inserting datasource from configuration " name=Prometheus uid=prometheus
```

`/etc/grafana/provisioning/datasources/datasource.yaml` in the grafana container in the pod contains the following

```
apiVersion: 1
deleteDatasources:
  - name: Prometheus
    orgId: 1
datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  url: http://prometheus-stack-kube-prom-prometheus.myns:9090/
  access: proxy
  isDefault: true
  jsonData:
    httpMethod: POST
    timeInterval: 30s
- name: Alertmanager
  type: alertmanager
  uid: alertmanager
  url: http://prometheus-stack-kube-prom-alertmanager.myns:9093/
  access: proxy
  jsonData:
    handleGrafanaManagedAlerts: false
    implementation: prometheus
- access: proxy
  isDefault: false
  name: Thanos Query
  type: prometheus
  uid: thanosquery
  url: http://thanos-query.myns.svc.cluster.local:9090/usr/share/grafana
```

### What you expected to happen?

I expected the Prometheus datasource to be deleted and not re-added.

### How to reproduce it?

Deploy the helm chart with the following values content:

```
grafana:
  enabled:
  additionalDataSources:
  - name: Thanos Query
    isDefault: false
    uid: thanosquery
    type: prometheus
    access: proxy
    url: http://thanos-query.myns.svc.cluster.local:9090 
  deleteDatasources:
  - name: Prometheus
    orgId: 1
```

### Enter the changed values of values.yaml?

```
grafana:
  enabled:
  additionalDataSources:
  - name: Thanos Query
    isDefault: false
    uid: thanosquery
    type: prometheus
    access: proxy
    url: http://thanos-query.myns.svc.cluster.local:9090 
  deleteDatasources:
  - name: Prometheus
    orgId: 1
```

### Enter the command that you execute and failing/misfunctioning.

See logs and screenshot above for incorrect outcome

**Comment by zeritti** [comment]
I reckon that the default datasource gets provisioned even after deletion due to the (default) setting

```yaml
grafana:
  sidecar:
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
```

**Comment by zeritti** [comment]
With respect to a default datasource, you can change it for the Prometheus datasource and still keep it if desired by means of

```yaml
grafana:
  sidecar:
    datasources:
      defaultDatasourceEnabled: true
      isDefaultDatasource: false
```
