### ISSUE TITLE
kube-prometheus-stack does not scrape targets

### ISSUE THREAD

**Issue by lfelipevaca** [prometheus-community/helm-charts#4078]
### Describe the bug a clear and concise description of what the bug is.

I have installed the kube-prometheus-stack chart, all pods, services and ingress are working fine.

kube-prometheus-stack-kube-state-metrics
kube-prometheus-stack-operator
kube-prometheus-stack-prometheus
kube-prometheus-stack-prometheus-node-exporter

The real problem is Prometheus does not expose targets for metrics status, operator, node exporter, etc..

Please consider that each pod/service (state-metrics,node-export,etc) is loading their metrics fine, the problem is that I don't know why Prometheus doesn't set the scrape configuration for them.

I have looked in the /etc/prometheus/config_out/prometheus.env.yaml file inside the pod, and found that the scrap settings are not set.

I'm pretty sure it's some configuration problem in the values, but I'm not sure what I'm forgetting or missing.

### What's your helm version?

helm3

### What's your kubectl version?

whatever

### Which chart?

kube-prometheus-stack

### What's the chart version?

55.1.0

### What happened?

I have installed the kube-prometheus-stack chart, all pods, services and ingress are working fine.

kube-prometheus-stack-kube-state-metrics
kube-prometheus-stack-operator
kube-prometheus-stack-prometheus
kube-prometheus-stack-prometheus-node-exporter

The real problem is Prometheus does not expose targets for metrics status, operator, node exporter, etc..

Please consider that each pod/service (state-metrics,node-export,etc) is loading their metrics fine, the problem is that I don't know why Prometheus doesn't set the scrape configuration for them.

I have looked in the /etc/prometheus/config_out/prometheus.env.yaml file inside the pod, and found that the scrap settings are not set.

I'm pretty sure it's some configuration problem in the values, but I'm not sure what I'm forgetting or missing.

### What you expected to happen?

I want prometheus to show the state_metrics,node_controller_etc targets. i.e. scrape the different cluster metrics

### How to reproduce it?

Install the chart  kube-prometheus-stack

### Enter the changed values of values.yaml?

```yaml
prometheus:
  enabled: true
  annotations: {}
  serviceAccount:
    create: true
    name: ""
    annotations: {}

  service:
    annotations: {}
    labels: {}
    clusterIP: ""
    port: 9090
    targetPort: 9090
    externalIPs: []
    nodePort: 30090
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalTrafficPolicy: Cluster
    type: ClusterIP
    additionalPorts: []
    publishNotReadyAddresses: false
    sessionAffinity: ""

  prometheusSpec:
    image:
      registry: quay.io
      repository: prometheus/prometheus
    tolerations: []
    topologySpreadConstraints: []
    alertingEndpoints: []
    retention: 2y
    replicas: 1
    shards: 1
    logLevel: info
    logFormat: logfmt
    routePrefix: /
    podMetadata: {}
    podAntiAffinity: ""
    podAntiAffinityTopologyKey: kubernetes.io/hostname
    affinity: {}
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-sc
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 200Gi
    volumes: []
    volumeMounts: []
    additionalScrapeConfigs:
      - job_name: "symphonica-business-metrics"
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (.+)
    securityContext:
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 2000
    walCompression: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
```

### Enter the command that you execute and failing/misfunctioning.

helmfile apply
