### ISSUE TITLE
[kube-prometheus-stack] Grafana switching Org adds Port 3000 in URL of Grafana

### ISSUE THREAD

**Issue by Atomique** [prometheus-community/helm-charts#4115]
### Describe the bug a clear and concise description of what the bug is.

If have configured multiple Orgs and if I switch between them the Port of Grafana (:3000) gets added into the URL which leads into an browser error of course ("ERR_CONNECTION_REFUSED"). 

I tried to find something like prometheus.prometheusSpec.externalURL for Grafana but couldn't find it. 

How Can I fix this issue? 

### What's your helm version?

v3.13.3

### What's your kubectl version?

v1.28.2

### Which chart?

prometheus-community/kube-prometheus-stack

### What's the chart version?

55.5.0

### Enter the changed values of values.yaml?

....
grafana:
  defaultDashboardsTimezone: Europe/Berlin
  adminPassword: <PW>
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - sub.domain.tld
  persistence:
    type: pvc
    enabled: true
    storageClassName: ceph-filesystem
    accessModes:
      - ReadWriteMany
   ...

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install $RELEASE_NAME $REPO_NAME/$RELEASE_NAME --namespace=$NAMESPACE --create-namespace --version=$RELEASE_VERSION -f values.yaml

**Comment by zeritti** [comment]
The problem should get fixed by setting `root_url` in `grafana.ini` ([Ref.](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#root_url)). For example, with ingress host `grafana.example.local` and TLS:

```yaml
grafana:
  grafana.ini:
    server:
      domain: grafana.example.local
      root_url: "https://%(domain)s/"
```

If using HTTP:

```yaml
grafana:
  grafana.ini:
    server:
      domain: grafana.example.local
      root_url: "http://%(domain)s/"
      ## alternative:
      # root_url: "%(protocol)s://%(domain)s/"
```
