### ISSUE TITLE
[prometheus] in agent mode: Configuring "rule_files"

### ISSUE THREAD

**Issue by andriy-simonov** [prometheus-community/helm-charts#4149]
### Is your feature request related to a problem ?

I deployed the chart in agent mode to my Kubernetes cluster. Unfortunately, the prometheus-server pod is stuck in "CrashLoopBackOff" due to the following error: _"Error loading config (--config.file=/etc/config/prometheus.yml)" file=/etc/config/prometheus.yml err="field rule_files is not allowed in agent mode"_.

To work around this issue, I removed the "rule_files" field from the prometheus-server ConfigMap, and the pod started successfully.

### Describe the solution you'd like.

I would like to disable the `rule_files` configuration explicitly or disable it by setting a corresponding value for the agent mode.

### Describe alternatives you've considered.

I tried to set the `ruleFiles` value to an empty object or redefine the whole `data.prometheus.yml` value without any success.

### Additional context.

Here's my current Helm values.yaml file:
```
alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false
server:
  configPath: /etc/config/prometheus.yml
  defaultFlagsOverride:
  - --enable-feature=agent
  - --config.file=/etc/config/prometheus.yml
  extraFlags:
  - web.enable-lifecycle
  global:
    evaluation_interval: 30s
    scrape_interval: 30s
    scrape_timeout: 10s
  remoteWrite:
  - basic_auth:
      password: xxxx
      username: yyyy
    url: https://my-external-prometheus.com/api/v1/write
```
