### ISSUE TITLE
[kube-prometheus-stack] Issue prometheus-grafana/inits stuck in download grafana dashboard

### ISSUE THREAD

**Issue by eltorio** [prometheus-community/helm-charts#4157]
### Describe the bug a clear and concise description of what the bug is.

Hi, on a previous version (forgot wich one :( it is a very bad idea to not specify version while using helm :(  ) this values.yaml works perfectly but now the pod prometheus-grafana/inits stuck at 
```log
2024-01-19T10:56:08.968002839Z + set -euf
2024-01-19T10:56:08.968044439Z + mkdir -p /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
2024-01-19T10:56:08.968741482Z + mkdir -p /var/lib/grafana/dashboards/grafana-dashboards-kubernetes-integration
2024-01-19T10:56:08.969561006Z + curl -skf --connect-timeout 60 --max-time 60 -H 'Accept: application/json' -H 'Content-Type: application/json;charset=UTF-8' https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
```  

**For testing** 
I added `highcanfly/net-tools:latest` container in my namespace and tested `curl -skf --connect-timeout 60 --max-time 60 -H 'Accept: application/json' -H 'Content-Type: application/json;charset=UTF-8' https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json` it downloads the remote dashboard perfectly.    

Without the `dashboard:` object in my values.yaml the stack deploys correctly but obviously without my custom dashboards.

### What's your helm version?

version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.5"}

### What's your kubectl version?

Client Version: v1.29.0 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.29.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

55.11.0

### What happened?

the customs grafana dashboards didn'y download

### What you expected to happen?

the customs dashboards should be downloaded and installed

### How to reproduce it?

see my values.yaml

### Enter the changed values of values.yaml?

 kube-prometheus-values.yaml:
```yaml
prometheus:
  ingress:
    enabled: true
    ingressClassName: haproxy
    annotations:
      haproxy.org/auth-type: basic-auth
      haproxy.org/auth-secret: monitoring/prometheus-haproxy-credentials
      cert-manager.io/cluster-issuer: l***********s-ca-issuer
    hosts:
    - prometheus.***********.org
    tls:
    - secretName: prometheus-crt
      hosts:
        - prometheus.***********.org
grafana:
  adminPassword: "R************o"
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false
  ingress:
    enabled: true
    ingressClassName: haproxy
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-azure
    hosts:
    - grafana.***********.org
    tls:
    - secretName: grafana-crt
      hosts:
        - grafana.***********.org
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'grafana-dashboards-kubernetes'
        orgId: 1
        folder: 'Kubernetes'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
      - name: 'grafana-dashboards-kubernetes-integration'
        orgId: 1
        folder: 'Integration'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes-integration
  dashboards:
    grafana-dashboards-kubernetes:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        token: ''
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        token: ''
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ''
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ''
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ''
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ''
      k8s-view-pvc:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/k8s-pvc.json
        token: ''
      prometheus:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-addons-prometheus.json
        token: ''
    grafana-dashboards-kubernetes-integration:
      home:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/home.json
        token: ''
      multi:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/multi-cluster.json
        token: ''
      cluster:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/cluster.json
        token: ''
      namespace-pods:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/namespace-pods.json
        token: ''
      namespace-workloads:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/namespace-workloads.json
        token: ''
      node-pods:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/node-pods.json
        token: ''
      pod:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/pod.json
        token: ''
      workload:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/workload.json
        token: ''
      kubelet:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/kubelet.json
        token: ''
      pvc:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/pvc.json
        token: ''

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: LocalCluster
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus:9090
        access: proxy
        isDefault: true
```  

### Enter the command that you execute and failing/misfunctioning.

```bash
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update prometheus-community
helm upgrade --install --namespace $MONITORING_NAMESPACE prometheus prometheus-community/kube-prometheus-stack --values kube-prometheus-values.yaml
```

**Comment by eltorio** [comment]
The problem is with curlimages/curl:7.73.0
I have a workaround using my own image containing curl (it is not designed for and include other tools but it has the advantage of being ready to use)…  
so I added in the grafana section of my values.yaml:  
```yaml
grafana:
  downloadDashboardsImage:
    registry:	docker.io
    repository:	highcanfly/net-tools
    tag: latest
```

And now it downloads all my dashboards !  
For reference this is my new values.yaml:  
```yaml
prometheus:
  ingress:
    enabled: true
    ingressClassName: haproxy
    annotations:
      haproxy.org/auth-type: basic-auth
      haproxy.org/auth-secret: monitoring/prometheus-haproxy-credentials
      cert-manager.io/cluster-issuer: l***********s-ca-issuer
    hosts:
    - prometheus.l***********s.org
    tls:
    - secretName: prometheus-crt
      hosts:
        - prometheus.l***********s.org
grafana:
  downloadDashboardsImage:
    registry:   docker.io
    repository: highcanfly/net-tools
    tag: latest
  adminPassword: "R**************o"
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false
  ingress:
    enabled: true
    ingressClassName: haproxy
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-azure
    hosts:
    - grafana.l***********s.org
    tls:
    - secretName: grafana-crt
      hosts:
        - grafana.l***********s.org
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'grafana-dashboards-kubernetes'
        orgId: 1
        folder: 'Kubernetes'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
      - name: 'grafana-dashboards-kubernetes-integration'
        orgId: 1
        folder: 'Integration'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes-integration
  dashboards:
    grafana-dashboards-kubernetes:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        token: ''
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        token: ''
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ''
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ''
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ''
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ''
      k8s-view-pvc:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/k8s-pvc.json
        token: ''
      prometheus:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-addons-prometheus.json
        token: ''
    grafana-dashboards-kubernetes-integration:
      home:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/home.json
        token: ''
      multi:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/multi-cluster.json
        token: ''
      cluster:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/cluster.json
        token: ''
      namespace-pods:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/namespace-pods.json
        token: ''
      namespace-workloads:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/namespace-workloads.json
        token: ''
      node-pods:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/node-pods.json
        token: ''
      pod:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/pod.json
        token: ''
      workload:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/workload.json
        token: ''
      kubelet:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/kubelet.json
        token: ''
      pvc:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/pvc.json
        token: ''

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: LocalCluster
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus:9090
        access: proxy
        isDefault: true
```
