### ISSUE TITLE
Allow Helm "list-merge" for sidecar containers

### ISSUE THREAD

**Issue by kesor** [prometheus-community/helm-charts#417]
A limitation with Helm is that it cannot merge lists (arrays) when using more than one values file (https://github.com/helm/helm/issues/3486); One workaround is having an object (dictionary) instead of the list, and iterating over the object. This allows to add/remove/modify internal properties of the objects when knowing their name.

In particular, we have a definition for a `sidecarContainers` that adds the `thanos-sidecar`; But we want to set different `resources.requests` for each of our different environments, without copying the whole sidecar container definition to each and every environment values file.

The existing use of `sidecarContainers` in the Deployment and StatefulSet of Prometheus server looks like this:
https://github.com/prometheus-community/helm-charts/blob/9abd1cfc61b9a3828c9d6909bf1fc7f755f0536d/charts/prometheus/templates/server/sts.yaml#L154-L156
https://github.com/prometheus-community/helm-charts/blob/9abd1cfc61b9a3828c9d6909bf1fc7f755f0536d/charts/prometheus/templates/server/deploy.yaml#L149-L151

It would be much more useful if changed to look like this:

```yaml
{{- if .Values.server.sidecarContainers }}
  {{- range $name, $spec :=  .Values.server.sidecarContainers }}
    - name: {{ $name }}
      {{- toYaml $spec | nindent 10 }}
  {{- end }}
{{- end }}
```

The above change will allow naming and defining a `sidecarContainer` in a single `values.yaml` file, then having an override for certain container properties (such as image tag, resources.requests/limits, etc...) in small per-environment files.

A shared `values-shared.yaml` can include:
```yaml
server:
  sidecarContainers:
    thanos-sidecar:
      image: quay.io/thanos/thanos:v0.16.0
      resources:
        requests:
          memory: 64Mi
```

And another `values-staging-env.yaml` can include only the override, like so:
```yaml
server:
  sidecarContainers:
    thanos-sidecar:
      resources:
        requests:
          memory: 128Mi
```

And all would work when using `helm install -f values-shared.yaml -f values-staging-env.yaml`
