### ISSUE TITLE
[prometheus-blackbox-exporter] include in extra-manifests.yaml

### ISSUE THREAD

**Issue by marselsultanov** [prometheus-community/helm-charts#4174]
### Describe the bug a clear and concise description of what the bug is.

When i put:
```
extraManifests:
  - apiVersion: v1
     kind: MyCRD
     metadata:
       labels:
         {{- include "prometheus-blackbox-exporter.labels" . | nindent 4 }}
```
to:
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/values.yaml

I get error "did not find expected node content"

Partially case here: 
https://stackoverflow.com/questions/71169122/how-to-add-custom-templates-to-bitnami-helm-chart
but quotas doesn't help me, because i have multiline labels, if i do:
```
extraManifests:
  - apiVersion: v1
     kind: MyCRD
     metadata:
      labels:
        '{{- include "prometheus-blackbox-exporter.labels" . | nindent 4 }}'
```
i get:
```
metadata:
  labels: '
    here: default
    labels: but_in
    single: quote'
```
but kubectl give error on this :/

How i can use **include** with map in **extraManifests**?

### What's your helm version?

3.11.1

### What's your kubectl version?

1.21

### Which chart?

prometheus-blackbox-exporter

### What's the chart version?

8.8.0

### How to reproduce it?

2. helm template prometheus-blackbox-exporter prometheus-community/prometheus-blackbox-exporter --values my-values.yaml

my-values.yaml:
```
extraManifests:
  - apiVersion: v1
    kind: MyCRD
    metadata:
      labels:
        {{- include "prometheus-blackbox-exporter.labels" . | nindent 4 }}
```

### Enter the command that you execute and failing/misfunctioning.

helm install -f values.yaml

**Comment by marselsultanov** [comment]
If i change:
1. values.yaml to
```
extraManifests:
  - |
    apiVersion: v1
    kind: MyCRD
    metadata:
      labels:
        '{{- include "prometheus-blackbox-exporter.labels" . | nindent 4 }}'
```
AND
2. extra-manifests.yaml to
```
{{ range .Values.extraManifests }}
---
{{ tpl . $ }}
{{ end }}
```

Its work...
