### ISSUE TITLE
[prometheus-adapter] Getting error when installing this chart by supplying a custom config.yaml file

### ISSUE THREAD

**Issue by pulkitsapra** [prometheus-community/helm-charts#419]
Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```

**Which chart**: prometheus-community/prometheus-adapter    
**Which version of the chart**: 2.7.0   

**What happened**:
I am using this Prometheus Adapter to expose `redis_queue_length_total` as a custom metric from Prometheus.
I am installing this Adapter using a custom config.yaml as follows :

`helm install -f config.yaml prometheus-adapter prometheus-community/prometheus-adapter`

This gives me the following error.
`Error: template: prometheus-adapter/templates/resource-metrics-cluster-role.yaml:1:38: executing "prometheus-adapter/templates/resource-metrics-cluster-role.yaml" at <.Values.rules.resource>: nil pointer evaluating interface {}.resource`

My config.yaml looks like this
```
rules:
custom:
- seriesQuery: 'redis_queue_length_total'
  resources:
    overrides:
      namespace:
        resource: namespace
    # skip specifying generic resource<->label mappings, and just
    # attach only pod and namespace resources by mapping label names to group-resources
  # specify that the `container_` and `_seconds_total` suffixes should be removed.
  # this also introduces an implicit filter on metric family names
  name:
    # we use the value of the capture group implicitly as the API name
    # we could also explicitly write `as: "$1"`
    matches:  "^(.*)_total$"
    as: "Redis_queue_length"
  # specify how to construct a query to fetch samples for a given series
  # This is a Go template where the `.Series` and `.LabelMatchers` string values
  # are available, and the delimiters are `<<` and `>>` to avoid conflicts with
  # the prometheus query language
  metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>,container_name!="POD"}[1m]) by (<<.GroupBy>>)
```
Can someone please tell me what I am doing wrong. It is an issue arising for a long time. Any help would be greatly appreciated.
