### ISSUE TITLE
[kube-prometheus-stack] alertmanager configuration does not take effect

### ISSUE THREAD

**Issue by luo964973791** [prometheus-community/helm-charts#4196]
### Describe the bug a clear and concise description of what the bug is.

```
  config:
    global:
      resolve_timeout: 5m

    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'email-alerts'

    receivers:
    - name: 'email-alerts'
      email_configs:
        - to: ''
          from: ''
          smarthost: ''
          auth_username: ''
          auth_password: ''
          require_tls: false

    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
      - target_matchers:
          - 'alertname = InfoInhibitor'

    templates:
    - '/etc/alertmanager/config/*.tmpl'
  stringConfig: ""
  tplConfig: true
  templateFiles:
    template_1.tmpl: |-
        {{ define "email.from" }}from@qq.com{{ end }}
        {{ define "email.to" }}to@qq.com{{ end }}
        {{ define "email.to.html" }}
        {{ range .Alerts }}
        =========start==========<br>
        告警程序: prometheus_alert <br>
        告警级别: {{ .Labels.severity }} 级 <br>
        告警类型: {{ .Labels.alertname }} <br>
        故障主机: {{ .Labels.instance }} <br>
        告警主题: {{ .Annotations.summary }} <br>
        告警详情: {{ .Annotations.description }} <br>
        触发时间: {{ .StartsAt.Format "2019-08-04 16:58:15" }} <br>
        =========end==========<br>
        {{ end }}
        {{ end }}



[root@node1 kube-prometheus-stack]# 
[root@node1 kube-prometheus-stack]# kubectl  exec -it -n monitoring           alertmanager-prometheus-kube-prometheus-alertmanager-0 /bin/sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
/alertmanager $ 
/alertmanager $ cd /etc/alertmanager/
/etc/alertmanager $ ls
alertmanager.yml  certs             config            config_out        web_config
/etc/alertmanager $ cd config
/etc/alertmanager/config $ ls
alertmanager.yaml.gz  template_1.tmpl
/etc/alertmanager/config $ cat template_1.tmpl 
{{ define "email.from" }}from@qq.com{{ end }}
{{ define "email.to" }}to@qq.com{{ end }}
{{ define "email.to.html" }}
{{ range .Alerts }}
=========start==========<br>
告警程序: prometheus_alert <br>
告警级别: {{ .Labels.severity }} 级 <br>
告警类型: {{ .Labels.alertname }} <br>
故障主机: {{ .Labels.instance }} <br>
告警主题: {{ .Annotations.summary }} <br>
告警详情: {{ .Annotations.description }} <br>
触发时间: {{ .StartsAt.Format "2019-08-04 16:58:15" }} <br>
=========end==========<br>
{{ end }}
{{ end }}/etc/alertmanager/config $ pwd
/etc/alertmanager/config
/etc/alertmanager/config $ exit
[root@node1 kube-prometheus-stack]# helm version
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}
[root@node1 kube-prometheus-stack]# kubectl get node
NAME    STATUS   ROLES           AGE    VERSION
node1   Ready    control-plane   7d1h   v1.25.6
node2   Ready    <none>          7d1h   v1.25.6
node3   Ready    <none>          7d1h   v1.25.6
[root@node1 kube-prometheus-stack]# kubectl get pod -n monitoring
NAME                                                      READY   STATUS    RESTARTS        AGE
alertmanager-prometheus-kube-prometheus-alertmanager-0    2/2     Running   0               3m18s
nginx-export-prometheus-nginx-exporter-69c6cf97b7-gjbxm   1/1     Running   12 (116m ago)   4d18h
prometheus-grafana-87c487c45-6sz6b                        3/3     Running   0               3m23s
prometheus-kube-prometheus-operator-8688498787-4wvgv      1/1     Running   0               3m23s
prometheus-kube-state-metrics-6876f5d49d-h4dgc            1/1     Running   0               3m23s
prometheus-prometheus-kube-prometheus-prometheus-0        2/2     Running   0               3m18s
prometheus-prometheus-node-exporter-84lv6                 1/1     Running   0               3m23s
prometheus-prometheus-node-exporter-ggsqf                 1/1     Running   0               3m23s
prometheus-prometheus-node-exporter-j679x                 1/1     Running   0               3m23s
[root@node1 kube-prometheus-stack]# 
```

### What's your helm version?

v3.10.3

### What's your kubectl version?

v1.25.6

### Which chart?

Alertmanager version=0.26.0,

### What's the chart version?

alertmanager

### What happened?

The configuration template did not take effect and was automatically generated, but emails were still sent using helm’s default format.

### Enter the changed values of values.yaml?

``` 
 config:
    global:
      resolve_timeout: 5m

    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'email-alerts'

    receivers:
    - name: 'email-alerts'
      email_configs:
        - to: ''
          from: ''
          smarthost: ''
          auth_username: ''
          auth_password: ''
          require_tls: false

    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
      - target_matchers:
          - 'alertname = InfoInhibitor'

    templates:
    - '/etc/alertmanager/config/*.tmpl'
  stringConfig: ""
  tplConfig: true
  templateFiles:
    template_1.tmpl: |-
        {{ define "email.from" }}from@qq.com{{ end }}
        {{ define "email.to" }}to@qq.com{{ end }}
        {{ define "email.to.html" }}
        {{ range .Alerts }}
        =========start==========<br>
        告警程序: prometheus_alert <br>
        告警级别: {{ .Labels.severity }} 级 <br>
        告警类型: {{ .Labels.alertname }} <br>
        故障主机: {{ .Labels.instance }} <br>
        告警主题: {{ .Annotations.summary }} <br>
        告警详情: {{ .Annotations.description }} <br>
        触发时间: {{ .StartsAt.Format "2019-08-04 16:58:15" }} <br>
        =========end==========<br>
        {{ end }}
        {{ end }}
```

### Enter the command that you execute and failing/misfunctioning.

The configuration template did not take effect and was automatically generated, but emails were still sent using helm’s default format.
