### ISSUE TITLE
[kube-prometheus-stack] not picking up windows-node-exporters

### ISSUE THREAD

**Issue by jemstep-kerry** [prometheus-community/helm-charts#4227]
### Describe the bug a clear and concise description of what the bug is.

Describe the bug a clear and concise description of what the bug is.
When i add:

```
windowsMonitoring:
  enabled: true
  job: windows-exporter

prometheus-windows-exporter:
  prometheus:
    monitor:
      enabled: true
      jobLabel: windows-exporter
  config: |
    - collectors:
        enabled: '[defaults],memory,container'
      collector:
        service:
          services-where: "Name='service-name'

```
to:
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

I get no metrics scraped from the windows nodes
I do however get metrics from Linux node with:
```
nodeExporter:
  enabled: true
```

Followed the advice given here:
https://github.com/prometheus-community/helm-charts/issues/3625
However no scraping of windows nodes is taking place and the windows-exporter is not being added in the prometheuslocal:port/config.

How i can use include other namespaces and services to scrape?
I may just be missing something simple in the docs but for the life of me, I can't see it.

### What's your helm version?

3.13.3

### What's your kubectl version?

1.24

### Which chart?

kube-prometheus-stack

### What's the chart version?

55.0.0

### What happened?

The windows exporters are running on the desired nodes however no targets are added to the Prometheus config.

### What you expected to happen?

I would have expected to see the metrics from windows nodes to appear and the windows scrape to be added to the configuration.

### How to reproduce it?

helm template kube-prometheus-stack prometheus-community/kube-prometheus-stack --values values.yaml
values.yaml:
```
prometheus-windows-exporter:
  ## Enable ServiceMonitor and set Kubernetes label to use as a job label
  ##
  prometheus:
    monitor:
      enabled: true
      jobLabel: windows-exporter
  config: |
    - collectors:
        enabled: '[defaults],memory,container'
      collector:
        service:
          services-where: "Name='service-name'
        process:
          include: "(containerd|kubelet|kube-proxy|EKS-WindowsServiceHost|cmd|powershell|pwsh|Microservice|Monolith).*"

prometheus:
  enabled: true
  prometheusSpec:
   additionalServiceMonitors:
    - name: Productname-monitor
      selector:
        matchLabels:
          repo: Productname
      namespaceSelector:
        matchNames:
          - main-service-namespace
      endpoints:
      - port: metrics
        interval: 10s
```

### Enter the changed values of values.yaml?

windowsMonitoring:
  enabled: true
  job: windows-exporter

prometheus-windows-exporter:
  prometheus:
    monitor:
      enabled: true
      jobLabel: windows-exporter
  config: |
    - collectors:
        enabled: '[defaults],memory,container'
      collector:
        service:
          services-where: "Name='service-name'
        process:
          include: "(containerd|kubelet|kube-proxy|EKS-WindowsServiceHost|cmd|powershell|pwsh|Microservice|Monolith).*"

prometheus:
  enabled: true
  prometheusSpec:
   additionalServiceMonitors:
    - name: Productname-monitor
      selector:
        matchLabels:
          repo: Productname
      namespaceSelector:
        matchNames:
          - main-service-namespace
      endpoints:
      - port: metrics
        interval: 10s
```


### Enter the command that you execute and failing/misfunctioning.

helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --values values.yaml

### Anything else we need to know?

_No response_
