### ISSUE TITLE
[kube-prometheus-stack] AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by ismail-temiz** [prometheus-community/helm-charts#4229]
### Describe the bug a clear and concise description of what the bug is.

I am trying to upgrade our KPS from 51.10.0 to `52.x.x`
our value file has:
```
    thanos:
      baseImage: quay.io/thanos/thanos
      version: "[[ thanos.version ]]"
      objectStorageConfig:
         key: thanos.yaml
         name: thanos-objectstorage
```

Therefore, I followed the instructions on the upgrade guide and edited as:
```
    thanos:
      baseImage: quay.io/thanos/thanos
      version: "[[ thanos.version ]]"
      objectStorageConfig:
        existingSecret:
          key: thanos.yaml
          name: thanos-objectstorage
```
But when I run the pipeline I get `AttributeError: 'NoneType' object has no attribute 'keys'`

I tried it as 
```
    thanos:
      baseImage: quay.io/thanos/thanos
      version: "[[ thanos.version ]]"
      objectStorageConfig:
        secret:
          key: thanos.yaml
          name: thanos-objectstorage
```

it deploys but then I get this in thanos-sidecar
```
{"caller":"main.go:135","err":"yaml: unmarshal errors:\n  line 1: field key not found in type client.BucketConfig\n  line 2: field name not found in type client.BucketConfig\nparsing config YAML file\ngithub.com/thanos-io/objstore/client.NewBucket\n\t/go/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20221006135717-79dcec7fe604/client/factory.go:55\nmain.runSidecar\n\t/app/cmd/thanos/sidecar.go:308\nmain.registerSidecar.func1\n\t/app/cmd/thanos/sidecar.go:73\nmain.main\n\t/app/cmd/thanos/main.go:133\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\npreparing sidecar command failed\nmain.main\n\t/app/cmd/thanos/main.go:135\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594","level":"error","ts":"2024-02-06T16:14:40.108761321Z"}
```

### What's your helm version?

version.BuildInfo{Version:"v3.13.3", GitCommit:"c8b948945e52abba22ff885446a1486cb5fd3474", GitTreeState:"clean", GoVersion:"go1.21.5"}

### What's your kubectl version?

Server Version: v1.26.10-gke.1101000

### Which chart?

kube-prometheus-stack

### What's the chart version?

51.10.0

### What happened?

Thanos side car secret key issue

### What you expected to happen?

Upgrade the deployment.

### How to reproduce it?

change
```
      objectStorageConfig:
        key: thanos.yaml	   
        name: thanos-objectstorage
```
to
```
      objectStorageConfig:
        existingSecret:
          key: thanos.yaml
          name: thanos-objectstorage
```

### Enter the command that you execute and failing/misfunctioning.

CI/CD pipeline

**Comment by ismail-temiz** [comment]
debug output:
```
# Source: kube-prometheus-stack/templates/prometheus/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: po-promop-prometheus
  namespace: monitoring
  labels:
    app: promop-prometheus
    app.kubernetes.io/component: prometheus

    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: po
    app.kubernetes.io/version: "56.6.2"
    app.kubernetes.io/part-of: promop
    chart: kube-prometheus-stack-56.6.2
    release: "po"
    heritage: "Helm"
data:
```
it won't render any `data`
