### ISSUE TITLE
kube-prometheus-stack not picking up additionalDataSources

### ISSUE THREAD

**Issue by thoefkens** [prometheus-community/helm-charts#4231]
### Describe the bug a clear and concise description of what the bug is.

Hi,

I deploy kube-prometheus-stack with helm and pass additional data sources in values.yaml as such:

```
grafana:
  defaultDashboardsEnabled: false
  additionalDatasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
```

After deployment however, this datasource is not picked up. The chart always creates the default xxx-grafana-datasource ConfigMap with these values:

```
apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  url: http://kube-prometheus-stack-prometheus.monitoring:9090/
  access: proxy
  isDefault: true
  jsonData:
    httpMethod: POST
    timeInterval: 30s
- name: Alertmanager
  type: alertmanager
  uid: alertmanager
  url: http://kube-prometheus-stack-alertmanager.monitoring:9093/
  access: proxy
  jsonData:
    handleGrafanaManagedAlerts: false
    implementation: prometheus
```

How can I make Grafana pick up the additional data source during deployment via helm?

### What's your helm version?

version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.21.4"}

### What's your kubectl version?

Client Version: v1.28.4

### Which chart?

kube-prometheus-stack

### What's the chart version?

latest version

### What happened?

Hi,

I deploy kube-prometheus-stack with helm and pass additional data sources in values.yaml as such:

```
grafana:
  defaultDashboardsEnabled: false
  additionalDatasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
```

After deployment however, this datasource is not picked up. The chart always creates the default xxx-grafana-datasource ConfigMap with these values:

```
apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  url: http://kube-prometheus-stack-prometheus.monitoring:9090/
  access: proxy
  isDefault: true
  jsonData:
    httpMethod: POST
    timeInterval: 30s
- name: Alertmanager
  type: alertmanager
  uid: alertmanager
  url: http://kube-prometheus-stack-alertmanager.monitoring:9093/
  access: proxy
  jsonData:
    handleGrafanaManagedAlerts: false
    implementation: prometheus
```

How can I make Grafana pick up the additional data source during deployment via helm?

### What you expected to happen?

I except my Loki data source to be there.

### Enter the command that you execute and failing/misfunctioning.

helm install Kube-prometheus-stack with the values.yaml I have shown above.

### Anything else we need to know?

Note I am not using loki-stack to add loki to my cluster but the standard loki chart. Loki-stack has other issues.
