### ISSUE TITLE
[kube-prometheus-stack] built in grafana dashboards invalid

### ISSUE THREAD

**Issue by thomasmRavn** [prometheus-community/helm-charts#4267]
### Describe the bug a clear and concise description of what the bug is.

I am not too familiar with prometheus scrape configs so I might be crazy buuuut...
We're trying to setup our scrape configs in prometheus so that we can make use of the grafana dashboards that you provide in the chart

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
This has a filter that the job is called "kubelet" and the metrics_path is metrics/cadvisor
While
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/persistentvolumesusage.yaml
also has a filter that the job is called "kubelet" and the metrics_pat is /metrics
But my understanding is the job name/metrics path is a 1:1 mapping, so I don't see how we can use both dashboards

we have ended up with this config below, which will work for the 1st dashboard but we can't see persistent volume data because the job is called kubelet-metrics in our config not kubelet. But if I named the job kubelet here then it would clash with the 1st block
```
additionalScrapeConfigs:
        - job_name: kubelet
          honor_timestamps: true
          scrape_timeout: 15s
          metrics_path: /metrics/cadvisor
          scheme: https
          kubernetes_sd_configs:
            - role: node
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__metrics_path__]
              regex: (.*)
              target_label: metrics_path
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
        - job_name: kubelet-metrics
          honor_timestamps: true
          scrape_timeout: 15s
          metrics_path: /metrics
          scheme: https
          kubernetes_sd_configs:
            - role: node
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/${1}/proxy/metrics
```

Am I just not understanding how prometheus additional scrape configs work or is this a mistake? What is a working/good example of the scrape config that would lead to both dashboards returning data?

Thanks in advance, and sorry for the inconvenience.

### What's your helm version?

version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.6"}

### What's your kubectl version?

Client Version: v1.29.1 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.27.3

### Which chart?

kube-prometheus-stack

### What's the chart version?

 56.8.0

### What happened?

We had this working for a while with our own grafana dashboards, then we realised that this was pointless. We should try to make better use of your stack and noticed this. If it is a bug I can raise a PR to resolve.

### What you expected to happen?

both dashboards should return data

### How to reproduce it?

I'm just looking at the files in github, 

### Enter the changed values of values.yaml?

```
prometheus:
  prometheusSpec:
      additionalScrapeConfigs:
        - job_name: kubelet
          honor_timestamps: true
          scrape_timeout: 15s
          metrics_path: /metrics/cadvisor
          scheme: https
          kubernetes_sd_configs:
            - role: node
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__metrics_path__]
              regex: (.*)
              target_label: metrics_path
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
        - job_name: kubelet-metrics
          honor_timestamps: true
          scrape_timeout: 15s
          metrics_path: /metrics
          scheme: https
          kubernetes_sd_configs:
            - role: node
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/${1}/proxy/metrics
```

### Enter the command that you execute and failing/misfunctioning.

helm template .
