### ISSUE TITLE
[kube-prometheus-stack] Ingress Annotation templating breaks valid annotations

### ISSUE THREAD

**Issue by aaronriedel** [prometheus-community/helm-charts#4269]
### Describe the bug a clear and concise description of what the bug is.

With Version 56.8.0 the following Change was made:
https://github.com/prometheus-community/helm-charts/pull/4236

Unfortunately this leads to the following helm error in my argocd:
```
ComparisonError: Failed to load target state: failed to generate manifest for source 1 of 3: rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . --name-template prometheus --namespace prometheus --kube-version 1.29 --values <path to cached source>/prometheus/values.yaml <api versions removed> --include-crds` failed exit status 1: Error: template: kube-prometheus-stack/templates/prometheus/ingressperreplica.yaml:28:52: executing "kube-prometheus-stack/templates/prometheus/ingressperreplica.yaml" at <.>: wrong type for value; expected chartutil.Values; got int Use --debug flag to render out invalid YAML
```

I use the following annotation for my ingresses and ingressreplicas:
```yaml
alertmanager::
  ingressPerReplica:
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: traefik-basic-auth@kubernetescrd
```

I think this is a valid annotation and it worked until Version 56.7.0
Does it somehow get interpreted by the helm tpl function?

### What's your helm version?

version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.20.10"}

### What's your kubectl version?

Client Version: v1.29.2  Server Version: v1.29.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

56.8.0

### What happened?

I update the Chart Version and helm throws an error for previously working values.

### What you expected to happen?

Since this should not have been a breaking change my old values.yaml should still work.

### How to reproduce it?

```yaml
alertmanager::
  ingressPerReplica:
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: traefik-basic-auth@kubernetescrd
```
Use this traefik annotation.

### Enter the changed values of values.yaml?

```yaml
alertmanager::
  ingressPerReplica:
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: traefik-basic-auth@kubernetescrd
```

### Enter the command that you execute and failing/misfunctioning.

helm template . --name-template prometheus --namespace prometheus --kube-version 1.29 --values <path to cached source>/prometheus/values.yaml <api versions removed> --include-crds
