### ISSUE TITLE
[kube-prometheus-stack] grafana dashboards set as home dashboard in values.yaml

### ISSUE THREAD

**Issue by Mert18** [prometheus-community/helm-charts#4272]
### Is your feature request related to a problem ?

Users have to go to settings and set a home dashboard. I want it to be automatic on deployment.

### Describe the solution you'd like.

I'd like to set option "is_home_dashboard" for dashboard json I provided at values.yaml.

### Describe alternatives you've considered.

NONE

### Additional context.

Grafana has this feature via the variable "default_home_dashboard_path". But this setting does not work when set in values.yaml file(or did I misplaced it?). Any help is appreciated.

**Comment by zeritti** [comment]
> Grafana has this feature via the variable "default_home_dashboard_path". But this setting does not work when set in values.yaml file(or did I misplaced it?). Any help is appreciated.

That is exactly the [setting](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#default_home_dashboard_path) to use. For example,

```yaml
grafana:
  grafana.ini:
    dashboards:
      default_home_dashboard_path: ../../../../tmp/dashboards/custom/myhomedashboard.json
```
where `/tmp/dashboards/custom/myhomedashboard.json` is a provisioned dashboard source.
