### ISSUE TITLE
[kube-prometheus-stack] Event trigger but not received

### ISSUE THREAD

**Issue by starker-xp** [prometheus-community/helm-charts#4277]
Hello, I find myself stuck.

I arrive at trigger events the alertmanager sees them, the logs show an event fired but I receive nothing at all. I've been searching for several days without success...

I try to setup 
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update`
kubectl create namespace monitoring
helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring

Helm prometheus version 56.8
Alert manager 0.26

I edit my prometheus config with 

  ```yml
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    probeNamespaceSelector: {}
    probeSelector: {}
    ruleNamespaceSelector:  {}
    ruleSelector:  {}
    scrapeConfigNamespaceSelector: {}
    scrapeConfigSelector: {}
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
```

and i try to apply this config 

```yml
---
apiVersion: v1
kind: Namespace
metadata:
  name: super-namespace
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: my-project
  namespace: super-namespace
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: my-project-compress
  namespace: super-namespace
spec:
  compress: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-project-frontend-cert
  namespace: super-namespace
spec:
  commonName: mywebsite.example.fr 
  secretName: my-project-frontend-cert
  dnsNames:
    - mywebsite.example.fr
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: my-project-frontend-80
  namespace: super-namespace
  labels:
    app: my-project
    tier: frontend
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`mywebsite.example.fr`)
      kind: Rule
      services:
        - name: my-project-frontend
          port: 80 
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: my-project-frontend-443
  namespace: super-namespace
  labels:
    app: my-project 
    tier: frontend
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mywebsite.example.fr`)
      kind: Rule
      services:
        - name: my-project-frontend
          port: 80 
      middlewares:
        - name: my-project-compress
  tls:
    secretName: my-project-frontend-cert
---
apiVersion: v1
kind: Service
metadata:
  name: my-project-frontend
  namespace: super-namespace
spec:
  selector:
    app: my-project
    tier: frontend
  ports:
    - name: http-web
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-project-frontend
  namespace: super-namespace
  labels:
    app: my-project
    tier: frontend
spec:
  selector:
    matchLabels:
      app: my-project
      tier: frontend
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: my-project
        tier: frontend
    spec:
      containers:
      - name: my-project-frontend
        image: fabxc/instrumented_app
        ports:
          - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-project-monitoring
  namespace: super-namespace
spec:
  namespaceSelector: {}
  selector: {}
  endpoints:
    - interval: 1s
      path: /metrics
      port: http-web
      scheme: http
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: my-project-alertmanager-config
  namespace: super-namespace
spec:
  route:
    # groupBy: [alertname, job]
    groupWait: 0s
    groupInterval: 5s
    repeatInterval: 1s
    receiver: "all"
  receivers:
  - name: all
    discordConfigs: 
      - sendResolved: true
        apiURL:
          name: discord-webhook-secret
          key: webhook_url
    webhookConfigs: 
      - sendResolved: true
        url: https://webhook.site/38245f6a-7276-4fcc-b1d1-62666d25af02
        maxAlerts: 0
    slackConfigs:
      - sendResolved: true
        apiURL:
          name: slack-webhook-secret
          key: webhook_url
        channel: '#monitoring'
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: my-project-rules
  namespace: super-namespace
  labels:
    app: kube-prometheus-stack
    release: prometheus
spec:
  groups:
  - name: alertmanager.rules
    rules:
      - alert: my-project-app-service-health
        annotations:
          description: Problem on application (check on swagger path)
          title:  "Health check failed for application on pod => {{ $labels.namespace }}/{{$labels.pod}}" 
        expr: |
         vector(1)
        for: 5s
        labels:
          severity: critical
      - alert: my-project-database-service-health
        annotations:
          description: Problem on contacting DATABASE
          title:  "Health check failed for service DATABASE on pod => {{ $labels.namespace }}/{{$labels.pod}}" 
        expr: |
          vector(1)
        for: 5s
        labels:
          severity: critical
---
apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook-secret
  namespace: super-namespace
data:
  webhook_url: >-
    url_base64==
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret
  namespace: super-namespace
data:
  webhook_url: >-
    url_base64
type: Opaque
```

This is probably nonsense but I can't find it.
