### ISSUE TITLE
[kube-prometheus-stack] unique labels for default prometheusrule

### ISSUE THREAD

**Issue by ThomasBoutelier** [prometheus-community/helm-charts#4281]
### Is your feature request related to a problem ?

It is not possible to define a unique label for each defaultRules. I use prometheus with thanos ruler and it would be interesting to be able to select the rules to be processed by one or other of the components.
It's already possible to define a rules selector for both, but you can only add a label for all the rules at once, or by patching it by hand.

### Describe the solution you'd like.

Like the solution for additionalRuleGroupLabels.  We could have a list of all the rules and select whether we want to add a specific label. 

For example:
```
defaultRules:
  additionalLabels:
    alertmanager:
      role: thanos-ruler
    etcd:
      role: prometheus  
    configReloaders: {}
    general: {}
```

### Describe alternatives you've considered.

At the moment, all my rules are managed by thanos. Which is not a recommendation.
