### ISSUE TITLE
[prometheus-postgres-exporter] http2=false address=[::]:9187

### ISSUE THREAD

**Issue by kenderipa** [prometheus-community/helm-charts#4286]
### Describe the bug a clear and concise description of what the bug is.

Hello,

while trying to deploy postgres-exporter into k8s-cluster with Terraform and Helm provider, I get following errors:
```
ts=2024-02-23T10:41:50.453Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9187

ts=2024-02-23T10:41:50.453Z caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9187
	
ts=2024-02-23T10:41:50.453Z caller=proc.go:267 msg="Excluded databases" databases=[]
	
ts=2024-02-23T10:41:50.453Z caller=main.go:86 level=warn msg="Error loading config" err="Error opening config file \"/etc/postgres_exporter.yml\": open /etc/postgres_exporter.yml: no such file or directory"
```

My values.yaml looks as follows:

```
config:
  datasource:
    host: '10.0.0.72' #IP of the Postgres instance in the same network/VPC, but not in the same cluster
    userSecret:
      name: postgresql-user-root
      key: username
    passwordSecret:
      name: postgresql-user-root
      key: password
    port: "5432"
    database: 'keycloak'
    sslmode: disable
```

There's a miscunfiguration somewhere, but I cannot find it.

### What's your helm version?

Probably the last one, pulled remotely by Terraform

### What's your kubectl version?

1.25 (Open Telekom Cloud)

### Which chart?

prometheus-postgres-exporte

### What's the chart version?

5.3.0

### What happened?

See above

### What you expected to happen?

Normal metric scraping.

### How to reproduce it?

See above. 

### Enter the changed values of values.yaml?

```
config:
  datasource:
    host: '10.0.0.72' #IP of the Postgres instance in the same network/VPC, but not in the same cluster
    userSecret:
      name: postgresql-user-root
      key: username
    passwordSecret:
      name: postgresql-user-root
      key: password
    port: "5432"
    database: 'keycloak'
    sslmode: disable
```

### Enter the command that you execute and failing/misfunctioning.

terraform apply
