### ISSUE TITLE
[prometheus-kube-stack] Custom ServiceMonitors are not loaded by Prometheus.

### ISSUE THREAD

**Issue by brpaz** [prometheus-community/helm-charts#430]
Hello. I have installed `prometheus-kube-stack` and I am trying to configure new service monitors but they are not being detected by Prometheus. Both my own, but also the ones provided by 3rd party charts like Nginx-ingress.

I am trying to experiment with some values of the chart and this is what I have now:

```yaml
podMonitorSelectorNilUsesHelmValues: "false"
serviceMonitorSelectorNilUsesHelmValues: "false"
serviceMonitorSelector: {}
```

The only way I can get Prometheus to find my service monitors is to use a `serviceMonitorSelector` like this:

```yaml
serviceMonitorSelector:
   matchLabels:
       role: service-monitor
```

And give the respective label to my service monitors. 

The problem is that the default service monitors configured by the Prometheus chart disappear.

I had the same issue with rulesSelector, but managed to solve it with the "defaultRules.labels" option, which seems not to be available for service monitors.

In my scenario, I simply want Prometheus to load all service monitor objects it can find. I shouldn't need to add a specific label or so as this might break Service Monitors provided by external Helm charts which might not allow specifying custom labels in the ServiceMonitor object.

**Helm Version**::

```console
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**Kubernetes Version**::

```console
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Which chart**:

kube-prometheus-stack

**Which version of the chart**:

12.2.4

**Comment by totoroot** [comment]
I had the similar troubles when first installing the chart. Prometheus looks for the release label of the deployed helm chart by default, so labeling your serviceMonitors with the release name of your chart, automatically adds them to the monitored stack no matter which namespace they're in. A serviceMonitor manifest "application-servicemonitor.yaml" might look like this:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: application-servicemonitor
  labels:
    app: application
    # release name substituted upon deployment of helm chart kube-prometheus-stack
    release: $KPS_RELEASE
  namespace: default
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: application
  endpoints:
  - port: prometheus-operator
    interval: 60s
    path: /
```
If you're deploying the chart and serviceMonitors via script I can recommend doing it with environment variable substitution:
```
KPS_RELEASE=test
envsubst < application-servicemonitor.yaml | kubectl apply -f -
```
For already deployed serviceMonitors just label them manually like so:
```
kubectl label servicemonitors.monitoring.coreos.com application-servicemonitor release=test
```

As you have already noticed, to enable discovery by a different label you have to modify your serviceMonitorSelector but then you must also modify the labels of the serviceMonitors deployed by the helm chart itself, otherwise they will not get picked up automatically. Also keep in mind the labelSelectors in K8s only select objects which have all the labels specified and not just one.

I hope this helps!

**Comment by brpaz** [comment]
@totoroot Your solution works. Thank you! I managed to get nginx-ingress service monitor working by setting the release label.

Still, I think having something similar as `defaultRules.labels`, which adds extra labels for all the `PrometheusRule` objects created by the chart, could make configuring service monitors more flexible.

Or I am missing some config. Because even, If I create a monitor in the same namespace as the prometheus-operator it´s not detected. Need really to have the release label.

**Comment by totoroot** [comment]
I haven't tried it myself as I don't mind adding the release label to my resources, especially using the method I described substituting the environment variables in the manifests, but I suspect you could match the labels like you suggested above and set the commonLabels at the very top of the values.yaml file:
```yaml
## Labels to apply to all resources
##
commonLabels:
  customlabel: custom

prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        customlabel: custom
```
I would suggest closing this issue since, even though I do not find it to be intuitive, that seems to be the desired behaviour.
