### ISSUE TITLE
[prometheus-alertmanager] Set PVC SC not work on Amazon EKS

### ISSUE THREAD

**Issue by kakafred** [prometheus-community/helm-charts#4339]
### Is your feature request related to a problem ?

Amazon EKS document - [Observability](https://docs.aws.amazon.com/eks/latest/userguide/eks-observe.html) - [Prometheus metrics](https://docs.aws.amazon.com/eks/latest/userguide/prometheus.html)

I have two SC in my Cluster, the default SC is "gp2".
![image](https://github.com/prometheus-community/helm-charts/assets/82210954/0f33b0a3-3dce-45e1-bd40-b957330fe924)

I found that using this command cannot successfully set the PVC of alertmanager, the PVC will use default SC:

```shell
helm upgrade -i prometheus prometheus-community/prometheus \
    --namespace prometheus \
    --set alertmanager.persistentVolume.storageClass="ebs-sc-gp3",server.persistentVolume.storageClass="ebs-sc-gp3"
```

After helm prometheus installation, when I use the get pvc command it returns the following:

![image](https://github.com/prometheus-community/helm-charts/assets/82210954/488daea1-289a-4a97-9cf6-f48e7cd143bb)

This is obviously not the result I want, alertmanager PVC is not set according to set and defines SC.

Finally, I found the reason in charts:

alertmanager - templates - sts.yaml

```yaml
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
      {{- if .Values.persistence.storageClass }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
      {{- end }}
  {{- else }}
        - name: storage
          emptyDir: {}
  {{- end }}
```

prometheus - templates - sts.yaml

```yaml
{{- if .Values.server.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.server.persistentVolume.statefulSetNameOverride | default "storage-volume" }}
        {{- if .Values.server.persistentVolume.annotations }}
        annotations:
{{ toYaml .Values.server.persistentVolume.annotations | indent 10 }}
        {{- end }}
        {{- if .Values.server.persistentVolume.labels }}
        labels:
{{ toYaml .Values.server.persistentVolume.labels | indent 10 }}
        {{- end }}
      spec:
        accessModes:
{{ toYaml .Values.server.persistentVolume.accessModes | indent 10 }}
        resources:
          requests:
            storage: "{{ .Values.server.persistentVolume.size }}"
      {{- if .Values.server.persistentVolume.storageClass }}
      {{- if (eq "-" .Values.server.persistentVolume.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.server.persistentVolume.storageClass }}"
      {{- end }}
      {{- end }}
{{- else }}
        - name: storage-volume
          emptyDir:
          {{- if .Values.server.emptyDir.sizeLimit }}
            sizeLimit: {{ .Values.server.emptyDir.sizeLimit }}
          {{- else }}
            {}
          {{- end -}}
{{- end }}
```

In the sts.yaml of alertmanager, the storage class definition of the persistent volume is completely different from that of prometheus. One uses persistence and the other uses persistentVolume.

### Describe the solution you'd like.

I hope the community can unify these variable names to let developers focus on productivity.

### Describe alternatives you've considered.

NONE
I'm not sure if this issue arises as a result of fixing another issue or if it affects the deployment of prometheus.
