### ISSUE TITLE
[kube-prometheus-stack] alertmanagerConfigMatcherStrategy.type: None doesn't work

### ISSUE THREAD

**Issue by vponoikoait** [prometheus-community/helm-charts#4343]
### Describe the bug a clear and concise description of what the bug is.
```
alertmanager:
  alertmanagerSpec:
    ...
    alertmanagerConfigMatcherStrategy:
      type: None
```
Doesn't provide expected results 

### What's your helm version?

version.BuildInfo{Version:"v3.13.3", GitCommit:"c8b948945e52abba22ff885446a1486cb5fd3474", GitTreeState:"clean", GoVersion:"go1.21.5"}

### What's your kubectl version?

Client Version: v1.28.2 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.28.5-eks-5e0fdde

### Which chart?

kube-prometheus-stack

### What's the chart version?

56.13.1

### What happened?

In a need of making config from AlertmanagerConfig to be set as a global I've tried to set up 
    alertmanagerConfigMatcherStrategy:
      type: None
But it still produced 
```
    matchers:
    - namespace="monitoring"
```

### What you expected to happen?

```
route:
  receiver: "null"
  group_by:
  - namespace
  continue: false
  routes:
  - receiver: monitoring/prometheus-based-alert-rules/slack-notifications
    group_by:
    - job
    matchers:
    - namespace="monitoring"
    continue: true
    routes:
    - receiver: monitoring/prometheus-based-alert-rules/slack-notifications
      continue: false
    group_wait: 30s
    group_interval: 1m
    repeat_interval: 5m
  - receiver: "null"
    matchers:
    - alertname="Watchdog"
    continue: false
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
```
I didn't expect 
```
    matchers:
    - namespace="monitoring"
```
Still to be present
### How to reproduce it?

Enable alertmanager, deploy AlertmanagerConfig 

### Enter the changed values of values.yaml?
```
alertmanager:
  alertmanagerSpec:
    ...
    alertmanagerConfigMatcherStrategy:
      type: None
```
### Enter the command that you execute and failing/misfunctioning.

helm install

### Anything else we need to know?

It is complicated to get any actual documentation on AlertmanagerConfig and how global routing should be implemented in a proper way.
