### ISSUE TITLE
[kube-prometheus-stack] Setting http_config proxy settings With Credentials/Secrets

### ISSUE THREAD

**Issue by pchang388** [prometheus-community/helm-charts#4358]
I couldn't find this in any other issue from my searching and was wondering what is the proper way to handle `proxy_url` properties in alertmanager `http_config` for proxies that require credentials, such as: `http://username:password.host.com`?

The kube-prometheus-stack alertmanager does not accept an `extraEnv` unlike the other standalone alertmanager helm chart available. How do we leverage `proxy_from_environment` in the `http_config` if we are unable to use such a feature? The other secrets are only mounted as a file in alertmanager, how can we avoid setting the `username:password` in plain text in the helm chart?

I'm thinking if the stack version accepted an `extraEnv` like the standalone one, you could just do:

```yaml
    extraEnv:
      - name: http_proxy
        valueFrom: 
          secretKeyRef:
            name: http-proxy-kube-prometheus-stack
            key: http_proxy
      - name: https_proxy
        valueFrom: 
          secretKeyRef:
            name: http-proxy-kube-prometheus-stack
            key: https_proxy
      - name: no_proxy
        value: ".internal,.svc.cluster.local,10.100.200.1"
```

**Comment by zeritti** [comment]
> The kube-prometheus-stack alertmanager does not accept an extraEnv unlike the other standalone alertmanager helm chart available.

This is correct. Prometheus and Alertmanager CRs are fully managed by Prometheus operator which does not support a direct means to set container's environment variables. Indirectly, though, it is possible through patching `containers` in [AlertmanagerSpec](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.AlertmanagerSpec), e.g. in the chart

```yaml
alertmanager:
  alertmanagerSpec:
    containers:
      - name: alertmanager
        envFrom:
          - secretRef:
              name: mysecret
```

> How do we leverage proxy_from_environment in the http_config if we are unable to use such a feature?

At the moment, we do not. Prometheus operator does not currently support alertmanager's configuration parameter `global.http_config.proxy_from_environment`, it does not recognise it as valid (similarly `no_proxy`, see #4234), i.e. such configuration will be rejected by the operator during the validation (alertmanager would not start at all at installation). Although one can set environment variables as shown above, it does not help as yet.
