### ISSUE TITLE
[prometheus-kube-stack] label too long > 63 chars

### ISSUE THREAD

**Issue by survivant** [prometheus-community/helm-charts#437]
**Describe the bug**
The PV and PVC won't be provisionning because the name is too long
````
 Warning  Provisioning  3m3s (x428 over 3h23m)  cstorvolumeclaim-controller  CStorVolume.cstor.openebs.io "pvc-47c63c31-4f90-43be-9ee5-70b466ab271f" is invalid: metadata.labels: Invalid value: "alertmanager-iep-kube-prometheus-stack-alertmanager-db-alertmanager-iep-kube-prometheus-stack-alertmanager-0": must be no more than 63 characters
````

I'm using a chart with kube-prometheus-stack as dependency
````
apiVersion: v2
name: iep
description: ccc
type: application
version: 0.1.8
appVersion: 1.0.0
dependencies:
   - name: kube-prometheus-stack
    version: 11.0.4
    repository: "@prometheus-community"
    condition: kube-prometheus-stack.enabled
 ````

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```

helm install iep . 

values.yaml 

````
kube-prometheus-stack:
  enabled: true
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: sc-iep-mirror
            resources:
              requests:
                storage: 300Mi
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: sc-iep-mirror
            resources:
              requests:
                storage: 300Mi
  grafana:
    grafana.ini:
      server:
        root_url: http://localhost:3000/grafana
````

````
root@test-pcl109:~# kubectl get pvc
NAME                                                                                                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
alertmanager-iep-kube-prometheus-stack-alertmanager-db-alertmanager-iep-kube-prometheus-stack-alertmanager-0   Bound    pvc-47c63c31-4f90-43be-9ee5-70b466ab271f   300Mi      RWO            sc-iep-mirror    3h34m
prometheus-iep-kube-prometheus-stack-prometheus-db-prometheus-iep-kube-prometheus-stack-prometheus-0           Bound    pvc-b8e75ab2-c1ab-48b9-9884-95fc18c599fe   300Mi      RWO            sc-iep-mirror    3h34m

````

The PV and PVC won't be provisionning because the name is too long
````
 Warning  Provisioning  3m3s (x428 over 3h23m)  cstorvolumeclaim-controller  CStorVolume.cstor.openebs.io "pvc-47c63c31-4f90-43be-9ee5-70b466ab271f" is invalid: metadata.labels: Invalid value: "alertmanager-iep-kube-prometheus-stack-alertmanager-db-alertmanager-iep-kube-prometheus-stack-alertmanager-0": must be no more than 63 characters
````

**Comment by survivant** [comment]
I was able to reduce a little bit the name for prometheus stack.. 

````
kube-prometheus-stack:
  fullnameOverride: kps
  nameOverride: kps

alertmanager:
    fullnameOverride: alert
    nameOverride: alert
````

but alertmanager override doesn't work


````
NAME                                         READY   STATUS              RESTARTS   AGE
alertmanager-kps-alertmanager-0              0/2     ContainerCreating   0          2m26s
prometheus-kps-prometheus-0                  2/2     Running             1          2m26s
````
