### ISSUE TITLE
[kube-prometheus-stack] Missing resource request and limit configuration

### ISSUE THREAD

**Issue by sourcehawk** [prometheus-community/helm-charts#4379]
### Is your feature request related to a problem ?

The Thanos sidecar cannot be configured with resource requests and limits. It is part of the prometheus statefulset deployment when enabled with `prometheus.thanosService.enabled`, but requests and limits are nowhere to be defined. I'm not even entirely sure about where the statefulset comes from as it is not defined in the helm chart. The sidecar uses around (150m - 200m) CPU credits in my case, so not negligible. 

### Describe the solution you'd like.

Thanos sidecar resource request and limit configuration added to the chart at `prometheus.thanosService.resources`

### Describe alternatives you've considered.

NONE

### Additional context.

desired values.yaml for kube-prometheus-stack
```yaml
prometheus:
  thanosService:
    # Configures resources for thanos sidecar
    resources: {}
      # requests:
      #   cpu: 150m
      #   memory: 100Mi
      # limits:
      #   cpu: 200m
      #   memory: 200Mi
```

**Comment by jkroepke** [comment]
I re-checked the Grafana configuration

https://github.com/grafana/helm-charts/blob/a439c9fe83c07bfb1437b35dbd1120f60aa4ba24/charts/grafana/values.yaml#L845

grafana.sidecar.resources works fine. I'm using it on a own deployment.

**Comment by sourcehawk** [comment]
> I re-checked the Grafana configuration
> 
> 
> 
> https://github.com/grafana/helm-charts/blob/a439c9fe83c07bfb1437b35dbd1120f60aa4ba24/charts/grafana/values.yaml#L845
> 
> 
> 
> grafana.sidecar.resources works fine. I'm using it on a own deployment.

Are you using kube-prometheus-stack to configure your grafana? Like I said, I know the configuration exists for the grafana helm chart, it just does not have any effect on the deployed sidecars when defined in kube-prometheus-stack. I have checked the deployed resources, and the sidecars do not have a resource and request limit on them.

If you can show me the request/resource limits set in your container specs for the sidecars then I'll take it as a problem on my side

**Comment by jkroepke** [comment]
Running the following command

``` 
helm template kube-prometheus-stack oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack --version 57.1.1 \
--set grafana.sidecar.resources.limits.cpu=1234m | grep 1234m
```

It generates manifests, where grep matches 1234m 2 times (datasource+dashboard sidecar)

**Comment by sourcehawk** [comment]
Hmm interesting... I see the limit being added in the template output as well.

I made sure to upgrade my chart to 57.1.1 to verify this, and after deleting the grafana deployment and redeploying, I still do not see the limits being applied to the sidecar pods.

**Comment by jkroepke** [comment]
Mention it also worked with version 50.0.0

> helm template kube-prometheus-stack oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack --version 50.0.0 --set grafana.sidecar.resources.limits.cpu=1234m | grep 1234m

Maybe something at your end does something wrong. Are you using kube-prometheus-stack as a sub-chart?

**Comment by sourcehawk** [comment]
Yes I'm using it as a subchart, could that be an issue?

**Comment by jkroepke** [comment]
Did you check the docs about override a values from a parent chart? https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart

In that case, you have to write this in your helm values file:

```yaml
kube-prometheus-stack:
  grafana:
    sidecar:
      # Configures resources for both datasource and dashboards sidecar
      resources: {}
      # requests:
      #   cpu: 25m
      #   memory: 100Mi
      # limits:
      #   cpu: 25m
      #   memory: 150Mi
  prometheus:
    thanosService:
      # Configures resources for thanos sidecar
      resources: {}
      # requests:
      #   cpu: 150m
      #   memory: 100Mi
      # limits:
      #   cpu: 200m
      #   memory: 200Mi
```

**Comment by sourcehawk** [comment]
That's exactly what it looks like on my end, I removed it from the discussion because I assumed it makes no difference.

**Comment by sourcehawk** [comment]
I have confirmed each of the following on a fresh kind cluster
1. Resource limits are set on the grafana sidecars when **not** using kube-prometheus-stack as a subchart
2. Resource limits are not set when using kube-prometheus-stack as a subchart :cry:

**Comment by jkroepke** [comment]
I have setup a chart like this

```yaml
apiVersion: v2
name: test
version: 0.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 57.1.0
    repository: oci://ghcr.io/prometheus-community/charts
```

Run `helm dep up` and execute:

```
% helm template kube-prometheus-stack . --set kube-prometheus-stack.grafana.sidecar.resources.limits.cpu=1234m | grep 1234m
              cpu: 1234m
              cpu: 1234m
```

**Comment by sourcehawk** [comment]
Okay I have just done the entire thing again on a kind cluster and for some reason it works now? :rofl: I have no idea what I was doing wrong last time... Anyhow, I went over my values again when scrolling down far enough, I think the problem becomes apparent; there are two `sidecar` definitions :sob: one likely overriding the other.

```yaml
grafana:
    enabled: true
    resources:
      requests:
        memory: 125Mi
        cpu: 75m
      limits:
        memory: 200Mi
        cpu: 150m
    sidecar:
      # Has no effect at the moment
      # https://github.com/prometheus-community/helm-charts/issues/4379
      resources:
        requests:
          memory: 100Mi
          cpu: 25m
        limits:
          memory: 150Mi
          cpu: 50m
    admin:
      existingSecret: <>
      userKey: <>
      passwordKey: <>
    plugins:
      - grafana-athena-datasource

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "DTE"
            orgId: 1
            folder: "DTE"
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /tmp/dashboards/DTE

    sidecar:
      dashboards:
        folder: "/tmp/dashboards"
        defaultFolderName: "default"
        folderAnnotation: "k8s-sidecar-target-directory"
        provider:
          allowUiUpdates: true
          # Allow Grafana to replicate dashboard structure from filesystem
          foldersFromFilesStructure: true
```

Thanks for the guidance, now only the thanos sidecar is left for discussion

**Comment by jkroepke** [comment]
Try this one:

```
prometheus:
  prometheusSpec:
    thanos:
      resources:
        requests:
          memory: 100Mi
          cpu: 25m
        limits:
          memory: 150Mi
          cpu: 50m 
```
