### ISSUE TITLE
[kube-prometheus-stack] Couldn't monitoring just specific namespaces

### ISSUE THREAD

**Issue by ellipsis-me** [prometheus-community/helm-charts#4394]
### Is your feature request related to a problem ?

no

### Describe the solution you'd like.

I´d like to know how to restrict the kube-prometheus-stack to monitoring some specific namespaces through a list passed in values.yaml
Something like:
```yaml
includedNamespacesMonitoring:
   - namespaceA
   - namespaceB
   -  namespaceC
```

### Describe alternatives you've considered.

I´ve tried to search in values this function, but a I couldn´t find anything

**Comment by zeritti** [comment]
Prometheus operator itself supports filtering namespaces through its flags, e.g. `namespaces`, `deny-namespaces`, etc. (ref. [operator](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/operator.md))

The chart makes the corresponding fields available (ref. [values](https://github.com/prometheus-community/helm-charts/blob/457c00097b18f46714f852030a48a5d1d368c5e6/charts/kube-prometheus-stack/values.yaml#L2468)):

```yaml
prometheusOperator:
  namespaces: {}
  denyNamespaces: []
  alertmanagerInstanceNamespaces: []
  alertmanagerConfigNamespaces: []
  prometheusInstanceNamespaces: []
  thanosRulerInstanceNamespace: []
```

If you set e.g. `prometheusOperator.namespaces`, the operator will query for resources from the given namespaces only when constructing Prometheus' configuration.
