### ISSUE TITLE
[kube-prometheus-stack] duplicate dashboard warning when adding JSON of file dashboards

### ISSUE THREAD

**Issue by felipeng** [prometheus-community/helm-charts#4405]
### Describe the bug a clear and concise description of what the bug is.

There is a conflict when adding dashboard via `grafana.dashboards` and `defaultDashboardsEnabled: true`, for example adding a dashboard via:
```yaml
grafana:
  dashboards:
    default:
      evse-grpc:
        json: |
          MY_DASHBOARD_JSON
```

The [grafana/templates/dashboards-json-configmap.yaml](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/dashboards-json-configmap.yaml) will create a ConfigMap and then it will [mount it via grafana deployment on grafana container](https://github.com/grafana/helm-charts/blob/7b857648f19018993987b343b2b1898c78c30cfb/charts/grafana/templates/_pod.tpl#L1155)

However, the [sidecar.dashboards](https://github.com/grafana/helm-charts/blob/7b857648f19018993987b343b2b1898c78c30cfb/charts/grafana/templates/_pod.tpl#L423) will also watch the ConfigMaps with `grafana_dashboard` label and load to Grafana

And the following warning happens because there are two providers adding the same dashboard:
```
msg="dashboards provisioning provider has no database write permissions because of duplicates" provider=default orgId=1
msg="dashboards provisioning provider has no database write permissions because of duplicates" provider=sidecarProvider orgId=1
msg="the same UID is used more than once" orgId=1 uid=VyVT5qHnz times=2 providers="[default sidecarProvider]"
msg="dashboard title is not unique in folder" orgId=1 title="EVSE GRPC calls" folderID=0 times=2 providers="[default sidecarProvider]"
```

### What's your helm version?

3.14.2

### What's your kubectl version?

1.24

### Which chart?

kube-prometheus-stack and grafana

### What's the chart version?

55.6.0

### What happened?

the same dashboard is saved on two different places and two providers are loading to grafana

### What you expected to happen?

dashboard added via `dashboards` should be added to Grafana via sidecard.dashboard or mounted on the grafana container 

### Enter the changed values of values.yaml?

```
grafana:
  enabled: true
    dashboards:
      enabled: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: default
        orgId: 1
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      evse-grpc:
        json: |
          MY_DASHBOARD
```

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus-community/kube-prometheus-stack --version 55.6.0 --values values.yaml
