### ISSUE TITLE
[Prometheus Operator CRDs] opt out CRDs

### ISSUE THREAD

**Issue by taind772** [prometheus-community/helm-charts#4411]
### Is your feature request related to a problem ?

Some other applications depend on Prometheus CRD to work:
- Grafana Agent
- VictoriaMetrics Agent

But those apps only use some CRDs, other CRDs are unnecessary and may confuse users.

### Describe the solution you'd like.

Add options to opt-out (or opt-in) of some CRDs:

```yaml
crds:
  includeAll: false # default true
  includes:
    - podmonitors
    - probes
```

### Describe alternatives you've considered.

-
