### ISSUE TITLE
[prometheus] Update extraScrapeConfigs from string to array in schema

### ISSUE THREAD

**Issue by naveengogu** [prometheus-community/helm-charts#4421]
### Describe the bug a clear and concise description of what the bug is.

<img width="996" alt="Screenshot 2024-04-06 at 1 55 47 PM" src="https://github.com/prometheus-community/helm-charts/assets/49301669/6ef1417f-47d5-4d0b-a133-e41224dfff06">

### What's your helm version?

v3.13.2

### What's your kubectl version?

v1.29.2

### Which chart?

prometheus

### What's the chart version?

25.15.0

### What happened?

<img width="996" alt="Screenshot 2024-04-06 at 1 55 47 PM" src="https://github.com/prometheus-community/helm-charts/assets/49301669/9c464cde-7ea0-4c53-ba48-6d3e6a8a0d28">

### What you expected to happen?

It should be string

### How to reproduce it?

add values to extraScrapeConfigs

### Enter the changed values of values.yaml?

extraScrapeConfigs:
  - job_name: 'prometheus-elasticsearch-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: 
        - http://elasticsearch-exporter-prometheus-elasticsearch-exporter.monitoring.svc.cluster.local:9108

### Enter the command that you execute and failing/misfunctioning.

helm upgrade prometheus prometheus-community/prometheus -n monitoring -f prometheus.yaml

**Comment by zeritti** [comment]
The required _string_ type is indicated by the empty string and the field's [comment](https://github.com/prometheus-community/helm-charts/blob/d26d47b5721ad6cadc3835a1275f60e13b0bd0e4/charts/prometheus/values.yaml#L1173):

> \# adds additional scrape configs to prometheus.yml
> \# must be a string so you have to add a | after extraScrapeConfigs:
> \# example adds prometheus-blackbox-exporter scrape config

```yaml
extraScrapeConfigs: |
  - job_name: 'prometheus-elasticsearch-exporter'
    metrics_path: /metrics
    static_configs:
      - targets:
        - http://elasticsearch-exporter-prometheus-elasticsearch-exporter.monitoring.svc.cluster.local:9108
```

**Comment by naveengogu** [comment]
@zeritti after adding above configuration got this error
```
Defaulted container "prometheus-server-configmap-reload" out of: prometheus-server-configmap-reload, prometheus-server
level=info ts=2024-04-06T15:38:46.800796917Z caller=main.go:137 msg="Starting prometheus-config-reloader" version="(version=0.71.2, branch=refs/tags/v0.71.2, revision=af2014407bdc25c4fc2b26cd99c9655235ebdf88)"
level=info ts=2024-04-06T15:38:46.800885293Z caller=main.go:138 build_context="(go=go1.21.6, platform=linux/amd64, user=Action-Run-ID-7656327832, date=20240125-14:58:54, tags=unknown)"
level=info ts=2024-04-06T15:38:46.801388786Z caller=reloader.go:246 msg="reloading via HTTP"
level=info ts=2024-04-06T15:38:46.801501206Z caller=reloader.go:282 msg="started watching config file and directories for changes" cfg= out= dirs=/etc/config
```

**Comment by zeritti** [comment]
Apologies, I did not pay enough attention to your values. A target is a hostname with an optional port number. Correct target is therefore

```yaml
...
static_configs:
  - targets:
    - elasticsearch-exporter-prometheus-elasticsearch-exporter.monitoring.svc.cluster.local:9108
```
