### ISSUE TITLE
Prometheus remote_write tls_skip_verify: true doesnt apply

### ISSUE THREAD

**Issue by silex27** [prometheus-community/helm-charts#4462]
Hello, 
Im installing prometheus with kube-prometheus stack and would need to do remote_write without tls verify to test something , but no matter if its added or not , its not working. 
`  prometheusSpec:
    tlsConfig:
      insecure_skip_verify: true`
`

`ts=2024-04-17T07:55:09.673Z caller=dedupe.go:112 component=remote level=warn remote_name=05909e url=https://infra-tools-prometheus.internal.com/api/v1/write msg="Failed to send batch, retrying" err="Post \"https://infra-tools-prometheus.internal.dpdgroup.com/api/v1/write\": tls: failed to verify certificate: x509: certificate signed by unknown authority"`

Version | 2.51.0

**Comment by zeritti** [comment]
The field has to be set in `remoteWrite.tlsConfig`(see [RemoteWriteSpec](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.RemoteWriteSpec)), e.g.

```yaml
prometheus:
  prometheusSpec:
    remoteWrite:
      - url: "https://someserver.local/endpoint"
        name: First
        tlsConfig:
          insecureSkipVerify: true
```
