### ISSUE TITLE
[kube-prometheus-stack] Unable to switch off metrics by namespace

### ISSUE THREAD

**Issue by irizzant** [prometheus-community/helm-charts#4464]
### Describe the bug a clear and concise description of what the bug is.

I have deployed the chart with
```yaml
kubelet:
    serviceMonitor:
        relabelings:
            - sourceLabels: [namespace]
              regex: 'test'
              action: drop
            - sourceLabels: [__meta_kubernetes_namespace]
              regex: 'test'
              action: drop
        metricRelabelings:
            - sourceLabels: [namespace]
              regex: 'test'
              action: drop
            - sourceLabels: [__meta_kubernetes_namespace]
              regex: 'test'
              action: drop
        cAdvisorMetricRelabelings:
            # Drop less useful container CPU metrics.
            - sourceLabels: [__name__]
              action: drop
              regex: 'container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)'
            # Drop less useful container / always zero filesystem metrics.
            - sourceLabels: [__name__]
              action: drop
              regex: 'container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)'
            # Drop less useful / always zero container memory metrics.
            - sourceLabels: [__name__]
              action: drop
              regex: 'container_memory_(mapped_file|swap)'
            # Drop less useful container process metrics.
            - sourceLabels: [__name__]
              action: drop
              regex: 'container_(file_descriptors|tasks_state|threads_max)'
            # Drop container spec metrics that overlap with kube-state-metrics.
            - sourceLabels: [__name__]
              action: drop
              regex: 'container_spec.*'
            # Drop cgroup metrics with no pod.
            - sourceLabels: [id, pod]
              action: drop
              regex: '.+;'
            - sourceLabels: [__meta_kubernetes_namespace]
              regex: 'test'
              action: drop
            - sourceLabels: [namespace]
              regex: 'test'
              action: drop
        cAdvisorRelabelings:
            - action: replace
              sourceLabels: [__metrics_path__]
              targetLabel: metrics_path
            - sourceLabels: [namespace]
              regex: 'test'
              action: drop
            - sourceLabels: [__meta_kubernetes_namespace]
              regex: 'test'
              action: drop
thanosRuler:
    thanosRulerSpec:
        ruleSelectorNilUsesHelmValues: false
prometheus:
    prometheusSpec:
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
```

I want to switch off cadvisor metrics coming from `test ` namespace.

When I query
container_cpu_usage_seconds_total{namespace="test"}

I still get 3 metrics:
```
container_cpu_usage_seconds_total{cpu="total", endpoint="https-metrics", id="/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podc99240aa_2aba_4e02_949d_a6cb0076bf96.slice", instance="172.18.0.5:10250", job="kubelet", metrics_path="/metrics/cadvisor", namespace="test", node="kind-worker3", pod="nginx", service="prometheus-kube-prometheus-kubelet"} | 0.070206

container_cpu_usage_seconds_total{cpu="total", endpoint="https-metrics", id="/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podc99240aa_2aba_4e02_949d_a6cb0076bf96.slice/cri-containerd-8f7388097b5037dbd3cae505a3a4eb81aa63118dc1d836bc4e7f830029fd5370.scope", image="registry.k8s.io/pause:3.7", instance="172.18.0.5:10250", job="kubelet", metrics_path="/metrics/cadvisor", name="8f7388097b5037dbd3cae505a3a4eb81aa63118dc1d836bc4e7f830029fd5370", namespace="test", node="kind-worker3", pod="nginx", service="prometheus-kube-prometheus-kubelet"} | 0.015278
container_cpu_usage_seconds_total{container="nginx", cpu="total", endpoint="https-metrics", id="/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podc99240aa_2aba_4e02_949d_a6cb0076bf96.slice/cri-containerd-75ba4b356f8eb64b3230d488763318f0cd806d574ec3c4741e4dcc3f16cfc9cd.scope", image="docker.io/library/nginx:latest", instance="172.18.0.5:10250", job="kubelet", metrics_path="/metrics/cadvisor", name="75ba4b356f8eb64b3230d488763318f0cd806d574ec3c4741e4dcc3f16cfc9cd", namespace="test", node="kind-worker3", pod="nginx", service="prometheus-kube-prometheus-kubelet"}
```

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: v1.29.4 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.29.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

58.1.3

### What happened?

When I query
container_cpu_usage_seconds_total{namespace="test"}

I still get 3 metrics:
```
container_cpu_usage_seconds_total{cpu="total", endpoint="https-metrics", id="/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podc99240aa_2aba_4e02_949d_a6cb0076bf96.slice", instance="172.18.0.5:10250", job="kubelet", metrics_path="/metrics/cadvisor", namespace="test", node="kind-worker3", pod="nginx", service="prometheus-kube-prometheus-kubelet"} | 0.070206

container_cpu_usage_seconds_total{cpu="total", endpoint="https-metrics", id="/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podc99240aa_2aba_4e02_949d_a6cb0076bf96.slice/cri-containerd-8f7388097b5037dbd3cae505a3a4eb81aa63118dc1d836bc4e7f830029fd5370.scope", image="registry.k8s.io/pause:3.7", instance="172.18.0.5:10250", job="kubelet", metrics_path="/metrics/cadvisor", name="8f7388097b5037dbd3cae505a3a4eb81aa63118dc1d836bc4e7f830029fd5370", namespace="test", node="kind-worker3", pod="nginx", service="prometheus-kube-prometheus-kubelet"} | 0.015278
container_cpu_usage_seconds_total{container="nginx", cpu="total", endpoint="https-metrics", id="/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podc99240aa_2aba_4e02_949d_a6cb0076bf96.slice/cri-containerd-75ba4b356f8eb64b3230d488763318f0cd806d574ec3c4741e4dcc3f16cfc9cd.scope", image="docker.io/library/nginx:latest", instance="172.18.0.5:10250", job="kubelet", metrics_path="/metrics/cadvisor", name="75ba4b356f8eb64b3230d488763318f0cd806d574ec3c4741e4dcc3f16cfc9cd", namespace="test", node="kind-worker3", pod="nginx", service="prometheus-kube-prometheus-kubelet"}
```

### What you expected to happen?

No metrics

### How to reproduce it?

* Deploy the chart
* Create test namespace
* Run an nginx pod in that namespace
* Query container_cpu_usage_seconds_total{namespace="test"}

### Enter the command that you execute and failing/misfunctioning.

Query container_cpu_usage_seconds_total{namespace="test"} and verify there are 3 metrics
