### ISSUE TITLE
[prometheus] incorrect metrics returned for host

### ISSUE THREAD

**Issue by thameezb** [prometheus-community/helm-charts#447]
**Describe the bug**
Currently node-exporter running within the prometheus chart returns dodgy host metrics. 
An example:
- metric `node_filesystem_avail_bytes` does not currently return all mountpoints for given nodes. Nor does it return correct values for the given metric 

Incorrect results 
![image](https://user-images.githubusercontent.com/13134870/101021375-86de5f00-3578-11eb-909b-9833bf9e8bdc.png)

Correct results (ignore the node name as I was testing my fix in my DEV env)
![image](https://user-images.githubusercontent.com/13134870/101021490-a6758780-3578-11eb-9677-a78184ec43d3.png)

**Version of Helm and Kubernetes**:
Helm Version: 3.4.0
K8s Version: 1.19.2

**Actual issue**
Fix was actually found by deploying https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-node-exporter. 
Chart [promtheus] currently does not set the flag `path.rootfs=/host/root` (nor does it do the appropriate mounts).

Therefore quick fix would be to add to `values.yml`
```
...
nodeExporter:
...
  extraArgs: 
    path.rootfs: /host/root
  extraHostPathMounts: 
    - name: root
      mountPath: /host/root
      hostPath: /
      readOnly: true
      mountPropagation: HostToContainer
...
```

However a longer term/better fix would be to add this mount automatically to the chart
