### ISSUE TITLE
[kube-promethsus-stack] analytics not included?

### ISSUE THREAD

**Issue by sojjan1337** [prometheus-community/helm-charts#4489]
### Is your feature request related to a problem ?

It seems that analytics is not present. I'm trying to disable it by:
But with no luck.

```
grafana:
  enabled: true
  analytics:
    reporting_enabled: false
    check_for_updates: false
    check_for_plugins_updates: false
```

### Describe the solution you'd like.

Include analytics.

### Describe alternatives you've considered.

nopp

**Comment by sojjan1337** [comment]
using kube-prometheus-stack-57.2.0

**Comment by zeritti** [comment]
> It seems that analytics is not present. I'm trying to disable it by:
But with no luck.

Those are configuration file parameters (see Grafana chart's [values](https://github.com/grafana/helm-charts/blob/3845cfde6256dc69ddea10c90a2ed65b63d04653/charts/grafana/values.yaml#L765)):

```yaml
grafana:
  grafana.ini:
    analytics:
     check_for_updates: false
     reporting_enabled: false
     check_for_plugins_updates: false
```
