### ISSUE TITLE
[kube-prometheus-stack] group grafana dashboards in folders

### ISSUE THREAD

**Issue by marcofranssen** [prometheus-community/helm-charts#4493]
### Is your feature request related to a problem ?

Give more structure to the dashboards in Grafana folders.

### Describe the solution you'd like.

I would like to have a way to structure the grafana dashboards in folders.

From following chart I see 2 options:

- https://artifacthub.io/packages/helm/grafana/grafana?modal=values&path=sidecar.dashboards.provider.foldersFromFilesStructure
- https://artifacthub.io/packages/helm/grafana/grafana?modal=values&path=sidecar.dashboards.folderAnnotation

e.g. All the Kubernetes / dashboards could go in a Kubernetes folder. Or we make it somehow configurable via option 2 using those annotations.

Maybe it is already possible with the current chart, but I can't really figure it out at the moment on how to do that. In that case some documentation might be great to tell users of the chart how to do this.

Anyone with more deep knowledge in this chart who knows how to achieve that?

### Describe alternatives you've considered.

Provisioning all the dashboards myself and disable the default shipped dashboards.

**Comment by jkroepke** [comment]
Lets wait for Grafana 11, then we may able to benefit from the sub-folder structor. What did you think about?

**Comment by marcofranssen** [comment]
> Lets wait for Grafana 11, then we may able to benefit from the sub-folder structor. What did you think about?

If that makes it easier. Would already be happy to group some stuff in one level of folders.

**Comment by jkroepke** [comment]
Grafana 11 release is less then four weeks, dated for mid may.

**Comment by jkroepke** [comment]
Set grafana.defaultDashboardsEnabled=false in values

**Comment by robinderooij-rl** [comment]
Just put the following in your `values.yaml`:

```
grafana:
  sidecar:
    dashboards:
      annotations:
        grafana_folder: "kubernetes"
      folderAnnotation: "grafana_folder"
     provider:
       foldersFromFilesStructure: true
```

Your custom dashboards can be organized by using the `grafana_folder` label in your configmap.

**Comment by sstewart-alterra** [comment]
For more detail on @robinderooij-rl's answer, there's another comment here that I found helpful: https://github.com/grafana/helm-charts/issues/527#issuecomment-982319638

**Comment by gera-corp** [comment]
> grafana:
>   sidecar:
>     dashboards:
>       annotations:
>         grafana_folder: "kubernetes"
>       folderAnnotation: "grafana_folder"
>      provider:
>        foldersFromFilesStructure: true

grafana:
  sidecar:
    dashboards:
      annotations:
        grafana_folder: "kubernetes"
      folderAnnotation: "grafana_folder"
      provider:
        foldersFromFilesStructure: true

**Comment by gera-corp** [comment]
```
grafana:
  sidecar:
    dashboards:
      annotations:
        grafana_folder: "kubernetes"
      folderAnnotation: "grafana_folder"
      provider:
        foldersFromFilesStructure: true
```

**Comment by mbauer-dilt** [comment]
For anybody coming in here almost a year after this conversation is over, the solution mentioned by @robinderooij-rl does work, however, the formatting of their example is a bit off, which caused me a headache and made me actually go look through the the grafana helm chart source.

So here it is with some better formatting:

``` 
  sidecar:
    dashboards:
      folderAnnotation: "grafana_folder"
      provider:
        foldersFromFilesStructure: true
  defaultDashboardsEnabled: false
```

Note that it is grafana.sidecar.dashboards.provider.foldersFromFilesStructure 
not grafana.sidecar.provider.foldersFromFilesStructure. 
This is probably just an issue caused by copy pasting but from the above formatting it was really unclear - at least to me.
