### ISSUE TITLE
Sharing Alerts Between Services in alerting_rules.yml

### ISSUE THREAD

**Issue by vitaliy-savchenkov** [prometheus-community/helm-charts#450]
Hello!
Is there a way to add alerts from multiple yam files in alerting_rules.yml?
For alert file its work
```
# service1-alert.yaml
serverFiles:
  alerts:
    service1:
      - alert: anAlert
      # ...

# service2-alert.yaml
serverFiles:
  alerts:
    service2:
      - alert: anAlert
      # ...
```
But for alerting_rules.yml its not work, everything is replaced by the last file
```
# service1-alert.yaml
serverFiles:
  alerting_rules.yml:
    groups:
    - name: test
      rules:
      - alert: 1_test
      # ...

# service2-alert.yaml
serverFiles:
  alerting_rules.yml:
    groups:
    - name: test2
      rules:
      - alert: 2_test
      # ...
```
How can I do that?
