### ISSUE TITLE
[kube-prometheus-stack] deployment via argocd stuck in "pending deletion" for kube-prometheus-stack-admission-create job

### ISSUE THREAD

**Issue by jkleinlercher** [prometheus-community/helm-charts#4500]
### Describe the bug a clear and concise description of what the bug is.

When deploying kube-prometheus-stack with argocd sometimes it gets stuck in "pending deletion" for object job kube-prometheus-stack-admission-create. We need to terminate the argocd sync and resync manually to get out of this situation, which is obviously not good in terms of full automation.

![image](https://github.com/prometheus-community/helm-charts/assets/11465610/f18361d5-49d7-4071-b650-3cb46d250449)

According to https://github.com/argoproj/argo-cd/issues/6880 this is a well known problem when a PreHook Job has a 

```
ttlSecondsAfterFinished: 0
```

defined, because then kubernetes deletes this job immediatly after it finished and also argocd wants to delete this job and so we have some kind of race condition here.

I would propose to make the value for ttlSecondsAfterFinished in https://github.com/prometheus-community/helm-charts/blob/9c41858ac9714483638d78fb560577dc37e55875/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml#L19 configurable via a helm value.

### What's your helm version?

3.14.3

### What's your kubectl version?

v1.29.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

58.2.2

### What happened?

When deploying kube-prometheus-stack with argocd sometimes it gets stuck in "pending deletion" for object job kube-prometheus-stack-admission-create. We need to terminate the argocd sync and resync manually to get out of this situation, which is obviously not good in terms of full automation.

### What you expected to happen?

the argocd sync of this chart works without failures are stuck problems

### How to reproduce it?

setup an argocd application with

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-jokl
spec:
  destination:
    name: ''
    namespace: jokl-test
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 58.2.2
    chart: kube-prometheus-stack
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
 ```

since it is a race condition it doesn't happen always, but very often

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

n.a.

**Comment by jkleinlercher** [comment]
Right after creating this issue and creating a PR for this issue I recognized that ttlSecondsAfterFinished is not set at all because there was a "batch/v1alpha1" condition around this attribute, which is not met in current clusters

https://github.com/prometheus-community/helm-charts/blob/9c41858ac9714483638d78fb560577dc37e55875/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml#L17-L20

 ... so I need to investigate again .. I leave this issue open but please consider it as still under investigations

**Comment by rouke-broersma** [comment]
Funnily enough we never ran into this issue before this change, but now we need to set the `ttlSecondsAfterFinished` because we consistently get this error 😂

**Comment by Sispheor** [comment]
Hello there 👋. We tried to mentioned above  above but jobs were still deleted in a loop.

Following the argo doc:

> HookSucceeded - The resource will be deleted after it has succeeded.

So once the job is successfull, argo will delete it, and the prom operator will create it again. My understanding is that we need to use 

> HookFailed - The resource will be deleted if it has failed.

Tested and this time working fine on our side:
```yaml
prometheusOperator:
  enabled: true
  createCustomResource: true
  admissionWebhooks:
    enabled: true

    annotations:
      argocd.argoproj.io/hook: PreSync
      argocd.argoproj.io/hook-delete-policy: HookFailed

    patch:
      annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: HookFailed

    mutatingWebhookConfiguration:
      annotations:
        argocd.argoproj.io/hook: PreSync

    validatingWebhookConfiguration:
      annotations:
        argocd.argoproj.io/hook: PreSync

```

**Comment by jkroepke** [comment]
```
    mutatingWebhookConfiguration:
      annotations:
        argocd.argoproj.io/hook: PreSync

    validatingWebhookConfiguration:
      annotations:
        argocd.argoproj.io/hook: PreSync
```

That make no sense to me. 

https://github.com/prometheus-community/helm-charts/blob/0c7bf42ac2265d13845ffe0c499d16e6b8cdedea/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml#L2-L10

That are persistent manifests, which should be not deleted or declared as hook.
