### ISSUE TITLE
[kube-prometheus-stack] Change Grafana database type?

### ISSUE THREAD

**Issue by Dunge** [prometheus-community/helm-charts#4505]
### Is your feature request related to a problem ?

Grafana uses by default a SQLite database. This database doesn't play nice with network shares volumes like EFS. My goal is actually to prevent false alerts saying "database is locked" as reported [here](https://community.grafana.com/t/database-is-locked/87028/15) (see my last comment as Dunge21). The solution seems to be to switch to use to MySQL or PostgreSQL as documented [here](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#database)

### Describe the solution you'd like.

An entry in the [values.yaml](https://github.com/prometheus-community/helm-charts/blob/d23700cbbda8068a2a3c7b32030a1ff70a3299ae/charts/kube-prometheus-stack/values.yaml) file to select between sqlite/mysql/postgre

### Describe alternatives you've considered.

Changing my volume to an EBS, but then it's not multi-AZ resiliant

**Comment by DrFaust92** [comment]
The operator chart use grafana chart as a dep, you are able to override any way you want as you can grafana via its values.

```
grafana.ini:
  database:
    type: mysql
```

**Comment by Dunge** [comment]
Ok thank you, I missed that grafana.ini section cause it was not part of the sample values.yaml file but of course it's a dep on the grafana chart who contains it [here](https://github.com/grafana/helm-charts/blob/f073467308b5ef0fb57e53d3134703d25f73bcf0/charts/grafana/values.yaml#L765).

I also realize this needs to point to an existing external database and there's no mechanism to deploy a mysql instance along with the chart, so that complexify things a bit. But thanks, it answers my question about the chart values.

**Comment by brenwell** [comment]
It took me a while to work this out so I thought I might add my solution for connecting to PG with a secret

```yaml
...
grafana:
  adminUser: admin
  grafana.ini:
    database:
      type: postgres
      host: awesome-pg-server.com:5432  # Use the service name of the PostgreSQL instance
      name: grafana
      user: grafana_rw
      ssl_mode: require
      password: $__file{/etc/secrets/password}  # Securely fetches password from file

  extraSecretMounts:
    - name: grafana-db-secret
      secretName: grafana-rw  # Use the existing secret
      mountPath: /etc/secrets
      readOnly: true
...
```
