### ISSUE TITLE
[kube-prometheus-stack] Set pod labels for the pod prometheus-prom-stack-kube-prometheus-prometheus-0 from the values.yaml

### ISSUE THREAD

**Issue by jordan-owen** [prometheus-community/helm-charts#4529]
### Is your feature request related to a problem ?

When setting the following in the values.yaml (or using any other `labels` in the Helm chart values.yaml), labels remain unuset for the pod `prometheus-prom-stack-kube-prometheus-prometheus-0`, which is created by StatefulSet `prometheus-prom-stack-kube-prometheus-prometheus`.

```
# values.yaml
commonLabels:
  azure.workload.identity/use: "true"
```

I'm trying to set the label `azure.workload.identity/use: "true"` so I can get the thanos-sidecar container to use Azure WorkloadIdentity.

### Describe the solution you'd like.

I'd like to set `commonLabels` to apply to all downstream resources created by the Helm chart.

### Describe alternatives you've considered.

NONE

**Comment by jordan-owen** [comment]
I figured it out. I needed to set the following:

```yaml
prometheus
  prometheusSpec:
    podMetadata:
      labels:
        azure.workload.identity/use: "true"
```
