### ISSUE TITLE
[kube-prometheus-stack] Migrate data from EmptyDir to StorageClass

### ISSUE THREAD

**Issue by shukurew** [prometheus-community/helm-charts#4579]
### Describe the bug a clear and concise description of what the bug is.

I noticed in production we are using prometheus-kube-stack with EmptyDir storage
So I'm trying to migrate datas of Prometheus, Alertmanager and ThanosRuler from EmptyDir to StorageClass 
as there more than 500 dashboard and rules 

I could not find any releated document to this. So guide me plz 
I'm afraid of losting datas.

If I update my Helm-chart with below StorageClass values all my existing datas will gone.

So I'm planning deploy prometheus-kube-stack in another namespace but how I copy datas from EmptyDir

```
    storageSpec:
      ## Using PersistentVolumeClaim
      ##
      volumeClaimTemplate:
        spec:
          storageClassName: ""
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
        selector:
          matchLabels:
            app: prometheus

```

### What's your helm version?

3

### What's your kubectl version?

1.28.7

### Which chart?

kube-prometheus-stack

### What's the chart version?

54.2.2

### Enter the command that you execute and failing/misfunctioning.

```
storageSpec:
      ## Using PersistentVolumeClaim
      ##
      volumeClaimTemplate:
        spec:
          storageClassName: ""
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
        selector:
          matchLabels:
            app: prometheus
```
