### ISSUE TITLE
[prometheus-node-exporter] node exporter does not scrape __meta_kubernetes_node_label_

### ISSUE THREAD

**Issue by nessa829** [prometheus-community/helm-charts#4584]
### Describe the bug a clear and concise description of what the bug is.

I am using prometheus-node-exporter subchart in kube-prometheus-stack chart. 
however, i cannot find node labels like karpenter tags in discovered label. (__meta_kubernetes_node_label_(.+) )
I need to relabel the nodeType label as a target, but i can't because it was not discovered in the first place. 

below is my values. 

### What's your helm version?

3.10.0

### What's your kubectl version?

1.30

### Which chart?

prometheus-node-exporter

### What's the chart version?

57.2.0

### What happened?

however, i cannot find node labels like karpenter tags in discovered label. (__meta_kubernetes_node_label_(.+) )

### What you expected to happen?

there are __meta_kubernetes_node_label_(.+) in node-exporter discovered labels. 

### How to reproduce it?

N/A

### Enter the changed values of values.yaml?

```
prometheus-node-exporter:
  namespaceOverride: ""
  podLabels:
    ## Add the 'node-exporter' label to be used by serviceMonitor to match standard common usage in rules and grafana dashboards
    ##
    jobLabel: node-exporter
  releaseLabel: true
  extraArgs:
    - --collector.ethtool
    - --collector.ethtool.device-exclude="^(brq|tap|veth|vxlan|virbr|usb).*$"
    - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
    - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
  service:
    portName: http-metrics
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 256Mi
  prometheus:
    monitor:
      enabled: true

      jobLabel: jobLabel

      additionalLabels:
        monitoring: prometheus

      ## Scrape interval. If not set, the Prometheus default scrape interval is used.
      ##
      interval: ""

      ## SampleLimit defines per-scrape limit on number of scraped samples that will be accepted.
      ##
      sampleLimit: 0

      ## TargetLimit defines a limit on the number of scraped targets that will be accepted.
      ##
      targetLimit: 0

      ## Per-scrape limit on number of labels that will be accepted for a sample. Only valid in Prometheus versions 2.27.0 and newer.
      ##
      labelLimit: 0

      ## Per-scrape limit on length of labels name that will be accepted for a sample. Only valid in Prometheus versions 2.27.0 and newer.
      ##
      labelNameLengthLimit: 0

      ## Per-scrape limit on length of labels value that will be accepted for a sample. Only valid in Prometheus versions 2.27.0 and newer.
      ##
      labelValueLengthLimit: 0

      ## How long until a scrape request times out. If not set, the Prometheus default scape timeout is used.
      ##
      scrapeTimeout: ""

      ## proxyUrl: URL of a proxy that should be used for scraping.
      ##
      proxyUrl: ""

      ## MetricRelabelConfigs to apply to samples after scraping, but before ingestion.
      ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
      ##
      metricRelabelings: []
      # - sourceLabels: [__name__]
      #   separator: ;
      #   regex: ^node_mountstats_nfs_(event|operations|transport)_.+
      #   replacement: $1
      #   action: dropf

      ## RelabelConfigs to apply to samples before scraping
      ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
      ##
      relabelings: []
      # - sourceLabels: [__meta_kubernetes_pod_node_name]
      #   separator: ;
      #   regex: ^(.*)$
      #   targetLabel: nodename
      #   replacement: $1
      #   action: replace
  rbac:
    ## If true, create PSPs for node-exporter
    ##
    pspEnabled: false
```

### Enter the command that you execute and failing/misfunctioning.

N/A

### Anything else we need to know?

N/A
