### ISSUE TITLE
[prometheus] How to enable Service Monitor

### ISSUE THREAD

**Issue by jackchuong** [prometheus-community/helm-charts#4634]
### Is your feature request related to a problem ?

Hi all,
I installed prometheus , grafana by individual charts : prometheus-community/prometheus , grafana/grafana
I want to enable Service Monitor for prometheus like below
```
prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
      mykey: myvalue
```
Is this possible ? Or I have to use prometheus-community/kube-prometheus-stack and set grafana.enabled to false ?

### Describe the solution you'd like.

prometheus-community/prometheus values support option to enable Service Monitor

### Describe alternatives you've considered.

I don't know.
