### ISSUE TITLE
[alertmanager] Can't import alertmanager chart with cdk8s due to schema issue

### ISSUE THREAD

**Issue by yuriy-yarosh** [prometheus-community/helm-charts#4689]
### Describe the bug a clear and concise description of what the bug is.

`npx cdk8s import` 

```yaml
language: typescript
app: yarn tsx stack.ts
imports:
  - helm:https://prometheus-community.github.io/helm-charts/alertmanager@1.11.0
```

results in 
```
Error: unable to find a definition for the $ref "config/route"
```
Which may have to do something with [schema](https://github.com/prometheus-community/helm-charts/blob/main/charts/alertmanager/values.schema.json#L222).

### What's your helm version?

3.15.2

### What's your kubectl version?

1.30.2

### Which chart?

Alertmanager

### What's the chart version?

1.11.0

### What happened?

Can't import alertmanager chart with cdk8s, possible due to schema issue.

### What you expected to happen?

To be able to import it

### How to reproduce it?

Init a project with `npx cdk8s init typescript-app` 

create `cdk8s.yaml` file with
```yaml
language: typescript
app: yarn tsx stack.ts
imports:
  - helm:https://prometheus-community.github.io/helm-charts/alertmanager@1.11.0
```
run `npx cdk8s import` 

### Enter the command that you execute and failing/misfunctioning.

npx cdk8s import
