### ISSUE TITLE
prometheus-kube-stack passing values into deployment using ArgoCD

### ISSUE THREAD

**Issue by juhisxd** [prometheus-community/helm-charts#4691]
### Describe the bug a clear and concise description of what the bug is.

I have issue that deployment doesnt use parameters from application
My setup is like this
prometheus-operator
├── Chart.yaml
└── values.yaml
Chart.yaml contents
```
apiVersion: v2
name: prometheus-operator
type: application
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: "57.0.1"
    repository: https://prometheus-community.github.io/helm-charts
 ```
  values.yaml contents
```
prometheus-operator:
  nameOverride: prometheus-operator
  prometheus:
    agentMode: true
  alertmanager:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false
  kubeEtcd:
    enabled: false
  grafana:
    enabled: false
```

I can see from ArgoUI app parameters that these values are propagated there, but still argo deploys grafana, alertmanager etc and prometheus is not in agent.

Parameters:
PARAMETERS
prometheus-operator.alertmanager.enabled
false
prometheus-operator.grafana.enabled
false
prometheus-operator.kubeControllerManager.enabled
false
prometheus-operator.kubeEtcd.enabled
false
prometheus-operator.kubeProxy.enabled
false
prometheus-operator.kubeScheduler.enabled
false
prometheus-operator.nameOverride
prometheus-operator
prometheus-operator.prometheus.agentMode
true

When running helm template those values are not in the template

### What's your helm version?

Argo

### What's your kubectl version?

argo

### Which chart?

kube-prometheus-stack

### What's the chart version?

57.0.1

### Enter the command that you execute and failing/misfunctioning.

helm template . --name-template kube-prometheus-stack --namespace kube-prometheus-stack --kube-version 1.28 --values values.yaml
