### ISSUE TITLE
[kube-prometheus-stack] Ability to set resource limits/request for kube-state-metrics and prometheus-node-exporter

### ISSUE THREAD

**Issue by t0a5tbr0t** [prometheus-community/helm-charts#4692]
### Is your feature request related to a problem ?

No, this request is not related to a problem - its more about a wish for enhancement:
I would like to set the resources limits and requests for kube-state-metrics and prometheus-node-exporter. 
Unfortunately there are no values available within the kube-prometheus-stack chart, even though the dependency charts kube-state-metrics and prometheus-node-exporter both support setting up these values.

It would be highly appreciated to have this option also directly within the kube-prometheus-stack chart. 
Thank you!

### Describe the solution you'd like.

Additional values to define resources limits and requests for kube-state-metrics and prometheus-node-exporter within values.yaml for kube-prometheus-stack:

```
kube-state-metrics:
      ## Resource limits & requests
      ##
      resources: {}

prometheus-node-exporter:
      ## Resource limits & requests
      ##
      resources: {}
```

### Describe alternatives you've considered.

NONE
