### ISSUE TITLE
[prometheus] How to enable HTTPs for accessing prometheus and alermanager.

### ISSUE THREAD

**Issue by chetanatole** [prometheus-community/helm-charts#4705]
For kube-prometheus-stack chart, updating the prometheus custom resource as mentioned [here](https://github.com/prometheus-community/helm-charts/issues/2828) enables HTTPs for communication, how do I achieve this using prometheus-community/prometheus chart with values.yaml?

**Comment by zeritti** [comment]
If you wish to configure TLS at Prometheus, you can do that as described briefly in the example below (TLS client authentication is not being configured, though). It is a few steps that could be made probably a bit easier in the chart.

If the goal were protecting just the Prometheus UI, the simplest approach would be by means of an ingress and letting the ingress controller terminate TLS.

1. Create a secret with TLS items, i.e. key and certificate
2. Create a secret with a web-config file [[Ref](https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md)] like for example

```yaml
tls_server_config:
  cert_file: /etc/secrets/tls.crt
  key_file: /etc/secrets/tls.key
  min_version: TLS12
```
3. Configure `server.extraSecretMounts` to mount the secrets as volumes
4. Adjust `scheme` at probes to HTTPS
5. Adjust scheme in `configmapReload.reloadUrl`. config-reloader seems to skip verifying the certificate issuer.
6. Set flag _web.config.file_ in `server.extraArgs` pointing to the path of the web-config file
7. Adjust server's service port number if desired to 443

In the end, the change would look like this:

```yaml
server:
  extraSecretMounts:
  - name: prometheus-tls
    mountPath: /etc/secrets
    secretName: prometheus-tls
    readOnly: true
  - name: prometheus-web-config
    mountPath: /etc/web
    secretName: prometheus-web-config
    readOnly: true

  service:
    servicePort: 443

  extraArgs:
    web.config.file: "/etc/web/web-config.yml"

  probeScheme: HTTPS

configmapReload:
  reloadUrl: "https://localhost:9090/-/reload"
```

Similarly for alertmanager (config-reloader is disabled by default in that chart). You would have to adjust discovery of alertmanagers, as e.g. scheme would change to https. Instead of relying on already configured discovery one could set the discovery of alertmanagers specifically in the `server.alertmanagers` field.
