### ISSUE TITLE
[kube-prometheus-stack] prometheus ClusterRole missing permissions for kube-state-metrics when kube-rbac-proxy is enabled

### ISSUE THREAD

**Issue by hmonsalv** [prometheus-community/helm-charts#4709]
### Describe the bug a clear and concise description of what the bug is.

When enabling `kube-rbac-proxy` in `node-exporter` and `kube-state-metrics`, the [following permission](https://github.com/prometheus-community/helm-charts/blob/5dcc890bbb5cb1d8c952835067332e39efec0ca4/charts/kube-prometheus-stack/templates/prometheus/clusterrole.yaml#L28) is added in `prometheus` ClusterRole:

```yaml
- apiGroups: [ "" ]
  resources:
  - services/kube-prometheus-stack-prometheus-node-exporter
  verbs: [ "get", "list", "watch" ]
```

But the corresponding one for `services/kube-prometheus-stack-kube-state-metrics` is not added.

As a result, prometheus is not able to scrap metrics with the ServiceMonitor defined for `kube-state-metriscs`:
![CleanShot 2024-07-10 at 12 29 06](https://github.com/prometheus-community/helm-charts/assets/6095559/5c372c3c-70eb-4a87-a739-20dc3c74cbbd)

Adding this additional permissions in the helm chart values fixes the issue:

```yaml
prometheus:
  additionalRulesForClusterRole:
  - apiGroups: [ "" ]
    resources: [ "services/kube-prometheus-stack-kube-state-metrics" ]
    verbs: [ "get", "list", "watch" ]
```

![CleanShot 2024-07-10 at 14 24 16](https://github.com/prometheus-community/helm-charts/assets/6095559/b5b35491-b50d-418b-846e-ff56242f896f)

### What's your helm version?

version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}

### What's your kubectl version?

Client Version: v1.28.0 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.30.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

61.1.1

### What happened?

See description of the bug above.

### What you expected to happen?

When `kube-rbac-proxy` is enabled for `kube-state-metrics`, then the prometheus ClusterRole is set to add the required permission:

```yaml
  - apiGroups: [ "" ]
    resources: [ "services/kube-prometheus-stack-kube-state-metrics" ]
    verbs: [ "get", "list", "watch" ]
```

### How to reproduce it?

Install helm chart enabling `kube-rbac-proxy` for `kube-state-metrics`:

```yaml
## Configuration for kube-state-metrics
kube-state-metrics:
  kubeRBACProxy:
    enabled: true
  prometheus:
    monitor:
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
```

Port-forward prometheus pod, and check the targets, `kube-state-metrics` should report an authentication error as follows:
![CleanShot 2024-07-10 at 12 29 06](https://github.com/prometheus-community/helm-charts/assets/6095559/a9c06ebf-2fce-45a0-af8b-816e1d66ea17)

### Enter the changed values of values.yaml?

To fix the issue, as specified in description it was needed to add to the `values.yaml`:

```yaml
prometheus:
  additionalRulesForClusterRole:
  - apiGroups: [ "" ]
    resources: [ "services/kube-prometheus-stack-kube-state-metrics" ]
    verbs: [ "get", "list", "watch" ]
```

My proposal is to add it directly in the template as done for `node-exporter` [here](https://github.com/prometheus-community/helm-charts/blob/5dcc890bbb5cb1d8c952835067332e39efec0ca4/charts/kube-prometheus-stack/templates/prometheus/clusterrole.yaml#L28).

### Enter the command that you execute and failing/misfunctioning.

```bash
helm template kube-prometheus-stack prometheus-community/kube-prometheus-stack  \
		--version 61.1.1 -n monitoring -f values.yaml \
		> kube-prometheus-stack.yaml
```
