### ISSUE TITLE
[prometheus-node-exporter] Prevent node exporter from being scheduled on fargate

### ISSUE THREAD

**Issue by mariuskimmina** [prometheus-community/helm-charts#4735]
### Is your feature request related to a problem ?

When running on EKS clusters with a mix of fargate and EC2 nodes the node exporter pods can end up unschedulable and stuck in a pending state. 

### Describe the solution you'd like.

Add a  `nodeAffinity` to the node-exporter by default

```
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: eks.amazonaws.com/compute-type
            operator: NotIn
            values:
            - fargate
 ```

### Describe alternatives you've considered.

None

### Additional context.

There have been many previous Issues about this:

https://github.com/prometheus-community/helm-charts/issues/2876
https://github.com/prometheus-community/helm-charts/issues/2908
https://github.com/prometheus-community/helm-charts/issues/925

Grafanas [k8s-monitoring charts](https://github.com/grafana/k8s-monitoring-helm) have also added a node affinity to the node-exporter by default which prevents it from running on fargate - see https://github.com/grafana/k8s-monitoring-helm/pull/362. 
I think it would be useful to do the same here. 

If my understanding is correct, then for people that have already added this `nodeAffinity` this would not be a breaking change, it would simply be redundant - but this I am not completely sure about.
