### ISSUE TITLE
Cant enable --web.enable-remote-write-receiver in prometheus-community/prometheus

### ISSUE THREAD

**Issue by Barsonax** [prometheus-community/helm-charts#4750]
### Is your feature request related to a problem ?

Cant enable --web.enable-remote-write-receiver in prometheus-community/prometheus

### Describe the solution you'd like.

Allow --web.enable-remote-write-receiver to be configured in helm

### Describe alternatives you've considered.

Stop using helm and deploying prometheus myself

**Comment by zeritti** [comment]
> Allow --web.enable-remote-write-receiver to be configured in helm

Prometheus' flags can be set either by appending the flag to `server.extraFlags` (is not empty by default) or inserting it in `server.extraArgs` (since 25.20.2):

```yaml
server:
  extraArgs:
    web.enable-remote-write-receiver: null
```

```yaml
server:
  extraFlags:
  - web.enable-remote-write-receiver
```

**Comment by Barsonax** [comment]
So this seems to indeed work:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: prometheus
  targetNamespace: monitoring
  version: 25.24.0
  valuesContent: |-
    server:
      extraFlags:
      - web.enable-lifecycle
      - web.enable-remote-write-receiver
```

I have to also define `web.enable-lifecycle` though, not sure if there's a way to just insert `web.enable-remote-write-receiver` and leave the other defaults as is in the helm chart.

**Comment by hyper-ricardo** [comment]
> > Allow --web.enable-remote-write-receiver to be configured in helm
> 
> Prometheus' flags can be set either by appending the flag to `server.extraFlags` (is not empty by default) or inserting it in `server.extraArgs` (since 25.20.2):
> 
> server:
>   extraArgs:
>     web.enable-remote-write-receiver: null
> server:
>   extraFlags:
>   - web.enable-remote-write-receiver


On `prometheus` chart,

This didn't worked for me:
```yml
server:
  extraArgs:
    web.enable-remote-write-receiver: null
```

But this did: 
```yml
server:
  extraFlags:
  - web.enable-remote-write-receiver
```

**Comment by nikaro** [comment]
On the prometheus chart this did not worked for me either:
```yaml
server:
  extraArgs:
    web.enable-remote-write-receiver: null
```
Helm somehow translate this to `server.extraArgs: {}`.

I had to do this:
```yaml
server:
  extraArgs:
    web.enable-remote-write-receiver: ""
```
