### ISSUE TITLE
[kube-prometheus-stack] How to set kube-prometheus-stack Grafana sidecar containers resource limit?

### ISSUE THREAD

**Issue by hongbo-miao** [prometheus-community/helm-charts#4766]
I deployed kube-prometheus-stack using it [Helm Chart](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack).

I am trying to set kube-prometheus-stack Grafana sidecar containers resource limit.

Here is original Helm chart values.yaml: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

Below is my custom values.yaml

```yaml
grafana:
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 512Mi
  sidecar:
    dashboards:
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 100m
          memory: 512Mi
    datasources:
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 100m
          memory: 512Mi
```

However, when I use [Goldilocks](https://github.com/FairwindsOps/goldilocks) to check, you can see the Grafana container in this pod resource got limited, but two sidecar containers resource still didn't get limited.

![image](https://github.com/user-attachments/assets/b97d404f-fdf3-4c77-be49-f8b889662b4f)

How to set kube-prometheus-stack Grafana sidecar containers resource limit? Thanks!

**Comment by zeritti** [comment]
Resources for the two sidecars are set through the subchart's field `sidecar.resources` ([values.yaml](https://github.com/grafana/helm-charts/blob/74821251da4abebd1301df3e1e6471ea64418774/charts/grafana/values.yaml#L867)), i.e. `grafana.sidecar.resources` in the KPS chart's values.

**Comment by hongbo-miao** [comment]
Thanks @zeritti ! I missed this, I will test and lost back the result. 😃

**Comment by hongbo-miao** [comment]
Hi @zeritti I am a little lost. The one you mentioned is in Grafana Helm chart values.yaml. Hmm I know Grafana in this case is subchart.
However, how could we set them in kube-prometheus-stack Helm chart [values.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml)? I may miss some knowledge here. Thanks!

**Comment by zeritti** [comment]
A subchart remains a _standalone_ chart with all of its supported values. The subchart's values gets inserted in the parent's values file underneath the field of its name, i.e. `grafana` in this case (this is how the chart's defaults get overriden). You are already doing it as shown above. 

If you wish to insert a value for the grafana chart that is not present in the KPS values file underneath `grafana`, you have to look it up in _that chart's values file_, i.e. in the grafana chart's values file. You have to review this file before you deploy the stack (and this applies to all the subcharts) - the parent chart does not override/set all the relevant values, e.g. persistence, grafana.ini, etc. - the user must make a choice)

Grafana chart's values file is [here](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml). You see that it has sidecar resources for the two sidecars defined in `sidecar.resources`. Now, you take this field and insert it in your custom values file in the `grafana` field as `grafana.sidecar.resources`, e.g.

```yaml
grafana:
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 512Mi
  sidecar:
    dashboards:
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 100m
          memory: 512Mi
    datasources:
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 100m
          memory: 512Mi
    ##
    ## here the inserted field
    ##
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi
```
