### ISSUE TITLE
[kube-prometheus-stack] Networking NO DATA

### ISSUE THREAD

**Issue by jsalatiel** [prometheus-community/helm-charts#4788]
### Describe the bug a clear and concise description of what the bug is.

I have installed  prometheus-kube-stack with the default values. 

So , my values is just:
```
grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - k8s.my.domain
```

When I login to grafana, all default dashboards related to network just show NO DATA.

### What's your helm version?

v3.15.2

### What's your kubectl version?

v1.29.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

61.9.0

### What happened?

NO DATA for all network related dashboards

### What you expected to happen?

I expect the network information be populated in the default dashboards.

### How to reproduce it?

Install the helm chart with default values on a single node k8s .

### Enter the changed values of values.yaml?

```
grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - k8s.my.domain
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade -i prometheus prometheus/kube-prometheus-stack  -n monitoring  -f myvalues.yml

### Anything else we need to know?

I run antrea 2.1.0 as CNI
