### ISSUE TITLE
[kube-prometheus-stack] Wrong Grafana default E-Mail

### ISSUE THREAD

**Issue by mvtab** [prometheus-community/helm-charts#4798]
### Describe the bug a clear and concise description of what the bug is.

After setting up the latest kube prom stack in a kubeadm Kubernetes 1.31.0, I tried configuring my Grafana contact points through the Helm values:
```
...
grafana:
  ...
  alerting:
    contactpoints.yaml:
      apiVersion: 1
      contactPoints:
      - name: ****
        orgId: 1
        is_default: True
        editable: True
        receivers:
        - uid: "****"
          type: email
          singleEmail: True
          settings:
            addresses: ****
 ...
```
This does achieve my purpose of setting an alternative contact, but even after trying the extra field deleteContactPoints, I can't seem to be able to change the default E-Mail address: example@email.com.

Now, a little bit of background. The current "example" E-Mail is absolutely horrible and a security concern, because email.com is NOT a [reserved domain](https://www.rfc-editor.org/rfc/rfc2606.html) and anyone who sets up a Grafana with this setup will start spamming alerts to the email at "email.com": currently owned by world.com - https://who.is/whois/email.com .

Here comes the next problem: you can not re-provision this default E-Mail address. I don't know what happens in the background, but for some reason the whole stack alerts are using this default contact point, and if you delete it you will get an error saying "contactpoint uuid '' not found". So the only way to fix this is to manually edit the address over the UI.

Can someone please change the default address to, I don't know: admin@example.com?

### What's your helm version?

3.15.3

### What's your kubectl version?

1.31.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

62.1.0

### Enter the command that you execute and failing/misfunctioning.

kubernetes.core.helm ansible module
