### ISSUE TITLE
[kube-prometheus-stack] Node Exporter Job name changed after upgrade fro 61.2.0 to 62.1.0

### ISSUE THREAD

**Issue by NotANormalNerd** [prometheus-community/helm-charts#4801]
### Describe the bug a clear and concise description of what the bug is.

After doing a upgrade to 62.1.0 the node exporter grafana dashboards don't show any data anymore.
As far as I have figured out up until now, it is because the job name changed. I haven't changed the configuration in between upgrades.

<img width="429" alt="image" src="https://github.com/user-attachments/assets/ccfb1c17-6575-4873-96fe-cb5ec319f0f3">

### What's your helm version?

version.BuildInfo{Version:"v3.15.3", GitCommit:"3bb50bbbdd9c946ba9989fbe4fb4104766302a64", GitTreeState:"clean", GoVersion:"go1.22.5"}

### What's your kubectl version?

Client Version: v1.29.2 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.29.6+k3s1

### Which chart?

kube-prometheus-stack

### What's the chart version?

62.1.0

### What happened?

The node exporter grafana dashboard stopped working

### What you expected to happen?

The node exporter grafana dashboards keep on working after the upgrade.

### How to reproduce it?

Upgrade to version 62.1.0 from 61.2.0

### Enter the changed values of values.yaml?

```yaml
    grafana:
      admin:
        existingSecret: "prometheus-stack-grafana"
        userKey: admin-user
        passwordKey: admin-password
      ingress:
        enabled: true
        hosts:
          - grafana.example
        path: /
        pathType: Prefix
      smtp:
        enabled: true
        fromAddress: system@example.com
        fromName: Grafana
        host: gmail.com:465
        password: abcdefg
        passwordKey: password
        skipVerify: "false"
        user: system@example.com
        userKey: user
      persistence:
        type: pvc
        enabled: true
        storageClassName: nfs-csi
        accessModes:
          - ReadWriteOnce
        size: 10Gi
        finalizers:
          - kubernetes.io/pvc-protection
    prometheus:
      prometheusSpec:
        retention: 365d
        retentionSize: 500GiB
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-csi
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 500Gi
```

### Enter the command that you execute and failing/misfunctioning.

helm_v3 upgrade --namespace prometheus --version 62.1.0 prometheus prometheus/kube-prometheus-stack --values /config/values-01_HelmChart.yaml

**Comment by zeritti** [comment]
The issue seems to be an unforeseen consequence of the prometheus-node-exporter chart's release [4.38](https://github.com/prometheus-community/helm-charts/releases/tag/prometheus-node-exporter-4.38.0). Since this release, `podLabels` has not been attached to all resources as previously but only to pods. In the same release, `commonLabels` was introduced to be attached to all resources. KPS release 62.1.0 updated node exporter chart dependency to release 4.38.

Now, KPS has relied on `podLabels` being present at node exporter's resources, namely at the service, as seen in `values.yaml`:

```yaml
prometheus-node-exporter:
  namespaceOverride: ""
  podLabels:
    ## Add the 'node-exporter' label to be used by serviceMonitor to match standard common usage in rules and grafana dashboards
    ##
    jobLabel: node-exporter
``` 

In this way, node exporter's service got the label `jobLabel=node-exporter` to be picked up by Prometheus operator through the node exporter's service monitor:

```yaml
prometheus-node-exporter:
  prometheus:
    monitor:
      jobLabel: jobLabel
```

and `job` was eventually set to `node-exporter`. Without `jobLabel` set at the node exporter's service, Prometheus operator falls back to the default, `prometheus-prometheus-node-exporter` in your case.

Setting `prometheus-node-exporter.service.labels.jobLabel` would have been a workaround but the chart does not currently support service labels.  At the moment, setting `prometheus-node-exporter.commonLabels.jobLabel=node-exporter` will add the label to the service (and all other node exporter's resources, similarly to the previous `podLabels`).
