### ISSUE TITLE
[kube-prometheus-stack] redirect to the login page after successful login

### ISSUE THREAD

**Issue by MichaelKora** [prometheus-community/helm-charts#4825]
### Describe the bug a clear and concise description of what the bug is.

I have  kube-prometheus-stack running on my Kubernetes cluster. When using Port Forwarding i can login into the Grafana dashboard with my creds. but when trying to do the same using the generated FQDN (created with the `ingress:` config of the the helm chart), i get redirected to the login page after seeing "Logged In".

I've seen some opened issue here and there but nothing helped so far. 
So i would truly appreciate your help.

![Screenshot 2024-08-28 162228](https://github.com/user-attachments/assets/f1174972-34c6-40b3-ac6a-23622bb31aa7)

### What's your helm version?

version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.5"}

### What's your kubectl version?

Client Version: v1.29.1 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.27.11

### Which chart?

prometheus-community/kube-prometheus-stack

### What's the chart version?

61.1.0 

### Enter the changed values of values.yaml?

```yaml
grafana:
   grafana.ini:
     users:
       viewers_can_edit: false
       login_default_org_id: 1
     server:
       serve_from_sub_path: true
     security:
       allow_embedding: true
       cookie_samesite: lax
       cookie_secure: false
     paths:
       data: /var/lib/grafana/
       logs: /var/log/grafana
       plugins: /var/lib/grafana/plugins
       provisioning: /etc/grafana/provisioning
     analytics:
       check_for_plugin_updates: true
       check_for_updates: true

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      kubernetes.io/ingress.allow-http: "true"
    hosts:
      - my-grafana.mydomain.com
    path: /
    pathType: ImplementationSpecific
    tls: []
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade -i -n monitoring prometheus prometheus-community/kube-prometheus-stack -f values.yaml

**Comment by MichaelKora** [comment]
right...i saw in grafans chart that its been set with the ingress's values" 
```
server:
    domain: "{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ tpl (.Values.ingress.hosts | first) . }}{{ else }}''{{ end }}"
``` 

and `root_url` is being set as well in the [defaults](https://github.com/grafana/grafana/blob/7057bd7cafdc8ec5bfb753b192b93fd082f68118/conf/defaults.ini#L51)

**Comment by MichaelKora** [comment]
a redirect is automatically performed on every link with the following pattern ` my-grafana.example.com/<xxxx>`.... everything with suffix in the link is redirected to ` my-grafana.example.com/login`

**Comment by zeritti** [comment]
`root_url` is a URL by which Grafana points to itself on its pages (like an external URL). According to your ingress for Grafana, you do not use https and I reckon your ingress controller listens on 80/tcp. Setting `http_port` to 3000 will not work unless your ingress controller listens on the same port.

Your `root_url` as "full public facing url" should in the end give `http://my-grafana.mydomain.com`. Give it a go:

```yaml
grafana:
  grafana.ini:
    server:
      root_url: http://my-grafana.mydomain.com
```

**Comment by MichaelKora** [comment]
it is still not working and this is my current config:
```yaml
grafana:
   grafana.ini:
    users:
      viewers_can_edit: false
      login_default_org_id: 1
    server:
      root_url: http://my-grafana.mydomain.com
      serve_from_sub_path: false
      http_port: 3000
    auth:
      disable_login_form: false
      disable_signout_menu: false
    security:
      allow_embedding: true
      cookie_samesite: lax
      cookie_secure: false
      angular_support_enabled: false
```

using `http_port: 80` resulted in a `permission denied` Error as mentioned before
