### ISSUE TITLE
[prometheus-smartctl-exporter] Add ability to include extra labels on PrometheusRule's rules

### ISSUE THREAD

**Issue by achetronic** [prometheus-community/helm-charts#4831]
### Is your feature request related to a problem ?

When deploying this chart in several clusters, having a centralized metrics data lake, and a collector such as Grafana Agent for collecting and pushing the PrometheusRule objects to it, the problem is there is no way in your helm chart to modify the  alerts 

### Describe the solution you'd like.

The idea is to include cluster-related information. It would be super useful to include some labels on the alerting rules for Alertmanager, and even include some extra metrics labels to filter the metrics by cluster

```
rules:
- alert: SmartCTLDeviceMediaErrors
  expr: smartctl_device_media_errors {my-custom-label="something", another="another-value"} != 0
  annotations:
    message: Device {{ $labels.device }} on instance {{ $labels.instance }} has media errors
  for: 1m
  labels:
    severity: error
    some-label: value
    cluster-name: this-is-a-cluster
```

### Describe alternatives you've considered.

Template and modify directly the PrometheusRule included in your chart and deploy it separatedly, which is not clean enough :)
