### ISSUE TITLE
[prometheus-mysql-exporter] multipleTarget.targets does not take effect

### ISSUE THREAD

**Issue by zhangzx1996** [prometheus-community/helm-charts#4836]
### Describe the bug a clear and concise description of what the bug is.

I deploy mysql-exporter by helm in k8s. And I want this exporter scrape two mysql instance. 
I was configed serviceMonitor.targets as follow:
```
serviceMonitor:
  multipleTarget:
    enabled: true
    targets:
      - endpoint: 172.30.0.10
        name: self-mysql
        port: 3307
        user: exporter1
        password: password
      - endpoint: 172.30.0.10
        name: exporter2
        port: 3306
        user: exporter2
        password: password
```
After exectu Helm install, there is a my.cnf look as this
```
      [client.beta-mysql]
      host=localhost
      port=3306
      user=exporter
      password=password
      [client.self-mysql]
      user=exporter1
      password=password
      [client.dev-mysql]
      user=exporter2
      password=password
```

### What's your helm version?

2.6.1

### What's your kubectl version?

kubephere. v3.3.2

### Which chart?

Prometheus-mysql-exporter

### What's the chart version?

0.15.1

### Enter the command that you execute and failing/misfunctioning.

The iphost I config in the targets[0].endpoint is not effect.
