### ISSUE TITLE
[kube-prometheus-stack] Prometheus targets are empty when using serviceDiscoveryRole: EndpointSlice

### ISSUE THREAD

**Issue by deutschj** [prometheus-community/helm-charts#4864]
### Describe the bug a clear and concise description of what the bug is.

I'd like to use the `serviceDiscoveryRole: EndpointSlice` configuration in the kube-prometheus-stack, and therefore manually created EndpointSlice objects, identical to the Endpoints objects that are created by the kube-prometheus-stack when filling out the `endpoints:` section for a component, e.g. kubeControllerManager. 
The EndpointSlice objects have the correct endpoint IP addresses and ports in them. However, they don't seem to be recognized by Prometheus, as the corresponding target in the Prometheus UI is empty and no metrics for the target are displayed. 

Support for the EndpointSlice role was introduced to Prometheus Operator in v0.76.0: https://github.com/prometheus-operator/prometheus-operator/issues/3862

I wanted to ask whether the discovery of EndpointSlice objects using the kube-prometheus-stack is already supported, and would be very glad if someone could help me with configuring this the right way. 

### What's your helm version?

v3.10.1

### What's your kubectl version?

v1.26.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

v62.3.1

### What happened?

Set `serviceDiscoveryRole: EndpointSlice` and created EndpointSlice objects for kubeControllerManager and kubeScheduler with the correct IP addresses and ports. However, the EndpointSlice objects are not recognized by the Prometheus ServiceMonitors created when installing the kube-prometheus-stack, and metrics for these targets are missing (targets section in the Prometheus UI is empty as well). 

### What you expected to happen?

EndpointSlice objects should show up as targets in the Prometheus UI and metrics should be successfully scraped from them.

### Enter the changed values of values.yaml?

prometheus:
  prometheusSpec:
    serviceDiscoveryRole: EndpointSlice

### Enter the command that you execute and failing/misfunctioning.

helm install kube-prom-stack -f values.yaml -n monitoring --version 62.3.1 prometheus-community/kube-prometheus-stack

**Comment by Dines97** [comment]
My kube-prometheus-stack version is 65.1.1. I also struggled a bit with this one. For me, creating an object of Service type that matches the EndpointSlice seems to fix the issue. I’m not sure which fields on all objects should match each other and what is the bare minimum configuration for all of this to actually work. But here are all three objects that I am using. All targets in the addresses field appear in the UI. All REDACTED strings were actually the same value; I’m not sure if they should be.

```yaml
addressType: FQDN
apiVersion: discovery.k8s.io/v1
endpoints:
  - addresses:
      - fqdn1.domain.com
      - fqdn2.domain.com
      - fqdn3.domain.com
    conditions:
      ready: true
kind: EndpointSlice
metadata:
  labels:
    app: <REDACTED>
  name: <REDACTED>
ports:
  - name: windows-exporter
    port: 9182
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: <REDACTED>
  name: <REDACTED>
spec:
  ports:
    - name: windows-exporter
      port: 9182
      protocol: TCP

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: <REDACTED>
spec:
  endpoints:
    - interval: 30s
      port: windows-exporter
      scrapeTimeout: 10s
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: <REDACTED>

```
