### ISSUE TITLE
[kube-prometheus-stack] Prometheus storageSpec Helm values ignored

### ISSUE THREAD

**Issue by crazyelectron-io** [prometheus-community/helm-charts#4868]
### Describe the bug a clear and concise description of what the bug is.

When deploying Prometheus with Helm the `storageSpec` in the `values.yaml` seems to be ignored. I specify 50Gi but a volume of 8Gi is created (did several runs with cleanup in between)..

See below for the `values.yaml` part related to Prometheus. What am I missing?

### What's your helm version?

version.BuildInfo{Version:"v3.15.3", GitCommit:"3bb50bbbdd9c946ba9989fbe4fb4104766302a64", GitTreeState:"clean", GoVersion:"go1.22.5"}

### What's your kubectl version?

Client Version: v1.30.3 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.30.1+k3s1

### Which chart?

rometheus-community/prometheus

### What's the chart version?

helm.sh/chart: prometheus-25.27.0

### What happened?

When deploying Prometheus with Helm the `storageSpec` in the `values.yaml` seems to be ignored. I specify 50Gi but a volume of 7.8Gi is created.
The `values.yaml` entries for Prometheus are:
```yaml
prometheus:
  enabled: true
  ingress:
    enabled: false
  serviceMonitor:
    selfMonitor: true
  prometheusSpec:
    ## Settings affecting prometheusSpec
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec
    replicas: 1
    replicaExternalLabelName: "replica"
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    image:
      registry: "{{harbor_registry}}"
      repository: prometheus
      tag: v2.54.1
    enableAdminAPI: true
    walCompression: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageCLassName: longhorn
          acessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
```
What am I missing?

### What you expected to happen?

Expected to get a 50Gi volume as specified.

### How to reproduce it?

Apply the Helm chart with the above in the values file.

### Enter the changed values of values.yaml?

See above.

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/prometheus -f values.yaml
