### ISSUE TITLE
[prometheus-elasticsearch-exporter] Add ability to set scheme for probes

### ISSUE THREAD

**Issue by timp87** [prometheus-community/helm-charts#4876]
### Is your feature request related to a problem ?

One may have security requirement to scrape exporters via HTTPS only.

Current 6.4.0 chart version of prometheus-elasticsearch-exporter allows one to:
- create a secret with TLS key/cert via `extraManifests` and then mount it to the pod via `secretMounts`
- create a configMap via `extraManifests` with web-config referring those TLS  key/cert
- mount that configMap to the pod via `extraVolumes` and `extraVolumeMounts`
- add `--web.config.file=<path_to_web_config>` to args vu `extraArgs`

Now exporter can be scraped via HTTPS. The only problem here is hardcoded `scheme` in the liveness and readiness probes. To make it work properly one need a way to redefine with scheme.

### Describe the solution you'd like.

Add ability to set [scheme](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#http-probes) for probes to prometheus-elasticsearch-exporter.

This might be done via adding `scheme` option to `service` object in values.yaml.
Or `service.metricsPort.name` can be used as `scheme` for probes, like this:
```
@@ -149,6 +149,7 @@ spec:
             httpGet:
               path: /healthz
               port: {{ .Values.service.metricsPort.name }}
+              scheme: {{ upper .Values.service.metricsPort.name }}
             initialDelaySeconds: 5
             timeoutSeconds: 5
             periodSeconds: 5
@@ -156,6 +157,7 @@ spec:
             httpGet:
               path: /healthz
               port: {{ .Values.service.metricsPort.name }}
+              scheme: {{ upper .Values.service.metricsPort.name }}
             initialDelaySeconds: 1
             timeoutSeconds: 5
             periodSeconds: 5
```
Or there might be a better way like dedicating a separate variable for scheme

### Describe alternatives you've considered.

N/A only forking
