### ISSUE TITLE
[kube-prometheus-stack] kubeEtcd, kubeControllerManager, kubeScheduler, kubeProxy automatic endpoint IP just like Kubelet

### ISSUE THREAD

**Issue by lukasmrtvy** [prometheus-community/helm-charts#488]
**Is your feature request related to a problem? Please describe.**

`kubeEtcd`, `kubeControllerManager`, `kubeScheduler`, `kubeProxy` Services/Endpoints should also support automatic endpoint IP just like Kubelet Service/Endpoint does. Endpoint does not support FQDNs, just IPs and thats sometimes hard to set, without any templating before actual deployment.

**Describe the solution you'd like**
Instead of this:
```
  kubeEtcd:
    enabled: false
  kubeControllerManager:
    endpoints:
    - 88.XX.XX.XX
  kubeScheduler:
    endpoints:
    - 88.XX.XX.XX
  kubeProxy:
    endpoints:
    - 88.XX.XX.XX
```
use
```
  kubeEtcd:
    enabled: false
  kubeControllerManager:
    external: true
  kubeScheduler:
    external: true
  kubeProxy:
    external: true
```

**Describe alternatives you've considered**
Templating endpoint IP before deployment

**Additional context**
No
