### ISSUE TITLE
[prometheus-blackbox-exporter] livenessProbe.httpGet: Forbidden: may not specify more than 1 handler type

### ISSUE THREAD

**Issue by Sispheor** [prometheus-community/helm-charts#4894]
Hello there,

I'm trying to configure my blackbox exporter to have multiple IP via Multus.
The service is working fine but I have an issue with the livenessProbe and readinessProbe.

The default config doesn't work when adding multiple IPs.
```yaml
# default config
livenessProbe:
  httpGet:
    path: /-/healthy
    port: http
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /-/healthy
    port: http
```

I would like to configure a cmd instead of an httpGet like this:
```yaml
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 15
  exec:
    command:
      - wget
      - http://localhost:9115/-/healthy

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 15
  exec:
    command:
      - wget
      - http://localhost:9115/-/healthy
```

Note: the command `wget  http://localhost:9115/-/healthy ` has been tested from the container and works well.

But when I deploy I get this error:
```
The Deployment "prometheus-blackbox-exporter" is invalid: 
* spec.template.spec.containers[0].livenessProbe.httpGet: Forbidden: may not specify more than 1 handler type
* spec.template.spec.containers[0].readinessProbe.httpGet: Forbidden: may not specify more than 1 handler type
```

Which is weird because the httpGet is not present anymore in value file.

### What's your helm version?

version.BuildInfo{Version:"v3.15.4", GitCommit:"fa9efb07d9d8debbb4306d72af76a383895aa8c4", GitTreeState:"clean", GoVersion:"go1.22.6"}

### What's your kubectl version?

Client Version: v1.31.0

### Which chart?

prometheus-blackbox-exporter

### What's the chart version?

9.0.0

### What happened?

First, the default readiness and and liveness probes don't work with multiple IP set via Multus. No idea why because the the listen (via netstat) is the same with added IPs.

Secondly, when trying to workaround the first issue by changing liveness and readyness probles we get the following:
```
The Deployment "prometheus-blackbox-exporter" is invalid: 
* spec.template.spec.containers[0].livenessProbe.httpGet: Forbidden: may not specify more than 1 handler type
* spec.template.spec.containers[0].readinessProbe.httpGet: Forbidden: may not specify more than 1 handler type
```

### What you expected to happen?

The default probes working when pods is connected to multiple IPs or being able to update probes with a cmd based check.

### How to reproduce it?

- Deploy by changing the readiness probe to use cmd check instead of httpget in value file (even if no multus configured)

### Enter the changed values of values.yaml?

```yaml
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 15
  exec:
    command:
      - wget
      - http://localhost:9115/-/healthy

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 15
  exec:
    command:
      - wget
      - http://localhost:9115/-/healthy
```

### Enter the command that you execute and failing/misfunctioning.

```
kustomize build --enable-helm apps/prometheus | argocd-vault-plugin generate - | kubectl apply --server-side -f -
```
