### ISSUE TITLE
[kube-prometheus-stack] support --kubelet-endpointslice=true

### ISSUE THREAD

**Issue by jihuiyang** [prometheus-community/helm-charts#4897]
### Describe the bug a clear and concise description of what the bug is.

with 65.0.0, `--kubelet-endpointslice=true` feature is available. please support setting 
```
        - --kubelet-endpoints=false
        - --kubelet-endpointslice=true
```
to the operator in values

also when i tried enabling it, operator failed to run due to 
```
ts=2024-10-03T22:27:05.878020844Z level=warn caller=/home/runner/work/prometheus-operator/prometheus-operator/cmd/operator/main.go:556 msg="missing permission on resource 'endpointslices' (group: \"discovery.k8s.io\")" reason="missing \"create\" permission on resource \"endpointslices\" (group: \"discovery.k8s.io\") for namespace \"kube-system\""
ts=2024-10-03T22:27:05.878065181Z level=warn caller=/home/runner/work/prometheus-operator/prometheus-operator/cmd/operator/main.go:556 msg="missing permission on resource 'endpointslices' (group: \"discovery.k8s.io\")" reason="missing \"update\" permission on resource \"endpointslices\" (group: \"discovery.k8s.io\") for namespace \"kube-system\""
ts=2024-10-03T22:27:05.878072703Z level=warn caller=/home/runner/work/prometheus-operator/prometheus-operator/cmd/operator/main.go:556 msg="missing permission on resource 'endpointslices' (group: \"discovery.k8s.io\")" reason="missing \"delete\" permission on resource \"endpointslices\" (group: \"discovery.k8s.io\") for namespace \"kube-system\""
```

looks like in `clusterrole/kube-prometheus-stack-operator`
you only have 
```
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
```

please update it to
```
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - create
  - update
  - delete
  - list
  - watch
```

### What's your helm version?

3.16.1

### What's your kubectl version?

1.29.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

65.0.0

### Enter the command that you execute and failing/misfunctioning.

command works, i need to enable new functionality
