### ISSUE TITLE
[prometheus-mysql-exporter] How do I provide SSL to MySQL connection

### ISSUE THREAD

**Issue by rnkhouse** [prometheus-community/helm-charts#491]
**Is your feature request related to a problem? Please describe.**
In order to connect to prod database connection has to be secured. Currently, there is no way to provide SSL certificate in the connection params.

For example, to connect with Azure MySQL (https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl), they required us to provide the certificate in the request.

Ref: https://github.com/prometheus/mysqld_exporter#customizing-configuration-for-a-ssl-connection

**Comment by jbouzekri** [comment]
@rnkhouse : this is not perfect but i was able to connect by setting param to the value `tls=skip-verify`

**Comment by rnkhouse** [comment]
@jbouzekri From the server-side TLS is mandatory. Also, it's not a good idea for prod.

**Comment by jbouzekri** [comment]
This configuration does not mean tls is disabled. Just that the client does not verify the cert but it does establish an encrypted tls connection.

**Comment by rnkhouse** [comment]
@jbouzekri `tls=skip-verify` is not available in `values.yaml` file. How can I set this flag?

**Comment by Prakashckesavan** [comment]
Do we have any solution for this, I am facing the same issue , i have dbs with ssl and values.yaml don't have anything to add ssl.

**Comment by deem1978** [comment]
@jbouzekri the link you provided point to 
```
# Extra Volume Mounts for the mysql exporter container
extraVolumeMounts: []
# - name: example
#   mountPath: /example
```
Do we have any solution regarding the helm chart?

**Comment by jbouzekri** [comment]
The link did not target a specific tag and the values.yaml file has changed since then.

At that time, you could do this : 

```
# mysql connection params which build the DATA_SOURCE_NAME env var of the docker container
mysql:
  db: ""
  host: "XXXXX"
  param: "tls=skip-verify"
```

Now, I think you should look into `additionalConfig` if you have something that allows to disable ssl certificate verification

```
# mysql connection params which build the my.cnf config
mysql:
  db: ""
  host: "localhost"
  # config my.cnf https://dev.mysql.com/doc/c-api/8.0/en/mysql-options.html
  additionalConfig:
    # - connect-timeout=5
    # - debug
```
