### ISSUE TITLE
[kube-prometheus-stack] ArgoCD reports of differences in multiple places which are set by the chart

### ISSUE THREAD

**Issue by zefferno** [prometheus-community/helm-charts#4914]
### Describe the bug a clear and concise description of what the bug is.

I'm encountering a strange issue with the deployment of the kube-prometheus-stack using Argo CD application. I'm consistently seeing differences in the Argo CD application, which prompts for the removal of resources and caBundle entries from the cluster. This started happening after I upgraded to version 58.7.2 (screenshot attached). I’ve attempted both downgrading and upgrading, but it hasn’t resolved the problem. Any idea what could be reason for this discrepancy?

### What's your helm version?

v3.16.2

### What's your kubectl version?

v1.30.5

### Which chart?

kube-prometheus-stack

### What's the chart version?

58.7.2

### Enter the command that you execute and failing/misfunctioning.

Deploying the helm chart using ArgoCD application:
project: default
destination:
  server: 'https://kubernetes.default.svc'
  namespace: monitoring
syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 58.7.2
    helm:
      valueFiles:
        - $x/prometheus-default-values.yaml
        - $y/grafana-overlay-values.yaml
        - $z/prometheus-additional-values.yaml
      releaseName: prometheus-operator
      values: |
        grafana:
          additionalDataSources:
           - ...
        prometheus:
            prometheusSpec:
                retention: "[REDUCTED]"
                storageSpec:
                    volumeClaimTemplate:
                        spec:
                            accessModes:
                            - ReadWriteOnce
                            resources:
                                requests:
                                    storage: "[REDUCTED]"
    chart: kube-prometheus-stack
  - repoURL: '....'
    targetRevision: ...
    ref: ...
  - repoURL: '....'
    targetRevision: ...
    ref: ..

**Comment by yardenws** [comment]
Using the below alongside using ServerSideApply=true fixed my issues ( ServerSideApply is required to fix long CRD names issue ).

```
ignoreDifferences:
  - group: monitoring.coreos.com
    kind: Prometheus
    jqPathExpressions:
    - .spec.remoteWrite[]?.writeRelabelConfigs[]?.action
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  - group: apps
    kind: Deployment
    name: kube-prometheus-stack-kube-state-metrics
    namespace: monitoring
    jqPathExpressions:
      - '.spec.template.spec.containers[]?.resources'
  - group: apps
    kind: DaemonSet
    name: kube-prometheus-stack-prometheus-node-exporter
    namespace: monitoring
    jqPathExpressions:
      - '.spec.template.spec.containers[]?.resources'
``` 

Enjoy :)

**Comment by zefferno** [comment]
@yardenws Thank you for sharing the workaround tip. This is exactly what I ended up using myself.

However, I still think this issue should be reported as a bug in the chart and potentially fixed to avoid such workarounds.

**Comment by tm-nadavsh** [comment]
added ignoreDifferences, fixed ValidatingWebhookConfiguration and mutating but not the resourece issue of - '.spec.template.spec.containers[]?.resources'

**Comment by ajostergaard** [comment]
Not stale.

**Comment by glycerine102** [comment]
I experience this as well. Grafana deployment resource keys always show differences in Argo for me on newer (v1.32) clusters. Similar to the above, I add this in the appset.

```
      ignoreDifferences:
      - group: apps
        kind: Deployment
        name: prometheus-grafana
        namespace: monitoring
        jqPathExpressions:
        - '.spec.template.spec.containers[]?.resources'
      - group: apps
        kind: Deployment
        name: prometheus-grafana
        namespace: monitoring
        jqPathExpressions:
        - '.spec.template.spec.initContainers[]?.resources'
 ```

**Comment by renklus** [comment]
Another difference in the chart 'prometheus' version 28.9.1 for the alertmanager.
<img width="704" height="364" alt="Image" src="https://github.com/user-attachments/assets/2e32a3af-dc6b-4025-a7cc-26edd7fd902c" />
Workaround is
```
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jqPathExpressions:
      - .spec.volumeClaimTemplates[0].apiVersion
      - .spec.volumeClaimTemplates[0].kind
```

**Comment by renklus** [comment]
I was able to fix it without using `ignoreDifferences` by configuring argocd to use the new [Server-Side Diff strategy](https://argo-cd.readthedocs.io/en/stable/user-guide/diff-strategies/).
From how they handled [this discussion](https://github.com/argoproj/argo-cd/issues/11143) I got the impression that there is no intention by argocd to fix this in their Legacy and Structured-Merge diff strategy.

The argocd link describes how to enable Server-Side Diff directly in the ConfigMap. 
To achieve this through the helm chart I had to set it as a helm valuesObject in the argocd Application yaml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    helm:
      valuesObject:
        configs:
          params:
            "create": 'true'
            "controller.diff.server.side": 'true'
```
