### ISSUE TITLE
[kube-prometheus-stack] Cannot use the alerts sidecar for alerts

### ISSUE THREAD

**Issue by andreitigau** [prometheus-community/helm-charts#4923]
### Describe the bug a clear and concise description of what the bug is.

The chart is missing the sidecar for alerts.
Before I could provision alerts using some configuration like this:
```
  grafana:
     sidecar:
          alerts:
            enabled: true
            searchNamespace: ALL
            watchMethod: SLEEP
            resource: configmap
```

Now this seems not to be possible anymore.

### What's your helm version?

v3.12.0

### What's your kubectl version?

v1.27.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

62.3.1

### Enter the command that you execute and failing/misfunctioning.

There is no failing command. The chart used to contain an alerts sidecar and now, it doesn't.
