### ISSUE TITLE
[prometheus-postgres-exporter] Support custom TLS configuration

### ISSUE THREAD

**Issue by volker-raschek** [prometheus-community/helm-charts#4940]
### Is your feature request related to a problem ?

The current version of the prometheus-postgres-exporter helm chart does not support TLS encryption between prometheus and the exporter. It is currently not possible to define a custom TLS configuration as part of the serviceMonitor resurce. 

In my opinion is this a security issue, because the metrics can be accessed from other application running inside the cluster. Only network policies can currently avoid accessing the metric endpoint. For this reason should be the helm chart adapted, that users can without implementing network policies use TLS authentication and encryption for the metrics endpoint.

### Describe the solution you'd like.

I would like to have some configuration options in the `values.yaml` to customize the TLS configuration used py prometheus to scrape the metrics endpoint. 

Inspect more details via `kubectl explain servicemonitor.spec.endpoints.tlsConfig` and `kubectl explain servicemonitor.spec.endpoints.scheme`.

### Describe alternatives you've considered.

No alternative.

### Additional context.

As far as I know. It is currently not possible to start the web server of prometheus-postgres-exporter with TLS encryption. An issue regarding the missing feature of TLS encryption as part of the application is still [open](https://github.com/prometheus-community/postgres_exporter/issues/454) since some years. 

I think the feature to configure a custom TLS configuration as part of the serviceMonitor should nevertheless be implemented.

**Comment by zeritti** [comment]
> As far as I know. It is currently not possible to start the web server of prometheus-postgres-exporter with TLS encryption.

Support for TLS in the exporter is present through TLS Toolkit's [web-config](https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-config.yml) file and flag `--web.config.file`.

> The current version of the prometheus-postgres-exporter helm chart does not support TLS encryption between prometheus and the exporter.

Support for TLS can be enabled in the chart by using fields `extraVolumeMounts`, `extraVolumes` and `config.extraArgs`. A working example:

```yaml
config:
  extraArgs:
    - "--web.config.file=/etc/webconfig/web-config.yaml"

extraVolumes:
  - name: tls
    secret:
      secretName: pge-tls
      items:
        - key: "tls.key"
          path: "tls.key"
        - key: "tls.crt"
          path: "tls.crt"
  - name: webconfig
    secret:
      secretName: webconfig

extraVolumeMounts:
  - name: tls
    mountPath: /etc/private
  - name: webconfig
    mountPath: /etc/webconfig
```

An outstanding and _blocking_ issue, though, is setting the scheme in probes which is currently not possible.
