### ISSUE TITLE
[kube-prometheus-stack] Configuration mapping issue by AlermanagerConfig CRD

### ISSUE THREAD

**Issue by kallaics** [prometheus-community/helm-charts#4948]
### Describe the bug a clear and concise description of what the bug is.

I try to use the AlertmanagerConfig CRD and it looks like it has some mapping issue. It works, when I configure it directly in the values yaml. When I convert the configuration to the AlertmanagerConfig CRD and I deploy it, then the configuration wil not the same. The issue affected most of the configuration parameter under the `route` section.  

I assume the issue somewhere the AlermanagerConfig CRD mapping to the configuration. The configuration merged one level deeper than needed. Please see the next section with an example configuration, it will present the issue.

### What's your helm version?

version.BuildInfo{Version:"v3.16.2", GitCommit:"13654a52f7c70a143b1dd51416d633e1071faffb", GitTreeState:"dirty", GoVersion:"go1.23.2"}

### What's your kubectl version?

lient Version: v1.31.1 Kustomize Version: v5.4.2 Server Version: v1.29.9

### Which chart?

kube-prometheus-stack

### What's the chart version?

65.5.0

### What happened?

AlertmanagerConfig CRD version

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
    operator.prometheus.io/version: 0.77.1
  labels:
    helm.toolkit.fluxcd.io/name: prometheus
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: alertmanagerconfigs.monitoring.coreos.com
spec:
  conversion:
    strategy: None
  group: monitoring.coreos.com
  names:
    categories:
    - prometheus-operator
    kind: AlertmanagerConfig
    listKind: AlertmanagerConfigList
    plural: alertmanagerconfigs
    shortNames:
    - amcfg
    singular: alertmanagerconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
  ...
```

Example configuration:

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config
  namespace: monitoring
spec:
  route:
    receiver: "null"
    groupBy:
      - alertname
      - env
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 5m
    routes:
      - matchers:
          - name: alertname
            matchType: "="
            value: Watchdog
        receiver: "null"
        continue: false
  receivers:
    - name: "null"
```

Current result /etc/alertmanager/config_out/alertmanager.env.yaml

```yaml
global:
  resolve_timeout: 5m
route:
  receiver: "null"
  group_by:
  - namespace
  routes:
   # It is wrong mapping and create routes, but it is not a route, just the groupBy configuration
  - receiver: monitoring/config/null
    group_by:
    - alertname
    - env
    matchers:
    - namespace="monitoring"
    # Until this point
    continue: true                                    #  implemented probably wrong level and not override the config
    routes:                                           #  implemented probably wrong level and not override the config
    - receiver: monitoring/config/null
      matchers:
      - alertname="Watchdog"
    #  implemented probably wrong level of next item
    group_wait: 30s                                #  implemented probably wrong level and not override the config
    group_interval: 5m                             #  implemented probably wrong level and not override the config
    repeat_interval: 5m                            #  implemented probably wrong level and not override the config
  - receiver: "null"
    matchers:
    - alertname = "Watchdog"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
```

### What you expected to happen?

Expected result in /etc/alertmanager/config_out/alertmanager.env.yaml

```yaml
global:
  resolve_timeout: 5m
route:
  receiver: "null"
  group_by:
  - alertname
  - env
  continue: true
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  routes:
  - receiver: monitoring/config/null
    matchers:
    - alertname="Watchdog"
  - receiver: "null"
    matchers:
    - alertname = "Watchdog"
```

### How to reproduce it?

1. Configure any of the parameters inside the `route` section as AlermanagerConfig CRDS like:

- groupWait
- groupInterval
- repeatInterval
- groupBy
- continue
- routes

2. Deploy a CRDS with AlertmanagerConfiguration CRD.
3. Deploy the kube-prometheus-stack Helm chart.
4. Check the /etc/alertmanager/config_out/alertmanager.env.yaml file the alertmanager container.

### Enter the changed values of values.yaml?

No changes in values yaml. 
Created CRDs for the configuration

### Enter the command that you execute and failing/misfunctioning.

Create a default configuration

```bash
cat << EOF > alertmanagerconfig.yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config
spec:
  route:
    receiver: "null"
    groupBy:
      - alertname
      - env
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 5m
    routes:
      - matchers:
          - name: alertname
            matchType: "="
            value: Watchdog
        receiver: "null"
        continue: false
  receivers:
    - name: "null"
EOF
```

Deploy the configuration and kube-prometheus-stack

```bash
kubectl apply -f alermanagerconfig.yaml -n monitoring
helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --values values.yaml
```

### Anything else we need to know?

I am using FluxCD latest stable version  (v2.4.0) to the deployment, but the issue looks like independent from the deployment system.
