### ISSUE TITLE
[kube-prometheus-stack] Metrics missing from Grafana Dashboards

### ISSUE THREAD

**Issue by paddatrapper** [prometheus-community/helm-charts#4951]
### Describe the bug a clear and concise description of what the bug is.

The default Grafana dashboards no longer have data for many of the measured metrics. See the screenshot below:

![grafana-dashboards-1](https://github.com/user-attachments/assets/b43553de-740d-427c-bfd7-cec009497a6b)
![grafana-dashboards-2](https://github.com/user-attachments/assets/4cd983e5-031c-4888-a512-7d0e86f50cbe)

Other dashboards, e.g. the API Server work without issue

### What's your helm version?

Flux helm-controller v0.26.0

### What's your kubectl version?

Client Version: v1.28.14 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.28.13-eks-a737599

### Which chart?

prometheus-kube-stack

### What's the chart version?

65.3.2

### What happened?

Most metrics are empty without data

### What you expected to happen?

The metrics to be displayed

### How to reproduce it?

1. Deployed kube-prometheus-stack
2. Navigate to Grafana
3. Open Kubernetes / Compute Resources / Cluster dashboard

### Enter the changed values of values.yaml?

```yaml
  values:
    defaultRules:
      rules:
        kubelet: false
        kubeSchedulerAlerting: false
        kubeControllerManager: false
        kubernetesSystem: false
      labels:
        prometheus: enabled
    alertmanager:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/tls-acme: "true"
          nginx.ingress.kubernetes.io/auth-signin: <redacted>
          nginx.ingress.kubernetes.io/auth-url: <redacted>
        hosts:
          - <redacted>
        paths:
          - /
        pathType: Prefix
        tls:
          - secretName: alertmanager-tls
            hosts:
              - <redacted>
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: <redacted>
      serviceMonitor:
        additionalLabels:
          prometheus: enabled
      config:
        route:
          routes:
            - receiver: 'null'
              matchers:
                - alertname =~ "InfoInhibitor|Watchdog"
            - receiver: slack
              group_by:
                - alertname
              matchers:
                - severity =~ "warning|critical"
              continue: true
            - receiver: sns-alert
              group_by:
                - alertname
              matchers:
                - severity =~ "warning|critical"
                - canary_name =~ ".*production"
                - alertName =~ "CanaryFailed"
        receivers:
          - name: 'null'
          - name: slack
            slack_configs:
              - title: "{{ .CommonLabels.alertname }} - Production Cluster"
                text: >-
                 {{ range .Alerts -}}
                 *Alert:* {{ .Annotations.summary }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

                 *Description:* {{ .Annotations.description }}

                 *Details:*
                   {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                   {{ end }}
                 {{ end }}
                api_url: <redacted>
          - name: sns-alert
            sns_configs:
              - topic_arn: <redacted>
                subject: "{{ .CommonLabels.alertname }} - Production Cluster"
                message: >-
                 {{ range .Alerts -}}
                 *Alert:* {{ .Annotations.summary }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

                 *Description:* {{ .Annotations.description }}

                 *Details:*
                   {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                   {{ end }}
                 {{ end }}
                sigv4:
                  region: <redacted>
      alertmanagerSpec:
        podMetadata:
          labels:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        storage:
          volumeClaimTemplate:
            metadata:
              name: alertmanager-main-db
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
              storageClassName: gp2
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/tls-acme: "true"
          nginx.ingress.kubernetes.io/auth-signin: <redacted>
          nginx.ingress.kubernetes.io/auth-url: <redacted>
          - <redacted>
        paths:
          - /
        pathType: Prefix
        tls:
          - secretName: grafana-tls
            hosts:
              - <redacted>
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: <redacted>
      additionalDataSources:
        - name: CloudWatch
          type: cloudwatch
          jsonData:
            authType: "default"
            defaultRegion: <redacted>
      serviceMonitor:
        scrapeTimeout: 90s
        interval: 90s
        additionalLabels:
          prometheus: enabled
    kubeApiServer:
      serviceMonitor:
        additionalLabels:
          prometheus: enabled
    kubelet:
      enabled: false
      serviceMonitor:
        additionalLabels:
          prometheus: enabled
    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/tls-acme: "true"
          nginx.ingress.kubernetes.io/auth-signin: <redacted>
          nginx.ingress.kubernetes.io/auth-url: <redacted>
        hosts:
          - <redacted>
        paths:
          - /
        pathType: Prefix
        tls:
          - secretName: prometheus-tls
            hosts:
              - <redacted>
      serviceMonitor:
        additionalLabels:
          prometheus: enabled
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        scrapeTimeout: 90s
        scrapeInterval: 90s
        podMetadata:
          labels:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        storageSec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 60Gi
              storageClassName: gp2
    thanosRuler:
      thanosRulerSpec:
        ruleSelectorNilUsesHelmValues: false
        externalPrefixNilUsesHelmValues: false
    prometheusOperator:
      serviceMonitor:
        scrapeTimeout: 90s
        interval: 90s
        additionalLabels:
          prometheus: enabled
    coreDns:
      serviceMonitor:
        additionalLabels:
          prometheus: enabled
    kubeEtcd:
      serviceMonitor:
        additionalLabels:
          prometheus: enabled
    kubeControllerManager:
      serviceMonitor:
        additionalLabels:
          prometheus: enabled
    kubeScheduler:
      serviceMonitor:
        additionalLabels:
          prometheus: enabled
    kube-state-metrics:
      prometheus:
        monitor:
          additionalLabels:
            prometheus: enabled
    kubeProxy:
      serviceMonitor:
        additionalLabels:
          prometheus: enabled
    prometheus-node-exporter:
      prometheus:
        monitor:
          interval: 90s
          scrapeTimeout: 90s
          additionalLabels:
            prometheus: enabled
```

### Enter the command that you execute and failing/misfunctioning.

No failing command or visible error messages
