### ISSUE TITLE
how to add cluster label

### ISSUE THREAD

**Issue by anacelto** [prometheus-community/helm-charts#4961]
Hi,

I've deployed the kube-prometheus-stack helm chart.

I am struggling with adding the `cluster` label, as it is required by some dashboards that I would like to use.

By the docs, it looks like I need to use the "agent" feature, but as this is only one cluster, I do not see the reason. Same for externalLabels value, they do not apply as we are not sending the metrics to an external system. 🤔 

It should be something trivial, but it looks like we are missing something.

Any insights? 

Thanks!

**Comment by zeritti** [comment]
> I am struggling with adding the cluster label, as it is required by some dashboards that I would like to use.

You can use service monitor's [RelabelConfig](https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.RelabelConfig), resulting in native Prometheus' `scrape_configs[].relabel_configs`, to attach that label to each endpoint. You'd have to do this in each service monitor endpoint that you have enabled/configured. 

If you consider the included service monitors, e.g. _kubelet_ (has multiple endpoints):

```yaml
kubelet:
  serviceMonitor:
    relabelings:
    - sourceLabels: [__address__]
      targetLabel: cluster
      replacement: mycluster
```

In a custom service monitor, you'd have

```yaml
spec:
  endpoints:
  - relabelings:
    - sourceLabels: [__address__]
      targetLabel: cluster
      replacement: mycluster
...
```

**Comment by anacelto** [comment]
> > I am struggling with adding the cluster label, as it is required by some dashboards that I would like to use.
> 
> You can use service monitor's [RelabelConfig](https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.RelabelConfig), resulting in native Prometheus' `scrape_configs[].relabel_configs[]`, to attach that label to each endpoint. You'd have to do this in each service monitor endpoint that you have enabled/configured.
> 
> If you consider the included service monitors, e.g. _kubelet_ (has multiple endpoints):
> 
> ```yaml
> kubelet:
>   serviceMonitor:
>     relabelings:
>     - sourceLabels: [__address__]
>       targetLabel: cluster
>       replacement: mycluster
> ```
> 
> In a custom service monitor, you'd have
> 
> ```yaml
> spec:
>   endpoints:
>   - relabelings:
>     - sourceLabels: [__address__]
>       targetLabel: cluster
>       replacement: mycluster
> ...
> ```

@zeritti thanks for your answer.

So, do you mean that I should add this to all the `serviceMonitor:` entries of the values file?

Also, why is sourceLabels: [__address__] needed?

**Comment by zeritti** [comment]
> Also, why is sourceLabels: [__address__] needed?

This could also work with the operator:

```yaml
- relabelings:
    - targetLabel: cluster
      replacement: mycluster
```

**Comment by zeritti** [comment]
There is another way of doing this and that is by using `servicemonitor.spec.targetLabels` and `servicemonitor.spec.podTargetLabels` ([ServiceMonitor](https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.ServiceMonitor)). 

This might be easier but depends on the desired label being present at services and pods, respectively. It also depends on the charts' support for those fields in their service monitors.

**Comment by ops4cloud** [comment]
I've got the same issue, i'am not able to set labels on kube-prometheus-stack !

**Comment by jacobw** [comment]
I have struggled with this too, the below config looks to have fixed everything.

```
  values:
    prometheusOperator:
      extraArgs:
        - --labels=cluster=taloscluster
    kubelet:
      serviceMonitor:
        targetLabels:
          - cluster
    prometheus-node-exporter:
      service:
        labels:
          jobLabel: node-exporter
          cluster: taloscluster
      prometheus:
        monitor:
          targetLabels:
            - cluster
    kube-state-metrics:
      customLabels:
        cluster: taloscluster
      prometheus:
        monitor:
          targetLabels:
            - cluster
  ```

It would be great to have a generic way to add a label to all sub charts.

**Comment by HujinoKun** [comment]
> @anacelto what did you end up using ? we tried `externalLabels` but it does not seem to apply

Same error :/

**Comment by geowalrus4gh** [comment]
It would be convenient if a common label to all metrics so that metric data would have multitenancy. chart template can then inject that label to all the service monitors rendered from the chart.

**Comment by rgauthey** [comment]
> > [@anacelto](https://github.com/anacelto) what did you end up using ? we tried `externalLabels` but it does not seem to apply
> 
> Same error :/

`commonLabels` doesn't seem to apply either

**Comment by rgauthey** [comment]
I achieved to have a cluster label applied to all my metrics (including metrics from service monitors defined in other helm charts) by doing this :

```yaml
prometheusSpec:
  scrapeClasses:
    - default: true
      name: cluster-relabelling
      relabelings:
        - sourceLabels: [ __name__ ]
          regex: (.*)
          targetLabel: cluster
          replacement: my-cluster
          action: replace
```

**Comment by Tiduster** [comment]
@rgauthey : works perfectly, thanks.

**Comment by ehsanafter** [comment]
i have used external labels on another project which works just fine
but with kube_prometheus stack non seem to work
only if you add it to the servicemonitor itself
seems like there is no generic way here.
trying scrapeclass now.
weird

**Comment by pedropilla** [comment]
@rgauthey perfect, thanks!

**Comment by jacobw** [comment]
@rgauthey also thanks, that's much better than my previous method.

I wonder if there would be any appetite to add this as a simple option to set in values.yaml, that would generate the scrapeClasses configuration, to save people having to learn this bit.

**Comment by ashaank** [comment]
@rgauthey your solution worked flawlessly. Thanks!

**Comment by arun-tl** [comment]
> prometheusSpec:
>   scrapeClasses:
>     - default: true
>       name: cluster-relabeling
>       relabelings:
>         - sourceLabels: [ __name__ ]
>           regex: (.*)
>           targetLabel: cluster
>           replacement: my-cluster
>           action: replace

where should i need to add this inorder to get the cluster label

**Comment by tsndqst** [comment]
> where should i need to add this inorder to get the cluster label

It goes under the top level `prometheus` value.
https://github.com/prometheus-community/helm-charts/blob/ba04297b341a59ac627dee9ec4b8e9686708fb6f/charts/kube-prometheus-stack/values.yaml#L3917

```
prometheus:
  prometheusSpec:
    scrapeClasses:
      - default: true
        name: cluster-relabeling
        relabelings:
          - sourceLabels: [ __name__ ]
            regex: (.*)
            targetLabel: cluster
            replacement: my-cluster
            action: replace
```
