### ISSUE TITLE
[kube-prometheus-stack] improvements to additionalDataSources

### ISSUE THREAD

**Issue by romelBen** [prometheus-community/helm-charts#4968]
### Is your feature request related to a problem ?

This is a small improvement to be made in the kube-prometheus-stack. The feature request is to be able to add external secrets that have been created in Kubernetes in the value `additionalDataSources`. The example that is provided is using `secureJsonData` but I don't see this being secure since you would still hard code your secret into your repository.

```yaml
    - name: GitHub (App)
      type: grafana-github-datasource
      jsonData:
        selectedAuthType: github-app
        appId: 2345252
        installationId: 2342343243
      secureJsonData:
        privateKey: <your_private_key>
 ```

### Describe the solution you'd like.

The possibility of using a flag for an existing kubernetes secret to be added.

### Describe alternatives you've considered.

Currently I'm looking into using `secretKeyRef` for this to work but I find this to be a pain where I have to mount the secret and reference.
