### ISSUE TITLE
[prometheus] Some metrics not working when use basic_auth_users

### ISSUE THREAD

**Issue by rubentest** [prometheus-community/helm-charts#4977]
### Describe the bug a clear and concise description of what the bug is.

When I add basic_auth_users to prometheus to protect enpoint, for example: `prometheus_build_info` metric stops working. 
Other metrics like kube related info, pods, etc are working correctly as usual.

The code that I add:

```
extraManifests:  +(mounted the manifest) with the info of basic_auth_users
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: web
    data:
      web.yml: |-
        basic_auth_users:
           xxx:xxxx
 
   extraFlags:  # to use the extra config.
    - web.enable-lifecycle
    - 'web.config.file=/etc/extra-conf/web.yml'
 
   probeHeaders:  # to use in the probes to start correctly prometheus
    - name: "Authorization"
      value: "Basic XXXXX"
      
```

### What's your helm version?

ArgoCD 2.12 -> Helm version 3.15.2

### What's your kubectl version?

kubectl version Client Version: v1.30.3 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.29.5

### Which chart?

prometheus

### What's the chart version?

25.28.0

### What happened?

Some metrics not working when use basic_auth_users

### Enter the command that you execute and failing/misfunctioning.

Prometheus query to prometheus_build_info
