### ISSUE TITLE
Repository index file has urls pointing to github releases instead of helm repository

### ISSUE THREAD

**Issue by speakyourcode** [prometheus-community/helm-charts#4980]
### Describe the bug a clear and concise description of what the bug is.

We have set up Artifactory to mirror the repository in an air-gapped environment and we're hitting the proxy because many urls point to github releases instead of the prometheus community helm repository. For example, `prometheus-consul-exporter` URL has changed from version 0.1.5 to version 0.1.6:
```yaml 
   name: prometheus-consul-exporter
    urls:
    - https://github.com/prometheus-community/helm-charts/releases/download/prometheus-consul-exporter-0.1.6/prometheus-consul-exporter-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v1
    appVersion: 0.4.0
    ...
    name: prometheus-consul-exporter
    urls:
    - https://prometheus-community.github.io/helm-charts/prometheus-consul-exporter-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v1
    appVersion: 0.4.0
    ...
``` 
Is there a reason for this?
Thanks!

### What's your helm version?

version.BuildInfo{Version:"v3.16.2", GitCommit:"13654a52f7c70a143b1dd51416d633e1071faffb", GitTreeState:"clean", GoVersion:"go1.22.7"}

### What's your kubectl version?

v1.31.2

### Which chart?

prometheus-consul-exporter

### What's the chart version?

0.1.6

### Enter the command that you execute and failing/misfunctioning.

`helm install prometheus-consul-exporter prometheus-community/prometheus-consul-exporter --version 0.1.6`
