### ISSUE TITLE
[kube-state-metrics] Wrong readyz endpoint used, failing with latest ksm-release 2.14.0

### ISSUE THREAD

**Issue by sfudeus** [prometheus-community/helm-charts#4981]
### Describe the bug a clear and concise description of what the bug is.

Liveness and readiness are are checked against /readyz and /livez, startupProbe is configured to /healthz. 
It seems already in 2.13.0 it was defined that specifically /readyz is available on the telemetry port, the others are on the standard/metrics port. The charts configures all on the standard port. Added in https://github.com/kubernetes/kube-state-metrics/pull/2442/files, current docs here: https://github.com/kubernetes/kube-state-metrics/blob/main/README.md#healthcheck-endpoints

With ksm 2.13.0, the index page was delivered on /readyz on the standard port, with status 200, so no problem was noticed, just not using the correct endpoint as intended by ksm.
With ksm 2.14.0, /readyz on the standard port return 404, now breaking the readiness probe. 

### What's your helm version?

version.BuildInfo{Version:"v3.12.2-1", GitCommit:"e6372f9729a7e1ba8d68fdd116a64dc0fecf692e", GitTreeState:"clean", GoVersion:"go1.21.6"}

### What's your kubectl version?

Client Version: v1.31.2 Kustomize Version: v5.4.2 Server Version: v1.29.10+k3s1

### Which chart?

kube-state-metrics

### What's the chart version?

5.26.0

### What happened?

With ksm 2.14.0, the kube-state-metrics pod doesn't come up because the readiness probe fails.

### What you expected to happen?

readiness-probe should work as intended

### How to reproduce it?

Take the chart 5.26.0 and override image.tag to v2.14.0

### Enter the changed values of values.yaml?

image:
  tag: v2.14.0

### Enter the command that you execute and failing/misfunctioning.

`helm install my-ksm prometheus-community/kube-state-metrics --version 5.26.0 ` becomes ready
`helm upgrade my-ksm prometheus-community/kube-state-metrics --version 5.26.0 --set image.tag=v2.14.0` fails

**Comment by mrueg** [comment]
Resolved in https://github.com/prometheus-community/helm-charts/pull/4982

**Comment by crouth-redge** [comment]
@mrueg This change has broken the readiness probe as it does not account for the `selfMonitor` being set to false, which is a chart _default_

https://github.com/prometheus-community/helm-charts/pull/4982#issuecomment-3272274588

```yaml
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - --port=8080
        - --resources=certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,leases,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments
        - --metric-labels-allowlist=*=[app.kubernetes.io/team,app.kubernetes.io/name,app,team,stream],nodes=[agentpool,alpha.eksctl.io/cluster-name,alpha.eksctl.io/nodegroup-name,beta.kubernetes.io/instance-type,cloud.google.com/gke-nodepool,cluster-name,ec2.amazonaws.com/Name,ec2.amazonaws.com/aws-autoscaling-groupName,ec2.amazonaws.com/aws-autoscaling-group-name,ec2.amazonaws.com/name,eks.amazonaws.com/nodegroup,k8s.io/cloud-provider-aws,karpenter.sh/nodepool,kubernetes.azure.com/cluster,kubernetes.io/arch,kubernetes.io/hostname,kubernetes.io/os,node.kubernetes.io/instance-type,topology.kubernetes.io/region,topology.kubernetes.io/zone]
        - --custom-resource-state-config-file=/etc/customresourcestate/config.yaml
        image: us-docker.pkg.dev/finer-muskox-hh3u/registry-k8s/kube-state-metrics/kube-state-metrics:v2.17.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: kube-state-metrics
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
```
