### ISSUE TITLE
[kube-prometheus-stack] There should be a ClusterRole to be aggregated into view/edit/admin

### ISSUE THREAD

**Issue by cwrau** [prometheus-community/helm-charts#4991]
### Is your feature request related to a problem ?

It is very useful if applications that create CRDs also create a ClusterRole with one or more of

```
rbac.authorization.k8s.io/aggregate-to-view: "true"
rbac.authorization.k8s.io/aggregate-to-edit: "true"
rbac.authorization.k8s.io/aggregate-to-admin: "true"
```

that way the end user doesn't have to specify the custom resources for the admins.

### Describe the solution you'd like.

The chart should ship ClusterRole(s), maybe names `kube-prometheus-stack-{view,edit-admin}` that include the corresponding RBAC and labels.

### Describe alternatives you've considered.

Everything I could think of involves writing RBAC by hand.

**Comment by jkroepke** [comment]
Are you interrest into a contribution/PR?

An upstream example can be found here: https://github.com/prometheus-operator/prometheus-operator/blob/5f512d21361a300889388c3a174f4349fef3604d/example/rbac/prometheus-operator-crd/prometheus-operator-crd-cluster-roles.yaml#L8

I would highly recommend to create 2 roles. 

Example values yaml structure:

```yaml
rbac:
  roles:
    edit:
      enabled: true
      kind: ClusterRole
      labels:
        rbac.authorization.k8s.io/aggregate-to-edit: "true"
        rbac.authorization.k8s.io/aggregate-to-admin: "true"
     extraRules: []
    view:
      enabled: true
      kind: ClusterRole
      labels:
        rbac.authorization.k8s.io/aggregate-to-edit: "true"
        rbac.authorization.k8s.io/aggregate-to-admin: "true"
        rbac.authorization.k8s.io/aggregate-to-view: "true"
     extraRules: []
```
