### ISSUE TITLE
[prometheus-snmp-exporter] Missing containerSecurityContext for configmap-reload

### ISSUE THREAD

**Issue by danilomcloud** [prometheus-community/helm-charts#4996]
### Describe the bug a clear and concise description of what the bug is.

configmap-reload container wasn't using containerSecurityContext configuration. So it's not possible to create configmap-reload if I have some gatekeeper with policy blocking missing security configurations like "allowPrivilegeEscalation: false" 

### What's your helm version?

"v3.13.1"

### What's your kubectl version?

v1.28.3

### Which chart?

prometheus-snmp-exporter

### What's the chart version?

5.6.0

### What happened?

configmap-reload container wasn't using containerSecurityContext configuration

### What you expected to happen?

Configmap-reload container uses the same containerSecurityContext configuration of  prometheus-snmp-exporter container.

### How to reproduce it?

Apply chart and check for SecurityContext at configmap-reload container

### Enter the changed values of values.yaml?
```

#enable config options
config: |
xxx
## Security context to be added to snmp-exporter pods
securityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true

## Security context to be added to snmp-exporter containers
containerSecurityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  privileged: false
  seccompProfile:
    type: RuntimeDefault
  appArmorProfile:
    type: RuntimeDefault
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade prometheus-snmp-exporter -n testing --values=prometheus-snmp-exporter.yaml prometheus-community/prometheus-snmp-exporter --version=5.6.0

### Anything else we need to know?

It's possible to do that, updating deployment.yaml template like (just add securityContext: config):

```
      {{- if .Values.config }}
        - name: configmap-reload
          image: "{{ .Values.configmapReload.image.repository }}:{{ .Values.configmapReload.image.tag }}"
          imagePullPolicy: "{{ .Values.configmapReload.image.pullPolicy }}"
          args:
            - --watched-dir=/etc/config
            - --reload-url=http://localhost:{{ .Values.service.port }}/-/reload
          resources:
{{ toYaml .Values.configmapReload.resources | indent 12 }}
          volumeMounts:
            - mountPath: /etc/config
              name: config
              readOnly: true
{{- if .Values.containerSecurityContext }}
          securityContext:
{{ toYaml .Values.containerSecurityContext | indent 12 }}
        {{- end }}
      {{- end }}
```
