### ISSUE TITLE
[kube-prometheus-stack] alertmanager config only receives from a specific namespace

### ISSUE THREAD

**Issue by alperdevrim** [prometheus-community/helm-charts#4999]
Hi, I'm using AlertManagerConfig custom resource to set configs. But only the alerts from monitoring namespace (which alertmanager is in). How should I update the configuration?

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  labels:
    alertmanagerConfig: alertmanager
spec:
  route:
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 30m
    receiver: 'smtp'
    routes:
      - receiver: 'smtp'
```
