### ISSUE TITLE
[kube-prometheus-stack] Increase alert threshold

### ISSUE THREAD

**Issue by vignesh-v3** [prometheus-community/helm-charts#5028]
Hi there, 
I am trying to increase the threshold for the alert in Kube Prometheus stack.
but some how i get an error for this line specifically as its not allowing me to use {{ $labels.name }} 

```
            description: Kubernetes aggregated API {{ $labels.name }}/{{ $labels.namespace }} has reported errors. It has appeared unavailable {{ $value | humanize }} times averaged over the past 20m.
```

I have created this file
```
#helm-charts/kube-prometheus-stack/templates/prometheus-rules/kube-aggregated-api-errors.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-prometheus-stack-kubernetes-system-apiserver
  namespace: kube-prometheus-stack
  annotations:
    prometheus-operator-validated: "true"    # adjust namespace as needed
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 62.3.1
    chart: kube-prometheus-stack-62.3.1
    heritage: Helm
    release: kube-prometheus-stack
spec:
  groups:
    - name: kubernetes-system-apiserver
      rules:
        - alert: KubeAggregatedAPIErrors
          annotations:
            description: Kubernetes aggregated API {{ $labels.name }}/{{ $labels.namespace }} has reported errors. It has appeared unavailable {{ $value | humanize }} times averaged over the past 20m.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeaggregatedapierrors
            summary: Kubernetes aggregated API has reported errors.
          expr: |
            sum by (name, namespace, cluster)(increase(aggregator_unavailable_apiservice_total{job="apiserver"}[20m])) > 4
          labels:
            severity: warning    
```

Also i have the below values file which has got `KubeAggregatedAPIErrors` to true.

```
#helm-charts/kube-prometheus-stack/values.yaml
kube-prometheus-stack:
  defaultRules:
    rules:
      # Disabled since we don't manage control plane nodes in OKE.
      etcd: false
      kubeScheduler: false
      KubeAggregatedAPIErrors: true
```
