### ISSUE TITLE
[kube-prometheus-stack] remoteWrite does no effect

### ISSUE THREAD

**Issue by silencePR** [prometheus-community/helm-charts#5030]
### Describe the bug a clear and concise description of what the bug is.

Using remoteWrite feature does not cause prometheus write data to the remote location.

### What's your helm version?

version.BuildInfo{Version:"v3.14.2", GitCommit:"c309b6f0ff63856811846ce18f3bdc93d2b4d54b", GitTreeState:"clean", GoVersion:"go1.21.7"}

### What's your kubectl version?

Client Version: v1.29.3 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.29.3

### Which chart?

kube-prometheus-stack

### What's the chart version?

58.0.0

### What happened?

I declared "remote write" in values.yaml, upgraded kube-prometheus-stack (with restarting pods).
Metrics are available from local source, just like before, no data in remote database. 
I'm sure deployment has accepted configuration, because I've check it like this:

user@101-kuball:~/servers/kube-prometheus-stack$ helm get values kube-prometheus-stack -n monitoring
(...)
```
    remoteWrite:
    - basicAuth:
        password:
          key: pass
          name: influx-anarti
        username:
          key: user
          name: influx-anarti
      url: https://xxx.yyy.net:8086/api/v1/prom/write?db=importprometheus
prometheusOperator:
  enabled: true
```

### What you expected to happen?

I would like data flow into remote Influx database. 

### How to reproduce it?

 place into values.yaml
    remoteWrite:
      - url: https://xxx.yyy:8086/api/v1/prom/write?db=database

### Enter the changed values of values.yaml?

```
alertmanager:
  enabled: false
grafana:
  enabled: false
kubeStateMetrics:
  enabled: true
prometheusOperator:
  enabled: true

prometheus:
  prometheusSpec:
    remoteWrite:
      - url: https://xxx.yyy.net:8086/api/v1/prom/write?db=importprometheus
        basicAuth:
           username:
             name: influx-anarti
             key: user
           password:
             name: influx-anarti
             key: pass
        #tls_config:
        #  insecure_skip_verify: true
    nodeSelector:
      prometheus: "true"
    additionalScrapeConfigs:
      -  job_name: pod-k8s
         honor_timestamps: true
         scrape_interval: 5s
         scrape_timeout: 5s
         metrics_path: /actuator/prometheus
         scheme: http
         relabel_configs:
         - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
           separator: ;
           regex: "true"
           replacement: $1
           action: keep
         - source_labels: [__meta_kubernetes_service_name]
           separator: ;
           regex: (.*)
           target_label: service
           replacement: $1
           action: replace
         - source_labels: [__meta_kubernetes_pod_container_name]
           separator: ;
           regex: (.*)
           target_label: container
           replacement: $1
           action: replace
         - source_labels: [__address__]
           separator: ;
           regex: ([^:;]+):(\d+)
           target_label: __address__
           replacement: ${1}:8081
           action: replace
         kubernetes_sd_configs:
         - role: pod
      -  job_name: gpu-k8s
         honor_timestamps: true
         scrape_interval: 5s
         scrape_timeout: 5s
         metrics_path: /metrics
         scheme: http
         relabel_configs:
         - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
           separator: ;
           regex: "true"
           replacement: $1
           action: keep
         - source_labels: [__meta_kubernetes_service_name]
           separator: ;
           regex: (.*)
           target_label: service
           replacement: $1
           action: replace
         - source_labels: [__meta_kubernetes_pod_container_name]
           separator: ;
           regex: (.*)
           target_label: container
           replacement: $1
           action: replace
         - source_labels: [__address__]
           separator: ;
           regex: ([^:;]+):(\d+)
           target_label: __address__
           replacement: ${1}:9400
           action: replace
         kubernetes_sd_configs:
         - role: pod
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --recreate-pods kube-prometheus-stack prometheus-community/kube-prometheus-stack -f values.yaml -n monitoring --version 58.0.0

### Anything else we need to know?

The connection is via nginx proxy. Analyzing logs I can tell, there's no signs of connection, even ended with some "bad" http code.
I've tried with curl from all k8s nodes, it occurred in logs, so there is no firewall issue.

**Comment by darshandeshmukh11** [comment]
I could reproduce this issue with below config - 

version: `66.3.1`
appVersion: `v0.78.2`

Helm Version - 
```
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /opt/kube_config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /opt/kube_config
version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.20.10"}
```

```
prometheus:
  prometheusSpec:
    remoteWrite:
      - url: "https://monitoring-central.abc.com/api/v1/push"
        headers:
          X-Scope-OrgID: devops
        basic_auth:
           username: admin
           password: 3$dsdsd-dsd
```

Logs from prometheus pod - 

```
$ kubectl logs prometheus-kube-prometheus-kube-prome-prometheus-0 -n monitoring-remote
pod service account via in-cluster config"
ts=2024-12-09T08:48:29.199Z caller=kubernetes.go:331 level=info component="discovery manager notify" discovery=kubernetes config=config-0 msg="Using pod service account via in-cluster config"
ts=2024-12-09T08:48:29.202Z caller=manager.go:164 level=info component="rule manager" msg="Starting rule manager..."
ts=2024-12-09T08:48:29.298Z caller=main.go:1452 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=111.246207ms db_storage=1.291µs remote_storage=193.901µs web_handler=469ns query_engine=750ns scrape=90.61µs scrape_sd=1.924761ms notify=21.56µs notify_sd=476.215µs rules=98.746136ms tracing=8.43µs
ts=2024-12-09T08:48:35.160Z caller=dedupe.go:112 component=remote level=info remote_name=43a5e0 url=https://monitoring-central.abc.com/api/v1/push msg="Done replaying WAL" duration=6.044983732s
```
But I dont see any other logs after this and data is missing in my remote mimir/minio setup.

**Comment by ymatsiuk** [comment]
I wonder if you should follow https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#monitoring.coreos.com/v1.RemoteWriteSpec
which would be something like:
```
basicAuth:
  username: foo
  password: bar
```
Just a wild guess though, not 100% sure

**Comment by ymatsiuk** [comment]
I was just passing by, but this what I've tried on my `kind` cluster:
```
❯ kind create cluster
❯ cat <<EOF> values.yaml
alertmanager:
  enabled: false
grafana:
  enabled: false
kubeStateMetrics:
  enabled: true
prometheusOperator:
  enabled: true

prometheus:
  prometheusSpec:
    remoteWrite:
      - url: https://xxx.yyy.net:8086/api/v1/prom/write?db=importprometheus
        basicAuth:
           username:
             name: creds
             key: user
           password:
             name: creds
             key: pass
EOF
❯ helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack -f values.yaml -n monitoring --version 58.0.0 --create-namespace
❯ kubectl -n monitoring create secret generic creds --from-literal=user=supersecret --from-literal=pass=topsecret
❯ k -n monitoring exec -it prometheus-kube-prometheus-stack-prometheus-0 -c config-reloader -- cat /etc/prometheus/config_out/prometheus.env.yaml | tail -6
remote_write:
- url: https://xxx.yyy.net:8086/api/v1/prom/write?db=importprometheus
  remote_timeout: 30s
  basic_auth:
    username: supersecret
    password: topsecret
```

**Comment by kodeine** [comment]
@silencePR
were you able to figure this out? i'm in the same situation

**Comment by silencePR** [comment]
No, this is not crucial thing to me. I just wait till bug is fixed.

**Comment by ymatsiuk** [comment]
Folks, check my previous comment for details (I provided all the commands with the output where you can see the password is properly set); make sure the secrets exists in the `monitoring` namespace (the command to create the secret is also in my previous comment).

**Comment by kodeine** [comment]
I am setting remote source to mimir and it does not need password, what am i missing.

**Comment by ymatsiuk** [comment]
It doesn't really matter, everything works as documented and I was able to confirm this. You can use this code and retrofit your config into it.

This is the yaml I used for my test (you can remove `basicAuth` recursively):
```yaml
alertmanager:
  enabled: false
grafana:
  enabled: false
kubeStateMetrics:
  enabled: true
prometheusOperator:
  enabled: true

prometheus:
  prometheusSpec:
    remoteWrite:
      - url: https://xxx.yyy.net:8086/api/v1/prom/write?db=importprometheus
        basicAuth:
           username:
             name: creds
             key: user
           password:
             name: creds
             key: pass
```

Steps:
1. ensure the secret exists in the `monitoring` namespace: `kubectl -n monitoring create secret generic creds --from-literal=user=supersecret --from-literal=pass=topsecret`
2. install helm chart: `helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack -f values.yaml -n monitoring --version 58.0.0 --create-namespace` (I used exact version of chart author reported, but you can use the version you need)
3. wait for helm to finish deployment
4. check if the configuration file contains defined options: `kubect -n monitoring exec -it prometheus-kube-prometheus-stack-prometheus-0 -c config-reloader -- cat /etc/prometheus/config_out/prometheus.env.yaml | tail -6` (in my case last 6 lines were enough to see the presence of `remote_write` configuration, feel free to inspect full configuration (removing `| tail -6` bit) for confirmation)


In case last command's output doesn't contain `remote_write` configuration, please post exact steps to reproduce, since from what I can tell currently using provided information the issue you reported is not reproducible on random stranger's laptop 😉
