### ISSUE TITLE
[prometheus] extraConfigmapMounts not creating configmap file

### ISSUE THREAD

**Issue by igloo12** [prometheus-community/helm-charts#5037]
### Describe the bug a clear and concise description of what the bug is.

I am trying to add a configmap as a file to my prometheus deploy but the file is not showing up 

```
$ kubectl describe -n logging configmap my-configmap
Name:         my-configmap
Namespace:    logging
Labels:       <none>
Annotations:  <none>

Data
====
custom-config.yaml:
----
scrape_configs:
  - job_name: 'custom'
    static_configs:
      - targets: ['localhost:9090']



BinaryData
====

Events:  <none>
```

It's showing up in the mounts, but there is no file
```
    Readiness:      http-get http://:9090/-/ready delay=30s timeout=4s period=5s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /data from storage-volume (rw)
      /etc/config from config-volume (rw)
      /etc/prometheus/custom from server-my-extra (ro,path="custom-config.yaml")
      /tmp/config from server-service-passwords (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-hwqgb (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-server
    Optional:  false
  server-service-passwords:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-server
    Optional:  false
  server-my-extra:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      my-configmap
    Optional:  false
  storage-volume:
```

### What's your helm version?

version.BuildInfo{Version:"v3.16.3", GitCommit:"cfd07493f46efc9debd9cc1b02a0961186df7fdf", GitTreeState:"clean", GoVersion:"go1.22.7"}

### What's your kubectl version?

Client Version: v1.31.3 Kustomize Version: v5.4.2 Server Version: v1.27.2

### Which chart?

prometheus-26.0.0

### What's the chart version?

v3.0.0 

### What happened?

No file showing up in the pod

### What you expected to happen?

File to show up in the pod

### Enter the changed values of values.yaml?

```
server:
  extraConfigmapMounts:
    - name: service-passwords
      mountPath: /tmp/config
      configMap: prometheus-server
      readOnly: true
    - name: my-extra
      mountPath: /etc/prometheus/custom
      subPath: custom-config.yaml
      configMap: my-configmap
      readOnly: true
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade -n logging prometheus prometheus-community/prometheus -f prometheus-values.yaml
