### ISSUE TITLE
[kube-prometheus-stack] thanos-sidecar volumeMounts missing

### ISSUE THREAD

**Issue by jhuspek** [prometheus-community/helm-charts#5039]
### Is your feature request related to a problem ?

The Prometheus CRD supports adding volumeMounts to the Thanos sidecar container, but this functionality is not currently available in the Helm chart. Additional volumes are required to include an internal CA certificate, which is necessary for establishing a secure connection to on-premise S3 storage.

### Describe the solution you'd like.

Update the Helm chart to allow configuration of volumeMounts and associated volumes for the Thanos sidecar container via values.

**Example Expected Configuration:**

```YAML
prometheus:
  prometheusSpec:
#... ...    
    thanos:
      objectStorageConfig:
        secret:
          type: S3
#... ...
      volumeMounts:
        - name: ca-certificates
          mountPath: /etc/ssl/certs/ca-certificates.crt
          subPath: ca.cer
#... ...
volumes:
  - name: ca-certificates
    configMap:
      name: cm-ca
```

### Describe alternatives you've considered.

We can alternatively use an insecure connection to the S3 storage or the workaround mentioned in https://github.com/prometheus-community/helm-charts/issues/1461 which involves overriding the Thanos sidecar container. However, this approach forces us to bypass the operator's native support, adding unnecessary complexity to operations.
