### ISSUE TITLE
[kube-prometheus-stack] Enable alertmanager, no corresponding statefulset and pod created

### ISSUE THREAD

**Issue by MicroOps-cn** [prometheus-community/helm-charts#5054]
### Describe the bug a clear and concise description of what the bug is.

Create a release using the following configuration file, without creating a statfulset/altmanager, only a service/altmanager will be created
```yaml
alertmanager:
  enabled: true
  config:
    ***more ...***
```

### What's your helm version?

version.BuildInfo{Version:"v3.16.3", GitCommit:"cfd07493f46efc9debd9cc1b02a0961186df7fdf", GitTreeState:"clean", GoVersion:"go1.22.7"}

### What's your kubectl version?

Client Version: v1.31.0-eks-a737599/Server Version: v1.31.2-eks-7f9249a

### Which chart?

kube-prometheus-stack

### What's the chart version?

v0.78.2

### Enter the command that you execute and failing/misfunctioning.

 helm upgrade --install -n monitoring prometheus prometheus-community/kube-prometheus-stack -f prometheus-values.yaml

**Comment by MicroOps-cn** [comment]
```
# prometheus-values.yaml
fullnameOverride: k8s
cleanPrometheusOperatorObjectNames: true
# https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
grafana:
  enabled: false
# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml
prometheus-node-exporter:
  fullnameOverride: node-exporter
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                  - fargate
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
prometheus:
  prometheusSpec:
    retention: 90d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          resources:
            requests:
              storage: 40Gi
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 2Gi
    enableAdminAPI: true
kube-state-metrics:
  fullnameOverride: "kube-state-metrics"
prometheusOperator:
  fullnameOverride: "prometheus-operator"
alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
      ***more ...***
```

```
[root@ip-10-0-1-167 monitoring]# kubectl get svc -n monitoring
NAME                  TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
k8s-alertmanager      ClusterIP   172.22.7.10    <none>        9093/TCP,8080/TCP   43m
k8s-prometheus        ClusterIP   172.22.9.185   <none>        9090/TCP,8080/TCP   43m
kube-state-metrics    ClusterIP   172.22.12.43   <none>        8080/TCP            46m
node-exporter         ClusterIP   172.22.9.29    <none>        9100/TCP            59m
prometheus-operated   ClusterIP   None           <none>        9090/TCP            69m
prometheus-operator   ClusterIP   172.22.4.32    <none>        443/TCP             40m
[root@ip-10-0-1-167 monitoring]# kubectl get pods -n monitoring
NAME                                   READY   STATUS    RESTARTS      AGE
kube-state-metrics-5bd769947c-pglls    1/1     Running   0             46m
node-exporter-szkvt                    1/1     Running   0             60m
node-exporter-vbljj                    1/1     Running   0             60m
node-exporter-wk5hn                    1/1     Running   0             60m
prometheus-k8s-0                       2/2     Running   1 (43m ago)   43m
prometheus-operator-678577cfc5-jkwkh   1/1     Running   0             40m
[root@ip-10-0-1-167 monitoring]# kubectl get statefulsets.apps -n monitoring
NAME             READY   AGE
prometheus-k8s   1/1     43m
[root@ip-10-0-1-167 monitoring]# kubectl get deployments.apps -n monitoring
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
kube-state-metrics    1/1     1            1           47m
prometheus-operator   1/1     1            1           41m
[root@ip-10-0-1-167 monitoring]# kubectl get daemonsets.apps -n monitoring
NAME            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
node-exporter   3         3         3       3            3           kubernetes.io/os=linux   60m
```
