### ISSUE TITLE
[kube-prometheus-stack] missing cpu statistics with chart deployed by argocd

### ISSUE THREAD

**Issue by adippl** [prometheus-community/helm-charts#5070]
### Describe the bug a clear and concise description of what the bug is.

My kube-prometheus-stack grafana stoped displaying pod cpu statistics after I've upgraded my cluster to 1.30

`node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate` metric is missing from prometheus

there are no prometheus related alerts in alertmanager

### What's your helm version?

argocd v2.12.4

### What's your kubectl version?

Client Version: v1.30.6 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.30.6

### Which chart?

prometheus-kube-stack

### What's the chart version?

67.2.0

### What happened?

Chart deployed by argocd doesn't work correctly/

### What you expected to happen?

I would want kube-prometheus-chart to work on argocd

### How to reproduce it?

Install kube-prometheus-chart with argocd.

### Enter the changed values of values.yaml?
```
fullnameOverride: "kps"
prometheus:
  networkPolicy:
    enabled: false

    flavor: kubernetes
  ingress:
    enabled: true
    ingressClassName: admin-ingress
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    labels: {}
    hosts:
      - prometheus.k8s3.domain.example
    path: /
    tls:
    - hosts:
        - prometheus.k8s3.domain.example
      secretName: prometheus.k8s3.domain.example-tls
    pathType: Prefix
  prometheusSpec:
    priorityClassName: "high-priority"
    externalLabels:
      cluster: k8s3
    retention: 14d
    replicas: 1
    podAntiAffinity: "hard"
    scrapeTimeout: 30s
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 200Gi
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector:
      matchLabels:
        prometheus: main
    podMonitorSelector: {}
    podMonitorNamespaceSelector:
      matchLabels:
        prometheus: main
    ruleSelector: {}
    ruleNamespaceSelector:
      matchLabels:
        prometheus: main
    resources:
     requests:
       cpu: 250m
       memory: 1536Mi
     limits:
       cpu: 2000m
       memory: 2048Mi
    priorityClassName: "high-priority"

grafana:
  adminPassword: xxxxxx
  sidecar:
    dashboards:
      searchNamespace: ALL
  serviceMonitor:
    scrapeTimeout: 10s
  ingress:
    enabled: true
    ingressClassName: admin-ingress
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    labels: {}
    hosts:
      - grafana.k8s3.domain.example
    path: /
    tls:
    - hosts:
        - grafana.k8s3.domain.example
      secretName: grafana.k8s3.domain.example-tls
  resources:
    requests:
      cpu: 150m
      memory: 384Mi
    limits:
      cpu: 500m
      memory: 512Mi
  prometheusSpec:
    priorityClassName: "high-priority"

prometheusOperator:
  resources:
    requests:
      cpu: 1m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 200Mi
  priorityClassName: "high-priority"
  networkPolicy:
    enabled: false

alertmanager:
  alertmanagerSpec:
    priorityClassName: "high-priority"
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'email'
      routes:
      - receiver: "null"
        matchers:
        - alertname =~ "Watchdog|InfoInhibitor"
      - receiver: "null"
        matchers:
        - alertname =~ "CephNodeNetworkPacketDrops"
        - device =~ "vnet.*|cilium_wg0"
    receivers:
    - name: "null"
    - name: 'email'
      email_configs:
      - to: 'xxxxxxxxxxx@xxxxxxx.xxx'
        from: 'xxxxxxxxxxx@xxxxxxx.xxx'
        smarthost: xxxx.xxxxxxx.xxx:587
        auth_username: 'xxxxxxx'
        auth_password: 'xxxxxxxxxxxxxxxxxxxxxxxxx'
        require_tls: true
    templates:
    - '/etc/alertmanager/config/*.tmpl'

defaultRules:
  rules:
    kubeProxy: false

kubeProxy:
  enabled: false
```
### Enter the command that you execute and failing/misfunctioning.

prometheus query `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate`
