### ISSUE TITLE
[prometheus-kube-stack] Enable otlp receiver

### ISSUE THREAD

**Issue by truongnht** [prometheus-community/helm-charts#5080]
### Is your feature request related to a problem ?

For new Prometheus 3.0 to receive OTLP metrics, OTLP receiver feature needs to be enabled via cli arg `web.enable-otlp-receiver`. This option is not available at this moment in helmchart. 

### Describe the solution you'd like.

Add option to enable `otlp-receiver`

### Describe alternatives you've considered.

n/a

**Comment by bartvanackooij** [comment]
You could use the `additonalArgs` on the `prometheus.prometheusSpec` to enable it: 

```
prometheus:
  prometheusSpec:
    additionalArgs:
      - name: web.enable-otlp-receiver
        value: ""
```

**Comment by truongnht** [comment]
@bartvanackooij let me try out, thanks

**Comment by pieterv-icloud-com** [comment]
If followed the instructions here: https://prometheus.io/docs/guides/opentelemetry/#send-opentelemetry-metrics-to-the-prometheus-server

I then configured an opentelemetry otel exporter with a similar url: https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlphttpexporter/README.md

The otel exporter complained about an invalid port because it is not expecting the path in the url.

**Comment by danielcn** [comment]
That is the config that I'm using:

On Prometheus side:

```
prometheus:
  prometheusSpec:
    scrapeInterval: "15s"  # Sets the global scrape interval
    additionalScrapeConfigs:
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['0.0.0.0:8889'] # or 'otel-collector.monitoring.svc.cluster.local:8889' if inside Kubernetes service into monitoring namespace.
```


On the Otel-Collector side:

```
exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
receivers:  
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          static_configs:
            - targets: ['0.0.0.0:8888']
service:
  extensions:
  - health_check
  pipelines:
    logs:
      exporters:
      - debug
      receivers:
      - otlp
    metrics:
      exporters:
      - debug
      - prometheus
      receivers:
      - otlp
      - prometheus
    traces:
      exporters:
      - debug
      receivers:
      - otlp
```

**Comment by diegocejasprieto** [comment]
@franco-roura were you able to solve your error? I have the same problem

**Comment by wokwong** [comment]
> [@bartvanackooij](https://github.com/bartvanackooij) let me try out, thanks

Hi ，Is there any result? Does it work?

**Comment by CosminLungu-NTTDATA** [comment]
Hi, I've solved this issue.

First, add the following lines to `templates/prometheus/prometheus.yaml`:
```yaml
{{- if .Values.prometheus.prometheusSpec.otlp }}
  otlp:
{{ toYaml .Values.prometheus.prometheusSpec.otlp | indent 4 }}
{{- end }}
```

Then, edit the `values.yaml` file:
```yaml
prometheus:
  prometheusSpec:
    otlp:
      promoteResourceAttributes:
        - service.instance.id
        - service.name
        - service.namespace
        - cloud.availability_zone
        - cloud.region
        - container.name
        - deployment.environment.name
        - k8s.cluster.name
        - k8s.container.name
        - k8s.cronjob.name
        - k8s.daemonset.name
        - k8s.deployment.name
        - k8s.job.name
        - k8s.namespace.name
        - k8s.pod.name
        - k8s.replicaset.name
        - k8s.statefulset.name
      translationStrategy: NoUTF8EscapingWithSuffixes
      keepIdentifyingResourceAttributes: true
```

With these changes, Prometheus will be deployed with OTLP enabled.

**Important Note:**
If you have `prometheus.prometheusSpec.routePrefix` set, you'll need to add this prefix to your OpenTelemetry exporter configuration:

Example with routePrefix set to "/prometheus/":
```yaml
config:
  exporters:
    debug: {}
    otlphttp/prometheus:
      endpoint: http://kube-prometheus-stack-prometheus.monitoring.svc:9090/prometheus/api/v1/otlp
```
(Note: I don't include the `/v1/metrics` path because OpenTelemetry will add it automatically when it's in the exporters section)

**Comment by ole12138** [comment]
This is my configuration, it works well:

`
server:
  extraFlags:
    - web.enable-otlp-receiver     
  otlp:
    promoteResourceAttributes:
      - service.instance.id
      - service.name
      - service.namespace
      - cloud.availability_zone
      - cloud.region
      - container.name
      - deployment.environment.name
      - k8s.cluster.name
      - k8s.container.name
      - k8s.cronjob.name
      - k8s.daemonset.name
      - k8s.deployment.name
      - k8s.job.name
      - k8s.namespace.name
      - k8s.pod.name
      - k8s.replicaset.name
      - k8s.statefulset.name
    translationStrategy: NoUTF8EscapingWithSuffixes
    
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite ^/otlp(/|$)(.*) /api/v1/otlp/$2 break;
	#...
`

Somebody submitted a PR about otlp, ref: https://github.com/prometheus-community/helm-charts/pull/5179

Default otlp uri in prometheus has a prefix "/api/v1", should be rewrited.  ref: https://prometheus.io/docs/guides/opentelemetry/#send-opentelemetry-metrics-to-the-prometheus-server

**Comment by liyaka** [comment]
Any update regarding updating kube-prometheus-stack helm chart to support it as well?

**Comment by QuentinBisson** [comment]
This is being addressed https://github.com/prometheus-community/helm-charts/pull/5793

**Comment by liyaka** [comment]
Unfortunately, this fix does not help since the fixed configuration is enabled only when Prometheus is running in agentMode, see  https://github.com/prometheus-community/helm-charts/blob/1a5241291d5e41664b5538693b995408fb2858ab/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L2

**Comment by QuentinBisson** [comment]
It should also run on server mode, this condition is only to change the kind: https://github.com/prometheus-community/helm-charts/blob/1a5241291d5e41664b5538693b995408fb2858ab/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L5

**Comment by liyaka** [comment]
configmap is not created..

**Comment by jacob7395** [comment]
For completeness, I got this working with `kube-prometheus-stack` using the following `values.yaml`:

```yaml
prometheus:
  prometheusSpec:
    enableOTLPReceiver: true
    otlp:
      promoteResourceAttributes:
        - service.instance.id
        - service.name
        - service.namespace
        - cloud.availability_zone
        - cloud.region
        - container.name
        - deployment.environment.name
        - k8s.cluster.name
        - k8s.container.name
        - k8s.cronjob.name
        - k8s.daemonset.name
        - k8s.deployment.name
        - k8s.job.name
        - k8s.namespace.name
        - k8s.pod.name
        - k8s.replicaset.name
        - k8s.statefulset.name
        - k8s.statefulset.name
      translation_strategy: NoUTF8EscapingWithSuffixes
      keepIdentifyingResourceAttributes: true
    tsdb:
      outOfOrderTimeWindow: 30m
```

My `open-telemetry/opentelemetry-collector` `values.yaml` looks like this:

```yaml
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318

  processors:
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25
    batch:
      send_batch_size: 10000
      timeout: 200ms

  exporters:
    otlphttp/prom:
      endpoint: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/otlp
    debug:
      verbosity: detailed

  pipelines:
    metrics:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - otlphttp/prom
        # - debug
```

For debugging, I found it helpful to add an additional attribute using the following processor:

```yaml
  processors:
    transform/add_arc_source:
      error_mode: ignore
      metric_statements:
        - set(resource.attributes["source"], "otc-arc-service")
        - set(resource.attributes["service.name"], resource.attributes["k8s.deployment.name"]) # Not sure why this is needed, but without it my service appears as unknownservice:dotnet

  pipelines:
    metrics:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - transform/add_arc_source
        - batch
      exporters:
        - otlphttp/prom
        # - debug
```

If you do add this attribute don't forget to include it in your list of `promoteResourceAttributes`.

Thanks to everyone who contributed to this issue—it was a bit tricky to piece together. A few notes from my debugging process (these may become outdated over time):

* Prometheus does not log incoming requests to `/api/v1/otlp/v1/metrics`, even when debugging is enabled.
* The relevant pod for me was `prometheus-prometheus-kube-prometheus-prometheus-0`, but this may differ depending on your deployment method. The pod should include `--web.enable-otlp-receiver` in its args.
* There is no need to use `additionalArgs: []` in your prom `values.yaml` the arg added when you set `enableOTLPReceiver: true`
* Enabling `debug: verbosity: detailed` in the OpenTelemetry Collector helps surface errors if pushing metrics to Prometheus fails.
* As noted in [this comment](https://github.com/prometheus-community/helm-charts/issues/5080#issuecomment-2824479621), the `/v1/metrics` suffix is currently not required in the OTLP HTTP exporter's endpoint.
