### ISSUE TITLE
[prometheus-postgres-exporter] Multi Target Bug

### ISSUE THREAD

**Issue by emily-ganze** [prometheus-community/helm-charts#5106]
### Describe the bug a clear and concise description of what the bug is.

With prometheus-postgres-exporter.serviceMonitor.multipleTarget.enabled = true, `DATA_SOURCE_URI` is still being set via .Values.config.datasource which is not used by the multipleTarget feature.

### What's your helm version?

version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.19.2"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"31", GitVersion:"v1.31.3-eks-56e63d8", GitCommit:"7a5334cf6c02f054f69ceef6698ffa059441b7c9", GitTreeState:"clean", BuildDate:"2024-12-03T17:52:44Z", GoVersion:"go1.22.8", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.25) and server (1.31) exceeds the supported minor version skew of +/-1

### Which chart?

prometheus-postgres-exporter

### What's the chart version?

6.8.1

### What happened?

env variable name: DATA_SOURCE_URI, value: ':5432/?sslmode=disable' caused connection errors.

### What you expected to happen?

postgres exporter should use the values in the service monitor + config map to connect to the db's not the DATA_SOURCE_URI env var.

### How to reproduce it?

use values listed below

### Enter the changed values of values.yaml?

  serviceMonitor:
    enabled: true
    multipleTarget:
      enabled: true
      targets:
      - endpoint: connectionstring-one
        name: one
        databaseName: one
      - endpoint: connectionstring-two
        name: two
        databaseName: two

  config:
    postgresExporter: |
      auth_modules:
        one:
          type: userpass
          userpass:
            username: something
            password: anotherthing
        two:
          type: userpass
          userpass:
            username: something
            password: anotherthing

### Enter the command that you execute and failing/misfunctioning.

helm install -f ./postgres-exporter/values.yaml -f ../../base/postgres-exporter.yaml postgres-exporter ./postgres-exporter

**Comment by emily-ganze** [comment]
@deem1978 no, we have not solved the problem.

**Comment by deem1978** [comment]
I am running in an other issue, this is the error:
`False  	Helm upgrade failed for release aa-monitoring/aa-prometheus-postgres-exporter with chart prometheus-postgres-exporter@6.10.0: template: prometheus-postgres-exporter/templates/deployment.yaml:31:28: executing "prometheus-postgres-exporter/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: prometheus-postgres-exporter/templates/configmap.yaml:11:18: executing "prometheus-postgres-exporter/templates/configmap.yaml" at <.Values.config.postgresExporter>: wrong type for value; expected string; got map[string]interface {`

This is my values.yaml:
```
replicaCount: 1

service:
  labels:
    app.kubernetes.io/component: monitoring
    prometheus: external-services-monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
    prometheus.io/path: "/metrics"
  port: 80
  targetPort: 9187
  type: ClusterIP
  name: http

automountServiceAccountToken: false

serviceMonitor:
  # When set true then use a ServiceMonitor to configure scraping
  enabled: true
  # Set the namespace the ServiceMonitor should be deployed
  # namespace: monitoring
  # Set how frequently Prometheus should scrape
  interval: 30s
  # Set path to cloudwatch-exporter telemtery-path
  # telemetryPath: /metrics
  # Set labels for the ServiceMonitor, use this to define your scrape label for Prometheus Operator
  # labels:
  # Set timeout for scrape
  timeout: 10s
  # Set of labels to transfer from the Kubernetes Service onto the target
  # targetLabels: []
  # MetricRelabelConfigs to apply to samples before ingestion
  metricRelabelings:
    # Map the "__param_target" label to "instance" for visibility in metrics
    - sourceLabels: [__param_target]
      targetLabel: instance
    # Map the "__param_target" label to "db_target" for custom identification
    - sourceLabels: [__param_target]
      targetLabel: db_target
  # Set relabel_configs as per https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
  relabelings:
    # Add the Kubernetes service name as the "job" label
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: job
    # Map the "__param_target" label to "instance" for scrape identification
    - sourceLabels: [__param_target]
      targetLabel: instance
    # Add the "__param_target" as a label in metrics
    - sourceLabels: [__param_target]
      targetLabel: target
  # HTTP scheme to use for scraping. For example `http` or `https`. Default is `http`.
  # scheme: http
  # TLS configuration to use when scraping the metric endpoint by Prometheus.
  # tlsConfig: {}

   # Use multipleTarget mode
  multipleTarget:
    enabled: true
    # Use the same auth module for every target
    # The config file should have a section like [$name]
    sharedAuthModule:
      enabled: false
      name: ""

    # Define each target's endpoint and name
    # When not using sharedAuthModule the config file should have one authModule for each target with key "client.$name"
    targets:
      - endpoint: <ip_first_db>
        name: first_db_name
        port: 5432
        databaseName: db
      - endpoint: <ip_second_db>
        name: second_db_name
        port: 5432
        databaseName: db

prometheusRule:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

rbac:
  # Specifies whether RBAC resources should be created
  create: false

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: false
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
  # Add annotations to the ServiceAccount, useful for EKS IAM Roles for Service Accounts or Google Workload Identity.
  annotations: {}

# Add a default ingress to allow namespace access to service.targetPort
# Helpful if other NetworkPolicies are configured in the namespace
networkPolicy:
  # Specifies whether a NetworkPolicy should be created
  enabled: false
  # Set labels for the NetworkPolicy
  labels: {}

# The securityContext of the pod.
# See https://kubernetes.io/docs/concepts/policy/security-context/ for more.
podSecurityContext:
  runAsGroup: 1001
  runAsUser: 1001
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# The securityContext of the container.
# See https://kubernetes.io/docs/concepts/policy/security-context/ for more.
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true

config:
  postgresExporter: |
    auth_modules:
      first_db_name:
        type: userpass
        userpass:
          username: metrics_postgres_exporter
        options:
          sslmode: disable
      second_db_name:
        type: userpass
        userpass:
          username: metrics_postgres_exporter
        options:
          sslmode: disable

# Configurable probes. If TLS client authentication is enabled at the exporter, TCP probe must be used.
livenessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTP
  # tcpSocket:
  #   port: http
  timeoutSeconds: 3

readinessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTP
  # tcpSocket:
  #   port: http
  timeoutSeconds: 1

podDisruptionBudget:
  enabled: false
  maxUnavailable: 1
```
Consider that I will inject the password field with a patch encrypted with sops, this should not be a problem because I do the same with my mysql-exporter and it works.
Do you have an idea about this map/string error?
