### ISSUE TITLE
prometheus-kube-stack - Alertmanager not working with SMTP configs

### ISSUE THREAD

**Issue by anihitk07** [prometheus-community/helm-charts#511]
**Describe the bug**

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
3.4.0
```

Kubernetes Version:

```console
$ kubectl version
please put the output of it here
1.19.3

**Which chart**:  prometheus-community/kube-prometheus-stack i.e  kube-prometheus-stack-12.8.0

**Which version of the chart**:  0.44.0

**What happened**: Alertmanager doesn't load while we try to configure Alertmanager with SMTP settings

**What you expected to happen**: Alertmanager should get loaded with provided SMTP settings

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
    - xxxxxxxx
    paths:
    - /prometheus(/|$)(.*)
    tls:
    - secretName: keyvault-certificate
      hosts:
      - xxxxxxx
  prometheusSpec:
    routePrefix: /
    externalUrl: https://xxxxxx/prometheus

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'email_config'
    receivers:
    - name: 'email_config'
      email_configs:
      - to: 'a@b.com'
        from: 'no-reply@a.b'
        smarthost: 'host:587'
        auth_username: uuuuuu
        auth_password: ppppppp
        require_tls: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
    - xxxxxxx
    paths:
    - /alertmanager(/|$)(.*)
    tls:
    - secretName: keyvault-certificate
      hosts:
      - xxxxxxxx
  alertmanagerSpec:
    routePrefix: /
    externalUrl: https://xxxxxxx/alertmanager
    
grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
    - xxxxxxx
    path: /grafana(/|$)(.*)
    tls:
    - secretName: keyvault-certificate
      hosts:
      - xxxxxx
  grafana.ini:
    server:
      domain: xxxxxxxx
      root_url: "%(protocol)s://%(domain)s/grafana/"
      enable_gzip: "true"

# Disable control plane metrics
kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false


**The helm command that you execute and failing/misfunctioning**:

For example:

```console
helm install prometheus prometheus-community/kube-prometheus-stack -n metricaservices-dev2 -f values.yaml --set grafana.adminPassword=$GRAFANA_ADMINPASSWORD
```

**Helm values set after installation/upgrade:**

```console
helm get values my-release
```

**Anything else we need to know**:  while trying to load https://xxxxxx/alertmanager/ it says - 503 Service Temporarily Unavailable

**Comment by okhuz** [comment]
Exactly I am having the same issue. It seems like it doesn't even mount it on the pod itself.

**Comment by jbouzekri** [comment]
:+1: same issue with chart version 13.0.2. A secret is created but not mounted in the statefulset and so the pod itself

**Comment by monotek** [comment]
Seems you know the solution so would be realy nice you could add na pr :)

**Comment by antoineozenne** [comment]
Same issue in kube-prometheus-stack 13.13.0.

**Comment by cvandesande** [comment]
Same issue,
Chart: kube-prometheus-stack-14.5.0	
APP: 0.46.0  

It seems 2 secrets are created with overlapping information
alertmanager-kube-prometheus-stack-alertmanager - has all the SMTP configs from the values file but it not mounted in the Statefulset
alertmanager-kube-prometheus-stack-alertmanager-generated - Has some SMTP configs from the values file and is mounted in the Statefulset

**Comment by cvandesande** [comment]
Never mind, seems like the issue is created when I have some bad values in Values.yaml.
The following smtp config works for me
```
  ## Alertmanager configuration directives
  ## ref: https://prometheus.io/docs/alerting/configuration/#configuration-file
  ##      https://prometheus.io/webtools/alerting/routing-tree-editor/
  ##
  config:
    global:
      smtp_smarthost: 'smtp.example.com:25'
      smtp_from: 'alertmanager@example.com'
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'smtp'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'smtp'
    receivers:
    - name: 'smtp'
      email_configs:
      - to: some'user@example.com'
        require_tls: false
    templates:
    - '/etc/alertmanager/config/*.tmpl'
```
