### ISSUE TITLE
[kube-prometheus-stack] How to monitor host network metrics without exposing Node Exporter on hostNetwork?

### ISSUE THREAD

**Issue by dtamienER** [prometheus-community/helm-charts#5138]
### Describe the bug a clear and concise description of what the bug is.

I need to monitor the network usage (e.g., incoming/outgoing traffic) of each node in my Kubernetes cluster using Node Exporter. However, I have the following requirements:

- The Node Exporter must have access to the host's network interfaces to collect accurate metrics (e.g., node_network_receive_bytes_total, node_network_transmit_bytes_total).

- The Node Exporter should not expose port 9100 on the host's network interface. This is to prevent unauthorized access to the metrics from outside the cluster.

- The Node Exporter metrics should only be accessible within the Kubernetes cluster, for example, by Prometheus or other internal services.

### What's your helm version?

v3.16.3

### What's your kubectl version?

v1.30.6-dispatcher

### Which chart?

prometheus-kube-stack

### What's the chart version?

67.8.0

### What happened?

I deployed the kube-prometheus-stack Helm chart with Node Exporter to monitor network usage on each node in my Kubernetes cluster.

When I disabled hostNetwork in the Node Exporter configuration, the Node Exporter pods lost access to the host's network interfaces and could not collect accurate network metrics (e.g., node_network_receive_bytes_total).

When I enabled hostNetwork, the Node Exporter exposed port 9100 on the host's network interface, which is a security risk as it allows unauthorized access to the metrics from outside the cluster.

### What you expected to happen?

Access the host's network interfaces to collect accurate network metrics.
Avoid exposing port 9100 on the host's network interface.

### How to reproduce it?

```
fullnameOverride: prometheus


alertmanager:
  enabled: false
  # fullnameOverride: alertmanager


grafana:
  fullnameOverride: grafana
  defaultDashboardsTimezone: Europe/Paris

  persistence:
    enabled: true
    storageClassName: "ceph-block"
    accessModes:
      - ReadWriteOnce
    size: 20Gi


kube-state-metrics:
  fullnameOverride: kube-state-metrics


nodeExporter:
  operatingSystems:
    aix:
      enabled: false
    darwin:
      enabled: false


prometheus-node-exporter:
  fullnameOverride: node-exporter
  # hostNetwork: false  # With this setting, nodes doesn't expose metrics on port 9100

          
prometheus:
  prometheusSpec:
    retention: 30d
    scrapeInterval: 1s

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "ceph-block"
          accessModes: 
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi

    additionalScrapeConfigs:      
      - job_name: gpu-metrics
        scrape_interval: 1s
        metrics_path: /metrics
        scheme: http
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - gpu-operator
        relabel_configs:
          - source_labels: [__meta_kubernetes_endpoint_node_name]
            action: replace
            target_label: hostname

      - job_name: node-exporter
        scrape_interval: 1s
        metrics_path: /metrics
        scheme: http
        relabel_configs:
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            regex: http-metrics
            action: keep
          - source_labels: [__meta_kubernetes_endpoint_node_name]
            action: replace
            target_label: hostname
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              own_namespace: false
              names:
              - monitoring
```

### Enter the changed values of values.yaml?

hostNetwork: false

### Enter the command that you execute and failing/misfunctioning.

-

### Anything else we need to know?

-
