### ISSUE TITLE
Grafana hostpath persistence not working 

### ISSUE THREAD

**Issue by 201508876PMH** [prometheus-community/helm-charts#5166]
### Describe the bug a clear and concise description of what the bug is.

Hi guys, even with my pods running i cant seem to persist grafana via hostpath. This is my current grafana config:

```
   grafana:
      deploymentStrategy:
        type: Recreate
      enabled: true
      fullnameOverride: grafana
      forceDeployDatasources: false
      forceDeployDashboards: false
      defaultDashboardsEnabled: true
      defaultDashboardsTimezone: utc+1
      serviceMonitor:
        enabled: true
      admin:
        existingSecret: grafana-admin-credentials
        userKey: admin-user
        passwordKey: admin-password
      persistence:
        disableMountSubPath: true
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 10Gi
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
        volumes:
          - name: grafana-storage
            hostPath:
              path: /mnt/volume-hel1-1/grafana
              type: DirectoryOrCreate
```

### What's your helm version?

v3.16.4

### What's your kubectl version?

v1.32.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

67.4.0

### What happened?

hostpath isnt working. No folder is created

### What you expected to happen?

Data is saved

### How to reproduce it?

use my code

### Enter the command that you execute and failing/misfunctioning.

?
