### ISSUE TITLE
[prometheus-mysql-exporter] How do I provide SSL to MySQL connection

### ISSUE THREAD

**Issue by deem1978** [prometheus-community/helm-charts#5176]
Hello, 
the issue is related to https://github.com/prometheus-community/helm-charts/issues/491. The problem is that the link provided point to 
```
# Extra Volume Mounts for the mysql exporter container
extraVolumeMounts: []
# - name: example
#   mountPath: /example
```
Could someone provide some explanation about how use SSL (or set the skip-verify flag) in values.yaml?
Thanks a lot to anyone wo will have a look into it.

**Comment by zeritti** [comment]
If you wish to disable certificate verification, you can use `config.extraArgs` like this ([General Flags](https://github.com/prometheus/mysqld_exporter#general-flags)):

```yaml
config:
  extraArgs:
    - "--tls.insecure-skip-verify"
```

Better still, having the server's CA certificate, you should be able, for example, to
- put the CA certificate in a configmap under key `ca.crt`
- set  

```yaml
mysql:
  additionalConfig:
    - "ssl-ca=/tls/private/ca.crt"
```
- use `extraVolumes` and `extraVolumeMounts` for the configmap so that the key's value can get mounted at `/tls/private/ca.crt`, e.g.

```yaml
extraVolumes:
  - name: mysqlca
    configMap:
      name: mysqlca
extraVolumeMounts:
  - name: mysqlca
    mountPath: /tls/private
    readOnly: true
```
