### ISSUE TITLE
[kube-promethues-stack] Some metrics not founnd in grafana

### ISSUE THREAD

**Issue by hamadodene** [prometheus-community/helm-charts#5180]
### Describe the bug a clear and concise description of what the bug is.

I deployed kube-prometheus from scratch, but I'm not seeing the metrics I would expect to see on Grafana. This is my `values.yaml`.

```
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus
  namespace: kube-prometheus-stack
  chart: prometheus-community/kube-prometheus-stack
  version: 68.1.0
  installed: true
  createNamespace: true
  disableValidation: true
  values:
    - values.yaml.gotmpl
    
```
```
fullnameOverride: "kube-prometheus"
alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true

prometheus-node-exporter:
  service:
    port: 9500
    targetPort: 9500

prometheusOperator:
  kubeletService:
    enabled: false

grafana:
  ingress:
    enabled: true
    hosts:
      - {{ requiredEnv "GRAFANA_HOST" }}
    ingressClassName: {{ requiredEnv "INGRESS_CLASS" | quote }}
  persistence:
    enabled: true
    storageClassName: {{ env "DEFAULT_STORAGE_CLASS"  | default "default-storageclass" }}
  adminUser: admin
  adminPassword: {{ requiredEnv "GRAFANA_ADMIN_PASSWORD" }}

prometheus:
  serviceMonitor:
    relabelings:
      - targetLabel: cluster
        replacement: {{ requiredEnv "CLUSTER_NAME" | quote }}
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prom
        spec:
          storageClassName: {{ env "DEFAULT_STORAGE_CLASS"  | default "default-storageclass" }}
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
```

In grafana some metrics are empty:

![image](https://github.com/user-attachments/assets/7a4de189-4c32-4d84-9601-387594d98990)

But in argocd namespace there a are pods:

 ```
get pods -n argocd
NAME                                               READY   STATUS    RESTARTS   AGE
argocd-application-controller-0                    1/1     Running   0          38h
argocd-applicationset-controller-6bccc7694-d2tfc   1/1     Running   0          38h
argocd-applicationset-controller-6bccc7694-hqvd2   1/1     Running   0          38h
argocd-dex-server-bb4584845-25hwn                  1/1     Running   0          38h
argocd-notifications-controller-6466f686d8-r2bhc   1/1     Running   0          38h
argocd-redis-ha-haproxy-7ff779566b-8vpvs           1/1     Running   0          38h
argocd-redis-ha-haproxy-7ff779566b-9bhk7           1/1     Running   0          38h
argocd-redis-ha-haproxy-7ff779566b-nfgq2           1/1     Running   0          38h
argocd-redis-ha-server-0                           3/3     Running   0          38h
argocd-redis-ha-server-1                           3/3     Running   0          38h
argocd-repo-server-58cc5b7799-c969f                2/2     Running   0          38h
argocd-repo-server-58cc5b7799-svg9b                2/2     Running   0          38h
argocd-server-784454f894-5d66l                     1/1     Running   0          38h
argocd-server-784454f894-zxcz8                     1/1     Running   0          38h

```

### What's your helm version?

v3.16.4

### What's your kubectl version?

v1.32.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

68.1.0

### Enter the command that you execute and failing/misfunctioning.

The installation is made using helmfile
