### ISSUE TITLE
[kube-prometheus-stack] allow custom annotations on prometheus rules

### ISSUE THREAD

**Issue by polak785** [prometheus-community/helm-charts#5192]
### Is your feature request related to a problem ?

In the values, `customRules` only support to override parameters `for` and `severity`, but not `annotations`.

### Describe the solution you'd like.

I want to be able to add annotations in order to declare links that will be in the Alertmanager notifications.

Exemple:
```
  NodeFilesystemSpaceFillingUp:
    severity: "error"
    annotations:
      dashboard: <web_link>
```

### Describe alternatives you've considered.

NONE
