### ISSUE TITLE
[kube-prometheus-stack] Unable to configure oauth2 for the default created alertmanager endpoint config.

### ISSUE THREAD

**Issue by d4rkfella** [prometheus-community/helm-charts#5197]
### Describe the bug a clear and concise description of what the bug is.

Hello, i've been banging my head for 2 hours straight and im unable to configure oauth for authenticating to alertmanager. The alertingEndpoints doesnt follow the official documentation and its really confusing . For example tlsConfig is translated to tls_config when the configuration file is rendered. These are some of the values i tried but none of them worked. 

```
alertingEndpoints:
          - scheme: https
            name: alertmanager-operated
            port: 8081
            tlsConfig:
              serverName: <servername>
            oauth2:
              clientId:
                secret:
                  name:  prometheus-oauth2-credentials
                  key: client_id
              clientSecret:
                name: prometheus-oauth2-credentials
                key: client_secret
              tokenUrl: <token_url>
              scopes: ["openid", "profile", "email"]
              endpointParams:
                grant_type: client_credentials


alertingEndpoints:
          - scheme: https
            name: alertmanager-operated
            port: 8081
            tlsConfig:
              serverName: <servername>
            oauth2:
              client_id: <client_id>
              client_secret_file: /vault/secrets/client_secret
              token_url: <token_url>
              scopes: ["openid", "profile", "email"]
              endpoint_params:
                grant_type: client_credentials
```
### What's your helm version?

v3.17.0

### What's your kubectl version?

v1.32.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

68.2.0

### Enter the command that you execute and failing/misfunctioning.

.
