### ISSUE TITLE
[prometheus-kube-stack] 12.8.1 probably has a bug

### ISSUE THREAD

**Issue by jjangga0214** [prometheus-community/helm-charts#521]
**Describe the bug**
With 12.8.1, an error occurs.
With 12.8.0, everything works fine, with the exact same setting and environment.
Currently, I don't know why, but it happens.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-23T02:22:53Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: prometheus-kube-stack

**Which version of the chart**: 12.8.1

**What happened**:

```shell
➜  capa-viewer git:(ops/tracing) (☸ |kind-kind:operations) kubectl get pod
NAME                                           READY   STATUS             RESTARTS   AGE
kube-prometheus-stack-admission-create-xt6ln   0/1     Completed          0          9m36s
```

```shell
➜  capa-viewer git:(ops/tracing) (☸ |kind-kind:operations) kubectl log kube-prometheus-stack-admission-create-xt6ln                                   
W1226 13:27:22.238438       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"err":"secrets \"kube-prometheus-stack-admission\" not found","level":"info","msg":"no secret found","source":"k8s/k8s.go:106","time":"2020-12-26T13:27:22Z"}
{"level":"info","msg":"creating new secret","source":"cmd/create.go:23","time":"2020-12-26T13:27:22Z"}
```
**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

```shell
$ kind create cluster
$ helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack
```

**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```yaml
alertmanager: # Though I haven't found the reason, alertmanager does not work with prometheus-msteams with this configuration (Of course prometheus-msteams is configured properly, but not shown here).
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: [critical, warning, job]
      group_interval: 30s
      repeat_interval: 30s
      group_wait: 30s
      routes:
        - receiver: prometheus-msteams-critical
          match:
            severity: critical
        - receiver: prometheus-msteams-warning
          match:
            severity: warning
        - receiver: prometheus-msteams-info
          match:
            alertname: Watchdog
    receivers:
      - name: prometheus-msteams-critical
        webhook_configs: # https://prometheus.io/docs/alerting/configuration/#webhook_config
          - send_resolved: true
            url: http://prometheus-msteams:2000/critical # the prometheus-msteams proxy
      - name: prometheus-msteams-warning
        webhook_configs: # https://prometheus.io/docs/alerting/configuration/#webhook_config
          - send_resolved: true
            url: http://prometheus-msteams:2000/warning # the prometheus-msteams proxy
      - name: prometheus-msteams-info
        webhook_configs: # https://prometheus.io/docs/alerting/configuration/#webhook_config
          - send_resolved: true
            url: http://prometheus-msteams:2000/info # the prometheus-msteams proxy
grafana:
  adminUser: ateamventures
  persistence:
    enabled: true
  # DO NOT configure "datasources" directly, as kube-prometheus-stack preconfigures it.
  # Instead, configure "additionalDataSources".
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-stack:3100
      access: proxy
      # prometheus would be the 'default' datasources,
      # so `isDefault` for other datasources should be `false`.
      isDefault: false
      version: 1
prometheus:
  prometheusSpec:
    externalLabels:
      # Thanos uses it, for example.
      replica: 84eaee6c-2374-4cdc-9eb9-ae417da0d4eb
    serviceMonitorSelector:
      matchLabels:
        release: prometheus
    # REF: https://github.com/prometheus-community/helm-charts/blob/1b967eed322a618f7007725e48496c9f16120e24/charts/kube-prometheus-stack/values.yaml#L2003
    ## AdditionalScrapeConfigs allows specifying additional Prometheus scrape configurations. Scrape configurations
    ## are appended to the configurations generated by the Prometheus Operator. Job configurations must have the form
    ## as specified in the official Prometheus documentation:
    ## https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config. As scrape configs are
    ## appended, the user is responsible to make sure it is valid. Note that using this feature may expose the possibility
    ## to break upgrades of Prometheus. It is advised to review Prometheus release notes to ensure that no incompatible
    ## scrape configs are going to break Prometheus after the upgrade.
    additionalScrapeConfigs:
      # Federate the Prometheus in Linkerd Control Plane
      # REF: https://linkerd.io/2/tasks/exporting-metrics/
      - job_name: 'linkerd'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['linkerd']
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_container_name
            action: keep
            regex: ^prometheus$
        honor_labels: true
        metrics_path: '/federate'
        params:
          'match[]':
            - '{job="linkerd-proxy"}'
            - '{job="linkerd-controller"}'
```
