### ISSUE TITLE
[kube-prometheus-stack] Add support message_thread_id on AlertManager

### ISSUE THREAD

**Issue by xahys** [prometheus-community/helm-charts#5219]
### Is your feature request related to a problem ?

After upgrade Alertmanager to 0.28 you can use topics to send alerts in Telegram (if use Alertmanager as single from https://github.com/prometheus/alertmanager).
Can anyone upgrade crd on Alertmanager?

Now it's little broken. If add message_thread_id:
```
      telegram_configs:
        - chat_id: -123456
          message_thread_id: 4
          bot_token: '111111:11111_11111'
          api_url: "https://api.telegram.org"
          send_resolved: true
          parse_mode: HTML
```

Getting error like
```
      message: >-
        provision alertmanager configuration: failed to initialize from secret:
        yaml: unmarshal errors:
          line 35: field message_thread_id not found in type config.plain

```

### Describe the solution you'd like.

I think need add new param (message_thread_id) in config pattern in spec CRD
I would like to help somehow better, but I haven't figured out how

### Describe alternatives you've considered.

Idk

**Comment by zeritti** [comment]
Your configuration above should work in a receiver with Prometheus operator in this form[1]:

```yaml
telegramConfigs:
  - chatID: -123456
    messageThreadID: 4
    botToken: '111111:11111_11111'
    apiUrl: "https://api.telegram.org"
    sendResolved: true
    parseMode: HTML
```

The main requirement is that Prometheus operator and its CRDs must be at version [0.79.0](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.79.0) or newer and  alertmanager 0.26 or newer.

[1] https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1alpha1.TelegramConfig
