### ISSUE TITLE
[kube-prometheus-stack] - no default dashboard or data source

### ISSUE THREAD

**Issue by fjellvannet** [prometheus-community/helm-charts#5232]
### Describe the bug a clear and concise description of what the bug is.

I installed kube-prometheus-stack into the monitoring-namespace in my bare-metal kubeadm-cluster.

However, when I log into grafana, there are no dashboards visible, and prometheus also does not appear as the default datasource.

### What's your helm version?

version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}

### What's your kubectl version?

Client Version: v1.32.1 Kustomize Version: v5.5.0 Server Version: v1.32.1

### Which chart?

prometheus-community/kube-prometheus-stack

### What's the chart version?

68.3.0

### What happened?

I tried to install the kube-prometheus-stack using the following command: 
`helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitoring --create-namespace`

All the pods / services etc are deployed properly, and I can log into grafana using a port-forward or ingress.

However - there are no dashboards in grafana, and also there is no datasource (prometheus is not automatically added).

### What you expected to happen?

I would expect the default dashboards for the different kubernetes components like etcd etc. to be visible and populated with data. Instead, Grafana appears like a clean instance with nothing configured.

### How to reproduce it?

Set up a bare-metal kubeadm cluster on ubuntu nodes, I now have 3 workers and 3 masters. For block- and other persistent storage, rook-ceph is configured on the worker nodes. Additionally, serverTLSBootstrap is enabled in the kubelets as described [here](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#kubelet-serving-certs) for metrics-server to work. Cert-manager is also running in the cluster. Other than that it is pretty bare-metal, and I have no clue why I don't see this data.

### Enter the changed values of values.yaml?

NONE

I tried enabling persistent storage for grafana, enabled an ingress for grafana, set the url of the prometheus-datasource in grafana to this value: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/, but it all made no difference. I see no dashboards and no datasource, even though they are all true in the values. While testing I have also not only helm upgraded, but also helm uninstall and then again helm install to be sure that everything is reconfigured. 

I purposely created the issue with NONE as the modified values, because I think it would make sense have the default values work more or less out of the box.

### Enter the command that you execute and failing/misfunctioning.

`helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitoring --create-namespace`

### Anything else we need to know?

I have tried to follow the different hints I found in the related issues https://github.com/prometheus-community/helm-charts/issues/873 and https://github.com/prometheus-community/helm-charts/issues/3800. See changed values of values.yaml to see what I tried to modify. As both of these issues were old and opened and closed multiple times, I decided to open a new clean issue to get this fixed.

**Comment by chris8205** [comment]
Same issue...
also recognized that default DataSources --> Prometheus and Alermanager not registred properly...
Also Prune not helping...

also "version: x" not added in default "datasources.yaml"


# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    prune: true
    datasources:
    - name: "Prometheus"
      type: prometheus
      uid: prometheus
      url: http://observability-prometheus.<mynamespace>:9090/
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 1m
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: xxxxxxxxxxxxxxx
    meta.helm.sh/release-namespace: xxxxxxxxxxxxxxxx
  creationTimestamp: "2025-01-27T10:46:16Z"
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/instance: xxxxxxxxxxxxxxxx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 68.1.1
    chart: kube-prometheus-stack-68.1.1
    grafana_datasource: "1"
    heritage: Helm
    release: xxxxxxxxxxxxxxxxxx
  name: observability-grafana-datasource
  namespace: xxxxxxxxxxxxxxxx
  resourceVersion: "xxxxxxxxxxx"
  uid: xxxxxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxxxx

**Comment by audiophonicz** [comment]
Same issue...
I just went to install a clean install of kube-prometheus-stack 70.4.1 from 4/1/25 and everything seems to be running properly except I have no dashboards or datasources in grafana. I also have added persistent storage to both prometheus and grafana.

3master x 6worker NUC cluster with K3s 1.30.6 on Debian 12.7 Kernel 6.10
Helm v3.11.2

**Comment by vdveldet** [comment]
Same here with 73.2.3, currently the latest

**Comment by slapcat** [comment]
I'm also getting this issue on 75.8.0, currently the latest

**Comment by chris8205** [comment]
Hi,

don't know if its the same...
but if you set / override the default password for the Dashboard with

```
kube-prometheus-stack:
  grafana:
    env:
      GF_SECURITY_ADMIN_USER=<myUser>
      GF_SECURITY_ADMIN_PASSWORD=<myPass>
```

you need to set also the SideCar User and Pass:

```
kube-prometheus-stack:
  grafana:
    sidecar:
      dashboards:
        env:
          REQ_USERNAME=<myUser>
          REQ_PASSWORD=<myPass>
      datasources:
        env:
          REQ_USERNAME=<myUser>
          REQ_PASSWORD=<myPass>
```

**Comment by abasu0713** [comment]
any update here? Latest versions don't have any datasource or dashboards..

**Comment by dilsontome** [comment]
Guys, anyone get datasources and default dashboards working?

**Comment by obarbier** [comment]
@dilsontome  not sure if i am answering the question you are asking. But ran into similar issue and stubble on this thread. The quick fix was to create the data source manually. Using the Web UI. However there must be a way to force configure it using the helm charts.  I will continue investigating and come back here if found anything.

**Comment by abasu0713** [comment]
> Guys, anyone get datasources and default dashboards working?

Nope. So i went to kube-prometheus bitnami chart. That doesn't come bundled with grafana. I just used the bitnami grafana chart and added all the data sources. As for dashboards I just imported them. Let me know and I can share my terraform source.

**Comment by confy** [comment]
I updated to v77.11.0 yesterday and my default dashboards have disappeared! Anyone with the same?

**Comment by abasu0713** [comment]
> I updated to v77.11.0 yesterday and my default dashboards have disappeared! Anyone with the same?

Yep. I saw this issue from v75 onwards. None of the data source mappings work either. Hence I moved to Bitnami kube prometheus. Much better. Requires the additional setup for Grafana chart. But that keeps things simpler

**Comment by confy** [comment]
> > I updated to v77.11.0 yesterday and my default dashboards have disappeared! Anyone with the same?
> 
> Yep. I saw this issue from v75 onwards. None of the data source mappings work either. Hence I moved to Bitnami kube prometheus. Much better. Requires the additional setup for Grafana chart. But that keeps things simpler

I dunno if that's the answer for me considering Bitnami's behaviour, good to know I'm not the only one with the issue though.

**Comment by abasu0713** [comment]
> > > I updated to v77.11.0 yesterday and my default dashboards have disappeared! Anyone with the same?
> > 
> > 
> > Yep. I saw this issue from v75 onwards. None of the data source mappings work either. Hence I moved to Bitnami kube prometheus. Much better. Requires the additional setup for Grafana chart. But that keeps things simpler
> 
> I dunno if that's the answer for me considering Bitnami's behaviour, good to know I'm not the only one with the issue though.

What do you mean Bitnami's behavior? 
If you do wanna give it a try here's some code reference:

`kube-prometheus.tf`:
```terraform 
resource "helm_release" "kube_prometheus" {
  depends_on = [
    helm_release.loki,
    helm_release.mimir,
  ]
  chart       = "kube-prometheus"
  name        = "observability"
  namespace   = data.kubernetes_namespace.observability.metadata[0].name
  repository  = "oci://registry-1.docker.io/bitnamicharts"
  description = "Terraform managed helm deployment for kube-prometheus-stack"
  version     = "11.3.9"
  set = [
    {
      name  = "alertmanager.config.global.smtp_auth_password",
      value = var.smtp.password
    }
  ]
  values = [
    <<-EOT
    namespaceOverride: ${data.kubernetes_namespace.observability.metadata[0].name}
    prometheus:
      defaultRules:
        rules:
          kubeProxy: false
          kubeControllerManager: false
          kubeSchedulerAlerting: false
          kubeSchedulerRecording: false
          etcd: false
          kubeApiserverAvailability: false
          kubeApiserverBurnrate: false
          kubeApiserverHistogram: false
          kubeApiserverSlos: false
      scrapeInterval: 1m
      persistence:
        enabled: true
        storageClass: null
        size: 10Gi
      resourcesPreset: large
      retention: 3d
      retentionSize: 8GB
      walCompression: true
      remoteWrite:
      - url: http://mimir-grafana-mimir-gateway.observability.svc.cluster.local/api/v1/push
        remoteTimeout: 60s 
        queueConfig:
          capacity: 10000
          maxShards: 20      
          minShards: 4
          maxSamplesPerSend: 2000  
          batchSendDeadline: 30s    
          minBackoff: 200ms
          maxBackoff: 20s
        metadataConfig:
          sendInterval: 1m
          maxSamplesPerSend: 500
        writeRelabelConfigs:
          - sourceLabels: [__name__]
            regex: "apiserver_request_duration_seconds_bucket|etcd_request_duration_seconds_bucket|apiserver_request_sli_duration_seconds_bucket|apiserver_request_body_size_bytes_bucket|apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket|workqueue_work_duration_seconds_bucket|workqueue_queue_duration_seconds_bucket|storage_operation_duration_seconds_bucket"
            action: drop

          - sourceLabels: [__name__]
            regex: "container_tasks_state|container_threads|container_fs_.*|container_blkio_.*|container_network_.*"
            action: drop

          # Drop kube_job metrics
          - sourceLabels: [job]
            regex: "kube_job.*"
            action: drop

          - sourceLabels: [job]
            regex: "coredns|kube-proxy|metrics-server"
            action: drop
    
          - action: labeldrop
            regex: "boot_id|machine_id|system_uuid|job|uid"

          - sourceLabels: [__name__]
            regex: ".*_bucket"
            action: drop
    kubeProxy:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeControllerManager:
      enabled: false
    alertmanager:
      config:
        global:
          resolve_timeout: 5m
          smtp_from: <redacted>
          smtp_smarthost: <redacted>
          smtp_hello: <redacted>
          smtp_auth_username: <redacted>
        route:
          receiver: 'email-alert'
          routes:
            - match:
                alertname: Watchdog
              receiver: 'email-alert'
        receivers:
          - name: 'email-alert'
            email_configs:
              - to: <redacted>
                send_resolved: true
      persistence:
        enabled: true
        storageClass: null
        size: 4Gi
    blackboxExporter:
      enabled: false
    EOT
  ]
}
```

`mimir.tf`
```terraform
resource "helm_release" "mimir" {
  chart       = "grafana-mimir"
  name        = "mimir"
  namespace   = data.kubernetes_namespace.observability.metadata[0].name
  repository  = "oci://registry-1.docker.io/bitnamicharts"
  description = "Terraform managed helm deployment for Grafana Mimir"
  version     = "3.0.17"
  timeout = 480

  values = [
    <<-EOT
    mimir:
      blockStorage:
        backend: s3
        config: |
          access_key_id: $${S3_ACCESS_KEY_ID}
          secret_access_key: $${S3_SECRET_ACCESS_KEY}
          region: default
          bucket_name: ${data.kubernetes_config_map_v1.mimir_bucket_claim.data["BUCKET_NAME"]}
          endpoint: ${data.kubernetes_config_map_v1.mimir_bucket_claim.data["BUCKET_HOST"]}:${data.kubernetes_config_map_v1.mimir_bucket_claim.data["BUCKET_PORT"]}
          insecure: true
      overrideConfiguration:
        query_scheduler:
          max_outstanding_requests_per_tenant: 5000
        frontend:
          max_outstanding_per_tenant: 5000
        limits:
          max_global_series_per_user: 700000
          ingestion_rate: 20000
          ingestion_burst_size: 40000
          out_of_order_time_window: 5m
    storeGateway:
      extraEnvVars:
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mimir-bucket
              key: AWS_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mimir-bucket
              key: AWS_SECRET_ACCESS_KEY
    ingester:
      resourcesPreset: large
      replicaCount: 2
      extraEnvVars:
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mimir-bucket
              key: AWS_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mimir-bucket
              key: AWS_SECRET_ACCESS_KEY
    compactor:
      extraEnvVars:
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mimir-bucket
              key: AWS_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mimir-bucket
              key: AWS_SECRET_ACCESS_KEY
    querier:
      extraEnvVars:
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mimir-bucket
              key: AWS_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mimir-bucket
              key: AWS_SECRET_ACCESS_KEY
    queryFrontend:
      extraEnvVars:
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mimir-bucket
              key: AWS_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mimir-bucket
              key: AWS_SECRET_ACCESS_KEY
    distributor:
      resourcesPreset: medium
    minio: 
      enabled: false
    EOT
  ]
}
```

```terraform
resource "helm_release" "grafana" {
  name        = "grafana"
  repository  = "https://grafana.github.io/helm-charts"
  chart       = "grafana"
  description = "Terraform managed helm deployment for Grafana Dashboards"
  version     = "9.4.2"
  namespace   = data.kubernetes_namespace.observability.metadata[0].name

  values = [
    yamlencode({
      adminUser     = var.grafana_admin_user
      adminPassword = var.grafana_admin_password

      service = { type = "ClusterIP" }
      smtp = {
        existingSecret = kubernetes_secret.grafana_smtp.metadata[0].name
        userKey        = "user"
        passwordKey    = "password"
      }

      datasources = {
        "datasources.yaml" = {
          apiVersion = 1
          datasources = [
            {
              name      = "Mimir"
              isDefault = true
              uid       = "mimir"
              type      = "prometheus"
              access    = "proxy"
              url       = "http://mimir-grafana-mimir-gateway:80/prometheus"
              jsonData = {
                httpMethod     = "POST"
                prometheusType = "Mimir"
                tlsSkipVerify  = true
                timeout        = "30s"
              }
            },
            {
              name      = "Loki"
              type      = "loki"
              uid       = "Loki"
              url       = "http://loki-gateway:80"
              access    = "proxy"
              isDefault = false
              jsonData = {
                httpMethod = "GET"
                maxLines   = 1000
              }
            },
            {
              name      = "AlertManager"
              isDefault = false
              uid       = "alertmanager"
              type      = "alertmanager"
              access    = "server"
              url       = "http://observability-kube-prometh-alertmanager:9093"
              jsonData = {
                tlsSkipVerify  = true
                implementation = "prometheus"
              }
            },
          ]
        }
      }
      notifiers = {
        "notifiers.yaml" = {
          notifiers = [
            {
              name      = "grafana_primary_email"
              type      = "email"
              uid       = "grafana_primary_email"
              isDefault = true
              org_id    = 1
              settings = {
                addresses   = var.smtp.from_address
                singleEmail = true
              }
            }
          ]
        }
      }
      alerting = {
        "policies.yaml" = {
          policies = [
            {
              orgId    = 1
              receiver = "grafana_primary_email"
            }
          ]
        }
        "contactPoints.yaml" = {
          secret = {
            contactPoints = [
              {
                orgId = 1
                name  = "grafana_primary_email"
                receivers = [
                  {
                    type = "email"
                    uid  = "grafana_primary_email"
                    name = "grafana_primary_email"
                    settings = {
                      addresses   = var.smtp.from_address
                      singleEmail = true
                    }
                  }
                ]
              }
            ]
          }
        }
      }
      persistence = {
        enabled          = true
        size             = "8Gi"
        storageClassName = "ceph-rbd"
        accessModes      = ["ReadWriteOnce"]
        type             = "pvc"
      }
      "grafana.ini" = {
        "unified_alerting" = { enabled = true }
        "smtp" = {
          enabled      = true
          host         = <redacted>
          from_address = var.smtp.from_address
          from_name    = "Grafana"
          passwordKey  = "password"
          userKey      = "user"
        }
      }
    })
  ]

  depends_on = [
    helm_release.kube_prometheus,
    helm_release.loki,
    helm_release.mimir
  ]
}
```
> PS: I use ceph orchestrated S3 buckets.. so the object store is within my network.

**Comment by confy** [comment]
> 
> What do you mean Bitnami's behavior? If you do wanna give it a try here's some code reference:
> 
Bitnami is moving images and charts to private repos for paying customers only, images will not be recieving updates starting in 3 days

https://github.com/bitnami/charts/issues/35164

**Comment by avakarev** [comment]
@confy, @abasu0713, @dilsontome, @vdveldet, @audiophonicz, @chris8205, @fjellvannet

`kube-prometheus-stack` still does generates dashboard and data-source resources, but doesn't mount them into the grafana instance. There is an `grafana-operator` that does it, check some more details in this issue: https://github.com/prometheus-community/helm-charts/issues/5822. Read the docs of what `grafana-operator` is and how it manages data-sources and dashboard resources: https://grafana.com/docs/grafana-cloud/developer-resources/infrastructure-as-code/grafana-operator/

Here is step-by-step guide for fresh installed.

1. `kube-prometheus-stack` 77.14.0 is installed into `observability` namespace.
2. Ensure it brings prometheus CRDs:
```yaml
# helmfile.yaml.gotmpl
releases:
  - name: prometheus-operator
    namespace: observability
    chart: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
    version: 77.14.0
    values:
      - crds:
          upgradeJob:
            enabled: true
```
3. Ensure grafana and prometheus instances are enableld, up and running.
4. Add `Grafana` and `GrafanaDatasource` resources:
```bash
cat charts/observability/kube-prometheus-stack/hack.yaml
```
```yaml
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  external:
    url: http://prometheus-operator-grafana
    adminUser:
      name: prometheus-operator-grafana
      key: admin-user
    adminPassword:
      name: prometheus-operator-grafana
      key: admin-password
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      app: grafana
  datasource:
    name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus-operator-kube-p-prometheus:9090/
    access: proxy
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 30s
      # tlsSkipVerify: true
    editable: false
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  instanceSelector:
    matchLabels:
      app: grafana
  datasource:
    name: Alertmanager
    type: alertmanager
    uid: alertmanager
    url: http://prometheus-operator-kube-p-alertmanager:9093/
    access: proxy
    jsonData:
      handleGrafanaManagedAlerts: false
      implementation: prometheus
      # tlsSkipVerify: true
    editable: false
```
```bash
kubectl apply --namespace observability -f charts/observability/kube-prometheus-stack/hack.yaml
```
5. Install `grafana-operator` into same namespace as `kube-prometheus-stack`, ensure it brings grafana CRDs
```yaml
# helmfile.yaml.gotmpl
releases:
  - name: grafana-operator
    namespace: observability
    chart: oci://ghcr.io/grafana/helm-charts/grafana-operator
    version: v5.19.4
    values:
      - crds:
          immutable: false
      - namespaceScope: true
      - rbac:
          create: false
      - serviceAccount:
          create: false
```
6. Enable mapping of dashboard config-maps into GrafanaDashboard resources
```yaml
# helmfile.yaml.gotmpl
releases:
  - name: prometheus-operator
     values:
       - grafana:
            operator:
               dashboardsConfigMapRefEnabled: true
               matchLabels:
                  app: grafana
```
7. At this point grafana instance should have both valid data-sources and all dashboards managed by `kube-prometheus-stack`.

**Comment by ahordez** [comment]
Today I did a fresh installation of kube-prometheus-stack 78.4.0.
After installation, I had the same issue as you: no datasource, no dashboards, no alert rules.
However, the datasource appeared automatically (without any action on my part) after about 5 minutes, along with the alert rules.
Then, the dashboards appeared automatically after about 10 minutes.
It therefore seems that there is an asynchronous mechanism in the chart for this configuration, which takes between 5 and 10 minutes after the chart installation.

**Comment by channaneq** [comment]
Also seeing this issue on v77.5.0. Wondering if related to the following logs from the grafana-sc-dashboards container

```
{"time": "2025-10-30T10:58:14.949803+00:00", "level": "WARNING", "msg": "Retrying (Retry(total=1, connect=10, read=5, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Missing Authority Key Identifier (_ssl.c:1032)'))': /api/v1/namespaces/kube-system/configmaps?labelSelector=grafana_dashboard%3D1&timeoutSeconds=60&watch=True"}
```

**Comment by imroc** [comment]
> Also seeing this issue on v77.5.0. Wondering if related to the following logs from the grafana-sc-dashboards container
> 
> ```
> {"time": "2025-10-30T10:58:14.949803+00:00", "level": "WARNING", "msg": "Retrying (Retry(total=1, connect=10, read=5, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Missing Authority Key Identifier (_ssl.c:1032)'))': /api/v1/namespaces/kube-system/configmaps?labelSelector=grafana_dashboard%3D1&timeoutSeconds=60&watch=True"}
> ```

Same in current latest v79.5.0, still no dashboards and datasources in grafana, sidecar has WARNING logs:

```json
{"time": "2025-11-19T12:20:10.684850+00:00", "level": "WARNING", "msg": "Retrying (Retry(total=1, connect=10, read=5, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Missing Authority Key Identifier (_ssl.c:1032)'))': /api/v1/configmaps?labelSelector=grafana_dashboard%3D1&timeoutSeconds=60&watch=True"}
```

**Comment by navera-mb** [comment]
Is there any update here? I Installed v79.5.0 and no dashboard. I waited almost 15mins if dashboards reappears but unfortunately, nothing come.

**Comment by channaneq** [comment]
We opened a support case with AWS who informed us that the above error `Missing Authority Key Identifier` is a known issue impacting older EKS clusters created around 2020. The X509v3 Authority Key Identifier extension was not included in the kube-apiserver certificates generated by those clusters.

As yet there is no fix, the following is from AWS. 

"Please also allow me to mention that EKS does not yet support CA rotation. EKS manages certificates for control plane components automatically and attempting manual rotation of the root CA can break cluster authentication. However, the good news is that our internal team is actively working on this feature request, which will enable customers to start using a newly generated Certificate Authority, which would include an SKI, and Kube API server certificates which will include an AKI extension."

To temporarily get around the issue I changed the version of the grafana sidecar image in our helm chart to v1.30.3 (last working image)

**Comment by dalehenries** [comment]
> We opened a support case with AWS who informed us that the above error `Missing Authority Key Identifier` is a known issue impacting older EKS clusters created around 2020. The X509v3 Authority Key Identifier extension was not included in the kube-apiserver certificates generated by those clusters.
> 
> As yet there is no fix, the following is from AWS.
> 
> "Please also allow me to mention that EKS does not yet support CA rotation. EKS manages certificates for control plane components automatically and attempting manual rotation of the root CA can break cluster authentication. However, the good news is that our internal team is actively working on this feature request, which will enable customers to start using a newly generated Certificate Authority, which would include an SKI, and Kube API server certificates which will include an AKI extension."
> 
> To temporarily get around the issue I changed the version of the grafana sidecar image in our helm chart to v1.30.3 (last working image)

It probably isn't the most secure option, but you can set `grafana.sidecar.skipTLSVerify = true` as a work around.  This fixed the issue for me:

```yaml
grafana:
  sidecar:
    skipTlsVerify: true
```

You can see this in the grafana helm chart for newer versions:
https://github.com/grafana/helm-charts/blob/3a633bf46cdd430065c83d6e9f1837325d0700d2/charts/grafana/values.yaml#L979

**Comment by guoard** [comment]
In my case, the issue affected only datasources, not dashboards.
Changing the `watchMethod` for datasources resolved the problem:

```
grafana:
  sidecar:
    datasources:
      watchMethod: "SLEEP"
```

For reference, this is related to the original answer here:
https://github.com/grafana/helm-charts/issues/4023#issuecomment-3633527427

**Comment by raphaelauv** [comment]
for a quick "fix"

in grafana go to `/connections/datasources/new` ( Add data source ) 

select prometheus

then enter the url -> `http://prometheus-kube-prometheus-prometheus.default.svc.cluster.local:9090`

then click on `save and test`

**Comment by yakobe** [comment]
For people hitting the "old EKS cluster" problem on AWS, here is an issue tracking it. 

https://github.com/aws/containers-roadmap/issues/2638

Give it a thumbs up to show them we need it.

**Comment by asaf400** [comment]
Same issue, for me the fix was simply to explicitly invoke a sync,
I renamed the label on the datasources configmap: `grafana_dashboard` --> `some_random_value` --> `grafana_dashboard`

This forces the sidecar which watches configmaps to pickup this change and create the dashboards :)

**Comment by julian-perge** [comment]
For anyone else who may be running into these issues:

After following @avakarev 's comment [here](https://github.com/prometheus-community/helm-charts/issues/5232#issuecomment-3382172029), I also had to set these values in the Grafana subchart.
- Skipping TLS verify causes a bunch of log spam from the sidecars about an insecure request being sent (AWS EKS 1.35).
- Disabling `auth.basic` causes a bunch of 401 errors from the sidecars, it HAS to be enabled.
- Disabling the initial admin creation also causes 401 errors.

```yaml
grafana:
  admin:
    existingSecret: grafana-admin-auth
  grafana.ini:
    auth.basic:
      enabled: true

  sidecar:
    dashboards:
      enabled: true
      env:
        LOG_FORMAT: json
        LOG_TZ: UTC
    datasources:
      enabled: true
      watchMethod: SLEEP
      env:
        LOG_FORMAT: json
        LOG_TZ: UTC
```

Updated Grafana CRDs (note: I have also set `cleanPrometheusOperatorObjectNames: true`, `fullnameOverride: metrics-stack`, and `grafana.fullnameOverride: grafana`)

```yaml
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  external:
    url: 'http://grafana.monitoring.svc.cluster.local:80'
    tenantNamespace: monitoring
    adminUser:
      name: grafana-admin-auth
      key: admin-user
    adminPassword:
      name: grafana-admin-auth
      key: admin-password
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
  namespace: monitoring
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      app: grafana
  uid: prometheus
  datasource:
    name: Prometheus
    type: prometheus
    access: proxy
    editable: false
    url: http://metrics-stack-prometheus.monitoring.svc.cluster.local:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 30s
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      app: grafana
  uid: alertmanager
  datasource:
    name: Alertmanager
    type: alertmanager
    access: proxy
    editable: false
    url: http://metrics-stack-alertmanager.monitoring.svc.cluster.local:9093/
    jsonData:
      handleGrafanaManagedAlerts: false
      implementation: prometheus
```
