### ISSUE TITLE
Adding a label to all metrics

### ISSUE THREAD

**Issue by aantn** [prometheus-community/helm-charts#5255]
What is the correct way to add a label like 'cluster=foo' to all metrics scraped by kube-prometheus-stack, including the builtin metrics and custom metrics that I scrape with ServiceMonitors?

**Comment by dlidstrom** [comment]
I am no expert but maybe you can use scrape configuration? Here’s how I have it:

```yaml
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: dotnet
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_language]
          regex: dotnet
          action: keep
        - source_labels: [__meta_kubernetes_endpoint_port_name]
          regex: http
          action: keep
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        metrics_path: /metrics
        scheme: http
```

I’ve added this to values.yaml. My config adds a label to my dotnet applications. It adds the job label:

`ocelot_downstream_requests_total{code="200", container="gateway", instance="10.1.76.191:8080", job="dotnet", method="GET", path="/api/v1/Team", pod="gateway-bbb6cd598-bvh67"} `

I suspect you can add other labels too.
See https://prometheus.io/docs/prometheus/latest/configuration/configuration/
