### ISSUE TITLE
[kube-prometheus-stack] Can not filter alerts by labels to be sent to reciver

### ISSUE THREAD

**Issue by abidaran** [prometheus-community/helm-charts#5263]
I am running Kube Prometheus stack in the k8s cluster and configured alertmanger to send alerts to alerta, the problem is that I want to send only critical alerts to alerta and however, I configure the matchers to severity=critical still the alertmanger sends warning alerts to alerta.
This is my configuration file:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alerta-config
  namespace: monitoring
spec:
  route:
    groupBy: ['alertname','severity','job','service']
    matchers:
     - name: severity
       value: critical
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: "alerta"
    continue: false
  receivers:
  - name: "alerta"
    webhookConfigs:
    - sendResolved: true
      url: 'http://alerta-web:80/api/webhooks/prometheus?api-key'
```
Any idea what's the problem is?

**Comment by b44rawat** [comment]
Hi @abidaran! Were you able to find a solution? If yes, it would be great if you could share it with us!

I reviewed the YAML you shared — it looks mostly good, but there’s one important parameter that seems to be missing: `matchType`.

According to the CRD definition ([reference link](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml#L10740)), the matchType field is required when defining matchers.

Here’s an updated version of your config with the fix:

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alerta-config
  namespace: monitoring
spec:
  route:
    groupBy: ['alertname','severity','job','service']
    matchers:
     - name: severity
       value: critical
       matchType: =               ## <----- this one
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: "alerta"
    continue: false
  receivers:
  - name: "alerta"
    webhookConfigs:
    - sendResolved: true
      url: 'http://alerta-web:80/api/webhooks/prometheus?api-key'
```

You can also check the Alertmanager UI to see if the alert is falling back to the null receiver or not being grouped correctly. If you're still facing issues, sharing the relevant log output could help diagnose further.

Hope this helps!
