### ISSUE TITLE
[kube-prometheus-stack] How to disable noisy alerts? <not a bug>

### ISSUE THREAD

**Issue by rwlove** [prometheus-community/helm-charts#5290]
### Describe the bug a clear and concise description of what the bug is.

How in the world do I disable an alert like this one? I've been playing with the below snippit in values.yaml, but I cannot figure it out.

```
    kubeApiServer:
      enabled: true
      endpoints: ["192.168.1.9", "192.168.4.9", "192.168.4.10"]
      serviceMonitor:
        metricRelabelings:
          # Drop high cardinality labels                                                                                                                                      
          - action: drop
            sourceLabels: ["__name__"]
            regex: (apiserver|etcd|rest_client)_request(|_sli|_slo)_duration_seconds_bucket
          - action: drop
            sourceLabels: ["__name__"]
            regex: (apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket|apiserver_request_total)
          - action: drop
            sourceLabels: ["__name__"]
            regex: code_verb:apiserver_request_total:increase1h[30d]
          - action: drop
            sourceLabels: ["__name__"]
            regex: '.*apiserver_request_total.*'
```

![Image](https://github.com/user-attachments/assets/d68cb4ec-1da6-4992-af6b-8e41f04ba96d)

### What's your helm version?

N/A

### What's your kubectl version?

1.31

### Which chart?

kube-promethues-stack

### What's the chart version?

69.0.0

### Enter the command that you execute and failing/misfunctioning.

N/A
