### ISSUE TITLE
[kube-prometheus-stack crds] Manifest generation error : Failed to unmarshal "clusterrole.yaml": <nil> while upgrading to v69.2.2

### ISSUE THREAD

**Issue by bluubean** [prometheus-community/helm-charts#5307]
### Describe the bug a clear and concise description of what the bug is.

Via Argocd, while upgrading crds from 67.11.0 to 69.2.2 I get the following error : 

```Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): rpc error: code = FailedPrecondition desc = Failed to unmarshal "clusterrole.yaml": <nil>```

### What's your helm version?

not relevant, using argocd version: v2.12.9

### What's your kubectl version?

Client Version: v1.31.3 Kustomize Version: v5.4.2 Server Version: v1.31.4-eks-2d5f260

### Which chart?

crds

### What's the chart version?

69.2.2

### How to reproduce it?

Upgrade crds from 67.11.0 to 69.2.2 with argocd

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

argocd sync with default values

### Anything else we need to know?

Before that last upgrade, I upgraded all the way from 57 to 67 without any issue.

I suspect there might be an issue in crds/templates/upgrade/clusterrole.yaml, specifically the namespace metadata which should not be needed. However I'm not sure if this would cause an unmarshalling error

**Comment by alaa-ledger** [comment]
(k8s noob here)

I'm getting this error on a completely fresh installation, any idea why that would happen? should I just use an older version? here's my helm chart (also using ArgoCD):

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack-crds
  namespace: argo-cd
spec:
  generators:
  - list:
      elements:
      - cluster: my-cluster
  template:
    metadata:
      name: '{{cluster}}-kube-prometheus-stack-crds'
    spec:
      project: k8s-services-common
      destination:
        name: '{{cluster}}'
        namespace: kube-prometheus-stack-crds
      source:
        repoURL: https://github.com/prometheus-community/helm-charts.git
        path: charts/kube-prometheus-stack/charts/crds/
        targetRevision: kube-prometheus-stack-70.2.1
        directory:
          recurse: true
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - Replace=true
        automated:
          prune: true
          selfHeal: true

```
