### ISSUE TITLE
[kube-prometheus-stack] Issues setting the node-exporter to use TLS

### ISSUE THREAD

**Issue by abpadan** [prometheus-community/helm-charts#5413]
### Describe the bug a clear and concise description of what the bug is.

The nodeExporter process is using the hostNetwork and there is a security vulnerability on port 9100. As such, I am trying to enable tls for the node-exporter. When upgrading or installing the kube-prometheus-stack, I am unable to set a custom configMap that points to where tls information is. 

The error I am receiving is that the file does not exist from the node-exporter pod logs.

`time=2025-03-11T20:39:19.160Z level=ERROR source=node_exporter.go:247 msg="open /etc/node-exporter/web-config.yaml: no such file or directory"`

The yaml specification for the configMap is here:

```
apiVersion: v1
data:
  web-config.yaml: |
    tls_server_config:
      cert_file: /etc/node-exporter/certs/tls.crt
      key_file: /etc/node-exporter/certs/tls.key
kind: ConfigMap
```

I have validated that the configMap gets created.

The helm values.yaml used at the install/upgrade has the following as it relates to the node-exporter.

```
nodeExporter:
  enabled: true

prometheus-node-exporter:
  enabled: true
  extraArgs:
    - "--web.config.file=/etc/node-exporter/web-config.yaml"
  volumes:
  - name: web-config
    configMap:
      name: node-exporter-web-config
  - name: tls-certs
    secret:
      secretName: node-exporter-tls
  - name: web-config
    configMap:
      name: node-exporter-web-config
  volumeMounts:
  - name: tls-secret
    mountPath: /etc/node-exporter/tls
    readOnly: true
  - name: web-config
    mountPath: /etc/node-exporter

```

### What's your helm version?

version.BuildInfo{Version:"v3.15.4", GitCommit:"fa9efb07d9d8debbb4306d72af76a383895aa8c4", GitTreeState:"clean", GoVersion:"go1.22.6"}

### What's your kubectl version?

Client Version: v1.31.6 Kustomize Version: v5.4.2 Server Version: v1.31.6

### Which chart?

kube-prometheus-stack

### What's the chart version?

60.5.0

### What happened?

The web-config file is not found. 

`time=2025-03-11T20:39:19.160Z level=ERROR source=node_exporter.go:247 msg="open /etc/node-exporter/web-config.yaml: no such file or directory`

### What you expected to happen?

I expected the web-config file to be found as the configMap already exists in the current namespace.

### How to reproduce it?

A web-config.yaml with the following.

`tls_server_config:
  cert_file: /etc/node-exporter/certs/tls.crt
  key_file: /etc/node-exporter/certs/tls.key`

A cm created with the following.

`k create cm node-exporter-web-config --from-file=web-config.yaml -n operator`

A values.yaml with the following.

```
nodeExporter:
  enabled: true

prometheus-node-exporter:
  enabled: true
  extraArgs:
    - "--web.config.file=/etc/node-exporter/web-config.yaml"
  volumes:
  - name: web-config
    configMap:
      name: node-exporter-web-config
  - name: tls-certs
    secret:
      secretName: node-exporter-tls
  - name: web-config
    configMap:
      name: node-exporter-web-config
  volumeMounts:
  - name: tls-secret
    mountPath: /etc/node-exporter/tls
    readOnly: true
  - name: web-config
    mountPath: /etc/node-exporter
```

A helm upgrade with the following.

`helm upgrade operator prometheus-community/kube-prometheus-stack -f kubernetes/prometheus-config/values.yaml -n operator --debug`

### Enter the changed values of values.yaml?

```
nodeExporter:
  enabled: true

prometheus-node-exporter:
  enabled: true
  extraArgs:
    - "--web.config.file=/etc/node-exporter/web-config.yaml"
  volumes:
  - name: web-config
    configMap:
      name: node-exporter-web-config
  - name: tls-certs
    secret:
      secretName: node-exporter-tls
  - name: web-config
    configMap:
      name: node-exporter-web-config
  volumeMounts:
  - name: tls-secret
    mountPath: /etc/node-exporter/tls
    readOnly: true
  - name: web-config
    mountPath: /etc/node-exporter
```

### Enter the command that you execute and failing/misfunctioning.

`helm upgrade operator prometheus-community/kube-prometheus-stack -f kubernetes/prometheus-config/values.yaml -n operator --debug`
