### ISSUE TITLE
[kube-prometheus-stack] [Help] Duplicate etcd metrics - kube_endpoint_ports

### ISSUE THREAD

**Issue by spatterIight** [prometheus-community/helm-charts#5417]
Hello!

I need help :(

In my [Kubespray](https://github.com/kubernetes-sigs/kubespray) deployed cluster there is a constantly firing alert, `PrometheusDuplicateTimestamps`

The duplicate metrics are:
```
kube_endpoint_ports{namespace="kube-system",endpoint="etcd-metrics",port_name="http-metrics",port_protocol="TCP",port_number="2381"} 1
kube_endpoint_ports{namespace="kube-system",endpoint="etcd-metrics",port_name="http-metrics",port_protocol="TCP",port_number="2381"} 1
kube_endpoint_ports{namespace="kube-system",endpoint="etcd-metrics",port_name="http-metrics",port_protocol="TCP",port_number="2381"} 1
```

This is caused by the `etcd-metrics` endpoint having `subsets` with identical `port_name:port_protocol:port_number` -- the address of these subsets is different but that information isn't included in the metric -- thus duplicating them.

I have spent the last few hours banging my head against the wall trying to configure relabeling on these to make them unique, without luck. Even something as simple as adding a hard-coded label to every metric doesn't seem to be working

```yaml
kube-state-metrics:
  fullnameOverride: kube-state-metrics
  selfMonitor:
    enabled: true
  prometheus:
    monitor:
      enabled: true
      metricRelabelings:
        - action: replace
          replacement: "test_value"
          targetLabel: test_label
      relabelings:
        - action: replace
          replacement: "test_value"
          targetLabel: test_label
```

Based on this, I think I am missing something fundamental about how to get relabeling working in this context. Could someone point me in the right direction?

Thanks!

Related:
1. https://github.com/kubernetes-sigs/kubespray/pull/12034
2. https://github.com/kubernetes-sigs/kubespray/issues/12033
