### ISSUE TITLE
[kube-prometheus-stack] upgrade CRD deployment stuck via ArgoCD in waiting for deletion of ServiceAccount and ClusterRole

### ISSUE THREAD

**Issue by azmelanar** [prometheus-community/helm-charts#5428]
### Describe the bug a clear and concise description of what the bug is.

Upgrade CRD job stuck during ArgoCD syncing with waiting for deletion of ServiceAccount and ClusterRole.

<img width="1683" alt="Image" src="https://github.com/user-attachments/assets/00244077-5bb2-4ce1-9b48-a80ed62759fb" />

### What's your helm version?

v3.12.0

### What's your kubectl version?

v1.24.13

### Which chart?

kube-prometheus-stack

### What's the chart version?

69.7.4

### What happened?

ArgoCD unable to synchronize the helm chart due to stuck of syncing process.

### What you expected to happen?

ArgoCD successfully can deploy the helm chart.

### How to reproduce it?

ArgoCD `application.yml`

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: prometheus
  ignoreDifferences:
    - group: "admissionregistration.k8s.io"
      kind: "MutatingWebhookConfiguration"
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
    - group: "admissionregistration.k8s.io"
      kind: "ValidatingWebhookConfiguration"
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'

  source:
    repoURL: {{ .Values.argocd.spec.source.repoURL }}
    targetRevision: {{ .Values.argocd.spec.source.targetRevision }}
    path: "prometheus-stack"
    helm:
      releaseName: prometheus-stack
      valueFiles:
        - values.yaml

  destination:
    server: {{ .Values.argocd.spec.destination.server }}
    namespace: prometheus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
```

`Chart.yaml`

```
apiVersion: v2
name: prometheus-stack
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 69.7.4
    repository: https://prometheus-community.github.io/helm-charts
```

`values.yaml`

```
kube-prometheus-stack:
  crds:
    upgradeJob:
      enabled: true
      image:
        busybox:
          tag: "stable"

      annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
```

### Enter the changed values of values.yaml?

```
kube-prometheus-stack:
  crds:
    upgradeJob:
      enabled: true
      image:
        busybox:
          tag: "stable"

      annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
```

### Enter the command that you execute and failing/misfunctioning.

helm install

**Comment by Tiduster** [comment]
Just had the same issue on our app.

Moving from chart kube-prometheus-stack version version: 69.2.4 to version: 70.1.1

And adding this config at the same time:

```
crds:
  enabled: true
  upgradeJob:
    enabled: true
```
