### ISSUE TITLE
[prometheus-postgres-exporter] unable to install chart

### ISSUE THREAD

**Issue by deem1978** [prometheus-community/helm-charts#5431]
Hello everybody, I would really appreciate if anyone will have a look into my issue.
I need to setup an unique `postgres-exporter `in order to monitor multiples databases. I already use the `mysql-exporter` chart in an almost identical setup and without any problem.

`Chart Version: 6.10.0`
`Exporter Version: v0.17.0`

Running the install of the chart, I run into this error:
```
Normal   HelmChartCreated  20m                helm-controller  Created HelmChart/aa-monitoring/aa-monitoring-aa-prometheus-postgres-exporter w ││ ith SourceRef 'HelmRepository/aa-monitoring/aa-prometheus-community'                                                                             ││   Warning  InstallFailed     2s (x12 over 20m)  helm-controller  Helm install failed for release aa-monitoring/aa-prometheus-postgres-exporter w │
│ ith chart prometheus-postgres-exporter@6.10.0: template: prometheus-postgres-exporter/templates/deployment.yaml:31:28: executing "prometheus-pos ││ tgres-exporter/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: prometh ││ eus-postgres-exporter/templates/configmap.yaml:11:18: executing "prometheus-postgres-exporter/templates/configmap.yaml" at <.Values.config.postg │
│ resExporter>: wrong type for value; expected string; got map[string]interface {}
```

This is my `values.yaml`:

```
replicaCount: 1

service:
  labels:
    app.kubernetes.io/component: monitoring
    prometheus: external-services-monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
    prometheus.io/path: "/metrics"
  port: 80
  targetPort: 9187
  type: ClusterIP
  name: http

automountServiceAccountToken: false

serviceMonitor:
  # When set true then use a ServiceMonitor to configure scraping
  enabled: true
  # Set the namespace the ServiceMonitor should be deployed
  # namespace: monitoring
  # Set how frequently Prometheus should scrape
  interval: 30s
  # Set path to cloudwatch-exporter telemtery-path
  # telemetryPath: /metrics
  # Set labels for the ServiceMonitor, use this to define your scrape label for Prometheus Operator
  # labels:
  # Set timeout for scrape
  timeout: 10s
  # Set of labels to transfer from the Kubernetes Service onto the target
  # targetLabels: []
  # MetricRelabelConfigs to apply to samples before ingestion
  metricRelabelings:
    # Map the "__param_target" label to "instance" for visibility in metrics
    - sourceLabels: [__param_target]
      targetLabel: instance
    # Map the "__param_target" label to "db_target" for custom identification
    - sourceLabels: [__param_target]
      targetLabel: db_target
  # Set relabel_configs as per https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
  relabelings:
    # Add the Kubernetes service name as the "job" label
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: job
    # Map the "__param_target" label to "instance" for scrape identification
    - sourceLabels: [__param_target]
      targetLabel: instance
    # Add the "__param_target" as a label in metrics
    - sourceLabels: [__param_target]
      targetLabel: target
  # HTTP scheme to use for scraping. For example `http` or `https`. Default is `http`.
  # scheme: http
  # TLS configuration to use when scraping the metric endpoint by Prometheus.
  # tlsConfig: {}

   # Use multipleTarget mode
  multipleTarget:
    enabled: true
    # Use the same auth module for every target
    # The config file should have a section like [$name]
    sharedAuthModule:
      enabled: false
      name: ""

    # Define each target's endpoint and name
    # When not using sharedAuthModule the config file should have one authModule for each target with key "client.$name"
    targets:
      - endpoint: 10.0.0.1
        name: first_endpoint
        port: 5432
        databaseName: db1
      - endpoint: 10.0.0.2
        name: second_endpoint
        port: 5432
        databaseName: db2

prometheusRule:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

rbac:
  # Specifies whether RBAC resources should be created
  create: false

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: false
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
  # Add annotations to the ServiceAccount, useful for EKS IAM Roles for Service Accounts or Google Workload Identity.
  annotations: {}

# Add a default ingress to allow namespace access to service.targetPort
# Helpful if other NetworkPolicies are configured in the namespace
networkPolicy:
  # Specifies whether a NetworkPolicy should be created
  enabled: false
  # Set labels for the NetworkPolicy
  labels: {}

# The securityContext of the pod.
# See https://kubernetes.io/docs/concepts/policy/security-context/ for more.
podSecurityContext:
  runAsGroup: 1001
  runAsUser: 1001
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# The securityContext of the container.
# See https://kubernetes.io/docs/concepts/policy/security-context/ for more.
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true

config:
  ## The datasource properties on config are passed through helm tpl function.
  ## ref: https://helm.sh/docs/developing_charts/#using-the-tpl-function
  datasource:
    # Specify one of both datasource or datasourceSecret
    host: ''
    user: ''
    # Specify userFile if DB username is stored in a file.
    # For example, to use with vault-injector from Hashicorp
    userFile: ''
    userSecret: {}
    # Secret name
    #  name:
    # User key inside secret
    #  key:
    # Only one of password, passwordFile, passwordSecret and pgpassfile can be specified
    password:
    # Specify passwordFile if DB password is stored in a file.
    # For example, to use with vault-injector from Hashicorp
    passwordFile: ''
    # Specify passwordSecret if DB password is stored in secret.
    passwordSecret: {}
    # Secret name
    #  name:
    # Password key inside secret
    #  key:
    pgpassfile: ''
    # If pgpassfile is set, it is used to initialize the PGPASSFILE environment variable.
    # See https://www.postgresql.org/docs/14/libpq-pgpass.html for more info.
    port: "5432"
    database: ''
    sslmode: disable
    extraParams: ''
  datasourceSecret: {}
    # Specifies if datasource should be sourced from secret value in format: postgresql://login:password@hostname:port/dbname?sslmode=disable
    # Multiple Postgres databases can be configured by comma separated postgres connection strings
    # Secret name
    #  name:
    # Connection string key inside secret
    #  key:
  disableCollectorDatabase: false
  disableCollectorBgwriter: false
  disableDefaultMetrics: false
  disableSettingsMetrics: false

  # possible values debug, info, warn, error, fatal
  logLevel: ""
  # possible values logfmt, json
  logFormat: ""
  extraArgs: []

  # postgres_exporter.yml
  postgresExporter: |-
    auth_modules:
      first_endpoint:
        type: userpass
        userpass:
          username: user1
          password: password1
        options:
          sslmode: disable
      second_endpoint:
        type: userpass
        userpass:
          username: user2
          password: password
        options:
          sslmode: disable

  # define an existing secret to be mounted as the config file
  # needs to have the key 'postgres_exporter.yml'
  existingSecret:
    enabled: false
    name: ""

# Configurable probes. If TLS client authentication is enabled at the exporter, TCP probe must be used.
livenessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTP
  # tcpSocket:
  #   port: http
  timeoutSeconds: 3

readinessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTP
  # tcpSocket:
  #   port: http
  timeoutSeconds: 1

podDisruptionBudget:
  enabled: false
  maxUnavailable: 1

```

The error message is clear, `Values.config.postgresExporter` expect a string, but it finds a map. However it is not clear at all which value has to be defined in `postgresExporter`. The values [file](https://github.com/prometheus-community/helm-charts/blob/f8bf8a63aaff6dde77ec4e5373ca624ff393a305/charts/prometheus-postgres-exporter/values.yaml#L202) give as example that the `auth_module` should be defined under the `config.postgresExporter`, but it does not work.
Please could somebody provide some clarification about how to setup a `multiTarget` configuration and how to use the `auth_module` and which value is expected to be defined in `config.postgresExporter`?
Thank you
