### ISSUE TITLE
[prometheus-pushgateway] Basic Auth forces to keep plaintext password in git

### ISSUE THREAD

**Issue by Huldula** [prometheus-community/helm-charts#5439]
When using Basic Auth, the passwords need to be set as plaintext values under `webConfiguration` and thus have to be checked in to git. One option to not forcing this would be to let the user create the secret containing web-config outside the helm chart, but right now the Deployment would be missing web-config options (volume mount, container args) when doing this.

**Comment by zeritti** [comment]
> When using Basic Auth, the passwords need to be set as plaintext values under webConfiguration and thus have to be checked in to git

No, this is incorrect. At the time of helm reading the field, it must be of the desired and correct value. What form the file is stored in has no relation to what helm (or another chart installer) eventually reads. The main thing is that the previous point applies. It is just a matter of a toolchain and a workflow. Obviously, the field's value need not be stored in the repository at all - it may come from the toolchain's secret store.

Just a few examples of what the field can look like in storage:

```yaml
webConfiguration:
  basicAuthUsers:
    operator: <path:secret/data/pushgateway/basic-auth/operator#password>
```

or

```yaml
webConfiguration:
  basicAuthUsers:
    operator: ENC[AES256_GCM,data:arb54yHMRnM1+w==,iv:N34/69bpFbd9PUslv+9kLAwYH4BqrHWt8hgvcpiN40M=,tag:KnlSsZ0rlLwp1gaPGj1i5g==,type:str]
```

or

```text
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3amp2NWpyclhFckEydklt
OGdWWHZkZFd6b0w1WWxiMTJreXg0Zy9jRzFnCnZydUNNMTJuck9TR01BZjRiQXRU
aTZPeW1XR3ZhbTVCNUZGTW5pM3NIaFEKLS0tIERMMXNXL2xEVmE2ZERnTmNsWmtt
c1VwclVYWkZKNXBWZFYwbDArZmpHTDgKLIp6yC8wl3i8jN96y7XMEiA993jcRMQP
Gnmj2jcpRopPJJAYMq8aO0VB8l7+HNIKvBWfEEThvIbpTlUnE8jKIXHP8OmKDi7Q
vufIaRgBybIMMakhL0pnblR0c7Ur
-----END AGE ENCRYPTED FILE-----
```

or any of many other forms.

> One option to not forcing this would be to let the user create the secret containing web-config outside the helm chart, but right now the Deployment would be missing web-config options (volume mount, container args) when doing this.

You should be able to configure and apply your own web-config by means of `extraVolumes`, `extraVolumeMounts` and `extraFlags` using a previously created secret.
