### ISSUE TITLE
kube-prometheus-stack version 12.10.5 Failed StatefulSet

### ISSUE THREAD

**Issue by WilliamCassanova** [prometheus-community/helm-charts#545]
**Describe the bug**
kube-prometheus-stack version 12.10.5 fails to deploy due to failed StatefulSet.
```
 Warning  FailedCreate  5m51s (x22 over 77m)  statefulset-controller  create Pod prometheus-prometheus-operator-kube-p-prometheus-0 in StatefulSet prometheus-prometheus-operator-kube-p-prometheus failed error: Pod "prometheus-prometheus-operator-kube-p-prometheus-0" is invalid: spec.containers[3].image: Required value
```

This problem was NOT occurring in kube-prometheus-stack 10.1.3

Helm Version:
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}

Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5+IKS", GitCommit:"e0352e4bc18d207c1f12fe32f05a6a69d9d52f7f", GitTreeState:"clean", BuildDate:"2020-12-09T23:04:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

**Which version of the chart**:
12.10.5

**What happened**:
 Warning  FailedCreate  6m23s (x20 over 44m)  statefulset-controller  create Pod prometheus-prometheus-operator-kube-p-prometheus-0 in StatefulSet prometheus-prometheus-operator-kube-p-prometheus failed error: Pod "prometheus-prometheus-operator-kube-p-prometheus-0" is invalid: spec.containers[3].image: Required value

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):
None Materially Pertinent.  The complete set of values with certain values redacted for security purposes.

**The helm command that you execute and failing/misfunctioning**:
Helm does not fail.  It completes successfully.  Output shown below.
```
helm upgrade prometheus-operator prometheus-community/kube-prometheus-stack --install --debug --wait --atomic --create-namespace --history-max 10 --reset-values --timeout 600s --version 12.10.5 --namespace prometheus-operator -f values-a1081267614-241-1.generated.yaml
history.go:53: [debug] getting history for release prometheus-operator
Release "prometheus-operator" does not exist. Installing it now.
install.go:172: [debug] Original chart version: "12.10.5"
install.go:189: [debug] CHART PATH: /root/.cache/helm/repository/kube-prometheus-stack-12.10.5.tgz

< Extra output deleted >

kube-prometheus-stack has been installed. Check its status by running:
  kubectl --namespace prometheus-operator get pods -l "release=prometheus-operator"

Visit https://github.com/prometheus-operator/kube-prometheus for instructions on how to create & configure Alertmanager and Prometheus instances using the Operator.
```

**Helm values set after installation/upgrade:**
```
USER-SUPPLIED VALUES:
alertmanager:
  alertmanagerSpec:
    configMaps:
    - alertmanager-template
    logFormat: logfmt
    secrets:
    - < redacted >
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: ibmc-block-bronze
    useExistingSecret: true
grafana:
  admin:
    existingSecret: < redacted >
deploymentStrategy:
    type: Recreate
  envFromSecret: 
  grafana.ini:
    auth.github:
      allow_sign_up: true
      allowed_organizations: < redacted >
      api_url: https://api.github.com/user
      auth_url: https://github.com/login/oauth/authorize
      enabled: true
      scopes: user:email,read:org
      team_ids: < redacted >
      token_url: < redacted >
    server:
      root_url: < redacted >
    users:
      auto_assign_org_role: Editor
  ingress:
    enabled: true
    hosts:
    - < redacted >
    tls:
    - hosts:
      - < redacted >
      secretName: < redacted >
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    size: 20Gi
    storageClassName: ibmc-block-bronze
  resources:
    requests:
      memory: 60Mi
  sidecar:
    dashboards:
      searchNamespace: ALL
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
kube-state-metrics:
  resources:
    requests:
      memory: 25Mi
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
prometheus:
  prometheusSpec:
    containers:
    - name: rules-configmap-reloader
      resources:
        limits:
          cpu: 200m
    externalLabels:
      cluster: < redacted >
    resources:
      requests:
        memory: 1Gi
    retention: 7d
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 60Gi
          storageClassName: ibmc-block-bronze
    thanos:
      baseImage: quay.io/thanos/thanos
      objectStorageConfig:
        key: < redacted >
        name: < redacted >
      resources:
        requests:
          cpu: 100m
          memory: 24Mi
      version: v0.17.1
prometheus-node-exporter:
  resources:
    requests:
      memory: 21Mi
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: edge
  - effect: NoExecute
    key: dedicated
    operator: Equal
    value: edge
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: alb
  - effect: NoExecute
    key: dedicated
    operator: Equal
    value: alb
prometheusOperator:
  admissionWebhooks:
    enabled: false
  createCustomResource: false
  resources:
    requests:
      memory: 20Mi
  tls:
    enabled: false
  tlsProxy:
    enabled: false
```
