### ISSUE TITLE
[kube-prometheus-stack] AlertmanagerConfig doesn't seem to send alerts to PagerDuty receiver

### ISSUE THREAD

**Issue by rjonala** [prometheus-community/helm-charts#548]
I am running **kube-prometheus-stack-11.1.7**. When I try to configure alerts using AlertmanagerConfig custom resource object, it doesn't seem to send alerts to PagerDuty receiver. I can see alerts being fired in Prometheus/Alertmanager UI but not on PagerDuty. Here is my AlertmanagerConfig yaml,

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-example
  labels:
    alertmanagerConfig: example
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'pagerduty'
  receivers:
  - name: 'pagerduty'
    pagerdutyConfigs:
    - serviceKey: 
        key: xxxxx
```
Is anything wrong with my config? I don't find any working examples online. Would be great if someone can provide a working example of AlertmanagerConfig custom resource object. Thank you.
