### ISSUE TITLE
[kube-prometheus-stack] Error on ingesting out-of-order samples only when scraping cAdvisor metrics

### ISSUE THREAD

**Issue by mbasha86** [prometheus-community/helm-charts#5483]
### Describe the bug a clear and concise description of what the bug is.

+ After upgrading to  prometheus stack helm chart version 68.5.0, we noticed ingesting out-of-order samples errors happening in different k8s clusters only with scrape pool "serviceMonitor/monitoring/prometheus-stack-kube-prom-kubelet/1" during scarping cAdvisor metrics. This out of order sample messages is also happening of different series. 

+ Here's an example from our promethues pod logs: 

```bash
{"time":"2025-03-26T11:51:06.016158945Z","level":"DEBUG","source":"scrape.go:1909","msg":"Out of order sample","component":"scrape manager","scrape_pool":"serviceMonitor/monitoring/prometheus-stack-kube-prom-kubelet/1","target":{},"series":"container_threads{container=\"\",id=\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podxxxx\",image=\"\",name=\"\",namespace=\"XXX\",pod=\"XXX\"}"}
{"time":"2025-03-26T11:51:06.017086726Z","level":"WARN","source":"scrape.go:1882","msg":"Error on ingesting out-of-order samples","component":"scrape manager","scrape_pool":"serviceMonitor/monitoring/prometheus-stack-kube-prom-kubelet/1","target":{},"num_dropped":460}
```

### What's your helm version?

Flux version 2.3.0

### What's your kubectl version?

v1.31.4

### Which chart?

kube-prometheus-stack

### What's the chart version?

68.5.0

### What happened?

+ After upgrading to  prometheus stack helm chart version 68.5.0, we noticed ingesting out-of-order samples errors happening in different k8s clusters only with scrape pool "serviceMonitor/monitoring/prometheus-stack-kube-prom-kubelet/1" during scarping cAdvisor metrics. This out of order sample messages is also happening of different series. 

+ Here's an example from our promethues pod logs: 

```bash
{"time":"2025-03-26T11:51:06.016158945Z","level":"DEBUG","source":"scrape.go:1909","msg":"Out of order sample","component":"scrape manager","scrape_pool":"serviceMonitor/monitoring/prometheus-stack-kube-prom-kubelet/1","target":{},"series":"container_threads{container=\"\",id=\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podxxxx\",image=\"\",name=\"\",namespace=\"XXX\",pod=\"XXX\"}"}
{"time":"2025-03-26T11:51:06.017086726Z","level":"WARN","source":"scrape.go:1882","msg":"Error on ingesting out-of-order samples","component":"scrape manager","scrape_pool":"serviceMonitor/monitoring/prometheus-stack-kube-prom-kubelet/1","target":{},"num_dropped":460}
```

### What you expected to happen?

+ Fixing this issue 

### How to reproduce it?

+ upgrade from an old version of prometheus stack helm chart i.e 62.x.x to  prometheus stack helm chart version 68.5.0.
+ check prometheus-prometheus-stack-kube-prom-prometheus-0  pod logs

### Enter the command that you execute and failing/misfunctioning.

Nothing Fail

**Comment by avidspartan1** [comment]
Anyone have any ideas on what may be causing this? I've played around with the honorTimestamps and timestamps staleness configuration on the Kubelet ServiceMonitor, but no dice yet.

**Comment by SuperQ** [comment]
This very much seems like some kind of cAdvisor bug to me. Maybe an system time issue? It would be useful to get a data capture of the raw sample data to see what's actually going on.

**Comment by stromnet** [comment]
This is still an issue for us. Have anyone played around with out_of_order_time_window setting in agent (haven't read up much about it yet) as mentioned in https://github.com/prometheus/prometheus/issues/14973?

**Comment by mbasha86** [comment]
> This is still an issue for us. Have anyone played around with out_of_order_time_window setting in agent (haven't read up much about it yet) as mentioned in [prometheus/prometheus#14973](https://github.com/prometheus/prometheus/issues/14973)?

We are not running prometheus agent, that's why i did not try this in prometheus especially i am not how this will affect scraping other metrics. So, i think this issue needs a fix.

**Comment by galovics** [comment]
Getting back here, I did switch to server mode and without any configuration and providing an outOfOrderTimeWindow setting, everything works perfectly fine.

**Comment by mbasha86** [comment]
> This is still an issue for us. Have anyone played around with out_of_order_time_window setting in agent (haven't read up much about it yet) as mentioned in [prometheus/prometheus#14973](https://github.com/prometheus/prometheus/issues/14973)?

I tried this in my testing prometheus stack env "no prometheus agent" with values 5s,10s,15s,20s,25s but almost same issue exists with different message "too old sample". So, this issue still needs a fix

**Comment by avidspartan1** [comment]
This is definitely still an issue for my use case of Prometheus in Agent mode

**Comment by lfrere** [comment]
> This is definitely still an issue for my use case of Prometheus in Agent mode

After search the issue appear in chart version 67.2.0. And new parameter exist for cadvisor (https://github.com/prometheus-community/helm-charts/compare/prometheus-operator-admission-webhook-0.18.0...kube-prometheus-stack-67.2.0). I changed cAdvisorInterval and resourceInterval to 30s instead of 10s solve the problem on my agents.

**Comment by minhes** [comment]
I still have this issue even when I am using Server mode and I'd like to keep 10s.

**Comment by bittrance** [comment]
I can confirm that
```
kubelet:
  serviceMonitor:
    interval: 30s
```
silenced this log message.

**Comment by beckyeh-ye** [comment]
interval 30s to slow for us, so I use blow

```
kubelet:
  serviceMonitor:
    cAdvisorInterval: 10s
    honorTimestamps: false
    trackTimestampsStaleness: false
```

**Comment by pspittelmeister** [comment]
Same problem here. Our config:

```
kubelet:
  serviceMonitor:
    honorTimestamps: false
```

but the generated Servicemonitor dosent have all `honorTimestamps: false` set to false. The `path: /metrics/cadvisor` keeps

```
spec:
  attachMetadata:
    node: false
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    honorTimestamps: false
    metricRelabelings:
    - action: drop
      regex: (csi_operations|storage_operation_duration)_seconds_bucket;(0.25|2.5|15|25|120|600)(\.0)?
      sourceLabels:
      - __name__
      - le
    port: https-metrics
    relabelings:
    - action: replace
      sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    honorTimestamps: true
    interval: 10s
    metricRelabelings:
    - action: drop
      regex: container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_memory_(mapped_file|swap)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_(file_descriptors|tasks_state|threads_max)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_memory_failures_total;hierarchy
      sourceLabels:
      - __name__
      - scope
    - action: drop
      regex: container_network_.*;(cali|cilium|cni|lxc|nodelocaldns|tunl).*
      sourceLabels:
      - __name__
      - interface
    - action: drop
      regex: container_spec.*
      sourceLabels:
      - __name__
    - action: drop
      regex: .+;
      sourceLabels:
      - id
      - pod
    path: /metrics/cadvisor
    port: https-metrics
    relabelings:
    - action: replace
      sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
    trackTimestampsStaleness: true
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    honorTimestamps: false
    path: /metrics/probes
    port: https-metrics
    relabelings:
    - action: replace
      sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
      k8s-app: kubelet
```
