### ISSUE TITLE
[kube-prometheus-stack] Standalone Prometheus operator chart

### ISSUE THREAD

**Issue by hobbit44** [prometheus-community/helm-charts#5497]
### Is your feature request related to a problem ?

At the moment the helm chart contains Prometheus, and Grafana, and Alertmanager, and a whole load of dashboards, policies and other things. Could we get a chart for just the Prometheus operator. I already have a Grafana instance using [grafana-operator](https://github.com/grafana/grafana-operator) so i just need Prometheus. 

### Describe the solution you'd like.

I think it follows the helm chart model as well if the individual parts of this are broken down into separate components. Then if we just need a part we can install that. This chart could then be a aggregator to maintain compatibility using the other charts as dependencies. I think this is where you're headed with #3548. My person preference is to be able to have separate configurations for the different components. It makes debugging a lot easier when I'm investigating a problem i can easier identify in my source which folder has the config for the app I'm looking for.

### Describe alternatives you've considered.

At the moment I have to install the above stack just specifying Prometheus. Then all my pod names come out as:
```
prometheus-kube-prometheus-operator-7745bc94fc-dqffg
prometheus-prometheus-kube-prometheus-prometheus-0
```
I can also go with the standalone crd chart but there isn't a standalone controller, only the admission webhook.

**Comment by hobbit44** [comment]
Please?

**Comment by hobbit44** [comment]
Pretty please?

**Comment by jkroepke** [comment]
You can already disable all parts from kube-prometheus-stack that you have basicly only a prometheus-operator chart.

I guess no current maintainer will maintain prometheus-operator related YAMLs twice.

**Comment by crouth-redge** [comment]
Doesn't need to be twice - create a prometheus-operator subchart that wraps the components for deploying only the operator, and treat the others as seperate concerns. The resulting chart would just become a dependency of kube-prometheus-stack

**Comment by crouth-redge** [comment]
For anyone else that lands here trying to find the way to have ONLY the Operator installed, this is the current state of things:

```yaml
  crds:
    enabled: false # installed by k8s-monitoring currently
  defaultRules:
    create: false
  prometheus-windows-exporter:
    prometheus:
      monitor:
        enabled: false
  alertmanager:
    enabled: false
  grafana:
    enabled: false
  kubernetesServiceMonitors:
    enabled: false
  kubeApiServer:
    enabled: false
  kubelet:
    enabled: false
  kubeControllerManager:
    enabled: false
  coreDns:
    enabled: false
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false
  kubeStateMetrics:
    enabled: false
  kube-state-metrics:
    enabled: false
  nodeExporter:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  prometheus:
    enabled: false
 
```

I think this is important context for this ticket. Not only are we required to download all the resources for these items that we do not want/will not use in a standalone operator deployment - thats a heck of a lot of boilerplate to arrive to an operator only install.
