### ISSUE TITLE
[prometheus-postgres-exporter] unable to use alert variables in prometheusRule entries

### ISSUE THREAD

**Issue by fredericve** [prometheus-community/helm-charts#5508]
### Describe the bug a clear and concise description of what the bug is.

When using an alert variable in the prometheusRule annotations section, I get this output:
```
COMBINED OUTPUT:
  Error: Failed to render chart: exit status 1: Error: template: prometheus-postgres-exporter/templates/prometheusrule.yaml:18:16: executing "prometheus-postgres-exporter/templates/prometheusrule.yaml" at <tpl (toYaml .) $>: error calling tpl: cannot parse template "- alert: PostgreSQLDown\n  annotations:\n    description: foobar {{ $labels.instance }}\n    summary: faa\n  expr: pg_up{} != 1\n  for: 1m\n  labels:\n    severity: warning": template: gotpl:3: undefined variable "$labels"
```

My values.yaml contains this:
```yaml
prometheusRule:
  enabled: true
  namespace: {{ .Values.stack.namespace }}
  rules:
    - alert: PostgreSQLDown
      annotations:
        description: 'foobar {{`{{ $labels.instance }}`}}'
        summary: faa
      expr: pg_up{} != 1
      for: 1m
      labels:
        severity: warning
```

I tried multiple known ways to escape variable expansion but have exhausted my knowledge.

### What's your helm version?

version.BuildInfo{Version:"v3.15.3", GitCommit:"3bb50bbbdd9c946ba9989fbe4fb4104766302a64", GitTreeState:"clean", GoVersion:"go1.22.5"}

### What's your kubectl version?

Client Version: v1.30.3 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.29.14-eks-bc803b4

### Which chart?

prometheus-postgres-exporter

### What's the chart version?

6.8.1

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus-postgres-exporter prometheus-community/prometheus-postgres-exporter --version 6.8.1 --values values.yaml

### Anything else we need to know?

A similar thing seems to have happened in the past for the prometheus-blackbox-exporter chart. The solution there was to remove the `tpl` function: https://github.com/prometheus-community/helm-charts/issues/2450

**Comment by fredericve** [comment]
@zeritti strange. I do get the error outputs and the chart fails to install. We're using similar escaping in other charts where it works fine.

Which versions of `helm` and `helmfile` are you using? I just upgraded to the latest versions and still have the issue there.

Using these values:
```yaml
prometheusRule:
  enabled: true
  rules:
    - alert: PostgreSQLDown
      annotations:
        description: '{{ `{{` }} $labels.instance {{ `}}` }} is rejecting query requests from the exporter. Please verify the exporter credentials.'
        summary: 'PostgreSQL is not processing queries on {{ `{{` }} $labels.instance {{ `}}` }}'
      expr: |
        pg_up{} != 1
      for: 1m
      labels:
        severity: warning
```
I get this result:

```
helmfile -l "name=prometheus-postgres-exporter" apply
Comparing release=prometheus-postgres-exporter, chart=../charts/prometheus-postgres-exporter-6.8.1.tgz, namespace=development-monitoring
in ./helmfile.yaml: in .helmfiles[0]: in /home/fredericve/git/modkub/stacks/monitoring/helmfiles/helmfile.yaml: command "/usr/bin/helm" exited with non-zero status:

PATH:
  /usr/bin/helm

ARGS:
  0: helm (4 bytes)
  1: diff (4 bytes)
  2: upgrade (7 bytes)
  3: --allow-unreleased (18 bytes)
  4: prometheus-postgres-exporter (28 bytes)
  5: ../charts/prometheus-postgres-exporter-6.8.1.tgz (48 bytes)
  6: --version (9 bytes)
  7: 6.8.1 (5 bytes)
  8: --namespace (11 bytes)
  9: development-monitoring (22 bytes)
  10: --values (8 bytes)
  11: /tmp/helmfile1072248345/development-monitoring-prometheus-postgres-exporter-values-6968655549 (93 bytes)
  12: --detailed-exitcode (19 bytes)
  13: --color (7 bytes)
  14: --reset-values (14 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Failed to render chart: exit status 1: Error: template: prometheus-postgres-exporter/templates/prometheusrule.yaml:18:16: executing "prometheus-postgres-exporter/templates/prometheusrule.yaml" at <tpl (toYaml .) $>: error calling tpl: cannot parse template "- alert: PostgreSQLDown\n  annotations:\n    description: '{{ $labels.instance }} is rejecting query requests from the exporter.\n      Please verify the exporter credentials.'\n    summary: PostgreSQL is not processing queries on {{ $labels.instance }}\n  expr: |\n    pg_up{} != 1\n  for: 1m\n  labels:\n    severity: warning": template: gotpl:3: undefined variable "$labels"
  Use --debug flag to render out invalid YAML
  Error: plugin "diff" exited with error

COMBINED OUTPUT:
  Error: Failed to render chart: exit status 1: Error: template: prometheus-postgres-exporter/templates/prometheusrule.yaml:18:16: executing "prometheus-postgres-exporter/templates/prometheusrule.yaml" at <tpl (toYaml .) $>: error calling tpl: cannot parse template "- alert: PostgreSQLDown\n  annotations:\n    description: '{{ $labels.instance }} is rejecting query requests from the exporter.\n      Please verify the exporter credentials.'\n    summary: PostgreSQL is not processing queries on {{ $labels.instance }}\n  expr: |\n    pg_up{} != 1\n  for: 1m\n  labels:\n    severity: warning": template: gotpl:3: undefined variable "$labels"
  Use --debug flag to render out invalid YAML
  Error: plugin "diff" exited with error
```

**Comment by zeritti** [comment]
I used `helm` 3.15.3 as yours and 3.17.2 and `helmfile` 0.171.

**Comment by fredericve** [comment]
Well, I don't know what to say. Myself and my colleagues all have the same problem. Other charts where we use the same syntax for alerts don't have this problem. It really is related to the `tpl` function.

We do use a gitops model, where our helmcharts are templated as well to be able to use across different environments. Maybe that why you can't reproduce it?

@zanhsieh I see you rebased the branch in the PR. Are you unable to reproduce it as well?

**Comment by zanhsieh** [comment]
No. I can't reproduce it.

**Comment by fredericve** [comment]
We can't reproduce with `helm`, but we can easily reproduce it with `helmfile` though.

After troubleshooting some more, we found that we have to quote twice in order to have it templated properly when using `helmfile`:
```yaml
prometheusRule:
  enabled: true
  namespace: {{ .Values.stack.namespace }}
  rules:
    - alert: PostgreSQLDown
      annotations:
        description: 'foobar {{ "{{ `{{` }}" $labels.instance "{{ `}}` }}" }}'
        summary: faa
      expr: pg_up{} != 1
      for: 1m
      labels:
        severity: warning
```

`helmfile` consumes the brackets once. Then the `tpl` function does it a second time, which does not work because they are already consumed.

For now we have a workaround, but still looks like the `tpl` function is not where it needs to be. Here's several examples in prometheus-community/helm-charts that don't use the tpl function, and we don't have the double quoting requirement:

- https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-yet-another-cloudwatch-exporter/templates/prometheusrule.yaml#L18
- https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/templates/prometheusrule.yaml#L18
- https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-cloudwatch-exporter/templates/prometheusrule.yaml#L18

I do see several other charts that are using the `tpl` function though. Probably these have the same issue.
