### ISSUE TITLE
[kube-prometheus-stack] grafana doesn't see prom data sources

### ISSUE THREAD

**Issue by kotyara85** [prometheus-community/helm-charts#5515]
Hello everyone,
Hitting a very strange error when using prome kube stack v65.0.0

![Image](https://github.com/user-attachments/assets/0cebdd63-4d5b-478e-8a5f-aa53d4663d98)

Some cluster do have this error some don't, they're running off the same centralized configs and managed by argocd

I do see that config was successfully injected into grafana:

```
apiVersion: 1
datasources:
- name: "Prometheus"
  type: prometheus
  uid: prometheus
  url: http://prometheus-kube-prometheus-prometheus.monitoring-system:9090/
  access: proxy
  isDefault: true
  jsonData:
    httpMethod: POST
    timeInterval: 30s
- name: "Alertmanager"
  type: alertmanager
  uid: alertmanager
  url: http://prometheus-kube-prometheus-alertmanager.monitoring-system:9093/
  access: proxy
  jsonData:
    handleGrafanaManagedAlerts: false
    implementation: prometheus
```

Is there anything else I can look into?
Thanks
