### ISSUE TITLE
[prometheus-redis-exporter] multipleTarget issue

### ISSUE THREAD

**Issue by emily-ganze** [prometheus-community/helm-charts#5532]
### Describe the bug a clear and concise description of what the bug is.

Hello,

When enabling multipleTarget, the REDIS_ADDR env variable is still defaulted to values.redisAddress and mutlipleTarget is not considered in the deployment template. 

[deployment template](https://github.com/prometheus-community/helm-charts/blob/995b3392c82ecfdec4cbc432064b04b40c71c8aa/charts/prometheus-redis-exporter/templates/deployment.yaml#L57):
```
          env:
            - name: REDIS_ADDR
            {{- if .Values.redisAddressConfig.enabled }}
              valueFrom:
              {{- if .Values.redisAddressConfig.isSecret }}
                secretKeyRef:
              {{- else }}
                configMapKeyRef:
              {{- end }}
                  name: {{ .Values.redisAddressConfig.source.name }}
                  key: {{ .Values.redisAddressConfig.source.key }}
            {{- else }}
              value: {{ .Values.redisAddress }}
            {{- end }}
```
default helm values [lines 65-66](https://github.com/prometheus-community/helm-charts/blob/995b3392c82ecfdec4cbc432064b04b40c71c8aa/charts/prometheus-redis-exporter/values.yaml#L66):
```
# If serviceMonitor.multipleTarget is enabled, this configuration is actually not used
redisAddress: redis://myredis:6379
```

configured helm yaml:
```
serviceMonitor:
    enabled: true
    multipleTarget: true
    targets:
    - url: "URL1:6379"
      name: redis1
    - url: "URL2:6379"
      name: redis2
```

logs:
```
error msg="Couldn't connect to redis instance (redis://myredis:6379)"
```
### What's your helm version?

version.BuildInfo{Version:"v3.17.1", GitCommit:"980d8ac1939e39138101364400756af2bdee1da5", GitTreeState:"clean", GoVersion:"go1.23.6"}

### What's your kubectl version?

Client Version: v1.32.2

### Which chart?

prometheus-redis-exporter

### What's the chart version?

6.9.0

### What you expected to happen?

mutlipleTarget is not being honored for the environment variable `REDIS_ADDR`

### How to reproduce it?

enable multipleTarget

### Enter the changed values of values.yaml?

serviceMonitor:
    enabled: true
    multipleTarget: true
    targets:
    - url: "URL1:6379"
      name: redis1
    - url: "URL2:6379"
      name: redis2

### Enter the command that you execute and failing/misfunctioning.

helm install Chart.yaml  --values values.yaml

**Comment by dmitry-mightydevops** [comment]
ran into the same issue

**Comment by rbudiharso** [comment]
me too

**Comment by stdmje** [comment]
This worked for me...

```
image:
  pullPolicy: Always

redisAddress: ""

serviceMonitor:
  enabled: true
  multipleTarget: true
  interval: 30s
  scrapeTimeout: 10s
  scheme: "http"
  telemetryPath: /scrape
  targets:
    - url: "redis://10.140.0.1:6379"
      name: "my-first-redis"

    - name: "my-second-redis"
      url: "redis://10.140.0.2:6379"
```

repoURL: https://prometheus-community.github.io/helm-charts
chart: prometheus-redis-exporter
targetRevision: 6.20.1
