### ISSUE TITLE
remove arrays from configs

### ISSUE THREAD

**Issue by matti** [prometheus-community/helm-charts#555]
overriding scrape_interval in the prometheus.yml scrape configs:
```
      helm upgrade --install prometheus prometheus-community/prometheus \
        --version="13.0.2" \
        --create-namespace --namespace prometheus \
        --set "serverFiles.prometheus.yml.scrape_configs[5].scrape_interval=30s" \
        --set "serverFiles.prometheus.yml.scrape_configs[5].scrape_timeout=25s"
```

results in:

```
  prometheus:
    yml:
      scrape_configs:
      - null
      - null
      - null
      - null
      - null
      - scrape_interval: 30s
        scrape_timeout: 25s
```

due to https://github.com/helm/helm/issues/5711
