### ISSUE TITLE
[kube-prometheus-stack] configMap Dashboard for grafana operator

### ISSUE THREAD

**Issue by DrummyFloyd** [prometheus-community/helm-charts#5568]
### Is your feature request related to a problem ?

i'm wondering if  it will be possible to add  following confimap for Grafna Operator, that will allow ppl taht use grafana operator to use maintained dashboard from this stack, especially when we use the stack excpect for grafana part

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server
data:
  api-server.json: >
    {
      "id": null,
      "title": "Simple Dashboard from ConfigMap",
      "tags": [],
      "style": "dark",
      "timezone": "browser",
      "editable": true,
      "hideControls": false,
      "graphTooltip": 1,
      "panels": [],
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {
        "time_options": [],
        "refresh_intervals": []
      },
      "templating": {
        "list": []
      },
      "annotations": {
        "list": []
      },
      "refresh": "5s",
      "schemaVersion": 17,
      "version": 0,
      "links": []
    }    
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: grafanadashboard-from-configmap
spec:
  instanceSelector:
    matchLabels:
      grafana_dashboard: "1"
  configMapRef:
    name: api-server
    key: api-server.json
```

### Describe the solution you'd like.

would be do thru' something like this :
```yaml
grafana:
  enabled: false
   forceDeployDashboards: true
# Create CRD: kind: GrafanaDashboardn for ppl who use grafana operator
   operatorDashboardsConfigMapRef: true
```

### Describe alternatives you've considered.

make it manually atm , but bit time consumming depending of the `releaseName` used
