### ISSUE TITLE
[prometheus-kube-stack] thanos sidecar metrics

### ISSUE THREAD

**Issue by IbraheemAlSaady** [prometheus-community/helm-charts#560]
**Describe the bug**
I'm not able to see the Thanos sidecar metrics. I have created a headless service like this

```yaml
apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecar
  labels:
    release: prometheus-operator
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 10902
    targetPort: http
  selector:
    app: prometheus
```
The Thanos sidecar exports metrics such as `thanos_sidecar_last_heartbeat_success_time_seconds`, I assume the service monitor will pick up the metrics since the service is labeled with `release: prometheus-operator`

here is my values.yaml

```yaml
    prometheus:
      prometheusSpec:
        externalLabels:
          cluster: main
          tenant: master
        thanos:
          image: docker.io/bitnami/thanos
          tag: 0.17.2-scratch-r1
          objectStorageConfig:
            name: thanos
            key: objstore.yml
```

```console
$ helm version

version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

Kubernetes Version:

```console
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: kube-prometheus-stack

**Which version of the chart**: 12.9.2

**Comment by janlud** [comment]
I'm not a maintainer but this should be just a configuration issue - it works fine for me. You have to line up the service monitor selectors/ports with the service.
The way I did it is that I added additional ports in `prometheus.service.additionalPorts`:

```
                - name: grpc
                  port: 10901
                  protocol: TCP
                  targetPort: 10901
                - name: http
                  port: 10902
                  protocol: TCP
                  targetPort: 10902
```

And then have custom service monitor in `additionalServiceMonitors` for it like this:
```
- name: thanos-sidecar
  jobLabel: thanos-sidecar
  selector:
    matchLabels:
      app.kubernetes.io/instance: ${cluster_name}-prom-op
      name: prometheus-service
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - interval: 30s
      honorLabels: true
      port: http
```
