### ISSUE TITLE
[kube-prometheus-stack] field msteamsv2_config not found in type config.plain

### ISSUE THREAD

**Issue by Zheer09** [prometheus-community/helm-charts#5602]
### Describe the bug a clear and concise description of what the bug is.

My sts alertmanager pod is not creating and i am seeing 2 error from promethues operator, first:

```
failed: provision alertmanager configuration: failed to initialize from secret: yaml: unmarshal errors:\n  line 27: field msteamsv2_config not found in type config.plain
```

and

```
msg="StatefulSet not found" component=alertmanager-controller key=monitoring/alertmanager-prometheus-operator-alertmanager
```

My chart version should have msteamsv2_config for the CDR and should support it.

### What's your helm version?

v3.12.1

### What's your kubectl version?

Client Version: v1.28.15 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.28.9

### Which chart?

kube-prometheus-stack

### What's the chart version?

71.0.0

### Enter the command that you execute and failing/misfunctioning.

I am using helmrelease chart with flux here is my configuration

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  interval: 10m0s
  timeout: 10m0s
  suspend: false
  install:
    disableWait: false
    remediation:
      remediateLastFailure: true
      retries: -1
  upgrade:
    disableWait: false
    remediation:
      remediateLastFailure: true
      strategy: rollback
      retries: 3
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 71.0.0
  values:
    nameOverride: prometheus-operator
    commonLabels:
      scrape_me: my_friend
    crds:
      upgradeJob:
        enabled: true
        forceConflicts: true
    alertmanager:
      alertmanagerSpec:
        externalUrl: https://******
        image:
          registry: quay.io
          repository: prometheus/alertmanager
          tag: v0.28.1
        resources: {}
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "observability"
            effect: "NoSchedule"
      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ["job"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: "prometheus-msteams"
        receivers:
          - name: prometheus-msteams
            msteamsv2_config:
              - webhook_url: "https://prod-13.westeurope.logic.azure.com:443/********"
                send_resolved: true
          - name: "null"
```
