### ISSUE TITLE
[kube-prometheus-stack] Default rules description is wrong if "for" is set to custom value in customRules

### ISSUE THREAD

**Issue by mvolodarets** [prometheus-community/helm-charts#5612]
### Describe the bug a clear and concise description of what the bug is.

kube-prometheus-stack helm chart provides the possibility to configure certain fields in default rules via the `customRules` key (`for` and `serverity`).
But when `for` is set to custom value, rule description keeps the default value for duration, e.g. **KubeNodeNotReady** rule keeps description `{{ $labels.node }} has been unready for more than 15 minutes on cluster {{ $labels.cluster }}` even when `for` is set to `5m`.

### What's your helm version?

3.16.4

### What's your kubectl version?

1.30.6

### Which chart?

kube-prometheus-stack

### What's the chart version?

70.5.0

### What happened?

I wanted to configure the `for` of `KubeNodeNotReady` rule via `customRules`:
```
customRules:
  KubeNodeNotReady:
    for: 5m
    severity: "critical"
```
Unfortunately, rule description keeps: `{{ $labels.node }} has been unready for more than 15 minutes on cluster {{ $labels.cluster }}`

### What you expected to happen?

Expected `KubeNodeNotReady`rule description to be: `{{ $labels.node }} has been unready for more than 5 minutes on cluster {{ $labels.cluster }}`

### How to reproduce it?

1. Add the following custom rule to the values.yaml:
```
customRules:
  KubeNodeNotReady:
    for: 5m
    severity: "critical"
```
2. Deploy the helm chart.
3. The `KubeNodeNotReady` rule description has wrong duration.

### Enter the changed values of values.yaml?

```
customRules:
  KubeNodeNotReady:
    for: 5m
    severity: "critical"
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install --wait prometheus-operator prometheus-community/kube-prometheus-stack  --version 70.5.0  --values values.yaml  --namespace=monitoring
