### ISSUE TITLE
[prometheus-elasticsearch-exporter] extra manifest mount issue

### ISSUE THREAD

**Issue by Viacheslav-Horbachov** [prometheus-community/helm-charts#5623]
### Describe the bug a clear and concise description of what the bug is.

I tried several times to add configuration for an external secret via extraManifests, to pass credentials for Elasticsearch. After checking the default values in values.yaml

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-elasticsearch-exporter/values.yaml#L138C1-L145C28

I found that it still doesn’t work — extraManifests simply doesn’t render any objects.

Then, after searching through commits and PRs, I came across this commit:

https://github.com/grafana/loki/commit/7524c4b3dc5adbfa9bee02992d54e9c6d8b759c3#diff-63fce4804a7a1326e58b3c5ab9bf8efed2fb8407de8280a170e1f74979a4b394R1309-R1327

I cloned the chart and fixed the following file:

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-elasticsearch-exporter/templates/extra-manifests.yaml

by replacing its contents with:

```
{{ range .Values.extraManifests }}
---
{{ tpl (toYaml .) $ }}
{{ end }}
```

After that, I was able to see the config map rendered correctly in the template and the diff.

Here's my values.yaml:

```
extraManifests:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: prometheus-elasticsearch-exporter-extra
      namespace: prometheus
    data:
      extra-data: "value"
```

Result of rendering with Helm:

```
➜  k8s git:(feat/exporter) ✗ helm template elasticsearch-exporter helm-charts/charts/prometheus-elasticsearch-exporter \
  --namespace prometheus \
  --values helm/values/freeze-qa/infrastructure/opensearch-exporter.yaml
Output:
# Source: prometheus-elasticsearch-exporter/templates/extra-manifests.yaml
apiVersion: v1
data:
  extra-data: value
kind: ConfigMap
metadata:
  name: prometheus-elasticsearch-exporter-extra
  namespace: prometheus
```

Could you please fix this issue? At the moment, it blocks anyone who tries to use this chart and mount credentials or additional configuration via extraManifests

### What's your helm version?

v3.16.4

### What's your kubectl version?

Client Version: v1.32.1 Kustomize Version: v5.5.0 Server Version: v1.32.3-eks-bcf3d70 Kubecolor Version: v0.5.0

### Which chart?

prometheus-elasticsearch-exporter

### What's the chart version?

each version from, i've tested on 5.6.0, 6.0.0

### What you expected to happen?

i hope it'll be fixed in a few days, cause changes to fix it very simple

### How to reproduce it?

just try to install chart with default values, by uncomment extra manifest 

### Enter the changed values of values.yaml?

extraManifests: []
--->
extraManifests:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: prometheus-elasticsearch-exporter-extra
      namespace: prometheus
    data:
      extra-data: "value"

### Enter the command that you execute and failing/misfunctioning.

```
helm template elasticsearch-exporter prometheus-community/prometheus-elasticsearch-exporter \               
  --version 5.6.0 \
  --namespace prometheus \
  --values helm/values/freeze-qa/infrastructure/opensearch-exporter.yaml

helm install elasticsearch-exporter prometheus-community/prometheus-elasticsearch-exporter \               
  --version 6.0.0 \
  --namespace prometheus \
  --values helm/values/freeze-qa/infrastructure/opensearch-exporter.yaml
```

**Comment by zeritti** [comment]
`extraManifests` expects an array of strings, e.g.

```yaml
extraManifests:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: prometheus-elasticsearch-exporter-extra
    data:
      extra-data: "value"
```
