### ISSUE TITLE
[kube-prometheus-stack] How can i install kube prometheus chart twice in one cluster, but different namespace?

### ISSUE THREAD

**Issue by vyadav5** [prometheus-community/helm-charts#5647]
I’m encountering an issue while deploying the kube-prometheus-stack Helm chart in a Kubernetes cluster that already has an existing deployment of the same stack.

The first deployment is running in monitoring.

I'm attempting to deploy a second instance of the stack in pulsar.

Despite using separate namespaces, the newly deployed Alertmanager pod is stuck in a continuous Terminating and Pending loop.

**Steps Taken:**
I referred to the following discussions and applied the suggested changes:

**[bitnami/charts#8265](https://github.com/bitnami/charts/issues/8265)**

**[bitnami/charts#8282](https://github.com/bitnami/charts/pull/8282)**

But this made no difference alertmanager pod's behavior 

Additional Information:
**Helm chart version:**   kube-prometheus-stack-72.4.0

**Kubernetes version:** Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.32.2-gke.1297002

**customization in values.yaml related to Alertmanager:**

  alertmanagerConfigNamespaces: 
    - monitoring
  prometheusInstanceNamespaces: 
    - monitoring
 
prometheusOperator:
  extraArgs: 
    - "--namespaces={{ .Release.Namespace }}"

**Question:**
How can I properly deploy a second instance of kube-prometheus-stack in a different namespace without causing Alertmanager to enter this termination loop?

Any guidance or clarification would be appreciated.

**Comment by zeritti** [comment]
It is important to ensure that the other (existing) release does not attempt to manage resources in the new release's namespace. If alertmanager CR or prometheus CR does not show the expected behaviour, please, check namespace' events and the Prometheus operator's logs.

Setting `prometheusOperator.extraArgs` is unnecessary for that specific argument - use `prometheusOperator.namespaces.releaseNamespace`. 

I ran a quick test with installing another release of the chart (namespace `ns01`) with the following settings. Prometheus operator of this release manages its CRs in namespace `ns01` only. For simplicity, I kept only Prometheus operator, alertmanager and prometheus.



```yaml
crds:
  enabled: false

prometheusOperator:
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false

  namespaces:
    releaseNamespace: true

  alertmanagerInstanceNamespaces: ["ns01"]
  alertmanagerConfigNamespaces: ["ns01"]
  prometheusInstanceNamespaces: ["ns01"]
  thanosRulerInstanceNamespaces: ["ns01"]

  kubeletService:
    enabled: false

prometheus:
  enabled: true
alertmanager:
  enabled: true

defaultRules:
  create: false

coreDns:
  enabled: false
grafana:
  enabled: false
kubeApiServer:
  enabled: false
kubeControllerManager:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubelet:
  enabled: false
kubeProxy:
  enabled: false
kubernetesServiceMonitors:
  enabled: false
kubeScheduler:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
```
