### ISSUE TITLE
[kube-prometheus-stack] Pod anti affinity broken

### ISSUE THREAD

**Issue by festeveira** [prometheus-community/helm-charts#5662]
### Describe the bug a clear and concise description of what the bug is.

Pod anti affinity is not working correctly when `agentMode: true`. It is matching wrong values or labels that do not exist. The antiaffinity configuration is matching the value of `app.kubernetes.io/name` with an incorrect value and looking for non-existent  `prometheus` label.

### What's your helm version?

version.BuildInfo{Version:"v3.17.3", GitCommit:"e4da49785aa6e6ee2b86efd5dd9e43400318262b", GitTreeState:"clean", GoVersion:"go1.23.7"}

### What's your kubectl version?

Client Version: v1.29.10 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.30.8+rke2r1

### Which chart?

kube-prometheus-stack

### What's the chart version?

72.5.0

### What happened?

After installing, configured pod anti affinity in prometheusagent resource does not match pod labels.

### What you expected to happen?

Anti affinity to be correctly matching pod labels.

### How to reproduce it?

Execute the helm command and compare the prometheusagent configured pod anti affinity and child pod labels.

### Enter the changed values of values.yaml?

```
prometheus:
  agentMode: true
  prometheusSpec:
    shards: 2
    externalLabels:
      cluster: redacted
    replicaExternalLabelNameClear: true
    prometheusExternalLabelNameClear: true
    scrapeInterval: 1m
    remoteWrite:
      - url: https://redacted/
        basicAuth:
          username: 
            key: username
            name: prometheus-agent-remote-write-auth
          password:
            key: password
            name: prometheus-agent-remote-write-auth    

fullnameOverride: prometheus-agent

kubelet:
  serviceMonitor:
    interval: 1m

grafana:
  enabled: false

defaultRules:
  create: false

alertmanager:
  enabled: false

kubeProxy:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeControllerManager:
  enabled: false

nodeExporter:
  enabled: false
```

### Enter the command that you execute and failing/misfunctioning.

```
helm install prometheus-agent  prometheus-community/kube-prometheus-stack --values values.yaml
```

### Anything else we need to know?

It seems that when `agentMode: true` the `app.kubernetes.io/name` always has `prometheus-agent` value.
It seems that `prometheus` label also never exists when `agentMode: true`. 

So adding a special case for agent mode seems to be necessary for pod anti affinity to work.
