### ISSUE TITLE
Unexpected HTTP scrape on :10250 from kube-prometheus-stack job

### ISSUE THREAD

**Issue by Nicola-Sergio** [prometheus-community/helm-charts#5676]
### Describe the bug a clear and concise description of what the bug is.

After deploying `kube-prometheus-stack`, I see an unexpected set of scrape targets under the section `kube-prometheus-stack` with `job="kube-prometheus-stack` attempting to scrape metrics from **http://<node-ip>:10250/metrics**. All of these targets fail with **400 Bad Request** responses.

![Image](https://github.com/user-attachments/assets/45068b91-4cb4-4870-b33d-af5da2b881d7)

This behavior seems redundant or misconfigured, as there is already a working kubelet job correctly scraping metrics from **https://<node-ip>:10250/metrics** using proper TLS configuration.

![Image](https://github.com/user-attachments/assets/6cdc0d5f-9a82-4b1f-943c-1880a1935ddf)

### What's your helm version?

3.15.2

### What's your kubectl version?

1.32.3

### Which chart?

kube-prometheus-stack

### What's the chart version?

72.6.2

### What you expected to happen?

The stack should not generate an HTTP scrape configuration for the kubelet's /metrics endpoint on port 10250, as it only supports HTTPS and authenticated access.

### Enter the changed values of values.yaml?

**.\helm\values\kube-prometheus-stack-override.yaml**
```yaml
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'kube-prometheus-stack'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels:  [__meta_kubernetes_node_name]
            target_label: hostname
    secrets: ['etcd-client-cert']

kubeControllerManager:
  enabled: true
  service:
    port: 10257
    targetPort: 10257
    selector:
      component: kube-controller-manager
  serviceMonitor:
    interval: ""
    https: true
    insecureSkipVerify: true
    metricRelabelings: []
    relabelings: []

# kubectl -n monitoring create secret generic etcd-client-cert --from-file=/etc/kubernetes/pki/etcd/ca.crt --from-file=/etc/kubernetes/pki/etcd/healthcheck-client.crt --from-file=/etc/kubernetes/pki/etcd/healthcheck-client.key because etcd works with mTLS
kubeEtcd:
  enabled: true
  service:
    port: 2379
    targetPort: 2379
    selector:
      component: etcd
  serviceMonitor:
    interval: ""
    scheme: https
    insecureSkipVerify: false
    serverName: "localhost"
    caFile: "/etc/prometheus/secrets/etcd-client-cert/ca.crt"
    certFile: "/etc/prometheus/secrets/etcd-client-cert/healthcheck-client.crt"
    keyFile: "/etc/prometheus/secrets/etcd-client-cert/healthcheck-client.key"
    metricRelabelings: []
    relabelings: []

kubeScheduler:
  enabled: true
  service:
    port: 10259
    targetPort: 10259
    selector:
      component: kube-scheduler
  serviceMonitor:
    interval: ""
    https: true
    insecureSkipVerify: true
    metricRelabelings: []
    relabelings: []

kubeProxy:
  enabled: true
  service:
    port: 10249
    targetPort: 10249
    selector:
      k8s-app: kube-proxy
  serviceMonitor:
    interval: ""
    https: false
    metricRelabelings: []
    relabelings: []

# prometheusOperator: 
#   enabled: true
#   service:
#     selector:
#       app.kubernetes.io/managed-by: prometheus-operator
#       k8s-app: kubelet
#   serviceMonitor:
#     interval: ""
#     https: false
#     metricRelabelings: []
#     relabelings: []
grafana:
  serviceMonitor:
    enabled: true

```

### Enter the command that you execute and failing/misfunctioning.

helm install kube-prometheus-stack ./helm/charts/kube-prometheus-stack -f .\helm\values\kube-prometheus-stack-override.yaml  -n monitoring
