### ISSUE TITLE
[prometheus-alertmanager] Default behaviour broken after PR5635

### ISSUE THREAD

**Issue by lisenet** [prometheus-community/helm-charts#5687]
### Describe the bug a clear and concise description of what the bug is.

Default behaviour of Alertmanager looks broken after the merge of [PR5635](https://github.com/prometheus-community/helm-charts/pull/5635). Chart can no longer be deployed successfully using provided `values.yaml` file.

### What's your helm version?

3.17.2

### What's your kubectl version?

v1.32.2

### Which chart?

prometheus-alertmanager

### What's the chart version?

1.18.0

## Behaviour before PR5635 (Not Broken)

Using `prometheus-helm-27.13.0` chart (which locks Alertmanager chart to `1.17.2`)  to deploy the stack results in this **valid** Alertmanager YAML code snippet:

```
      containers:
        - name: alertmanager-configmap-reload
          image: quay.io/prometheus-operator/prometheus-config-reloader:v0.82.1
          args:
            - '--watched-dir=/etc/alertmanager'
            - '--reload-url=http://127.0.0.1:9093/-/reload'
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
```

Do note that neither `livenessProbe` nor `readinessProbe` are defined. This chart works.

## Behaviour after PR5635 (Broken)

Using `prometheus-helm-27.14.0` chart (which locks Alertmanager chart to `1.18.0`)  to deploy the stack results in this **invalid** Alertmanager YAML code snippet:

```
      containers:
        - name: alertmanager-configmap-reload
          image: quay.io/prometheus-operator/prometheus-config-reloader:v0.82.1
          args:
            - '--watched-dir=/etc/alertmanager'
            - '--reload-url=http://127.0.0.1:9093/-/reload'
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
          livenessProbe:
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
```

Do note that `livenessProbe` and `readinessProbe` are defined but are not valid. This results in the following error:

```
create Pod prometheus-alertmanager-0 in StatefulSet prometheus-alertmanager failed error: Pod "prometheus-alertmanager-0" is invalid: [spec.containers[0].livenessProbe: Required value: must specify a handler type, spec.containers[0].readinessProbe: Required value: must specify a handler type]
```

### What you expected to happen?

Expected to have a non-broken deployment.

### How to reproduce it?

Deploy `prometheus-helm-27.14.0` with Alertmanager enabled and default `values.yaml` file.

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

```bash
helm upgrade \
  --install prometheus \
  prometheus-community/prometheus \
  --namespace monitoring \
  --set alertmanager.enabled=true \
  --set alertmanager.configmapReload.enabled=true \
  --version "27.14.0"
```

**Comment by greninja517** [comment]
Hi @lisenet,
I don't think it is actually a bug. You probably have enabled the configmapReload option and not set any of the values for that configmap-reload container. As seen in your output, all the values are taking the default values so liveness and readiness probes are improperly set which are causing the issue during the pod deployment. You need to provide all these values for `confimapReload` object through a separate values.yaml file or edit that existing values.yaml file while installing the chart:
```yaml
configmapReload:
  ## If false, the configmap-reload container will not be deployed
  ##
  enabled: false

  ## configmap-reload container name
  ##
  name: configmap-reload

  ## configmap-reload container image
  ##
  image:
    repository: quay.io/prometheus-operator/prometheus-config-reloader
    tag: v0.82.2
    pullPolicy: IfNotPresent

  # containerPort: 9533

  ## configmap-reload resource requests and limits
  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}

  livenessProbe: {}
    # httpGet:
    #   path: /healthz
    #   port: 8080
    #   scheme: HTTP
  readinessProbe: {}
    # httpGet:
    #   path: /healthz
    #   port: 8080
    #   scheme: HTTP

  extraArgs: {}

  ## Optionally specify extra list of additional volumeMounts
  extraVolumeMounts: []
    # - name: extras
    #   mountPath: /usr/share/extras
    #   readOnly: true

  ## Optionally specify extra environment variables to add to alertmanager container
  extraEnv: []
    # - name: FOO
    #   value: BAR

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsUser: 65534
    # runAsNonRoot: true
    # runAsGroup: 65534
```
Hope ! This helps. Thank You

**Comment by lisenet** [comment]
How to replicate using default config provided on GitHub (no changes to `values.yaml` whatsoever). 

Version `27.13.0` of the chart works (which locks Alertmanager to `1.17.2`):

```bash
helm upgrade \
  --install prometheus \
  prometheus-community/prometheus \
  --namespace monitoring \
  --set alertmanager.enabled=true \
  --set alertmanager.configmapReload.enabled=true \
  --version "27.13.0"
```

Version `27.14.0` of the chart (which locks Alertmanager to `1.18.0`) seems to generates invalid config:

```bash
helm upgrade \
  --install prometheus \
  prometheus-community/prometheus \
  --namespace monitoring \
  --set alertmanager.enabled=true \
  --set alertmanager.configmapReload.enabled=true \
  --version "27.14.0"
```

Snippet of the config that is failing:

```
      containers:
        - name: alertmanager-configmap-reload
          image: quay.io/prometheus-operator/prometheus-config-reloader:v0.82.1
          args:
            - '--watched-dir=/etc/alertmanager'
            - '--reload-url=http://127.0.0.1:9093/-/reload'
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
          livenessProbe:
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
```

**Comment by mkilchhofer** [comment]
> @lisenet Both livenessProbe and readinessProbe are declared as empty objects {}, but Kubernetes requires at least one handler field inside these probes.

It only requires if the block is not `{}`.
From the rendered values above, **you** somewhere define the four attributes per probe:
```yaml
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
```

Also the prometheus Helm chart you are using (https://github.com/prometheus-community/helm-charts/blob/a80cc01d4c7124f5e3845508c73c214357beea45/charts/prometheus/Chart.yaml#L5) does not define those keys.
Here are the only set keys related to the `alertmanager` subchart in the `prometheus` chart:
https://github.com/prometheus-community/helm-charts/blob/a80cc01d4c7124f5e3845508c73c214357beea45/charts/prometheus/values.yaml#L1317-L1329

Maybe you can share a `helm get values prometheus` from your installation?
_But please make sure you don't paste potential sensitive/internal data (please review it carefully before pasting)._
