### ISSUE TITLE
[kube-prometheus-stack] enableOTLPReceiver is not passed through to the CRD

### ISSUE THREAD

**Issue by KarstenB** [prometheus-community/helm-charts#5689]
### Is your feature request related to a problem ?

There is now a enableOTLPReceiver field in the Prometheus CRD, but the kube-prometheus-stack doesn't pass that through unfortunately.

### Describe the solution you'd like.

Pass 
```yaml
prometheus:
  prometheusSpec:
    enableOTLPReceiver: true
```
down to the Prometheus CRD

### Describe alternatives you've considered.
This works, but I don't see why a supported flag in the CRD should not be passed through.

```yaml
prometheus:
  prometheusSpec:
    additionalArgs:
     # This is a workaround for the enableOTLPReceiver: true line which would actually be supported in the prometheus spec
      - name: "web.enable-otlp-receiver"
```

**Comment by Mason0920** [comment]
I need this feature too.

**Comment by dprotaso** [comment]
I notice this error now 

```yaml
  - lastTransitionTime: "2025-06-19T02:18:08Z"
      message: 'making statefulset failed: make StatefulSet spec: can''t set arguments
        which are already managed by the operator: web.enable-otlp-receiver'
```
