### ISSUE TITLE
[prometheus-kube-stack] Adapter unexpected high cpu usage

### ISSUE THREAD

**Issue by Syntax3rror404** [prometheus-community/helm-charts#5747]
### Describe the bug a clear and concise description of what the bug is.

I use the prom stack with its default values at the latest version.

Without any reason the adapter pod gets unexpected extreme high CPU usages, which are so extreme, that the CPU temps are also affected by this.

In this picture you can see the cpu usage about 170% from the adapter container
![Image](https://github.com/user-attachments/assets/d9672fae-f8ac-40fb-ad9e-233902b940d8)

Here you can see, that this spike also affects the temperature significantly

![Image](https://github.com/user-attachments/assets/fff57b2a-163a-4e60-a800-65715aabe9fe)

The scrap time is set to 60s default is 30s

Is this normal and expected? Or is this a bug? 

### What's your helm version?

v3.17.2

### What's your kubectl version?

Client Version: v1.32.3 Kustomize Version: v5.5.0 Server Version: v1.32.4

### Which chart?

[rancher-monitoring
](https://github.com/rancher/charts/tree/dev-v2.11/charts/rancher-monitoring/106.1.1%2Bup69.8.2-rancher.5)
### What's the chart version?

106.1.1+up69.8.2-rancher.5

### What you expected to happen?

Normal ressource usage 

### How to reproduce it?

Install prom stack and monitore the adapter pod

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

Installed by fluxcd

**Comment by Syntax3rror404** [comment]
Ping

**Comment by Syntax3rror404** [comment]
Ping

**Comment by amamir14** [comment]
@Syntax3rror404 did you find any solution for this?

**Comment by abdullahsumsum** [comment]
Any updates here?

**Comment by Syntax3rror404** [comment]
> [@Syntax3rror404](https://github.com/Syntax3rror404) did you find any solution for this?

Everything i've tryed does not solve this issue :/

**Comment by azertyfun** [comment]
Our workaround was to redeploy the same rules EXCEPT the rules which use the `name!=XXX` pattern. Since we don't yet use any HPAs that's basically a free win. If you do use HPAs, I suppose you'll have to be careful to ensure you are not removing a rule they depend on.

```yaml
prometheus-adapter:
  # cf. https://github.com/rancher/rancher/issues/30697
  rules:
    default: false
    custom:
      - seriesQuery: '{__name__=~"^container_.*",container!="POD",namespace!="",pod!=""}'
        seriesFilters: []
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: ^container_(.*)_seconds_total$
          as: ""
        metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,container!="POD"}[5m]))
          by (<<.GroupBy>>)
      - seriesQuery: '{__name__=~"^container_.*",container!="POD",namespace!="",pod!=""}'
        seriesFilters:
        - isNot: ^container_.*_seconds_total$
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: ^container_(.*)_total$
          as: ""
        metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,container!="POD"}[5m]))
          by (<<.GroupBy>>)
      - seriesQuery: '{__name__=~"^container_.*",container!="POD",namespace!="",pod!=""}'
        seriesFilters:
        - isNot: ^container_.*_total$
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: ^container_(.*)$
          as: ""
        metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>,container!="POD"}) by (<<.GroupBy>>)
```

Impact on our rancher cluster (which has very little going on!) was immediate:

<img width="1211" height="568" alt="Image" src="https://github.com/user-attachments/assets/70b9f5ae-c35c-481e-b20f-f85509e467df" />
