### ISSUE TITLE
[kube-prometheus-stack] Incorrect indentation in alertmanager.spec.storage.volumeClaimTemplate

### ISSUE THREAD

**Issue by B1F030** [prometheus-community/helm-charts#5750]
### Describe the bug a clear and concise description of what the bug is.

in values.yaml, alertmanager.spec.storage.volumeClaimTemplate is conflict with crd.
values.yaml:
```yaml
    ## Storage is the definition of how storage will be used by the Alertmanager instances.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/platform/storage.md
    ##
    storage: {}
    # volumeClaimTemplate:
    #   spec:
    #     storageClassName: gluster
    #     accessModes: ["ReadWriteOnce"]
    #     resources:
    #       requests:
    #         storage: 50Gi
    #   selector: {}
```

crd:
```yaml
volumeClaimTemplate:
  spec:
    selector:
```

```shell
$ helm install monitor --namespace monitoring -f values.yaml --version 72.6.3 prometheus-community/kube-prometheus-stack

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Alertmanager.spec.storage.volumeClaimTemplate): unknown field "selector" in com.coreos.monitoring.v1.Alertmanager.spec.storage.volumeClaimTemplate
```

### What's your helm version?

v3.16.2

### What's your kubectl version?

v1.22.15

### Which chart?

kube-prometheus-stack

### What's the chart version?

72.6.3

### What happened?

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Alertmanager.spec.storage.volumeClaimTemplate): unknown field "selector" in com.coreos.monitoring.v1.Alertmanager.spec.storage.volumeClaimTemplate
```

### What you expected to happen?

```shell
NAME: monitor
LAST DEPLOYED: Tue Jun 10 19:20:11 2025
NAMESPACE: monitoring
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
kube-prometheus-stack has been installed. Check its status by running:
  kubectl --namespace monitoring get pods -l "release=monitor"

Get Grafana 'admin' user password by running:

  kubectl --namespace monitoring get secrets monitor-grafana -o jsonpath="{.data.admin-password}" | base64 -d ; echo

Access Grafana local instance:

  export POD_NAME=$(kubectl --namespace monitoring get pod -l "app.kubernetes.io/name=grafana,app.kubernetes.io/instance=monitor" -oname)
  kubectl --namespace monitoring port-forward $POD_NAME 3000

Visit https://github.com/prometheus-operator/kube-prometheus for instructions on how to create & configure Alertmanager and Prometheus instances using the Operator.
```

### How to reproduce it?

```yaml
    ## Storage is the definition of how storage will be used by the Alertmanager instances.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/platform/storage.md
    ##
    storage: {}
      volumeClaimTemplate:
        spec:
          storageClassName: gluster
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
        selector: {}
```

### Enter the command that you execute and failing/misfunctioning.

helm install monitor --namespace monitoring -f values.yaml --version 72.6.3 prometheus-community/kube-prometheus-stack
