### ISSUE TITLE
[kube-prometheus-stack] Documentation clarification for grafana.operator settings

### ISSUE THREAD

**Issue by gwvandesteeg** [prometheus-community/helm-charts#5822]
### Describe the bug a clear and concise description of what the bug is.

Folks,

The documentation around the `grafana.operator` settings are quite unintelligible and unclear as to what is required, what it does, how it works, etc. Can someone who understands this functionality clarify in  clear grammatically correct English as to what exactly these settings do, what their intent is, how this interoperates with the grafana-operator, and what additional material we need to provide to make this interoperability work.

### What's your helm version?

N/A

### What's your kubectl version?

N/A

### Which chart?

kube-prometheus-stack

### What's the chart version?

75.4.0

### What happened?

Documentation unclear

### What you expected to happen?

Clear documentation to understand the interoperability between this chart and the grafana-operator and how the dashboards created by this chart can be deployed using the grafana-operator.

### How to reproduce it?

https://github.com/prometheus-community/helm-charts/blob/695b8e771f795ba73dffdcc75786dc8583913e16/charts/kube-prometheus-stack/values.yaml#L1233-L1278

### Enter the changed values of values.yaml?

n/a

### Enter the command that you execute and failing/misfunctioning.

n/a

**Comment by jkroepke** [comment]
Context: https://github.com/prometheus-community/helm-charts/pull/5569

@DrummyFloyd could you assist here?

**Comment by DrummyFloyd** [comment]
yes sure @jkroepke 

so @gwvandesteeg 


The [Grafana-Operator](https://github.com/grafana/grafana-operator), once installed will add some news CRDs like
- [Grafana](https://grafana.github.io/grafana-operator/docs/examples/basic/readme/)
- [GrafanaDashboard](https://grafana.github.io/grafana-operator/docs/examples/dashboard_from_configmap/readme/)
- [GrafanaDatasource](https://grafana.github.io/grafana-operator/docs/examples/datasource_types/readme/)
- and few more like `Folders/GrafanaNotificationTemplate ...`

Because some ppl do not use the Grafana from the `kube-prometheus-stack`, in that case they might use 
- dedicated [chart](https://github.com/grafana/helm-charts)  to install Grafana
- or thru' the `Grafana-operator` 

before the merge of #5569, it was complicated to use these dashboards with an operator, because you needed to referenced each `configMap` (dashboard definition ) into multiple `GrafanaDashboard` manually... which was time consuming and painful.

**eg:**

 ```yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: grafanadashboard-from-configmap
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  configMapRef:
    name: dashboard-definition
    key: json
```

so that's why i came with this merge request.


# How to use it 

when you install the `Grafana Operator`, which is not part of the `kube-prometheus-stack`,

1. you need to create a `Kind: Grafana` that will be handled by the operator

**eg:**

<details>
<summary>kind: Grafana</summary>

```yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
spec:
  config:
    log:
      mode: console
    auth:
      disable_login_form: "false"
  deployment:
    metadata:
      labels:
        grafana: home  # THIS LABELS is very important
    spec:
      strategy:
        type: Recreate
      template:
        metadata: {}
        spec:
          containers:
            - name: grafana
              resources: {}
              securityContext:
                # INFO: https://github.com/grafana/grafana-operator/issues/1439#issuecomment-2677822604
                # Customize this in case your volume provider needs specific UIDs/GIDs
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_USER
                      name: grafana-admin-credentials
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_PASSWORD
                      name: grafana-admin-credentials
              # envFrom:
              #   - secretRef:
              #       name: grafana-oidc
          # INFO: https://github.com/grafana/grafana-operator/issues/1439#issuecomment-2677822604
          securityContext:
            fsGroup: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
      # storageClassName: "" # Customize storage class if needed

  ingress:
    spec:
      ingressClassName: nginx-internal
      rules:
        - host: monitoring.lab.internal
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
```

</details>

The `spec.deployments.metadata.labels` field in the manifest above is crucial, as it serves as the `LabelsSelector` for all CRDs managed by the `grafana-operator`. 

```yaml
....
  deployment:
    metadata:
      labels:
        grafana: home
....
```

**eg:** To use all `GrafanaDashboard` resources created by `kube-prometheus-stack` with your `kind: Grafana` instance, you need to add the label `grafana: home` in your `kube-prometheus-stack` configuration. This label tells the operator which specific Grafana instance should receive the dashboards.

```yaml
grafana:
  enabled: false
  forceDeployDashboards: true
  defaultDashboardsEnabled: true
  operator:
    dashboardsConfigMapRefEnabled: true
    matchLabels: 
		grafana: home
```

**NB:** you may need to set also manually some `GrafanaDatasource`(prometheus & alertmanager), because i didn't had time to make a new PR for this.

```yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      grafana: home
  datasource:
    name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-operated.prometheus-stack.svc.cluster.local:9090
    isDefault: true
    jsonData:
      "tlsSkipVerify": true
      "timeInterval": "5s"
    editable: true
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      grafana: home
  datasource:
    name: alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager-operated.prometheus-stack.svc.cluster.local:9093
    jsonData:
      "tlsSkipVerify": true
      "implementation": prometheus
      "handleGrafanaManagedAlerts": true
    editable: false
```

Do not hesitate to read a bit more the documenation about `Grafana-operator` [here](https://grafana.github.io/grafana-operator/docs/quick-start/)
