### ISSUE TITLE
In all pvc.yml add support for selector.matchLabels

### ISSUE THREAD

**Issue by rgstephens** [prometheus-community/helm-charts#602]
Would like to specify a selector for PersistentVolumeClaims. This would be useful to support attaching to a specific `local-storage` volume.

```yml
spec:
  selector:
    matchLabels:
      directory: 5TB-drive
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
  resources:
    requests:
      storage: "8Gi"
```

**Is your feature request related to a problem? Please describe.**
I want to use a specific `local-storage` volume

**Describe the solution you'd like**
Would like the pvc.yml charts to add support for `selector:` so that I could specify the following:

```yml
    selector:
      matchLabels:
        directory: 5TB-drive
```

**Describe alternatives you've considered**
Use the `existingClaim:` already supported by this chart.

I'd like to contribute the PR for this enhancement request if it is accepted.
