### ISSUE TITLE
[prometheus-operator] additionalScrapeConfigs query

### ISSUE THREAD

**Issue by KR411-prog** [prometheus-community/helm-charts#62]
I am trying to add a new label called "teamname" to the metrics scraped on kube-state-metrics.So my objective is to add teamname as an additional label to the metrics scraped at kube-state-metrics so in the PrometheusRule we can set the specific team name on the label.
So tried with the below config.But I dont see this new label being added to the kube-state-metrics in Prometheus Service Discovery page.Please let me know whats the correct method to do this.
Objective: is to add new label named "teamname" so based upon the metrics,the team name can  be set.

prometheus:
prometheusSpec:
additionalScrapeConfigs:
- job_name: kube-state-metrics
relabel_configs:
- separator: ;
regex: (.*)
target_label: teamname
replacement: "myteam"
action: replace

Prometheus Operator chart version: 9.3.1

Insert image tag or Git SHA here

quay.io/coreos/prometheus-operator:v0.38.1

Kubernetes version information:

kubectl version 1.15

Kubernetes cluster kind: EKS

**Comment by KR411-prog** [comment]
I tried below and it works now ...

```
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: kube-state-metrics
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - monitoring
      relabel_configs:
      - separator: ;
        regex: (.*)
        target_label: teamname
        replacement: "myteam"
        action: replace

 
```

<img width="1769" alt="image" src="https://user-images.githubusercontent.com/14121261/92413022-181d7100-f103-11ea-81c0-f05044a9dc90.png">
