### ISSUE TITLE
[prometheus-kube-stack] smtp_require_tls: false is ignored in alertmanager config

### ISSUE THREAD

**Issue by sebv7** [prometheus-community/helm-charts#623]
**Describe the bug**
Alertmanager deployed with 12.10.4 will ignore the "smtp_require_tls: false" option and therefor not send out any alarms anymore.
The alertmanager log reports: err="send STARTTLS command: x509: certificate is valid for a.xyz.org, b.xyz.org, not mailhost.xyz.org"

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-08-04T12:00:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kube-prometheus-stack

**Which version of the chart**:
12.10.4 and higher

**What happened**:
I updated the chart to version 12.10.4 with the following configuration:

```
alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'mailhost.xyz.org:25'
      smtp_from: 'k8s-{{ .Environment.Name }}@xyz.org'
      smtp_require_tls: false
```

On the alertmanager website the config is displayed with smtp_require_tls: true
The secrets are populated correctly though (with smtp_require_tls: false).

**What you expected to happen**:
I would expect the config being applied as configured in the values.yaml and to be shown correctly on the alertmanagers website. 

**How to reproduce it** (as minimally and precisely as possible):

1. Install the helm chart with smtp_require_tls: false
2. Check if alertmanager secrets are populated with the right config value
3. Check the config on the alertmanagers website
4. Send test alarm (not working anymore)
5. Check the alertmanager logs for: err="send STARTTLS command: x509: certificate is valid for a.xyz.org, b.xyz.org, not mailhost.xyz.org"

**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
smtp_require_tls: false
```

**The helm command that you execute and failing/misfunctioning**:
n/a

**Helm values set after installation/upgrade:**
n/a

**Anything else we need to know**:
n/a

**Comment by juanvasquezreyes** [comment]
I'm facing the same issue, were you able to fix that?

**Comment by cyperplex** [comment]
I am also experiencing this issue, any update? or advise.

**Comment by juanvasquezreyes** [comment]
I think I was able to fix it, with the following
```
config:
      global:
        resolve_timeout: 5m
        smtp_smarthost: 'xxx:25'
        smtp_from: 'xxx'
        smtp_require_tls: false
      route:
        group_by: ['job']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'devops'
        routes:
        - match:
            cluster: "test"
          receiver: 'test'
        - match:
            severity: "critical"
          receiver: 'test'
      receivers:
      - name: 'test'
        email_configs:
        - to: 'xxx@test.com'
          **require_tls**: false
      - name: 'test2'
        email_configs:
        - to: 'xxx@test.com'
          **require_tls**: false
```
