### ISSUE TITLE
[kube-prometheus-stack] Merge podAntiAffinity

### ISSUE THREAD

**Issue by derekperkins** [prometheus-community/helm-charts#633]
In the values.yaml, you are able to set the `affinity` block in addition to a specific `podAntiAffinity` field. It isn't clear that if you set any `podAntiAffinity` in the open `affinity` field, it will be clobbered if you choose `hard` or `soft`. If I set `podAntiAffinity: ""`, then my custom settings are preserved. Would it be possible to merge the `podAntiAffinity` rather than overwriting it?

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L196-L217

#### Example that gets clobbered

```yaml
    ## Pod anti-affinity can prevent the scheduler from placing Prometheus replicas on the same node.
    ## The default value "soft" means that the scheduler should *prefer* to not schedule two replica pods onto the same node but no guarantee is provided.
    ## The value "hard" means that the scheduler is *required* to not schedule two replica pods onto the same node.
    ## The value "" will disable pod anti-affinity so that no anti-affinity rules will be configured.
    podAntiAffinity: "hard"

    ## If anti-affinity is enabled sets the topologyKey to use for anti-affinity.
    ## This can be changed to, for example, failure-domain.beta.kubernetes.io/zone
    ##
    podAntiAffinityTopologyKey: kubernetes.io/hostname

    ## Assign custom affinity rules to the prometheus instance
    ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
    ##
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              memory: xl
```
