### ISSUE TITLE
[prometheus] Adding relabel_configs breaks monitoring 

### ISSUE THREAD

**Issue by aorfanos** [prometheus-community/helm-charts#669]
**Describe the bug**

I'm trying to drop some metrics from Prometheus at scrape time. From inspecting `helm show values prometheus-community/prometheus` I understand that to accomplish that, I need the following in `values.yml`:

```yaml
serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: kubernetes-node-cadvisor
        relabel_configs:
          - source_labels: [ __name__ ]
            regex: "^container.*"
            action: drop
```

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
v3.3.1
```

Kubernetes Version:

```console
$ kubectl version
v1.17.14
```

**Which chart**: `prometheus-community/prometheus`

**Which version of the chart**: 13.2.1

**What happened**: Kubernetes metrics stopped flowing in Grafana.

**What you expected to happen**: All other metrics other than the ones starting with `container` should appear.

**How to reproduce it** (as minimally and precisely as possible): Use the Chart with the supplied values.

**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
server:
  name: "staging-server"
  global:
    external_labels:
      environment: staging
  remoteWrite:
    - url: http://aremotewriteurl.com
  retention: "24h"

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: kubernetes-node-cadvisor
        relabel_configs:
          - source_labels: [ __name__ ]
            regex: "^container.*"
            action: drop

alertmanager:
  enabled: false
```

**The helm command that you execute and failing/misfunctioning**:

I am installing and upgrading through Terraform's `helm_release` module.

**Helm values set after installation/upgrade:**

```console
USER-SUPPLIED VALUES:
alertmanager:
  enabled: false
server:
  global:
    external_labels:
      environment: staging
  name: staging-server
  remoteWrite:
  - url: http://aremotewriteurl.com
  retention: 24h
serverFiles:
  prometheus.yml:
    scrape_configs:
    - job_name: kubernetes-node-cadvisor
      relabel_configs:
      - action: drop
        regex: ^container.*
        source_labels:
        - __name__
```
