### ISSUE TITLE
[prometheus-kube-stack] can not disable default Rules for controller manager

### ISSUE THREAD

**Issue by slukianets** [prometheus-community/helm-charts#674]
**Description**
When you run your kubernetes cluster in some cloud, you do not have access to control panale. And when your installing kube-prometheus-stack, alerts about API server, Scheduler and Controller Manager are always in firing status. I can disable setting rules for API and Scheduler using following varilable from the file helm-charts/charts/kube-prometheus-stack/values.yaml:

```defaultRules:
  create: true
  rules:
    ...
    kubeApiserver: false
    kubeApiserverAvailability: false
    kubeApiserverError: false
    kubeApiserverSlos: false
    ...
    kubeScheduler: false
    ...
 ```
But rule for Controller Manager is missed in this list. Also I tries to set variale .Values.kubeControllerManager.enabled to ```null``` from the file helm-charts/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml, it did not help. Workarount for it is sending notification about this rule 'KubeControllerManagerDown' to null receiver.

**Version of Helm and Kubernetes**:
Kubernetes 1.16+
Helm 3+

**Which chart**:
helm-charts/charts/kube-prometheus-stack/

**What happened**:
Alert about Controller Manager always present in Promethues Alerts and firing.

**What you expected to happen**:
Add variable ```.Values.defaultRules.rules.kubeControllerManager``` to the file helm-charts/charts/kube-prometheus-stack/values.yaml with default value ```true```, like part of section:
```
defaultRules:
  create: true
  rules:
    kubeControllerManager: true
.........

```
Also add variable ```.Values.defaultRules.rules.kubeControllerManager``` to the file helm-charts/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml for disabling this rule for installing with prometheus-kube-stack to part of code:
```
....

{{- $kubeTargetVersion := default .Capabilities.KubeVersion.GitVersion .Values.kubeTargetVersionOverride }}
{{- if and (semverCompare ">=1.14.0-0" $kubeTargetVersion) (semverCompare "<9.9.9-9" $kubeTargetVersion) .Values.defaultRules.create .Values.kubeControllerManager.enabled .Values.defaultRules.rules.kubeControllerManager }}
apiVersion: monitoring.coreos.com/v1
....
```

**Comment by KlavsKlavsen** [comment]
I am having this same problem. except on KOPS configured cluster on ec2 instances.. I have no failed jobs - so no scraping job of kube-controller-manager.. and yet I have an alert expecting that job to be there :(

**Comment by KlavsKlavsen** [comment]
kube-controller-manager does not seem to be a standard service one would have running on a k8scluster? so why have it enabled by default at all?

**Comment by KlavsKlavsen** [comment]
It seems its core part of k8s and from 1.18 listens also on port 10257 with TLS (previously 10252 http only) and PR #490 enables this. Its still odd that this alert kube-controller-manager is enabled by default, but the scrape job is not.. (me goes digging).

**Comment by KlavsKlavsen** [comment]
I found that scrape job looks for different service label than I had with kops 1.18.. (not EKS/GKE though) - for me I could fix it by pointing to correct servicelabels by setting this:
```
   kubeControllerManager:
    service:
      selector:
        k8s-app: kube-controller-manager
```
as I HAVE that service running ofcourse - that might not? be exposed on EKS/GKE - haven't tested.

**Comment by meni2029** [comment]
We have the same request. We would like to disable setting rule `kubernetes-system-controller-manager`, as we can do for `kube-scheduler.rules` . @slukianets's proposition is just what we would need.

**Comment by demisx** [comment]
Same problem with EKS Kubernetes v1.21. Please reopen this issue.

**Comment by roberto-civitas** [comment]
same issue here, with EKS as well

**Comment by eric-kinsa** [comment]
I was able to disable the alerts that couldnt be reached on my EKS cluster following the advice from this issue:

https://github.com/prometheus-community/helm-charts/issues/1618#issuecomment-1082713258

```
defaultRules:
  rules:
    kubeScheduler: false

kubeProxy:
  enabled: true
  service:
    enabled: true
    selector:
      component: kube-proxy

kubeControllerManager:
  enabled: false
  service:
    enabled: false
  serviceMonitor:
    enabled: false

kubeScheduler:
  enabled: false
  service:
    enabled: false
  serviceMonitor:
    enabled: false
```

**Comment by prashantkalkar** [comment]
I was able to get it working for kubeControllerManager and kubeProxy, with following configuration: 

```
kubeControllerManager:
   enabled: false
   service: 
     enabled: true
     selector: 
       # make sure controller pod labels are added here
       k8s-app : kube-controller-manager 
   
kubeProxy:
  enabled: true
  service:
    enabled: true
    selector:
      k8s-app: kube-proxy
```
The kube-proxy configuration is same as mentioned by @eric-kinsa . 
Apart from above configuration I also had to ensure that metric bind address is configured for kube-proxy pods as  
`--metrics-bind-address=0.0.0.0:10249`

Unfortunately, I was not able to get the kubeScheduler working. So it might have to be disabled as mentioned in previous comment.
