### ISSUE TITLE
prometheus-kube-stack servicemonitor issue

### ISSUE THREAD

**Issue by amin224** [prometheus-community/helm-charts#678]
**Describe the bug**
When installing the prometheus rabbitmq exporter helm chart it is not creating a servicemonitor resource so that it connects to my prometheus cluster.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

Kubernetes Version:

```console
$ kubectl version --short
Client Version: v1.19.4
Server Version: v1.18.9-eks-d1
```

**Which chart**:
prometheus-rabbitmq-exporter

**Which version of the chart**:
prometheus-rabbitmq-exporter-0.6.0
appVersion: v0.29.0

**What happened**:
I am installing the helm chart while changing the default configuration using
helm install -f values.yml rabbitmq-exporter prometheus-community/prometheus-rabbitmq-exporter

```
kubectl get all
NAME                                                                 READY   STATUS    RESTARTS   AGE
pod/rabbitmq-exporter-prometheus-rabbitmq-exporter-c8495-2b7   1/1     Running   0          17m

NAME                                                     TYPE           CLUSTER-IP      EXTERNAL-IP                                                               PORT(S)                                                         AGE
service/rabbitmq-exporter-prometheus-rabbitmq-exporter   ClusterIP      10.10.19.8   <none>                                                                    9419/TCP                                                        17m

NAME                                                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/rabbitmq-exporter-prometheus-rabbitmq-exporter   1/1     1            1           17m

NAME                                                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/rabbitmq-exporter-prometheus-rabbitmq-exporter-c85687495   1         1         1       17m
```
```
kubectl get servicemonitors.monitoring.coreos.com 
No resources found in default namespace.
```

**What you expected to happen**:

I expected the helm chart to install 3 components in my cluster, which are the pod, service and servicemonitor. The rabbitmq exporter pod and service were installed successfully but the servicemonitor was not installed which prevents the rabbitmq exporter to connect to my prometheus targets.

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):

values.yml (Changes only):

```
loglevel: info
rabbitmq:
  url: {URL for rabbitmq}
  user: {username}
  password: {password}
  # If existingPasswordSecret is set then password is ignored
  existingPasswordSecret: ~
  capabilities: bert,no_sort
  include_queues: ".*"
  include_vhost: ".*"
  skip_queues: "^$"
  skip_verify: "false"
  skip_vhost: "^$"
  exporters: "exchange,node,overview,queue"
  output_format: "TTY"
  timeout: 30
  max_queues: 0

prometheus:
  monitor:
    enabled: false
    additionalLabels:
      release: prometheus
    interval: 15s
    namespace: []
  rules:
    enabled: false
    additionalLabels: {}
```

In addition, I also tried to put an extra parameter like the one used in mongodb exporter but did not work.

```
serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  namespace:
  additionalLabels:
      release: prometheus
  targetLabels: []
  metricRelabelings: []
```

**The helm command that you execute and failing/misfunctioning**:
helm install -f values.yml rabbitmq-exporter prometheus-community/prometheus-rabbitmq-exporter

**Helm values set after installation/upgrade:**
helm get values my-release
```console

USER-SUPPLIED VALUES:
affinity: {}
annotations: {}
image:
  pullPolicy: IfNotPresent
  repository: kbudde/rabbitmq-exporter
  tag: v0.29.0
loglevel: info
nodeSelector: {}
priorityClassName: ""
prometheus:
  monitor:
    additionalLabels:
      release: prometheus
    enabled: false
    interval: 15s
    namespace: []
  rules:
    additionalLabels: {}
    enabled: false
rabbitmq:
  capabilities: bert,no_sort
  existingPasswordSecret: null
  exporters: exchange,node,overview,queue
  include_queues: .*
  include_vhost: .*
  max_queues: 0
  output_format: TTY
  password: {password}
  skip_queues: ^$
  skip_verify: "false"
  skip_vhost: ^$
  timeout: 30
  url: {URL}
  user: {username}
replicaCount: 1
resources: {}
service:
  externalPort: 9419
  internalPort: 9419
  type: ClusterIP
tolerations: []

```

**Anything else we need to know**:
While reading tutorials and documentation I was told that exporters should have service monitors with label release: prometheus in order for the exporter to be able to connect to prometheus server and scrap the /metrics endpoint from the application.

**Comment by amin224** [comment]
I manually created a servicemonitor resource for the rabbitmq-exporter and it got registered in the prometheus target but cannot find endpoints for the service and pod of the exporter. I tried fixing the selector labels to match the servicemonitor but it still couldnt find an endpoint.

servicemonitor.yml:
```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: prometheus-kube-prometheus-rabbitmq-exporter
  namespace: default
spec:
  endpoints:
    - interval: 30s
      port: mqex
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: prometheus-rabbitmq-exporter
      app.kubernetes.io/managed-by: Helm
      heritage: Helm
      chart: prometheus-rabbitmq-exporter-0.6.0
```
