### ISSUE TITLE
thanos-sidecar not installed issue title

### ISSUE THREAD

**Issue by modevops** [prometheus-community/helm-charts#684]
**Describe the bug**
thanos sidecar not installhlem 
**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"

```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kube-prometheus-stack
**Which version of the chart**:
13.7.2
**What happened**:
thanos-sidecar installed
**What you expected to happen**:
thanos sidecar installed
**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
key: value
```

**The helm command that you execute and failing/misfunctioning**:

For example:

```console
helm install my-release prometheus-community/name-of-chart --version version --values values.yaml
```

**Helm values set after installation/upgrade:**

```console
helm get values my-release
```

**Anything else we need to know**:
you need to improve your helm documentation

**Comment by NadavkOptimalQ** [comment]
I am facing the same issue.
Did you manage to resolve this? If so do you mind sharing your values.yaml?

**Comment by saikatharryc** [comment]
even i'm facing this issue, dont see the the thanos sidecar running,
`values.yaml`

```yaml
grafana:
    enabled: false
  kubeStateMetrics:
    enabled: false
  kube-state-metrics:
    namespaceOverride: ""
    rbac:
      create: false
    podSecurityPolicy:
      enabled: false
  nodeExporter:
    enabled: false
  prometheus:
    thanosService:
      enabled: true
    thanos:
      image: quay.io/thanos/thanos:v0.17.1
      version: v0.17.1
      objectStorageConfig: 
        name: thanos
        key: object-store.yaml

```
