### ISSUE TITLE
[kube-prometheus-stack] Grafana is not activating new dashboards until pod is restarted

### ISSUE THREAD

**Issue by omerfsen** [prometheus-community/helm-charts#710]
**Describe the bug**

When we install kube-prometheus-stack it uses  grafana chart version 6.1.X with at Chart.yaml

```yaml
dependencies:
- name: kube-state-metrics
  version: "2.9.*"
  repository: https://kubernetes.github.io/kube-state-metrics
  condition: kubeStateMetrics.enabled
- name: prometheus-node-exporter
  version: "1.12.*"
  repository: https://prometheus-community.github.io/helm-charts
  condition: nodeExporter.enabled
- name: grafana
  version: "6.1.*"
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled
```
There is an issue with kiwi sidecar with version 1.1.0 which is used in latest patch version of grafana helm chart (6.1.17)

```yaml
Containers:
  grafana-sc-dashboard:
    Container ID:   docker://34b28f63582fc6cbc1b483e1689159c54229b6d57e79f246e18adfb973ad7546
    Image:          kiwigrid/k8s-sidecar:1.1.0
```

```bash
https://github.com/grafana/helm-charts/blob/grafana-6.1.17/charts/grafana/values.yaml#L553
```

Issue is detailed here https://github.com/helm/charts/issues/20476 and fixed with 1.3.0 version of kiwigrid/k8s-sidecar. Commit is at 
```bash
https://github.com/kiwigrid/k8s-sidecar/commit/b85e5a95140a895da8092684f921ac654e4c707b
```
So to have upgrade this k8s-sidecar by upgrading grafana helm chart to have newer kiwigrid/k8s-sidecar version. Grafana helm chart 6.4.4 (latest one) has 1.10.3 version of k8s-sidecar 

https://github.com/grafana/helm-charts/blob/grafana-6.4.4/charts/grafana/values.yaml#L566

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
please put the output of it here
```

Kubernetes Version:

```console
$ kubectl version
please put the output of it here
```

**Which chart**:

**Which version of the chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
key: value
```

**The helm command that you execute and failing/misfunctioning**:

For example:

```console
helm install my-release prometheus-community/name-of-chart --version version --values values.yaml
```

**Helm values set after installation/upgrade:**

```console
helm get values my-release
```

**Anything else we need to know**:
