### ISSUE TITLE
[prometheus] extraScrapeConfigs not loaded and double || 

### ISSUE THREAD

**Issue by survivant** [prometheus-community/helm-charts#720]
helm version: 
````
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
````

I'm using this chart
````
  - name: prometheus
    version: 13.4.0
    repository: "@prometheus-community"
````

I have this in values.yaml

````
prometheus:
   serverFiles:
    prometheus.yml:
      rule_files:
        - /etc/config/recording_rules.yml
        - /etc/config/alerting_rules.yml
        ## Below two files are DEPRECATED will be removed from this default values file
        - /etc/config/rules
        - /etc/config/alerts
        - /etc/config/custom-rules/*.yaml
        - /etc/config/custom-alerts/*.yaml

    extraScrapeConfigs: |
     - job_name: 'prometheus-blackbox-exporter'
       metrics_path: /probe
       params:
         module: [http_2xx]
       static_configs:
         - targets:
           - https://example.com
       relabel_configs:
         - source_labels: [__address__]
           target_label: __param_target
         - source_labels: [__param_target]
           target_label: instance
         - target_label: __address__
           replacement: prometheus-blackbox-exporter:9115  
   
````

the output is this

````
# Source: monitoring-stack/charts/prometheus/templates/server/cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: "server"
    app: prometheus
    release: monitor
    chart: prometheus-13.3.1
    heritage: Helm
  name: prometheus-server
  namespace: metrics
data:
  alerting_rules.yml: |
    {}
  alerts: |
    {}
  extraScrapeConfigs: |
    |
      - job_name: 'prometheus-blackbox-exporter'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - https://example.com
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: prometheus-blackbox-exporter:9115
  prometheus.yml: |
    global:
....

````

the extra scrape config are not loaded when I go in : http://10.1.7.114:30004/config   (using nodePort)

**Comment by monotek** [comment]
Works for me with blackbox exporter:

```
    extraScrapeConfigs: |
      - job_name: 'prometheus-blackbox-exporter'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - https://www.google.com
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: prometheus-blackbox-exporter.monitoring:9115
```

You have a "|" to much in your config.

**Comment by survivant** [comment]
In the result there is 2 || that is the problem.  I my values.yaml file there only one |

````
prometheus:
   serverFiles:
    prometheus.yml:
      rule_files:
        - /etc/config/recording_rules.yml
        - /etc/config/alerting_rules.yml
        ## Below two files are DEPRECATED will be removed from this default values file
        - /etc/config/rules
        - /etc/config/alerts
        - /etc/config/custom-rules/*.yaml
        - /etc/config/custom-alerts/*.yaml

    extraScrapeConfigs: |
     - job_name: 'prometheus-blackbox-exporter'
       metrics_path: /probe
       params:
         module: [http_2xx]
       static_configs:
         - targets:
           - https://example.com
       relabel_configs:
         - source_labels: [__address__]
           target_label: __param_target
         - source_labels: [__param_target]
           target_label: instance
         - target_label: __address__
           replacement: prometheus-blackbox-exporter:9115
````

what is the values.yaml that you tried ?  I want to test it locally.. I don't think it's a bug on Windows.. never know.

but I didn't put 2|| in my input.. but the output contains 2.. that's the error on my side.
