### ISSUE TITLE
[prometheus-kube-stack] Service definition not matching pod labels with kops 1.18

### ISSUE THREAD

**Issue by KlavsKlavsen** [prometheus-community/helm-charts#731]
I had opened https://github.com/prometheus-operator/kube-prometheus/issues/1006 - but it turned out that the issue was that the service selector label (component: kube-scheduler) - did NOT match the actual labels on Pod (by kops 1.18) - which was k8s-app: kube-scheduler and k8s-app: kube-controller-manager respectively.

I understand this has been changed in kops 1.19 to: app.kubernetes.io/name: kube-scheduler
So perhaps a parameter setting the selector name for helm chart would be of use ?

**Comment by KlavsKlavsen** [comment]
I am currently overriding this with:
```
   kubeControllerManager:
    service:
      selector:
        k8s-app: kube-controller-manager
   kubeScheduler:
    service:
      selector:
        k8s-app: kube-scheduler
  ```
  to work with kops 1.18 deployment.
