### ISSUE TITLE
[prometheus-blackbox-exporter] prometheus-blackbox-exporter is Firing false positive alerts

### ISSUE THREAD

**Issue by jorotg** [prometheus-community/helm-charts#735]
Description:
prometheus-blackbox-exporter is Firing false positive alerts
**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"dirty", GoVersion:"go1.15.6"}
```

Kubernetes Version:

```console
$ kubectl version
1.18.9
```

**Which chart**:
prometheus-community/charts/prometheus
prometheus-blackbox-exporter

**Which version of the chart**:
prometheus-community/charts/prometheus - 13.4.0
prometheus-blackbox-exporter - 4.10.3

**What happened**:
We have set up full Prometheus stack - Prometheus/Grafana/Alertmanager/Node Explorer/Blackbox exporter using community helm charts in our Kubernetes cluster. Monitoring stack is deployed in its own namespace and our main software, comprised of microservices is deployed in the default namespace. Alerting is operating fine however blackbox exporter is not scraping correctly metrics (I guess) and FIRING regularly false positive alerts. We use the last for probing our microservices HTTP liveness/readiness endpoints.

My configuration (in values.yaml) related to the issue looks like:

```
- alert: InstanceDown
           expr: up == 0
           for: 5m
           annotations:
             title: 'Instance {{ $labels.instance }} down'
             description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
- alert: ExporterIsDown
           expr: up{job="prometheus-blackbox-exporter"} == 0
           for: 5m
           labels:
             severity: warning
           annotations:
             summary: "Blackbox exporter is down"
             description: "Blackbox exporter is down or not being scraped correctly"
...
...
...
extraScrapeConfigs:  |
   - job_name: 'prometheus-blackbox-exporter'
     metrics_path: /probe
     params:
       module: [http_2xx]
     static_configs:
       - targets:
         - http://service1.default.svc.cluster.local:8082/actuator/health/liveness
         - http://service2.default.svc.cluster.local:8081/actuator/health/liveness
         - http://service3.default.svc.cluster.local:8080/actuator/health/liveness
     relabel_configs:
       - source_labels: [__address__]
         target_label: __param_target
       - source_labels: [__param_target]
         target_label: instance
       - target_label: __address__
         replacement: prometheus-blackbox-exporter:9115
```

These 2 alerts are firing on every hour but at that time endpoints are 100% reachable.
We're using the default prometheus-blackbox-exporter/values.yaml file:

```
config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        no_follow_redirects: false
        preferred_ip_protocol: "ip4"
```

Mails accordingly look this way:
```
5] Firing
Labels
alertname = InstanceDown
instance = http://service1.default.svc.cluster.local:8082/actuator/health/liveness
job = prometheus-blackbox-exporter
severity = critical
```
**What you expected to happen**:
Not to get these false alerts

**How to reproduce it** (as minimally and precisely as possible):

**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
key: value
```

**The helm command that you execute and failing/misfunctioning**:
N/A

**Helm values set after installation/upgrade:**

```console
helm get values my-release
```

**Anything else we need to know**:
