### ISSUE TITLE
[kube-prometheus-stack], [prometheus-adapter] - kubectl top node

### ISSUE THREAD

**Issue by bocha-fanatic** [prometheus-community/helm-charts#738]
```
kubectl version --short
Client Version: v1.18.16
Server Version: v1.18.15

helm version --short
v3.5.2

kubectl top node
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
kubectl top pods -A
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
```

Installed kube-prometheus-stack and prometheus-adapter:
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update

kubectl create namespace monitoring

helm install -n monitoring prometheus \
prometheus-community/kube-prometheus-stack \
--version 13.13.1 --values kube-prometheus-stack.yaml

helm install -n monitoring adapter \
prometheus-community/prometheus-adapter  \
--version 2.12.1 --values prometheus-adapter.yaml
```

kube-prometheus-stack.yaml
```
fullnameOverride: "monitoring"
grafana:
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.0.118
    port: 80
prometheusOperator:
  clusterDomain: "test.clstr.local"
prometheus:
  service:
    loadBalancerIP: "192.168.0.119"
    type: LoadBalancer
```

prometheus-adapter.yaml
```
prometheus:
  url: http://monitoring-prometheus.monitoring.svc
rules:
  default: false
  custom:
  - seriesQuery: '{__name__=~"^some_metric_count$"}'
    resources:
      template: <<.Resource>>
    name:
      matches: ""
      as: "my_custom_metric"
    metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)
  resource:
    cpu:
      containerQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>}[3m])) by (<<.GroupBy>>)
      nodeQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, id='/'}[3m])) by (<<.GroupBy>>)
      resources:
        overrides:
          instance:
            resource: node
          namespace:
            resource: namespace
          pod:
            resource: pod
      containerLabel: container
    memory:
      containerQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>}) by (<<.GroupBy>>)
      nodeQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>,id='/'}) by (<<.GroupBy>>)
      resources:
        overrides:
          instance:
            resource: node
          namespace:
            resource: namespace
          pod:
            resource: pod
      containerLabel: container
    window: 3m
```

After installation, the situation is as follows:
```
kubectl top node
error: metrics not available yet

kubectl top node master-01.test
Error from server (NotFound): nodemetrics.metrics.k8s.io "master-01.test" not found

kubectl top pods -A
NAMESPACE                           NAME                                                             CPU(cores)   MEMORY(bytes)
...
kube-system                         kube-proxy-67qb2                                                 8m           104Mi
kube-system                         kube-proxy-bnf7g                                                 8m           80Mi
kube-system                         kube-proxy-rtxxv                                                 9m           120Mi
...
```

How to solve the problem with "kubectl top node"?
