### ISSUE TITLE
Helm error during upgrade of stack  - grafana.ini values

### ISSUE THREAD

**Issue by Daxcor69** [prometheus-community/helm-charts#751]
I am adding some custom values to the grafana.ini:  section of the values.yaml file.

```
 # grafana config override values.
  grafana.ini:
    server:
      root_url: 'https://grafana.domain.net'
      enable_gzip: true
    auth:
      azuread:
        allow_sign_up: false
      generic_oauth:
        allow_sign_up: false
      github:
        allow_sign_up: false
      gitllab:
        allow_sign_up: false
      google:
        allow_sign_up: false
      grafana_com:
        allow_sign_up: false
      grafananet:
        allow_sign_up: false
      ldap:
        allow_sign_up: false
      okta:
        allow_sign_up: false
      proxy:
        allow_sign_up: false
        enable_login_token: true
        enabled: true
        header_name: 'X-WEBAUTH-USER'
        header_property: 'username'
```
When I go to do the helm update I get the following error:
```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(ConfigMap): unknown field "enable_login_token" in io.k8s.api.core.v1.ConfigMap, ValidationError(ConfigMap): unknown field "enabled" in io.k8s.api.core.v1.ConfigMap, ValidationError(ConfigMap): unknown field "header_name" in io.k8s.api.core.v1.ConfigMap, ValidationError(ConfigMap): unknown field "header_property" in io.k8s.api.core.v1.ConfigMap]
```
I did an repo update, before I ran the update to make sure I had the latest chart.

Thanks
Brad

**Comment by bittrance** [comment]
For what it is worth, I had success with this Terraform/Helm set operation:
```
  set {
    name  = "grafana.grafana\\.ini.auth\\.proxy.enabled"
    value = "true"
  }
  set {
    name  = "grafana.grafana\\.ini.auth\\.proxy.header_name"
    value = "X-Remote-User"
  }
```
Note that `auth.proxy` is escaped. The config file is an ini file and has no real notion of hierarchy. Perhaps your example above can be equally addressed with:
```
grafana.ini:
  auth.azuread:
     allow_sign_up: false
...
```
?
