### ISSUE TITLE
[kube-prometheus-stack] rpc error: code = Unimplemented 404 from thanos query

### ISSUE THREAD

**Issue by occelebi** [prometheus-community/helm-charts#762]
Hi,

I have thanos query and thanos sidecar in separate project in GCP. I have created internal load balancer for GKE and placed A record for internal zone by having ingress with external-dns. 

Values.yaml:
```
prometheus:
  service:
    annotations:               
      cloud.google.com/neg: '{"ingress": true}'
    type: NodePort             

  thanosIngress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "gce-internal"
    hosts:
      - thanos.dev.domain.internal
```

log from thanos query:

> level=warn ts=2021-03-12T16:25:20.305577182Z caller=storeset.go:458 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from thanos.dev.domain.internal:80: rpc error: code = Unimplemented desc = Not Found: HTTP status code 404; transport: received the unexpected content-type \"text/plain; charset=utf-8\"" address=thanos.dev.domain.internal:80

values.yaml for bitnami/thanos: 
```
query:
  enabled: true
  replicaLabel: []
  dnsDiscovery:
    enabled: false
  stores:
    - thanos.dev.domain.internal:80
  ```
Internal load balancer works fine. But I could not get thanos query got metrics from sidecar.

**Comment by occelebi** [comment]
Hey I just found out that GCP L7 internal load balancer does not support grpc (HTTP/2) request coming from StoreAPI. So instead, I used L4 TCP internal load balancer for IP that dns record needs. 

values.yaml:
```
prometheus:

  service:
    annotations:
      networking.gke.io/load-balancer-type: "Internal"
      external-dns.alpha.kubernetes.io/hostname: thanos.dev.domain.internal
    type: LoadBalancer         
    additionalPorts:
    - name: grpc               
      port: 10901
      targetPort: 10901
```
It is as simple as it is. Neither you need ingress nor network endpoint group. 

And then values.yaml for thanos query:
```
query:
  enabled: true         
  stores:    
    - thanos.dev.domain.internal:10901
```

I hope it would be beneficial for future reviewers.
