### ISSUE TITLE
[kube-prometheus-stack] support NodePort type to thanos-discovery service

### ISSUE THREAD

**Issue by jabbukka** [prometheus-community/helm-charts#768]
**Is your feature request related to a problem? Please describe.**
I'd like to set the thanos-discovery service type to `NodePort`.   
Because Thanos needs an exposed port (NodePort) to connect prometheus servers running in the other clusters.

**Describe the solution you'd like**
Add new values in kube-prometheus-stack chart and apply using it in yaml file:  

_values.yaml:_
```yaml
  thanosService:
    ...
    ## Service type
    ##
    type: ClusterIP 

    ## Port to expose on each node
    ##
    nodePort: 30901
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
