### ISSUE TITLE
[prometheus-kube-stack] grafana dashboard with input does not load data

### ISSUE THREAD

**Issue by rwong2888** [prometheus-community/helm-charts#782]
**Describe the bug**

Dashboards with inputs such as [istio performance dashboard](https://grafana.com/api/dashboards/11829) are not loading the datasource.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T09:58:13Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.15-gke.800", GitCommit:"fa6f8f9671a3ba4b1790bac677bb72b04204e8fc", GitTreeState:"clean", BuildDate:"2020-12-21T09:19:13Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kube-prometheus-stack

**Which version of the chart**:
14.1.2

**What happened**:
Dashboard loads but has no metrics.

**What you expected to happen**:
Expected to have metrics from Prometheus

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):
```
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder:
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      istio-performance-dashboard:
        gnetId: 11829
        DS_PROMETHEUS: Prometheus
```

**Comment by rwong2888** [comment]
needed revision and datasource

**Comment by tommy31** [comment]
Hello if you end up here, i found the solution in this commit: https://github.com/paolopiaggio/helm-charts/commit/ee7f4d8e75d2237fec4d64c481765d7035e2689a

```  
dashboards:
    default:
      karpenter-overview:
        gnetId: 20398
        revision: 1
        datasource: 
          - name: DS_PROMETHEUS
            value: Prometheus
```
