### ISSUE TITLE
[prometheus-kube-stack] delete datasource using configuration

### ISSUE THREAD

**Issue by jemag** [prometheus-community/helm-charts#791]
**Describe the bug**

Deleting a datasource from the configmap does not delete the datasource.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"clean", GoVersion:"go1.15.7"}

```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"archive", BuildDate:"2021-01-13T22:07:54Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-20T16:22:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Which chart**:
kube-prometheus-stack

**Which version of the chart**:
14.3.0

**What happened**:
- Removed datasource from grafana datasource configmap
- Restarted grafana pod

**What you expected to happen**:
Datasource gets deleted from grafana

**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
grafana:
  persistence:
    enabled: true
    storageClassName: managed-premium
    size:  50Gi
  additionalDataSources:
   - name: iwls-prometheus
     type: prometheus
     access: proxy
     url: http://iwls-prometheus.iwls:9090/
```

grafana-datasource configmap:
```yaml
apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://kube-prometheus-stack-prometheus:9090/
      access: proxy
      isDefault: true
      jsonData:
        timeInterval: 30s
    - access: proxy
      name: iwls-prometheus
      type: prometheus
      url: http://iwls-prometheus.iwls:9090/
kind: ConfigMap
```

datasources in Grafana UI:
![image](https://user-images.githubusercontent.com/7985687/112196913-e2912e80-8be1-11eb-8e5b-fa2be42fce99.png)

## Questions

1- Is this the expected behavior?
2- If this is the expected behavior, how can we delete datasources through configuration?
