### ISSUE TITLE
[kube-prometheus-stack] Expose more values for kube-state-metrics

### ISSUE THREAD

**Issue by roelandvanbatenburg** [prometheus-community/helm-charts#794]
From my kube-prometheus-stack values, I want to configure the kube-state-metrics deployment to run on tainted nodes. For most other components (grafana, prometheus(Operator) and alertmanager) this works fine and the kube-state-metrics does have this value: <https://github.com/kubernetes/kube-state-metrics/blob/master/charts/kube-state-metrics/values.yaml#L101>. But most of these values are not exposed.

**Describe the solution you'd like**
When settings the following in values.yml
```yml
kubeStateMetrics:
  nodeSelector:
    cloud.google.com/gke-preemptible: "true"
  tolerations:
    - key: cloud.google.com/gke-preemptible
      operator: Equal
      value: "true"
      effect: NoSchedule
```

This should cause the nodeSelector and toleration should be applied to the kube-state-metrics deployment.

**Describe alternatives you've considered**
Alternative could be to introduce a `kubeStateMetricsSpec` same as for alertmanager and prometheus

**Comment by joshm91** [comment]
It's my understanding that just because the values you're looking to set aren't specified directly in the kube-prometheus-stack values.yaml file doesn't mean you can't set them. They'll still get passed to the underlying subchart. That being said, the key you're looking for is actually `kube-state-metrics`. Any values specified under [that](https://github.com/prometheus-community/helm-charts/blob/99805230a123e979995e67a3a539c827802952f5/charts/kube-prometheus-stack/values.yaml#L1180) key will be passed to the underlying chart.

In your example, this _should_ work:
```yaml
kube-state-metrics:
  nodeSelector:
    cloud.google.com/gke-preemptible: "true"
  tolerations:
    - key: cloud.google.com/gke-preemptible
      operator: Equal
      value: "true"
      effect: NoSchedule
```
