### ISSUE TITLE
[prometheus-kube-stack] Grafana chart SMTP is not working

### ISSUE THREAD

**Issue by nowjean** [prometheus-community/helm-charts#803]
**Describe the bug**
Grafana SMTP is not working

```console
$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

Kubernetes Version:

```console
$ kubectl version(AKS)
v1.18.14
```

**Which chart**:
prometheus-kube-stack

**Which version of the chart**:
14.0.0

**What happened**:
Grafana SMTP Setting is not working

**What you expected to happen**:
Grafana SMTP Setting is working and sending mail 

===========================================
I configured grafana chart like this
```
grafana.ini:
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  smtp:
    enable: true
    host: smtp.sendgrid.net:587
    user: <USERID>
    password: <PASSWORD>
    skip_verify: false
    from_address: grafana@ssafy.com
    from_name: Grafana 
```

And i checked in grafana pod at /etc/grafana/grafana.ini is like
```
[smtp]
enable = true
from_address = grafana@ssafy.com
from_name = Grafana
host = smtp.sendgrid.net:587
password = <PASSWORD>
skip_verify = true
user =<USERID>
```

I guess every setting for SMTP is fine. But when i test Notification channels on Grafana GUI, I could see this message : SMTP not configured, check your grafana.ini config file's [smtp] section.

What should i do??? My SMTP Server is okay.... I already used this server on other Programs..
Please give me a hint..

Thanks guys.
