### ISSUE TITLE
[kube-prometheus-stack] Support EnableFeatures API

### ISSUE THREAD

**Issue by tonychoe** [prometheus-community/helm-charts#823]
**Is your feature request related to a problem? Please describe.**
Prometheus Operator is adding the feature that allows users to enable the disabled features such as the in-memory storage for Exemplars. It's done via https://github.com/prometheus-operator/prometheus-operator/pull/3878, and merged. It would be great to see the Helm Chart support this.

**Describe the solution you'd like**
I want to be able to configure enableFeatures through `values.yaml` like this.
```yaml
prometheus;
  prometheusSpec:
    enableFeatures:
      # Enable the Exemplar in-memory storage
      - 'exemplar-storage'
```

**Additional Info**

- https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
- See [the latest prometheuses.monitoring.coreos.com CRD](https://github.com/prometheus-operator/prometheus-operator/blob/master/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml).

```yaml
              enableFeatures:
                description: Enable access to Prometheus disabled features. By default, no features are enabled. Enabling disabled features is entirely outside the scope of what the maintainers will support and by doing so, you accept that this behaviour may break at any time without notice. For more information see https://prometheus.io/docs/prometheus/latest/disabled_features/
                items:
                  type: string
                type: array
```
