### ISSUE TITLE
[prometheus-kube-stack] how to enable persistent volume in prometheus?

### ISSUE THREAD

**Issue by hehe717** [prometheus-community/helm-charts#834]
**Describe the bug**
I am trying to enable persistent volume in this chart by enable `storageSpec`
```
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: prometheus-sc
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
        selector: {}
```
But I got below error. 
```
Error: UPGRADE FAILED: cannot patch "kube-prometheus-stack-prometheus" with kind Prometheus: Prometheus.monitoring.coreos.com "kube-prometheus-stack-prometheus" is invalid: [spec.storage.class: Required value, spec.storage.selector: Required value, spec.storage.resources: Required value]
```
I can't find any spec for `spec.storage.class` or `spec.storage.resources` from https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/storage.md
Am I missing something?

**Version of Helm and Kubernetes**:

Helm Version: 

version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}

Kubernetes Version:

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-gke.2800", GitCommit:"4ef0543cc59f482d118ae33397108118ec80d447", GitTreeState:"clean", BuildDate:"2021-02-20T01:42:15Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
