### ISSUE TITLE
[kube-prometheus-stack] alertmanager antiaffinity has no affect

### ISSUE THREAD

**Issue by laverya** [prometheus-community/helm-charts#857]
**Describe the bug**
Alertmanager antiaffinity uses the wrong keys - specifically, it uses `prometheus` as the key [here](https://github.com/prometheus-community/helm-charts/blob/ac86c92/charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml#L94) when the statefulset does not have that key.

Presumably, it should be using the key `alertmanager` instead.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:09:28Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: prometheus-community/kube-prometheus-stack

**Which version of the chart**: 14.9.0

**What happened**: The following alertmanager object:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-alertmanager
    
    chart: kube-prometheus-stack-14.9.0
    release: "v0.46.0-14.9.0"
    heritage: "Helm"
spec:
  image: quay.io/prometheus/alertmanager:v0.21.0
  version: v0.21.0
  replicas: 3
  listenLocal: false
  serviceAccountName: prometheus-alertmanager
  externalUrl: http://prometheus-alertmanager.monitoring:9093
  paused: false
  logFormat: "logfmt"
  logLevel:  "info"
  retention: "120h"
  alertmanagerConfigSelector: {}
  alertmanagerConfigNamespaceSelector: {}
  routePrefix: "/"
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
            - {key: app, operator: In, values: [alertmanager]}
            - {key: prometheus, operator: In, values: [prometheus-alertmanager]}
  portName: web
```
created the following statefulset:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kube-prometheus-stack-alertmanager
    chart: kube-prometheus-stack-14.9.0
    heritage: Helm
    release: v0.46.0-14.9.0
  name: alertmanager-prometheus-alertmanager
  namespace: monitoring
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      alertmanager: prometheus-alertmanager
      app: alertmanager
  serviceName: alertmanager-operated
  template:
    metadata:
      creationTimestamp: null
      labels:
        alertmanager: prometheus-alertmanager
        app: alertmanager
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - alertmanager
              - key: prometheus
                operator: In
                values:
                - prometheus-alertmanager
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - --config.file=/etc/alertmanager/config/alertmanager.yaml
        - --storage.path=/alertmanager
        - --data.retention=120h
        - --cluster.listen-address=[$(POD_IP)]:9094
        - --web.listen-address=:9093
        - --web.external-url=http://prometheus-alertmanager.monitoring:9093
        - --web.route-prefix=/
        - --cluster.peer=alertmanager-prometheus-alertmanager-0.alertmanager-operated:9094
        - --cluster.peer=alertmanager-prometheus-alertmanager-1.alertmanager-operated:9094
        - --cluster.peer=alertmanager-prometheus-alertmanager-2.alertmanager-operated:9094
        - --cluster.reconnect-timeout=5m
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: quay.io/prometheus/alertmanager:v0.21.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /-/healthy
            port: web
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: alertmanager
        ports:
        - containerPort: 9093
          name: web
          protocol: TCP
        - containerPort: 9094
          name: mesh-tcp
          protocol: TCP
        - containerPort: 9094
          name: mesh-udp
          protocol: UDP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /-/ready
            port: web
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          requests:
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
        - mountPath: /etc/alertmanager/certs
          name: tls-assets
          readOnly: true
        - mountPath: /alertmanager
          name: alertmanager-prometheus-alertmanager-db
      - args:
        - --listen-address=:8080
        - --reload-url=http://127.0.0.1:9093/-/reload
        - --watched-dir=/etc/alertmanager/config
        command:
        - /bin/prometheus-config-reloader
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SHARD
          value: "-1"
        image: quay.io/prometheus-operator/prometheus-config-reloader:v0.46.0
        imagePullPolicy: IfNotPresent
        name: config-reloader
        ports:
        - containerPort: 8080
          name: reloader-web
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: prometheus-alertmanager
      serviceAccountName: prometheus-alertmanager
      terminationGracePeriodSeconds: 120
      volumes:
      - name: config-volume
        secret:
          defaultMode: 420
          secretName: alertmanager-prometheus-alertmanager-generated
      - name: tls-assets
        secret:
          defaultMode: 420
          secretName: alertmanager-prometheus-alertmanager-tls-assets
      - emptyDir: {}
        name: alertmanager-prometheus-alertmanager-db
  updateStrategy:
    type: RollingUpdate
```

Which has antiAffinity of 
```yaml
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - alertmanager
              - key: prometheus
                operator: In
                values:
                - prometheus-alertmanager
            topologyKey: kubernetes.io/hostname
```
but labels
```yaml
      labels:
        alertmanager: prometheus-alertmanager
        app: alertmanager
```
and thus the antiaffinity has no affect.

**What you expected to happen**:
Antiaffinity labels match pod labels.

**How to reproduce it** (as minimally and precisely as possible): 

Set `alertmanager.alertmanagerSpec.podAntiAffinity: "hard"`, `alertmanager.alertmanagerSpec.replicas: 3` and install to a single node cluster. Observer multiple alertmanager pods running on that one node.

**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
 `alertmanager.alertmanagerSpec.podAntiAffinity: "hard"`
```
```console
 `alertmanager.alertmanagerSpec.replicas: 3`
```

**The helm command that you execute and failing/malfunctioning**:

```console
helm template v0.46.0-14.9.0 prometheus-community/kube-prometheus-stack --version 14.9.0 --values values.yaml
```

**Helm values set after installation/upgrade:**

None, as it was setup with `helm template`.

**Anything else we need to know**:
