### ISSUE TITLE
[prometheus-blackbox-exporter] Relabelings doesn't work

### ISSUE THREAD

**Issue by pbrissaud** [prometheus-community/helm-charts#868]
**Describe the bug**
When deploying the blackbox-exporter, the default relabeling config for Service Monitor is not applied 

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16.2"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"archive", BuildDate:"2021-03-25T19:02:48Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Which chart**: prometheus-blackbox-exporter

**Which version of the chart**: 4.11.0

**What happened**:
When I go to prometheus target page :
* the label *instance* is incorrect
* the label *target* doesn't appear 

![Capture d’écran de 2021-04-21 16-24-37](https://user-images.githubusercontent.com/27202456/115573352-f606e680-a2c0-11eb-907b-200b67205992.png)

**What you expected to happen**: 
I expect to see the labels as set in rendered service monitor file 
```console
$ helm get manifest blackbox-exporter 
```
```yaml
# Source: prometheus-blackbox-exporter/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-exporter-prometheus-blackbox-exporter-dns-cloudflare
  labels:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: blackbox-exporter
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: prometheus-blackbox-exporter-4.11.0
spec:
  endpoints:
  - port: http
    scheme: http
    path: "/probe"
    interval: 60s
    scrapeTimeout: 60s
    params:
      module:
      - dns
      target:
      - 1.1.1.1
    metricRelabelings:
      - targetLabel: instance
        replacement: 1.1.1.1
      - targetLabel: target
        replacement: dns-cloudflare
  jobLabel: "blackbox-exporter"
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
      app.kubernetes.io/instance: blackbox-exporter
  namespaceSelector:
    matchNames:
      - default

```

**How to reproduce it** (as minimally and precisely as possible):
1. Clone the project
2. Modify the values.yaml file (see below) 
3. Install the chart (see below) 

**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml (git diff output)

```console
diff --git a/charts/prometheus-blackbox-exporter/values.yaml b/charts/prometheus-blackbox-exporter/values.yaml
index 7d70c9c..e3261be 100644
--- a/charts/prometheus-blackbox-exporter/values.yaml
+++ b/charts/prometheus-blackbox-exporter/values.yaml
@@ -101,6 +101,14 @@ config:
         valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
         no_follow_redirects: false
         preferred_ip_protocol: "ip4"
+    dns:
+      prober: dns
+      dns:
+        query_name: "bizdy.fr"
+        query_type: "A"
+        validate_answer_rrs:
+          fail_if_not_matches_regexp:
+           - "bizdy.fr.\t.*\tIN"  
 
 extraConfigmapMounts: []
   # - name: certs-configmap
@@ -187,7 +195,7 @@ serviceMonitor:
   ## If true, a ServiceMonitor CRD is created for a prometheus operator
   ## https://github.com/coreos/prometheus-operator
   ##
-  enabled: false
+  enabled: true
 
   # Default values that will be used for all ServiceMonitors created by `targets`
   defaults:
@@ -204,13 +212,13 @@ serviceMonitor:
   bearerTokenFile:
 
   targets:
-#    - name: example                    # Human readable URL that will appear in Prometheus / AlertManager
-#      url: http://example.com/healthz  # The URL that blackbox will scrape
-#      labels: {}                       # Map of labels for ServiceMonitor. Overrides value set in `defaults`
-#      interval: 60s                    # Scraping interval. Overrides value set in `defaults`
-#      scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
-#      module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`
-#      additionalMetricsRelabels: {}    # Map of metric labels and values to add
+    - name: dns-cloudflare       
+      url: 1.1.1.1
+      labels: {}
+      interval: 60s
+      scrapeTimeout: 60s
+      module: dns
+      additionalMetricsRelabels: {}
```

**The helm command that you execute**:
```console
helm install blackbox-exporter charts/prometheus-blackbox-exporter 
```

**Anything else we need to know**:

* Minikube cluster
```console
$ minikube version
minikube version: v1.18.1
commit: 09ee84d530de4a92f00f1c5dbc34cead092b95bc
```

* Bitnami kube-prometheus helm chart (version: 4.2.2) installed with :
```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install my-release bitnami/kube-prometheus
```

**Comment by pbrissaud** [comment]
Weird thing : when I query the data, the labels are good. So it's only a visual bug in **targets** view  ? 

![Capture d’écran de 2021-04-22 14-08-35](https://user-images.githubusercontent.com/27202456/115711983-82261600-a374-11eb-8e7b-eead0e2e6b46.png)

**Comment by zeritti** [comment]
In you service monitor, you applied `serviceMonitor.spec.endpoints.metricRelabelings` which acts on samples before ingestion and it did. To relable targets' labels, you may want to use `serviceMonitor.spec.endpoints.relabelings`.

**Comment by pbrissaud** [comment]
Thanks for your answer. So, as the `serviceMonitor.spec.endpoints.relabelings` is not present in the `servicemonitor.yaml` template file, I should modify it for my case. Do I need only change *metricRelabelings* to *relabelings* like that ? 

```yaml
relabelings:
    - targetLabel: instance
      replacement: {{ .url }}
    - targetLabel: target
      replacement: {{ .name }}
      {{- range $targetLabel, $replacement := .additionalMetricsRelabels | default $.Values.serviceMonitor.defaults.additionalMetricsRelabels }}
    - targetLabel: {{ $targetLabel }}
      replacement: {{ $replacement }}
      {{- end }}
```
