### ISSUE TITLE
[kube-prometheus-stack] remoteRead & remoteWrite configs aren't parsed using tpl

### ISSUE THREAD

**Issue by VineethReddy02** [prometheus-community/helm-charts#874]
When using `kube-prometheus-stack` as a dependent helm chart in other helm charts. Passing `{{ .Release.Name }}` & `{{ .Release.Namespace}}` isn't parsed in config using the helm `tpl` function. This is causing Prometheus pod to crash when remote config is provided as follows:

 ```
      remoteRead:
        - url: "http://{{.Release.Name }}-promscale-connector.{{ .Release.Namespace }}.svc.cluster.local:9201/read"
          readRecent: true

      remoteWrite:
        - url: "http://{{ .Release.Name }}-promscale-connector.{{ .Release.Namespace }}.svc.cluster.local:9201/write"
 ```
 
 The Prometheus pod logs the below error & crashes as provided remote endpoint URLs aren't being parsed to releaseName & namespace:

```
$ kubectl logs prometheus-gg-kube-prometheus-stack-prometheus-0 -n ns -c prometheus
level=error ts=2021-04-21T20:15:30.619Z caller=main.go:293 msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: parse \"http://{{ .Release.Name }}-promscale-connector.{{ .Release.Namespace }}.svc.cluster.local:9201/write\": invalid character \"{\" in host name"
```
