### ISSUE TITLE
[prometheus-elasticsearch-exporter] how to add custom label ?

### ISSUE THREAD

**Issue by Xat59** [prometheus-community/helm-charts#879]
Hello team !

I am using `prometheus-elasticsearch-exporter` and would like to add custom `label: value` for every exported metric.
I will be useful to me later for filtering.

**Is your feature request related to a problem? Please describe.**
Not sure if this feature exists, but for now I didn't successfully added a custom label.

**Describe the solution you'd like**
For every metric that is exported with `prometheus-elasticsearch-exporter`, I would like to add this label `job: elasticsearch-exporter`.

By the way, it could be nice to have the possibility to add several labels, so it could be something like this : 
```
append_labels:
  job: elasticsearch-exporter
  any_label: value
```

**Describe alternatives you've considered**
If you know any alternative, please let me know ;)

Thanks a lot.
Regards.

**Comment by Xat59** [comment]
I tried with this : 

```
serviceMonitor:
  enabled: true
  interval: 10s
  labels: {}
  metricRelabelings:
  - action: replace
    replacement: elasticsearch-exporter
    targetLabel: job
  relabelings:
  - action: replace
    replacement: elasticsearch-exporter
    targetLabel: job
```

But it does not work as expected

**Comment by zeritti** [comment]
Using `serviceMonitor.targetLabels` in your values seems the way forward. However, before the listed labels get transferred on to the target, they must be attached to the service(es) in question.

**Comment by Xat59** [comment]
Thanks @zeritti for the response. 

So I can use something like this to add `job=elasticsearch-exporter` label into every metrics :
```
serviceMonitor:
  enabled: true
  interval: 10s
  targetLabels:
    job: elasticsearch-exporter
```

But you say this label must be attached before adding it ? That's what I don't understand.
Can you please explain it to me ?

Thank you !

**Comment by zeritti** [comment]
Yes, `serviceMonitor.targetLabels` transfers labels present on a service to the corresponding Prometheus' target. It presumes that the listed label is already present on the service. For instance, I have a service being scraped labelled `team: blue`. If I wish to have this label available in the metrics, I will set the service monitor like this:
```
 serviceMonitor:
   enabled: true
   targetLabels:
     - team
```
Note that `targetLabels` is a list.
For the job label in particular, it may be more difficult as this label is AFAIK always created by Prometheus. In this case, one might consider `serviceMonitor.jobLabel` which will be used for setting the job's name. However, as above, it gives an existing  label to be used for setting the job's name.
