### ISSUE TITLE
[prometheus] possibility to add metric_relabel_configs to individual pre-configured jobs from values.yaml

### ISSUE THREAD

**Issue by jhuebner79** [prometheus-community/helm-charts#894]
I would like to be able to add a metric_relable_configs section to individual scrape jobs you define per default. Something like this:

```
- job_name: kubernetes-apiservers
  [...]
  metric_relabel_configs:
   - source_labels: [ __name__ ]
     regex: 'apiserver_request_duration_seconds_bucket'
     action: drop
```
The only option I see right now is to generate a complete separate configmap outside of this helm chart and use that.

That configmap would contain everything the configmap that is being generated when `configMapOverrideName:` is unset, plus the metric_relabel_configs sections I need.

It would be very helpful not needing to do that. Or is there something I do not see?
