### ISSUE TITLE
[kube-prometheus-stack] Wrong test for "networking.k8s.io/v1"

### ISSUE THREAD

**Issue by mxmorin** [prometheus-community/helm-charts#899]
**Describe the bug**
ingress chart test capability to set the version of Ingress
Unfortunately, this returns always networking.k8s.io/v1

**Version of Helm and Kubernetes**:
Helm Version: 3 5.3
K8s version : v1.18.15+vmware.1

**Which chart**:
kube-prometheus-stack
Template : prometheus/ingress.yaml
**Which version of the chart**:
15.2.1

**What you expected to happen**:
Detect version of ingres

Test should be : 
` {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}`

**Comment by jtackaberry** [comment]
PR #900 was picked up in kube-prometheus-stack-15.2.2 and this is breaking the ingress resource for me.

I'm using Helm 3.5.4 and K8s 1.19.9 and my values looks like:

```yaml
grafana:
  ingress:
    enabled: true
    pathType: Prefix
    ingressClassName: nginx
    hosts:
      - mysite.example.com
```

But notice the resulting apiVersion is `extensions/v1beta`:

```yaml
$ helm template prometheus-operator ./kube-prometheus-stack -f values.yaml  -s charts/grafana/templates/ingress.yaml
---
# Source: kube-prometheus-stack/charts/grafana/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-operator-grafana
  namespace: default
  labels:
    helm.sh/chart: grafana-6.8.2
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/version: "7.5.5"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: nginx
  rules:
    - host: mysite.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: prometheus-operator-grafana
              servicePort: 80
```

If I revert the change from #900 the Ingress resource is correct.

Looking at the Helm documentation for [Capabilities.APIVersions.Has](https://helm.sh/docs/chart_template_guide/builtin_objects/) this change sounds like it should be valid, but it's not behaving properly for me at least with Helm 3.5.4.
