### ISSUE TITLE
Read mounted secret in Grafana pod in values.yaml 

### ISSUE THREAD

**Issue by Jaja0624** [prometheus-community/helm-charts#909]
I have mounted a secret in Grafana pod but not sure how to read from it and use it as secret for custom HTTP header in Grafana data source. Tried Grafana file provider but that doesnt work. Any tips?

values.yaml
```
grafana:
  extraSecretMounts:
  - name: secrets-mount
    secretName: secretName
    defaultMode: 0440
    mountPath: /etc/grafana/secrets/mysecret
    readOnly: true
  additionalDataSources:
  - name: datasourceName
    access: proxy
    basicAuth: false
    editable: true
    jsonData:
        tlsSkipVerify: false
        httpHeaderName1: "X-Query-Key" 
    secureJsonData:
        httpHeaderValue1: $__(/etc/grafana/secrets/mysecret) # doesn't work
```
Thank you :)
