### ISSUE TITLE
[prometheus-kube-stack] err="open /prometheus/queries.active: permission denied

### ISSUE THREAD

**Issue by CarlosIVI** [prometheus-community/helm-charts#910]
**Describe the bug**
The prometheus-kube-prometheus-0 pods is in CrashLookBackOff by:

level=error ts=2021-04-28T17:26:54.814Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"

**Version of Helm and Kubernetes**:

Helm Version:

```
Helm v3.5.3
```

Kubernetes Version:

```console
$ kubectl version
kubectl v1.20.2
```

**Which chart**: prometheus-kube-stack

**Which version of the chart**: Lastest (I guess is x15)

**What happened**:

I know that this is a issue normally cause by permissions on the SecurityContext Section, but I already modify that section on my helm chart, and I gave all the permisions to my PV folders.

```
  securityContext:
    runAsUser: 1000   <- - modify this to 1000,
    runAsNonRoot: true
    runAsGroup: 65534
    fsGroup: 2000   <- - modify this to 2000
```

```
# chown 1000:1000 -R /localhoststorage/

```
My persistent volume is on $HOME/localhoststorage

**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```
LINE 625

grafana:
  enabled: true
  namespaceOverride: ""

  ## Deploy default dashboards.
  ##
  defaultDashboardsEnabled: true

  adminPassword: cal1ps0
  persistence:
    type: pvc
    enabled: true
    storageClassName: my-local-storage
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection
    selectorLabels:
      type: local
      purpose: grafana

LINE 2113


storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "my-local-storage"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
          selector:
            matchLabels:
              type: local
              purpose: prometheus

Line 2227

securityContext:
    runAsUser: 1000   
    runAsNonRoot: true
    runAsGroup: 65534
    fsGroup: 2000 

```
