### ISSUE TITLE
[prometheus-kube-stack] Not able to add Service monitor with Helm values.yaml

### ISSUE THREAD

**Issue by anoop-l** [prometheus-community/helm-charts#922]
**Describe the bug**
We added additional service monitor using values.yaml
**Version of Helm and Kubernetes**:
v1.19.6
Helm Version: v3.5.3

```console
$ helm version
v3.5.3```

Kubernetes Version:

```console
$ kubectl version
v1.19.6
```

**Which chart**:
prometheus-kube-stack
**Which version of the chart**:

**What happened**:

**What you expected to happen**:
Install Operator with additional service monitors

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml:
```
additionalRulesForClusterRole: []
  #  - apiGroups: [ "" ]
  #    resources:
  #      - nodes/proxy
  #    verbs: [ "get", "list", "watch" ]
additionalServiceMonitors:
    - name: couchbase
      additionalLabels:
        - app: couchbase
      endpoints:
        - port: metrics
          interval: 5s
          bearerTokenFile:
            key: token
            name: cb-metrics-token
      namespaceSelector:
        matchNames:
          - default
      selector:
        matchLabels:
          app: couchbase
```

```console
helm install kube-prometheus prometheus-community/kube-prometheus-stack -f values.yaml
```

We are trying to add additional service monitor as above using Helm.
We get the following error:
```Error: YAML parse error on kube-prometheus-stack/templates/prometheus/servicemonitors.yaml: error converting YAML to JSON: yaml: line 18: did not find expected key```

Any help on debugging this would be appreciated
