### ISSUE TITLE
[kube-prometheus-stack] Enable affinity specification for node exporter

### ISSUE THREAD

**Issue by frvasquezjaquez** [prometheus-community/helm-charts#925]
**Is your feature request related to a problem? Please describe.**
I have an AWS cluster with EC2 and fargate nodes. When i deploy the prometheus stack chart it tries to deploy a node exporter daemon set in all the nodes, even in fargate nodes, which are serverless, so it causes that some pods stay Pending. 

**Describe the solution you'd like**
Add the node selector or affinity tag to the value.yml so i can especify in which nodes i want to deploy the node exporters.

**Additional context**

1. This is the error that im getting in the fargate nodes:
```
0/8 nodes are available: 3 Too many pods, 5 node(s) didn't have free ports for the requested pod ports.
```

2. This is the affinitt created automatically by the helm chart:
```
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
      - matchFields:
          - key: metadata.name
            operator: In
            values:
              - fargate-ip-xxx.xxxx.xxx.xxx.ec2.internal
```

**Comment by xpunch** [comment]
```
affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                      - fargate
```
