### ISSUE TITLE
[Prometheus  Community - Prometheus Helm Chart] Won't pick up serverFile Overrides

### ISSUE THREAD

**Issue by brokencode64** [prometheus-community/helm-charts#932]
**Describe the bug**
Created prometheus helm-chart and prometheus launches fine, but serverFiles such as prometheus.yml and alert configs are not picked up. Default values are still used.

**Version of Helm and Kubernetes**:
Helm Operator: 1.2.0
Kubernetes (EKS): 1.19.6
Prometheus Community - Prometheus Helm Chart: 13.8.0

**What happened**:
Default prometheus.yml and alerts are used. Configmap shows default values despite providing overrides.

**What you expected to happen**:
Custom override prometheus.yml values  and other serverFiles should be used.

**How to reproduce it** (as minimally and precisely as possible):
1. Created prometheus.yaml values file with the following configurations
2. Apply configuration
3. Helm-operator deploys chart

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitor
spec:
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus
    version: 13.8.0
  values:
      server:
        create: true
        name: prometheus-prometheus
        annotations: {}

  configmapReload:
      prometheus:
        enabled: false
      alertmanager:
        enabled: false

    alertmanager:
      enabled: false
    alertmanagerFiles:
      alertmanager.yml: {}
    kubeStateMetrics:
      enabled: false
    nodeExporter:
      enabled: false
    pushgateway:
      enabled: false


  server:
      name: prometheus
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "10902"
        prometheus.io/scrape: "true"
      enableServiceLinks: false
      sidecarContainers:
        thanos-sidecar:
          image: prom/thanos:v0.19.0
          imagePullPolicy: IfNotPresent
          args:
          - sidecar
          - --log.level=info
          - --log.format=json
          - --tsdb.path=/data
          - --prometheus.url=http://127.0.0.1:9090
          - --grpc-address=0.0.0.0:10903
          - --reloader.config-file=/etc/config/prometheus.yml
            #- --reloader.rule-dir=/etc/alerts
          - --objstore.config-file=/etc/s3-config/config-file.yaml
          ports:
          - name: sidecar-grpc
            containerPort: 10903
          - name: sidecar-http
            containerPort: 10902
          volumeMounts:
          - mountPath: /data
            name: storage-volume
            readOnly: true
          - mountPath: /etc/config
            name: prometheus-config-volume
            readOnly: true
          - mountPath: /etc/s3-config
            name: thanos-store-config
      extraVolumes:
        - name: thanos-store-config
          secret:
            secretName: thanos-store-config
            defaultMode: 288
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: monitor-prometheus-prometheus
      extraFlags:
        - storage.tsdb.min-block-duration=2h
        - storage.tsdb.max-block-duration=2h
        - web.enable-admin-api
      baseURL: "http://prometheus.example.com"
      global:
        external_labels:
          env: 'test-aws'
      alertmanagers: [] #["prometheus-alertmanager"]
      ingress:
        enabled: true
        hosts: ["prometheus.example.com"]
      resources:
        limits:
          memory: 2048Mi
        requests:
          memory: 2048Mi
      persistentVolume:
        size: 50Gi
        storageClass: "gp2"
      retention: "1d"
```

Minimal config files for testing - this is not picked up:
```
serverFiles:
  alerts:
    service1:
      - alert: ThanosSidecarPrometheusDown
        expr: thanos_sidecar_prometheus_up{name="prometheus"} == 0
        for: 1m
        labels:
          responder: Test
          priority: P4
        annotations:
          summary: Thanos Sidecar cannot connect to Prometheus
          impact: Prometheus configuration is not being refreshed
  prometheus.yml: ""
  rules: ""
```

Have tried this separately. Config files with prometheus.yml overriden - also not being picked up:
```
prometheus.yml:
   rule_files:
     - /etc/config/recording_rules.yml
     - /etc/config/alerting_rules.yml
     # Below two files are DEPRECATED will be removed from this default values file
     - /etc/config/rules
     - /etc/config/alerts
     - 
   # Scrape config for services
   # * `prometheus.io/probe`: Only probe services that have a value of `true`
   # * `prometheus.io/path` :  If the probe path is not `/` override this.
   scrape_configs:
     - job_name: etcd
       sample_limit: 50000

      - job_name: prometheus
       sample_limit: 50000
       static_configs:
         - targets:
           - localhost:9090

      - job_name: 'kube-apiservers'
       sample_limit: 50000
       kubernetes_sd_configs:
         - role: endpoints

       scheme: https
       tls_config:
         ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
         insecure_skip_verify: true
       bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
. . .
```

**The helm command that you execute and failing/misfunctioning**:
Helm-operator is not showing any errors.

**Anything else we need to know**:
I am trying to launch the whole stack, and so far everything else has worked except this portion. I have temporarily disabled all other components except prometheus-server for testing. 

I've abreviated the prometheus.yml for testing purposes - but whatever values I provide they are not being picked up.

**Comment by brokencode64** [comment]
Stupid - My indentation was off for serverFiles block. Corrected that and changes are picked up.

**Comment by sanusatyadarshi** [comment]
@brokencode64 Can you share the fixed yaml? I am facing the same issue?
Thanks

**Comment by brokencode64** [comment]
> @brokencode64 Can you share the fixed yaml? I am facing the same issue?
> Thanks

You just need to make sure your "Server" and "ServerFiles" block are at the same level of indentation:
 
```
    server:
      name: prometheus
      enableServiceLinks: false
       . . . 
     serverFiles:
       alerting_rules.yml:
         groups:
        . . .
        prometheus.yml:
          rule_files:
          - /etc/config/recording_rules.yml
          - /etc/config/alerting_rules.yml
        scrape_configs:
        . . .
```

**Comment by sanusatyadarshi** [comment]
This is what happens to my Prometheus pod @brokencode64.
I am not sure what is causing this.

![Screenshot 2021-06-22 at 8 45 10 PM](https://user-images.githubusercontent.com/20282376/122951331-d3657c80-d39a-11eb-8a89-fab3dc4e9ff8.png)
![Screenshot 2021-06-22 at 8 45 17 PM](https://user-images.githubusercontent.com/20282376/122951343-d52f4000-d39a-11eb-95bf-da177c1fb654.png)

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/name":"prometheus-operator","app.kubernetes.io/version":"v0.39.0","k8s-app":"prometheus-operator"},"name":"prometheus-operator","namespace":"monitoring"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/name":"prometheus-operator"}},"template":{"metadata":{"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/name":"prometheus-operator","app.kubernetes.io/version":"v0.39.0"}},"spec":{"containers":[{"args":["--kubelet-service=kube-system/kubelet","--logtostderr=true","--config-reloader-image=jimmidyson/configmap-reload:v0.3.0","--prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.39.0"],"image":"quay.io/coreos/prometheus-operator:v0.39.0","name":"prometheus-operator","ports":[{"containerPort":8080,"name":"http"}],"resources":{"limits":{"cpu":"200m","memory":"200Mi"},"requests":{"cpu":"100m","memory":"100Mi"}},"securityContext":{"allowPrivilegeEscalation":false}},{"args":["server","--listen=:8443","--target=127.0.0.1:8080","--key=cert/key","--cert=cert/cert","--disable-authentication"],"image":"squareup/ghostunnel:v1.4.1","imagePullPolicy":"IfNotPresent","name":"tls-proxy","ports":[{"containerPort":8443,"name":"https","protocol":"TCP"}],"resources":{},"securityContext":{"allowPrivilegeEscalation":false,"readOnlyRootFilesystem":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/cert","name":"tls-proxy-secret","readOnly":true}]}],"nodeSelector":{"beta.kubernetes.io/os":"linux"},"securityContext":{"runAsNonRoot":true,"runAsUser":65534},"serviceAccountName":"prometheus-operator","volumes":[{"name":"tls-proxy-secret","secret":{"defaultMode":420,"secretName":"prometheus-operator-admission"}}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.39.0
    k8s-app: prometheus-operator
  name: prometheus-operator
  selfLink: /apis/extensions/v1beta1/namespaces/monitoring/deployments/prometheus-operator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/version: v0.39.0
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --config-reloader-image=jimmidyson/configmap-reload:v0.3.0
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.39.0
        - --config-reloader-cpu-request=400m
        - --config-reloader-cpu-limit=400m
        - --config-reloader-memory-request=100Mi
        - --config-reloader-memory-limit=100Mi        
        image: quay.io/coreos/prometheus-operator:v0.39.0
        imagePullPolicy: IfNotPresent
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 1000Mi
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - server
        - --listen=:8443
        - --target=127.0.0.1:8080
        - --key=cert/key
        - --cert=cert/cert
        - --disable-authentication
        image: squareup/ghostunnel:v1.4.1
        imagePullPolicy: IfNotPresent
        name: tls-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cert
          name: tls-proxy-secret
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccount: prometheus-operator
      serviceAccountName: prometheus-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tls-proxy-secret
        secret:
          defaultMode: 420
          secretName: prometheus-operator-admission
status: {}
```

**Comment by zeitler** [comment]
This bug affects me also

removing rule_files from serverFiles|prometheus.yml in provided values dont override.
And I believe that it makes sense, because it's computed values, and there's nothing to remove it.

Original serverFiles block:
```
serverFiles:
  alerting_rules.yml: {}
  alerts: {}
  rules: {}
  prometheus.yml:
    rule_files:
      - /etc/config/recording_rules.yml
      - /etc/config/alerting_rules.yml
      - /etc/config/rules
      - /etc/config/alerts
    scrape_configs:
...
```
My values.yaml:
```
serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
...
```
In my values.yaml, I don't fill alerts object, because I don't want to be overriden.

So, just removing rule_files, makes that helm computes with rule_files array from the helm values.yaml

Changing my values.yaml to:
```
serverFiles:
  prometheus.yml:
    rule_files: []
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
...
```
works.

My situation was that I was trying to install prometheus in agent mode.
And in agent mode, rule_files shows up an error

Perhaps an option in helm to enable agent mode?
