### ISSUE TITLE
[prometheus-pushgateway] missed podLabels in deployments.yaml

### ISSUE THREAD

**Issue by auroaj** [prometheus-community/helm-charts#937]
There is an option in values.yaml:
```
# Optional pod labels
podLabels: {}
```

But it missed in template deployments.yaml:
```
...
  template:
    metadata:
      labels:
        app: {{ template "prometheus-pushgateway.name" . }}
        release: {{ .Release.Name }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
    spec:
...
```

Solution: just add line `{{ toYaml .Values.podLabels | indent 8 }}`.
```
...
  template:
    metadata:
      labels:
        app: {{ template "prometheus-pushgateway.name" . }}
        release: {{ .Release.Name }}
{{ toYaml .Values.podLabels | indent 8 }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
    spec:
...
```
