### ISSUE TITLE
[prometheus-kube-stack] deploy custom dashboard using grafana_dashboard=1 is not working

### ISSUE THREAD

**Issue by gowrisankar22** [prometheus-community/helm-charts#939]
If I want to deploy additional Grafana dashboards, the recommendation says that, to add a ConfigMap or Secret which has a label grafana_dashboard=1. The ConfigMap or Secret does not have to be in the same namespace monitoring but this works, if deployed in the same namespace. Any idea how can I fix this?

i am using the default configuration:
```
 sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
 ```
