### ISSUE TITLE
[kube-prometheus-stack] Missing backend definition for ingress

### ISSUE THREAD

**Issue by Shini31** [prometheus-community/helm-charts#942]
**Is your feature request related to a problem? Please describe.**
I'm using ingress with NEG on GKE to create LB. I have to define a backend declaration in the ingress configuration

**Describe the solution you'd like**
A backend section as hosts or paths in values.yaml

**Describe alternatives you've considered**
A backend section as hosts or paths in values.yaml

**Additional context**
an example of functional ingress and service with NEG
_ingress_
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana-neg
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: grafana
    ingress.gcp.kubernetes.io/pre-shared-cert: foo-com
    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: grafana-neg
    servicePort: 3000
```

_service_
```
apiVersion: v1
kind: Service
metadata:
  name: grafana-neg
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
```
