### ISSUE TITLE
[kube-prometheus-stack] PodSecurityPolicy for Grafana

### ISSUE THREAD

**Issue by modzilla99** [prometheus-community/helm-charts#944]
**Describe the bug**
When I deploy the prometheus-stack with persistent storage for prometheus and grafana it will always get stuck with the errormessage "unable to admit pod: [spec.initContainers[0].securityContext.runAsNonRoot". The grafana pod can't create the init container and therefore doesn't run.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:20:25Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kube-prometheus-stack
**Which version of the chart**:
15.4.4
**What happened**:
unable to admit pod: [spec.initContainers[0].securityContext.runAsNonRoot
**What you expected to happen**:
Addition of a different servicaccount for grafana with a PSP that allows root access or privilege escalation, so that the init container can do its chowning
**How to reproduce it** (as minimally and precisely as possible):
Enable PodSecurityPolicy on the cluster and deploy the chart.
**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```yaml
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
grafana:
  rbac:
    pspEnabled: true
  adminPassword: 2d13e45a3ad3b77ec9aec7
  persistence:
    type: pvc
    enabled: true
    accessModes:
      - ReadWriteMany
    size: 20Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
```

**The helm command that you execute and failing/misfunctioning**:

For example:

```console
$ helm install --repo https://prometheus-community.github.io/helm-charts --version 15.4.4 prometheus kube-prometheus-stack --values values.yml
```

**Helm values set after installation/upgrade:**

```console
$ helm get values prometheus
USER-SUPPLIED VALUES:
grafana:
  adminPassword: 2d13e45a3ad3b77ec9aec7
  persistence:
    accessModes:
    - ReadWriteMany
    enabled: true
    finalizers:
    - kubernetes.io/pvc-protection
    size: 20Gi
    storageClassName: longhorn-rep1
    type: pvc
  rbac:
    pspEnabled: true
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: longhorn-rep1
```

**Anything else we need to know**:

To work around the issue I changed the entry MustRunAsNonRoot to RunAsAny with `kubectl edit psp prometheus-grafana`
```yaml
...
  runAsUser:
    rule: RunAsAny
...
```
