### ISSUE TITLE
[prometheus-kube-stack] - Autodiscover not scraping Ceph/Rook mgr's

### ISSUE THREAD

**Issue by skyfox675** [prometheus-community/helm-charts#952]
**Describe the bug**
Prometheus instance deployed by this helm chart's operator does not scrape Ceph metrics from the mgr's service.

**Version of Helm and Kubernetes**:
K8s client: v1.19
K8s cluster: v1.19

Helm Version:
v3.5.2

**Which chart**: prometheus-community/kube-prometheus-stack

**Which version of the chart**: 15.4.2 

**What happened**: Metrics for Ceph are not shown in the dropdown metrics explorer

**What you expected to happen**: Ceph metrics such as `ceph_health_status` to exist in the dropdown

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml**:
``` yaml
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
grafana:
  enabled: false  
prometheus:
  prometheusSpec:
    remoteWrite:
      - url: http://localhost:8005/workspaces/xxxxxxapi/v1/remote_write
    containers:
    - image: public.ecr.aws/aws-observability/aws-sigv4-proxy:1.0
      name: aws-proxy-sidecar
      args:
      - --name
      - aps
      - --region
      - us-east-1
      - --host
      - aps-workspaces.us-east-1.amazonaws.com
      - --port
      - :8005
      ports:
      - name: aws-sigv4-proxy
        containerPort: 8005
  serviceAccount:
    name: xxxxxxx
    annotations:
      eks.amazonaws.com/role-arn: xxxxxxxxxx
```

**Comment by skyfox675** [comment]
Was anyone able to take a look at this?

**Comment by zamnuts** [comment]
Do you have a `PrometheusRule` CRD and/or a `ServiceMonitor` CRD for ceph? I deploy ceph via rook, which has the option to enable prometheus monitoring within the cluster CRD (rook makes it easy!):

```
# relevant snippet
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  monitoring:
    enabled: true
    rulesNamespace: rook-ceph
```

If you're not running ceph via rook, here's what happens behind the scenes:

The rook-ceph-operator creates the following `PrometheusRule` (you can see the actual rules at [rook/rook@v1.6.5 cluster/examples](https://github.com/rook/rook/blob/v1.6.5/cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml) and [operator implementation within ceph/cluster/mgr/mgr.go](https://github.com/rook/rook/blob/e06c36dbc9643d5bde0ee7feade967b26b000ea3/pkg/operator/ceph/cluster/mgr/mgr.go#L462-L482)):

```
# k get prometheusrules prometheus-ceph-v15-rules -n rook-ceph -oyaml
# partial snippet
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    prometheus-operator-validated: "true"
  generation: 1
  labels:
    prometheus: rook-prometheus
    role: alert-rules
  name: prometheus-ceph-v15-rules
  namespace: rook-ceph
```

The operator also creates a `ServiceMonitor` ([rook/rook@1.6.5 cluster/examples](https://github.com/rook/rook/blob/v1.6.5/cluster/examples/kubernetes/ceph/monitoring/service-monitor.yaml) and [operator implementation within ceph/cluster/mgr/mgr.go](https://github.com/rook/rook/blob/e06c36dbc9643d5bde0ee7feade967b26b000ea3/pkg/operator/ceph/cluster/mgr/mgr.go#L437-L459)):
```
# k get servicemonitor rook-ceph-mgr -n rook-ceph -oyaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 1
  labels:
    team: rook
spec:
  endpoints:
  - interval: 5s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-mgr
      ceph_daemon_id: a
      rook_cluster: rook-ceph
```

The operator also adds scrape/port annotations on the ceph pod (I'm pretty sure these aren't used anymore, but just in case I'm including this info):
```
# kgp -n rook-ceph -l app=rook-ceph-mgr -oyaml
# partial snippet
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/port: "9283"
    prometheus.io/scrape: "true"
```

Finally `ceph_health_status` is available:
```
$ curl 'http://localhost:9090/api/v1/query?query=ceph_health_status'                     
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"ceph_health_status","container":"mgr","endpoint":"http-metrics","instance":"10.*.*.*:9283","job":"rook-ceph-mgr","namespace":"rook-ceph","pod":"rook-ceph-mgr-a-***-***","service":"rook-ceph-mgr"},"value":[1625272884.023,"1"]}]}}
```
Note that port `9283` is indeed the ceph mgr exporter per [prometheus' documented default port allocations](https://github.com/prometheus/prometheus/wiki/Default-port-allocations).

---

Additionally, for prometheus-stack, allow the prometheus operator to discover rules and service monitors in all (or select) namespaces. IIRC by default it only discovers in its own namespace:
```
prometheus:
  prometheusSpec:
    ruleNamespaceSelector:
      matchLabels: {} # any: true
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector:
      matchLabels: {} # any: true
    serviceMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs: []
```

If ceph is hosted external to the kubernetes cluster prometheus-stack is deployed, then you'll need a `ServiceMonitor`, `Service`, and `Endpoint` declared which correspond to the external ceph-mgr.
