### ISSUE TITLE
[kube-prometheus-stack] alertmanager spec: add additionalAlertmanagerSecretsAnnotations

### ISSUE THREAD

**Issue by notjames** [prometheus-community/helm-charts#956]
We are currently using kube-prometheus-stack with https://github.com/banzaicloud/bank-vaults and the [https://banzaicloud.com/docs/bank-vaults/mutating-webhook/](vault-secrets-webhook) mutator to affect k8s secrets, configmaps, and pods. In order for inline secrets mutations (in other words, mutation of string pointers to vault secrets within a kubernetes secret) to properly mutate, k8s secrets one wants to get mutated must be annotated IE:

```yaml
     apiVersion: v1
     kind: Secret
     metadata:
       name: some_name 
       annotations:
         vault.security.banzaicloud.io/vault-addr: 'https://vault.vault:8200'
         vault.security.banzaicloud.io/vault-path: kubernetes
         vault.security.banzaicloud.io/vault-role: default
         vault.security.banzaicloud.io/vault-skip-verify: 'false'
         vault.security.banzaicloud.io/vault-tls-secret: vault-tls
         vault.security.banzaicloud.io/inline-mutation: 'true'
     data:
       config.yaml: <base64 representation of `config.yaml`>
```

An example of the `config.yaml` would be something like:
```
config:
  global:
    resolve_timeout: 5m
    smtp_auth_password: ${vault:secret/data/path/to/foo#secret}
    smtp_auth_username: ${vault:secret/data/path/to/foo#username}
...
```

Currently we put the AM configuration in the values.yaml file and let the chart create the secret containing that config in a k8s secret. The desire is that the chart will automatically annotate that secret given the annotations specified in the values.yaml file in the same manner as `additionalPrometheusSecretsAnnotations`.

My read of the example values.yaml file for the alertmanager spec doesn't surface this property it seems. The prometheus spec has `additionalPrometheusSecretsAnnotations`, but no such thing for alertmanager.

**Is your feature request related to a problem? Please describe.**
A "native" ability to annotate secrets with arbitrary necessary annotations would be super appreciated.

**Describe the solution you'd like**
Please add something like `additionalPrometheusSecretsAnnotations` to the alertmanager chart.

**Describe alternatives you've considered**
I'll need to annotate the AM configuration secret after it's created post chart-installation

**Comment by notjames** [comment]
hmm. I was going to work on submitting a PR for this but looking through the chart I see:

```bash
at 09:28:39 ❯ grep additionalPrometheus -r .
./prometheus/additionalScrapeConfigs.yaml:{{- if .Values.prometheus.prometheusSpec.additionalPrometheusSecretsAnnotations }}
./prometheus/additionalScrapeConfigs.yaml:{{ toYaml .Values.prometheus.prometheusSpec.additionalPrometheusSecretsAnnotations | indent 4 }}
./prometheus/additionalAlertRelabelConfigs.yaml:{{- if .Values.prometheus.prometheusSpec.additionalPrometheusSecretsAnnotations }}
./prometheus/additionalAlertRelabelConfigs.yaml:{{ toYaml .Values.prometheus.prometheusSpec.additionalPrometheusSecretsAnnotations | indent 4 }}
./prometheus/additionalPrometheusRules.yaml:{{- if or .Values.additionalPrometheusRules .Values.additionalPrometheusRulesMap}}
./prometheus/additionalPrometheusRules.yaml:{{- if .Values.additionalPrometheusRulesMap }}
./prometheus/additionalPrometheusRules.yaml:{{- range $prometheusRuleName, $prometheusRule := .Values.additionalPrometheusRulesMap }}
./prometheus/additionalPrometheusRules.yaml:{{- range .Values.additionalPrometheusRules }}
./prometheus/additionalAlertmanagerConfigs.yaml:{{- if .Values.prometheus.prometheusSpec.additionalPrometheusSecretsAnnotations }}
./prometheus/additionalAlertmanagerConfigs.yaml:{{ toYaml .Values.prometheus.prometheusSpec.additionalPrometheusSecretsAnnotations | indent 4 }}
```

```yaml
at 09:29:15 ❯ \cat ./prometheus/additionalAlertmanagerConfigs.yaml
{{- if and .Values.prometheus.enabled .Values.prometheus.prometheusSpec.additionalAlertManagerConfigs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-prometheus-am-confg
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
{{- if .Values.prometheus.prometheusSpec.additionalPrometheusSecretsAnnotations }}
  annotations:
{{ toYaml .Values.prometheus.prometheusSpec.additionalPrometheusSecretsAnnotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus-am-confg
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
data:
  additional-alertmanager-configs.yaml: {{ toYaml .Values.prometheus.prometheusSpec.additionalAlertManagerConfigs | b64enc | quote }}
{{- end }}
```

So perhaps my request should be an update to values.yaml or documentation for `.Values.prometheus.prometheusSpec.additionalAlertManagerConfig` usage as this doesn't seem to be referenced in the `values.yaml`
