### ISSUE TITLE
[prometheus-kube-stack] kube-proxy metrics status with connection refused.

### ISSUE THREAD

**Issue by shan100github** [prometheus-community/helm-charts#977]
I did set an EKS environment monitoring with prometheus-kube-stack. Notices prometheus-kube-proxy metrics are down with `10249: connect: connection refused` displayed in Prometheus>Status>Targets displayed always.

**Version of Helm and Kubernetes**:
Helm Version:
```console
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: v1.18.8-eks-7c9bda
Server Version: v1.18.9-eks-d1db3c
```

**Which version of the chart**:
```
kube-prometheus-stack-15.4.6
```

**What happened**:
Always `10249: connect: connection refused` displayed in Prometheus>Status>Targets and not able to monitor metrics of kube-proxy

**Changed values of values.yaml** (only put values which differ from the defaults):
```
## Component scraping kube proxy
##
kubeProxy:
  enabled: true

  ## If your kube proxy is not deployed as a pod, specify IPs it can be found on
  ##
  endpoints: []
  # - 10.141.4.22
  # - 10.141.4.23
  # - 10.141.4.24

  service:
    enabled: true
    port: 10249
    targetPort: 10249
    selector:
      k8s-app: kube-proxy

  serviceMonitor:
    enabled: true
    ## Scrape interval. If not set, the Prometheus default scrape interval is used.
    ##
    interval: ""

    ## proxyUrl: URL of a proxy that should be used for scraping.
    ##
    proxyUrl: ""

    ## Enable scraping kube-proxy over https.
    ## Requires proper certs (not self-signed) and delegated authentication/authorization checks
    ##
    https: false

    ## 	metric relabel configs to apply to samples before ingestion.
    ##
    metricRelabelings: []
    # - action: keep
    #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
    #   sourceLabels: [__name__]

    # 	relabel configs to apply to samples before ingestion.
    ##
    relabelings: []
    # - action: keep
    #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
    #   sourceLabels: [__name__]
```

**Helm values set after installation/upgrade related to  kubeProxy setting**

```console
helm get values kube-prom

kubeProxy:
  enabled: true
  endpoints: []
  service:
    enabled: true
    port: 10249
    selector:
      k8s-app: kube-proxy
    targetPort: 10249
  serviceMonitor:
    enabled: true
    https: false
    interval: ""
    metricRelabelings: []
    proxyUrl: ""
    relabelings: []
```
