### ISSUE TITLE
[prometheus-kube-stack] prometheus-operator pod doesn't start on EKS, Calico and hostNetwork: true

### ISSUE THREAD

**Issue by r-erema** [prometheus-community/helm-charts#987]
Hi! According to [documentation](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1494) in the case of using AWS EKS and Calico plugin parameter `hostNetwork` has to be `true`

```
kubectl get pods -n monitoring
NAME                                                   READY   STATUS             RESTARTS   AGE
prometheus-grafana-5dbff499ff-4k24x                    2/2     Running            0          3m35s
prometheus-kube-prometheus-operator-5668ff99fb-g225t   0/1     CrashLoopBackOff   5          3m35s
prometheus-kube-state-metrics-685b975bb7-7v4xt         1/1     Running            0          3m35s
prometheus-prometheus-node-exporter-649rs              1/1     Running            0          3m36s
prometheus-prometheus-node-exporter-kkqht              1/1     Running            0          3m35s
prometheus-prometheus-node-exporter-n9k25              1/1     Running            0          3m35s
prometheus-prometheus-node-exporter-plxll              1/1     Running            0          3m35s
```

Here is a log, surprisingly small and not much informative:
```
nbe-042-71b:kubernetes roman.erema$ kubectl logs prometheus-kube-prometheus-operator-5668ff99fb-g225t -n monitoring
level=info ts=2021-05-20T11:56:28.00452713Z caller=main.go:294 msg="Starting Prometheus Operator" version="(version=0.47.0, branch=refs/tags/pkg/client/v0.47.0, revision=539108b043e9ecc53c4e044083651e2ebfbd3492)"
level=info ts=2021-05-20T11:56:28.004597371Z caller=main.go:295 build_context="(go=go1.16.3, user=simonpasquier, date=20210413-15:45:09)"
```

BTW: in case `hostNetwork: false`, the pod starts successfully

I install the release in this way:
```
helm upgrade -i prometheus prometheus-community/kube-prometheus-stack \
    --set prometheusOperator.hostNetwork=true \
    --set prometheusOperator.logLevel=all \
    -n monitoring
```

Could you tell me what the problem might be?

**Comment by tylerku** [comment]
Hey @r-erema, when I try to install this chart on my eks cluster with the command 
```
helm install prometheus prometheus-community/kube-prometheus-stack -f my-values.yaml
```
and where my `my-values.yaml` contains:

```
prometheusOperator:
  hostNetwork: true
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: my-job
        scrape_interval: 15s
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - my-namespace
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: pod
        - source_labels: [__address__]
          action: replace
          regex: ([^:]+)(?::\d+)?
          replacement: ${1}:3000
          target_label: __address__
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: my-pod-name

```
none of the kubernetes objects start running and I get this error (after a long hanging period):

```
Error: failed pre-install: timed out waiting for the condition
```

Have you experienced this or have any advice on why it might be happening on my cluster?

**Comment by r-erema** [comment]
@tylerku Do you need more details? Which ones? I'll be glad to provide

**Comment by tylerku** [comment]
I just want to get the prometheus stack running and scraping a service I have running in a different namespace on my eks cluster by using this helm chart. Could you help me out with that? I'd really appreciate it.

**Comment by r-erema** [comment]
@tylerku Does it work without specifying the values file(my-values.yaml in your case)?

**Comment by tylerku** [comment]
@r-erema I get the same error when I don't include the values file.

**Comment by tylerku** [comment]
@r-erema When you run `kubectl describe pod <your operator pod>` What is the output at the bottom in the `Events:` section

**Comment by yuriipolishchuk** [comment]
I had similar issue. 

Here's my config that worked with EKS and Calico CNI:
```
prometheusOperator:
  hostNetwork: true
  service:
    type: NodePort
  tls:
    internalPort: 10252
```

Overriding `.Values.prometheusOperator.tls.internalPort` helped. The root cause is  that kubelet is already listening on port `10250`. Please note that `service.type: NodePort` is also required.
