### ISSUE TITLE
[prometheus-pushgateway] Please make ClusterIP optional

### ISSUE THREAD

**Issue by yannickkirschen** [prometheus-community/helm-charts#998]
**Is your feature request related to a problem? Please describe.**
We have the issue that the ClusterIP flag added in f183c48e91bc99e025e11f5a708d64615b4799ae causes an error when updating the deployment. In the services we define ourselves, we don't set a ClusterIP.

**Describe the solution you'd like**
It would be cool to make the ClusterIP optional. Something like:

**values.yaml**
```yaml
service:
    clusterIP:
        enabled: false
        ip: ""
```

**service.yaml**
```yaml
spec:
    {{- if .Values.service.clusterIP.enalbed -}}
    clusterIP: {{ .Values.service.clusterIP.ip }}
    {{- end -}}
```
